### ISSUE TITLE
Can't remove main page from blank template

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#100]
**Repro**

- New template project
- Blank
- MVVM Basic
- Add a new map page

**Expected**
Should be able to remove the Main/Blank page from the list

**Actual**
the 'remove' button doesn't allow the removal of the Main/Blank page. But I can remove the added map page.

But I wanted to create a single app with just a map page in it 😢

**Comment by mvegaca** [comment]
I've fix this issue on dev branch. Now any  page can be set as Home page. Using the new summary options menu, the templates has different options (Set as Home, Remove, Rename, Move Up and Move Down). Issue labeled as "Can Close Out Soon"

**Comment by ralarcon** [comment]
The Wizard allows now to change the Main / Default page. Verified in nightly build 0.14.17146.65001.

Closing this issue as the #406 is already fixed too (even considering #406 fix will be available in the following Nightly build).
