### ISSUE TITLE
simplify summary for right-click add

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1028]
This is redundant.  I would drop the full sentence area.  We say it is a new file in multiple spots and then the file is name is highlighted in multiple spots

![image](https://user-images.githubusercontent.com/1462282/29855295-99bc573c-8cff-11e7-812c-efe3c36ba9c7.png)

**Comment by mvegaca** [comment]
Updated on #1206

**Comment by sibille** [comment]
Verified on dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.2
