### ISSUE TITLE
Info button hover state has oval

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1029]
while testing #748, some of the "Info" buttons had an oval versus a proper circle

![image](https://user-images.githubusercontent.com/1462282/29855440-b3bc6978-8d00-11e7-8bcc-4b8d233d9e35.png)

**Comment by mvegaca** [comment]
Fixed on #1038 - Fix focus visual state on information button

**Comment by mvegaca** [comment]
Fixed with 7faca3545369d32d917bda33872549b2a76f39d1

**Comment by mvegaca** [comment]
Checked on version
Wizard: 0.14.17244.65002
Templates: 0.14.17244.2
