### ISSUE TITLE
Publish Templates build broken after Templatex rename

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1032]
The script code\_build\PackAndSign-Content.ps1 have a reference to our core library to allow to create the templates package. After the renaming the scripts fails.

**Comment by crutkas** [comment]
what could have been done to prevent that?  I renamed so wondering how i could have done better

**Comment by ralarcon** [comment]
I think is just to be aware... but it is difficult as it is referenced from the Powershell (weak refrence) we use in the build process to create the package... but it was simple to fix.
