### ISSUE TITLE
Create tool for analyzing/verifying templates

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1037]
With more people creating templates and the expectation (and hope) that this will continue, it will be useful to have a tool that can do some level of automated analysis of generated templates.

The aim here is to spot any mistakes, errors, or potential issues quickly and provide some confidence that the template is correct.

Not a substitute to manual checking and other testing of templates but a compliment to it.

This should also integrate with the coded tests that we currently also have but also be able to be run separately.

X-Ref #919

I suspect that any such tool will be added to over time but having something to get us started would be a bonus.

**Comment by ralarcon** [comment]
We had in mind an extension for Visual Studio Code to allow users authoring templates to make checks... but nothing started yet.

**Comment by crutkas** [comment]
great ideas @ralarcon and @mrlacey!

**Comment by mrlacey** [comment]
I want something scriptable for automated tests as well as well as stand alone and tied to the core code base as much as possible to avoid issues with maintaining concurrent versions.
A VSCode extension may be useful for some in creating templates but I'm aiming for something more broadly applicable.
I already have my own tool for validating JSON that I'll make public and use as part of this.

**Comment by ralarcon** [comment]
Good approach. The extension for the VSCode could be implemented "on-top", isn't it?

**Comment by mrlacey** [comment]
Also, need to update https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/templates.md

**Comment by mrlacey** [comment]
For the initial version, I'm not planning on supporting localized output.
As this isn't part of the wizard and won't be included in anything that's shipped I'm assuming this won't be an issue. 
If translations must be supported I'm hoping this can be added in a later version.
Adding this in at this stage will delay the creation of this tool. I think it's more important to see if others find it useful before spending time on globalization.

**Comment by mrlacey** [comment]
For the initial version, I'm planning the following:
- Ensure that template.json contains only valid properties
- Ensure the values specified for properties in template.json (will catch typos, etc.)
- Ensure files referenced in template.json exist
- Ensure all Tag values are valid/appropriate
- Ensure naming standards for VB templates are followed
- Ensure all defined symbols are known/supported
- Check for unused files in the template
- Check for uniqueness of template identities
- Check that defined dependencies exist
- Check for identical files in multiple templates (that could be combined)

Intended to be easy to extend with other checks as needed in the future.

This list of functionality is based mostly on things I've got wrong, common typos, and issues I've discovered with templates. My intention and expectation is that these tests will be extended as necessary in the future if this tool and tests are found to have value.
There are also some hard-coded lists of values that will have to be changed and extended in future as more functionality is supported.

**Comment by ralarcon** [comment]
I think is a good initial approach. To need to "modify" the code / hard-coded values when something new rise up is not a problem for me.

We were thinking, apart from these kind of checks, in a tool that would give a way to represent the composition  (and maybe the post actions execution) of a certain page / feature using a concrete framework and project type, that is a way to "see" what templates are being composed and what is the generation result.  In that sense, I think this is "other" tool or something we can explore in our end while you progress with the analyzer / checker... then maybe we can "merge" both tools... 

What do you think @mrlacey?

**Comment by mrlacey** [comment]
@ralarcon

> We were thinking, apart from these kind of checks, in a tool that would give a way to represent the composition (and maybe the post actions execution) of a certain page / feature using a concrete framework and project type, that is a way to "see" what templates are being composed and what is the generation result. In that sense, I think this is "other" tool or something we can explore in our end while you progress with the analyzer / checker... then maybe we can "merge" both tools...

This seems like a very different tool which can and should be developed separately. It sounds like a way to visualize how different templates are chosen based on the options selected in the wizard. I've also thought about having such a tool as it would potentially be useful but it seems like more work than I have personally wanted to spend on something as the actual value of it seems small.
I look for ward to seeing how this is spec'd out and how the value & effort is evaluated.

**Comment by ralarcon** [comment]
Sure, anyway this is not something going to be faced immediatly... let see how we can face this.

**Comment by mrlacey** [comment]
Merged into dev so closing
