### ISSUE TITLE
Set default wizard window based on Dpi information

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1040]
Working with #721 I've calculated the font size in relation with Dpi. We must calculate default wizard window based on Dpi, because when the wizard is opened in a high dpi screen, wizard window is bigger than the laptop screen.

**Comment by mvegaca** [comment]
I've set 1.4 milestone but I'll try to implement that on 1.3

**Comment by crutkas** [comment]
lets stabilize 1.3 and do this for 1.4

**Comment by mvegaca** [comment]
Added on #1203

**Comment by mvegaca** [comment]
PR Updated #1203

**Comment by ralarcon** [comment]
Verified in nightly version
Wizard: 0.14.17284.65001
Templates: 0.14.17284.7
