### ISSUE TITLE
A better Wizard notifications and warnings system

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1044]
* **Overview:** We need to revisit how errors and information is being displayed to users.  Current VM is unclear what exactly happens if, as a dev, if i called StatusViewModel.Error("foo", true, 15); versus StatusViewModel.Error("foo", false, 15);. Or StatusViewModel.Error("foo", false, 0); and then called StatusViewModel.Error("bar", false, 0); i don't know what exactly would happen / should happen.

When i think about a dialog as well, it is either Transient or Persistent dialog

- A transient message disappears based on time (or something else)
- A persistent message would stay up until a direct action corrects it (error fixed, user closed, ...)

When would either of these states not be cleared out when it goes away or another warning super-succeeds it. I think the type of dialog also would be thought about for our we handle our markdown modals for. (that is a different topic however).

One idea @mvegaca has is to have a better unified message display method, that allows having a status pool to read all notifications, with some improvements. If there are one status showing and one thread wants to show a new status, this new status keep in a pool until the current message is autohide or closed, defining different priorities.

* **Links:** #757, #596, #1017

**Comment by ralarcon** [comment]
Does this make sense to be moved to the backlog and delay this implementation to be aligned with the wizard re-design?

**Comment by crutkas** [comment]
Sure

**Comment by mrlacey** [comment]
moving to 2.0 to make sure this is included as part of the redesign work

**Comment by mvegaca** [comment]
The new NotificationsControl is part of the new wizard redesign, here is a summary of control behaviors.
- You can add notifications by calling `NotificationsControl.Instance.AddNotification(newNotification);`
- Notification can handle 3 types of auto-hide: None, short timer, long timer.
- Notifications contain a category that allows a notification clear the same category notifications.
- Different notifications from different categories can be added and will be processed as soon as current notification is closed.
- Notifications are using Visual Studio InfoBar category colors and one xaml icon.

This Issue can be closed.
