### ISSUE TITLE
Update UWP Community Toolkit to v2.0

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1045]
The UWP Community Toolkit has just released version 2.0 ([announcement](https://blogs.windows.com/buildingapps/2017/08/30/uwp-community-toolkit-v2-0/))
We need to update templates to use this new version.

**Comment by crutkas** [comment]
Note: toolkit takes UWP NuGet package 5.3.3

**Comment by crutkas** [comment]
Got this working, adds some compile time as both nuget packages need to be fetched.

![image](https://user-images.githubusercontent.com/1462282/29898941-685a6e56-8d9d-11e7-9c31-ecec99192c19.png)

**Comment by crutkas** [comment]
@mvegaca, the PR is ready but we moved this to 1.4 due to the the need to update Microsoft.NETCore.UniversalWindowsPlatform and the added first time run time it would add on a new box

**Comment by sibille** [comment]
Master Detail is referencing version 1.5

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
