### ISSUE TITLE
Error Learn More button on Changes Summary window

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1051]
Open one project and add a WTS Page (right click). On Changes Summary window click on "learn more" button. Display error:

![image](https://user-images.githubusercontent.com/12777039/29931264-08a0affa-8e71-11e7-8226-06eb059e5e58.png)

Only in dev-nightly version.

## System

* **VS Version: 15.2 (26430.15)
* **WTS Wizard Version:0.14.17243.65005 (nightly)
* **WTS Template Version:0.14.17243.13

**Comment by crutkas** [comment]
did our automated tests catch this failure?

**Comment by dgomezc** [comment]
Tests passed correctly, it was a problem in the build to publish the extension.

**Comment by mrlacey** [comment]
@dgomezc I think @crutkas was asking why a test didn't catch this. Could we add a test to detect this happening again? If this is down to a configuration issue, how do we avoid such an issue occurring again?

**Comment by ralarcon** [comment]
Not possible as the value is set / not set by the build server. 

We can improve the handling of the value (protect against invalid values) and give a better error message. Then we could unit test the new code.

What we currentluy do is basically concatenate the url configured with the page name we want to show in the info. If we configure wrong data while creating the extension in the build server, not unit test will catch that.

**Comment by dgomezc** [comment]
If you think is worthy, I can add a method to grab the value from the configuration and validate that it is good, then raise an exception if not. We can use that method when the doc url is required

**Comment by mrlacey** [comment]
>  If we configure wrong data while creating the extension in the build server, not unit test will catch that.

Is there something else we can do to verify the configuration of the build server?

**Comment by ralarcon** [comment]
We can try to figure out something...

**Comment by sibille** [comment]
Checked on pre
Wizard: 0.8.17248.4
Templates: 0.8.17248.4
Checked on dev-nightly
Wizard: 0.14.17248.65001
Templates: 0.14.17248.4
