### ISSUE TITLE
Major vs minor version increment as we approach Fall Creators Update

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1062]
As we approach Fall Creators Update, we'll be transitioning from supporting Anniversary Update and Creators Update to Creators Update and Fall Creators Update.

Currently the 1.4 release is slotted to be side by side with the Fall Creator's Update release but should this actually be the 2.0 release?

To me, while I believe the 1.4 release isn't a larger release, a Major increase rev would show that something has moved and would allow us to move on past the possible breaking changes of dropping support for Anniversary Update when we may start requiring templates to use conditional XAML to support Fluent

**Comment by mrlacey** [comment]
If this release becomes the one that also adds two more frameworks and support for VB, then that becomes a very big, obvious set of changes that warrant a major number bump.
And if the VS changes tie in too, then even more so.

**Comment by crutkas** [comment]
I think Caliburn will come in 1.4, Prism 1.5/6 timeframe IMO unless Lee and folks are much more bad ass than my gut estimates.

When do you feel VB support can be added?

**Comment by mrlacey** [comment]
I was originally aiming for the end of Sept for VB but that's going to slip due to spending the last two weeks dealing with the consequences of other changes.

Bumping the major version at the same time as the UI is updated might also be a good idea.

**Comment by crutkas** [comment]
lets say UI adjustment + major feature for 2.0 bump.
