### ISSUE TITLE
Broken NavPanel item highlighting in latest dev build

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1078]
The highlighting of the text and icon in the Nav Menu of the currently displayed item has been broken.
In the below, the circled item should use the accent color, like the other version in the image.

![image](https://user-images.githubusercontent.com/189547/30080547-e0526d86-927b-11e7-9c06-a138e3b69c68.png)

Above created with a MVVM Basic project

    <genTemplate:Item Name="wizardVersion" Version="0.14.17247.65001" />
    <genTemplate:Item Name="templatesVersion" Version="0.14.17248.13" />

**Comment by mvegaca** [comment]
Fixed on #1083

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65002
Templates: 0.14.17249.10
