### ISSUE TITLE
Right-Click page has inconsistent line wrapping in summary areas

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1079]
Go to Right-Click > Add template on existing project

Author is shortened with an elipsis

![image](https://user-images.githubusercontent.com/189547/30081766-5c7daa5c-9280-11e7-863f-2266310dd445.png)

Licenses are wrapped

![image](https://user-images.githubusercontent.com/189547/30081836-978a61d0-9280-11e7-8d61-d4f168ff7a63.png)

Should be consistent in wrapping.

**Comment by mvegaca** [comment]
Thanks Matt, fixed on #1081

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65002
Templates: 0.14.17249.10
