### ISSUE TITLE
Review SettingsPage postactions

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1082]
I think that those post actions are not necessaries.

\_composition\FRAMEWORK_TYPE\Page.Settings.AddShellThemeSupport_SplitView\ViewModels\ShellNavigationItem_postaction.cs

**Comment by mrlacey** [comment]
The code in these templates enables the changing of the foreground of the selected item in the NavPanel menu.  Without this, they won't reflect the theme and accent colors correctly.
Of course, there's no need for guesswork. Remove them and check the same behavior exists in the generated code.

**Comment by mvegaca** [comment]
I'm going to think about that and review if it is optimizable

**Comment by mvegaca** [comment]
I've commented postaction additions and I still thinking that this template is not necessary
- ThemeSelectorService.GetSystemControlForegroundForTheme method is also returning the same value "ThemeControlForegroundBaseHighBrush".
 - Commenting OnThemeChanged SelectedForeground updates navigation pane colors still updating because the current foreground is a theme resource, not a fixed value.

Attached App14 that has those code lines commented. I've also tried to comment template filter to not apply this template and resulting code works as expected.

"wts.compositionFilter": "$framework == MVVMBasic & identity == wts.Page.Settings & $projectType == **SplitView2**"

[App14.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/1292106/App14.zip)

**Comment by mvegaca** [comment]
Can you review that @mrlacey?

**Comment by mrlacey** [comment]
Yes, it seems to work without that code.
As it was originally added before we had support for the "Windows Default" theme I'm guessing the changes made to support the default theme made this redundant.
Looks safe to remove.

Side question (for reflection as much as anything) is there a way we could have detected this redundant code automatically?

**Comment by mvegaca** [comment]
I think it's difficult to do some automatic test here :S

**Comment by mvegaca** [comment]
Templates updated on #1136

**Comment by sibille** [comment]
Verified on dev-nightly:
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
