### ISSUE TITLE
 Narrator text for hamburger menu main button is not customizable

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1084]
In the main button of the hamburger menu the narrator says "Main Button". This text is not customizable.

Customization depends on UWP Community Toolkit team. Here is an [issue](https://github.com/Microsoft/UWPCommunityToolkit/issues/1329) with the description.

We have proposed a [PR](https://github.com/Microsoft/UWPCommunityToolkit/pull/1418) and are waiting to be reviewed / merged.

Narrator general issue X-Ref: #494.

**Comment by mrlacey** [comment]
As already said elsewhere.
The temporary fix for this is to modify the template in the code we generate so the hard coded text can be replaced with something else.
We can release templates without this issue in the generated code so that we can create code that is fully globalized.

**Comment by ralarcon** [comment]
I think this is somehting we can live with unless the accesibility guys force us to fix it before UWP Community Toolkit fix it.

@crutkas what do you think?

**Comment by crutkas** [comment]
i think it is livable until they push a fix.  @nmetulev is this something we can get prioritized for 2.1?  It is blocking accessibility.

**Comment by nmetulev** [comment]
Yes we can, looking into doing this the same way as NavigationView to minimize breaking changes when moving to NavigationVIew.

**Comment by nmetulev** [comment]
To update this thread, the NavigationView also does not have a way to customize the Narrator Text, the properties are already localized. Anything we add to the HamburgerMenu will not work for NavigationView, so don't believe it's a good idea to add new properties seeing how the HamburgerMenu is getting deprecated in favor for the NavigationView.

**Comment by nmetulev** [comment]
Good news is, the HamburgerMenu will use the NavigationView when running on FCU starting with 2.1 :)

**Comment by crutkas** [comment]
AWESOME!  once this is stable, we should test again the pre-release

**Comment by nmetulev** [comment]
It's already in our pre-release packages: https://dotnet.myget.org/gallery/uwpcommunitytoolkit and ready to be tested

**Comment by nmetulev** [comment]
The docs have more info about this too: https://github.com/Microsoft/UWPCommunityToolkit/blob/master/docs/controls/HamburgerMenu.md#navview , there is a new property called UseNavigationViewWhenPossible to enable this

**Comment by dgomezc** [comment]
We still cannot customize the narrator text of the button for the HamburgerMenu control (considering only the customization for the NavigationView part).
 
I've been testing with a NavigationView control (alone), setting the button style using "PaneToggleButtonStyle" property, but when setting the AutomationProperties.Name, or ToolTipService.ToolTip properties, nothing happens, so I think it's the control itself that internally changes these properties (The button tooltip shows "Open Navigation" or "Close Navigation" when opening or closing the navigation panel).
 
Investigating NavigationView's default style, the button has an identifier (x:name="TogglePaneButton"), that when changing it manually, does not work correctly, but allows configure the AutomationProperties.Name, or ToolTipService.ToolTip properties correctly, so they confirm my suspicions that it´s the control that internally sets those properties.
 
We need to double check with the team and see if it´s possible customize this behavior.

**Comment by nmetulev** [comment]
The NavigationView is already localized by the platform team. You can test it by downloading a specific language to your device and changing the default language of the app. I believe this issue can be closed.

**Comment by ralarcon** [comment]
Closing now, I'll update the thread when knowing about customization.
