### ISSUE TITLE
Remove duplication in UriSchemeExamplePage templates

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1095]
As identified [here](https://github.com/Microsoft/WindowsTemplateStudio/issues/506#issuecomment-327506989) in #506

These files only differ by one line

- [Feature.UriSchemeExamplePage_Activation_Blank_SplitView](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/_composition/MVVMBasic/Feature.UriSchemeExamplePage_Activation_Blank_SplitView/Activation/SchemeActivationHandler_postaction.cs)
- [Feature.UriSchemeExamplePage_Activation_TabbedPivot](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/_composition/MVVMBasic/Feature.UriSchemeExamplePage_Activation_TabbedPivot/Activation/SchemeActivationHandler_postaction.cs)

This wasn't originally done due to the perceived complexity of merge file as the line that differs is deep within the method.  There may be an easier way of doing this though that wasn't obvious to the original author.

**Comment by mrlacey** [comment]
Please note that this is not a must fix. 
If someone else looks at this and thinks the current code/template is good enough then just close this with no changes

**Comment by sibille** [comment]
I think both options are valid, one leaves the method together and uses less composition, the other makes heavier use of composition and avoids some more code duplication. There are more examples in the templates where we decided not to use composition in favor of template understandability
