### ISSUE TITLE
Navigation service improvements for VB

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1096]
Align VB Navigation Service with C#, see #1012

**Comment by mrlacey** [comment]
possibly see also https://github.com/Microsoft/WindowsTemplateStudio/pull/1092/commits/bbe0d2266380f38591456dcd5f30e05b7613a2d7

**Comment by mrlacey** [comment]
#863 has been moved to the 1.5 milestone but leaving this here as hope to have this and some of the other template work done in the 1.4 timeframe

**Comment by mrlacey** [comment]
Closing as now made into the branch with other VB work. Will likely be many weeks before can "properly" close but is in a good enough state for now.
