### ISSUE TITLE
Make it easier to manually test generated code output

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#1100]
Manually testing generated code, variations thereof, doing Right-Click add of an item in specific circumstances, and reviewing documentation for adjusting generated code can be very time consuming to generate all the project variations.
It would be really useful to make this faster by adjusting VSEmulator to be able to do some of the slow, repetitive work.

I'm imagining something where a folder to generate the solution and the name of the solution could be specified (similar to when creating a single project) and then a dynamically generated grid is displayed to allow control of all that is included in the generated solution.
Something like this:

![annotated-wts-solution-generation-grid](https://user-images.githubusercontent.com/189547/30158016-bf9edf20-93bb-11e7-8b25-8bb279234ed1.png)

_(Annotated, in red, to provide additional insight but only an early concept.)_

It would generate multiple projects within the defined solution with projects named as a combination of project type and framework. (e.g. NavPanelCodeBehind or BlankMvvmLight) similar to how projects are named in some of the generation tests.

This would allow for the generation of some complicated combinations of things but that's not the aim.

The purpose of this would be to remove some (much?) of the time and risk of human error in manually creating multiple projects for testing. 
Consider needing to test how a page displays and works in all combinations. This means generating nine (and soon to be twelve and then fifteen) projects. (The M*N issue.) With this tool, those projects could all be created in seconds and with a few clicks. Currently, it takes many minutes and lots of manual effort.

We would need programming language (C# or VB) specific versions of the above. Similar to the existing language specific versions of the options in VSEmulator.

This may do away with the need for #953 as it achieves the results that issue was intended to address but in a more user-friendly way.

Feedback and suggestions on how this could be improved are welcomed, along with related concepts, ideas, or other aspects of generation this could help with.

**Comment by mrlacey** [comment]
As we add more frameworks (and languages) this would be increasingly useful.   
At the moment, to check which framework/language combinations a bug affects requires manually creating 8 different projects. The above tool would save a bunch of time!

**Comment by crutkas** [comment]
Agreed

**Comment by mrlacey** [comment]
Automated testing and enhancements to VSEmulator have meant the lack of the functionality defined here hasn't been an issue so closing. Can reopen if ever needed.
