### ISSUE TITLE
StoreNotification duplicate references in csproj

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1101]
### Repro steps

Create a new App (i.e. Blank App Code Behind)
Setup Dev Center notifications.
Finish
Add new Dev center notifications from right click

### Expected Behavior
All files are unmodified

### Actual Behavior
csproj includes dev center notifications reference one more time.

If you try to add dev center feature for third time it not still happens

**Comment by sibille** [comment]
The extra whitespaces in the csproj file caused the code block to not be detected as duplicate code by the postaction.

**Comment by ralarcon** [comment]
Fix verified in nightly build

Wizard: 0.14.17250.65003
Templates: 0.14.17250.3
