### ISSUE TITLE
UriScheme feature breaks for MVVMLight if start page name is changed

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1104]
**Repro steps**

- New project, NavPanel & MVVMLight
- Change the name of the first/main/home page
- Include the UriSchemeFeature

**Expected Behavior**

- All compiles fine.

**Actual Behavior**

- Change in name of the default page isn't handled by the UriScheme templates and it tries to reference the VM for the default page name value which doesn't exist, so the code doesn't compile.

- `GenAllPagesAndFeaturesRandomNamesAsync` should have caught this!

_discovered while investigating #1097_

**Comment by mrlacey** [comment]
@ralarcon In that there's a CI build done by AppVeyor, are the results of the tests done as part of the process publicly available?
- If so, can they be linked from the Build Status on the main readme?
- If not, can they be made public? so it's possible to verify the tests that are run as part of a build

**Comment by ralarcon** [comment]
They are... you can Access from the PR checklist if not wrong, somehting like: https://ci.appveyor.com/project/ralarcon/windowstemplatestudio/build/CIBuild_0.14.79.dev/tests

**Comment by mrlacey** [comment]
It seems the CI is running `GenerateAllPagesAndFeaturesAndCheckWithStyleCopAsync` but not `GenAllPagesAndFeaturesRandomNamesAsync`. Running both of these is the minimum we need to do to have confidence in the templates. Over the summer, before we had the AppVeyor instance we went down to running just these two sets of generation tests as they are the simplest way to cover the widest range of range of scenarios. To leave out either puts a lot of uncertainty over the quality.
That's a separate issue.

The reason this wasn't caught by the automated tests is that there's a bug in the GenAllPagesAndFeaturesRandomNamesAsync test. I'll raise a separate issue for that.

**Comment by ralarcon** [comment]
@mrlacey I'll include `GenAllPagesAndFeaturesRandomNamesAsync` as part of the "Minimum" execution test. Open the issue for the bug in GenAllPagesAndFeaturesRandomNamesAsync and we will have a look on it tomorrow.

**Comment by mrlacey** [comment]
@ralarcon actually don't.  You need to include `BuildAllPagesAndFeaturesRandomNamesAsync`.
After you split everything from ProjectGenerationTests into GetProjectTests and BuildProjectTests things are different and I didn't realize. I was used to running `GenerateAllPagesAndFeaturesRandomNamesAsync` and just assumed that `GenAllPagesAndFeaturesRandomNamesAsync` did the same thing and so had been running that without realizing it only did half of what the old version did.

The Gen* tests ensure that the templates can be combined without error but don't check the generated projects can build.
The Build* tests do everything the equivalent Gen* ones do but also check the generated project can build.

This raises two questions:
1. What's the point of the Gen* tests in that any issues they find will also be found by their Build* equivalents?
2. Why are none of these tests being run? Surely verifying that the process produces apps that actually work and can be compiled is a fundamental aspect of the project and verifying this is being done is essential.


---

>They are... you can Access from the PR checklist if not wrong, somehting like: https://ci.appveyor.com/project/ralarcon/windowstemplatestudio/build/CIBuild_0.14.79.dev/tests

Great, can you add appropriate links to the **Build Status **section of the main readme so that anyone can follow appropriate links when necessary?
This also seems to be connected to your own AppVeyor account. What are the consequences and implications of this going forward? What's the impact for project ownership? and does anyone else have access to this should it need to be changed?

**Comment by ralarcon** [comment]
I've included the Build*. The reason to have the Gen* tests is to be able to have another build which execute all generation combinations (executed more frequently) so it can catch any generation issue... the Build* takes 66 - 70 mins to complete.

Those tests are not run in AppVeyor but are run in the Build Server of our TFS so these are an extra check but trying to do not block too much the developers to know if their PR are properly combined (rest of the world can't Access the TFS -by now-).

Regarding the appveyor account, all GitHub team members are granted to the Project where the build runs (the "appveyor" account was created automatically, I need to check if we can créate something more generic, just a matter of time). 

The following image would give you an idea of what is run in our custom build servers with TFS:
![image](https://user-images.githubusercontent.com/2638875/30182631-ccfb016a-9417-11e7-860f-41fb6c026313.png)

**Comment by dgomezc** [comment]
Fix verified in nightly build

Wizard: 0.14.17251.65001
Templates: 0.14.17250.3
