### ISSUE TITLE
[Gen|Build]AllPagesAndFeaturesRandomNamesAsync does not use a random name for the Main Page

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1106]
The automated tests `GenAllPagesAndFeaturesRandomNamesAsync` and `BuildAllPagesAndFeaturesRandomNamesAsync` do not use a random name for the "Main" page. Because of this, it does not detect any issues related to changing the name of this page.

This is particularly important as other templates (such as URI Scheme) can make reference to the main page and so are not currently tested properly.

_discovered while investigating #1104_

**Comment by mrlacey** [comment]
`Microsoft.Templates.Test.GenerationFixtureSetupProjectAsync` contains a hardcoded value for the value of "Main" for the `UserSelection.HomeName`.
With this value unchanged the related tests all pass.
If this hard-coded value is changed (or set to a random value for the Random name tests) then the versions of this test for the Blank and SplitView project types fail.

![image](https://user-images.githubusercontent.com/189547/30185189-63635242-9418-11e7-92b4-17f2c1b35213.png)

However, if creating any of these project types through the VS wizard UI, then the changed name is correctly used and the project is generated so that is can be successfully built.

**This shows that the code to test the generated projects is not doing the same thing as when the tool is used normally. This makes the tests inconclusive at best. The tests are, therefore, potentially worthless and mean we can have no confidence in the code without manually testing.** 

This is a large issue and should be tracked separately.

The original issue of using a hard-coded name in a random name test should still be addressed but if it can be manually tested and confirmed as not affeccting the current templates this issue can be moved back to a later milestone.

**Comment by ralarcon** [comment]
Verifed.
