### ISSUE TITLE
Audit all testing

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1108]
#1106 shows that there are issues with the current automated tests. In light of this, all tests should be thoroughly audited and reviewed to make sure they do what they claim, are correct, and cover all necessary scenarios.

**Comment by sibille** [comment]
I reviewed the projects generated by all test categories and added in a test that generates a project with all features and pages and then adds in everything again (#1097).

**Comment by mrlacey** [comment]
I don't think this is ready to close as there's no evidence of having looked at this fundamental issue:

> This shows that the code to test the generated projects is not doing the same thing as when the tool is used normally. This makes the tests inconclusive at best. The tests are, therefore, potentially worthless and mean we can have no confidence in the code without manually testing.

While the change here adds more tests it doesn't address the issue that the tests are not doing the same things as the code when used as a VS extension. As they're doing different things, whether the test passes or fails doesn't mean anything in terms of the wizard being used in VS. This is what needs to be audited.

**Comment by sibille** [comment]
The tests differ from the wizard in the way the userSelection is set up. 
Once the userSelection is set up, wizard and tests perform the same steps. 
We tried to UITest the Wizard but faced issues, as Clint states in #1035 winappdriver could be a solution to automate Wizard tests.

**Comment by mrlacey** [comment]
My concern was that if the same inputs produced different outputs there were possibly other things being done differently that had consequences or issues that were unknown or hadn't been observed yet. If you've been through the code to look for this then let's take that as confirmation that we're confident there isn't anything.

Automated UI tests would be good. I've created #1140 to track that idea
