### ISSUE TITLE
UriScheme must be a reserved name

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1113]
To avoid collisions creating features with the same name

**Comment by ralarcon** [comment]
Regarding this, adding feature unable to be renamed (fixed name), that name must be added to the reserved name list. Adding new issue to create a test to validate exactly this.

**Comment by mrlacey** [comment]
It doesn't need adding to the reserved list, it just needs a value ("UriScheme") adding as a "wts.defaultInstance" tag in the template as this will then be included in the list of `DefaultNames`.

**Comment by mrlacey** [comment]
X-Ref #1115

**Comment by ralarcon** [comment]
Verified in PRE release

Wizard: 0.8.17251.2
Templates: 0.8.17251.2
