### ISSUE TITLE
All fixed-name features must have the parameter wts.defaultInstance

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1114]
Include a test to validate that any feature unable to be renamed must have the name in the reserved name list.
x-ref: #1113

**Comment by mvegaca** [comment]
Fixed on #1115

ReservedNames was already loaded from templates information but we have not validations for template json file. wts.defaultInstance set a reverved names entry on wizard.

**Comment by mrlacey** [comment]
It'll be easy for me to add this test into the TemplateValidator tool. (#1037)

I think the rule should be:
- if the template tag "wts.type" is "feature"
- and "wts.multipleInstance" is "false"
- then a "wts.defaultInstance" must be specified and that should match the "name" but without any whitespace

This feels a bit like creating rules so the templates work with the rules of the engine, rather than making the engine smarter, but this is probably a good first step.

Additionally, we must also add the names of any pages included in a feature template (and which can't be renamed) to the reserved list.

**Comment by mrlacey** [comment]
_my last comment was started before Martin assigned and marked fixed_

@mvegaca this issue is to create a test to enforce the required underlying behavior.
You haven't fixed it on #1115, you've fixed #1113 which is the specific instance which identified the problem.

**Comment by mrlacey** [comment]
@ralarcon any plans for how you'll address this? I still think it'll be both trivial and appropriate for me to add this to the TemplateValidator I've added for #1037

**Comment by ralarcon** [comment]
@mrlacey yes, initially I was planning to add a unit test to validate it but looks better to include it in the validator... let me try to do it and if I have any doubt, I'll let you know.

**Comment by ralarcon** [comment]
Regarding the reserved names list, If i'm not wrong, it is dynamically created adding the wts.defaultInstance name of those templates which wts.multipleInstance is false.


I'm not checking the wts.defaultInstance value to be exaclty the same as the template name without whitespaces as we currently have some features where both differ (Azure Notifications vs HubNotification; Dev Center Notifications vs StoreNotifications; Sample data vs SampleDataService; What's New Prompt vs WhatsNewPrompt...). I don't thing this is too much important as far as the value for wts.defaultInstance is going to be validated too.

I've added a new `VerifyWtsTypeFeatureMultipleInstancesRule()` method called from `VerifyTagUsage()` when the `tag.Key` is `feature`. You can see the details in the PR #1143

I've added the attribute [Trait("ExecutionSet", "Minimum")] to the test class in order the test being executed in the CI build.

As an idea for the future, after seeing the TemplateValidator I've thinking that maybe adding a couple of refactors (mainly replacing in-code constants by constants definitions for json tags names, values, properties, etc.) we would include this validations in the Templates.Core assembly to be applied before loading the templates (before TemplateEngine being instantiated). This will help to avoid to load malformed templates... In the case we are running in Debug configuration, we can raise warinings to the UI, if running in Release configuration, we can do it to the log file...

**Comment by mrlacey** [comment]
There are actually two reserved names lists.
There's the hardcoded list of values in `ReservedNamesValidator` and there's the "existing names list" which is built up during the generation process. Between these, I think we now cover everything.

I like the idea of running the template validator over templates that are loaded from other sources (e.g. #919) at runtime so the wizard doesn't load any templates that are invalid or may cause it to break.

**Comment by sibille** [comment]
Verified on dev-nightly: 
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
