### ISSUE TITLE
Merge postaction fails when using tabs instead of whitespaces in _postaction file

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1126]
Merge postaction fails when using tabs instead of whitespaces in _postaction files like on [this](https://github.com/sibille/WindowsTemplateStudio/blob/poc_reordergenerationqueue/templates/_composition/CodeBehind/Project.SplitView/App_postaction.xaml.cs) one because the merge postaction does not find the line `public sealed partial class App`.
I see two possible solutions to the problem: 

1. Replace the tab with 4 whitespaces when searching for the line.
2. Always use whitespaces in templates, and do not allow tabs in templates. Add in a test that enforces this rule. 

Whilst the second rule is more restrictive, I think it's the correct one as it enforces consistency in the templates. What do you think?

**Comment by mrlacey** [comment]
I vote for the second one.

**Comment by crutkas** [comment]
I vote for the failure option

**Comment by sibille** [comment]
Clint, you refer to option 2, correct?

**Comment by crutkas** [comment]
Yes

**Comment by sibille** [comment]
I'll add this check in the TemplateValidator tool (and call it from the tests), as part of the directory option. 
I think we could include a test to ensure the fileencoding here as well. @mrlacey, what do you think?

**Comment by mrlacey** [comment]
@sibille we already have separate tests for this sort of thing.
You could easily test this by adding the following to **Templates.Test.CodeStyleEnforcementTests**

```csharp
        [Fact]
        public void EnsureCSharpCodeDoesNotUseTabs()
        {
            var result = CodeIsNotUsed('\t'.ToString(), ".cs");

            Assert.True(result.Item1, result.Item2);
        }

        [Fact]
        public void EnsureVisualbasicCodeDoesNotUseTabs()
        {
            var result = CodeIsNotUsed('\t'.ToString(), ".vb");

            Assert.True(result.Item1, result.Item2);
        }
```

Whether test like this should also be run by TemplateValidator is an interesting question. 
My original aim with the TemplateValidator was about the structure and content of the JSON file. That has already broadened to include directory based checks looking for duplicate identities, etc. That's an argument for having it do more but not decisive.
We could also include the file encoding tests with TemplateValidator but we can't run all the tests in it. The StyleCop ones being an obvious but important set of tests that the TemplateValidator couldn't do on its own. It is not intended to be a tool that is only used in isolation. 
In addition to our use, TemplateValidator is also intended to be used by people creating their own templates (for use when #919 is done) and those templates don't need to meet as strict a set of standards as we require. If they included tabs, were encoded to only use ASCII, or didn't meet our StyleCop checks, but still worked for the people who created and are using them then that's fine.
I need more time for reflection on this before saying they should be combined. For now, I'd like to wait and see how (& if) TemplateValidator is used before merging other functionality with it.

**Comment by sibille** [comment]
Ok, sounds correct to me, I'll include only the unit tests for the moment.

**Comment by ralarcon** [comment]
From my point of view, having this validation in the TemplatesValidator is also usefull to help people develop the templates... anyway, having the test will catch this.
