### ISSUE TITLE
missing build status icon

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1128]
![image](https://user-images.githubusercontent.com/1462282/30288197-b8c9e540-96dc-11e7-85f4-a88f96ed9d40.png)

**Comment by ralarcon** [comment]
The new Build Status section is as follows:

![image](https://user-images.githubusercontent.com/2638875/30469426-8b6c2b6e-99f0-11e7-8fd7-b29b78100863.png)

**Comment by crutkas** [comment]
hotness!

**Comment by sibille** [comment]
Verfied in dev branch
