### ISSUE TITLE
How to add a hamburger menu button like 'rate my app'?

### ISSUE THREAD

**Issue by hupo376787** [Microsoft/WindowsTemplateStudio#1133]
With the great hamburger menu controls, we can easily create our own. But now I want to create a button like 'rate my app', which means, when I click the button, it doesn't navigate to a page, but response to a piece of code.
In my example, it will show a dialog first, and then lead the users to app store.
How? Thanks.

![_20170912105652](https://user-images.githubusercontent.com/14960168/30306198-718103b2-97a9-11e7-8c29-db2f00fd80e8.png)
![_20170912105716](https://user-images.githubusercontent.com/14960168/30306200-71d66eec-97a9-11e7-8ba4-920081784443.png)

**Comment by mrlacey** [comment]
Here's a quick way to do what you ask.
The ability to do this will be built into the generated code soon as I know this is a common requirement of apps.
It's likely that the implemented version will be similar to the example below but with some naming differences.

In **ShellNavigationItem.cs** add the following

```csharp
    public Action Action { get; private set; }

    private ShellNavigationItem(string label, Symbol symbol, Action action)
        : this(label, null)
    {
        Symbol = symbol;
        Action = action;
    }

    public static ShellNavigationItem ForAction(string label, Symbol symbol, Action action)
    {
        return new ShellNavigationItem(label, symbol, action);
    }
```

In **ShellPage.xaml.cs** (If using CodeBehind) or in **ShellPageViewModel** (If using MVVM Basic) change the `Navigate` method to be like this.

```csharp
    private void Navigate(object item)
    {
        var navigationItem = item as ShellNavigationItem;
        if (navigationItem != null)
        {
            if (navigationItem.Action != null)
            {
                navigationItem.Action.Invoke();
            }
            else
            {
                NavigationService.Navigate(navigationItem.PageType);
            }
        }
    }
```
Or, if using MVVM Light in **ShellPageViewModel** change the `Navigate` method to be like this.

```csharp
    private void Navigate(object item)
    {
        var navigationItem = item as ShellNavigationItem;
        if (navigationItem != null)
        {
            if (navigationItem.Action != null)
            {
                navigationItem.Action.Invoke();
            }
            else
            {
                NavigationService.Navigate(navigationItem.ViewModelName);
            }
        }
    }
```



With the above, you can create an app that does something like this

![image](https://user-images.githubusercontent.com/189547/30319349-8d47dd20-97a7-11e7-9f2e-038035dfc3df.png)

with code like this

```csharp
_secondaryItems.Add(
    ShellNavigationItem.ForAction(
        "Shell_Rate".GetLocalized(),
        Symbol.OutlineStar,
        async () => { await new Windows.UI.Popups.MessageDialog("Pretty please...").ShowAsync(); }));
```
_I've added the appropriate string resource for the label. Any text in a dialog should also be localized but this was just a quick example_

Does this help? Is there anything more needed in this area?

**Comment by hupo376787** [comment]
@mrlacey Wow, big thanks. It works.
But In ShellNavigationItem.cs, the function should be private ShellNavigationItem(string label, Symbol symbol, Action action)
        : this(label, null, null)

You missed a word "null", am I right? : )

**Comment by mrlacey** [comment]
there's a version of the constructor that just takes 2 params so `this(label, null)` is fine
