### ISSUE TITLE
Hamburger menu's last item is invisible while Page.BottomAppBar occures

### ISSUE THREAD

**Issue by hupo376787** [Microsoft/WindowsTemplateStudio#1134]
As the picture shown, I added a bottomappbar to the map page.  My hamburger menu's last item is invisible.

How to solve it? Thx.

![_20170912110639](https://user-images.githubusercontent.com/14960168/30306442-c884edd0-97aa-11e7-956b-1d71c4df5d8f.png)

**Comment by EdiWang** [comment]
My solution is to use CommandBar in the page's grid, not page.appbottombar. 你也是中国开发者呀? 握手 :)

**Comment by mrlacey** [comment]
Issue #425 & #1098 also ask this same question. This is being addressed by adding documentation (PR #1130) to explain why this happens and how to work around it.

Closing as duplicate.

**Comment by hupo376787** [comment]
@EdiWang Hi, thanks. This is a good idea. I'm also a Chinese developer. 握爪 ; )

**Comment by hupo376787** [comment]
@mrlacey Thanks : )
