### ISSUE TITLE
Formalize documentation for adding a NavPanel menu item that runs other code

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1137]
Follow on from #1133

Create formal documentation that explains how to add a menu item to the NavPanel project that can be used to do things other than navigating to a page.

Extending /docs/projectTypes/navigationpane.md seems like a logical palce to put this.

Hopefully, the need for this documentation will be temporary until this functionality can be built into the templates. Possibly for #196

**Comment by mrlacey** [comment]
waiting until changes for #425 are merged with dev as this will impact the same documents.

**Comment by mrlacey** [comment]
May build this functionality natively into the templates for #196. If that is done this documentation will need to be very different so waiting to do that first.

**Comment by mrlacey** [comment]
merged so closing as not part of shipped artifacts

**Comment by ThomasPe** [comment]
One thing I noticed is that the Menu Item will still get the active marker even though this might not make sense for example when opening the feedback hub. Any way to prevent this manually?

![uwp](https://user-images.githubusercontent.com/4225039/31863681-2c774f48-b751-11e7-8151-cabe2d397047.PNG)

**Comment by crutkas** [comment]
Without knowing how / what was done here. It is hard to make any guidance

Can you share the code?

**Comment by mrlacey** [comment]
@ThomasPe What are you doing in the code when clicking on the secondary menu item? The indicator should only be changed/applied when navigation is triggered.
Also, which version of Windows is running on the machine you're seeing this? I cant' repro on a machine with Fall Creators Update.

**Comment by ThomasPe** [comment]
sure, here's the project: https://github.com/wp-net/WordPressUWP
no navigation is being triggered as far as I can tell.
Screenshot was taken on W10 with Fall Creators update.

**Comment by mrlacey** [comment]
It seems you removed the background on the grid in the `NavigationMenuItemDataTemplate`
It's the change added here https://github.com/Microsoft/WindowsTemplateStudio/commit/8ed03b3e95619777362da5f95536fcf90b7558c6#diff-1d7062722815b44e736ce1b0a5ff1e4a
Put the background in and all works fine.

We specifically add the background to hide the incorrect selection indicator.

**Comment by ThomasPe** [comment]
Right, I removed that because I wasn't seeing any hover or click effects on the hamburger menu items.

**Comment by ThomasPe** [comment]
so yes, on a completely fresh new project with navigation & mvvmlight I don't see any hover or clicked states in the hamburger menu, probably due to that background on the grid in the `NavigationMenuItemDataTemplate`. should I open a new issue for this?

**Comment by mrlacey** [comment]
yes, raise a new issue if you think you've identified a problem with the generated code
