### ISSUE TITLE
Localize exception messages in the generated code

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1144]
For example, take [SettingsStorageExtensions](https://github.com/Microsoft/WindowsTemplateStudio/blob/69619ddfa844d076d67c223d02bf6ce934aee913/templates/Features/SettingsStorage/Helpers/SettingsStorageExtensions.cs#L69)

Is it ok that the exception message is hard-coded in English?

```csharp
        public static async Task<StorageFile> SaveFileAsync(this StorageFolder folder, byte[] content, string fileName, CreationCollisionOption options = CreationCollisionOption.ReplaceExisting)
        {
            if (content == null)
            {
                throw new ArgumentNullException("content");
            }

            if (string.IsNullOrEmpty(fileName))
            {
                throw new ArgumentException("File name is null or empty. Specify a valid file name", "fileName");
            }

            var storageFile = await folder.CreateFileAsync(fileName, options);
            await FileIO.WriteBytesAsync(storageFile, content);
            return storageFile;
        }
```

**Comment by crutkas** [comment]
If an exception is shown to an end user, yes

**Comment by mrlacey** [comment]
[MSDN says so too](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions)

> Include a localized description string in every exception

Changing this issue to be about making the changes.

**Comment by mrlacey** [comment]
Also, need to review all generated code to identify all strings that need changing.

The example code above should also use `nameof()` for other hard coded strings.

**Comment by ralarcon** [comment]
Regarding the generated content we do not / will not localize the content. Agree to include the strings in a resource file.

**Comment by sibille** [comment]
All frameworks ok, do for Caliburn Micro, too

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.2
