### ISSUE TITLE
ChartPage uses the wrong TODO comment

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1149]
The Chart page still uses the old `TODO UWPTemplates:` form of comment prefix and not `TODO WTS:` like everywhere else.

**Comment by crutkas** [comment]
Possible to do a test to verify this like we do with the header?

**Comment by mrlacey** [comment]
test added to same PR

**Comment by mrlacey** [comment]
Confirmed in Dev Nightly
Wizard: 0.14.17262.65001
Templates: 0.14.17262.2
