### ISSUE TITLE
Sort order of pages is broken in dev branch

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1151]
v1.3 release shows pages correctly sorted by order
![image](https://user-images.githubusercontent.com/189547/30498295-068fb75e-9a4e-11e7-8ee8-cfc8d9c934b4.png)

Latest dev nightly has them incorrectly listed alphabetically
![image](https://user-images.githubusercontent.com/189547/30498315-19fe947c-9a4e-11e7-9419-0df9a92d4871.png)

**Comment by sibille** [comment]
Fixed on dev-nightly 
Wizard: 0.14.17261.65001
Templates: 0.14.17261.1
![image](https://user-images.githubusercontent.com/24698018/30531201-e846d88a-9c4c-11e7-96a0-dc28e075c12c.png)

**Comment by sibille** [comment]
Verfied on dev-nightly: 
Wizard: 0.14.17282.65001
Templates: 0.14.17282.1
