### ISSUE TITLE
Allow Templates.Test tests to be run concurrently

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1156]
The idea is to separate build tests by framework and run them in separate runners concurrently.

TODO: 
- [x] Sync Templates in separate folder to avoid sync conflicts
- [x] Generate tests projects in separate folders to avoid naming collissions

**Comment by mrlacey** [comment]
X-Ref #497

**Comment by sibille** [comment]
To shorten test execution time traits in Templates.Test are run parallel using this [script](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/_build/ParallelTestExecution.ps1).
To execute this script locally use the following powershell command:

`<wts directory>\_build\ParallelTestExecution.ps1 -testRunner <wts directory>\Code\packages\xunit.runner.console.2.2.0\tools\xunit.console.exe -testLibrary <wts directory>\Code\test\Templates.Test\bin\Analyze\Microsoft.Templates.Test.dll -traits 'ExecutionSet=BuildMinimum', 'ExecutionSet=BuildStyleCop', 'ExecutionSet=TemplateValidation' -outputDir <output directory>`

where

* `<wts directory>` : Directory where WTS is cloned
* `<output directory>`: Directory where test xml result files will be generated

**Comment by sibille** [comment]
Mental note: Adapt pre builds before merge to main
