### ISSUE TITLE
Latest dev-nightly: Item name of items with wts.defaultName is inferred

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1160]
### Repro steps

1. Create new project with dev-nightly version
2. Add Suspend and Resume feature and Toast Notification feature

### Expected Behavior
Items should be added with defaultName

### Actual Behavior
Item name was inferred
![image](https://user-images.githubusercontent.com/24698018/30584705-d98c20b4-9d2a-11e7-8219-d4720ac28486.png)

## System
Wizard: 0.14.17262.65001
Templates: 0.14.17262.1

**Comment by mvegaca** [comment]
Fixed on #1159

**Comment by sibille** [comment]
Verified on dev-nightly: 
Wizard: 0.14.17282.65001
Templates: 0.14.17282.1
