### ISSUE TITLE
Set dev branch as the default repo branch

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1162]
We are thinking in making the `dev` branch the repo default branch. I've done my self in my fork and no side effects detected.

We actually use the `dev`as the default one so I think it make sense.

**Comment by ralarcon** [comment]
Anyone see a risk here? If not, I will change the default repo branch to `dev`...

**Comment by ralarcon** [comment]
@crutkas, @mrlacey... agree with changing the default branch to `dev` as it is the "ongoing branch"?

**Comment by mrlacey** [comment]
I don't understand what this will do and what any implications are

**Comment by ralarcon** [comment]
Basically, the default branch shown when access the github repo will be the dev one instead of master (which, by the way, we only use to generate the pre-release and release versions). This will set dev as default merge branch (instead of master). So in general dev branch is shown by default.

**Comment by mrlacey** [comment]
If that's the only change then seems fine

**Comment by ralarcon** [comment]
doing...

**Comment by ralarcon** [comment]
Done
