### ISSUE TITLE
Exception in dev when changing framework/projecttype on first page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1170]
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Microsoft.Templates.UI.ViewModels.NewProject.ProjectTemplatesViewModel.ContextFramework.get returned null.

**Comment by mvegaca** [comment]
Fixed on #1178

**Comment by sibille** [comment]
Verified on dev-nightly: 
Wizard: 0.14.17282.65001
Templates: 0.14.17282.1
