### ISSUE TITLE
Improve Navigation sample and doc

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1171]
We shoud improve the [Navigation sample and documentation](https://github.com/Microsoft/WindowsTemplateStudio/tree/master/samples/navigation) to consider the following scenarions:

* Consider MVVM Light as it has some important differences which should also be documented. A description of what's different if using Code Behind should also be included.
* Consider Login-Logout scenarion where logging out means to show a full screen page to be able to re-login
* Consider showing a page taking up the full window space (but not the full screen). This would hide the navigation menu but be able to return to it via the back stack. Example. an image gallery where a single image can be viewed using all the space of the window.

X-Ref: #775

**Comment by crutkas** [comment]
without having a login feature / page, i want to steer clear of that scenario in a sample.

**Comment by sibille** [comment]
The Navigation documentation already contains sample code for showing a startup page that is displayed before navigating to the shell page. We are thinking of extending the docs and sample code to include code to show how to navigate to a page shown in full window mode and navigate back from within the shell.

**Comment by sibille** [comment]
Can we close this in favor of #482?

**Comment by crutkas** [comment]
Sure
