### ISSUE TITLE
Wrong title in select pages section and missing title in select features section

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1172]
Wrong title in select pages section:
![image](https://user-images.githubusercontent.com/12777039/30632263-c7f7a630-9de7-11e7-9460-8c16e91e0417.png)

Missing title in select features section:
![image](https://user-images.githubusercontent.com/12777039/30632305-e0767aa6-9de7-11e7-967e-46a0340e155c.png)

**Comment by crutkas** [comment]
great catch!

**Comment by dgomezc** [comment]
Verfied on dev-nightly:
Wizard: 0.14.17282.65001
Templates: 0.14.17282.1
