### ISSUE TITLE
VB project creation failing in dev

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1173]
### Repro steps
Create vb project with framework codebehind.

Actual behaviour: 
Failing as page defined in layout could not be found

![image](https://user-images.githubusercontent.com/24698018/30639558-b1f82e78-9dff-11e7-872b-ea0de1897a4a.png)

**Comment by mrlacey** [comment]
Works fine in the VB templates branch.

**For reference.**
There is no expectation that anything relating to VB will work in the dev branch, _yet_.
VB support is currently targetted for m1.5 (at the earliest)
