### ISSUE TITLE
Post-Actions for Style resources dictionaries

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1179]
In relation of #519 and #1164 we were thinking about the following:

We have a conflict handling styles between project template and pages/features templates. We are developing Camera and image gallery pages that need to add styles on project resources dictionaries.

There are two different ways to solve it:
- The new template adds a new style sheet in the project.
- The new template adds styles to existing style sheets in the project.

The first option has the following problem:
- If we have two different templates that add a new style sheet with the same name and different styles on it, only one style sheet will be added.

The second has the following problem:
- This option forces us to create empty style sheets in all new projects even if no templates add styles on it.

We were thinking on the best approach could be to add a specific Post-Actions for styles.
Styles PostAction should create a empty style sheet if the project hasn't it before apply the postaction.

i.e. Adding Button styles from two different templates:
- Check no button styles sheet in the project.
- Create a Empty Style Sheet.
```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

</ResourceDictionary>
```
- Add styles from first template
```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Style TargetType="Button" x:Key="StyleFromFirstTemplate">
        <Setters>........</Setters>
    </Style>

</ResourceDictionary>
```
- Add styles from second template
```xml
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Style TargetType="Button" x:Key="StyleFromFirstTemplate">
        <Setters>........</Setters>
    </Style>

    <Style TargetType="Button" x:Key="StyleFromSecondTemplate">
        <Setters>........</Setters>
    </Style>

</ResourceDictionary>
```

This issue is added to 1.5 version, By this moment we are going to solve Camera and Image gallery templates by:
**New Image Galley Page -> ImageGalleryPageStyles.xaml** (New file)
**New Camera Page -> CameraPageStyles.xaml** (New file)

**Comment by mrlacey** [comment]
The way this is currently planned seems the worst of all options.
The point of a shared resource dictionary is that is can be reused. If you're going to create a new file just to hold the styles for a single page then that's not going to be shared and you end up making managing associated styles and their uses harder as they're kept apart.
In general, things should be defined close to where they will be used. If it's only used in one place then it should be defined close to it.
Your proposal also creates future maintenance issues with the generated projects. Say a resource file is created for the camera page that includes a specific button style. If I then want to use that same style on another page it takes a dependency on the camera resources. The reason for such a dependency is non-obvious and creates an unnecessary cognitive overhead in terms of maintenance.

We're supposed to be demonstrating best practices in the generated project. This is a long way from it.

There should be no need to create empty resource files in all projects. Why create empty placeholders? Template composition, dependencies, and merging mean we shouldn't need empty placeholders in all projects.

It seems to me that the best approach is to have page & feature templates merge new style resources into general resource dictionaries and to ensure that such merging doesn't create duplicates. i.e. Ignore the second merge if adding two copies of a page. Or, more generally, merging shouldn't add something if it already exists in the target location in the file.

If need be, once merging can avoid duplicates, we could add hidden feature templates for empty resource files if there are some that are needed. Similar to what we do for the SampleDataService.

I'm also concerned about the potential for a lot of resource files that also only contain a few definitions. This could potentially lead to an issue with dependencies and the order the files are merged given that we don't know what could end up being added to them. Going down the route of creating a separate file for different types of control, such as a 'ButtonStyles.xaml' resource file is also to be avoided. This sets a bad example and a dangerous precedent. Dividing up resources in such a way is only really useful when there are a large number of such resources used in a project. Using a very large number of resources is a code smell indicating a poorly designed app. Only very large apps with a lot of custom UI can really justify this and that's not what most apps that are generated will be. The dangerous precedent is that it also doesn't make it clear how specific the division of resources should be. Should a person take the generated project and create new resource files for every different control type they wish to style?  
I believe we'd be better off with a single resource file with all the styles and other resources used by the generated code. Additions could be merged into it as needed.  
Generated projects (at least from the generic templates) shouldn't need large numbers of styles and resources. We're not creating a unique style and look for the generated project and should only be adding things that should really be built into the SDK anyway. A number that will hopefully come down in the future too.

This should have been planned and documented when the original work was done with the style resource files that are included with each project. That it wasn't makes me wonder what else is part of the generated projects that wasn't fully thought through and is likely to cause problems in the future.

Planning on doing one approach for things in one version of the templates and a different approach in the next version creates lots of potential opportunities for breaking the ability to do right-click add to a project generated with an earlier version of the templates and should be avoided if at all possible. Just going straight to the final desired way of doing things also means less work overall. Avoiding unnecessary work allows more time for testing and adding other features.

On a related note, I have big issues with the way styles have been named also but I don't even have time to go into what's wrong. Let alone look into the best way to address the situation going forward.

**Comment by ralarcon** [comment]
@mrlacey, trying to syntetize, the idea is exacly to avoid potential conflicts by merging the styles in the project Styles folder.

If a template defines certain styles, the post action will move the styles to the project folder. If the project already have that style file, it will merge the contents. If not, the style file is created (probably the explanation from @mvegaca wasn't clear).

The post actions already check if the code being inserted already exists and can be created with validations to detect when there is confilct or even rise warnings if new style file is created with few styles.

Agree with the fact of giving guidance. We can state that the styles defined in a template will act as "partial" and will be merged to the main project.

The issue of adding the styles to the project and updating  the existing one as a centralized files are exactly related to the right-click and backward compatibility. Previous created projects will lack of the new styles if we upgrade the project styles, so the unique way to solve it is defining a part of template which have the styles to be merged to the existing one... that is, almost the same solution, the only thing we want to avoid with the new post-action is the pre-requirement of the project to have the style files pre-defined (an empty).

Finally, as a transitory workaround, for the both concrete cases exposed, we can move to inline styles or create the custom style file, no matter as we will change it soon (next version or even this one if possible).

**Comment by mrlacey** [comment]
I still don't see what this new postaction will do that can't already be done with hidden dependencies.
Why invest time in another way of doing something that's already possible? What's the benefit over the existing way? How would such a new post-action work and be configured?

**Comment by ralarcon** [comment]
If i'm not wrong the current post-actions only will be able to merge content from different files if the file already exists. That is, if we have a style file in the project, then we can merge the content added thru a merge post-action using the same file in the templates. The post-action for styles must take in consideration if the file exist to merge or if not exists to add it to the project. By the way, the post-action for styles can make other validations we think are required for sytles. 
Other option is to improve the existing post-actions somehow to cover this.

@sibille can you confirm.

**Comment by sibille** [comment]
Hidden dependencies and global postactions would be a solution, that's correct @mrlacey. 
Although it seems to be quite complicated to have a hidden dependency for every Style resource dictionary. 
The postaction @mvegaca proposes would no be too much effort to develop and seems quite strait forward to me, search for the file, if its not there create one, then execute the postaction.

**Comment by mrlacey** [comment]
Yes, current functionality would mean we'd need a hidden template (as a dependency) for each resource file being added. 
But my other point is we shouldn't be adding loads of separate resource files which each only contain a small number of items

**Comment by ralarcon** [comment]
The thing is to control the proliferation and give guidance on how we expect the styles to be defined in the templates. The first (proliferation) could be done by implementing as warnings where small style files results from the post-action execution. The second, we need to define that guidance and mentioning that the styles will be merged...

As more templates are being implemented more posibilities for that templates to require its custom styles. The guidance would be that the styles for foundation controls / elements must be done in planned / concrete files. Other styles would be merged to a certain file. Anyway, we need to provide a simple way to implement this and IMHO, improving / creating the post-action would help to be more understandable than using hidden features.

**Comment by sibille** [comment]
As Master-Detail page styles will changes, moving this to 1.4.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.1
