### ISSUE TITLE
Review of redlines for new Master-Detail page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1183]

**Comment by sibille** [comment]
Review redlines and extract styles to ResourceDictionaries

**Comment by mvegaca** [comment]
Redlines updated on #1222

**In**
- Four frameworks alignments (UWP Toolkit MasterDetailControl)
- Two lines list view redlines
- TextBlock styles Type ramp (In MasterDetail)
- Added new xaml resources postactions
- High contrast accessibility checks
- Color contrast accessibility checks
- Theme selection support

**Out**
- Reviewing [BreakPoints documentation](https://docs.microsoft.com/en-us/windows/uwp/layout/screen-sizes-and-breakpoints-for-responsive-design) we could think about adding dynamic margins on Detail Control.
- Fix narrator support for detail (Adding Focusable to detail even it is not actionable).
- Grid values multiples of 4px.

**Comment by mvegaca** [comment]
Margins fixed on #1285

**Comment by sibille** [comment]
Verified in dev
