### ISSUE TITLE
Changing framework set project type to Navigation Pane

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1186]
**Repro steps**
- Open wizard
- Choose the project type "Pivot and Tabs"
- Choose the framework "MVVM Light"

**Expected Behavior**
- nothing happens

**Actual Behavior**
- The selected project type reverts to "Navigation Pane"

**ALSO**

 **Repro steps**
- Open wizard
- Choose the framework "MVVM Light"
- Choose the project type "Pivot and Tabs"

**Expected Behavior**
- nothing happens

**Actual Behavior**
- The selected framework reverts to "Code Behind"

The logic to reset the selections is wrong.

These should not change.
It is easy to miss that the change has happened and so someone may not end up with the project they thought they'd selected.

**Comment by mvegaca** [comment]
Can not reproduce in Dev nightly: 0.14.17271.65001.
I think it was fixed after UI Test code refactoring.

**Comment by mrlacey** [comment]
I can no longer repro either. Assuming fixed as part of other changes
