### ISSUE TITLE
Wizard execution context requirements and verifications

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1191]
As we are moving forward with the templates and our generated code will target the FCU sdk (10.0.16XXX.0) as default target version and CU sdk (10.0.15063.0) as minimum target version, the Wizard will require certain context to be sure can be executed.

The requirement includes:
- [x] Verifiy the minumum VS Version (probably VS 15.3) where the wizard can be executed and the impact of executing it in a lower one.
- [x] Verifiy dependencies with Microsoft.Templating (since VS 15.3, Microsoft.Templating libraries are delivered with Visual Studio. This probably will require to avoid deliver these libraries our own.
- [x] Verify the Microsoft.NETCore.UniversalWindowsPlatform dependency depending on the update level for Visual Studio and check impacts.
- [x] It would be interesting to allow people to install the extension in any version of visual studio but only allow to generate if have the expected dependencies (and give a proper message to invite the people to upgrade the Visual Studio if required).

X-Ref: #1045 and #552

**Comment by ralarcon** [comment]
One thing I'm working on is to allow users to install the extension even not having the pre-requisites and rise an unexpected error when launched. Something like this:

![image](https://user-images.githubusercontent.com/2638875/30868272-67fb5960-a2de-11e7-92ac-158bb10488b5.png)

We can improve the ErrorDialog to show a less strong message (kind of waring)...

**Comment by mrlacey** [comment]
Any error message should also include details of where to get the dependency from.
It's the difference between saying
"WTS needs X. Please upgrade it"
and
"WTS needs the latest version of X to work correctly. Please install it from {link to installer}."

The second version helps solve the blockage, rather than just saying there's a problem.

**Comment by ralarcon** [comment]
Unfortunately, if we opt for the VSIX to set the pre-requirements, there is no option for us to give customized messages. It will be blocked with the standar errors and the Visual Studio infrastructure.

In the other side, if we allow to install and block the execution afterwards when we detect a missing pre-requirement, then there would be users that would be impacted if visual studio automatically updates the VSIX and then they can't use the extension because, for any reason, they can't upgrade the pre-requirements.

**Comment by ralarcon** [comment]
Summarizing:
In 1.4 there are two pre-requirements to properly execute the Wizard:
* .NET 4.7
  Updated to take advantage of latest changes.
* Run on Visual Studio 15.3 or higher
  We now will relay on Microsoft.TemplateEngine distributed with Visual Studio (starting from vs 15.3)

With this and taking a conservative approach, the extension will not be installed in any Visual Studio lacking the pre-requirements.

Those pre-requirements are defined in the VSIX manifest using the standard mechanisms. Two dependencies:
* Microsoft .Net Framework 4.7 or higher
* Visual Studio Product Updates (15.0.26730 or higher -> VS Update 15.3)

![image](https://user-images.githubusercontent.com/2638875/30954944-48f58a68-a432-11e7-8b0b-bf860ae76edf.png)

This will make the user failing with the following errors:
- Lack of .Net Framework 4.7
![image](https://user-images.githubusercontent.com/2638875/30956229-eaf971b8-a436-11e7-9d91-74a1dccbdc2f.png)

- Lack of VS Update 15.3
![image](https://user-images.githubusercontent.com/2638875/30957560-e5b472da-a43a-11e7-9d27-4d983e075487.png)

Developers can access the log to check the error. In the log there is the description and the dependency have the link to download.

I think with this approach we are in a good shape and avoid anyone being updated without possibility to continue using the tool due to they don't wan't to update the dependencies yet.

**Comment by ralarcon** [comment]
All is verified now. Just pending to change the TargetVersion and update the reference of NETCore.UniversalWindowsPlatform.
