### ISSUE TITLE
Port ImageGallery page to Caliburn.Micro

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1200]
Now we have an image gallery page ready but it is pending to be ported to Caliburn.Micro framework.

@nigel-sampson, can you have a look on this to see if it is possible to include to the 1.4? If not we will need some time to get familiarized with the Caliburn.Micro framework.

**Comment by mvegaca** [comment]
ImageGallery added on ##1177

**Comment by nigel-sampson** [comment]
I should be able to look into this in a few days.

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.2
