### ISSUE TITLE
Some description files have weird characters.

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1202]
Some description files have weird characters.

![image](https://user-images.githubusercontent.com/12777039/30956981-28354686-a439-11e7-8a86-fae0b488a634.png)

**Comment by mrlacey** [comment]
This happened in at least one of the descriptions files added for Caliburn Micro too. 
Do we know what caused it and what we can do to detect and prevent it happening again?
In that, this has now happened multiple times with no clear cause, more investigation and action is needed than just addressing the specific instance.

**Comment by dgomezc** [comment]
The problem is that some texts have "non break spacing" (http://www.fileformat.info/info/unicode/char/00a0/index.htm) instead of spaces.
Running the script Set-All-Text-File-Template-Encodings.ps1 converts that character to a strange character.

[spaces_difference.txt](https://github.com/Microsoft/WindowsTemplateStudio/files/1340846/spaces_difference.txt)

You can see the difference between space and non break spacing  at http://www.babelstone.es/Unicode/whatisit.html

**Comment by mrlacey** [comment]
So, do we need to change the script to prevent this happening again? And if so, how?
How are the non-breaking spaces getting in the files in that they weren't there previously?
Are they wanted or needed?

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
