### ISSUE TITLE
System.InvalidCastException: 'Unable to cast object of type...'

### ISSUE THREAD

**Issue by zipswich** [Microsoft/WindowsTemplateStudio#1208]
Create a new UWP app project with Windows Template Studio.
Select configuration: Debug, Any CPU and Mobile Emulator 10.2.10586
Run the app and the following exception is generated:
System.InvalidCastException: 'Unable to cast object of type 'My_App.App' to type 'Windows.UI.Xaml.IApplication2'.'

Code:
```
public App()
{
    InitializeComponent();

    EnteredBackground += App_EnteredBackground;

    // Deferred execution until used. Check https://msdn.microsoft.com/library/dd642331(v=vs.110).aspx for further info on Lazy<T> class.
    _activationService = new Lazy<ActivationService>(CreateActivationService);
}
```
The statement throwing the exception is:
EnteredBackground += App_EnteredBackground;

System:
Windows 10 Pro
VS2017 (V15.3.5)
WTS verson: 1.3.17255.1

**Comment by ralarcon** [comment]
Does the app run in the desktop (x86 Local Device)? Looks you are running the emulator for the version 10.0.10586 does this still happen using the emulators for v 10.0.15063.0? 

You can download latest emulators from [here](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive)

**Comment by zipswich** [comment]
It works on local machine.
[V10.0.15063.0 does not work with any app](https://developercommunity.visualstudio.com/content/problem/122425/dep0001-unexpected-error-smartdeviceexception-the.html).

**Comment by ralarcon** [comment]
This looks like a different exception / issue. We are able to run generated apps in the mobile emulators with no issues with the 10.0.15063 emulators. If you still have issues running the app in the emulator, can you give a repro steps and, if possible, some screen shots describing your issue?

Regarding the liked issue there are some entries if you search like this: https://stackoverflow.com/questions/36384375/dep0001-unexpected-error-1988945906-while-deploying-windows-uwp-app-to-phone

**Comment by zipswich** [comment]
If you can use Mobile Emulator 10.0.15063, it means there may be something wrong with the emulators on my machine because, as mentioned before, I cannot run any UWP on any Mobile Emulator 10.0.15063, but they do fine on every Mobile Emulator 10.0.14393

**Comment by zipswich** [comment]
It looks like that the machine has the latest Windows SDK:
![image](https://user-images.githubusercontent.com/6095671/31075463-a6b25f14-a743-11e7-9d61-47e0aa766e0e.png)

**Comment by ralarcon** [comment]
Sorry @zipswich, just to be sure, which exception are you experiencing right now? If it is the one related to the deployment of the app within the emulator, I think it would be something related to emulators itsef. By the way, apart from the SDK, be sure you have the emulators 10.0.15063.

**Comment by zipswich** [comment]
Thanks a lot for trying to lend a hand here, @ralarcon 
Let me try a bit clarification here.
My original issue is about Mobile Emulator 10.2.10586.
As for Mobile Emulator 10.0.15063 about which you asked, I filed [a problem report for VS] (https://developercommunity.visualstudio.com/content/problem/122425/dep0001-unexpected-error-smartdeviceexception-the.html) as indicated in an earlier post .  The exception is DEP0001: Unexpected Error: SmartDeviceException - The system cannot find the file specified. [0x80131500].
Here are the emulators shown in VS:
![image](https://user-images.githubusercontent.com/6095671/31080674-5f5bcb82-a757-11e7-8391-a9345dc34b10.png)

**Comment by ralarcon** [comment]
In that case looks like a VS issue deploying to the emulators. We can wait till you have an answer from the VS team regarding the exception you are getting right now and check if everything runs fine once you can deploy to the emulators.

**Comment by crutkas** [comment]
@ralarcon did we ever follow up on this

**Comment by zipswich** [comment]
I believe everything is fine now.
