### ISSUE TITLE
Project creation error running wizard on VS 15.3 having installed VS15.4 side by side

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1210]
During the test for #1191 and having both VS2017 15.3 and the preview version 15.4 installed in the same box, the projects not being properly created and you get the following exception:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TemplateEngine.Orchestrator.RunnableProjects, Version=1.0.0.304, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.TemplateEngine.Orchestrator.RunnableProjects, Version=1.0.0.304, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by ralarcon** [comment]
After investigation and support from the TemplateEngine this is occurring because the same .templateengine hive is being shared between 15.3 and 15.4. When the template engine is initialized, it references the hive under _%userprofile%\.templateengine\host\version._

We include the WTS VSIX version as host running but do not add a differentiatior for the VS host version. This required to be included to avoid the sxs execution issues.

**Comment by sibille** [comment]
Verified on dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.2
