### ISSUE TITLE
Show original and postaction file on MergeFailureType.KeyAlreadyDefined merge conflicts.

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1212]
Show both resource dictionary files (original and failedpostaction) in this case to be able to compare changes easily.

**Comment by mvegaca** [comment]
Added on #1222 to Wizard.
![image](https://user-images.githubusercontent.com/5556784/31135643-ec2fa9ac-a865-11e7-9bc6-25de2b0bdc52.png)

There is an issue, if there three styles are different, warning text only specifies the first one.

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
