### ISSUE TITLE
Right-Click needing double compile

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1215]
### Repro steps

Create a base application from WTS without referencing the Telerik controls.
Right click add and include a page with Chart

### Expected Behavior

Application compiles

### Actual Behavior

VS throws a binding error.  Compiling again fixes issue.

## System

* **VS Version:**  15.4 preview 3
**Wizard:** 1.3.17255.1
**Templates:** 1.3.17255.1
* **Windows Build:** 16299

**Comment by mrlacey** [comment]
Sounds like right-click isn't doing a package restore when it needs to.

**Comment by dgomezc** [comment]
The problem occurs when add a page and auto-opening the xaml file.

The Visual Studio Xaml Viewer overwrite the temp file PageName.g.i.cs in obj/x86/Debug/Views folder and delete this line: "private IChartPage_Bindings Bindings;" This breaks the bindings in the page.

To fix it we have chosen to clean solution by adding csproj references in post-actions.

Another option is not auto-open xaml file. If xaml file is manually opened, overwrite does not occur.

**Comment by sibille** [comment]
Verified on dev-nightly: 
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
