### ISSUE TITLE
Problem with camera rotation

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1219]
While testing an application generated in a windows 10 mobile, there is problem with the rotation:

Taking a picture with the front camera, the preview image is rotated 90 degrees.
![front_vertical](https://user-images.githubusercontent.com/12777039/31127054-01cd4818-a84e-11e7-827f-c062af5bb649.png)

Using the back camera and putting it in landscape mode, the preview of the capture seems to be in vertical mode and see two bars on the sides.
![back_horizontal](https://user-images.githubusercontent.com/12777039/31127062-05b17cb0-a84e-11e7-8ba5-c256856ce724.png)

The screenshots has been taken with the device emulator but also has been verified with a physical device.

@CarteKiwi

**Comment by ralarcon** [comment]
x-ref: #908

**Comment by CarteKiwi** [comment]
I will have a look at this soon.

**Comment by dgomezc** [comment]
Hi @CarteKiwi, did you had some progress with this?. We have reached code complete and just want to know if this will be fixed for 1.4 or not.

**Comment by CarteKiwi** [comment]
Hello @dgomezc , I'm sorry, I didn't get time to work on it. 
I'll do my best to fix it tonight (in 3 hours).

**Comment by ralarcon** [comment]
Progress as you can. We can help out with this, the only thing is that leave all things in a PR and we can continue if some things are left.

**Comment by dgomezc** [comment]
#1271 solves the problem of preview image rotating when take a photo with the front camera.

**Comment by CarteKiwi** [comment]
Well done. I have tested the #1271 and it solved this issue. Thanks for your help.

**Comment by ralarcon** [comment]
Rotation issue verified. Closing now.
