### ISSUE TITLE
Review ViewModelLocator instatiation in MVVMLight

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1228]
We have some workarround to enable functionallity in MVVM templates because the ViewModelLocator is based in SimpleIoC which is not thread safe. 

The intention is to review if it is possible to make ViewModelLocator safe to avoid the workarrounds.

**Comment by ralarcon** [comment]
After reviewing the Settings Page workarround in place for #1053 we found that it is not easy to discover why the page behaves erroneously when uses x:Bind.

Once we are using x:Bind with MVVMLight for the settings page, we got the StackOverFlowException mentioned in #1053.

We have found that changing the binding Mode from TwoWay to OneWay, solve the StackOverFlowException. More details in #1053.

**Comment by sibille** [comment]
Verified on dev-nightly:
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
