### ISSUE TITLE
Sub Menus required

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/WindowsTemplateStudio#1237]
### Expected Behavior

Hello,

for Windows Template Studio Projects, i searching for a Solution, that allowed me on "Hamburg Menü" create Submenus.

Did have anywhere a solution?
## System

* **VS Version: 2017
* **WTS Wizard Version: 1.3.17255.1
* **WTS Template Version: 1.0.0
* **Windows Build: 15063

**Comment by crutkas** [comment]
You mean more in tune to a tree view?  NavView is a single level typically.

**Comment by harrypotter06** [comment]
Yes, that i mean. So, no Solution about that?

**Comment by crutkas** [comment]
Possible but you would have to swap the control out and do some alterations. 

Good idea for another global nav project type.

**Comment by mvegaca** [comment]
You can checkout this GitHub repo and sample app that uses a ShellControl with submenus
https://github.com/wasteam/waslibs

**ShellControl**
https://github.com/wasteam/waslibs/tree/master/src/AppStudio.Uwp/Controls/ShellControl
**Sample App**
https://github.com/wasteam/waslibs/blob/master/samples/AppStudio.Uwp.Samples/AppShell.xaml

![image](https://user-images.githubusercontent.com/5556784/31273526-60aab49a-aa8f-11e7-8958-42fd715d185f.png)

**Comment by harrypotter06** [comment]
Thank you all, for the support. I think, i will made a Spezial Solution ;)
