### ISSUE TITLE
Camera page is missing UWP Community Toolkit license

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1251]
Camera page using BoolToVisibilityConverter from UWP Community Toolkit

**Comment by sibille** [comment]
BoolToVisibilityConverter is no longer needed since anniversary update. 
https://social.technet.microsoft.com/wiki/contents/articles/34846.uwp-compiled-binding-windows-10-anniversary-update.aspx
Will remove dependency and convertet

**Comment by crutkas** [comment]
good catch!

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.1
