### ISSUE TITLE
Going back to first page deletes all pages and features selected

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1266]
1. Create a project with any project and frameworktype
2. Click next
3. Add some pages
4. Click back
5. Click next.

Result: 
All pages are deleted

Expected result:
Nothing should be deleted unless you change framework or project type

Wizard: 0.14.17283.65001
Templates: 0.14.17283.1

**Comment by mvegaca** [comment]
Fixed on #1266
