### ISSUE TITLE
Caliburn Micro is not highlighting text of selected item in SplitView

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1270]
Caliburn:
![image](https://user-images.githubusercontent.com/24698018/31384492-89d72f14-adbf-11e7-8d08-e19f1b0fd3dd.png)

Other framework
![image](https://user-images.githubusercontent.com/24698018/31384534-ab7d7ea2-adbf-11e7-894f-6399079f0e34.png)

## System
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17286.65001
Templates: 0.14.17286.1
