### ISSUE TITLE
Failed to create new project

### ISSUE THREAD

**Issue by mjmeans** [Microsoft/WindowsTemplateStudio#1281]
Updated VS and WTS today. Right click solution > Add new project. .NET Framework 4.6.1. C#. Windows Template Studio. App name set to App1.IOT. Selected Navigation Pane, MVM Basic. Next. Settings +, default name, check. Toast Notification +. Create.

Project creates and will not build. Multiple errors. MainPage.xaml.cs looks like this:

```
using Param_ItemNamespace.ViewModels;

using Windows.UI.Xaml.Controls;

namespace Param_ItemNamespace.Views
{
    public sealed partial class wts.ItemNamePage : Page
    public sealed partial class BlankViewPage : Page
    {
        public wts.ItemNameViewModel ViewModel { get; } = new wts.ItemNameViewModel();
        public BlankViewPage()
        {
            InitializeComponent();
        }
    }
}
```

**Comment by mjmeans** [comment]
This happened after I updated VS. I already updated WTS and it worked. Then I updated VS 2017 to 15.4.0 and it failed. Now when I check extensions and WTS now shows 1.0.17142.1 but there is an update again to 1.3.1725.1. So maybe the VS update reverted to an older WTS? Very strange. I will update WTS to 1.3.1725.1 again and try it again.

**Comment by mjmeans** [comment]
After re-updating WTS, the generated project builds. This can be closed. It seems that after updating VS 2017 you must re-check extensions to make sure WTS has not reverted.

**Comment by sibille** [comment]
Glad this is working for you now!! 
Thanks for your help!!
We'll try to repro this on a test machine.

**Comment by ralarcon** [comment]
Closing this as not possible to repro and user reports it was fixed after updating WTS.
