### ISSUE TITLE
NavigationMenuItem is opaque, please make it transparent

### ISSUE THREAD

**Issue by Alvaromah** [Microsoft/WindowsTemplateStudio#1284]
When changing the Pane background in the HamburgerMenu, the menu items maintain the default color.

Changing NavigationMenuItem background color to Transparent solve this issue.

See attached image.

![menuitems](https://user-images.githubusercontent.com/16006835/31434575-fd3f5b8a-ae7c-11e7-80cd-e707fdf6edfb.jpg)

**Comment by mrlacey** [comment]
Unfortunately, in the current version, there's a reason that it has its own background color. (It's hiding something else 😉)

You can change the background color yourself if you need to.

In the next version we'll be adding support for the Acrylic/fluent styling of the control and so this will remove the issue for apps generated in the future.

**Comment by crutkas** [comment]
We are currently taking advantage of the UWP toolkit control.  This will provide backwards compatibility. When they handle the (hard) flipping between the new navview and their control, this should just light up if you are on FCU or greater.
