### ISSUE TITLE
Page: Chart

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#129]
Having a page with a chart would be swell.  We could use the telerik controls

**Comment by mrlacey** [comment]
If happy with the default/sample data can close this out soon

**Comment by mrlacey** [comment]
changing milestone as already in as part of 1.1

**Comment by mrlacey** [comment]
Still to do here:
- Change to a bar chart
- add comment link to http://docs.telerik.com/windows-universal/controls/radchart/getting-started 
- update description.md with more info and link(s)

**Comment by mrlacey** [comment]
Closing as now in dev nightly and seems to be working fine.
