### ISSUE TITLE
Review the use of lock {} in NavigationServiceEx. It may cause a Deadlock.

### ISSUE THREAD

**Issue by Alvaromah** [Microsoft/WindowsTemplateStudio#1291]
For example, the following method in NavigationServiceEx may cause a deadlock:

```
public bool Navigate(string pageKey, object parameter = null, NavigationTransitionInfo infoOverride = null)
{
    lock (_pages)
    {
        if (!_pages.ContainsKey(pageKey))
        {
            throw new ArgumentException($"Page not found: {pageKey}. Did you forget to call NavigationService.Configure?", "pageKey");
        }

        var navigationResult = Frame.Navigate(_pages[pageKey], parameter, infoOverride);
        return navigationResult;
    }
}
```
The call to Frame.Navigate() inside the critical region is risky, since several methods are executed in this method call (i.e: Page constructor, OnNavigatedTo, etc.). For example, a page that calls Navigate() inside OnNavigtedTo() may cause a deadlock.

A best practice for using critical regions is to use the locked resource only when required and avoiding unnecessary calls inside the lock.

The following implementation of this method is more safe:

```
public bool Navigate(string pageKey, object parameter = null, NavigationTransitionInfo infoOverride = null)
{
    Type page;
    lock (_pages)
    {
        if (!_pages.TryGetValue(pageKey, out page))
        {
            throw new ArgumentException($"Page not found: {pageKey}. Did you forget to call NavigationService.Configure?", "pageKey");
        }
    }
    var navigationResult = Frame.Navigate(page, parameter, infoOverride);
    return navigationResult;
}
```

Hope this helps.

**Comment by ralarcon** [comment]
@Alvaromah Thanks for pointing this. Do you want to fix this and make a PR? If not, we can take care. Please let me know.

**Comment by Alvaromah** [comment]
Yes I will. Regards.

**Comment by ralarcon** [comment]
Verified in dev-nightly
Wizard: 0.14.17292.65001
Templates: 0.14.17292.1
