### ISSUE TITLE
WebView navigation buttons does not work in Caliburn.Micro

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1299]
### Repro steps

- Create an app with tabbed project type and caliburn micro
- Add WebView page
- Luanch the app and navigate to other pages
- Try go back with bar buttons
### Expected Behavior
- WebView can go back

### Actual Behavior
- Navigation buttons are disabled

**Comment by mvegaca** [comment]
Fix on #1302

**Comment by ralarcon** [comment]
Verified in PreRelease: Wizard 0.9.17286.3, Templates: 0.9.17286.3

**Comment by mvegaca** [comment]
Wizard: 0.9.17286.3
Templates: 0.9.17286.3
