### ISSUE TITLE
Map page add your location multiple times

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1300]
### Repro steps
- Create an app with tabbed project type and Caliburn.Micro
- Add map page
- navigate between pages

### Expected Behavior
- Map page shows your location

### Actual Behavior
- Map page shows your location multiple times

![image](https://user-images.githubusercontent.com/5556784/31538854-28d09b98-b007-11e7-8192-eeba66d2385e.png)

**Comment by mvegaca** [comment]
The problem is that OnActivate method is invoked on each navigation but the MapControl instance is the same.
What is the best approach to solving this in Caliburn.Micro @nigel-sampson ? Could we add a bool isMapInitialized to run initialization only one time?

**Comment by nigel-sampson** [comment]
It can be shifted to the `OnInitialized` overload which doesn't get called multiple times (only on first activation).

**Comment by ralarcon** [comment]
Verified in pre-release 0.9.17289.03
