### ISSUE TITLE
Update FirstRun & WhatsNew prompts to use Community Toolkit

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1304]
Depends on Community Toolkit v2.1

Once the new version of the toolkit is released, update the **First Run** and **What's New** prompts to use the logic from the toolkit that was recently ported from the WTS code.

X-Ref https://github.com/Microsoft/UWPCommunityToolkit/issues/1505 & https://github.com/Microsoft/UWPCommunityToolkit/blob/master/docs/helpers/SystemInformation.md

**Comment by mrlacey** [comment]
toolkit v2.1 due Nov22 ([ref](https://github.com/Microsoft/UWPCommunityToolkit/milestones))

**Comment by mrlacey** [comment]
Please leave this open for the equivalent VB changes to be made also. (Can reassign to me to do this if you wish)

**Comment by mrlacey** [comment]
VB equivalents in progress

**Comment by ralarcon** [comment]
Verified in
Wizard: 0.16.18015.65002
Templates: 0.16.18015.4
