### ISSUE TITLE
txt encoding info artifacts in 1.3

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1313]
<img width="622" alt="1 3_characterencodingbug" src="https://user-images.githubusercontent.com/1462282/31664074-f306487c-b33b-11e7-96c2-d2c02b182682.PNG">

Noticed this during a presentation.  I know we noticed this during localization as well

**Comment by ralarcon** [comment]
This is fixed now in dev - nightly / pre-release and ready to be released. We shipped 1.3 with the wrong characters. 

Now we verify this will not happen as part of the templates verifications.
