### ISSUE TITLE
Image gallery wrong behavior if navigate to other page while displaying the detail

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1317]
### Repro steps
1. Generate and app with a Main (blank) page and an ImageGallery page.
2. Build and run
3. Navigate to the ImageGallery page
4. Click on one image
5. While diplaying the detail, navigate await to the "Main" page.

### Expected Behavior

The navigated page (Main) show up inmediatly and the image do not stay.

### Actual Behavior

The image stay for a moment under the "main" page and then disappear.

![image](https://user-images.githubusercontent.com/2638875/31762170-a906841e-b4ba-11e7-88bb-83e1ef8226d0.png)

## System
Wizard: 0.14.17292.65001
Templates: 0.14.17292.1

**Comment by mvegaca** [comment]
Fixed on #1326

**Comment by ralarcon** [comment]
Verified.
Wizard: 0.14.17300.65001
Templates: 0.14.17300.2
