### ISSUE TITLE
Unable to update to latest release v1.4 if .NET 4.7 is not present

### ISSUE THREAD

**Issue by OtisRanger** [Microsoft/WindowsTemplateStudio#1319]
I have just updated my version of Visual Studio 2017 to 15.4.0 and was notified that there is a new version of WTS to install. When I do this it downloads the package and then states that it is unable to update. The message states "The extension 'Windows Template Studio' requires a version of the .NET framework that is not installed.

I can provide log file if needed

**Comment by ralarcon** [comment]
You need to install the .NET Framework 4.7 Developer Pack (or higher). You can do it from: https://www.microsoft.com/net/targeting.

**Comment by ralarcon** [comment]
@OtisRanger let me now if this solves the issue.

**Comment by OtisRanger** [comment]
Hello Raúl
Thanks for the info, but surely the update should do this? Or at least warn you that you would have to do this? I am in the process of downloading and installing it now so will let you know

**Comment by ralarcon** [comment]
In the log you mention you should find that the .NET framework required is not present and the .NET Framework required is 4.7 (not so direct). Unfortunatelly, this is the default behaviour for the extensions not directly depending on us.

Let me know if it works and we can update the title of this issue just in case other users experience the same.

**Comment by OtisRanger** [comment]
Hello
Downloading and installing the 4.7 developer pack has allowed the update to happen. I am now slightly worried that either 
a) the home page of this site is not updated or
b) I have installed an unsafe update
as the version that I have just installed is NOT the version that has been deemed as release

**Comment by ralarcon** [comment]
The home page is not updated jet, updating right now. The update is safely signed with an official, trusted Microsoft certificate and distributed by the Visual Studio Marketplace.

**Comment by OtisRanger** [comment]
Phew :1st_place_medal: 
Thanks for your help on this

**Comment by ralarcon** [comment]
Now the version is updated too in the home page.

**Comment by crutkas** [comment]
feel like this can be closed
