### ISSUE TITLE
Latest templates update prevent previous Windows Template Studio versions to keep working

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1321]
### Symthoms

You have installed Windows Template Studio v1.3 or v1.2 installed and you try to create a new project or add a new page or feature to your existing project by using Windows Template Studio and get the following error:
![image](https://user-images.githubusercontent.com/2638875/31788143-22400e38-b50e-11e7-8d20-f96a23bb1e3b.png)

If you open the output window through Menu ->View -> Output Window (Alt+Ctrl+O)
<img src="https://user-images.githubusercontent.com/2638875/31788303-9f18258a-b50e-11e7-8e46-3d32fc9e229d.png" width="300"/>

You will see the following error:
_Microsoft.Templates.Core.RepositorySynchronizationException: Error syncing templates. Status: 'Acquiring' ---> Microsoft.Templates.Core.Packaging.InvalidSignatureException_

![image](https://user-images.githubusercontent.com/2638875/31788458-0f5c70b2-b50f-11e7-83d0-66ff01dd4dc5.png)

### Root Cause
The latest Templates content are signed with a renovated certificate. In order to avoid tampering Windows Template Studio only allows content from trusted signed sources and the certificate used to sign the latest Templates content is not recognized.

### Recommended action
Update to the lastest Windows Template Studio version: v1.4.17291.5.

You should have a notification:
<img src="https://user-images.githubusercontent.com/2638875/31789444-69a2175e-b512-11e7-8cf3-894a7835d576.png" width="300"/>

Or you can do it by updating the extension thru Visual Studio Extensions and Tools.
<img src="https://user-images.githubusercontent.com/2638875/31789513-9d417ca8-b512-11e7-93db-f6ae6bb41790.png" width="300"/>

![image](https://user-images.githubusercontent.com/2638875/31789588-e4118eac-b512-11e7-9060-550956961dcd.png)

Or by downloading the latest version from the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio).

The latest Windows Template Studio version have the following requirements:
* .NET Framework 4.7 Developer Pack (or higher). Get the latest update [here](https://www.microsoft.com/net/targeting).
* Visual Studio 2017 Update 3 (or higher). Get the latest update [here](https://www.visualstudio.com/downloads/).

### Workarround
If you don't want to update your current installed .NET Framework version and / or the Visual Studio version, follow this steps to continue working with your current Windows Template Studio version:
1. Locate the configuration file (you can identify the path from the Windows Template Studio output)
   Tipically in the path: `C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\_<Visual Studio Edition>_\COMMON7\IDE\EXTENSIONS\_<Installation_Guid>_\WindowsTemplateStudio.config.json`
2. Edit the `WindowsTemplateStudio.config.json` file with an editor of your preference.
3. Add the following certificate pin to the `AllowedPublicKeysPins`:
`2A0A69F1AB9BB46A8AE3563B72702FD6CCB16ECBF669D62A7DC92D217A084E318EC8BB2AE87A4A2C6855BDB9C0F4FD93D77E802AAACDDEB795C2EF718D7D4890`

The resulting file should look like the following:
``` json
{
  "Environment": "Pro",
  "CdnUrl": "https://wts.azureedge.net",
  "RemoteTelemetryKey": "AIF-00b714d7-d0ea-466f-a809-af3d8a243036",
  "LogFileFolderPath": "WindowsTemplateStudio\\Logs",
  "CustomTelemetryEndpoint": "https://vortex.data.microsoft.com/collect/v1",
  "RepositoryFolderName": "WindowsTemplateStudio",
  "BackupFolderPath": "WindowsTemplateStudio\\Backups",
  "TempGenerationFolderPath": "WTSTempGeneration",
  "DiagnosticsTraceLevel": "Information",
  "GitHubDocsUrl": "https://github.com/Microsoft/WindowsTemplateStudio/tree/master/docs/",
  "DaysToKeepTempGenerations": 5,
  "DaysToKeepDiagnosticsLogs": 5,
  "VersionCheckingExpirationMinutes": 1440,
  "AllowedPublicKeysPins": [
"14CAC54E3A89855AF3F33C6C2F88E389094305F15EC3E7CC18844E8ABD4651A8992710E005DE189A313039064B082D62D41077B44BEFA4D837C1FC320083D422",  
"51E93470FD838DFCE5F4ADF0D7750D2B66635677499A73160B9CB3BA84884A9EBA5F4E80C346323C0F61D2A8EDDC8EE5E02E7F186D13C953270F68AEB44CFE3D",
"8A79BF09C49440C614229A2338384348443353A4B3DBA4AD46EDC0FE1054ED220A0D3445783493869186DEADBF0D9D8627E0EAC2D37475C9EC991A0324038EA4",
"2A0A69F1AB9BB46A8AE3563B72702FD6CCB16ECBF669D62A7DC92D217A084E318EC8BB2AE87A4A2C6855BDB9C0F4FD93D77E802AAACDDEB795C2EF718D7D4890"
  ]
}
```

**Comment by crutkas** [comment]
I think if we are erroring here, why wouldn't the system throw a warning versus not work with the older content

**Comment by ralarcon** [comment]
Yes, we need to better handle this situation. Adding to 1.5 milestone to avoid this happen in the future.

**Comment by ralarcon** [comment]
Verified in nightly v0.14.17310.1

**Comment by crutkas** [comment]
This fixes the underlying issue but doesn’t fix the issue outlined here.  The error does not tell a user what happened as well or what to do.  1391 feels to be just a repeat of this issue

**Comment by ralarcon** [comment]
Yes, that is complex. 

The error is in the output, but we are not able to exactly tell the user what need to do as the root cause of the problem could vary from an issue with the pin (like now) to the template package being tampered, so I do not see the way to tell the user how to solve it. We can point the user to the git hub repo site, and publish the pin certificates we allow. 

We are now preventing for failure and let the user continue working if possible with downloaded content he have. 

Finally, we need to improve the strategy and remote version handling as  #1376 try to reflect.
