### ISSUE TITLE
ThemeSelectorService Compiler Errors

### ISSUE THREAD

**Issue by Joebeazelman** [Microsoft/WindowsTemplateStudio#1322]
I update my project and added a settings file using the latest release.  When I compile it, I get the following errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'ThemeSelectorService' does not contain a definition for 'GetSystemControlForegroundForTheme'	RateQuoter	119	Active
Error	CS0117	'ThemeSelectorService' does not contain a definition for 'OnThemeChanged'	RateQuoter	108	Active

ThemeSelectorService.cs doesn't define OnThemeChanged or GetSystemControlForegroundForTheme. I tried to find the most recent copy of ThemeSelectorServce.cs on github and they don't define them either.

**Comment by crutkas** [comment]
@Joebeazelman what was your original base?  the diff should have added in any needed code adjustment.  Was your project based in WTS 1.2?

**Comment by Joebeazelman** [comment]
I am not sure.  I downloaded and installed it a couple of weeks ago if that helps.  Given that it is a generated file that I never altered, where can I find a clean version so I can get back to work?

**Comment by mvegaca** [comment]
On October 12, I've added some changes on ThemeSelection code, removing parts of the code that were not still necessary.
GetSystemControlForegroundForTheme was removed from ThemeSelectorService. It was used initialy to apply theme changes on ShellNavigationItem but it was also updated using a theme brush that apply theme changes by default.

I recommend you to look at the [pull request changes](https://github.com/Microsoft/WindowsTemplateStudio/pull/1136/files) and compare with the code in your app.

- Issue #1082
- Pull Request #1136

**Comment by ralarcon** [comment]
Can you provide your current project files? (you can attach a file to this thread). Other option is to give us some repto steps including: initial project configuration (project type and framework); intial pages and features added (if possible); right click actions which lead to this error.
Other helpful info is: wts version (you can pick it up from the wizard by clicking in the left upper corner) and visual studio version (you can pick it from the help / about menu).

**Comment by Joebeazelman** [comment]
Here's the setting from VS:

```
> Microsoft Visual Studio Community 2017 
> Version 15.4.0
> VisualStudio.15.Release/15.4.0+27004.2002
> Microsoft .NET Framework
> Version 4.7.02046
> 
> Installed Version: Community
> 
> Visual Basic 2017   00369-60000-00001-AA091
> Microsoft Visual Basic 2017
> 
> Visual C# 2017   00369-60000-00001-AA091
> Microsoft Visual C# 2017
> 
> Visual C++ 2017   00369-60000-00001-AA091
> Microsoft Visual C++ 2017
> 
> Visual F# 4.1   00369-60000-00001-AA091
> Microsoft Visual F# 4.1
> 
> Application Insights Tools for Visual Studio Package   8.9.00809.2
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017   15.0.30925.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Core Razor Language Services   1.0
> Provides languages services for ASP.NET Core Razor.
> 
> ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   15.0.30915.0
> Azure App Service Tools v3.0.0
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Cookiecutter   3.0.17262.1
> Provides tools for finding, instantiating and customizing templates in cookiecutter format.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JavaScript UWP Project System   2.0
> JavaScript UWP Project System
> 
> JetBrains ReSharper Ultimate 2017.2.2    Build 109.0.20171006.122324
> JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.
> 
> Markdown Editor   1.11.214
> A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.
> 
> MenuCommands Extension   1.0
> MenuCommands Visual Studio Extension Detailed Info
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1
> 
> Microsoft Continuous Delivery Tools for Visual Studio   0.3
> Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> NuGet Package Manager   4.4.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Python   3.0.17262.1
> Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
> 
> Python - Django support   3.0.17262.1
> Provides templates and integration for the Django web framework.
> 
> Python - IronPython support   3.0.17262.1
> Provides templates and integration for IronPython-based projects.
> 
> Python - Profiling support   3.0.17262.1
> Profiling support for Python projects.
> 
> RelayCommand Extension   1.0
> RelayCommand Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools   15.1.61707.200
> Microsoft SQL Server Data Tools
> 
> TypeScript   2.3.5.0
> TypeScript tools for Visual Studio
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio tools for CMake   1.0
> Visual Studio tools for CMake
> 
> Visual Studio Tools for Universal Windows Apps   15.0.27004.2002
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Win
```

dows 10 Software Development Kit.

**Comment by ralarcon** [comment]
What about your code, can you share it?

**Comment by Joebeazelman** [comment]
I just regenerated my application from scratch and the errors didn't appear.  I made some modification to some files and rearranged the data.  Perhaps the application got confused.  Unfortunately, I have already applied the changes manually and I don't have an old version.  

I would be happy to share code with you.  Do you have a place where I can dump it without exposing it to the world?

**Comment by ralarcon** [comment]
if you have the code which have failed (even if repared) you can drop me an email to ralarcon@microsoft.com (removing bin and obj directories must leave just plain text files, so a zip should not be quite big).

**Comment by Joebeazelman** [comment]
Sorry, but Windows keeps giving me "File not found or no read permission."  when I try to compress it into a zip file.  I am using my Microsoft account like a good boy, hoping Microsoft won't abuse me. I also tried to give my account more permissions, but it says "An error occurred while applying security information to .... Failed to enumerate objects in the container. Access denied." 

Great job Microsoft!  You buffoons spray cryptic error messages at your users.  Even the technical elite, such as myself, have no clue what this means.  Why don't I have administrator privileges when I am an administrator?  It could at least clue me into what permission I need. Maybe this is why your generator thingumabob didn't work because only hackers and malware can access your files! All this security and this crappy OS still gets hacked!  It's been several decades now and you clowns can't get an operating system working! You're a multi-billion dollar company with an enormous development budget!  

Just wasted most of my work day over this!

**Comment by ralarcon** [comment]
I understand you feel upset and I'm so sorry for that. Looks like you have some files locked by a process in the folder you try to zip. Have you tried restaring the computer?

If you want, instead of the whole source code, you can share the .csproj project file of the original failling project. This would allow use to figure out more of the situation which would lead to your error.

As your orignal issue has been solved. I will close this issue now.

Thanks.
