### ISSUE TITLE
Include platform concept in WTS (catalog redesign)

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1328]
Include platform in templates repository catalog and wizard.
Filter projectTypes and frameworks by platform.

We initially have two options in mind: 
- Uwp: Uwp Native project
- Uwp + Mobile xPlat: Uwp Native + Xamarin Forms iOS and Android projects

**Comment by mrlacey** [comment]
Why not keep it simple. Just "UWP" and "XamForms"?

Names built of combined elements risk getting very long in future. (Think of how long some PCL identities got)

Generic names like "xPlat" also risk causing confusion in the future if support for other frameworks was added.

**Comment by ralarcon** [comment]
Yes, we are finishing the requirements / needs as the intial idea was to have always a UWP native project within the xPlat solutions... But this is pending of having the final decission. Anyway it could be "Uwp + Xamarin Forms"...

**Comment by ralarcon** [comment]
We will have two platforms:
* Uwp
* Xamarin Forms

The templates catalog will be updated to have a separation allowing to to handle both platforms (a future ones):

|───Uwp
│   ├───Features
│   ├───Pages
│   ├───Projects
│   └───_composition
├───Xamarin
│   ├───Features
│   ├───Pages
│   ├───Projects
│   └───_composition
└───_catalog

Key points for the new template repository
* This disposition will allow to support sharing code among Xamarin Forms and Native templates. 
* We will include the "wts.Platform" attribute in the templates to allow filtering and composition among the catalog.
* This repository reorganization will impact current all templates as will  be required to introduce the "wts.Platform" attribute
* If required, we can include "_shared" folder to share code among all the platforms but, by now, and after some investigation we haven't seen important elements to be shared.

Pending to investigate the most effective way to load and sync the templates depending on the platform.

**Comment by ralarcon** [comment]
In order to define the entry points, the platform will not be an option in the wizard for the user. If the user starts the wizard from "Windows Universal", Uwp platform will be selected. If the user starts from "Cross Platform", Xamarin forms will be selected.

**Comment by crutkas** [comment]
@ralarcon agreed.

**Comment by mvegaca** [comment]
We also need to consider setting a new catalog for categories to establish the order with no language dependency

xRef: #1421

We can use this structure for Categories catalog:

```json
[
    {
        "wts.type": "page",
        "categories":
        [
            {
                "name": "None",
                "order": "0"
            }
        ]
    },
    {
        "wts.type": "feature",
        "categories":
        [
            {
                "name": "None",
                "order": "0"
            },
            {
                "name": "ApplicationLaunching",
                "order": "1"
            },
            {
                "name": "ConnectedExperiences",
                "order": "2"
            },
            {
                "name": "UserInteraction",
                "order": "3"
            },
            {
                "name": "BackgroundWork",
                "order": "4"
            }  
        ]
    }    
]
```

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.18.18110.2
Wizard version: 0.18.18110.2
