### ISSUE TITLE
Add VB version of Camera Page

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1335]
Follow on from #863 

Port Camera page templates to VB.

**Comment by mrlacey** [comment]
Needs thorough manual testing to verify everything works as expected. Waiting to see if anyone who worked, tested, or verified the C# version has a list.

**Comment by ralarcon** [comment]
@dgomezc would help here for sure.

**Comment by dgomezc** [comment]
### Camera page tests
- [ ] Open camera page in a device with active camera -> The page show previsualize of camera and capture button is active.
- [ ] Open camera page in a device without camera or disabled camera -> The page show "no video capture devices found" message and capture button is disable.
- [ ] If device does not have back camera -> Switch camera button is not visible.
- [ ] If device have front and back cameras -> Switch camera button is visible.
- [ ] If preview is from the front camera and click in the switch camera button -> Switches the preview to the back camera.
- [ ] If preview is from the back camera and click in the switch camera button -> Switches the preview to the front camera.
### Capture tests
- [ ] Click in capture button -> A picture is created and displayed in the bottom right side with the correct orientation.
- [ ] Turn device to the left -> The buttons and the preview have the correct orientation.
- [ ] With the device turned to the left, click in capture button -> A picture is created and displayed in the bottom right side with the correct orientation.
- [ ] Turn device to the right -> The buttons and the preview have the correct orientation.
- [ ] With the device turned to the right, click in capture button -> A picture is created and displayed in the bottom right side with the correct orientation.

** Capture tests have to be passed to the front and back camera.

**Comment by mrlacey** [comment]
thanks @dgomezc

**Comment by mrlacey** [comment]
All camera tests done with VB & CS versions of the code and output behaved the same on both.
Also fixed wrapping of camera error message on narrow /mobile screens

**Comment by mrlacey** [comment]
Verified in 
Wizard: 0.14.17325.65001
Templates: 0.14.17325.1
