### ISSUE TITLE
Create VB templates for Drag Drop Source Feature 

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1343]
Follow on from #863 
Depends on #820

**Comment by mrlacey** [comment]
changing milestone to match dependency

**Comment by ralarcon** [comment]
@mrlacey we have the Drag and Drop feature pending to be approved so probably it will be on 1.6, but is on 2.0 the milestone for #820 should be 1.6 (just in case you want to review it)

**Comment by mrlacey** [comment]
Verified in 
Wizard: 0.14.17347.65001
Templates: 0.14.17363.1
