### ISSUE TITLE
README.md is out of date

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1345]
The main [README.md](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/README.md) document was not updated for the m1.4 release. This document is important as it is the [first page seen](https://github.com/Microsoft/WindowsTemplateStudio) when coming to the repository.

Changes needed:
- Update image to also include CaliburnMicro as a framework option.
- Add CM (with appropriate link) as an option under App Frameworks in the features section.
- Add known issue with installing multiple different version of the VSIX (nightly/pre-release/release) in the same VS instance.
- Update the versions of Win10 targetted in Principle 6.

**Comment by rootasjey** [comment]
Hello,

I can make these changes if needed.

**Comment by crutkas** [comment]
@rootasjey, if you want to take a stab, create a PR!

**Comment by crutkas** [comment]
Merged, thanks for helping out @rootasjey!  we always welcome help
