### ISSUE TITLE
Caliburn.Micro page and feature descriptions

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1349]
Should be Microsoft Community.

![image](https://user-images.githubusercontent.com/1462282/31964635-89ac3c5a-b8b9-11e7-9924-d98a0a0f7c3b.png)

**Comment by dgomezc** [comment]
Verified on dev-nightly:
Wizard: 0.14.17310.65001
Templates: 0.14.17310.1
