### ISSUE TITLE
dev branch readme CI img broken

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1352]
![image](https://user-images.githubusercontent.com/1462282/32006259-23738f5e-b95b-11e7-8dd0-3fdba411abbb.png)

**Comment by ralarcon** [comment]
I saw few times the badge not appearing in the first load. Can you "reload" the page? I'm viewing it properly.

**Comment by crutkas** [comment]
weird loads now.
