### ISSUE TITLE
Make "Right-click Add" work on a folder or in the Add->New Item... Dialog

### ISSUE THREAD

**Issue by enghch** [Microsoft/WindowsTemplateStudio#1353]
## Usability Feedback:

* **Overview:** 
I had some trouble finding the Right-click to Add functionality. In fact, it was hard to know if it even existed. My first assumption was that I could right-click on a folder within my WTS project and I'd see a menu item called something like "Add Template Studio Item." When I didn't see that I assumed it would be inside of the normal "Add->New Item..." menu. I looked though that list without seeing anything. I started to assume it just didn't exist. Finally @crutkas pointed me in the right direction. I think it would be much easier to find in one of those places. Just some feedback.

**Comment by ralarcon** [comment]
@enghch Thanks for your feedback, I'm going to add to the 1.5 milestone in other to investigate if there is a chance of rise up the "Add New Page / Feature" at any item / folder in the project.

One question: Most of the pages / features generates multiple items in different folders... will it be clear if we allow launch the wizard in any project item (folder / file) that this will generate elements at the Project level?

**Comment by enghch** [comment]
That's a good question that I was asking myself as well. I appreciate that in those cases it could create confusion because the user might not know where the new items went. Not sure how to address that. Maybe a popup that says "Your new items were added here" then list the locations? Just a thought.

**Comment by crutkas** [comment]
My thought is it would generate where WTS would expect.  Our system makes assumptions on a lot of things and I fear if we changed that the testing and edge cases we would have to do.

what happens when something adds in 10 files?

**Comment by ralarcon** [comment]
It does not make sense to allow users to see the "Wts RightClick menu" on single items. What worries to me too is that if we allow the menu to be shown on folders, this might be confusing as may lead the users to think that the generated files will be contained within that folder and, by definition, this will not be true (this is because we only show the menu at project level).

Maybe we can add a text somewhere in the wizard indicating that the users will be allowed to add new pages and features after a new project is generated using the right-click over the project...

**Comment by sibille** [comment]
I think we should include instructions on how to use right click on project in the docs (f.ex. on [getting started page](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#public-release-instructions)

**Comment by ralarcon** [comment]
After reviewing pros and cons we think that the documentation should be enought to guide the users throught the usage of the "right-click" in WTS.
