### ISSUE TITLE
Need Microsoft Ads (banner and interstitial) as a WTS component to easily embed in a page

### ISSUE THREAD

**Issue by sshaik37** [Microsoft/WindowsTemplateStudio#1354]
## For new Features:

* **Overview:** 
Almost all the free apps needs ads to be implemented in them. If WTS can create an Microsoft Ads extension/component/feature to plug into app page directly then that would be awesome. Just we will be replacing the ad unit.

**Comment by crutkas** [comment]
@sshaik37 great idea.  so much so, we already have it included.  #901 is that item.
