### ISSUE TITLE
Master/Detail - back button not working in narrow mode (minimum width)

### ISSUE THREAD

**Issue by jabak** [Microsoft/WindowsTemplateStudio#1356]
### Repro steps

1. Open up visual studio 2017
2. New Project
3. Visual C#\Windows Universal\Windows template studio
4. Project type = navigation pane
5. Framework = caliburn
6. Add Master/Detail page
7. Create application
8. Run app
9. Make sure the app is not in narrow mode (shrinked to minimum) 
9. Select Master/Detail page
10. Select Company CC in master section
11. Shrink app to minimum width
12. Hit back button

### Expected Behavior

I would expect the app to return to the master view and show the master view list.

### Actual Behavior

It just keeps navigating to the Company CC detail page. There is no way to navigate back to neither master view og event main page.

![image](https://user-images.githubusercontent.com/30479662/32124159-0f951dd2-bb67-11e7-93f0-566cb47e5a61.png)

## System

* VS Version: 2017
* WTS Wizard Version: 1.4.17291.5
* WTS Template Version: 1.4.17291.5
* Windows Build: 1709 (16299.19)

**Comment by mvegaca** [comment]
Thank you @jabak I've checked that this behavior also happen in other frameworks, I'm going to have a look here ;)

**Comment by mvegaca** [comment]
It looks that it could be an Issue on Master Detail control, I've opened a [new Issue](https://github.com/Microsoft/UWPCommunityToolkit/issues/1589) on UWP Community toolkit repository.

**Comment by ralarcon** [comment]
Moving to backlog as we still waiting for UWP Community guyes

**Comment by crutkas** [comment]
any update from the uwp community toolkit guys?

**Comment by jabak** [comment]
I've run through the repro steps and it seems to be okay now. So the community guys must have fixed this in the latest release.

**Comment by mrlacey** [comment]
The toolkit bug says that the repro is inconsistent. It was [suggested](https://github.com/Microsoft/UWPCommunityToolkit/issues/1589#issuecomment-354721676) that they should defer investigating this to an unspecified future release.

**Comment by jabak** [comment]
Okay. I did some more testing and I agree with the toolkit guys. The repro is indeed inconsistent. Some times it works flawlessly (works like in it behaves as expected with no bugs) and sometimes it just skips the master view and returns directly to the main page. The old behavior where it kept navigating to the CC company details page is gone. I cant reproduce that behavior. 

On my machine the inconsistency is caused by either starting in debug mode (hit F5) or starting without debugging (cltr + F5). The latter exposes the bug and the former doesn't. I hope that will shed some light on the matter.

**Comment by mrlacey** [comment]
It sounds like a race condition for setting the selected item for display and knowing if it's been set. Therefore, having a debugger attached could definitely be a factor in being able to repro or not.

**Comment by jabak** [comment]
Sounds plausible. Or maybe a directive could be the culprit.

**Comment by mvegaca** [comment]
Fixed on Windows Community Toolkit Issue [#1589](https://github.com/Microsoft/WindowsCommunityToolkit/issues/1589). This behavior can be tested in generated apps and this Issue could be closed.

**Comment by mvegaca** [comment]
Issue Fixed in Windows Community Toolkit and it's also fixed in new generated apps.
Checked in dev
Templates version: 0.18.18155.1
Wizard version: 0.18.18152.1
