### ISSUE TITLE
Settings menuitem is in primary list

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1357]
![image](https://user-images.githubusercontent.com/189547/32135067-b2854c7c-bbf0-11e7-9a50-279672d82469.png)

Settings menu item is included in the primary menu but it should be in the second menu (at the bottom)

This affects MVVM Light projects only.

* **WTS Wizard Version:** 0.14.17301.65001
* **WTS Template Version:** 0.14.17301.1

**Comment by mrlacey** [comment]
The issue is an outdated value in the CompositionFilter.
Will also add tests to verify the values in the compositionFilter.

**Comment by sibille** [comment]
Verified on dev-nightly:
Wizard: 0.14.17307.65003
Templates: 0.14.17307.3
