### ISSUE TITLE
Update Store Notifications feature logo

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1362]
Align the Store notification feature logo with the latest product updates.

![image](https://user-images.githubusercontent.com/2638875/32166332-ca57480c-bd65-11e7-8366-b45c058f7934.png)

**Comment by crutkas** [comment]
looks to be done, any reason to not close it?

**Comment by mvegaca** [comment]
Checked out on.
Wizard: 0.14.17327.65001
Templates: 0.14.17327.1
