### ISSUE TITLE
Fix wizard to show various dependencies in LearnMore dialog

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1368]
With Feedback Hub we now have the posibility to have more than one dependency, adapt Wizard to show this correctly:

![image](https://user-images.githubusercontent.com/24698018/32217520-85fa9ad8-be28-11e7-8da3-613dc6ace94d.png)

**Comment by mvegaca** [comment]
Fixed #1388

**Comment by dgomezc** [comment]
Verified on dev-nightly:
Wizard: 0.14.17310.65001
Templates: 0.14.17310.1
