### ISSUE TITLE
NavigationView instead Telerik

### ISSUE THREAD

**Issue by hannespreishuber** [Microsoft/WindowsTemplateStudio#1374]
still not satisfied
to complex code and logic, to much controls. 
Instead telerik use Navigationview or Splitview for menu.

**Comment by crutkas** [comment]
We're not using Telerik.  The UWP Community Toolkit with the 2.1 swap over will do a smart flip between their implementation and the Fall Creators Update's NavigationView control.

With the update after the Fall Creators Update, we'll swap over to NavigationView fully
