### ISSUE TITLE
Running a project built by Template Studio crashes when targeting older versions of the Framework.

### ISSUE THREAD

**Issue by fourwhey** [Microsoft/WindowsTemplateStudio#1375]
## For Bugs:
Running a UWP app built by Template Studio crashes when targeting older versions of the Framework.

### Repro steps
Create a simple 1 page project using Template Studio - no need to add anything special. Once it opens, change the target framework to minimum 10240, maximum to 10586 (our devices (Panasonic FZ-F1) running W10M Enterprise cannot currently use a newer version). Close the solution, reopen it. Reload Project/Clean/Build (this should succeed), then debug the project. Watch it crash with an exception in ShellPage() ... InitializeComponent().

Here's the exception:
Windows.UI.Xaml.Markup.XamlParseException occurred
  HResult=0x802B000A
  Message=The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key AppBarButtonBackground [Line: 129 Position: 48]
  Source=
  StackTrace:
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at App4.Views.ShellPage.InitializeComponent() in C:\Users\fourwhey\documents\visual studio 2017\Projects\App4\App4\obj\x86\Debug\Views\ShellPage.g.i.cs:line 45
   at App4.Views.ShellPage..ctor() in C:\Users\fourwhey\documents\visual studio 2017\Projects\App4\App4\Views\ShellPage.xaml.cs:line 60
   at App4.App.CreateActivationService() in C:\Users\fourwhey\documents\visual studio 2017\Projects\App4\App4\App.xaml.cs:line 42
   at System.Lazy`1.CreateValue()

### Expected Behavior
It should run no matter what version of the framework is being targeted.

### Actual Behavior
The app crashes.

## System

* **VS Version:**
VS 15.4.2
* **WTS Wizard Version:**
1.4.17291.5
* **WTS Template Version:**
1.4.17291.5
* **Windows Build:**
1709 Build 16299.19

**Comment by crutkas** [comment]
Not a bug, we support the current release and release prior.

**Comment by fourwhey** [comment]
Perhaps this should be documented in the wizard, or elsewhere?

**Comment by crutkas** [comment]
https://github.com/Microsoft/WindowsTemplateStudio and under Principles, it is # 6.  We've always publically stated that.  We take dependencies on APIs that aren't in the prior releases.  We know 80% of devices are on the latest version of Windows 10 in under a year.

Without being able to take this dependency, it would be impossible for us to do anything with Fluent for example.

**Comment by fourwhey** [comment]
Thanks for the link. I did everything from VS within VS, where it says nothing about limitations of Template Studio. I just assumed something was wrong... I supposed I should have read the GitHub front page prior to making the bug report.
