### ISSUE TITLE
Review templates sources strategy and new requirements

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1376]
With the consolidation of the extension the way we handle the templates source strategy has been evolved.
 
Some of the initial assumptions like no content being distributed with the Wizard are no longer valid, while new requirements rised up like unnecessary downloads when templates content is not updated or the update does not apply) or handle multiple sources. Including these new features will be complex with the current logic. 

The revision must include:
- Version metatada per repository (to avoid unnecessary downloads)
- Handle multiple versions
- Background download
- Do not get new content if not required 
- Avoid wizard being blocked if there is local content available
- Consider multiple sources (remote -> must be trusted; local -> no packaged, no certificate...)
- ...

Remotes sources uses a Temlate Packages as a way to zip have the content signed (to avoid tampering). 
To enforce and ease the remote repository templates handling (pack, unpack, upload, download, get packages info, ensure versioning metatada properly alinged...) a tool could be considered. This tool would help to upload and set the versioning from the build / release process.

**Comment by ralarcon** [comment]
x-ref: #1321

**Comment by ralarcon** [comment]
After reviewing the remote content handling we are considering determining with the remote CDN content which content and versions are available. 

From v1.2 the wizard distributes templates contents with the installer for production / pre-release and nightly versions. 

We can change the Wizard to only download content if there is a new (higher) version available of the templates and if it is aligned with the Mayor and Minor version. The query and download will be performed in background. The process of content acquisition will be the following:

1. If it is a new installation, the wizard will extract the delivered content.
2. The wizard will load and start working with the delivered content.
3. After having fully loaded the available contents and ready to start working, the wizard will check in background if there is an updated version.
3.1. If there is an updated version, the content will be downloaded in background. Maybe we can consider doing it on-demand, that is, to ask the user to download the content (something like inform the user that there is updated version of content available.
3.2. Once downloaded, the content will be extracted and ready to be used the next time the wizard starts. We will notify the user that there is a templates update available just in case he wants to use it directly.

The CDN currently contains different content versions ranging from 1.0.ww.xx to 1.4.yy.zz. This means that we can provide content for different wizard versions.

Scenarios to cover:
- [ ] Newer Content Available:
   * [ ] The wizard is on version 1.4.17291.1 and the current content is 1.4.17291.1 (the content delivered with the Vsix installer); A new version of the contents is available, let say the CDN have the 1.4.17291.5. This needs to be notified to the user, download the content automatically (or ask the user to do it) and leave the content ready to be used.
   * [ ] The wizard is on version 1.4.17291.1 and the current content is in v1.4.17291.5. The CDN contains a newer version, i.e. 1.4.17298.2. This needs to be handled exactly in the same way as the previous point.
- [ ] Newer Wizard Available: 
The wizard is on version 1.4.17239.0 and there is content in the CDN for version 1.5.xx.yy. The wizard needs to notify the user that there is a newer version of the wizard available. But will continue working with its current contents.
- [ ] Older wizard content handling:
A previous version of the wizard is installed, the v1.3. The installer contains the v1.3.17255.1 of the templates. The CDN contains different versions of content for each mayor.minor (1.4.17291.1, 1.4.17291.5, 1.4.17298.2, v1.3.17265.1, v1.3.17270.1, v1.3.17255.0, v1.3.17255.1). In this case the wizard will start working with the delivered content. Then, in background needs to check for the most recent version compatible, in this case, v1.3.17270.1. The wizard will download the content and inform the user that there is a newer version of the content.

To cover these scenarios correctly, the templates sources needs to handle the concept of different content versions.

The wizard currently has logic to handle the scenario of not having content (inherited from v.1.0 where the content was downloaded the first time the wizard was launched) as well as the situation of downloading content (thru the latest template package) that would not be aligned with the wizard version. This logic and complexity needs to be removed and the process of content version checking and download simplified.

**Comment by crutkas** [comment]
here is my thought because right now i do believe it is downloading and unzipping the template file every time.

we have a JSON file called config.json or something on the CDN.  This file then tells WTS what the latest versions are.  This should be an extremely small file.  

We break the VB, C#, Xamarin templates into independent parts as well and by version.  If we need to update to templates, we rev the json file and add the new zip on the file CDN.

This way we are only grabbing very small amounts of data if needed to verify templates versus everything.

**Comment by ralarcon** [comment]
Regarding the json file, I was trying to grab the available version by listing the contents of the CDN (as every file already have the version in its name) instead of maintaing a different file (update every time we publish a new version) we can use the contents of the CDN itself. What do you think? I'm currently working on a tool to help deal with the packaging and publishing of versions and introducing this idea.

Regarding the spliting of the templates content, agree, this will help to reduce the amount of data managed and speed up the whole adquisiton process. In this case (a bit more complex) we need to think how to properly handle the splitting of the repository and the implications (the catalog is currently shared, if I'm not wrong there are composition templates shared among VB and C#...). 

I propose to make a first pass optimizing the version download handling and making this work in background properly and a second pass to think how to make partial updates.

**Comment by ralarcon** [comment]
We will go with the config.json in the cdn but automatically generating / updating the file when publishing new templates content (using the tool).

We will evaluate the spliting of content to reduce the amount of content to be downloaded too.

**Comment by ralarcon** [comment]
Closing this as the review is done and the new strategy is defined. Opened different issues to cover the requirements.

x-ref: #1475, #1476, #1477, #1478, #1479
