### ISSUE TITLE
Revisit our template update system

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1378]
Currently, the update system takes much longer than one would expect to get going.  On a fresh start of VS, it takes upwards to a 30+ seconds.

This isn't an ideal experience and really should be revisited on a top notch way to do this updating system.

This would not just extend to the templates themselves but the extension too.  Far too often it feels the extension itself doesn't auto-update.  it would be great if we caught this scenario and alerted the user there is a new version there.

**Comment by ralarcon** [comment]
This would be considered here #1376

**Comment by crutkas** [comment]
Trying the nightly, it takes minutes for it to show up now and stuck in the updating state

![image](https://user-images.githubusercontent.com/1462282/32579668-d5c3294e-c496-11e7-87af-b8707ab6778d.png)

**Comment by ralarcon** [comment]
We will review a the same time as the Template sources to have real improved experience.

**Comment by crutkas** [comment]
Even on local, the experience here also feels surprisingly long.  We really should document what is causing this and actions we may want to take to improve this.

**Comment by ralarcon** [comment]
Not finally conclusion but looks like in some of the UI refactors we lost the ability to check the existence of new templates in background... this is why looks like taking so long. Currently working in a new stragey.

**Comment by ralarcon** [comment]
Verified in
Wizard: 0.16.18015.65002
Templates: 0.16.18015.4
