### ISSUE TITLE
Creating post action which ensures SA1516 provokes SA1508 violation

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1380]
Creating a post action which ensures the rule SA1516 finish with a code block which violates the SA1508. Create a post-action or method within the Merge-PostAction to ensure the generated code is aligned with the rules. Check SA1505 as well.

**Comment by mvegaca** [comment]
Checked on local and VS Emulator modifying local templates to reproduce that situation
