### ISSUE TITLE
Uri scheme feature not available for caliburn

### ISSUE THREAD

**Issue by jabak** [Microsoft/WindowsTemplateStudio#1385]
### Repro steps

1. Open up visual studio 2017
2. New Project
3. Visual C#\Windows Universal\Windows template studio
4. Project type = navigation pane
5. Framework = caliburn
6. Add Blank page
7. Press next.
### Expected Behavior

A "Select feature" wizard page with the "Uri scheme" option available.

![image](https://user-images.githubusercontent.com/30479662/32336138-c61e448a-bfee-11e7-8649-3f7f22fc69e0.png)

### Actual Behavior

The "Uri scheme" option is not available with caliburn as the selected framework. 

![image](https://user-images.githubusercontent.com/30479662/32336316-407d4906-bfef-11e7-9691-8cc0534eeb6e.png)

## System

* VS Version: 2017
* WTS Wizard Version: 1.4.17291.5
* WTS Template Version: 1.4.17291.5
* Windows Build: 1709 (16299.19)

**Comment by crutkas** [comment]
@jabak not all frameworks and navigation systems will have a 1 to 1 parity.  More so when a framework is just added do we wait and ship with everything (hard when we add new stuff in constantly) or ship and catch up.  

With that said, this should 100% be included and just is a very labor intensive item to test.

**Comment by jabak** [comment]
@crutkas Fair enough. Your work is much appreciated that's for sure. I'm new to windows template studio so I just wondered why uri shceme was absent in the caliburn branch. 

If I understand you correctly caliburn is a fairly new addition to Windows template studio so understandably there will be a thing or two missing.

Agreed. Better ship often and catch up than never ship ;o)

**Comment by mrlacey** [comment]
The disparity is due to the feature and the framework being developed at the same time.

**Comment by mrlacey** [comment]
This was implemented in v1.5 as #1390 

closing as duplicate
