### ISSUE TITLE
Use style resource files when possible in templates

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#139]
New templates XAML code must be reviewed to include resource files to handle the Styles when possible.

**Comment by mvegaca** [comment]
I've just pushed a commit to madrid-dev branch.
[Add style resources dictionaries](https://github.com/Microsoft/WindowsTemplateStudio/commit/cb669a69c66272ae8f9b22f521c47499c5ac5f28)

This aproach includes an **AppTheme.xaml** dictionary merged in App.xaml and one resource dictionary  for each target type on styles. Cons values are center defined on different resources dictionaries.

![image](https://cloud.githubusercontent.com/assets/5556784/26359916/feba6d98-3fd6-11e7-9612-af1638a40892.png)

For now, I've defined only four textblock styles.

**Comment by ralarcon** [comment]
@crutkas @mrlacey any coments on this? With this approach we can even include partial content thru post-actions if required.

**Comment by crutkas** [comment]
i like it.

**Comment by mrlacey** [comment]
Why create the empty files? (thickness & colors) Wait until something is needed before adding it.
Styling and sizes should match the system ones as defined in https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/xaml-theme-resources we want to encourage following existing standards, not create our own ones.
Why does "AppTheme.xaml" exist? It seems just like an extra file to step through. The functionality there should be in App.xaml.
I don't like the "_Const" prefixes on file names.
- I've never seen this used on any other projects. We shouldn't be introducing new conventions without a very good reason.
- Underscores at the start of names are good when something needs to be sorted alphabetically within a group. For items being logically grouped we have namespaces (and folders). If we really feel there's a need to subgroup some of the style files then use a namespace/folder.
- Why the "Const" part? Are you expecting to define any styles or resources that aren't constant?

+ another comment in the PR

**Comment by ralarcon** [comment]
Well, the creation of empty files is to introduce "guidance" as well as introduce the posibility of add "merge post-actions" using this files for single pages or features.

The AppTheme.xaml is just a way to gather all together, you are right, it is an extra step, but at the same time we liked the idea of having the "generated" theme and allow users to create their own style templates... just an aproximation.

The _const prefix is just to group the files with constants visually at the begining of the folder, do you think it is better to have another subfolder with those files. We can hold the "_" to efectively group the files at the begining and remove the "const".

**Comment by mrlacey** [comment]
Creating things you need and using them in a consistent way is good guidance.
Creating things that aren't used is just a waste of effort and potentially creates confusion. 
- "Why is this empty?"
- "Is it meant to be empty?" 
- "If it's a placeholder, why doesn't it say so? And why are there placeholders for some things and not others?"
- etc.

Putting the merge dictionaries directly in App.xaml would group them together. If it was at all realistic to think that someone would take the generated coded and if wanting to create a dramatically different visual style they'd start by taking a copy of the generated theme and work from that then there'd be a case for AppTheme.xaml existing but I expect only a handful of developers will ever take that approach. They'll just dive in and change what's there.
If you created docs outlining a recommended approach from creating different themes it might help a few more do this.
Of course providing another example theme would be another way of indicating what your intentions and expectations are for this structure, but:
- Do we really want or need the extra effort involved in creating and maintaining multiple themes?
- How many developers will actually ever want or need this?
I think the answers are NO and VERY FEW.

By saying (or implying) that some things are constants it suggests that others aren't.

Why do these files need to be grouped?
If they really do, put them in a specific folder/namespace. That is how related files are grouped in .NET projects. (This isn't a language/environment where the file order matters.)
If people want to look for something specific they will do a general search (for which a prefix doesn't help) or look down the list alphabetically. Having some items prefixed just turns one alphabetic list into two--If I want to look for something starting with 'T' I have to look under '_T' and 'T'.

**Comment by ralarcon** [comment]
You are right, the principle of do not create things which aren't used works for me. We expect to use some soon, but anyway we will apply that consideration.

Regrding the AppTheme, I think it is not as important, we can remove it. 

Finally, I like the idea of having the first of the list the files that are base (or are being used) by the rest. It is not as important as well, is just a question of likes.

**Comment by mvegaca** [comment]
I've done som fixes on template styles.

- Remove AppTheme.xaml
- Add Thickness as App resources and use that thickness on pages.
- Remove Const from resource dictionaries names.

This is in the following commit.
[Style fixes on templates](https://github.com/Microsoft/WindowsTemplateStudio/commit/f975a9c8d57a81d9cb68e49222f5bfb4a2ba1cbd)

**Comment by ralarcon** [comment]
Solved in PR #421
