### ISSUE TITLE
Make Uri Scheme available in Caliburn.Micro framework

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1390]
Port Uri Scheme feature to Caliburn framework.

**Comment by mvegaca** [comment]
Working on this

**Comment by mvegaca** [comment]
Added on #1399

**Comment by mvegaca** [comment]
Checked on **Dev Nightly**
Wizard: 0.14.17314.65001
Templates: 0.14.17314.1
