### ISSUE TITLE
Composition Template Page.EnsureMergedDictionaries is not added to generation in dev-nightly

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1395]
Wizard: 0.14.17307.65003
Templates: 0.14.17307.4

**Comment by sibille** [comment]
Was caused by a duplicate name in composition template. Template engine retrieves identities from name if identity is not specified, duplicate identites are not charged in the template repos. Working on adapting the tests to catch this.

**Comment by ralarcon** [comment]
Wizard: 0.14.17310.65001
Templates: 0.14.17310.1
