### ISSUE TITLE
AppToApp Category Name

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1401]
This new category contains the following features: 

- Drag & Drop target
- Share source
- Share target
- Schema launch
- File extension handling
- Project Rome
- Cortana skill/voice command

We're trying to find a better name, proposals were so far:
- App to App
- App Interaction
- Inter-App Communication

X-Ref: #827

**Comment by crutkas** [comment]
Rome itself isn't an item, it is the APIs inside of it.  Rome in dev center is under "Connected Applications"

Cortana for us is actually launching, so is file ext, and scheme.  Share source / target go back to actually launching but could be decoupled.

- Application Launching
   - Cortana
   - Schema
   - Web to App
   - File Ext

- Connected Experiences???
   - Sharing
   - Drag and Drop (while it can be app to app, it can also be to itself)
   - User Activity (Rome)

**Comment by crutkas** [comment]
Sibille, this was more of a discussion versus action.  hence the ???? :)

**Comment by sibille** [comment]
Sorry, had my mind set all to action ;-) But you're right, let's finish the discussion before changing categories. 
I like the idea of breaking App Launching into a new category. Also like the name for Connected Experiences, other options would be Connecting Apps, App Interaction or App Communication.

**Comment by ralarcon** [comment]
@crutkas Are the current categories ok? Can we close this issue?

**Comment by crutkas** [comment]
lets go with what we got, if we need to adjust, we adjust
