### ISSUE TITLE
Missing dots in Package.appxmanifest when generating with dev-nightly

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1407]
### Repro steps
Generate project with dev-nightly

What did you do? How can someone else reproduce this?

### Expected Behavior
Metadata in package.appxmanifest should be:

 <genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
    <genTemplate:Item Name="wizardVersion" Version="0.14.17310.65001" />
    <genTemplate:Item Name="templatesVersion" Version="0.14.17310.1" />
    <genTemplate:Item Name="projectType" Value="SplitView" />
    <genTemplate:Item Name="framework" Value="CodeBehind" />
  </genTemplate:Metadata>

### Actual Behavior
Metadata in package.appxmanifest is:

 <genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
    <genTemplate:Item Name="wizardVersion" Version="141731065001" />
    <genTemplate:Item Name="templatesVersion" Version="14173101" />
    <genTemplate:Item Name="projectType" Value="SplitView" />
    <genTemplate:Item Name="framework" Value="CodeBehind" />
  </genTemplate:Metadata> 

## System
Happens only in vsix, not in VSEmulator.

Wizard: 0.14.17310.65001
Templates: 0.14.17310.1

**Comment by mvegaca** [comment]
Checked on **Dev Nightly**
Wizard: 0.14.17314.65001
Templates: 0.14.17314.1
