### ISSUE TITLE
Shared composition templates not being generated when Windows is set Turkish 

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1409]
### Repro steps

Install Turkish language in windows. Set Turkish as default language. Log off and log on.

Create a project which requires a _shared composition template, i.e. Nav Pane project, Code Behind framework and be sure to include a Camera page. 

### Expected Behavior
The generation creates the project properly which is able to be built and run.

### Actual Behavior
All the composition templates in the _composition\_shared template repository are not generated.

We have experience generating and using the WIndows template Studio generation in other languages without any issue (Spanish and German). But in Turkish looks like the _shared templates folder is not being considered as we have verified that other templates are not properly generated too.

**Comment by crutkas** [comment]
can we some how also validate spoken languages via testing somehow

**Comment by ralarcon** [comment]
You mean to execute the Windows Narrator to read the translated tests? We can do it too, in spanish and german (maybe in french) we can validate the correctness but not in other languages.

**Comment by crutkas** [comment]
My understanding of the bug was something wasn’t being generated properly due to language.

**Comment by ralarcon** [comment]
Is a weird thing, shared composition templates (only the shared ones, not other composition templates) are not being considered in the generation when using Turkish (is like the generation engine does not find the templates). This works in other languages (like spanish or german)... I'm suspecting in something related to sorting / language when evaluating the filters....

**Comment by ralarcon** [comment]
Found the root cause: the Turkish culture have a different representation for "i" and this makes the comparison thru the identity fail as does not match the field name.

![image](https://user-images.githubusercontent.com/2638875/32492761-b12f8716-c3bb-11e7-8b98-77da8d037b84.png)

In the dictionary, only some of the entries use the `ToLower` to create the key and need to use invariant culture (`ToLowerInvariant`) in this case.  I will activate the code analysis rule [CA1304](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1304-specify-cultureinfo) to ensure we do not miss any comparison with the correct culture specification or using invariant culture.

**Comment by crutkas** [comment]
I thought we had already caught all the tolower / uppers.  Good find and good job enabling the rule

**Comment by mvegaca** [comment]
Fix checked on
Wizard: 0.14.17320.65001
Templates: 0.14.17320.1
