### ISSUE TITLE
Cannot move error message box

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1413]
In Small screen and big text scale (150%), if the extension shows the error message box, the button to close the message is outside the visual area. The error message box should be able to be moved so that the button is accessible. 

![image](https://user-images.githubusercontent.com/12777039/32490720-7c5e2c24-c3b4-11e7-91b4-2908ca7dc27a.png)

**Comment by mvegaca** [comment]
Checked on Installer with experimental instance on dev branch throwing a new exception
