### ISSUE TITLE
Review composition in localized strings

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1420]
Review the use of string.Format in localized string resources. 

Whilst this is fine:  Feature {0} successfully added, (0: SettingsStorage)
this is not: You can not remove {0} because {1} {2} depends on it. (0: SettingsStorage, 1: Settings, 2: Page)

**Comment by mvegaca** [comment]
Cases to test
New project
- Can not remove template

New Item
- Template already added
- Header changes summary

**Comment by mvegaca** [comment]
Checked on **Dev nightly**
Wizard: 0.14.17314.65001
Templates: 0.14.17314.1
