### ISSUE TITLE
Maintain sort order of feature categories throughout languages

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1421]
Currently, the feature categories are ordered alphabetically, this leads to different order in different languages.

English
![image](https://user-images.githubusercontent.com/24698018/32545345-b5e80b64-c47b-11e7-9287-83b40c9137f8.png)

German
![image](https://user-images.githubusercontent.com/24698018/32545144-0cbaa664-c47b-11e7-83c2-da3e01f5b6a6.png)

Spanish
![image](https://user-images.githubusercontent.com/24698018/32545056-c44cae0e-c47a-11e7-9d72-3a9e9051fab9.png)

Wizard: 0.14.17312.65001
Templates: 0.14.17312.1

**Comment by mvegaca** [comment]
Fixed on #1428

**Comment by mvegaca** [comment]
Fix checked on
Wizard: 0.14.17320.65001
Templates: 0.14.17320.1

**Comment by sibille** [comment]
Do this for right click too

**Comment by sibille** [comment]
Verified in 
Wizard: 0.14.17353.65001
Templates: 0.14.17353.1
