### ISSUE TITLE
[Watson] crash32: FATAL_USER_CALLBACK_EXCEPTION_c000041d_Microsoft.Templates.UI.dll!Unknown

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1431]
Repro steps: 
1. Create project with WTS
2. Change to high contrast

Stack trace from installer:

![image](https://user-images.githubusercontent.com/24698018/32657210-268b787a-c615-11e7-83c4-a7d79b64c4b2.png)

**Comment by mvegaca** [comment]
Fixed on #1433
