### ISSUE TITLE
Add more postactions defined by template

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1432]
With the possibility to add postactions defined by templates (X-Ref #1330) we found some more postactions that could be added/ implemented that way. 

For example:
- Restore nuget packages for project
- Open Files after generation
- Add project (and nuget?) reference

**Comment by dgomezc** [comment]
Important, for restore nuget packages we have to considered the way to add references to the projects, because when you add references to Xamarin projects, each type of project (Android, iOS, UWP) references are added differently.

**Comment by mrlacey** [comment]
IS this issue still relevant?
It needs updating if keeping open to make clearer what the action points are and when/why they're needed.

**Comment by sibille** [comment]
Opened #2386 to track this separately. I don't think we'll need the others for now, so closing this issue.
