### ISSUE TITLE
Navigation Pane template doesn't use proper navigation

### ISSUE THREAD

**Issue by r2d2rigo** [Microsoft/WindowsTemplateStudio#1459]
### Repro steps

- Create a new Windows Template Studio project.
- Select `Navigation Pane` as the project type.
- Add any number of pages to it.

### Expected Behavior

- Navigating to any section instantiates only one copy of that page/viewmodel, if it is the first time it is navigated. If not, it reuses the previous instance.

### Actual Behavior

- Each time a section is selected, a new copy of the page/viewmodel is pushed to the navigation stack (selecting the active section does this too). 

## System

* **VS Version:** 15.4.4
* **WTS Wizard Version:** 1.4.17291.5
* **WTS Template Version:** 1.4.17291.5
* **Windows Build:** 10.0.16299.64

**Comment by crutkas** [comment]
I can see both sides of this.  can you provide a bit more guidance on why you view this as the appropriate app model?

Does this happen on MVVM Light?  Code behind?

**Comment by ralarcon** [comment]
I guess you are using Mvvm Basic framework as MVVM Light hold the viewmodel instances among navigation. 

Anyway, the default current behavior is to recreate the page (even in MVVM Light). If you want to maintain the same instances for the page and viewmodel you can take advantage of the `NavigationCacheMode="Required"` in the page. With this, the page is cached when navigated away and reused when navigate to again.

There could be scenarios where it is more interesting to hold the same instances (avoid reloads) and others where, in pro reduce resources consumption, the pages are instantited and released as the are navigated to and away (probably storing the current state before navigate away if the page have costly external services calls).

**Comment by r2d2rigo** [comment]
@crutkas it happens using MVVM Light.

It seems that the hamburger menu navigation isn't standarized even in MS apps:
- The Xbox app only allows one level of depth - selecting the back arrow goes back to the Home section.
- The Mail and Calendar ones don't have a navigation stack.
- The Weather one behaves like the WTS template one.

IMHO it would be great to be able to select which type of navigation behaviour you want when creating a new project, but maybe it adds additional complexity that not many users will benefit from.

@ralarcon thanks! That fixes half of the issue, now I have to tweak how the navigation stack works.

**Comment by crutkas** [comment]
Our goal is to get a lot of the plumbing up and operational for everyone. We were never designed to be a few clicks and be done system. 

As every dev knows, there are hundreds of ways to do stuff. We are trying to get the boiler plate stuff up and do it in a way that doesn’t force you the dev to delete 70% like the old templates would. 

If you strongly feel we are doing something that is against the common use use or should be documented to improve Your scenario let’s get it fixed. 

Every app has different requirements as you just pointed out with our own apps.
