### ISSUE TITLE
HubNotificationsService not firing HandleInternalAsync(ToastNotificationActivatedEventArgs args)

### ISSUE THREAD

**Issue by ThomasPe** [Microsoft/WindowsTemplateStudio#1461]
### Repro steps

I registered my app for push notifications, which get delivered just fine to the notification center in Windows. 
I'm seding test notifications from Azure NotificationHub like this:

```<?xml version="1.0" encoding="utf-8"?>
<toast>
<visual><binding template="ToastText01">
<text id="1">Test message</text>
</binding>
</visual>
</toast>
```

### Expected Behavior

When opening the app from the toast notification I should be able to handle the `ToastNotificationActivatedEventArgs`.

### Actual Behavior

Launching the app from there I never reach the `HandleInternalAsync(ToastNotificationActivatedEventArgs args)` method inside the `HubNotificationsService.cs`. 

I assume that `ToastNotificationActivatedEventArgs` never get matched - I do get `LaunchActivatedEventArgs` for these launches.

I have uncommented the `Singleton<HubNotificationsService>.Instance.InitializeAsync();` line in the `ActivationService.cs`.

## System

* **VS Version:** 15.4.4
* **WTS Wizard Version:** 1.4.17291.5
* **WTS Template Version:** ?
* **Windows Build:** 16299.64

**Comment by ThomasPe** [comment]
Turns out the Azure test message is missing some crucial parts for activating the app:

`<toast activationType='foreground' launch='args'>`

**Comment by crutkas** [comment]
Was this due to something we didn’t do or a todo we lacked to add in?

**Comment by ThomasPe** [comment]
not sure, it seems like you need the `activationType='foreground'` and/or `launch='args'` for the Handler to work. Might be a good addition to the documentation.

**Comment by crutkas** [comment]
@ralarcon is this part of our template?

**Comment by mvegaca** [comment]
I'm reviewing the feature with following steps.
- Create an App: BLANK, MVVMBasic, BlankPage, FromToastPage, HubNotifications
- Fill the parameters hubName and accessSignature in HubNotificationsService
- Uncomment the line `await Singleton<HubNotificationsService>.Instance.InitializeAsync();`
- Added in `NavigationService.Navigate<FromToastPage>(args.Argument);` `HubNotificationsService `method `HandleInternalAsync`
- Create a Azure/AppServices/NotificationHub
- Link the App with the Store (Dev Center)
- Setup the NotificationHub/WindowsWNS with the Dev Center SSID and Secret.
- Send a sample toast notification
```xml
<?xml version="1.0" encoding="utf-8"?>
<toast>
   <visual>
      <binding template="ToastText01">
         <text id="1">Test message</text>
      </binding>
   </visual>
</toast>
```


If I launch the App from the Toast Notification in Window Action Center and the app is closed, the App is launched in FromToastPage.
If I launch the App from the Windows menu the app is launched in MainPage, if then I click on the notification with the app already opened the app navigates to FromToastPage

**Comment by mvegaca** [comment]
I realized that the default template when testing from Azure test contains
`<binding template="ToastText01">` 
When the template of the notification is not well formed the activation becomes from OnLaunched instead of the OnActivated event and it is because of that we don't identify the ToastNotificationActivatedEventArgs in args. It becomes fixed if the notification is ToastGeneric.

From the [documentation](https://docs.microsoft.com/es-es/windows/uwp/design/shell/tiles-and-notifications/send-local-toast#handling-activation-1)
> Note: If you are using the legacy toast templates from Windows 8.1, OnLaunched will be called instead. The following documentation only applies to modern Windows 10 notifications utilizing the Notifications library (or the ToastGeneric template if using raw XML).

If the notifi

**Comment by ralarcon** [comment]
@ThomasPe Did you have a chance to review the comments from @mvegaca. Can we close this issue?

**Comment by ThomasPe** [comment]
this issue can be closed as far as I'm concerned. Just wondering if we want to link to this info somewhere (maybe as a comment in the code) since it's easy to run into this problem with the default azure notification templates?

**Comment by ralarcon** [comment]
Good point, we'll do!
