### ISSUE TITLE
Define a config file to support templates content version checking and download

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1475]
The file must consider the version handling requirements and provide an easy and fast way to detect if there is a new version of the content available.

Adding it to 1.5 to deliver the new download strategy in the next version. By now no breaking changes will be integrated to dev branch to ensure we can deliver this with warranty.

**Comment by ralarcon** [comment]
Initially the json for the cdn configuration will be as follows:
``` json
{
    "Latest": {
        "Name": "dev.templates.publish_0.14.17327.01.mstx",
        "StorageUri": "https://wtsrepository.blob.core.windows.net/dev/dev.templates.publish_0.14.17327.01.mstx",
        "Date": "2017-11-23T11:20:25",
        "Bytes": 3897956,
        "Version": {
            "Major": 0,
            "Minor": 14,
            "Build": 17327,
            "Revision": 1,
            "MajorRevision": 0,
            "MinorRevision": 1
        }
    },
    "VersionCount": 12,
    "Versions": [
        {
            "Name": "dev.templates.publish_0.14.17327.01.mstx",
            "StorageUri": "https://wtsrepository.blob.core.windows.net/dev/dev.templates.publish_0.14.17327.01.mstx",
            "Date": "2017-11-23T11:20:25",
            "Bytes": 3897956,
            "Version": {
                "Major": 0,
                "Minor": 14,
                "Build": 17327,
                "Revision": 1,
                "MajorRevision": 0,
                "MinorRevision": 1
            }
        },
        ...
     ]
}
```

With this information will be enough to the refer the correct template package to be downloaded (by name) from the corresponding environment cdn

**Comment by crutkas** [comment]
I feel like this is heavy for the JSON and lots of unneeded data.  We get version count from the array, we get actual version number from the name of the file.

how does this look / feel?

```
rootUri:"https://wtsrepository.blob.core.windows.net/dev/",
"Latest": {
        "Name": "dev.templates.publish_0.14.17327.01.mstx",
        "Date": "2017-11-23T11:20:25",
        "Bytes": 3897956,
        "platform": "uwp",
        "langauge": "csharp",
        }
    },
"Versions": [
        {
overrideRootUri:"https://wtsrepository.blob.core.windows.net/dev"
            "Name": "dev.templates.publish_0.14.17327.01.mstx",
            "Date": "2017-11-23T11:20:25",
            "Bytes": 3897956,
```

**Comment by ralarcon** [comment]
Looks fine. 

I didn't introduced the platform / language info as we forsee an issue with the partial content (splitting by language -csharp / vb- and platform -uwp / xam-). As it is not as simple, I was leaving this for a further review. The main issue is, for example, if we want to share content among different languages then we will need to update the templates at the same time for both languages unless we have a common source but splitted local repositories to be able to have a CSharp content on version 1.X.Y.Z and VB Content in version 1.U.V.W ...  That is, a solution would be to have a common resource templates repository to AUTHOR templates but use it as splitted repository using filtered content to setup the packages.

I will include both concepts to be used in a further review.

**Comment by sibille** [comment]
Done as part of template source revision, in PR #1680

**Comment by ralarcon** [comment]
Verified in
Wizard: 0.16.18015.65002
Templates: 0.16.18015.4

This is the final structure (at least by moment):
{
    "Latest": {
        "Name": "dev.Templates_0.16.18015.04.mstx",
        "Date": "2018-01-15T14:36:22",
        "Bytes": 5395964
    },
    "RootUri": "https://wtsrepository.blob.core.windows.net:443/dev",
    "Versions": [
        {
            "Name": "dev.Templates_0.16.18015.04.mstx",
            "Date": "2018-01-15T14:36:22",
            "Bytes": 5395964
        },
        {
            "Name": "dev.Templates_0.15.18012.05.mstx",
            "Date": "2018-01-12T14:18:09",
            "Bytes": 5378423
        }]
}
