### ISSUE TITLE
[Question] - MVVM Basic 

### ISSUE THREAD

**Issue by garfbradaz** [Microsoft/WindowsTemplateStudio#1500]
Hey Guys,

Firstly I absolutely love this extension. It is helping a lot as I'm a beginner with UWP and never touched WPF before, but I do come from an MVC background.

I understand the basic concepts of MVVM as a pattern, but it s the Navigation side which is befuddling me. I see there is  `ShellViewModel.cs` and wiring up the Navigation (in Navigation). Is there any good reference material that you guys built the **MVVM Basic** template to, so I can learn about the pattern against what you guys have implemented? 

Again, I love this Studio extension and thank you for it, as working with XAML has always put me off looking up UWP previously, but this is brilliant work.

**Comment by mvegaca** [comment]
Hi @garfbradaz 
Thank you for your feedback. Currently, we already have an Issue to create an MVVM Basic design pattern documentation #886 in the backlog.

**Comment by garfbradaz** [comment]
@mvegaca : Diamond - I will follow that issue - thanks again matey.
