### ISSUE TITLE
MediaPlayer Page don't Pause the video on Tabbed project type

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1504]
When you navigate to a MediaPlayer page on Tabbet project the video starts because it's configured as auto-start, but when you navigate to another page the video does not be paused because Pause action is set on OnNavigatedFrom event handler and this event is not fired on tabbed project

**Comment by dgomezc** [comment]
After reviewing this issue, we think we will need some infrastructure for Pivot project types to handle when the active tab changes and properly execute actions (in this case play / pause the video when required). 

Then, the action or preference itself would depend on the developer needs, that is some apps would require the video to be paused and other would prefer the background playing... 

I've opened a new issue to discuss the convenience of having some infrastructure to detect when the active tab have changed: #1584

Considering all of this, I would suggest to hold on this until decide if we will have the required infrastructure.

**Comment by ralarcon** [comment]
Moving to next release as we are not going to face this for 1.6

**Comment by crutkas** [comment]
@dgomezc  Just verifying that we have tested this on navview along with tabbed?  code has been removed from the main page so just want to be sure the page still works correctly in the majority use case.

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.16.18018.65001
Templates: 0.16.18018.1
