### ISSUE TITLE
Any docs/samples about persisting state for Caliburn.Micro-based WTS?

### ISSUE THREAD

**Issue by Myrmex** [Microsoft/WindowsTemplateStudio#1522]
Hello, sorry for the naive question, but I'm new to WTS and UWP and I'm experimenting with the Caliburn framework in WTS and I'm not sure about the intended way of using state suspend/resume. Could anyone point to some sample or explanation?

I can see that `App.xaml.cs` has an `App_EnteredBackground` method which gets the suspend/resume service singleton instance and invokes the save state method. In turn, this creates a new `SuspensionState` object, wraps it into an `OnBackgroundEnteringEventArgs` object, and calls all the subscribers for this event. I thus suppose I should add to each viewmodel I want to persist state for a handler for this event, like maybe (in the constructor of each VM) `Helpers.Singleton<SuspendAndResumeService>.Instance.OnBackgroundEntering += OnBackgroundEntering;`. I imagine that the handler of each VM should populate it with its own status data; further, as initially `SuspensionState.Data` is null, it should be created if not already set by another VM handler. Yet, I'm a bit at loss with the details of all this, and even more dubious about the restore mechanism. Could anyone point me to some useful resource? It does not seem there is anything about this in the Wiki.

**Comment by crutkas** [comment]
if it is a caliburn question, let me loop in @nigel-sampson

**Comment by Myrmex** [comment]
Maybe it's useful adding updated information here after the latest release: I made some changes/additions to the template code to enable save/resume, but I'm not sure this is the intended path, nor it works (it seems that the `OnActivated` override in `App.xaml.cs` never gets called):

- I changed `SuspensionState` property from `object` to a dictionary: `public Dictionary<string,object> Data { get; set; }`, and also instantiated it from its constructor.
- I see that `SuspendAndResumeService` has an `OnBackgroundEntering` event, but I could not find any clue for resuming. I tried by adding another event to this service, `public event EventHandler<OnBackgroundEnteringEventArgs> OnResuming;`, and changing this method as follows:

```cs
private async Task RestoreStateAsync()
{
    OnBackgroundEnteringEventArgs state = await ApplicationData.Current.LocalFolder
        .ReadAsync<OnBackgroundEnteringEventArgs>(STATE_FILENAME);

    OnResuming?.Invoke(this, state); // <== ADDED THIS

    if (state?.Target != null)
    {
        var navigationService = IoC.Get<INavigationService>();
        navigationService.NavigateToViewModel(state.Target, state.SuspensionState);
    }
}
```

My idea would then subscribing to both these events in each VM I need to persist the state of. When handling the `OnBackgroundEntering` event, I wrap its state in a POCO object and save it to the `SuspensionState.Data` dictionary (`SuspensionState` is part of the argument received from the event). When handling `OnResuming`, I do the inverse.

When suspending I can see this working; yet, when resuming, the resume handler never gets called as in turn the `OnActivated` override in `App.xaml.cs` never gets called, too.

**Comment by nigel-sampson** [comment]
Sorry this slipped through the cracks. 

Looking at the framework code I'm seeing the following patterns.

1. The way `OnBackgroundEnteringEventArgs` takes a target type indicates it's designed to preserve the state of a single view model, this target type being the "current" view model.
2. View models interested in preserving data should subscribe to the `OnBackgroundEntering` event, personally I'd subscribe in `OnActivate` and unsubscribe in `OnDeactivate`, so only the "current" view model gets notified.
3. Definitely 👍 on switching to a dictionary to state.
4. The restore state method then takes that target "current" view model and navigates to it, passing it as a navigation parameter.
5. The important point here is how Caliburn.Micro handles the parameter. If it's a dictionary then it will look for properties on the view model named the same as the key and populate with the value, or simply create a property `Parameter` on the view model and the dictionary will be inserted into it.

This way there is no special path for restoring state, it's just a normal navigation to the view model.

Hope this makes some sense and apologies again for missing the question.

**Comment by Myrmex** [comment]
Thanks Nigel, this makes things much clearer. What I was missing was the Caliburn "magic" in handling the navigation parameter.

Anyway, I'm wondering how I should handle a scenario where I have to restore the state of *several* viewmodels; also, sometimes it turns that *rebuilding* the values of some properties, rather than simply restoring the full object tree, is more profitable in terms of performance. In this case, I can just add a `Parameter` property to the VM, and handle it in the property setter: here I would read the dictionary got from Caliburn, and do whatever appropriate to rebuild such a complex state.

As for restoring multiple VMs states instead, this happens in my app where I have a main page representing by a pivot, with 3-4 tabs, each representing a view to some data. In this case I must keep track of e.g. the page number and the filters applied to each view, so that the user finds himself back where he left when restoring. So in this case I'm rather going to use a single state dictionary, shared among VMs, and add a resuming event to the service so that each VM can subscribe to it. Would the following approach be OK? Maybe the question can help someone else, so I list my changes to the template for this particular scenario.

First, `OnBackgroundEnteringEventArgs` and `SuspensionState` (there I add a helper method as I don't want to resume if 7 days or more have passed):

```c#
public class OnBackgroundEnteringEventArgs : EventArgs
{
    public SuspensionState SuspensionState { get; set; }

    public Type Target { get; }

    public OnBackgroundEnteringEventArgs(SuspensionState suspensionState, Type target)
    {
        SuspensionState = suspensionState;
        Target = target;
    }
}

public class SuspensionState
{
    public Dictionary<string,object> Data { get; set; }
    public DateTime SuspensionDate { get; set; }

    public SuspensionState()
    {
        Data = new Dictionary<string, object>();
    }

    public bool ShouldResume()
    {
        return (DateTime.Now - SuspensionDate).TotalDays < 7;
    }
}
```

Then, the event for `SuspendAndResumeService`:

```c#
// ...
public event EventHandler<OnBackgroundEnteringEventArgs> OnResuming;
//...
private async Task RestoreStateAsync()
{
    OnBackgroundEnteringEventArgs state = await ApplicationData.Current.LocalFolder
        .ReadAsync<OnBackgroundEnteringEventArgs>(STATE_FILENAME);

    OnResuming?.Invoke(this, state);

    if (state?.Target != null)
    {
        var navigationService = IoC.Get<INavigationService>();
        navigationService.NavigateToViewModel(state.Target, state.SuspensionState);
    }
}
```

In each of my VMs constructor I subscribe to the events like:

```c#
Helpers.Singleton<SuspendAndResumeService>.Instance.OnBackgroundEntering
    += OnBackgroundEntering;
Helpers.Singleton<SuspendAndResumeService>.Instance.OnResuming
    += OnResuming;
```

I handle such events like this (the `STATUS_KEY` constant is a constant defined in each VM to uniquely identify it in the state dictionary):

```c#
private void OnBackgroundEntering(object sender, OnBackgroundEnteringEventArgs e)
{
    e.SuspensionState.Data[STATUS_KEY] = new CharCodeViewModelState
    {
        Input = _input,
        Decimal = _decimal,
        AutoCopy = _autoCopy
    };
}

private void OnResuming(object sender, OnBackgroundEnteringEventArgs e)
{
    if (!e.SuspensionState.Data.ContainsKey(STATUS_KEY) ||
        !e.SuspensionState.ShouldResume()) return;

    CharCodeViewModelState state =
        (CharCodeViewModelState) e.SuspensionState.Data[STATUS_KEY];

    IsDecimal = state.Decimal;
    IsAutoCopyEnabled = state.AutoCopy;
    Input = state.Input;
}
```

**Comment by nigel-sampson** [comment]
Sounds like you're on a good path.

I'd recommend using your state in `OnActivate` rather than the `Parameter` setter. This way you're only doing the work when the view model is actually being used.

I'd do much the same as what you're doing here, have the root "conductor" view model handle storing and restoring state for itself and it's child view models. 

Looks like its all working and just a matter of style at this point. I would tend to the root view model doing the work so the child view models don't care about state management.

**Comment by Myrmex** [comment]
Thanks Nigel, I'll go for this path! Keep up the good work, I love this template, it makes things a lot quicker and easier.
