### ISSUE TITLE
Settings page has white background set, different than rest

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1525]
was creating a quick sample for #1499  and noticed the setting page is different than the rest.

I just tested grid, chart, setting and you'll see the diff
![image](https://user-images.githubusercontent.com/1462282/33629728-f38f687e-d9b9-11e7-9bcd-fd5577010031.png)
![image](https://user-images.githubusercontent.com/1462282/33629732-f6a87b2c-d9b9-11e7-8c37-0fd52f2deb88.png)
![image](https://user-images.githubusercontent.com/1462282/33629733-f8a3ffaa-d9b9-11e7-9221-c55f17b95f10.png)

**Comment by mvegaca** [comment]
Page background setted by page style. Updates on #1542
