### ISSUE TITLE
HamburgerMenu is deprecated

### ISSUE THREAD

**Issue by hupo376787** [Microsoft/WindowsTemplateStudio#1527]
## For new Features:

* **Overview:** What you'd think should be added with scenarios
* **Links:**

### Repro steps

What did you do? How can someone else reproduce this?

### Expected Behavior

What was expected to happen
(include screenshots if a visual issue)

### Actual Behavior

2>E:\Universal Windows Platform\Store\WeRecognition\WeRecognition\Views\ShellPage.xaml(93,6): XamlCompiler warning WMC1500: 'HamburgerMenu' is deprecated: The HamburgerMenu will be removed in a future major release. Please use the NavigationView control available in the Fall Creators Update
2>E:\Universal Windows Platform\Store\WeRecognition\WeRecognition\obj\x86\Release\Views\ShellPage.g.cs(22,96,22,151): warning CS0618: “HamburgerMenu” out of date:“The HamburgerMenu will be removed in a future major release. Please use the NavigationView control available in the Fall Creators Update”

## System

* **VS Version: 15.5.0**
* **WTS Wizard Version: 1.5.17334.7**
* **WTS Template Version:1.5.17334.7**
* **Windows Build: 16299.98**

**Comment by mrlacey** [comment]
The WTS aim is that the generated projects target the last two public releases. Currently, this means the **Creators Update** and the **Fall Creators Update**.
For now, the generated code continues to use the HamburgerMenu as that supports both versions. When the next release of Windows 10 is made public, the inclusion of the HamburgerMenu will end.
An investigation of supporting both the HamburgerMenu and the NavigationView and swapping which is used based on the machine the app is running on is ongoing.

@ralarcon or @crutkas does WTS have an official statement on maintaining support for deprecated controls or functionality? If not, can one be created?

**Comment by crutkas** [comment]
That control will support exactly what @mrlacey mentioned.  It does a smart flip between NavigationView and their older, custom implementation. Since we (Template Studio) support both CU and FCU currently, we will do a flip to navigation view once the next update of Windows 10 comes out as by then, we feel we'll have enough market penetration to validate that.  That won't occur until Spring 2018 time frame.

**Comment by hupo376787** [comment]
Hi, guys
I think WTS can give users an option to choose NavigationView mode or HamburgerMenu mode, while creating project.

**Comment by crutkas** [comment]
@hupo376787 that actually adds a ton of complexity and a break of our promise supporting current and prior release.  Also by the time that would be implemented, my gut says we'd be rolled onto the next update of Windows 10 and you'd get this by default :)

**Comment by hupo376787** [comment]
OK, got it. Thanks
