### ISSUE TITLE
Include last run information on build status

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1528]
Add details of when builds and tests were run to the [build status section of the home page](https://github.com/Microsoft/WindowsTemplateStudio#build-status).

![image](https://user-images.githubusercontent.com/189547/33659290-9331c8e6-da77-11e7-9af6-7c44289bff0b.png)

While the above is useful it is not the complete picture.

Just having a pass/fail indication it's not clear when the result was achieved. 
If showing a successful result that was actually several days ago that might indicate a problem if it's expected to run more frequently.
If a failure happened a few minutes (or maybe hours) ago that's not so much of an issue as one that happened several days ago. If something's been in a failed state for many days that may indicate a bigger issue. 

As these indicators are on the front page of the project they serve as an indicator to anyone looking at the project. They indicate not just the current state of the code but also the management of the project. (If it doesn't look like build or test failures will be addressed or they're not run frequently that's a bad indicator of the level of support someone using the project may get.)

For the output created from AppVeyor it's possible to click through to see when things were last run but this is slow and prevents an overview of evverything on a single page.
For the output created from VSTS it's only possible for the few people with access to the private server to see these details. This means a typical viewer of the page cannot know this.

What's I'm asking for:
- Add details of when the tests and CI builds whose status is shown were run to the build status page.
- Add a note about how frequently these are expected to run so it can highlight any potential issues.

**Comment by ralarcon** [comment]
Updated the web hook with VSTS to publish a page with the build summary in our repo in the vsts-builds folder. The readme has been updated to link to the new summaries too but untill builds run, no actual page will exists.
