### ISSUE TITLE
Add reporting, tracking, & escalation of build failures

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1529]
When something fails it won’t get fixed unless someone able to fix it is told about the problem.
At the very least, VSTS should be raising issues (sending emails) to people with access to see the output.
I must assume that is happening but it is invisible to anyone outside the inner core of developers.

From a public perception/community involvement perspective. It looks bad if the main page of the project shows things failing. With no indication of how long something has been failing it may reflect very badly on a project. (I have in the past seen failures up for several days when the team were away or on vacation.)
That details of a failure can’t be seen (they’re on the private VSTS instance) means that their seriousness and any consequences isn’t known to someone looking from the outside and it’s not possible for anyone to contribute a fix (unless they can recreate the failure locally but this may require running several hours’ worth of tests—from my experience.)

A failed build should be treated like any other bug or required piece of work. Raise an issue; assign it; make necessary changes; mark it as closed;  all of which ensures we have a record of what was done and why, plus a historical record if things start to happen repeatedly.

What we need:
-	A failing test (or build) should raise an issue on GitHub detailing the problem. 

This may require custom development against the GitHub API or evaluation of possible 3rd party solutions to provide this functionality.

X-Ref: #1524 (for issue prompting this) & #1528 (for related item)

**Comment by ralarcon** [comment]
VSTS does not allow anonymous access to build information. After reviewing the options we have to achive this, we can create a WebHook when a VSTS build fails and an Azure Function which receive the build information, pull the logs and and creates an issue in the repo.

It is not expected that a build in the VSTS fail frequently as we run a wide sample of the tests within the AppVeyor build (publicly accesible) but it is true that currently there are some builds related to VB that are failing within AppVeyor with a wierd and only can run in VSTS. We are going to prioritize this to be try to provide as much info as possible if a build in VSTS fails.

**Comment by mrlacey** [comment]
There have also been some errors in the past that were temporal and unrelated to the templates (in either language).

**Comment by ralarcon** [comment]
Now we have a solution PR #1553. Every time a build fails in VSTS, an issue will be created in the repo with the build output and log files.
