### ISSUE TITLE
Prism: Navigation pane is not showing navigation items in dark theme

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1547]
Repro steps: 
1. Create a project with project type NavigationPane and framework Prism
2. Add all pages
3. Start the app
4. Go to Settings Page
5. Change theme to dark

Expected behaviour: 
Navigation items should show with white foreground

Actual behaviour:

![image](https://user-images.githubusercontent.com/24698018/33942125-3a67d4e6-e015-11e7-8b76-b9b080adac73.png)

**Comment by milazzom** [comment]
Linking with #350.  There is also a PR #360 which I can't link to, but it has discussion about this very issue.

**Comment by crutkas** [comment]
i would verify the navigation pane is setting proper value.  Also test if tabs are doing this.

**Comment by crutkas** [comment]
@LeeParrishMSFT or @milazzom have either of you looked at this?  This is a blocking bug for shipping Prism.

**Comment by LeeParrishMSFT** [comment]
I have a fix and once I run the unit tests I'll get a pull request in for it. Minor change to a style name so low risk.

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.18008.65001
Templates: 0.14.18008.1
