### ISSUE TITLE
Prism: Adapt MasterDetail to use UWPCommunityToolkit and new designs

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1548]
We changed the Master Detail templates to use the ~~HamburgerMenu~~ MasterDetailsView control from the UWP Community Toolkit and did design changes. 
I think the Prism version of Master Detail should follow the same approach.

**Comment by crutkas** [comment]
what caused us to change the template to use the hamburger menu?  when was this change done?

**Comment by sibille** [comment]
@crutkas, I was refering to the MasterDetailsView control from UWP Community Toolkit, sorry for the confusion. 
We did this change in PR https://github.com/Microsoft/WindowsTemplateStudio/pull/1222/ and discussion on this took place in issue https://github.com/Microsoft/WindowsTemplateStudio/issues/1184

**Comment by crutkas** [comment]
i missed everyone being in agreement this was the best way forward.

**Comment by crutkas** [comment]
this feels like a prism ship blocking issue if the templates aren't in sync

**Comment by ralarcon** [comment]
@LeeParrishMSFT I think this is ready to be closed, isn't it?

**Comment by LeeParrishMSFT** [comment]
@ralarcon  Yes, we can close this as the fixes are checked in and verified in the dev branch.
