### ISSUE TITLE
Share source and share target icons

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1550]
Looking at the share source and share target icons I think they are interchanged. 
Shouldn't the icon where the arrow goes out of the box be the share source icon (as data is shared by the application) ?

![image](https://user-images.githubusercontent.com/24698018/33985439-e1c09d72-e0ba-11e7-8b7d-1c4853867f0c.png)

**Comment by mrlacey** [comment]
Yes. They are wrong.

This image is for sharing something from the app.
![image](https://winblogs.azureedge.net/win/2017/02/new-share-icon.png)

**Comment by ralarcon** [comment]
We will swap the icons. The most simple way is to swap the icons content and leave everything (templates and names as it is now)

**Comment by sibille** [comment]
Verified in 
Wizard: 0.14.17352.65001
Templates: 0.14.17352.1
