### ISSUE TITLE
Prism: Reduce use of composition templates where not necessary

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1555]
The following prism feature/pages have composition templates for prism that are not necessary as the feature/page has a separate template for Prism:

- ShareTarget, 
- Chart, 
- Grid
- MasterDetail, 
- ImageGallery 

Intention behind composition template was to augment reusibility of code. If neither the page/feature template nor the composition template are shared their content should be merged in the page/feature template to reduce complexity.

**Comment by crutkas** [comment]
is it possible to validate stability and get this in to the 1.6 release?  should this be a 1.7?

**Comment by ralarcon** [comment]
Not to much risk as I understand but there is no hurry. This falls in the side of template optimization, would say, we can leave it to 1.7 if needed.

**Comment by sibille** [comment]
This is not much risk, @ralarcon, @crutkas should we do this for 1.7?

**Comment by sibille** [comment]
ShareTarget Feature is missing extension in appxmanifest and resources are not replaced correctly.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18114.1
Wizard version: 0.18.18114.1
