### ISSUE TITLE
Build dev.templates.tests.full_20171215.5 failed

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1561]
## Build dev.templates.tests.full_20171215.5
- **Build result:** `failed`
- **Build queued:** 12/15/2017 8:18:37 PM
- **Build duration:** 4.75 minutes
### Details
Build [dev.templates.tests.full_20171215.5](https://winappstudio.visualstudio.com/web/build.aspx?pcguid=a4ef43be-68ce-4195-a619-079b4d9834c2&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f24301) failed

+ Process completed with exit code 1.

Find detailed information in the [build log files](https://uwpctdiags.blob.core.windows.net/buildlogs/dev.templates.tests.full_20171215.5_logs.zip)

**Comment by sibille** [comment]
Temporary failure
