### ISSUE TITLE
Clean projects don't work

### ISSUE THREAD

**Issue by StefanJanssen95** [Microsoft/WindowsTemplateStudio#1562]
I have tried the following 4 times with different MVVM frameworks and features.
### Repro steps

- Create a new project
- Choose a random setup (including the hamburger menu, might not work with non hamburger menus as well)
- Execute the scaffolded project

### Expected Behavior

I expect to see a view when building the project with at least something.

### Actual Behavior

Screen just stays in the loading screen while it's not doing anything. I kept it open for 2 hours and it doesn't change.

## System

* **VS Version:** 2017 15.5.2
* **WTS Wizard Version:** 1.5.17334.7
* **WTS Template Version:** (Please help me find this version)
* **Windows Build:** 17025.1000

**Comment by ralarcon** [comment]
Hey,

We are not able to reproduce this behaviour using the same VS Version (we have tried it on existing deployments as well as over a vanilla machine just installed).

![image](https://user-images.githubusercontent.com/2638875/34109953-7fc045ca-e405-11e7-9b9e-51c03112d7b8.png)

![image](https://user-images.githubusercontent.com/2638875/34109993-94bab03c-e405-11e7-8175-d48e1169df88.png)

![image](https://user-images.githubusercontent.com/2638875/34110056-c64fd0be-e405-11e7-86a1-5e34841e9a8b.png)

@StefanJanssen95 To investigate it further and try to understand what is happening behind the scenes, could you please share you generated project and the log files (just in case there is any exception)? You can find the log files under C:\ProgramData\WindowsTemplateStudio\Logs folder.

If it is fine for you, attach a zip file to this conversation, if not, I can provide an email.

**Comment by crutkas** [comment]
@ralarcon  note he is on an windows insider preview build.   @StefanJanssen95 when you say "execute the project" you mean compile and running the app?  click the generate to generate the project?

Can you do a screenshot and paste it in the screenshot?  I have seen once in a while VS just not compiling properly and canceling and rebuilding fixes it (more than just WTS generated projects).

**Comment by StefanJanssen95** [comment]
Today I accidentally started the version added to the start menu and it worked, while launching it from Visual Studio 2017 it doesn't. I will reinstall VS to see if the problem is in the installation

**Comment by StefanJanssen95** [comment]
@crutkas I build and execute it by pressing the button "> local machine": ![https://i.imgur.com/5CTQJdj.png](https://i.imgur.com/5CTQJdj.png)

But as I mentioned in my previous message it seems like its not a fault within the templates since it can be launched from outside visual studio.

**Comment by crutkas** [comment]
does a cleaning the solution then recompiling work?  Sadly this is outside WTS
