### ISSUE TITLE
Build dev.version_0.14.17350.01 failed

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1563]
## Build dev.version_0.14.17350.01
- **Build result:** `failed`
- **Build queued:** 12/16/2017 3:00:02 AM
- **Build duration:** 60.35 minutes
### Details
Build [dev.version_0.14.17350.01](https://winappstudio.visualstudio.com/web/build.aspx?pcguid=a4ef43be-68ce-4195-a619-079b4d9834c2&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f24365) failed

+ The job running on agent wtsb3 has exceeded the maximum execution time of 01:00:00.
+ The operation was canceled.

Find detailed information in the [build log files](https://uwpctdiags.blob.core.windows.net/buildlogs/dev.version_0.14.17350.01_logs.zip)

**Comment by sibille** [comment]
Changed build timeout
