### ISSUE TITLE
Use UWP Community Toolkit MasterDetailsView?

### ISSUE THREAD

**Issue by skendrot** [Microsoft/WindowsTemplateStudio#157]
Should the template page for MasterDetail use the control from the UWP Community Toolkit?

**Comment by ralarcon** [comment]
Are we going to shift to the UWP Community toolkit Master-Detail? If not, we can close this issue.

**Comment by mrlacey** [comment]
Can we get pros and cons lists for changing?

@skendrot what reason(s) did you have for proposing this? Anything we should be especially aware of when considering this suggestion?

**Comment by skendrot** [comment]
Mainly that there is a control that is actively being worked on and improved. I would consider the work here as duplicate from the one in the toolkit. The same problems faced with one implementation will need to be addressed in the other.

If moving to the UWP toolkit version is something we want to do I would be happy to take it on.

**Comment by crutkas** [comment]
**pro's**

- stays up to date


**con's**

- nuget dependency
- abstracts out a layer.
- For other pages that may need to launch, we have opposing metaphors.

**Comment by crutkas** [comment]
moving to open community question.

**Comment by crutkas** [comment]
closing, POR right now is to stay how we're doing it
