### ISSUE TITLE
The HamburgerMenu will be removed in a future major release. 

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/WindowsTemplateStudio#1575]
## For new Features:

* **Overview:** What you'd think should be added with scenarios
* **Links:**

## For Bugs: Error on VS 2017 (last Version) 
"The HamburgerMenu will be removed in a future major release. Please use the NavigationView control available in the Fall Creators Update" 

Error only for x64. 

### Repro steps - Compile a VS Project with compability on W10 16299

What did you do? How can someone else reproduce this?
Setting compability to 16299 

### Expected Behavior

What was expected to happen
(include screenshots if a visual issue)

### Actual Behavior

How can i Change to NavigationView Control, only that i make other Changes like "ActivationServices"?
Have any instruktions what changes i must do in "ShellPage"?

## System

* **VS Version: 2017
* **WTS Wizard Version: last
* **WTS Template Version: last
* **Windows Build: W10 16299 - Patchlevel last

**Comment by crutkas** [comment]
dup of  #1527.  known issue and we'll phase out the UWP Toolkit control for NavigationView for with the next update of Windows in spring 2018 timeframe.  We (WTS) supports the current release and the prior update of Windows.  This means we have to wait 2 releases before we can adopt new controls like NavigationView.
