### ISSUE TITLE
HamburgerControl does not initialize selected item

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1600]
### Repro steps
- Create a new project using Navigation Page
- Add few pages.

### Expected Behavior
The first element of the list should be selected showing the blue icon and the vertical blue rectangle on the left.

### Actual Behavior
The first page is selected and displayed in the main area. The navigation pane is showed as compact mode and the first element is selected, the icon is blue, but it is not showing the blue bar on the left.
When you select the second navigation item this blue icon appears.
Then you click on go back and blue rectangle is visible.

**App launch**

![image](https://user-images.githubusercontent.com/5556784/34205876-7077a7b8-e584-11e7-9983-7ad0133d5ecb.png)

**Navigate to second item**

![image](https://user-images.githubusercontent.com/5556784/34205900-8a75c01e-e584-11e7-89af-c1f3069579c4.png)

**Go Back**

![image](https://user-images.githubusercontent.com/5556784/34205902-8e1531a0-e584-11e7-9476-cdcde35fd2c7.png)

@nmetulev it looks it's an Issue of Hamburger control in Community Toolkit. What do you think?

**Comment by nmetulev** [comment]
@mvegaca, did this happen recently with an update of the toolkit, or where there any other changes? Is it using the NavigationView? Is this issue on a dev build or public release? If not too much trouble, could you share a quick repro project?

**Comment by mvegaca** [comment]
Hi @nmetulev 
It's happening on new release when you create a Navigation pane project and launch the App on FCU Windows version. The App is using NavigationView control and Marks as selected the first element but it doesn't show the blue rectangle on the left of the icon.

**Comment by nmetulev** [comment]
It looks like a bug with the HamburgerMenu, I created this bug on the toolkit side: https://github.com/Microsoft/UWPCommunityToolkit/issues/1730

**Comment by mvegaca** [comment]
Thank you @nmetulev 😄

**Comment by crutkas** [comment]
looks like they just checked in a fix

**Comment by crutkas** [comment]
eta for fix: toolkit v2.2 is scheduled for 2/28

**Comment by mvegaca** [comment]
I've checked that it's fixed by updating UWP Community Toolkit to  2.2 version (released yesterday).

**Comment by mvegaca** [comment]
In version 2.1 we are using the Method ItemInvoked that are using a event args Hamburge**t**MenuItemInvokedEventArgs with **T**. In version 2.2 it's is fixed to use Hamburge**r**MenuItemInvokedEventArgs and we should update it.
![image](https://user-images.githubusercontent.com/5556784/36837116-b73e0306-1d3b-11e8-8ff0-83a3fc848e8c.png)

**Comment by mrlacey** [comment]
I recall some other issues that meant we stayed on 2.0 of the toolkit, rather than move to 2.1.
We need to review/test everything when updating to 2.2

**Comment by mvegaca** [comment]
Code uploaded on branch [mvegaca/Issue1600-toolkit2.2](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue1600-toolkit2.2).

Tested and ready to PR on 2.1.

**Microsoft.Toolkit.Uwp.UI.Controls**
2.1.1 -> **2.2.0**

Used in
**Navigation Pane project type.
Master-Detail page.**

**Test on C#**
Code Behind **OK**
Mvvm Light **OK**
Mvvm Basic **OK**
Caliburn **OK**
Prism **OK**

**Test on VB**
Code Behind **OK**
Mvvm Light **OK**
Mvvm Basic **OK**


**Microsoft.Toolkit.Uwp**
2.1.1 -> **2.2.0**

Used in
**First Use Prompt.
WhatsNew Prompt.**

**Test on C#**
Code Behind **OK**
Mvvm Light **OK**
Mvvm Basic **OK**
Caliburn **OK**
Prism **OK**

**Test on VB**
Code Behind **OK**
Mvvm Light **OK**
Mvvm Basic **OK**

**Comment by sibille** [comment]
This is ready for integration. Should we include this in 2.0?

**Comment by mrlacey** [comment]
I think this should be in 2.0 if it doesn't affect anything else

**Comment by sibille** [comment]
@mvegaca We should update Microsoft.Toolkit.Uwp.Notifications and Microsoft.Toolkit.Uwp.UI too, to have them all aligned.

**Comment by mvegaca** [comment]
All UWP Toolkit version 2.2.0 checked in Dev nightly
Templates version: 0.17.18068.1
Wizard version: 0.17.18068.1
