### ISSUE TITLE
update telem for dec

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1614]
I need to update the telem.  I pulled it but need to input it

**Comment by crutkas** [comment]
in PR https://github.com/Microsoft/WindowsTemplateStudio/pull/1613

**Comment by mrlacey** [comment]
Is there a way to do this automatically? 
Or at the very least add it to your calendar as a recurring event

**Comment by crutkas** [comment]
Automatically no, sadly pretty manual process.  I did update the doc.  I'll set a cal reminder for myself.
