### ISSUE TITLE
Remove doc on PerspectiveParallax?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1623]
The docs folder includes a file about [using PerspectiveParallax in an app](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/Fluent_PerspectiveParallax.md).

There are a number of issues with this document
- It contains spelling errors (most notably in the title)
- It is incomplete, as it contains placeholders (xxxxxx) for version numbers
- It reads like an attempt to summarize existing, official, documentation that is also linked at the bottom of the file
- Despite a claim in the opening sentence, this has nothing specific to do with Windows Template Studio so it has no real reason for existing
- It isn't linked from any of the other documentation, or any comments or templates

Is it ok to delete it?

**Comment by crutkas** [comment]
Delete it.

**Comment by ralarcon** [comment]
PR accepted. Closing now.
