### ISSUE TITLE
Incorrect Settings Page Icon for Navigation Pane App with Prism Framework

### ISSUE THREAD

**Issue by LeeParrishMSFT** [Microsoft/WindowsTemplateStudio#1625]
### Repro steps

- Create a Navigation Pane App using Prism framework
- Add a Settings Page to the app

### Expected Behavior

The icon added to the Hamburger menu for the Settings page should show the settings icon (small gear):

![image](https://user-images.githubusercontent.com/30470292/34441524-e6fcf1e6-ec81-11e7-9f97-0a0770773649.png)

### Actual Behavior

The generated app has the document icon:

![image](https://user-images.githubusercontent.com/30470292/34441569-2b577e9c-ec82-11e7-9baa-5b7bd3d71335.png)

What really happened

The template has the wrong icon declared in the Project.SplitView.AddToSecondaryNavigationItems template.

## System

Current dev branch, not released yet.

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.14.18008.65001
Templates: 0.14.18008.1
