### ISSUE TITLE
SplitView.DisplayMode doesn't work at all in any State 

### ISSUE THREAD

**Issue by jeansusgodney** [Microsoft/WindowsTemplateStudio#1635]
I want the DisplayMode of NavigationView/HamburgerMenu to be CompactOverlay in any state. I have edited the ShellViewMode.cs but it doesn't work at all. The DisplayMode stays Inline 

`        private void GoToState(string stateName)
        {
            switch (stateName)
            {
                case PanoramicStateName:
                    DisplayMode = SplitViewDisplayMode.CompactOverlay;
                    IsPaneOpen = false;
                    break;
                case WideStateName:
                    DisplayMode = SplitViewDisplayMode.CompactOverlay;
                    IsPaneOpen = false;
                    break;
                case NarrowStateName:
                    DisplayMode = SplitViewDisplayMode.CompactOverlay;
                    IsPaneOpen = false;
                    break;
                default:
                    break;
            }
        }`

**Comment by mrlacey** [comment]
@jeansusgodney If you want it to always be in the same state I'd remove all the state change code from the CS file(s) and the adaptive trigger from the XAML and then set the desired mode in the XAML file.

**Comment by crutkas** [comment]
What Matt said :)  hard code the xaml and remove the state trigger

**Comment by jeansusgodney** [comment]
Hi guys, thank you for the reply. I have removed all the state change from the Shell .xaml and .cs file. and set the DisplayMode="CompactOverlay" in the .xaml file.

But it still doesn't work.

**Comment by mrlacey** [comment]
@jeansusgodney Can you share a repro?
It might be due to which version of the templates you're using - which we'd see in a repro.
