### ISSUE TITLE
Wizard: Complete generation cycle

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1641]
Link wizard selection with templates generation.

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by crutkas** [comment]
does this work item imply when i click "Generate", it generates the solution?

**Comment by mvegaca** [comment]
Yes, it is.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
