### ISSUE TITLE
Wizard: Reorder with Drag and drop

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1642]
Reorder selected template using drag and drop.

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by mvegaca** [comment]
It's currently implemented on new wizard redesign, but it's only accessible from mouse, I'm going to translate the same usability on the old wizard to reorder using the keyboard.
- select the item using arrows.
- press space bar to select the drag source.
- select the item position you want to move the item using arrows.
- press space bar to drop the item and complete the reorder operation.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
