### ISSUE TITLE
Wizard: Remove selected template

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1643]
- Add the possibility to remove selected template.
- Disable removing option when a template cannot be deleted.
- Give feedback to the user when a template cannot be removed (i.e. dependency).

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by crutkas** [comment]
verifying this is to remove single items, not multiple items.  "Selected templates" implies multiple

**Comment by mvegaca** [comment]
Both kind of items, every selected template can be removed unless:
- This template is a page and there are no more than one pages.
- Another template depends on that.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
