### ISSUE TITLE
Wizard: Complete Template naming validations

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1644]
Complete Template naming validations

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by crutkas** [comment]
is this disallowing non-valid names for pages / features?

**Comment by mvegaca** [comment]
Yes, this task consists of check the naming validations error, infer the correct names and display the generated errors.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
