### ISSUE TITLE
Wizard: Template updating

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1645]
- Display Templates version and wizard version as selectable text.
- Create options to update or refresh the templates.

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by sibille** [comment]
Verified in dev/nightly
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
