### ISSUE TITLE
Wizard: Templates adding

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1646]
- Resolve dependencies
- Lock a single instance template when it's already added.
- Make templates selected using Keyboard (By now it's adding templates using an ItemClick Command).

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by sibille** [comment]
Verified on dev/nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
