### ISSUE TITLE
Wizard: Loading feedback

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1647]
- Lock ComboBox when loading.
- Change notification closes using a timer to notification closes when loading complete.
- Lock next / create buttons.
- Lock Sequential Flow area.
- Add no pages/features selected text to project details.

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
