### ISSUE TITLE
Wizard: Error handling

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1648]
- Add a global exception handling and view.
- Add a known error handling using notifications.
- Think about different errors interact with other errors, Errors that can override other errors and errors that will be added to the notifications pool.

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
