### ISSUE TITLE
Wizard: Right Click Design

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1649]
Request a design for right click on the new wizard.

**Comment by mvegaca** [comment]
Hi @crutkas 

We need to ask the right click design to design team.
But the moment I'm working on the first approach that is similar to the new wizard design:
- Same bottom buttons bar.
- Same workflow area with two steps: Template selection, Changes summary.
- Same header style.
- Same notification management.

Step 1
- Same template list layout and detail page using navigation.
- Selection area on the right to edit the template name and view the licenses.

Step 2
- Similar file list using Visual Studio Colors
- Similar file comparations using Monaco component.

**Comment by mvegaca** [comment]
Making progress on Right click development.

![image](https://user-images.githubusercontent.com/5556784/35213869-706d9698-ff5f-11e7-8902-82d1268428da.png)

Currently working on **Changes Summary** page

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
