### ISSUE TITLE
Wizard: Integrate Dev branch Sync infrastructure

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1650]
Integrate Dev branch Sync infrastructure.

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
