### ISSUE TITLE
Wizard: Add Windows Template Studio Colors to Visual Studio

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1652]
There are some colors that we need to use and are not available on Visual Studio Color Collections.
By now, I've created two color collections with hardcoded RGB values.
- ThemedCard
- WindowsTemplateStudio

We could probably need to add more colors during new wizard development.

We are also taking colors from VS color collections:
- CommonDocument
- CommonControls
- ThemedDialog

The source of all colors can be cheked on [VSStyleValuesProvider](https://github.com/mvegaca/WindowsTemplateStudio/blob/wizard-redesign/code/src/UI/V2Services/Styles/VSStyleValuesProvider.cs).

The code of new wizard can be checked on [wizard redesign branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/wizard-redesign).

**Comment by crutkas** [comment]
where are those two being added?  how do those colors react w/ dark theme and high contrast

**Comment by mvegaca** [comment]
Those color collections should be added to Visual Studio on a future release of Visual Studio with all colors that we need to use. By the moment the colors are fixed as static values (light theme) but we should fonund equivalent values to other themes before adding this to VS. I think it will not be easy 😄

**Comment by crutkas** [comment]
I know there were 2 colors or something that weren't in the service already but did the designer's mock use windows blue?

**Comment by mvegaca** [comment]
New Icons and color fixes on #1878

**Comment by mvegaca** [comment]
Check fixed on
Templates version: 0.16.18047.4
Wizard version: 0.16.18047.1
