### ISSUE TITLE
can uri scheme featue be used for File Assosiation?

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#1653]
I just wanted to clear something up, I have File Assosiation in my app. i.e: if a user opens a video file it opens my app and go straight to the playing page.

My Question is : Can I do this with Uri scheme feature in the template studio? If yes then how exactly can I do that? I checked official docs and it turnes out, "mp4" extension is for basic app of windows so it will be ignored? Doest that mean I cant use it for my purpose and I will have to use OnFileActivated handler ? Also I read wts docs and followed all steps and at the end wrote the uri in the edge and pressed enter but my app didnt open, am I missing something here? I just want to clarify before I proceed with trying to implement it. 

**Desired Behaviour:**  I have created a pivot project with some pages, but then for playing page, I removed it from my Pivot and put it ( NowPlaying.xaml page ) directly in the main frame, i.e : _NavigationService.Frame_ . Now when user plays a video file the app should open and go directly to NowPlayingPage, instead of going to PivotPage ( which normally opens on usual launch of the app ).

**Thanks in advance.** 

* **VS Version:** VS 2017 15.5
* **WTS Wizard Version:** Dev Nightly
* **WTS Template Version:** Dev Nightly
* **Windows Build:** FCU

**Comment by crutkas** [comment]
Nothing stopping you from refactoring the code to have them both call the same method.

**Comment by mrlacey** [comment]
The UriScheme functionality handles directing system launched URIs to the app. Given a URI such as `myapp:play?artist=skrillex` or `myapp:play?file=c%3A%2Fvideos%2Fskrillex%2Frecess.mp4` (where **myapp**) is the scheme.  
File association is done by adding the handling of system launched files based on the file extension. So, if you clicked on `myfile.mp4` in file explorer, the OS would know that your app could be used to open that file if it has created the association with the **mp4** file extension.

As @crutkas has said, you could have the handlers for each call a shared piece of code for processing the details passed to the app but you would need handlers for both. We provide a URIScheme handler but don't currently provide a feature that adds a handler for file activation.

When you say you "read wts docs and followed all steps" do you mean [the activation doc](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/activation.md) which talks about creating a handler for file association?

Having a feature for File Association is something I've thought about adding but that there is already an explanation for doing this in the docs and it would need to be replaced with another example of writing a custom activation handler.

If you think that a File Type Association Feature would be a good addition, please raise a new issue to request this. (In theory, if we had features for all possible activation handlers we wouldn't need documentation on how to create any more.)

**Comment by touseefbsb** [comment]
well, not having documentation anymore and having them as features, I think that would be ideal for a developer as it will further reduce their work. there can be an option or a list of checkboxes in the wizard, where developer can specify which activation handlers their app need, and they can mark all those they need and then that can be generated by the app, that can include FileAssosiation handler along with, uri scheme handler and all other basic ones.

On the other hand, I do understand how File Assosiation works from double clicking a file in file explorer, but I am still not sure what a uri scheme activation does, I mean what is exactly its use case for our customer, so that we will be needing to add this activation handler feature in our app? If I understand that maybe I can know better how to work with both of them together, or ideally suggest all activation handlers to work together in future version of WTS. and when I said i read the wts docs for uri scheme, I meant the following docs, just to test the sample but it didnt work for me, maybe I missed a step bcz I am not sure what a uri scheme feature is.

https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/features/uri-scheme.md

I included uri scheme feature in my app bcz I thought it will help me with FileAssociation use case, but thats a bit different I guess.

**Comment by crutkas** [comment]
giving an app a scheme allows it to be launched via the protocol.  if one app wanted to launch another, this is one way that could happen.    Exactly what matt had above.  a great example would be the mail app and the well known mailto scheme.  https://en.wikipedia.org/wiki/Mailto

File association, while a related launching system, is different from uri scheme.  As of now, we don't have file association as a WTS feature.  while it is a good idea to add, we currently don't.

WTS's goal is to get you up and going faster with best practices but implementation details like how your app should launch around certain scenarios becomes too hard for us to generate in a generic way that would work for everyone.  If we were to add file association in, we would add a comment about maybe having you, the developer, to think about keeping your launching logic in a single spot.  Past that, i worry we'd be doing too much

**Comment by touseefbsb** [comment]
so the main use of uriScheme is to launch one app from another app? for example if I am a developer and I developed two apps and I want to launch App A, from App B ( both created by me ) I will do it with uriScheme, right?  or If I know the protocol for any app I can launch that too from within my app. I think I get it now both are completely different features, btw can you let me know that if urischeme can be used with cortana? I mean if user gives certain command to cortana ( play xyz song ) and it matches the protocol of my app, so would my app be launched then? or is that just related to cortana and not anything to do with uriScheme?
Thanks

**Comment by crutkas** [comment]
that is one use, another use would be Timeline with activity feed.  Cortana skills is another way.  If you want to deeplink into your app, this is how you can do it.  someone could do this via the run prompt or other ways.  what you outlined for cortana is true, if you set up your cortana skill correctly, your app should launch :)

This is actually why Uri Scheme was one of those must add sooner than later features as so many other items need it to actually be successful.

**Comment by touseefbsb** [comment]
oh alright thanks for the clarification :)
