### ISSUE TITLE
UI.Test.ruleset is missing

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1658]
UI.Test.csproj references a custom ruleset file but it is not in the repo.

https://github.com/Microsoft/WindowsTemplateStudio/blob/cf3765a521bdee1f7626ccfd9d0f54bcd3b4925f/code/test/UI.Test/UI.Test.csproj#L33

**Comment by ralarcon** [comment]
The Analyze configuration had the correct config 
![image](https://user-images.githubusercontent.com/2638875/34677710-40c1b920-f491-11e7-9857-b5b1a1d7b5f0.png)

But Looks like the references to the file in the project and the code analysis for debug and release configuration were obsolet (maybe a change lost in some merge). 

Fixed now in commit bcd4e6491a8f8a7cd9d5e6222243be79ccc88e91

**Comment by mrlacey** [comment]
reopening to track removal of reference to unneeded file

![image](https://user-images.githubusercontent.com/189547/34679208-2d4e8e8a-f48d-11e7-8c13-4f5fb01cec2f.png)

![image](https://user-images.githubusercontent.com/189547/34679219-37357d14-f48d-11e7-9c87-8c1d31e852c4.png)

**Comment by mrlacey** [comment]
Closing again. Was already removed in https://github.com/Microsoft/WindowsTemplateStudio/commit/bcd4e6491a8f8a7cd9d5e6222243be79ccc88e91
