### ISSUE TITLE
Update Settings keys to avoid possible collisions

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1660]
Update key names used for settings to try and minimize possible collisions with user code or libraries that may use the same name but different content (or formatting) so as to avoid issues.

X-Ref https://github.com/Microsoft/WindowsTemplateStudio/issues/1659#issuecomment-356124183

What to add or how to rename items should be done on a case by case basis. Names should be meaningful without adding generic prefixes/suffixes.  
e.g. If currently using `RequestedTheme` a better value might be `AppBackgroundRequestedTheme`. A worse value would be `wts.RequestedTheme`.

Making keys longer will, in theory, reduce the likelihood of a clash.  
**But**, need to identify if there's a max length of the key value. (I can't find anything in the docs but it's worth checking. There probably is one.)

Might also be worth reviewing error handling when there's a problem getting a previously set value. It's probably best to let any exception fall through for the developer to handle as they see best there's no harm in reviewing this.

**Comment by crutkas** [comment]
ok, so we said we would do this, but there wasn't a discussion on implementation.

**Comment by ralarcon** [comment]
Three keys, aligned with what @mrlacey have mentioned and all agree is a good idea. Naming can be changed. I think @dgomezc was about to comment to the issue but github was down for a while...

**Comment by dgomezc** [comment]
After reviewing the settings key in the templates files I made the following renames:

suspensionState -> SuspendAndResumeState
NotificationQueueEnabled -> LiveTileNotificationQueueEnabled
RequestedTheme -> AppBackgroundRequestedTheme

**Comment by mrlacey** [comment]
While tidying up keys, there are some consts in the ImageGallery template that are used as keys and could be better named.

This isn't great.

    public const string ImageGallerySelectedImageId = "ImageGallerySelectedImageId";

**Comment by crutkas** [comment]
@mrlacey, related but diff issue.  Suggest we open a new one and maybe provide suggestions?

**Comment by dgomezc** [comment]
When the code of Image Gallery Page is generated, the substring "ImageGallery" is replaced by the name of the page. 

For example, if you generated a project with an image gallery type page named "MyPictures", the generated code is:

    public const string MyPicturesSelectedImageId = "MyPicturesSelectedImageId";

**Comment by mrlacey** [comment]
I can see what it's doing. My issue is with the usage, it looks like an actual Id is used as the key when it's actually a fixed string

**Comment by ralarcon** [comment]
Hey @mrlacey, can you help us to better understand your concern... the data stored in the settings is the "SelectedImageId", so I do not understand why you consider it is not good the current definition... here is how is used:
`ApplicationData.Current.LocalSettings.SaveString(MyPicturesPage.MyPicturesSelectedImageId, ((SampleImage)SelectedImage).ID); `

**Comment by mrlacey** [comment]
Look at this line
```
ApplicationData.Current.LocalSettings.SaveString(
        MyPicturesPage.MyPicturesSelectedImageId,
        ((SampleImage)SelectedImage).ID);
```

From just looking at that code, what is being passed to the `SaveString` method? 

Doesn't it look like two "Ids" are being passed to the method?

It looks strange for the code to pass two "selected image Ids"?

That it's not two Ids is my issue. The first isn't an Id. It's a badly named cost that's used as a key.

A better name would be `MyPicturesSelectedIdKey`. This makes it clear that it is a key.  I can look at this substituted into the above line (represented below) and it's immediately clear that a key and value are being passed, not two values. I don't get drawn into wondering why two values, asking what is that first Id? Why is it just a string with a value the same as the variables name? And then wasting time trying to work out why it's doing what it's doing.

```
ApplicationData.Current.LocalSettings.SaveString(
        MyPicturesPage.MyPicturesSelectedIdKey,
        ((SampleImage)SelectedImage).ID);
```

Confusingly named variables (or consts) make for code that is hard to read, understand, and follow.  
If names are confusing (like this was for me) they should be improved where possible. That's what I'm asking for.

_(It's been a long time since I've looked at the generated code or I would have flagged it earlier. I've just been trusting that the C# code is correct and making the VB code the same. And yes, I really care about naming. If thousands of developers, many with limited experience, are going to read this code I want it to be easily understandable.)_

**Comment by ralarcon** [comment]
Opening another issue to update the XXXXSelectedId to XXXXSelectedIdKey

**Comment by sibille** [comment]
Verified in dev-nightly:
Wizard: 0.16.18015.65001
Templates: 0.16.18015.2
