### ISSUE TITLE
Generated project to target version of UWP with latest security fix

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1676]
As there is a new version (**6.0.6**) of the **.Net for UWP** package that addresses a potential security issue. ([announcement](https://blogs.msdn.microsoft.com/dotnet/2018/01/09/net-for-uwp-january-2018-update/)) this should be referenced by the generated projects.

In the past, we've been slow to update to newer versions of these packages because if the package (which is quite large) has not been downloaded before it causes the nuget restore step in the project generation to be slow while the package is downloaded.

I think we should still target the new release because:
- The store will use it internally anyway so it's better to start using it sooner to reduce the possibility of issues or changes in behavior with the new version. (No one wants to build and test with one version only to find a bug (or worse!) when the app is distributed via the store.)
- We shouldn't encourage people to ignore updates and security patches.
- WTS exists to help developers take positive first steps when creating an app and that includes being aware of security issues and applying patches.

If the speed issue is a concern it should be called out in the release notes.

**Comment by ralarcon** [comment]
Not problem to update it for next release. Just going to double check the impact if any to document it if required.

**Comment by sibille** [comment]
Verified on pre-version:
Wizard: 0.11.18023.1
Templates: 0.11.18023.1
