### ISSUE TITLE
Icons that are not applying the foreground correctly

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1695]
The are some template icons that contains a part that it isn't applying the foreground.

**Image Galley Page template**
![image](https://user-images.githubusercontent.com/5556784/34950686-28371afc-fa14-11e7-83de-20eb1bc9b947.png)

**Drag and Drop feature template**
![image](https://user-images.githubusercontent.com/5556784/34950705-392246de-fa14-11e7-90a9-02a81be2c50e.png)

This issue only can be appreciated in new wizard design that is applying a color to the icons.

**Comment by mrlacey** [comment]
Moving this to 2.0 as it's specific to the new wizard.
 
Have created a related issue to track the impact of this on the current wizard.

**Comment by mrlacey** [comment]
Fix in #1764 may also fix this when new wizard branch is merged into dev

**Comment by mrlacey** [comment]
Also Camera page icon

![image](https://user-images.githubusercontent.com/189547/35914643-e9aabd94-0bfb-11e8-9cd6-9d96d94368d0.png)

**Comment by mrlacey** [comment]
MVVMLight icon doesn't appear to be colored correctly

![image](https://user-images.githubusercontent.com/189547/35914683-117a6612-0bfc-11e8-8e65-d1cb24a597b6.png)


Prism icon uses color. Is this correct? Is the use of a related gray color coincidence?

![image](https://user-images.githubusercontent.com/189547/35914699-1df9e76e-0bfc-11e8-9cc2-c3864b0e08de.png)

**Comment by crutkas** [comment]
everything should be a flat, single color

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18045.1
Wizard version: 0.16.18045.1
