### ISSUE TITLE
What SDK do I need?

### ISSUE THREAD

**Issue by Oleg26Dev** [Microsoft/WindowsTemplateStudio#1697]
I have installed the WTS in VS2017 (Windows 7).
When try to create the simple application I receive the error:

Unable to add the project to the solution. Make sure you have the expected SDK installed

What SDK do I need?

**Comment by mrlacey** [comment]
@Oleg26Dev As per the [prerequisites](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#prerequisites) for using the extension, you must be on Windows 10 (Creators Update) or later. WTS is a tool for building Windows 10 (UWP) apps and as such needs to be run on a machine with that OS installed.

@ralarcon is there a way to enforce this on install of the VSIX?

**Comment by ralarcon** [comment]
The UWP platform SDK is part of the dependencies so not sure how the Vsix Installer infrastructure handle this, I can double check and verify if there is a way to ensure we are in Windows 10 but do not remember any restriction regarding OS... assigning my self to have a look on it.

**Comment by Oleg26Dev** [comment]
I have installed the Windows 10 SDK on my Windows 7 machine , probably it was installed with VS2017

C:\Program Files (x86)\Windows Kits\10

And that is the manifest
```
<FileList
  DisplayName = "Universal Windows"
  PlatformIdentity = "UAP, Version=10.0.16299.0"      
  TargetFramework = ".NETCore,version=v4.5.3;.NETFramework,version=v4.5.3"
  MinVSVersion = "14.0"
  MinOSVersion = "6.1"
  MaxOSVersionTested = "10.0"
  UnsupportedDowntarget = "Windows, version=8.1">

  <File Reference = "Windows">
    <ToolboxItems VSCategory = "Toolbox.Default"/>
  </File>
</FileList>


```

**Comment by ralarcon** [comment]
From https://developer.microsoft.com/windows/downloads/windows-10-SDK:

![image](https://user-images.githubusercontent.com/2638875/34980423-cbe2e15a-faa4-11e7-97ca-3a2fbae7b40a.png)

This means that you can install the SDK in Windows 7, but just to develop Win32 apps. If you want to develop UWP, you will need Windows 10 as development platform. Because of that you still seeing the message related to the SDK.

**Comment by Oleg26Dev** [comment]
There is 
[](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk)

> The Windows SDK has the following minimum system requirements:
> 
> Supported operating systems
> Windows 10 App Development (UWP)
> 
> Windows 10 version 1507 or higher: Home, Professional, Education, and Enterprise (LTSB and S are not supported)
> Windows Server 2012 R2 (Command line only) Windows Server 2016 (Command Line only)
> Win32 Development
> 
> Windows 10 version 1507 or higher
> Windows Server 2016: Standard and Datacenter
> Windows 8.1
> Windows Server 2012 R2
> Windows 7 SP1
> (Not all tools are supported on earlier operating systems)

As I understand it means that UWP apps can be created only in W10.

**Comment by ralarcon** [comment]
Welcome @Oleg26Dev, I will close the issue now.
