### ISSUE TITLE
Do VSIX prerequisites need updating?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1699]
According to the [prerequisites list for installing the extension](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#prerequisites), the minimum supported version of Visual Studio 2017 is update 3 (15.3)

It's not possible to download this version for install and therefore testing cannot be done against 15.3 or 15.4 unless machines with these versions are kept around.

Visual Studio only makes the current and next/preview update versions available for download/install. Should WTS only support the same?  And if not, how are older VS versions tested?

**Comment by ralarcon** [comment]
The prerequisites define the minimum version as 15.3 or higher. This does not mean it do not work on higher versions. If you are running 15.3 and can not or don't want to update it (whatever the reason) you still can install WTS.

Our dependencies with VS are related to the UWP SDK and net standard dependencies, by now, 15.3 or higher is our need...

**Comment by mrlacey** [comment]
Yes, I get 15.3 _or higher_.  
But, it's no longer possible for anyone to download that version. This includes anyone wanting to test against it.  How to test and ensure that any new functionality works against that version when VS no longer make it available.

**Comment by ralarcon** [comment]
I know what you mean, with the VS minor version changes we do not expect big impact changes without having notice (but may occur). What was working on 15.3, still works in higher versions as we are working with the newer versions every day...  Our dependency from 15.3 is just the version which ensures you have the required pre-req regarding UWP. 

We can update the pre-requisite and say that we recommend to use the most "Current Visual Studio Version"... @crutkas what do you think?

**Comment by crutkas** [comment]
we should snap to what VS supports.  Which is currently N and N-1.  15.4 and 15.5

**Comment by ralarcon** [comment]
With VS 15.4 we are in the same situation as it can't be download as well, so what we can do is to reference the most current version of Visual Studio (saying something like "Visual Studio with the Latest Update")...

**Comment by sibille** [comment]
I think we should not prevent people using VS 15.3 from using our extension if there is no explicit dependency on a later version, unless we want to "push" them to update.

**Comment by sibille** [comment]
We could change the docs (https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md) to say that pre-req is 15.3 but there is official support for VS N and N-1.

**Comment by mrlacey** [comment]
Making officially supported versions clear seems like a suitable compromise.

**Comment by sibille** [comment]
Done
