### ISSUE TITLE
Images on MasterDetail pages not displaying correctly in VB projects

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1706]
Images show as grey rectangles, rather than the symbol image.

This is an issue with Unicode character encodings.

A fix already exists as part of the work for #1336 (where this regression was identified) - I'm sure I've fixed this before.

Raising this so can get a fix into the nightly build ASAP, rather than wait for this fix to come with the other changes.

**Comment by mrlacey** [comment]
Before

![image](https://user-images.githubusercontent.com/189547/35007407-8767bbac-faf1-11e7-8911-74424c5b9e67.png)

**Comment by mrlacey** [comment]
After

![image](https://user-images.githubusercontent.com/189547/35007809-7b35b5a4-faf2-11e7-8d04-fa31a2e21af1.png)

**Comment by ralarcon** [comment]
Any clue regarding this rising up again?

**Comment by mrlacey** [comment]
I'm not sure where the regression came from and can't see it in the history but I'm certain I fixed it before.

New automated tests 😄 will detect any such regression in future though.

**Comment by ralarcon** [comment]
Good!

**Comment by mrlacey** [comment]
Partial screenshot of test output that would detect this in future
![image](https://user-images.githubusercontent.com/189547/35039203-0822a81e-fb75-11e7-82a8-1fd67fa19996.png)

**Comment by ralarcon** [comment]
Wow! this is part of the new UI test?

**Comment by mrlacey** [comment]
Yes. X-Ref image and video link at  https://github.com/Microsoft/WindowsTemplateStudio/issues/1336#issuecomment-358276316

**Comment by mrlacey** [comment]
Verified in 

Wizard: 0.16.18017.65001
Templates: 0.16.18017.4
