### ISSUE TITLE
Wizard shows wrong title and buttons when updating templates on second page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1709]
### Repro steps
1. Configure a new template version compatible with current wizard
2. Start wizard
3. Click next
4. Refresh templates from version and notification area

### Expected Behavior
Should reload the templates and go to first page

### Actual Behavior
Reload the templates and goes to first page but title and buttons are wrong
![image](https://user-images.githubusercontent.com/24698018/35032338-e106f752-fb66-11e7-9135-9dfc788521ac.png)

## System
Dev

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.16.18022.65001
Templates: 0.16.18022.1
