### ISSUE TITLE
Hamburger button position wrong on latest insider build

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1716]
![image](https://user-images.githubusercontent.com/189547/35050476-d6677f0e-fb9a-11e7-9a56-9f87dd427b51.png)

Using latest dev-nightly templates.

When running a SplitView app on a machine running on Windows Insider Build (17074.rs_prerelease.180106-2256) the position of the hamburger button is displayed to low. 

This does not occur on a machine running the FCU version of Win10.

I'm unable to identify any other difference between the two machines I have this running on that may be causing the issue.

**Comment by mrlacey** [comment]
Can anyone else repro this?

**Comment by phraemer** [comment]
Me.

Windows Template Studio 1.6.17355.2
Visual Studio 15.5.4
Windows 10 Enterprise Insider Preview version 1709 build 17074.1000

**Comment by mrlacey** [comment]
As this only happens on Insider builds, I suggest we monitor and revisit after the next insider build is released.  
I can't see an easy fix for this and don't think it's something we should be spending time on.

**Comment by crutkas** [comment]
agreed if this is insider builds issue.  one question is does this happen on the insider build's normal control without WTS

**Comment by mrlacey** [comment]
I can't get a full repro but believe it's due to the control on the insider build putting the back arrow in a different place.

**Comment by thepiratejester** [comment]
Hi, I can repro this bug in my machine. In fact, it exists since previous build (17073). This bug is also present in some system apps: Windows Defender Security Center and Tips

![image](https://user-images.githubusercontent.com/29515596/35187350-95917ea0-fdf0-11e7-9772-ba79f12fb390.png)

![image](https://user-images.githubusercontent.com/29515596/35187417-7ae2a4d4-fdf1-11e7-8c02-6d54635e9886.png)

**Comment by michael-hawker** [comment]
@nmetulev you have a contact for this, they aware of the issue in the insider builds?

**Comment by EdAlexander** [comment]
Problem not manifest when setting UseNavigationViewWhenPossible="False"

**Comment by crutkas** [comment]
@EdAlexander looks to be an issue with the navview for WIP.  i'll follow up with the XAML team

**Comment by mdtauk** [comment]
The issue is still present in the RS5 branch in 17604 @crutkas  This needs to be fixed before RS4 goes live.

**Comment by crutkas** [comment]
@mdtauk yup, bug fixes are still going into the current release which then are also put into the next gen branch.

looking into this now.

**Comment by crutkas** [comment]
bug is verified and looks to have been fixed.  going to see when it will be merged into a public SDK drop.

**Comment by EdAlexander** [comment]
Just for clarity:  Is this a bug in Template Studio, UWP community toolkit, or W10?

**Comment by mrlacey** [comment]
@EdAlexander  It's an issue with the native control in the insider builds

**Comment by crutkas** [comment]
Bug in the native Navigation view control in WIP builds. It is fixed but hasn’t hit a public build.

The toolkit does a smart flip between their custom and the native control that was introduced in fall creators update.

**Comment by EdAlexander** [comment]
From above, I am also interested in pushing the secondary items to the bottom of the pane.... Is this possible?  I have confirmed that on production W10 (fall creators update) that the secondary items are listed with no alignment.

**Comment by mrlacey** [comment]
@EdAlexander in terms of moving secondary items to the bottom. See an explanation of why and a workaround at https://github.com/Microsoft/WindowsTemplateStudio/issues/1763#issuecomment-363251560 
If you want to move more than just the settings, you could add those items to the `PaneFooter` of the NavigationView.

**Comment by crutkas** [comment]
bet this is fixed now

**Comment by mrlacey** [comment]
no longer repos on 17128
