### ISSUE TITLE
Offical Beta feed for WTS

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#1718]
I think it would be great if we could have a "beta" feed that would be an opt-in feed.  Items that are deemed beta would have a "beta" tag next to it.

Items in this feed could be items that are inside a WIP build.  There are new APIs and features that are in new releases but don't meet our N and N-1 requirement.

#1478 & #234 are backbone items for this.

**Comment by mrlacey** [comment]
Could also serve as providing early access to new features/pages that will be in the next release (but without needing to use the dev-nightly feed.)

To be clear. This would be for templates only and couldn't include any new templates that require new wizard functionality.

**Comment by ralarcon** [comment]
Exactly @mrlacey, I see this as a way to early distribute the incoming templates.

**Comment by crutkas** [comment]
Maybe "Beta" and "Early adoption".

**Comment by nguyenminhthuat** [comment]
Sự cố bị hack

**Comment by touseefbsb** [comment]
so no beta feed it seems uptil now :)

**Comment by mrlacey** [comment]
> so no beta feed it seems uptil now

Correct. There is still no beta feed. There's also nothing we have that we'd put in one yet.
The work for this is low priority and there are lots of other things we need to do before this becomes possible.
