### ISSUE TITLE
Wizard: Integrate Design Team feedback

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1730]
Things TODO:
- [x] Add **Term and conditions** text and link.
- [x] Template layout must show 3 lines of description.
- [x] Disabled textbox on templates added must hide the box border and leave the text as black.
- [x] Add project type and design pattern icons in combo box items.
- [x] Add about WTS, templates version and wizard version on the bottom of project details list.
- [x] Add refresh templates button (Only visible on debugging).

Things to Fix:
- [x] Add selected by keyboard status the same layout to mouse over status.
- [x] Select project type and design pattern by click or enter.
- [x] Reduce "+" icon on templates card and fix paddings.
- [x] Confirm **template renaming** with "enter".
- [x] Start **renaming** a selected template with **F2 Key**.
- [x] **Remove** a selected template with **Del Key**.
- [x] Too much space between **licenses** on project details.
- [x] **Reorder** using Ctrl + up/down arrow
- [x] If you click on any step wizard should mark as checked the previous steps.
- [x] Remove header for the dialog box.
- [x] Remove dotted lines from all FocusVisualStates

**Comment by sibille** [comment]
Selected by keyboard status does not have the same color as  mouse over status in step navigation pane.

![image](https://user-images.githubusercontent.com/24698018/36094376-44bb29f8-0fee-11e8-805e-fdf69f1b45a4.png)

**Comment by mvegaca** [comment]
Updates on #1886

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18046.3
Wizard version: 0.16.18046.1
