### ISSUE TITLE
App crashed when clicking ok button in toast notification

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1731]
Create an application with first run prompt and toast notifications features. Run the app and click on toast notification ok button, an exception occurs with the following message:

Only a single ContentDialog can be open at any time.

![image](https://user-images.githubusercontent.com/12777039/35320768-40094786-00e5-11e8-94a6-25473a808938.png)

**Comment by sibille** [comment]
This did not happen before as isfirstrun flag was set to false when the dialog was shown. 
SystemInformation class from UWPCommunityToolkit return isfirstrun = true during the complete first run. We decided to integrate a flag to avoid the dialog again when it was already shown.

**Comment by crutkas** [comment]
confused what the bug here is?  Toast is independent of a dialog

**Comment by sibille** [comment]
The click on the ok button of the toast activates the app again and the firstrunservices tries to show the firstrundialog again, which causes the crash

**Comment by sibille** [comment]
Verified in dev-nightly: 
Wizard: 0.16.18025.2
Templates: 0.16.18025.2
