### ISSUE TITLE
App takes to much time to update the theme when there are many features added

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1752]
If you add all features to the app, the app adds a delay on setting the dark theme.

ThemeSelectorService.SetRequestedTheme() should be added at the beginning of ActivationService StartupAsync.

**Comment by mvegaca** [comment]
Fixed on #2035.

**Comment by mrlacey** [comment]
Any issue with moving this into the 2.0 milestone so it can be part of the solution for #1998 ?

**Comment by sibille** [comment]
No, moving to solve #1998

**Comment by mvegaca** [comment]
#2044 
Moved await Task.CompletedTask; to the bottom of the method.

@mrlacey  could you please review this Issue on VB?

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.17.18074.2
Wizard version: 0.17.18074.2

**Comment by mrlacey** [comment]
looks good to me too.
