### ISSUE TITLE
Changelog.md 

### ISSUE THREAD

**Issue by magol** [Microsoft/WindowsTemplateStudio#1755]
I have not used this in a year, and I was curious about what has changed during this time. Unfortunately, there is no changelog (that I can found), so it's not easy to see. There was a changelog.md, but it was strangely deleted in #532, with the motivation that the information is already in [roadmap.md](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/roadmap.md). But that's not true, as it only contains what you're working on right now.
Please, create an [changelog.md](http://keepachangelog.com) that list the most important improvements in each version,

**Comment by mrlacey** [comment]
I suggest adding a changelog file that just points to https://github.com/Microsoft/WindowsTemplateStudio/releases as that contains a history of releases. This is what would be in a changelog and duplication seems unnecessary and likely to get out of sync.

In the past, roadmap contained a larger list of changes in past releases but it wasn't as comprehensive.

**Comment by mrlacey** [comment]
Merged to dev so can be closed
