### ISSUE TITLE
Wizard: Download and refresh new templates (if available) when entering the wizard 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1756]
If there is a new version of templates available (that is compatible with the wizard) download and load this version before displaying templates to ensure people work with latest templates.
Show Progress bar for download.

**Comment by mrlacey** [comment]
Didn't the wizard do this originally?  
How is it different currently?  
Is the progress bar different to the current information bar at the top of the wizard?  
What about slow or no connectivity?  

Does this have any impact on the wizard redesign?

**Comment by sibille** [comment]
Currently the wizard is downloading new content in background and offering refresh when templates are downloaded. 
For the wizard redesign @crutkas asked us to change the progress, as we do not update templates a lot and we want people to work with the latest version. 
Connectivity errors will be handled and current template version or the one delivered with the vsix will be used. 
Progress will be integrated in the information bar at the top of the wizard.

**Comment by crutkas** [comment]
My feedback was to focus this is for the new redesign

**Comment by mrlacey** [comment]
So, is this for the new wizard (v2.0) or the next release of the current wizard (v1.8)? I ask because this is in-progress for 1.8.

**Comment by ralarcon** [comment]
Well, this is for the new redesign, which is work in progress right now.

**Comment by ralarcon** [comment]
Look at the new progress indicator for each stage of the "templates update process":

1) Downloading:
![wts_download](https://user-images.githubusercontent.com/2638875/35815772-96891952-0a99-11e8-89aa-81e7dc1242d6.gif)

2) Extracting templates:
![wts_extracting](https://user-images.githubusercontent.com/2638875/35815774-96d66dc4-0a99-11e8-9a65-bb40301efd5f.gif)

3) Copying templates to the repository and refreshing templates:
![wts_copy_refresh](https://user-images.githubusercontent.com/2638875/35815773-96a5dcd6-0a99-11e8-89ed-b8eb52287cb0.gif)


Comments?

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18040.7
Wizard version: 0.16.18040.2
