### ISSUE TITLE
App go back navigation: Add Alt+LeftArrow support

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1770]
x-ref: #1612 

Alt+LeftArrow behavior using [keyboard accelerators](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators) is available since FCU (Build 16299). 

We need to add this support once the FCU is the minimum version supported by WTS.

**Comment by crutkas** [comment]
Is this how inbox apps go back / official doc guidance?

**Comment by sibille** [comment]
yes, the info is here #1612.

We could not implement this due to the min target version, but can now, adding to 2.3

**Comment by mvegaca** [comment]
#2383 Keyboard accelerators added on CS (CodeBehind, MVVM Basic, MVVVM Light, Caliburn Micro) and VB (CodeBehind, MVVM Basic, MVVVM Light).
Prism is already handling this Keyboard Accelerator.

Prism also handle accelerator for Go Forward, I'm not sure if we have to handle go forward by default generated apps.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18187.1
Wizard version: 0.18.18187.1
