### ISSUE TITLE
Page Navigation - Double Click

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#1774]
I have noticed that the template doesn't check the CurrentSourcePage therefor it is possible to navigate to the same page twice.  This obviously messes up the backstack when using the back button as there are now 2 pages that are the same.

Probably wise to include check on navigation as desktop users sometimes double click on menu items.

Steps to reproduce
1) double click on the menu icon
2) use back button and notice that the same page is in backstack.

Current latest stable version of templatestudio + VS2017

[MultipleBackStack.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/1680888/MultipleBackStack.zip)

**Comment by mrlacey** [comment]
This should not happen. I remember writing the code to stop you navigating to the page that is already top of the stack.

**Comment by mrlacey** [comment]
Affects
- MVVM Light (C# & VB)
- CodeBehind (VB)
- MVVM Basic (VB)

Doesn't affect
- Caliburn Micro
- MVVM Basic (C#)
- CodeBehind (C#)
- Prism

**Comment by mrlacey** [comment]
A fix will be in the next release. In the mean-time, you can correct this behavior by copying the modification shown in the appropriate link below.

[C# with MVVMLight](https://github.com/Microsoft/WindowsTemplateStudio/pull/1776/commits/5405dde47bd43f62fc1620be56a977dfc358da05#diff-51153d6da3c9638139b9ee08b180c537)  
[VB.Net with MVVMLight](https://github.com/Microsoft/WindowsTemplateStudio/pull/1776/commits/934e419a33b58f5777a86285a6b11da930f64f3f#diff-61f2e9ba09eaee69bd0e8ea2a2f0a9cf)  
[VB.Net with MVVMBasic](https://github.com/Microsoft/WindowsTemplateStudio/pull/1776/commits/f9800a7b0aed5ad016a2444d9f30e1bc0082a827#diff-440a62449ae15faa9bd52b819f2723dc)  
[VB.Net with CodeBehind](https://github.com/Microsoft/WindowsTemplateStudio/pull/1776/commits/735338d9c43acac0d2ebbd5733a4cd1495069676#diff-8450261ad2c29f4961e23037396b2cb2)

**Comment by crutkas** [comment]
should we do a hot fix?

**Comment by mrlacey** [comment]
> should we do a hot fix?

Let's pencil in a hotfix for next week. Give a couple more days to see if anything else gets found (especially for the VB stuff - the MVVMLight/C# issue has been there forever)

**Comment by ralarcon** [comment]
I think the same, let's wait at least until next week. Then decide.

**Comment by mrlacey** [comment]
Verified in 
Wizard: 0.16.18035.1
Templates: 0.16.18035.1

keeping open until hotfix

**Comment by sibille** [comment]
Hotfix released:
Wizard: 1.7.18030.1
Templates: 1.7.18037.1
