### ISSUE TITLE
Only Main page shows

### ISSUE THREAD

**Issue by hapzfl** [Microsoft/WindowsTemplateStudio#1786]
## For Bugs:
I was just trying to follow a tutorial. So I selected several different project types (Navigation Pane, Code Behind) and Pages (Settings, Master/Detail, Grid) with VS 2017 and with VS 2017 Preview, all with the same result: 
Only a Main page was there but none of the other selected pages.
### Repro steps
I tried it several times with the sam outcome

### Expected Behavior
Like in the tutorial, I expected to see Settings, a Master Page, a MasterDetail and a Grid Page.
Win 10 Pro b.17025.171020-1626

### Actual Behavior
Only the Main Page is shown.

* **VS Version:**
15.5.5
* **WTS Wizard Version:**

* **WTS Template Version:**
1.7.18030.1

* **Windows Build:**
Win 10 Pro b.17025.171020-1626
[App5.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/1683433/App5.zip)

**Comment by mrlacey** [comment]
In the attached zip there is only the single page in the project.

I wonder if you added all the pages you clicked one.  

To add a page you must first click on the button with the plus sign. At this point, you can change the default name if you wish. You must then click on the tick button (whether you change the name or not) to actually add the page to the list of items to generate. If you only click on the plus sign and not the tick button as well, the page won't be added.

A list of all the pages that will appear in the final project can be seen on the right of the screen.

![image](https://user-images.githubusercontent.com/189547/35650007-b2afec20-06d2-11e8-85a9-0396d0bb13e6.png)

I know this double click requirement can be confusing and frustrating if you're not aware of it.  We're currently working on a redesign of the wizard which should make this easier and/or more obvious in future.

**Comment by hapzfl** [comment]
Ahh, that’s it. The check mark misled me as I assumed that the feature was already selected after I selected the plus sign. Maybe you want to reconsider the UI and leave the box empty until after it is clicked.

 

Thanks for your prompt help!!!

 

Harald

**Comment by mrlacey** [comment]
Glad I could help.
Yes, the new design will remove the need to "double-click."

**Comment by ralarcon** [comment]
@hapzfl, you can now have a flavor of our new design approach by using the nightly release (WARN: only one extension can be active at a time).

Check https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio for installation instructions.

By the way, if you want, you can now review your rating review at [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio#review-details)
