### ISSUE TITLE
Not all VB templates have fully translated descriptions

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1793]
Not all VB templates have the latest description translations.

**This needs to be part of the hotfix too.**

**Comment by crutkas** [comment]
Is this something we can do as part of a unit test with winappsriver

**Comment by mrlacey** [comment]
@crutksas We could have a test for this without needing WinAppDriver but it can't be fully automated without raising false negatives or forcing the VB templates to be updated at the same time as the C# ones. And we don't want to force people to have to make changes for both languages at the same time because that's likely to mean that people are less likely to contribute.

**Comment by mrlacey** [comment]
Thinking about it some more, we could detect where the C# version has a translation but the VB version doesn't. This would highlight anything new with a translation that hasn't been copied to the VB version without ensuring that everything is in perfect sync.

I think will be a suitable compromise. I'll raise a new issue.

**Comment by mrlacey** [comment]
Verified in 
Wizard: 0.16.18035.1
Templates: 0.16.18035.1
