### ISSUE TITLE
CodonFX Framework Support

### ISSUE THREAD

**Issue by DVaughan** [Microsoft/WindowsTemplateStudio#1798]
## Support for Codon Framework

I'd like to see included in the list of MVVM frameworks, my own framework CodonFX.
I'm happy to perform any integration tasks.
* [CodonFX homepage](http://codonfx.com)
* [CodonFX on GitHub](https://github.com/CodonFramework)

**Comment by mrlacey** [comment]
Even if all the integration was done by the project owner, it's not practical for us to support more than the most popular of frameworks.  

Instead, our plan is to eventually allow the support for the templates for other frameworks to be hosted externally and be combined with the ones we provide.  
We're tracking this in Issue #234 and while the idea has been on hold for a while, I'm currently expecting this to become available in the next few months. (Sorry, I can't be more specific yet.)

**Comment by crutkas** [comment]
@DVaughan I am going to close this out unless you are planning to implement this.
