### ISSUE TITLE
Right Click: Exception if going back and forward creating an Image Gallery 

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#1806]
### Repro steps
1. Using right click, Windows Template Studio -> Add new page 
2. Select Image Gallery page and set the name you prefer.
3. In the Change Summary page, move the selected item to any of the image assets.
4. Viewing the image, navigate back
5. Click next aging.
6. An exception is raised.

### Expected Behavior
You can navigate back and next without an exception.

### Actual Behavior
An error avoiding to continue is raised.

Wizard: 1.7.18030.1
Templates: 1.7.18030.1

**Comment by crutkas** [comment]
does this happen on every page or just this?

**Comment by ralarcon** [comment]
Just this page. The issue is related to the image (png) to be loaded and unable to be removed...

**Comment by mrlacey** [comment]
Affects any page that includes an image. This means ImageGallery **& the Map page** as that also includes `map.png`.
UriScheme would also do this if it supported Right-Click> Add Feature.

**Comment by ralarcon** [comment]
@mrlacey you are right

**Comment by mrlacey** [comment]
I've found another, related issue.

If viewing an image on the summary page, go back and select a different page, the previously viewed image will appear on the list of files for the new page.  [Below shows adding a grid page, but that page shouldn't include map.png.]

![image](https://user-images.githubusercontent.com/189547/35857840-43b3dc50-0b32-11e8-96ae-8203edf10964.png)

The spurious image is even included in the generated project.

**Comment by mrlacey** [comment]
pausing my investigation of this until wizard redesign work is merged back into the main (dev) branch to avoid duplication of work.

**Comment by ralarcon** [comment]
@mrlacey, we are about to merge the new design changes to dev branch.  We are finishing the tests over the design branch as the change is really heavy.

**Comment by ralarcon** [comment]
@mrlacey the dev branch has now the new design. Let me know if you want to still investigate this issue just by assigning it to you. If not, we will take care.

**Comment by mvegaca** [comment]
Fixed on #1895.
The problem was that we are cleaning the previous generation result but the Image controls still locking the image on image source.
I've decided to fix it loading the ImageSource with a new DisposableImageSource that does not lock the image file allowing the gen controller to delete it.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18046.3
Wizard version: 0.16.18046.1
