### ISSUE TITLE
Wizard: Localization Review

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1831]
Review string resources from New Wizard. 
- [x] Ensure everything is in resource file
- [x] Spell and grammar check
- [x] Correct comments

**Comment by sibille** [comment]
@mrlacey and @crutkas could you have a look at the [StringRes file](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/code/src/UI/Resources/StringRes.resx) to ensure there are no grammar or spelling errors, before we send it to localization? Thanks!!

**Comment by mrlacey** [comment]
The value for `StatusBarRunFinished` doesn't look right. The message "Creating Windows Template Studio project..." doesn't imply it's finished.

`NotificationSyncError_Refresh` might be clearer as "Error refreshing templates. See output window for more details."

**Comment by sibille** [comment]
Thank for you feedback, the first one is correct, but the title is a bit confusing so I changed the name in this case. It's used in the runfinish method, where the wizard run finishes and generation starts...

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
