### ISSUE TITLE
Why has "Framework" been renamed "design pattern" in the new wizard?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1832]
While "Code Behind" isn't a framework, the other options aren't design patterns.

**Comment by ralarcon** [comment]
Visual Studio team (design) guideline. Internally is still manage as "framework". Not sure if there is any chance to modify based on feedback.

**Comment by mrlacey** [comment]
If "Visual Studio team (design)" are saying change it, they need to explain why!

**Comment by sibille** [comment]
It might have been due to CodeBehind not being a framework. 
Keeping this open to remind me to update the documentation with new screenshots and design pattern instead of framework.

**Comment by mrlacey** [comment]
Code behind isn't a framework, but none of the others are "design patterns." They use the MVVM Design Pattern but that's not a choice.

**Comment by sibille** [comment]
@mrlacey, updated the docs. Can we close this? I think best would be DesignPatterns and Frameworks to make all options fit perfectly, but that's too long.

**Comment by mrlacey** [comment]
ok to clcose.
