### ISSUE TITLE
+ button shown on selected feature after added (new wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1833]
v  0.16.18038

![image](https://user-images.githubusercontent.com/189547/35914194-5099ff4e-0bfa-11e8-86a6-eaeefeed76b5.png)

After adding a feature the (+) button remains shown even though it will no longer do anything when clicked.

**Comment by crutkas** [comment]
agreed

**Comment by mvegaca** [comment]
Fixed on #1855

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
