### ISSUE TITLE
Pages are not displayed in the correct (configured) order [New wizard]

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1834]
In the new wizard, the pages are listed in alphabetical order, rather than the configured order.

new version

![image](https://user-images.githubusercontent.com/189547/35914412-1988ee4c-0bfb-11e8-8153-c2e49a691fd4.png)

old version

![image](https://user-images.githubusercontent.com/189547/35914599-b4cc6938-0bfb-11e8-995a-ffb6899c624a.png)

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
