### ISSUE TITLE
how to manually check for new templates in the new wizard?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1835]
The old version of the wizard had a button to "refresh templates".
![image](https://user-images.githubusercontent.com/189547/35915066-752aa7a2-0bfd-11e8-8ec2-809992328a26.png)

How is this functionality exposed in the new design?

**Comment by ralarcon** [comment]
This has changed. The wizard will check if there is a new version. If so, templates will be downloaded, extracted and refreshed. The UI will be blocked while installing new templates.

**Comment by mrlacey** [comment]
@ralarcon are you saying there will now be no way to manually check because there's a theoretical need to never require this?

Does this also mean that the wizard will always check for new templates when started? (Even if offline or on a very slow connection?)

**Comment by ralarcon** [comment]
Yes. cc/ @crutkas.

The idea is that we only release template updates alone when a hotfix is delivered (very few occasions). The wizard already checks for new templates existence everytime it starts (only if connection available), the only change is that it will block you until the templates are downloaded and ready to use.

**Comment by mrlacey** [comment]
@ralarcon Where is the spec for the logic of checking for / loading new templates? I can't find it in an issue.

Even without looking at the code, there appear to be some big issues. Such as, if you're on a slow network connection VS will freeze when opening the wizard until the response returns!!!!

**Comment by mrlacey** [comment]
What are the chances this is related?

![image](https://user-images.githubusercontent.com/189547/35926214-8c658fc8-0c1f-11e8-8654-b3b325f2a7ff.png)

**Comment by crutkas** [comment]
This should all be in the wizard.  it should initially check a small file on our CDN.  if there is a newer version, then download then extract.

**Comment by mrlacey** [comment]
If the intention is that the wizard always checks for new versions when it starts,  there are some implementation issues:
- The wizard makes a synchronous/blocking call to get the file listing latest versions. This leaves the UI totally unresponsive if the request takes time (such as if there is a slow connection.)
- Ignoring the blocking of the UI, the wizard makes no indication that it's making a request and that it may take some time.
- There is no way to cancel this request (if it is taking time.)
- The requesting of the JSON file over the web does not use appropriate HTTP Headers and response codes to minimize unnecessary traffic and the repeated transmission of the same file. While the file is currently only ~1.4K it is growing with every release but it is requested many thousands of times (across all users.)

**Comment by ralarcon** [comment]
Hey @mrlacey,

Regarding the message about unresponsiveness, did you made any special action (reduce bandwidth, block the call using a proxy,...) before you get it? Did the message point you to any log?  

Then, I need some clarifications to improve the experience
> The wizard makes a synchronous/blocking call to get the file listing latest versions. This leaves the UI totally unresponsive if the request takes time (such as if there is a slow connection.)

Not sure if this is an assumption or something you have experience, but the UI should not be blocked. If so, please fill a bug.

> Ignoring the blocking of the UI, the wizard makes no indication that it's making a request and that it may take some time.

We have tested the download and it was really quick. We can provide feedback when checking for new versions. If it is quick the message will not be shown. 

> There is no way to cancel this request (if it is taking time.)

We will leave the "Cancel" button available to allow users cancel the request if takes so long. Another option is to avoid the config download in poor network conditions (we can try to figure it out).

> The requesting of the JSON file over the web does not use appropriate HTTP Headers and response codes to minimize unnecessary traffic and the repeated transmission of the same file. While the file is currently only ~1.4K it is growing with every release but it is requested many thousands of times (across all users.)

In production, the size is around 800 bytes. It is true we are not adding specific headers to the file in the blob container and we can do data. I guess you mention the Cache-Control header. If not wrong, the real CDN in production https://wts2.azureedge.net/config.json is adding caching features but it is true we are not adding this explicitly. We can do it as well.

We are going to review the issues marked by @mrlacey in the way I mentioned. If there is something that is not good for you, let us know.

**Comment by sibille** [comment]
closing this in favor of #1858
