### ISSUE TITLE
"About" info is placed weirdly in new wizard

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1836]
The About info seems to be grouped with the project details in the summary section

![image](https://user-images.githubusercontent.com/189547/35914952-0cef74ba-0bfd-11e8-8786-81bc95194070.png)

If it was moved to the bottom of the screen the separation would break the association.

![image](https://user-images.githubusercontent.com/189547/35915106-9cebd810-0bfd-11e8-8a8e-4304a0b331fb.png)

However, the gap is lost when the view is made smaller or more pages or features are added.

This information about WTS should always be clearly separate from details of the solution that will be generated.

**Comment by ralarcon** [comment]
We can consider it. Initially, we added at this level to avoid to deal with scroll issues when adding several pages

**Comment by crutkas** [comment]
Thought we chatted about putting this on the left side.  I think we can really tighten this up as well size wise

**Comment by ralarcon** [comment]
Nop, design guys told us to put it on the right side below licenses.

**Comment by sibille** [comment]
Reviewed with design team, about is in the correct position.
