### ISSUE TITLE
Inconsistent alignment and spacing in details page (new wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1838]
![image](https://user-images.githubusercontent.com/189547/35915696-c6f027cc-0bff-11e8-8451-e8743cc3e66b.png)

rough mockup of alternate positioning.

![image](https://user-images.githubusercontent.com/189547/35915769-02362174-0c00-11e8-8c06-64f979703b02.png)

multiple licenses could be put over multiple lines and the space between dependencies increased as necessary  
OR  
multiple licenses and dependencies could be placed on the same line, but with a comma as separator.

**Comment by sibille** [comment]
@mvegaca, could you review the designs here (icon alignment and gap size) and adjust license and dependencies position

**Comment by mvegaca** [comment]
Fixed on #1868

I've redesign TemplateInfoPage.

![image](https://user-images.githubusercontent.com/5556784/36024336-c266c95e-0d8f-11e8-9244-44432e366279.png)

Screenshot with photoshop rules.

**Comment by mrlacey** [comment]
I'd also like to see increased spacing directly below the description.

Do all translations of "Dependencies" (or other label) fit in the space allocated?

**Comment by mvegaca** [comment]
Updated on #1870

![image](https://user-images.githubusercontent.com/5556784/36028831-de529a56-0da0-11e8-99ba-487210dab731.png)

**Comment by crutkas** [comment]
Dependencies can be made much tighter here for line height.  i think the margin different makes it look too much like a different grouping versus together in dependencies.

**Comment by mvegaca** [comment]
Updated on #1880. Now all text in "<- back" button is clickable.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18046.3
Wizard version: 0.16.18046.1
