### ISSUE TITLE
Increase size of hit area for details back button in new wizard

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1839]
In the new wizard, the cursor must be directly over either the arrow or the text when clicked to trigger the back navigation.
Even clicking in the space between the arrow and text does nothing.

Instead, clicking anywhere (approximately) in the area indicated by the red box in the image below should trigger back navigation.

Do this because it makes it easier to trigger the navigation when that is the intent of the user.
There is no way that clicking in this area is meant to do anything else.
Keeping the current behavior makes it easy to not trigger navigation when clicking very close to the text but not actually on it.

![image](https://user-images.githubusercontent.com/189547/35915909-96c6c85c-0c00-11e8-803f-046abd6f41c3.png)

**Comment by ralarcon** [comment]
Agree this need to be improved.

**Comment by mvegaca** [comment]
Fixed #1894

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18046.3
Wizard version: 0.16.18046.1
