### ISSUE TITLE
Distinguish between different types of link on the item detail page (new wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1840]
The item detail page shows links with very different actions but they are styled the same. People should never be left wondering what will happen when they click on a link. Nor should they be surprised by what it does. (Which can easily happen when the behavior is different to past similar actions.)

![image](https://user-images.githubusercontent.com/189547/35916436-50bdaf86-0c02-11e8-8aae-51825975db3b.png)

As the blue underlined link was used for the "details" that were clicked on to get to this page, this can continue to be used for internal navigation links.  
An indication that the license link will open in a browser should be displayed. I'd also like to see the URI that will be navigated to shown somewhere.

Based on conventions elsewhere.
- Add text next to external links saying "Opens in browser"
- When the cursor is over such a link or it has focus, a tooltip should show the URI.

**Comment by sibille** [comment]
Suggestion from design team:

Add tool tips on rollover. There is no visual differentiation between navigational links. However, alt tag/tool tip are as follows:
•	Open Microsoft Store Service SDK in a new browser tab
•	Settings
•	Settings storage

I think this will help to differentiate internal vs external links

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18047.5
Wizard version: 0.16.18047.2
