### ISSUE TITLE
Increase size of the hit target for "details" in the new wizard

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1841]
As with #1839, increase the size of the hit target for the "details" text on an item in the wizard.
The precision needed to click this text is such that it is very easy to accidentally click on the control behind the text and accidentally select the item, rather than cause the details to be displayed.

![image](https://user-images.githubusercontent.com/189547/35916784-84bc98aa-0c03-11e8-8e46-c683f2dc5c09.png)

The red box is an approximation of the size of the needed area.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18046.3
Wizard version: 0.16.18046.1
