### ISSUE TITLE
Incorrect framework description being shown

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1842]
The longer description for each framework appears to be being shown, rather than the shorter version which is intended for this use and does not contain unused formatting.

new version 

![image](https://user-images.githubusercontent.com/189547/35917270-6b974dc8-0c05-11e8-833c-36986eba881f.png)

old version 

![image](https://user-images.githubusercontent.com/189547/35917203-27b7e234-0c05-11e8-85ed-3c1a6441f739.png)

**Comment by mvegaca** [comment]
Fixed on #1851

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
