### ISSUE TITLE
Feature icon alignment in summary area (new wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1844]
Feature icons in the summary area are left aligned but centrally aligned in the main item entry.

![image](https://user-images.githubusercontent.com/189547/35925569-f7d0a880-0c1d-11e8-8bb6-cc841e1eafee.png)

The variation in widths of feature icons makes the difference stand out and causes the appearance of misalignment. In turn, this visual discrepancy unnecessarily draws attention to the area.

Does not affect pages as their icons all have a more consistent width.

**Comment by sibille** [comment]
@mvegaca, reviewed designs, icons in project summary should be centrally aligned

**Comment by mvegaca** [comment]
Fixed #1867

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
