### ISSUE TITLE
License not removed from summary in new wizard when no longer needed

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1845]
**REPRO**

- > New project
- Navigation Pane
- Code Behind
- Add 'Settings Storage' Feature

note that a license for 'Newtonsoft.Json' has been added due to inclusion from 'Settings Storage'

Now remove the 'Settings Storage' feature

![image](https://user-images.githubusercontent.com/189547/35925938-e84c7aa0-0c1e-11e8-827a-443709818fa7.png)

Indication of license still remains in summary

![image](https://user-images.githubusercontent.com/189547/35926011-0f1a41bc-0c1f-11e8-98e3-58f965b805ea.png)

**Comment by mvegaca** [comment]
Nice catch! Fixed on #1856
