### ISSUE TITLE
Multiple page indication reset when a page removed (new wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1846]
Add multiple instances of a page and see indication of multiple pages added

![image](https://user-images.githubusercontent.com/189547/35926435-0d4f5538-0c20-11e8-8d5c-b31db5a76f53.png)

remove just one of the newly added pages

![image](https://user-images.githubusercontent.com/189547/35926615-7afc0130-0c20-11e8-9fc2-b4c16e377d3e.png)

There are now two (2) pages but only one is indicated

![image](https://user-images.githubusercontent.com/189547/35926743-c9214bb8-0c20-11e8-8de2-3883e4f83df6.png)

**Comment by mvegaca** [comment]
It could be fixed with #1862 but I'm not sure. Could you check on next nightly @mrlacey ?

**Comment by mrlacey** [comment]
adding myself as a reminder to retest

**Comment by mrlacey** [comment]
verified fixed in 
Templates version: 0.16.18040.4
Wizard version: 0.16.18040.1
