### ISSUE TITLE
Page incorrectly highlighted after deleting page with duplicate name (new wizard)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1848]
- Add two camera pages
- change second to have the same name as first camera page
- see error indicated and item highlighted

![image](https://user-images.githubusercontent.com/189547/35932905-fca8e92c-0c30-11e8-9552-60325d136249.png)

- Remove the second page

![image](https://user-images.githubusercontent.com/189547/35932944-132f6676-0c31-11e8-869d-f708cc772784.png)

- warning about name already existing is dismissed but first camera page has the error highlighting

![image](https://user-images.githubusercontent.com/189547/35933005-3871d1a8-0c31-11e8-9108-8681926ea827.png)

**Comment by mvegaca** [comment]
Fixed on #1853

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
