### ISSUE TITLE
Settings Page Listed followed by menu items

### ISSUE THREAD

**Issue by BALAGANENGINEERING** [Microsoft/WindowsTemplateStudio#1850]
### Expected Behavior

I Dislike This Placement of Settings Page (Options Item)

![screenshot 11](https://user-images.githubusercontent.com/19682495/35959624-6aacb516-0ccc-11e8-8464-29f201c68b16.png)

No Provision to Make Like this Copyright info in Hamburger menu
Like this
![microsoft copyright](https://user-images.githubusercontent.com/19682495/35959557-1fe12b0c-0ccc-11e8-8cb6-2626b3dcf31b.png)

#

**Comment by ralarcon** [comment]
Please, check #1763 where you can find the reason as well as a workaround.

**Comment by mrlacey** [comment]
@BALAGANENGINEERING in terms of adding copyright information at the bottom of the Hamburger menu, you could switch to use the `NavigationView` and set the `PaneFooter` to hold this information.  
However, doing so will require a minimum SDK version of the **Fall** Creators Update, but the code that WTS produces targets the Creators Update and so can't do this.
