### ISSUE TITLE
Workflow control does not draw tick icon with environment font family modified

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1852]
I've set Arial 15 Font to Environment in Visual Studio and run WTS.

All texts are increased but sequential flow stop drawing the tick icons.

![image](https://user-images.githubusercontent.com/5556784/35967416-1dfd7e86-0cc1-11e8-8a5b-217295534233.png)

![image](https://user-images.githubusercontent.com/5556784/35967455-3bcec97e-0cc1-11e8-8fca-aa102dc0cb81.png)

**Comment by mvegaca** [comment]
Fixed on #1875

**Comment by mvegaca** [comment]
Updated on #1888

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18045.1
Wizard version: 0.16.18045.1
