### ISSUE TITLE
Translations missing for Prism description file

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1854]
Localized versions of [Prism.md](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/_catalog/frameworks/Prism.md) still contain the English versions of the text. 

Translation required.

**Comment by sibille** [comment]
Good catch!!
We'll have to look into the localization tool why this file was not sent in the last localization round.

**Comment by crutkas** [comment]
how can we validate this somehow?  can we do a test that throws an warning when we have localized files that 100% match another file?

**Comment by mrlacey** [comment]
@crutkas We can add the test but it means that whenever we add anything new, we'll get have a failing test until we have the translation(s). 
I think a pre-release check (or tests that only run at this point) might be more appropriate. Of course, if we find anything at this point it either won't get fixed or will delay a release.

**Comment by crutkas** [comment]
Agreed.  Added this as a thought so we can catch stuff like this. I love the prerelease idea. 

Also another idea could be we do that check every few builds and create a running list for stuff we need to translate

**Comment by mrlacey** [comment]
I'm adding something for this as a "manual-only" check as part of #1869 ;)

**Comment by dgomezc** [comment]
The Prism .md files have been sent to be located

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.17.18074.2
Wizard version: 0.17.18074.2
