### ISSUE TITLE
Delete /Remove an WTS Page in Solution, not Updates an ShellPage.xaml.cs, App.xaml.cs 

### ISSUE THREAD

**Issue by BALAGANENGINEERING** [Microsoft/WindowsTemplateStudio#1857]
## For Bugs:

What really happened
![screenshot 13](https://user-images.githubusercontent.com/19682495/35971044-7f9ebf34-0cf2-11e8-865b-f60a220b4389.png)
For Some Reason I Removed  2 Pages From Solution, 
I Delete all References Related to that pages which I created.

But Build Error Shows  Windows Template Studio Produced References Are Not Removed Automatically. #

**Comment by mrlacey** [comment]
When you generate a project with WTS, depending on the options chosen, references to added pages will be included elsewhere in the code.

If you delete or remove a page, Visual Studio (Not WTS as WTS is only used to generate the project) is not capable of removing all references to that page. You'll need to remove such references yourself. Fortunately, the error window will show where the references are as they will cause errors.

It looks like you generated a project with a Navigation Pane and CodeBehind.

App.xaml.cs gets a reference to MainPage as that's the page it opens by default. If you remove "MainPage" then you'll need to modify App.xaml.cs to open a different page when the app is launched.

ShellPage.xaml.cs includes references to each page (so it can launch them when the corresponding menu item is chosen.)  These entries must also be removed (or changed) if the related pages are removed from the project.

The behavior you are experiencing is as expected.
