### ISSUE TITLE
Visual Studio freezes while checking for new templates on wizard launch

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1858]
Follow on from #1835 

When the wizard is launched, it checks for new versions of templates by making a synchronous/blocking call.

If the request takes time (e.g. slow network connection) then a blank version of the wizard window is displayed.

![image](https://user-images.githubusercontent.com/189547/35971865-7ccc34e2-0cc7-11e8-8a2e-2cc7d3538ae3.png)

Trying clicking around on the screen or doing anything and you may get this.

![image](https://user-images.githubusercontent.com/189547/35971723-031d7728-0cc7-11e8-93e7-94eeb8f2bc9c.png)

If delayed, once data is finally returned the wizard will display correctly but VS may display a warning.

![image](https://user-images.githubusercontent.com/189547/35971828-60743ec0-0cc7-11e8-9b7c-7cebc3f2d655.png)

For testing/debugging, you can force a delay with Fiddler.
Add the following to `OnBeforeRequest` in the FiddlerScript

```
if (oSession.uriContains("wtsrepository.blob.core.windows.net"))
{
    oSession["response-trickle-delay"] = "30000";
}
```

**Comment by sibille** [comment]
I'm looking at this to download the file asynchronously and display a message for slow connections.

**Comment by sibille** [comment]
During the investigation we discovered another issue with template synchronization:

The download of new packages is not truly cancelled when cancelling, if you open the wizard twice in little time the experience is confusing as it starts another download and reports progress on both of them.

The same thing happens with template extraction and copying. 

We should support true cancellation when cancelling during download. 
No cancelling should be available during extraction and copy process.

**Comment by crutkas** [comment]
sounds like this is affecting production, correct?
is this a hot fix?

**Comment by sibille** [comment]
No, that change was introduced in the Wizard redesign. There should be no issue in production, but I'll double check.

**Comment by mrlacey** [comment]
Do analytics give us anything that tells us if people might be encountering this in real use?
This would be a hot-fix for the wizard (full new vsix release) and based on the current state of refactoring could be a lot of work and an unwelcome interruption if we don't _have_ to do it.

**Comment by mrlacey** [comment]
comment overlap!

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.16.18047.5
Wizard version: 0.16.18047.2
