### ISSUE TITLE
Generated projects to not include localization of app title

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1859]
Generated projects include localized resources for all strings apart from the display name of the generated project. 

The display name is hardcoded in the appxmanifest, rather than using a resource.

Docs https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#refer-to-a-string-resource-identifier-from-your-app-package-manifest

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.18.18110.2
Wizard version: 0.18.18110.2
