### ISSUE TITLE
Page licenses aren't shown on "New Page" wizard

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1860]
Adding the Grid page requires accepting a License for the Telerik UI controls but this is not listed.

![image](https://user-images.githubusercontent.com/189547/35973483-8332287c-0ccd-11e8-9669-71a0d6020bd0.png)

If the page has a dependency with a license, that is shown.

![image](https://user-images.githubusercontent.com/189547/35973552-cb17785e-0ccd-11e8-8f36-1b905074e264.png)

**Comment by mvegaca** [comment]
It was fixed on #1856

**Comment by sibille** [comment]
Verified in dev-nightly
Templates version: 0.16.18043.1
Wizard version: 0.16.18043.1
