### ISSUE TITLE
New feature wizard indicates naming error after changing item

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1861]
On Add Feature page

- select background task
- delete pre-populated name
- click on other feature item

- error message and name highlighting are still displayed but should be dismissed.

![image](https://user-images.githubusercontent.com/189547/35973863-e3e28e36-0cce-11e8-9a5d-026c70eebb5e.png)

**Comment by mvegaca** [comment]
Fixed on #1866
