### ISSUE TITLE
Delete button is not visible when editing item text and is not accessible with tab

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1876]
Delete button is not visible when editing item text. 
The button is not accessible with tab due to this behaviour. 

Tab 1
![image](https://user-images.githubusercontent.com/24698018/36091019-a9782f14-0fe2-11e8-813d-0b9b8dac2b17.png)

Tab 2
![image](https://user-images.githubusercontent.com/24698018/36091092-e9038a2a-0fe2-11e8-931f-f67497803e1d.png)

**Comment by dgomezc** [comment]
Currently a user page can be deleted using supr key, but we believe that is important for accessibility that the button can be accessed by keyboard navigation and can be activated using the enter key. 

Accessing the button with keyboard navigation would look like this:
<img width="175" alt="sin titulo" src="https://user-images.githubusercontent.com/12777039/36416806-791112de-162a-11e8-87b8-45f7fbb15755.png">

**Comment by ralarcon** [comment]
I like it. I think it is perfect and understandable.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.17.18052.1
Wizard version: 0.17.18052.1
