### ISSUE TITLE
 UI unresponsiveness message in VS 15.6 Preview 5 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1884]
1) Create project
2) Add any page or feature that requires to restore a nuget package via right click
3) During package restore try to access UI

-> following message is shown
![image](https://user-images.githubusercontent.com/24698018/36150170-15036cae-10c3-11e8-9324-4c32d64445e5.png)

**Comment by sibille** [comment]
This is still happening and not only related to nuget package restore

**Comment by sibille** [comment]
This is caused by calls to VS Shell for Restore Packages, Add items to projects..  

Added JoinableTaskCreationOption LongRunning as this should avoid the hang report to be fired (https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.joinabletaskcreationoptions?view=visualstudiosdk-2017), but it's still showing the same message.

**Comment by sibille** [comment]
UI Thread is not unresponsive, but blocked until generation finishes, which is the desired behaviour to ensure the user is not presented with an uncomplete project. VS Team is working on this.

**Comment by crutkas** [comment]
Is this still an issue?

**Comment by sibille** [comment]
No, was fixed in VS 15.7, this message should no longer appear. I'll close this.
