### ISSUE TITLE
Dark Theme color support

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1903]
Card Footer text should be lighter

![image](https://user-images.githubusercontent.com/5556784/36266375-93989c88-1271-11e8-8ade-3e5b44d073a0.png)

**Comment by mvegaca** [comment]
Right click code Viewer is not applying dark theme.

![image](https://user-images.githubusercontent.com/5556784/36266898-f4997614-1272-11e8-980e-29badd9a5d5e.png)

**Comment by mvegaca** [comment]
Monaco Editor Support 3 themes
- vs
 - vs-dark
- hc-black

We should detect the selected theme and set vs-dark to DarkTheme or vs to Light and Blue themes.
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#theme

**Comment by crutkas** [comment]
may want to track individual issues at a point else this could be come a never ending bug

**Comment by sibille** [comment]
Solved the monaco part.
The rest is about adjusting colors for dark theme, I think they can stay together as it is the same issue (changing dark color adjustments)

**Comment by mvegaca** [comment]
Working on a [separated branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue1903-colors)

Updated CardFooterText Color (Using same values as CardDescriptionText color)
 - Light #717171
 - Dark #999999
 - Blue #717171
 - Hight Contrast GrayText/None

Old
![image](https://user-images.githubusercontent.com/5556784/36732190-4dffe8d8-1bcd-11e8-9017-61a24c07d9ae.png)

New
![image](https://user-images.githubusercontent.com/5556784/36732200-554b17b6-1bcd-11e8-954c-484abaab315d.png)

**Comment by mvegaca** [comment]
These are the updated colors in Dark Theme on WTS Color Category.

Windows Template Studio Color | Dark Theme Value
-- | --
CardFooterText | FF999999
ChangesSummaryDetailFileHeaderBackground | FF2D2D30

- CardFootertext is used on template added count on the Added label.
- ChangesSummaryDetailFileHeaderBackground is used on right click changes summary page on file header background.

ScreenShots on Dark Theme mode:

![image](https://user-images.githubusercontent.com/5556784/36793221-20bda808-1c9d-11e8-8652-02338eafa39c.png)

![image](https://user-images.githubusercontent.com/5556784/36793253-362f8512-1c9d-11e8-8670-aba74101100d.png)

**Comment by mvegaca** [comment]
Fixed
Templates version: 0.17.18060.3
Wizard version: 0.17.18060.3
