### ISSUE TITLE
Ubuntu NFS client functionality not working

### ISSUE THREAD

**Issue by cjbryant-github** [Microsoft/WindowsTemplateStudio#1905]
## For new Features:

* **Overview:** What you'd think should be added with scenarios
* **Links:**

### Repro steps:  The following steps I used to grab the latest NFS client and <mount> command code:
Note: First enter:
1) sudo apt-get update
2) sudo apt-get upgrade

Note: To the latest available packages, enter:
sudo apt-cache search <keyword> (i.e. nfs)

3) sudo apt-get install nfs-common (NFS support files common to client and server)
4) sudo apt-get install libnfs8 (NFS client library)
5) sudo apt-get install nfs4-acl-tools (Cmd line and GUI ACL utlities for NFSv4 client)
6) sudo apt-get install liblockfile1 (NFS-safe locking library)
** optional: 7) sudo apt-get install nfs-kernel-server (Support for NFS kernel server)
8) sudo apt-get install libfile-nfslock-perl (NFS locking pkg)
9) sudo apt-get install rpcbind

10) <sudo apt-get install mount>
11) <sudo apt-get upgrade mount>

What did you do? How can someone else reproduce this?

### Expected Behavior: Expected behavior is to have the NFS client succesfully connect to an 
Server resource.  In this case, I used the mount.nfs command which is called by <mount>.

(include screenshots if a visual issue)

### Actual Behavior:  The actual behavior is a mount failure to a working NFS Server for one of its NFS exported resource being exported correctly.

![ubuntu_screen_shot_win_10](https://user-images.githubusercontent.com/26305978/36266905-acd28d48-1240-11e8-8922-cb3d4732a245.jpg)

## System

* **VS Version:**
* **WTS Wizard Version:**
* **WTS Template Version:**
* **Windows Build:**  Latest Windows 10 Insider Program driver from week of Feb 12, 2018.

**Comment by crutkas** [comment]
Use the Windows Feedback Hub built into Windows 10 to report this.

**Comment by cjbryant-github** [comment]
Hi Crutkas,
      My apologies, but I need my entire post above removed.  I did not realize it would be public in GitHub.  Thank you very much for your help!

~Charlie B.
