### ISSUE TITLE
Settings storage is showing extra border when added before Suspend And Resume

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1908]
1) Create new project
2) Add Setting Storage
3) Add Suspend and Resume (depends on settings storage)

-> Border is drawn around Settings Storage as if there were two. 
-> When removing both, Setting Storage still shows as added

![image](https://user-images.githubusercontent.com/24698018/36297965-d48074e4-12f5-11e8-92ce-98adcc4dfcd1.png)

**Comment by mvegaca** [comment]
#1912

**Comment by mvegaca** [comment]
Check fixed on
Templates version: 0.16.18047.5
Wizard version: 0.16.18047.2
