### ISSUE TITLE
Update MVVMLight version

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1918]
The current stable release is 5.4.1 but we're still shipping 5.3.0

The project has also moved its license file (as no longer on codeplex - http://www.galasoft.ch/license_MIT.txt) which we should update in the template config.

The latest version of the code also has a namespace change in a dependency that will require changing. (from `Microsoft.Practices.ServiceLocation` to `CommonServiceLocator`)

**Comment by mrlacey** [comment]
I have [a fix for this in a branch](https://github.com/mrlacey/WindowsTemplateStudio/tree/Issue1918-UpdateMvvmLight) but it causes some of the RightClickLegacy tests to fail.
This raises an important question.

**How should we handle breaking changes in 3rd party libraries and frameworks?**

Here's what's happened with regard to this specific issue.

A namespace has changed.
By updating the templates the code we generate uses the new namespace.
There are now two possibilities when it comes to updating an app that was produced previously.

App built with v1.x templates. 
-  If the developer doesn't manually update the nuget reference and make the appropriate namespace changes, adding a page or feature with the v2.0 templates will fail.
- If the developer does make the appropriate changes then adding a page or feature with the v2.0 templates will succeed.



Here are some options about what we could do
1. Ignore it (at least for now.) We don't _have_ to update the version of MVVMLight we reference for v2.0 but this will come up in the future. We can't ignore it forever though.
2. Add the ability to detect which version of the library they are using and use different templates accordingly. (This could get very complicated in the future as more dependencies introduce breaking changes.)
3. Allow it to break. It is, after all, a "breaking change." We can still provide documentation and links on what's changed, why, and what to do about it.
4. Allow it to break for now, but if a lot of people complain then look to do something with multiple templates and detection.
5. Something else? (I'm open to suggestions.)

I think we have to go with option 3. 
- Doing anything else has the potential to get very complicated.
- We don't want to have to support multiple versions of the same thing.
- We don't want to discourage people from updating dependencies. Especially as they may include bug/security fixes.
- Adapting to changes in 3rd party libraries are a part of modern software development. As a large proportion of the users of WTS are developers with limited experience we shouldn't try to hide this fact. Instead, we should be honest about it and help them make the necessary changes. 
- It allows us to establish a clear guideline about backward support with WTS projects and breaking changes. Something like this:

**Our templates are designed to work with the latest versions of 3rd party libraries. If a 3rd party has introduced breaking changes, previously generated projects may need to be updated before adding new pages or features.** 


If we do adopt this approach we need to consider the following:
- How do we communicate that we're now referencing a version of something which has breaking changes from the past version? Can it just go in release notes or should we do something else as well?
- Should we update the right-click error messages for failures due to this to be more specific and indicate how a workaround may be possible? (When we know there's a possibly related breaking change issue.)
- How should we change the legacy tests for anything related to the breaking change? (We don't want them to fail indefinitely. Nor should they be disabled.) If left unchanged, they will fail the Full test pass after a PR for this change is accepted.


Something like this was always going to happen. That's why we have the RightClick/Legacy tests.

**Comment by mrlacey** [comment]
> How do we communicate that we're now referencing a version of something which has breaking changes from the past version? Can it just go in release notes or should we do something else as well?

I think something in the release notes should be enough.

> Should we update the right-click error messages for failures due to this to be more specific and indicate how a workaround may be possible? (When we know there's a possibly related breaking change issue.)

How we do this will come down to how specific we want to get. 
For the sake of simplicity, I think we should just add a link to a new "Known issues with adding to an existing project" file in /docs. This could detail all known issues with adding to an existing project due to changes in 3rd party libraries. The release notes could also link to this.

> How should we change the legacy tests for anything related to the breaking change? (We don't want them to fail indefinitely. Nor should they be disabled.) If left unchanged, they will fail the Full test pass after a PR for this change is accepted.

As the tests are only designed to test the right-click functionality with the previous template version, I think it will be acceptable to modify the test to ignore things where we know there's an issue. When adding an exclusion, a new issue should be added to track removing the exclusion when we get to the subsequent release.

**Comment by sibille** [comment]
I think option 3 is the best, as you said we want to encourage people to use the last version of dependencies. Also it could happen, that somebody creates a MVVMLight project, updates the nuget and wants to add pages via WTS. That would fail if we do not update. 
Right click is designed to handle merge failures, if a merge fails it should show why the merge fails and what it was trying to add where (to allow the user to include this code manually). This error message was lost in the new wizard (#1933), we're fixing it. 
I had a look at your branch and there are currently no merge failures, the right click works fine, but the compilation fails afterwards if you do not update the nuget because of the namespace changes. 
We could force merge to fail by adding in more context (modify for example the ShellViewModel postaction files and add in the new using) and make the dependency explicit. We could add in a csproj_postaction too, that updates your mvvmlight dependency when adding a new item. 
This would help to make the change more explicit, but it won't fix pages that were already added.

Legacy tests are prepared to accept a series of templates to be excluded, this has happened before with the webview I think. It's a good idea to open an issue to reinclude them on the next release.

**Comment by mrlacey** [comment]
Note to self. Need to update MVVMLight related docs.

**Comment by mrlacey** [comment]
I've added a [wiki page](https://github.com/Microsoft/WindowsTemplateStudio/wiki/3rd-party-libraries---updates-and-breaking-changes) to document how we'll treat [breaking] changes in referenced libraries. I felt this should be somewhere more permanent than just in a comment (above) in this issue.

**Comment by mrlacey** [comment]
> Need to update MVVMLight related docs.

Nothing in docs to change. Affected namespaces not mentioned.

**Comment by mrlacey** [comment]
Added 'DO FOR LAUNCH' label as reminder that release notes need details that this update includes a potentially breaking change and should link to blog.galasoft.ch/posts/2018/02/publishing-mvvmlight-v5-4-1-with-net-standard-support/

**Comment by sibille** [comment]
Good point having this in wiki and release notes.
I'll add a link to the wiki on the [more info](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/newitem.md) page from right click too

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.17.18058.4
Wizard version: 0.17.18058.1

**Comment by sibille** [comment]
Reopening as this has DO FOR LAUNCH actions

**Comment by mrlacey** [comment]
Removing my assignment because the remaining (DO FOR LAUNCH) action is on whoever prepares the release notes.

**Comment by sibille** [comment]
Release notes prepared
