### ISSUE TITLE
Why added a dependency on sqlsysclrtypes?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1922]
The latest nightly installer has added a new dependency.  
Why is this now being included, especially as the tool does nothing with SQL Server? (as that's what the dependency relates to.)

![image](https://user-images.githubusercontent.com/189547/36353540-94b23ce6-14bf-11e8-89fb-b9096c6c8d76.png)

**Comment by sibille** [comment]
We did not update dependencies nor prerequisits.
![image](https://user-images.githubusercontent.com/24698018/36372584-bf5149c8-1565-11e8-8bdb-dbc399674951.png)
![image](https://user-images.githubusercontent.com/24698018/36372604-ce1c51d2-1565-11e8-9bea-42c81773259b.png)

This must be something internal of the VSIX installer or a dependency of a dependency.

**Comment by mrlacey** [comment]
Have seen other extensions trigger this install too. Assuming it's not anything WTS is doing.
