### ISSUE TITLE
Update description of SettingsStorage feature

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1923]
![image](https://user-images.githubusercontent.com/189547/36353688-6800af96-14c1-11e8-94b6-70ff7aaf4b91.png)

The details of the different storage locations seem out of place and like they were copied from the documentation. (oh, it was.) Their inclusion isn't connected to the opening text and it's not clear why it's there. There's also no explanation about how they're related to the helper class.   
I'd also argue that they're not a list of types of data but rather the locations data can be stored.

**Comment by sibille** [comment]
@mrlacey, the objective here was to give an introduction on what's setting storage and link to documentation for further details. We can include more info about the helper class generated. Do you have a proposal?

**Comment by mrlacey** [comment]
I suggest changing it to something simpler. Such as:

> Settings Storage provides extension methods that make working with application data simpler. It handles loading, saving, and serializing both files and individual pieces of data in any of the application folders.
> 
> To find out more about application data storage, head to [docs.microsoft.com](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata).

**Comment by sibille** [comment]
I like the text but I think we should update this on 2.1. It's not high priority and we just sent the content to localization.
