### ISSUE TITLE
New feature invalid name error state not handled correctly

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1924]
### Repro steps

- Add Feature
- Select Background Task
- Change name to something invalid (blank or reserved name)
- Select another item

![image](https://user-images.githubusercontent.com/189547/36354026-1b0e281c-14c6-11e8-8214-1b6482ad4b2f.png)

### Expected Behavior

- The error state should be cleared

### Actual Behavior

- The error indication remains but it shouldn't
- 'Next' and 'Create' buttons are also disabled

## System

nightly v 0.16.18049.1

**Comment by mvegaca** [comment]
Fixed on #1934

**Comment by mvegaca** [comment]
Check fixed on
Templates version: 0.17.18051.1
Wizard version: 0.17.18051.1
