### ISSUE TITLE
Can still change step even when buttons are disabled

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1925]
- Add Feature to existing project
- Select Background Task
- Change name to something invalid (blank or reserved)
- Tap/click on 'Changes summary'

- Advances to next step but shouldn't

![image](https://user-images.githubusercontent.com/189547/36354072-b2407a6e-14c6-11e8-9e2e-023e3674af54.png)

- Error message is displayed and 'Back', 'Next' and 'Create' buttons are disabled so shouldn't be able to change to the summary step.

**Comment by mvegaca** [comment]
Fixed on #1932

**Comment by mvegaca** [comment]
Check fixed on
Templates version: 0.17.18051.1
Wizard version: 0.17.18051.1
