### ISSUE TITLE
Improve vague description in link tooltips

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1926]
![image](https://user-images.githubusercontent.com/189547/36354211-a432af80-14c8-11e8-9249-294f994c7934.png)

In the above, the 'docs.microsoft.com' in the tooltip is vague.

Either use a simple generic message

> 'Opens on your browser'

Or a more specific message which indicates that they will be taken to the page with the relevant details, rather than just the root of the site. (Preferred)

> 'Opens https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata in your browser'

**Comment by sibille** [comment]
@mrlacey: I think we should use the generic message: "Open in a new browser tab" to differentiate external links (without duplicating link text)

**Comment by mrlacey** [comment]
@sibille ok. 
I still like to see where a link will go before I click on it, not just the domain it's on or what will open it, but understand this is more work.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.17.18051.1
Wizard version: 0.17.18051.1
