### ISSUE TITLE
Inconsistent backspace button behavior on details page

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1927]
On the details page, the backspace key will trigger the back functionality only when the focus is on an item on the page. It does not work when focus is on the form as a whole (the default when getting to the details page) or on the close ('x') button.

The consequence of the current behavior is that pressing the backspace key provides inconsistent, unpredictable (unless you spend a lot of time working out why) behavior.

**Comment by sibille** [comment]
I think we can give consistency here by going back always when backspace is hit on detail page.

**Comment by mvegaca** [comment]
Check fixed on
Templates version: 0.17.18053.1
Wizard version: 0.17.18053.1
