### ISSUE TITLE
Failed merges on right click do not show error message

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1933]
1) Create MVVMLight project
2) Change method PopulateNavItems method in ShellViewModel
3) Add Blank page with right click.

-> Error message: Could not find row... should be shown
![image](https://user-images.githubusercontent.com/24698018/36374675-7395da4c-156c-11e8-844d-33bf7c9d539d.png)

![image](https://user-images.githubusercontent.com/24698018/36374891-43ef58b2-156d-11e8-98a6-f0ca32663e76.png)

**Comment by mvegaca** [comment]
Fixed on #1942

**Comment by mvegaca** [comment]
Check fiexed on
Templates version: 0.17.18051.1
Wizard version: 0.17.18051.1
