### ISSUE TITLE
Drag and drop not setting hover color correctly

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#1940]
When reordering pages using drag and drop, the hover color isn´t correct. Verify in dark and light themes.

![image](https://user-images.githubusercontent.com/12777039/36381796-030f5b8e-1587-11e8-9b54-1fd03d39ca03.png)

**Comment by mvegaca** [comment]
Check fixed on
Templates version: 0.17.18051.1
Wizard version: 0.17.18051.1
