### ISSUE TITLE
Monaco Editor shows a white screen before render the dark theme colors

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1945]
I've created an Issue for this on Monaco Editor repository.
[Microsoft/monaco-editor/issues/729](https://github.com/Microsoft/monaco-editor/issues/729)

**Comment by sibille** [comment]
Verified in dev-nightly:

Templates version: 0.17.18068.1
Wizard version: 0.17.18068.1
