### ISSUE TITLE
Remove HashIdentIcon & HasIdentTitle in SampleOrder

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1952]
[SampleOrder](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/Features/SampleData/Models/SampleOrder.cs) contains calculated readonly properties `HashIdentIcon` & `HasIdentTitle`.

These are set as `Tag`s in the MasterDetail views but never used for anything.

It appears they were [added](https://github.com/Microsoft/WindowsTemplateStudio/commit/867221f7b83ccacbfeea5178582458f8f919959e) as part of the initial exploratory work on connected animations but weren't removed when they became unnecessary or redundant.
The commit message for why they were added ("as methods that can be used in data binding to uniquely identify an order") seems to ignore that each order already has a unique Id (`OrderId`) but the identifiers aren't used for anything anyway.

I'm intending to remove these properties unless anyone has a good reason to keep them.

They are currently unused items in the sample data and they break our guidelines of not including anything more than we need in the templates.

These computed values of varying content and length are also the blocker for one of the issues in #1717

**Comment by mvegaca** [comment]
I was also reviewing that and I also think that those properties could be removed.

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.17.18052.5
Wizard version: 0.17.18052.1
