### ISSUE TITLE
Navigation disabled after deleting page with error

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#1958]
1) Add a page
2) Delete name
3) Delete page
![image](https://user-images.githubusercontent.com/24698018/36476715-f3ab0f02-16fe-11e8-93ac-c9b61945d225.png)

-> Navigation is still disabled

**Comment by mvegaca** [comment]
Fixed on  #1959

**Comment by mvegaca** [comment]
Check fixed on:
Templates version: 0.17.18053.1
Wizard version: 0.17.18053.1
