### ISSUE TITLE
Adding master-detail page by right click add extra white spaces to TextBlock.xaml

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#1968]
1 - Create a new project
2 - Add a MasterDetail page

The modified file TextBlock.xaml contains update adding white spaces.

**Comment by mvegaca** [comment]
Fixed on #1967

**Comment by sibille** [comment]
Verified in pre
Templates version: 0.12.18054.1
Wizard version: 0.12.18054.1
