### ISSUE TITLE
will we have multiinstance support in WTS?

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#1975]
## Feature Request:
I am currently watching **Windows Community Standup** in which they talked about 2 new templates in **VS** for **Multi-Instance** support in uwp platform. My request is can we have that embeded in WTS as well? with well documented and commented code for multi instance scenario? I think that would be great. Thanks

**Comment by mrlacey** [comment]
This functionality is only available in new next release of the Windows SDK.
WTS templates support functionality available in the current and previous releases. (n & n-1)
When this functionality is available in a released SDK and version of Windows, then we will look to add it.

In the meantime, you can try this functionality with the template produced by the team behind it ([marketplace link](https://marketplace.visualstudio.com/items?itemName=AndrewWhitechapelMSFT.MultiInstanceApps)) if running the latest insider build and SDK.

I have created separate issues for (tracking) adding this functionality (#1977) and command line support (#1976)

**Comment by touseefbsb** [comment]
yeah great. Because I think  it would be perfect to add it to WTS, specially because the main function in this new model is executed even before any kind of ActivatedEventargs stuff. so I think it would be good to merge that application model with already existing model in wts and really bring all activation models under one hood :) But obviously it should be added after stable release of the next sdk.

**Comment by crutkas** [comment]
@touseefbsb great idea.  We have a few ideas on how to add in non "n / n-1" features via a preview / beta feed.  #1718 is that tracking item.

**Comment by crutkas** [comment]
@touseefbsb we do support multi-view as well.  depending on the app, this could be a great way to do it.  Multi-instance does make life a lot easier for other implementations.

**Comment by touseefbsb** [comment]
@crutkas  yeah multi instance makes it easier bcz we dnt have to clean up anything in consolidated events. but one thing is important in using multi instace that we dont try to call LocalFolder, roaming folder or anything at package level at the same time from multiple instances, also in case of shared global dbs this needed to be taken care of. so when this is introduced in WTS, I suggest that with TODOs comments and also in docs, we should provide the developer with precautions to use multiinstace and how they can get around the possible problems of that for their app., and also how their multiple instances can talk to each other. I think they cover a lot of this stuff in the appmodel samples they showed in the community standup yesterday, if you dont have those samples, please let me know I can provide you with those samples.
