### ISSUE TITLE
Re-enable RightClick-Legacy support for MVVMLight

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#1985]
X-Ref #1918

These tests were disabled in `BuildRightClickWithLegacyFixture.cs` (Line 48) due to updates to support MVVMLight 5.4.1 which include breaking changes to namespaces.

This exclusion should be removed once v2.0 of the templates ships as v2.1 should not have any legacy issues.

**Comment by sibille** [comment]
Verified on build  Build dev.templates.tests.full_20180420.1
