### ISSUE TITLE
MasterDetailView selected item's binding is OneWay 

### ISSUE THREAD

**Issue by paulio** [Microsoft/WindowsTemplateStudio#2003]
### Repro steps

Requested a MasterDetailView feature

### Expected Behavior

The selected item in the ViewModel is kept in sync with the view (Binding is TwoWay)

### Actual Behavior
The selected item in the ViewModel remains at the initialised value (Binding is OneWay)

## System

<genTemplate:Item Name="wizardVersion" Version="v1.7.18030.1" />
    <genTemplate:Item Name="templatesVersion" Version="v1.7.18037.1" />

**Comment by mrlacey** [comment]
Yes, this is a bug.

The binding should be `TwoWay` so it's possible to know what's currently selected from within the VM (or code behind).

**Comment by mvegaca** [comment]
Checked on the five modified files:
Code Behind C#
Code Behind VB

MVVM Basic C#
MVVM Basic VB

Prism C#

Fixed
Templates version: 0.17.18060.3
Wizard version: 0.17.18060.3
