### ISSUE TITLE
Design Team Feedback

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2017]
Colors to Update
- ListItemMouseOver 
- CardBorderSelected 
- + Icon color on card mouse over.

FontSizes to changes.
- Template sub-group header.
 - Info Page description.

Other.
Review columns sizing

**Comment by mvegaca** [comment]
Fixed #2018

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.17.18065.1
Wizard version: 0.17.18065.1
