### ISSUE TITLE
Does WTS still favor the deprecated HamburgerMenu over NavigationView

### ISSUE THREAD

**Issue by zipswich** [Microsoft/WindowsTemplateStudio#2022]
I am using V1.7.18030.1.  A new project created with WTS still uses the deprecated HamburgerMenu.  Is this intentional or my version is not the latest?

**Comment by mrlacey** [comment]
@zipswich the generated project is configured to run on devices running the creators update (CU) and the fall creators update(FCU). At runtime the code will swap to use the NavigationView control if the app is running on a machine with the FCU (or above) but will use the HamburgerMenu if not, as the NavView requires FCU. 
We’ll remove the HamburgerMenu when it’s no longer required by the versions targeted.  (For reference, WTS creates apps that target the two most recent-non preview-versions of Windows to maximise the target user base but still make the most of the latest features)

**Comment by zipswich** [comment]
@mrlacey Thank you for the elucidation.  [As soon as one starts using .net standard 2.0 which Microsoft appears to recommend strongly, the only allowed target currently is FCU](https://developercommunity.visualstudio.com/content/problem/93522/uwp-uap10015063-not-compatible-with-net-standard-2.html).  I assume more and more developers will adopt .net standard 2.0. I had to swap HamburgerMenu with NavigationView.  It is not a big deal thanks to [the clear instructions on Moving to NavigationView](https://docs.microsoft.com/en-us/windows/uwpcommunitytoolkit/controls/hamburgermenu#navview).
