### ISSUE TITLE
Change wizard RelayCommand implementation

### ISSUE THREAD

**Issue by dgomezc** [Microsoft/WindowsTemplateStudio#2030]
The implementation of RelayCommand in the wizard is not correct, because every time we want to notify the change of a property that affects some command, we must manually launch the OnCanExecuteChanged method to refresh the command.

We should use an implementation with CommandManager, something like this: [	
ICommand and RelayCommand in WPF
](http://www.c-sharpcorner.com/UploadFile/20c06b/icommand-and-relaycommand-in-wpf/)

**Comment by sibille** [comment]
@geometrikal, thanks for reporting!! Did you experience any issues in the Wizard? We noticed that there are cases where OnCanExecutedChanged has to be called explicitly during development.

**Comment by sibille** [comment]
Closing this, please reopen if there are any issues related

**Comment by geometrikal** [comment]
Sorry for late reply. I do not use the Wizard, but I do use that implementation of RelayCommand. I sometimes have problems where the UI doesn't update in response to `CanExecute` changing, as there is nothing that has caused the `CommandManager.RequerySuggested` event to fire.
