### ISSUE TITLE
Right click window is showing border sometimes

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2032]
![image](https://user-images.githubusercontent.com/12777039/37035757-d4dc2ee0-214d-11e8-9e84-377f9f2d216c.png)

**Comment by dgomezc** [comment]
The problem occurs when Visual Studio has some xaml file open. If you have a xaml file opened with Visual Studio and you try to add a page or a feature with the right click, the window borders are visibles.

We suspect that there is some internal problem that prevents the WindowChrome properties of the window from loading correctly.

**Comment by sibille** [comment]
Moving to backlog until we have more insight of why this is happening

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19177.1
Wizard version: 0.20.19177.1
