### ISSUE TITLE
Templates for Xamarin (uwp, Android, iOS) / .net 2.0 / Prism would be great 

### ISSUE THREAD

**Issue by StanleyBroo** [Microsoft/WindowsTemplateStudio#2058]
# New features

Templates for Xamarin (uwp, Android, iOS) / .net 2.0 / Prism would be great

**Comment by crutkas** [comment]
@StanleyBroo  great idea, we already have an existing item tracking this!  #321.  Here is our thoughts on the approach: https://github.com/Microsoft/WindowsTemplateStudio/wiki/Xamarin-approach 

We would love to get feedback on the tracking issue #321 for the work
