### ISSUE TITLE
Back link text is cropped in some languages on details page

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2071]
Text is cropped, should be Zurüc**k**

![image](https://user-images.githubusercontent.com/24698018/37469677-1c904f4a-2866-11e8-9682-0279f203c761.png)

**Comment by mvegaca** [comment]
Fixed in #2072

**Comment by sibille** [comment]
Verified in dev-nightly:
Vorlagenversion: 0.17.18074.3
Version des Assistenten: 0.17.18074.3
