### ISSUE TITLE
HamburgerMenu XAML Control deprecated

### ISSUE THREAD

**Issue by odyright** [Microsoft/WindowsTemplateStudio#2075]
![hbger menu](https://user-images.githubusercontent.com/4316506/37547062-78fc8d14-2967-11e8-8034-32a85dd6ed5c.PNG)

**Comment by crutkas** [comment]
Thanks for reporting and we're tracking this in #308, Since we support N and N-1 releases, we have to wait for the next update to Windows 10 to be released before we can migrate away.
