### ISSUE TITLE
Controls:HamburguerMenu

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#2081]
Controls:HamburguerMenu,  The version is obsolete is recommended NavigationView

**Comment by sibille** [comment]
dup of #1527. known issue and we'll phase out the UWP Toolkit control for NavigationView for with the next update of Windows. We (WTS) supports the current release and the prior update of Windows. This means we have to wait 2 releases before we can adopt new controls like NavigationView.

**Comment by Javier118** [comment]
Thank you .You can add NavigationView a button for authentication in Azure.

**Comment by mrlacey** [comment]
closing as duplicate
