### ISSUE TITLE
Need documentation that explains how to update a previously generated project

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2082]
We will need clear documentation that explains how to modify an existing project that was generated using WTS v1.x and targets CU & FCU so that it targets FCU as a minimum SDK version and adds (RS4) targetting.

As a minimum, this should cover migrating from the HamburgerMenu to the NavigationView (X-Ref #308) but may need to cover other things as well - TBD.

**Comment by sibille** [comment]
@mvegaca is currently working on this.

**Comment by mvegaca** [comment]
Doc added on #2084.

**Comment by mrlacey** [comment]
As with the note about other things that need documentation but were still to be determined. The WebView Page has some CU/FCU specific code that should also have changes defined and documented.

**Comment by mrlacey** [comment]
The documentation provided on how to manually update an existing project needs to match the way that future projects will be produced in the future to enable manually updated projects to work with future versions of the tool.
In that the way that the tool will generate projects in the future it is not possible to provide equivalent documentation. Any documentation provided now could lead to future problems.

Here are my issues with the initial version of the documentation.
- It only covers projects built with the MVVMBasic framework. The code in projects built with other frameworks has substantial differences and it's not appropriate to assume that someone with a project using another framework will be able to convert their project based on the instructions provided.
- The document does not explain how existing menu items correspond to new NavigationMenuItems.
- By creating NavigationMenuItems directly in the XAML, the logical grouping of what is displayed in a menu item and what happens when it's invoked is now lost. This was previously contained in `ShellNavigationItem`.
- The use of `NavigationViewItemExtensions` seems to have been inspired from an MSDN Journal article. That article uses this approach for specifying the 

- The document does not allow for scenarios where the menu item may do something other than trigger navigation. ([such as is documented here](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.md#invokecode).)

**Comment by sibille** [comment]
Needs update on https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.vb.md too

**Comment by sibille** [comment]
Verified on pre-release:
0.14.18124.02
