### ISSUE TITLE
Detect breaking changes in project on right click

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2086]
Detect breaking changes on a project to give guidance on update before adding in a new page or feature that may fail due to breaking changes we did. 
An example would be a project created with Hamburger Menu and then adding a new page by right click with new templates using NavView.

**Comment by mrlacey** [comment]
Is this to add the ability to improve general guidance on a failed add? Or does it relate to specific scenarios?
If specific scenarios, how will they be configured and detected?

**Comment by sibille** [comment]
It's about giving guidance on situations we caused due to introduction of breaking changes.
It's currently in exploration state, but we imagine the following:

When right click starts detect if there's a breaking change. For NavView that would be:
- Templates on project creation where version 1.7 or lower
- Templates on right click are version higher than 1.7 
- ProjectType is SplitView
- ShellPage does not contain NavView

In this case a notification would show up to, that points to docs on how to migrate.

We're still working out where to configure this, to prepare this also for future changes.

**Comment by dgomezc** [comment]
Message would show like this.

![image](https://user-images.githubusercontent.com/12777039/38257477-927af2c4-3760-11e8-9fa6-511745f9ec8b.png)

**Comment by crutkas** [comment]
So this covers up navigation and is a critical issue?  I'm assuming this won't auto dismiss as well.

**Comment by sibille** [comment]
Created issue #2125 to revisit breaking change notification and show it in another place

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18110.2
Wizard version: 0.18.18110.2
