### ISSUE TITLE
Deleting code in MergePostactions deletes all occurrences of code

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2088]
Detected while investigating issue #2068: Instructions on postaction to delete row `await Task.CompletedTask;` delete all occurences of this in the file. This should be limited to the configured context, f. ex if I want to delete await Task.CompletedTask; from StartAsync method it should be deleted only there.

**Comment by sibille** [comment]
After investigating the problem:
Removals on postactions are working currently different from insertion, context is not taken into account here. 
@mrlacey, I'll refactor the code to make removals working the same way as insertions, on a row based approach, that takes into account the context. 
```       
private IEnumerable<ActivationHandler> GetActivationHandlers()
{
//{[{
            yield return Singleton<HubNotificationsFeatureService>.Instance;
//}]}
//{--{
            yield break;//}--}
}
```

This should remove `yield break;` from the method `GetActivationHandlers()` only, currently it is removing every occurence of yield break in the code.

**Comment by sibille** [comment]
Moving to 2.2 as this is not high priority and refator needs more tests

**Comment by mvegaca** [comment]
Checked in Dev-Nightly
Templates version: 0.18.18152.1
Wizard version: 0.18.18152.1
