### ISSUE TITLE
Rename current Grid page 

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2090]
Because "grid" is such a loaded name, renaming this page will hopefully remove possible confusion over its use and purpose. 
This will be particularly important as we add pages that include other "grids".

X-Ref #405

Change to RadDataGrid?

Exact name to be confirmed. May want spaces, punctuation or some other variant.

**Comment by crutkas** [comment]
I would do Telerik Data Grid or something like that.  Remember to not break our telem for rename :)

**Comment by mrlacey** [comment]
For telem: leave this as "Grid".
Anything new gets a different ID

**Comment by mrlacey** [comment]
@crutkas  Telemetry appears to [use the template name](https://github.com/Microsoft/WindowsTemplateStudio/blob/f15309917030fd6b602dbc343d6e7ee24e921657/code/src/Core/Diagnostics/TelemetryTracker.cs#L205) for tracking purposes. This means that we can't rename anything without breaking telemetry continuity.
Template item names are also never translated. Which seems wrong. Is the need for telemetry consistency the reason we don't support translating names?
I was expecting telemetry to use ID (which would never be translated and should have no reason to change.)
What are the consequences of switching telemetry to use ID?
Or should we accept just breaking consistency for this change? (In theory--and without seeing the reports--, it should be possible to use a combination of version number and name to handle the change.)

_Using 'Name' (rather than ID) for telemetry could also have other issues when we add support for additional template sources too._

**Comment by crutkas** [comment]
Nav View is called Splitview in the telem.  I don't think that is the end of the world.  I'm fine with a breaking change if it is a single shift versus a bunch of small over time.

**Comment by mrlacey** [comment]
@crutkas Are you saying:
1. You're ok with changing "Grid" to "Telerik Data Grid" now, and leaving the collision issue and any other future changes for another time?
or
2. You're ok with switching to using the template ID? ("Grid" would become "wts.Page.Grid" or "wts.Page.Grid.VB" in this instance) It'll be one big change now but avoid anything else changing in the future and will also avoid any collision between identifiers (highly possible with custom template sources) because the tool forces the Template ID to be unique when it loads them.

**Comment by crutkas** [comment]
I'm saying i think we can change the public name and the telem is reported 

- SplitView (Shown as Navigation Pane)
- Blank
- TabbedPivot (Shown as Pivot and Tabs)

**Comment by crutkas** [comment]
if we need to change it, lets change it.  I would have the new page not use Grid so we're not mixing telem.

**Comment by mrlacey** [comment]
Project types have both **Name** (used for telem) and **DisplayName** (shown in the UI) properties but pages only support **Name** (used for both).
It's probably a better solution to add **DisplayName** support for pages.
We can review telem for custom template sources when we have them. They will probably need something different for telem anyway.

**Comment by mrlacey** [comment]
So, pages use **Name** as it can be localized. If I added **DisplayName** it wouldn't get picked up by the localization.
Instead, I'm adding a new tag for "telemName" which will get used if it exists. If not present, we'll continue to use the name.
This will allow us to also change other names in the future but keep the old telemetry values.
Will run this by @sibille to get her input on this too when raising the PR.

**Comment by mrlacey** [comment]
Verfied in 
Templates version: 0.17.18104.1
Wizard version: 0.17.18104.1
