### ISSUE TITLE
Make sample data platform agnostic

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2093]
Remove Windows specific references from `SampleOrder` and `SampleDataService`.

This is to enable the use of sample data in multiple projects.
X-Ref #2087

**Comment by sibille** [comment]
There is a wrong char in Prism.SampleDataService.

**Comment by mrlacey** [comment]
Closing as verified in 
   wizardVersion="v0.18.18112.1" 
    templatesVersion="v0.18.18112.1"

Prism issue appears to be due to https://github.com/Microsoft/WindowsTemplateStudio/commit/1758a330d9a57e5a2aa5cce068c5a38a9313fd0c#diff-fc87c59e6a12d914f43fe8c63973a9c6
