### ISSUE TITLE
Wizard showing "no content available" on 1.7 version

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2097]
Version 1.7 shows "No content available" and does not download new content when checking for new content.

Templates got only half extracted to ProgramData and Wizard is stuck here. 

Workaround until this is fixed:
1. Delete C:\ProgramData\WindowsTemplateStudio\Templates\Pro folder
2. Restart Visual Studio
3. New content should be downloaded and extracted

**Comment by crutkas** [comment]
My request here is to have the system auto fix itself, not add a button to refresh. Why a button?

**Comment by sibille** [comment]
We were evaluating that, but if the system tries to autofix this could result in an infinite loop if the fix does not work. 

We also saw that we can optimize the copy process and add in a mechanism to flag the copy as complete (f.ex by renaming the folder from .tmp to final name). This should avoid the problem in its origin, I'll create an issue, but not sure we can do this for 2.1.

**Comment by crutkas** [comment]
wait, so we download, we verify the download is correct.  if the files don't extract properly, we should instantly know this.  If the zip is corrupt, we should be able to detect that as well.

How is this an infinitive loop?

incomplete / corrupt -> redownload
If unzipping and moving files failed, -> unzip again

If we try again and fail, flag user then and say something is wrong, do XYZ and we should log it.

**Comment by sibille** [comment]
If download fails or extraction failes, templates are downloaded again. This error is caused if the copy process is interrupted (by closing VS). 
We can auto-fix in this case, and if it fails again inform the user and log instead of the button.

**Comment by crutkas** [comment]
i'm confused still why we need the button.  On startup, we detect incorrect files, we then throw up a "we detected possible issue with our template repository" and kick off Unpacking / preparing" window and start unzipping / copying or something like that.

Why would a user need to intervene?

**Comment by sibille** [comment]
I think I did not explain myself correctly in the last post. We can do it without the button and download/extract templates again. If this is not successful show a message and log the error.

**Comment by mrlacey** [comment]
What happens if the "download/extract templates again" fails? It's ok to show and log an error but is that the best we can do?
What might cause this? - Anything we can pre-empt or prepare guidance/docs for?
How could someone recover? - Do we really not know and must have the logs to help?

**Comment by sibille** [comment]
If download fails, templates delivered with the wizard are extracted. Next time you enter the wizard it will try again to download. Extraction of templates should only fail due to "local" errors (like no disk space). Errors here are logged, and next time you enter the wizard it will try extraction again.

We're preparing the copy process to start over again if copy was aborted.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18110.2
Wizard version: 0.18.18110.2
