### ISSUE TITLE
Use NavigationView instead  of Hamburger Menu from UWP toolkit

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WindowsTemplateStudio#2103]
When can we expect to have NavigationView within the code? 

I believe it was said that WTS would only be support last two version of window. Now that 1803 is going to be released next month, WTS can drop using `HamburgerMenu` from the UWPToolkit and start using `NavigationView`.

**Comment by mrlacey** [comment]
@harvinders once the next version of Windows is released, an update to WTS will also be released that adjusts the target versions accordingly and will remove the use of the HamburgerMenu control.
The aim is that this will be within a few days of the OS release.
