### ISSUE TITLE
Update the version of NetCore.UWP referenced in templates

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2104]
The current templates use 6.0.6 but 6.0.8 is the latest and it uses a newer version of .NetNative ([history](https://github.com/Microsoft/dotnet/blob/master/releases/UWP/net-native2.0/README.md))

Switching to the newer version means we'll match what's used by store packaging and is also what will be used by UWP apps built with VS 15.6+ 
Matching what's installed by VS can be useful in ruling out potential issues and this is also a good time to update the templates to make sure generated apps are using the latest versions.

X-Ref #2102 

**This fix would be a great contender for inclusion in the 2.0 hotfix!**

**Comment by touseefbsb** [comment]
is there a way for template to automatically get the latest version of the nuget package at the time of project being generated? that will ease up the need for updating it manually after every month or so

**Comment by mrlacey** [comment]
@touseefbsb I don't believe there's an automated way of forcing all NuGet packages to update to the latest version. 
We wouldn't want this anyway:
- New versions may introduce new dependencies or changes in license terms that we shouldn't hide.
- New versions may introduce very large downloads. (We've had this in the past where updating this package meant a 2GB download. We don't want to cause VS to be unusable while it performs a large download in the background.) It looks really bad if the first time someone uses WTS it takes _ages_ to generate the first app while dependencies are downloaded.
- New versions can introduce breaking changes.  Automatically changing to a different version could lead to the generation of apps that don't work as expected or even compile.
- New versions may address issues we have workarounds for elsewhere in the generated code. Where this is the case we remove the workarounds at the same time as switching to using the newer version.

It's not always a case of always switching to the latest version as soon as it's available.

We want to include versions of dependencies that are already installed by VS as much as possible and that are the same versions we've tested against.

**Comment by touseefbsb** [comment]
yeah you are right, only tested versions should be included.

**Comment by crutkas** [comment]
Agree on the hotfix here.  This is just a template fix, not an engine fix, correct?

**Comment by mrlacey** [comment]
@crutkas yes, just templates.

**Comment by sibille** [comment]
Should we include this into 2.0 hotfix together with Navview?

**Comment by sibille** [comment]
Verified in dev-nightly
Templates version: 0.17.18096.1
Wizard version: 0.17.18096.1
