### ISSUE TITLE
Fix typo in Default.rd.xml

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2109]
The version of Default.rd.xml that we include is based on an olde version from the default blank project template.
The version we use still includes a typo that was fixed in the default template.
The typo is in sample code that is commented out and included for reference but we should still update so that if someone uncomments the sample code it will actually work.

The property **Seralize** should be **Serialize**.

**Comment by sibille** [comment]
Should we include this into 2.0 hotfix together with Navview?

**Comment by sibille** [comment]
Verified in dev-nightly
