### ISSUE TITLE
ShellPage is not child of a frame which limits some scenarios

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2113]
## For new Features:

the window content seems to be directly the **ShellPage** and not a Parent Frame which hosts the ShellPage, this limits the functionality for some scenarios.

* **Overview:** What you'd think should be added with scenarios
the ShellPage should be hosted in a Frame.

### Expected Behavior

When I try to do **Frame.Navigate(typeof(AnotherPage))** from within the **ShellPage.xaml.cs** I should be able to navigate to another page which will also be hosted within the **MainFrame** and I can manually write my own code to deal with back button specfic to that page so that when I press back I can go back to **ShellPage** and the normal functionality of the app will remain the same as expected, within the shellpage all navigation will remain the same.

### Actual Behavior

When I tried to navigate away from ShellPage I got a null error on the frame because ofcourse the window content is ShellPage itself and not the frame.

## System

* **VS Version:**  VS 2017 15.6.3
* **Windows Build:** 1803 ( I am on insider Fast Ring so I already have the next update )

<genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Windows Template Studio" />
    <genTemplate:Item Name="wizardVersion" Version="v0.17.18089.1" />
    <genTemplate:Item Name="templatesVersion" Version="v0.17.18089.1" />
    <genTemplate:Item Name="projectType" Value="SplitView" />
    <genTemplate:Item Name="framework" Value="MVVMBasic" />
</genTemplate:Metadata>

**Comment by mrlacey** [comment]
The [mixed navigation sample](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/navigation.md#mixed-navigation-sample) should show how to do what you're after

**Comment by touseefbsb** [comment]
it is based on version 1.3 of wts, should it be updated for current version? or will it work perfect with current version as well? @mrlacey

**Comment by touseefbsb** [comment]
also the docs sample tells us about following scenario
>Start the app on StartPage -> navigate back to ShellPage -> use the app on the shellpage.

but there are 2 other scenarios as well, which are not documented.

1. >start the app on shellpage -> navigate to the StartPage -> navigate back to shellpage -> navigate to the StartPage ( this scenario is flexible and lets the user keep navigating between shellpage and startpage whenever needed )

2. > start the app on startpage and then go back and forth between shellpage and startpage.

both of above scenarios are not possible because of the following line in the docs.

>//Navigating to a ShellPage, this will replaces NavigationService frame for an inner frame to change navigation handling.
> NavigationService.Navigate<Views.ShellPage>();

as the comment suggest, this replaces the frame with inner frame, this cancels the possibility of going back and forth and the functionality is very limited for one usecase but cancels all other usecases which involved going back and forth between shellpage and another page.

**Comment by touseefbsb** [comment]
@mrlacey  any idea on how to achieve this cleanly?

**Comment by mrlacey** [comment]
The docs show a sample built with 1.3 but this should have no significant differences with 1.7.

Updating this documentation should already be part of the work to migrate to using the NavigationView.

**Comment by touseefbsb** [comment]
should we add the docs for the scenarios I defined as well ? @mrlacey

**Comment by crutkas** [comment]
@touseefbsb  if you feel strongly, create a PR

**Comment by touseefbsb** [comment]
I think my usecase is not very common, and my solution is also not perfect right now, Ill try to polish it, and if some more people also need this, then we can consider including this in the docs, otherwise it can be confusing in the docs.

**Comment by mrlacey** [comment]
@touseefbsb if this isn't a common use case then I don't see a need to create docs for it.
Updating the existing docs is covered elsewhere

**Comment by hupo376787** [comment]
Hi, @touseefbsb I have the same situation now. My logic is in ShellPage.xaml.cs, I added an event to detect network change.

```
NetworkHelper.Instance.NetworkChanged += Instance_NetworkChanged;
private async void Instance_NetworkChanged(object sender, EventArgs e)
{
...
}
```

So when network changed, app will navigate to a page.
Do you work out a better solution, thx.

**Comment by touseefbsb** [comment]
@hupo376787  Actually I also just made a custom work around which wont work for every case. You should look at the mixed navigation sample provided by @mrlacey  above in the 1st comment of this post, that has been updated over time and looks much more simpler and easier to use now.
