### ISSUE TITLE
Roadmap for this project is outdated

### ISSUE THREAD

**Issue by AWulkan** [Microsoft/WindowsTemplateStudio#2135]
The roadmap on this page appears to be outdated:
https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/roadmap.md

According to that roadmap, the project should be at version 2.2 this month.

Also, the "Track progress" links for version 2.1 and 2.2 are linking to the wrong version.

**Comment by crutkas** [comment]
100% great feedback and something @mrlacey continually tries to keep us honest.  We've been fighting hard to get the new UX and 100% accessible.  This will allow us to do something pretty neat in the near future.  It has taken a bit longer than we expected.

Fixed links, thanks for making us aware.

I'm going to keep this open until we update the Roadmap as 100% a valid issue.

**Comment by mrlacey** [comment]
@AWulkan 2.0 became delayed for external reasons that should become apparent when it’s released. When it’s released it will also have an impact on the future release cadence. Standby for more details  once it’s officially announced ;)

**Comment by AWulkan** [comment]
Ye, I have no problem with the delay, I understand that things sometimes take longer than expected. Just pointing out that the roadmap didn't reflect the delay. :)

**Comment by mrlacey** [comment]
@AWulkan I've just [submitted a PR](https://github.com/Microsoft/WindowsTemplateStudio/pull/2204) to update the doc.
As background for the delay, 2.0 was put on hold while we explored some other opportunities for WTS. The investigation and discussion around them took a lot longer than expected and the outcome of them was that they will not take place at this time.
The knock-on effect of all that was a delay to our normal monthly release schedule.
We're now back to our normal schedule, with the 2.1 release expected at the end of this month.

The [Microsoft Build conference](https://www.microsoft.com/en-us/build) is at the beginning of next month and we expect what's announced there to have a big impact on future releases.

**Comment by mrlacey** [comment]
docs merged to the main branch so closing as they are now what's visible on the site.
