### ISSUE TITLE
select default theme of the app from the wizard.

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2144]
## For new Features:

When creating a new project with WTS, can we have an option to select a default them for the app? 
Light or Dark?

I know by including settings, we have option to toggle theme and even save that in settings, but default theme always seems to be Light, unless user changes it to dark and then it changes to dark. is there a way we can have this in wizard as well to select default them for the app for example if I select dark then the theme will be dark unless I change it to light afterwards from within the app? 

Even if we cant include this feature in wizard, can we have a simple comment within the themselector service or maybe settings page? that how to change the default theme of the app to dark? (i.e : whenever the app runs for the first time on a user's machine, the theme is dark ) ?

**Comment by crutkas** [comment]
It defaults to "Default" which is whatever YOU as an end user have your system set to in your settings.  
 From a platform stance, this is what we feel is best.  You as the developer can set that in your app manually with the theme selection service by changing "public static ElementTheme Theme { get; set; } = ElementTheme.Default;" to ElementTheme.Dark if you want it dark.

If you don't want to do theming, you can force your app's theme as well with App.xaml and bypass the theme service entirely. 
https://stackoverflow.com/questions/34554871/changing-theme-in-windows-10-uwp-app-programmatically

**Comment by marektoman** [comment]
The problem is that the "Windows default" setting is often NOT what the user wants, e.g. it's light when my system setting is set to dark. Ocasiaonly, it works as expected. This happens in case of a generated app where are no modifications.

**Comment by crutkas** [comment]
@marektoman, WTS generates the base, changing the default value is pretty straightforward if memory serves. You are the app creator, do what you feel is the best default experience for your app 😊
