### ISSUE TITLE
Wrong image restore on go back navigation

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2145]
Repro steps:
 - Create an app with nav view with pages: Blank, Image Gallery and Settings.
 - Launch the app.
 - Navigate to the image gallery.
 - Navigate to the first image.
 - Move the selected image to the next image in the pivot.
 - Navigate to the settings page.
 - Click on go back.

Expected behavior:
Go back to the image detail page on the second image.

Actual behavior:
Go back to the image detail page on the first image.

**Comment by crutkas** [comment]
This feels like a must fix for launch

**Comment by mrlacey** [comment]
Note. this is an existing issue in the current code. Not a regression after changing to the NavigationView as I initially assumed when seeing this raised.

**Comment by sibille** [comment]
I think we can finish it today

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18114.1
Wizard version: 0.18.18114.1
