### ISSUE TITLE
Add an option to extend acrylic into the title bar

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WindowsTemplateStudio#2146]
## For new Features:

Given that the version 2.0+ would have to only support 1709 & 1803, and Microsoft having provided fluent design guidelines, there should be an option to extend the acrylic into the title bar as shown [here](https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic#extend-acrylic-into-the-title-bar)  if it makes sense (say when using `NavigationView`).

### Expected Behavior
Instead of showing a solid Titlebar, extend arcylic into it. Not everyone may like to replace the solid Titlebar with the acrylic, so maybe it could be an option in the wizard or a property of a class that can be set.

**Comment by crutkas** [comment]
This is something as a developer, you would add in.  We have to find that fine line of doing too much or not enough. This feels like too much as is easy for someone to add in. 

We try to handle bigger bits of code like a full page or a feature like a background task.

**Comment by crutkas** [comment]
100% great idea by the way.

**Comment by harvinders** [comment]
@crutkas, @sibille  
Of late I saw lot of code changes based on feedback from fluent team. Wondering if it would make sense to have a re-look at extending view into title bar, given that we are now looking at margins and stuff like that in WTS from fluent design perspective?

It does not hurt to make app beautiful by default.

**Comment by mrlacey** [comment]
@harvinders one of the aims of this project is to always get all the code that's generate reviewed by the fluent design teams to ensure that what's produced is the best it can be.

I'm not aware on any guidance having changed regarding the title bar (most recent was to not put anything in it as sets will change how title bars work when they become widespread) so asking for a review right now seems unnecessary. If there has been an announcement I've missed (perfecctly possible) can you point to it and we will review.

**Comment by crutkas** [comment]
@harvinders the wonderful thing about Fluent is you can do whatever you want.  If this is something that you feel your applications need, by all means, do it.
