### ISSUE TITLE
Add MRU (Most Recently Used) File Helper/Page

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/WindowsTemplateStudio#2194]
## For new Features:

* **Overview:** 
You still need to store in your app storage a list of the files you want to have access to.  The settings page is great for general app settings, but it'd be nice to have another helper/page that sets up making keeping tracking of the MRU easier.  i.e. it could have an `RememberFile(StorageFile)` method and `GetMostRecentFiles(int number)` methods.  It should also have an event for when an item is added (or maybe just expose it as an observable collection).

This would make it easier for developers to pass in files the user has opened or interacted with and then retrieve them to put a list in an app somewhere.

* **Links:**
Reference: https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders

**Comment by crutkas** [comment]
Feels like something someone would use in the Community Toolkit versus WTS.  @nmetulev thoughts?

**Comment by nmetulev** [comment]
Looks like there is a helper already in the platform for this per the linked doc above. I could see an ObservableCollection on top of the MCU being helpful, but not sure if there is a demand for that.

**Comment by mrlacey** [comment]
We already have an issue (#920) for adding the handling of specific file extensions that includes a note that it should also have an MRU for files of that type.

Closing this as the functionality requested here will be covered as part of that feature although it may or may not include the method names suggested here.
