### ISSUE TITLE
First default mainpage (in wizard) is not removable

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WindowsTemplateStudio#2195]
## For Bugs:
The wizard does not allow us to remove the first default main page that is automatically added. What if I want a tabbed page in the navigation type project?
### Repro steps
- Create a new navigation project
- Add a new tabbed page
- Try to remove the first page

### Expected Behavior
Once a second page is added, allow the first one to be deleted/removed

## System

* **VS Version:** 2017
* **WTS Wizard Version:** .17.18105.1 (nightly)
* **WTS Template Version:** 
* **Windows Build:** 1709

**Comment by sibille** [comment]
@harvinders, did you reorder the pages before deleting the first page? First page is the "Home page" and cannot be deleted, if you add another page (Blank1 for example), reorder the pages (by drag and drop) to make the Blank1 page the home page, then you can delete the first page.

**Comment by harvinders** [comment]
I haven't tried that. But now I know, thanks.

**Comment by sibille** [comment]
@crutkas, I think we should redesign that in a future and allow deletion of any page if there is more than one.

**Comment by crutkas** [comment]
agreed as long as the last page isn't a settings page

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18149.2
Wizard version: 0.18.18149.1
