### ISSUE TITLE
Find a typo in the comment of FireAndForget method 

### ISSUE THREAD

**Issue by kennyzx** [Microsoft/WindowsTemplateStudio#2202]
The path of the file is \WindowsTemplateStudio\templates\Uwp\Features\BackgroundTask\Helpers\TaskExtensions.cs

And it reads

    // This method allows you to call an async method **with** awaiting it.
    // Use it when you don't want or need to wait for the task to complete.

the word 'with' should be 'without'.

**Comment by mrlacey** [comment]
also Prism and VB versions of this file

**Comment by mrlacey** [comment]
verified in 
    wizardVersion="v0.18.18113.1" 
    templatesVersion="v0.18.18113.2"
