### ISSUE TITLE
Error creating project using nightly build (0.18.18110.1)

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WindowsTemplateStudio#2212]
## For Bugs:
While adding a project through the wizard in existing solution, project creation fails and the solution is closed

### Repro steps
Select Navigation Option
Select MvvmLight
Added Settings and Blank Page
Click Create

### Expected Behavior
The project should be created

### Actual Behavior
System.Exception: Error executing 'Microsoft.Templates.Core.PostActions.Catalog.SetDefaultSolutionConfigurationPostAction'. Related template: None. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.SetActiveConfigurationAndPlatform(String configurationName, String platformName, Project project)
   at Microsoft.Templates.UI.VisualStudio.VsGenShell.SetDefaultSolutionConfiguration(String configurationName, String platformName, String projectGuid)
   at Microsoft.Templates.Core.PostActions.Catalog.SetDefaultSolutionConfigurationPostAction.ExecuteInternal()
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   --- End of inner exception stack trace ---
   at Microsoft.Templates.Core.PostActions.PostAction.Execute()
   at Microsoft.Templates.UI.GenController.ExecuteGlobalPostActions()
   at Microsoft.Templates.UI.GenController.<GenerateItemsAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.NewProjectGenController.<UnsafeGenerateProjectAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Templates.UI.NewProjectGenController.<GenerateProjectAsync>d__6.MoveNext()

## System

* **VS Version: VS 2017, 15.6.6**
* **WTS Wizard Version:0.18.18110.1**
* **WTS Template Version:No idea**
* **Windows Build:1709**

**Comment by sibille** [comment]
Thanks for reporting, @harvinders, I'll have a look at this!

**Comment by mrlacey** [comment]
I get no repro 
VS 15.7p3
Templates version: 0.18.18114.1
Wizard version: 0.18.18113.1

@harvinders you can see both version numbers on 
![image](https://user-images.githubusercontent.com/189547/39194470-bfaf9b3e-47d5-11e8-9e59-e69cd92fdced.png)

**Comment by sibille** [comment]
I could not reproduce. You're saying that you added a project to an existing solution. Where there more projects? Which project types? This might give us more hints. 
		
Although this fails it should not result in an exception being thrown, I'll change the postaction to log an error in case of failure.

**Comment by harvinders** [comment]
First the templates, this is what I am the using today
Templates version: 0.18.18115.1
Wizard version: 0.18.18110.1

I am not able to reproduce when I am creating it as the first project. It happens only when I add it to the existing solution. Well, there are around 50 projects in the solution, but interestingly one project is WTS project created through an earlier nightly build of WTS.

Also, I noticed that the new project is created, it is just that the exception closes the solution and the created project is added to the solution.

I will see if I can create a minimal solution with which I can reproduce it again.

**Comment by harvinders** [comment]
@sibille Just tried. Still fails. This time though I saw project was added to the solution before the solution was closed and error displayed. 

Let me see if I can pin it down, will try to remove some projects and see what happens.

**Comment by harvinders** [comment]
@sibille I have removed all the projects from the solution and the problem still exists. The solution directly still has .svn, .vs folders and user settings file. I will take the solution to a different PC tomorrow to see if it runs there.

**Comment by sibille** [comment]
@harvinders, I tried with the above mentioned solution and it works fine. 
What wizard and template version are you using? You can get this info from the right side of the Wizard.
![image](https://user-images.githubusercontent.com/24698018/39347793-ba51d1b8-49f4-11e8-86da-11ff982de053.png)

**Comment by harvinders** [comment]
Tried again with
Templates version: 0.18.18117.1
Wizard version: 0.18.18110.1

I suspect it may be something to do with my installation of visual studio or the plugins installed. I noticed that one time, I added a simple project (just pressed the create button directly) that project got created. After that, I was able to create the mvvmlight project.

I did some more experiments but I am not able to pin it down. You may like to close the issue.

**Comment by sibille** [comment]
I'd really love to solve this. Changing the default solution configuration to debug/x86 is done after project creation. It might fail on your machine due to some vs or solution configuration we where not aware of, but even if it fails it should not prevent you from getting to the generated project.

This change was introduced in wizard version 0.18.18116.2, you're using a lower wizard version. Could you update the wizard? (Go to Tools -> Extensions and Updates -> Updates -> configured dev-nightly feed)

**Comment by harvinders** [comment]
@sibille You have already solved it. It was my mistake, I did not update the extension. After the update, it works. Thanks.

**Comment by sibille** [comment]
Thanks to you for reporting the problems.
