### ISSUE TITLE
Bug: fails to install with "do not have supported versions"

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#2218]
User on marketplace reported:  I have an Up-to-Date VS2017/VS2015/VS2013 and when I run the VSIX it fails with "You do not have a supported version"

Have we tested against when we have multiple versions installed?  I know preview and 2017 but unsure if we've ever tested with multiples

**Comment by mrlacey** [comment]
Can we also do anything about the message that gets reported, so it provides more useful information? 
Or is that fully VS controlled?

**Comment by sibille** [comment]
The message comes from VSIX installer. We tested in the beginning with multiple versions installed. I'll install VS 2015 on a one of the test machine to see if I can reproduce this.

**Comment by sibille** [comment]
Could not reproduce in test machine. Reviewed the issue in PM with the user. The installer did not detect VS2017 correctly, solved the issue repairing Visual Studio 2017.
