### ISSUE TITLE
Navigationview is showing extra back button on rs4

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2221]
Navigationview is showing extra back button on rs4 machine.

![image](https://user-images.githubusercontent.com/24698018/39362099-6f414dbc-4a25-11e8-9f76-0c6092b93c96.png)

**Comment by sibille** [comment]
The Navigationview back button is new on April 2018 SDK. As we support fcu and April Update we'll hide the button for now. When april update is min version we can change to support navviews back button.

**Comment by sibille** [comment]
Verified on pre-release:
0.14.18124.02

**Comment by larsschellhas** [comment]
This does not solve the problem when you try to extend the Navigationview into the title bar...
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#extending-your-app-into-the-title-bar 

![image](https://user-images.githubusercontent.com/14281234/40629339-bdc262ce-62ca-11e8-97c7-69988089e9d7.png)
