### ISSUE TITLE
MVVM Light NavigatedTo

### ISSUE THREAD

**Issue by Weasy666** [Microsoft/WindowsTemplateStudio#2222]
### Repro steps

Create a clean WTS project with 2 pages and try to navigate from `Page1` to `Page2` by code.
Like this:
``` csharp
var navigationService = ServiceLocator.Current.GetInstance<NavigationServiceEx>();
navigationService .Navigate(typeof(Page2ViewModel).FullName, someParameter);
```

### Expected Behavior

In `Page2` i would now expect that i can override the `OnNavigatedTo` method.

### Actual Behavior

`OnNavigatedTo` method is not available in `ViewModelBase` and so i can't override it and am not able to access my passed parameter. I feel kinda stupid, but how am i supposed to do this?

## System

* **VS Version:** 15.6.7
* **WTS Wizard Version:** 2.0.18100.1
* **Windows Build:** 16299.402

**Comment by mrlacey** [comment]
@Weasy666 While MVVMLight uses the name of the ViewModel as the key for the navigation, it does not do ViewModel-navigation.  The app will navigate to a page instance and you can access the parameter passed during navigation in the `OnNavigatedTo` method there.
The behavior you describe as expecting isn't something possible with MVVMLight but is with Prism.

**Comment by crutkas** [comment]
@Weasy666 one thing to remember here, we follow best practices for that target framework.  each framework has pro's and con's.  We want to make sure if you adopt one framework, what WTS generates acts like how it is supposed to.  Every framework is signed off by that framework's team.

**Comment by Weasy666** [comment]
Yeah, i thought so....but like you can see here:
![image](https://user-images.githubusercontent.com/11967542/39380790-17ee5600-4a60-11e8-853c-817b9f144137.png)
They tell you to use the overwritten `OnNavigatedTo` method in the MVVM Light docs. But it's not possible.

**Comment by mrlacey** [comment]
@Weasy666 Is the documentation image you included from http://www.mvvmlight.net/doc/nav5.cshtml

`OnNavigatedTo` does exist. You'll find it in the Page/View, not the ViewModel.
Look in `Page2Page.xaml.cs` not `Page2ViewModel.cs`

**Comment by Weasy666** [comment]
Oh....damn...i didn't realize that...i thought it's a MVVM framework so the method has to be in the ViewModel, like in Template10.  
Thank you for correcting my misinterpretation.
If this is the MVVM Light way, then i need to change to Prism.
