### ISSUE TITLE
Compilation error with project generated using 2.1 release

### ISSUE THREAD

**Issue by harvinders** [Microsoft/WindowsTemplateStudio#2237]
### Repro steps

Create a new project using 2.1 in Visual Studio 2017 (15.6.7), community edition
Selected Navigation
Selected MVVM Basic
Added Two Tabbed Pages and Settings Page

### Expected Behavior

No Compilation error

### Actual Behavior

```
1>...\Views\ShellPage.xaml.cs(26,32,26,51): error CS1061: 'NavigationView' does not contain a definition for 'IsBackButtonVisible' and no extension method 'IsBackButtonVisible' accepting a first argument of type 'NavigationView' could be found (are you missing a using directive or an assembly reference?)
1>...\Views\ShellPage.xaml.cs(26,54,26,85): error CS0103: The name 'NavigationViewBackButtonVisible' does not exist in the current context

```
## System

* **VS Version:** 15.6.7
* **WTS Wizard Version:** 2.1.18124.1
* **WTS Template Version:** 2.1.18124.1
* **Windows Build:** 17134

**Comment by harvinders** [comment]
I suspect it is because I don't have the corresponding SDK. I still have 16299 SDK. If that is reason for this code generation, then I suspect that instead of looking at the OS, we should look at the SDK installed, while generating this code, if that is possible.

**Comment by sibille** [comment]
It should look at the installed sdk not the machines version. Do you have April 2018 sdk installed? Did you retarget the project?

**Comment by harvinders** [comment]
No I don't have the April SDK installed. After the project creation, I got some error related to SDK targeting, and the project was set to use 16299 as the Target and min version. What I had was the nightly version of wizard, could that cause this issue?

I would update you in couple of hours with the screen shot of the error dialog that shows after project creation.

**Comment by harvinders** [comment]
@sibille The **Update your project to target an SDK that is installed** stumped me. I should have read it carefully. 
![image](https://user-images.githubusercontent.com/8557046/39662623-2affe314-50a8-11e8-9795-a07e56dfdcf2.png)

So, it seems like it does look at the OS and not the SDK installed. It is not a deal breaker though. You may like to close the issue.

**Comment by crutkas** [comment]
Our 2.1 update does require Windows 10 Spring 2018 Update (17134) for applications created with it.  My blog outlines how to get it.  Depending if VS 15.7 is out, the install instructions change hence pointing to the blog.  https://blogs.windows.com/buildingapps/2018/04/30/start-developing-on-windows-10-april-2018-update-today/

**Comment by jhueppauff** [comment]
can approve, with Spring 2018 Update (17134) the error is gone.

**Comment by sibille** [comment]
Thanks for the confirmation!
