### ISSUE TITLE
Add page using new DataGrid from the community toolkit

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2238]
The Windows Community Toolkit now includes a pre-release version of a [DataGrid control](https://github.com/Microsoft/WindowsCommunityToolkit/blob/harinikmsft/datagrid/docs/controls/DataGrid.md).

Add a page that uses this control.
This should be functionally equivalent to the page using the RadDataGrid.

**Comment by mrlacey** [comment]
As the control is still in preview and may change before final release, we should consider adding this to dev branch (for nightlies) but only including it in a WTS release once the control has a proper release.

**Comment by mrlacey** [comment]
Not adding the `Can Close Out Soon` tag as we need to wait for the control to come out of preview before releasing fully.

Once it is out of preview will need to update
- the version of the control that's included
- the link to documentation in the generated code comments

**Comment by mrlacey** [comment]
Moving to next milestone as the release of this new page is dependent upon the control getting out of preview and that won't happen in the v2.2 timeframe.

**Comment by mrlacey** [comment]
Moving to next milestone as the release of this new page is dependent upon the control getting out of preview and that won't happen in the v2.3 timeframe.

**Comment by sibille** [comment]
@mrlacey, the DataGrid seems to be included in WCT version 4.0 https://github.com/Microsoft/WindowsCommunityToolkit/releases/tag/v4.0.0

**Comment by mvegaca** [comment]
Checked in Dev
Templates version: 0.18.18241.3
Wizard version: 0.18.18241.1
