### ISSUE TITLE
WebView Adblocker

### ISSUE THREAD

**Issue by pachony** [Microsoft/WindowsTemplateStudio#2245]
## For new Features:

* **Overview:** Hello, first I want to admire all of the team for the great work that you have done, the template is great. Thank you! I have worked with it for several months. WebView is working great, but I have a question. Can AdBlocker be implemented for the ads inside the web content?
* **Links:**

**Comment by mrlacey** [comment]
@pachony It cannot.
The webview control doesn't support extensions like a browser. It also isn't intended for use to create a general purpose web browser. It's meant for showing content from a limited set of sources. These would normally be directly related to the app or served directly for it. In these scenarios, a generic ad blocker shouldn't be necessary.
