### ISSUE TITLE
Scroll on touch devices not working on pages and features section

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2250]
On a touchscreen you can scroll on the whole are in the project type section, but not on pages and features section.

**Comment by crutkas** [comment]
This is low priority but is nice to have. Who knew demoing for 3 days straight we would find an issue or two :)

**Comment by mvegaca** [comment]
Checked in Dev-Nightly
Templates version: 0.18.18152.1
Wizard version: 0.18.18152.1
