### ISSUE TITLE
As I can put the Title on each page and CommandBar with the new template NavView 

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#2251]
Hello:

As I can put the Title on each page and CommandBar with the new template NavView.

**Comment by crutkas** [comment]
believe the question is how can i update a commandbar and the title when a user clicks to a different page.

**Comment by sibille** [comment]
Did you have a look at https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.md#using-the-navigation-pane-and-command-bars?

**Comment by Javier118** [comment]
I want to put in each page a CommandBar as in previous versions WTS. Since you utlizo different controls.

**Comment by sibille** [comment]
https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.md#adding-a-commandbar-to-every-page-in-the-app was updated to do add a command bar to the NavView as you did before with the hamburger menu. 

Could you give us more details on whats not working or missing for you?

**Comment by Javier118** [comment]
The command bar falls below the title

**Comment by Javier118** [comment]
I want the CommandBar for each page and that at the height of the title

**Comment by Javier118** [comment]
![2018-04-18](https://user-images.githubusercontent.com/17751683/40057179-d6b9b5a2-584d-11e8-8591-8c3365e5a5b7.png)

**Comment by Javier118** [comment]
If you look at the image you will see that the CommandBar is at the same height as the title

**Comment by mrlacey** [comment]
@Javier118 Is the image a mockup of what you're trying to do or what you've done? What have you tried? How is what you've tried producing something different to what you want to achieve?

**Comment by Javier118** [comment]
This is before the new update WTS

**Comment by crutkas** [comment]
@Javier118  can you write what you're trying to do in your native language and we'll try to translate?

We really want to help but we need much more information.  Single sentence responses aren't enough context for what you're trying to accomplish.

**Comment by Javier118** [comment]
El Problema como puedo  acoplar  la commandbar  en la parte superior, yo quiero  ponerlo a la altura del titulo  como se hacia con controlHambuguer  en las diferentes paginas .   Por ejemplo :`<Grid
        x:Name="ContentArea"
        Margin="12,0,12,0">

        <Grid.RowDefinitions>
            <RowDefinition x:Name="TitleRow" Height="48"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <TextBlock
            x:Name="TitlePage"
            x:Uid="MiHistorial_Title"
             FontSize="{StaticResource FontSizeMedium}" Foreground="{StaticResource RedBrush}" FontWeight="SemiLight" TextTrimming="CharacterEllipsis" TextWrapping="NoWrap" VerticalAlignment="Center"
            Margin="0,0,12,7"/>

        <CommandBar x:Name="MyAppBar" Grid.Row="0" HorizontalAlignment="Right" Background="White" >
            <CommandBar.PrimaryCommands>
                <AppBarButton x:Name="AddButton" Icon="Add" x:Uid="Añadir" Foreground="{StaticResource RedBrush}" Click="AddButton_Click"/>
            </CommandBar.PrimaryCommands>
            <CommandBar.SecondaryCommands>
                <AppBarButton x:Name="Btndelete" Icon="DeLete" x:Uid="BorrarTodo" Foreground="{StaticResource RedBrush}" Click="DeleteButton_Click"/>
            </CommandBar.SecondaryCommands>
        </CommandBar>

        <Grid 
            Grid.Row="1" 
            Background="White" x:Name="Content">`

**Comment by sibille** [comment]
If you want to see the commandbar at the same height as the title, you should add it to the shell page as described in documentation. If you need to add it to the page, you can set NavViews AlwaysShowHeader property to false, to hide the header and add your own header and commandbar to the page.

We're also studying if we could have a documentation on how to dynamically insert commands from a page to the shell command bar. 


(Si quieres ver la command bar al mismo nivel que el titulo deberías añadir la command bar al HeaderTemplate de la pagina Shell. Si necesitas que esté en la pagina, puedes poner la propiedad AlwaysShowHeader a false, y añadir tu propio Header y commandbar en la pagina. 

Estamos mirando si podemos añadir un apartado en la documentación sobre como dinámicamente insertar comandos desde una pagina al command bar de la shell.)

**Comment by Javier118** [comment]
Where would this AlwaysShowHeader

**Comment by Javier118** [comment]
arreglado.

**Comment by mrlacey** [comment]
comment above says this should be closed. so closing it.
