### ISSUE TITLE
Suspend/resume with Caliburn Micro: resume handler not invoked

### ISSUE THREAD

**Issue by Myrmex** [Microsoft/WindowsTemplateStudio#2255]
I am trying to implement a scenario where my UWP app using Caliburn Micro should let its viewmodels save and restore data (e.g. page number and size) whenever suspending and resuming; this follows the pattern I discussed in <https://github.com/Microsoft/WindowsTemplateStudio/issues/1522>. Yet, it seems I'm doing something wrong with respect to the latest template, as I'm able to save on suspend, but my resume code **never gets called**. Thus, no data can be restored.

Here is how I modified the `SuspendAndResumeService.cs` got from your template: essentially, I set two **events for saving and restoring**: `OnBackgroundEntering`, `OnResuming`.

```cs
internal sealed class SuspendAndResumeService : ActivationHandler<LaunchActivatedEventArgs>
{
    private const string STATE_FILENAME = "SuspendAndResumeState";

    public event EventHandler<OnBackgroundEnteringEventArgs> OnBackgroundEntering;
    // >>> added by myself
    public event EventHandler<OnBackgroundEnteringEventArgs> OnResuming;

    public async Task SaveStateAsync()
    {
        var suspensionState = new SuspensionState()
        {
            SuspensionDate = DateTime.Now
        };

        // invoke the background entering event so that subscribers can store their
        // state into the state object got from the event's argument.
        Type target = OnBackgroundEntering?.Target.GetType();
        OnBackgroundEnteringEventArgs onBackgroundEnteringArgs =
            new OnBackgroundEnteringEventArgs(suspensionState, target);

        OnBackgroundEntering?.Invoke(this, onBackgroundEnteringArgs);

        await ApplicationData.Current.LocalFolder.SaveAsync(STATE_FILENAME, onBackgroundEnteringArgs);
    }

    protected override async Task HandleInternalAsync(LaunchActivatedEventArgs args)
    {
        await RestoreStateAsync();
    }

    protected override bool CanHandleInternal(LaunchActivatedEventArgs args)
    {
        return args.PreviousExecutionState == ApplicationExecutionState.Terminated;
    }

    private async Task RestoreStateAsync()
    {
        OnBackgroundEnteringEventArgs state = await ApplicationData.Current.LocalFolder
            .ReadAsync<OnBackgroundEnteringEventArgs>(STATE_FILENAME);

        // >>> added by myself
        OnResuming?.Invoke(this, state);

        if (state?.Target != null)
        {
            var navigationService = IoC.Get<INavigationService>();
            navigationService.NavigateToViewModel(state.Target, state.SuspensionState);
        }
    }
}
```

Then, each VM which should keep its state **subscribes** to those events, like (in the constructor):

```cs
Helpers.Singleton<SuspendAndResumeService>.Instance.OnBackgroundEntering
    += OnBackgroundEntering;
Helpers.Singleton<SuspendAndResumeService>.Instance.OnResuming
    += OnResuming;
```

These methods are implemented like:

```cs
private void OnBackgroundEntering(object sender, OnBackgroundEnteringEventArgs e)
{
    e.SuspensionState.Data[STATUS_KEY] = new MainViewModelState
    {
        PageNumber = _pageNumber,
        PageSize = _pageSize,
        // etc...
    };
}

private void OnResuming(object sender, OnBackgroundEnteringEventArgs e)
{
    Debug.WriteLine($"Resuming state for {nameof(MainViewModel)}");

    if (!e.SuspensionState.Data.ContainsKey(STATUS_KEY) ||
        !e.SuspensionState.ShouldResume()) return;
    MainViewModelState state = (MainViewModelState)
        e.SuspensionState.Data[STATUS_KEY];

    _pageNumber = state.PageNumber;
    _pageSize = state.PageSize;
    // other stuff here, including call to code rebuilding state from restored parameters...
}
```

Could anyone suggest me what's missing here so that `OnResuming` handlers effectively get called?

**Comment by crutkas** [comment]
paging @nigel-sampson

**Comment by nigel-sampson** [comment]
@Myrmex is it possible for you to create a new app from WTS with your changes applied to share with me. Will help a lot in trying to diagnose the problem.

**Comment by Myrmex** [comment]
Thank you, of course I can do it, here it is: <https://1drv.ms/u/s!AsHCfliT740PkPRAN9rOmPmYrhAN1g>. Just unzip and open the solution. I created it by selecting Pivot navigation, Caliburn Micro, and using a single blank page plus a settings page.

I changed only these files:

- `SuspendAndResumeService.cs`
- `SuspensionState.cs`

I then added code to subscribe to suspend/resume events in the main VM. This VM has just a label with content equal to its `Message` property, which is initially set to the current date and time. If you launch the app (F5) and then use the `Suspend` command in VS the `OnBackgroundEntering` handler gets called as expected; when you then use the `Resume` command in VS, the app is resumed but `OnResuming` handler never gets called.

**Comment by nigel-sampson** [comment]
Thanks for the sample. 

1. The Suspend and Resume feature doesn't handle resume while the app is running, but resumes it state when the app relaunches after it was Suspended. If you use `Suspend and Shutdown`, then start debugging again the `SuspendAndResumeService` will be invoked.
2. There is however a timing issue here, the event is invoked before the view model is created and subscribed to the event.

Here's a different way we can do this. I've removed `OnResuming` and modified `OnBackgroundEntering` to simply
``` csharp
e.SuspensionState.Data[nameof(Message)] = Message;
```

In `SuspendAndRestoreService` I've modified `RestoreStateAsync` to 
``` csharp
var state = await ApplicationData.Current.LocalFolder
    .ReadAsync<OnBackgroundEnteringEventArgs>(STATE_FILENAME);

if (state?.Target != null)
{
    var navigationService = IoC.Get<INavigationService>();
    navigationService.NavigateToViewModel(state.Target, state.SuspensionState.Data);
}
```
How this works is that the target is the view model / page we want to restore to and we pass the suspension data as the navigation parameter.

CM can take those parameters and map them directly to properties on the view model so you won't need to do the mapping yourself.

**Comment by Myrmex** [comment]
Nigel, thank you very much for this answer!

Anyway, I have some questions: what if I cannot directly bind to my VM properties? This may happen because any of these scenarios:

- several VMs have **properties with the same name**: e.g. `PageNumber`, `PageSize`. Thus, I cannot just save them with their raw property name. That's why in my real world code I use a POCO object representing the VM state, and save it under the VM name or any other key which can be granted as unique in the app scope. Of course I could change each VM property name, but this would be a hack, and would make the VMs more obscure and less manageable.

- typically these properties notify their change and this **triggers some actions** in the VM. For instance, in a VM with both `PageNumber` and `PageSize`, changing any of the two would trigger a data request to the server. Now, if I am restoring I would not want to trigger 2 requests just because I'm updating both values one after another. Probably, here a specific VM method to invoke when restoring would be easier and more efficient; it would be able to examine all the restored values at once (from a POCO object in the dictionary), and act accordingly, thus optimizing the restore process and avoiding clashes.

- it might be the case that some inner parameter used in the restore process is **not directly exposed** as a VM public property. In this case, I would have no way of getting its value back, unless "polluting" my VM with unnecessary (and otherwise encapsulated) properties coming from the internals of my class.

Unfortunately I'm hitting these issues right now in my real-world app, where I have several VMs which get their data from services, according to user-selected parameters. I'd like to save these parameters when entering background, and then get them back when resuming, so my VM code can request data from the server again and fill its view accordingly. It's not like restoring the `Message` property in my dummy sample; it's more like triggering some code when restoring, which given some input parameters knows what to do to retrieve data and update the VM accordingly.

What would you suggest for such scenario?
Thanks again!

**Comment by nigel-sampson** [comment]
1. Bit confused what you mean by same name here. Sorry.
2. You could separate the properties bound to the view from the ones being populated by the resumed state. In fact you could do something like
`` csharp
e.SuspensionState.Data[nameof(PagingState)] = new PagingState { PageSize = PageSize, PageNumber = PageNumber };
```
where the resumption populates a POCO exposed on the view model.  One the view model is activated you can then use that resumed the data including populating the view bound properties.  CM will look for a property called Parameter that it will populate with the dictionary if nothing else.

The framework currently doesn't support calling a method on navigation / populating navigation state.  If you really wanted to avoid using navigation properties then you could replace the navigation service with how you want to do that. Happy to walk you though that.

Hope this helps.

**Comment by Myrmex** [comment]
Thanks again, I'm trying the following solution, maybe this is helpful for others (unless you have any doubt about it in relation to the framework; in this case please let me know).

1.`SuspensionState.cs`: I just added some helper methods, nothing fancy here:

```cs
public sealed class SuspensionState
{
    public Dictionary<string, object> Data { get; }

    public DateTime SuspensionDate { get; set; }

    public SuspensionState()
    {
        Data = new Dictionary<string, object>();
    }

    public SuspensionState(Dictionary<string, object> data)
    {
        Data = data ?? new Dictionary<string, object>();
    }

    public bool ShouldResume()
    {
        return Data.Count > 0 && (DateTime.Now - SuspensionDate).TotalDays < 7;
    }

    public T TryGet<T>(string key, T defaultValue)
    {
        return Data.ContainsKey(key) ? (T)Data[key] : defaultValue;
    }
}
```

2.`SuspendAndResumeService.cs`: I paste the relevant code only. Note that when restoring I always navigate to my main VM (`MainViewModel`), as this is the VM I elected for holding the suspension state of the *whole app*. This is required because I'm going to let CM automatically map the suspension state to its `State` property. To this end, I wrap the `SuspensionState` object into a new dictionary with a unique key, `State`:

```cs
public async Task SaveStateAsync()
{
    var suspensionState = new SuspensionState()
    {
        SuspensionDate = DateTime.Now
    };

    Type target = OnBackgroundEntering?.Target.GetType();
    OnBackgroundEnteringEventArgs onBackgroundEnteringArgs =
        new OnBackgroundEnteringEventArgs(suspensionState, target);

    OnBackgroundEntering?.Invoke(this, onBackgroundEnteringArgs);

    await ApplicationData.Current.LocalFolder.SaveAsync(STATE_FILENAME, onBackgroundEnteringArgs);
}

private async Task RestoreStateAsync()
{
    OnBackgroundEnteringEventArgs state = await ApplicationData.Current.LocalFolder
        .ReadAsync<OnBackgroundEnteringEventArgs>(STATE_FILENAME);

    var navigationService = IoC.Get<INavigationService>();
    navigationService.NavigateToViewModel(typeof(MainViewModel),
        new Dictionary<string, object> { ["State"] = state.SuspensionState });
}
```

Also, I enforce the stateful nature of all my VM which must save and restore their state by letting them implement `IHasState`:

```cs
public interface IHasState
{
    void GetState(SuspensionState state);
    void SetState(SuspensionState state);
}
```

3.my `MainViewModel.cs`, which implements `IHasState`, I add the `State` property to be targeted by CM, and methods for writing to the state dictionary or reading from it. I also add a `Resume` method which effectively applies the state to the VM; the `SetState` method limits itself to setting the `State` property, which will be consumed when the VM is initialized (*hopefully this laziness should avoid timing issues*). When this happens, the main VM publishes a `RestoreStateMessage` with the `State` it got from the resume process, and then resumes itself by calling `Resume`:

```cs
private const string STATE_PREFIX = "Main.";

public SuspensionState State { get; set; }

public void GetState(SuspensionState state)
{
    if (state?.Data == null) return;

    // save state like e.g.:
    state.Data[STATE_PREFIX + nameof(PageNumber)] = _pageNumber;
    state.Data[STATE_PREFIX + nameof(PageSize)] = _pageSize;
}

public void SetState(SuspensionState state)
{
    if (state?.Data == null) return;
    State = state;
}

private void Resume()
{
    if (State == null || !State.ShouldResume()) return;

    // apply state to VM, like e.g. (for the ugly Convert see below):
    _pageNumber = Convert.ToInt32(State.TryGet(STATE_PREFIX + nameof(PageNumber), 1L));
    _pageSize = Convert.ToInt32(State.TryGet(STATE_PREFIX + nameof(PageSize), (long)DEFAULT_PAGE_SIZE));
}

protected override void OnInitialize()
{
    base.OnInitialize();

    if (State != null && State.ShouldResume())
    {
        _events.PublishOnUIThread(new RestoreStateMessage(State));
        Resume();
    }
}
```

Note that to avoid names clashes in the state dictionary I'm prefixing each property name with an arbitrary prefix (here `Main.`). This avoids issues when two VMs have the same property name like e.g. `PageNumber`.

3.`RestoreStateMessage.cs` is just a wrapper for the state:

```cs
public sealed class RestoreStateMessage
{
    public SuspensionState State { get; }

    public RestoreStateMessage(SuspensionState state)
    {
        State = state ?? throw new ArgumentNullException(nameof(state));
    }
}
```

4.all the other VMs which require to save/restore implement `IHandle<RestoreStateMessage>`. The handler stores the received state, and a `Resume` method applying it to the VM is called in `OnInitialize`, or directly in the handler if the VM is already initialized:

```cs
public void Handle(RestoreStateMessage message)
{
    _state = message.State;
    if (IsInitialized) Resume();
}
```

At the end of the `OnInitialize` method I call `Resume`, which before applying the state checks if there is any, and it should be applied (in my case I do not want to apply it if a predefined number of days has passed):

```cs
private void Resume()
{
    if (_state == null || !_state.ShouldResume()) return;
    // TODO apply
}
```

For instance, here is the `Resume` method of the `PivotViewModel`, which in my app is the screen conductor:

```cs
private void Resume()
{
    if (_state == null || !_state.ShouldResume()) return;

    int i = Convert.ToInt32(_state.TryGet(nameof(ActiveItem), 0));
    if (i > -1 && i < Items.Count) ActivateItem(Items[i]);
}
```

Note that I have to convert numbers to 32-bit integers, as it seems that when the state object gets serialized, any numeric value becomes a 64-bit value (I suppose this depends on JSON serialization).

5.as for saving state, I'm doing this in the conductor, as it holds all the children VMs. Here I subscribe to the `OnBackgroundEntering` event, and in the handler I save the index of the active item for my pivot, plus the state of all the stateful children VMs. This way the full state of the app will be saved in the unique dictionary.

```cs
public PivotViewModel()
{
    Singleton<SuspendAndResumeService>.Instance.OnBackgroundEntering
        += OnBackgroundEntering;
}

private void OnBackgroundEntering(object sender, OnBackgroundEnteringEventArgs e)
{
    _state = e.SuspensionState;
    _state.Data.Clear();

    // pivot state
    if (ActiveItem != null)
        e.SuspensionState.Data[nameof(ActiveItem)] = Items.IndexOf(ActiveItem);

    // children states
    foreach (Screen item in Items)
    {
        if (item is IHasState stateful)
            stateful.GetState(_state);
    }
}
```

**Comment by Myrmex** [comment]
Sorry, I must add that it seems a new issue is arising on restore: when restoring the app, and navigating to the main VM, all the other VMs in my pivot disappear. Yet, the `Items` collection in the pivot VM is being filled as usual, and the pivot view binds to that collection. Maybe this is a totally different issue (?), so I could make a new post about it, but it would lose some scope. Or I'm just doing something wrong?

**Comment by nigel-sampson** [comment]
The approach you've got looks good, best thing to do is what works and makes sense for you in terms of how you think about the flow of data.

In terms of your second  issue happy to take a look, I can't replicate it so if you show a sample of it I'll dig in.

**Comment by Myrmex** [comment]
Thanks again. Here is a repro: <https://1drv.ms/u/s!AsHCfliT740PkPRF7jc9gkvCru-qqg>. You will see the save/restore mechanism at work, but on restoring only a single page appears in the pivot.

Below I paste the steps for setting up this infrastructure starting from the WTS template.

## Infrastructure

1.`SuspensionState.cs`: replace its code with:

```cs
public sealed class SuspensionState
{
    public Dictionary<string, object> Data { get; }

    public DateTime SuspensionDate { get; set; }

    public SuspensionState()
    {
        Data = new Dictionary<string, object>();
    }

    public SuspensionState(Dictionary<string, object> data)
    {
        Data = data ?? new Dictionary<string, object>();
    }

    public bool ShouldResume()
    {
        return Data.Count > 0 && (DateTime.Now - SuspensionDate).TotalDays < 7;
    }

    public T TryGet<T>(string key, T defaultValue)
    {
        return Data.ContainsKey(key) ? (T)Data[key] : defaultValue;
    }
}

public interface IHasState
{
    void GetState(SuspensionState state);
    void SetState(SuspensionState state);
}
```

2.`SuspendAndResumeService.cs`: `RestoreStateAsync`: pass the state dictionary to the MainViewModel targeting its `State` property:

```cs
private async Task RestoreStateAsync()
{
    var saveState = await ApplicationData.Current.LocalFolder.ReadAsync<OnBackgroundEnteringEventArgs>(StateFilename);
    if (saveState != null)
    {
        var navigationService = IoC.Get<INavigationService>();
        navigationService.NavigateToViewModel(typeof(MainViewModel),
            new Dictionary<string, object> { ["State"] = saveState.SuspensionState });
        // navigationService.NavigateToViewModel(saveState.Target, saveState.SuspensionState);
    }
}
```

3.`MainViewModel.cs`: replace with this code, where the `Message` property is a sample: here we add a `State` property to be used as the target of the navigation in CM, and publish a restore state message when a cached state is found in `OnInitialize`. Thus, when restoring, CM takes care of injecting the state data into `State` and the main VM publishes it to the whole app. It also uses the state itself.

```cs
public class MainViewModel : Screen, IHasState
{
    private const string STATE_PREFIX = "Main.";
    private string _message;
    private readonly IEventAggregator _events;

    public SuspensionState State { get; set; }

    public string Message
    {
        get { return _message; }
        set
        {
            _message = value;
            NotifyOfPropertyChange();
        }
    }

    public MainViewModel(IEventAggregator events)
    {
        Message = DateTime.Now.ToString();
        _events = events;
    }

    protected override void OnInitialize()
    {
        base.OnInitialize();

        if (State != null && State.ShouldResume())
        {
            _events.PublishOnUIThread(new RestoreStateMessage(State));
            Resume();
        }
    }

    public void GetState(SuspensionState state)
    {
        if (state?.Data == null) return;

        state.Data[STATE_PREFIX + nameof(Message)] = _message;
    }

    public void SetState(SuspensionState state)
    {
        if (state?.Data == null) return;
        State = state;
    }

    private void Resume()
    {
        if (State == null || !State.ShouldResume()) return;

        Message = State.TryGet<string>(STATE_PREFIX + nameof(Message), null);
    }
}
```

4.`MainPage.xaml`: add a control to display `Message`:

```cs
<TextBlock Text="{Binding Path=Message}" HorizontalAlignment="Center"
            VerticalAlignment="Center"
            FontSize="24"/>
```

5.`PivotViewModel.cs`: add state store and active item selection resume:

```cs
public class PivotViewModel : Conductor<Screen>.Collection.OneActive,
    IHandle<RestoreStateMessage>
{
    private readonly IEventAggregator _events;
    private SuspensionState _state;

    public PivotViewModel(IEventAggregator events)
    {
        _events = events;
        _events.Subscribe(this);

        Singleton<SuspendAndResumeService>.Instance.OnBackgroundEntering
            += OnBackgroundEntering;
    }

    protected override void OnInitialize()
    {
        base.OnInitialize();

        Items.Add(new MainViewModel(_events) { DisplayName = "PivotItem_Main/Header".GetLocalized() });
        Items.Add(new AlphaViewModel(_events) { DisplayName = "PivotItem_Alpha/Header".GetLocalized() });
        Items.Add(new BetaViewModel(_events) { DisplayName = "PivotItem_Beta/Header".GetLocalized() });
        Items.Add(new SettingsViewModel { DisplayName = "PivotItem_Settings/Header".GetLocalized() });

        Resume();
    }

    private void OnBackgroundEntering(object sender, OnBackgroundEnteringEventArgs e)
    {
        _state = e.SuspensionState;
        _state.Data.Clear();

        // pivot state
        if (ActiveItem != null)
            e.SuspensionState.Data[nameof(ActiveItem)] = Items.IndexOf(ActiveItem);

        // children states
        foreach (Screen item in Items)
        {
            if (item is IHasState stateful)
                stateful.GetState(_state);
        }
    }

    private void Resume()
    {
        if (_state == null || !_state.ShouldResume()) return;

        int i = Convert.ToInt32(_state.TryGet(nameof(ActiveItem), 0));
        if (i > -1 && i < Items.Count) ActivateItem(Items[i]);
    }

    public void Handle(RestoreStateMessage message)
    {
        _state = message.State;
        if (IsInitialized) Resume();
    }
}
```

## Stateful VMs

For each VM which requires its state to be saved:

1. define a key prefix for that VM (here `STATE_PREFIX`) and a `private SuspensionState _state;` member.
2. remember to subscribe the VM to the events aggregator.
3. add `OnInitialize` like:

```cs
protected override void OnInitialize()
{
    base.OnInitialize();
    if (_state != null && _state.ShouldResume()) Resume();
}
```

This will resume the cached state if any.

4. let the VM implement `IHasState` and `IHandle<RestoreStateMessage>`, and add the state handling methods (in this sample we're storing a text message in the state):

```cs
public void GetState(SuspensionState state)
{
    if (state?.Data == null) return;

    state.Data[STATE_PREFIX + nameof(Message)] = _message;
}

public void SetState(SuspensionState state)
{
    _state = state;
}

private void Resume()
{
    if (_state == null || !_state.ShouldResume()) return;

    Message = _state.TryGet<string>(STATE_PREFIX + nameof(Message), null);
}

public void Handle(RestoreStateMessage message)
{
    _state = message.State;
    if (IsInitialized) Resume();
}
```

**Comment by nigel-sampson** [comment]
Sorry about the late reply on this one, slipped through my backlog. Thanks for the repro, made it easier to follow.

It looks to be a simple problem of having the `MainViewModel` hard coded into the `RestoreStateAsync`, switching this to `state.Target` has it restore to `PivotViewModel` correctly.

**Comment by Myrmex** [comment]
Thank you Nigel, the problem was right that I was navigating back to the main VM instead of to the conductor (in my case, the pivot VM). Yet, this implies that I will have to hard-code `typeof(PivotViewModel)` in my restore code, and throw away the restored target type, as I want to always land to the pivot. This is required not only to show the whole UI (=the pivot children), but also because the pivot should be the app state holder. So I'm changing my "recipe" as follows, should I find other issues in my real-world app I'll post again in this thread, hope this will be useful to other readers.

**Recipe for restoring the state of multiple VMs in a conductor like Pivot.**

1.`SuspensionState.cs`: add some helper methods:

```cs
public sealed class SuspensionState
{
    public Dictionary<string, object> Data { get; }

    public DateTime SuspensionDate { get; set; }

    public SuspensionState()
    {
        Data = new Dictionary<string, object>();
    }

    public SuspensionState(Dictionary<string, object> data)
    {
        Data = data ?? new Dictionary<string, object>();
    }

    public bool ShouldResume()
    {
        return Data.Count > 0 && (DateTime.Now - SuspensionDate).TotalDays < 7;
    }

    public T TryGet<T>(string key, T defaultValue)
    {
        return Data.ContainsKey(key) ? (T)Data[key] : defaultValue;
    }

    public int TryGetInt32(string key, int defaultValue)
    {
        return Data.ContainsKey(key) ? Convert.ToInt32(Data[key]) : defaultValue;
    }
}
```

Note the helper method `TryGetInt32`. You should use this to retrieve Int32 numbers, as it seems that when the state object gets serialized, any numeric value becomes a 64-bit value (I suppose this depends on JSON serialization).

2.`SuspendAndResumeService.cs`: I paste the relevant code only. Note that when restoring we always navigate to our pivot VM (`PivotViewModel`), as this is the VM elected for holding the suspension state of the *whole app*. This is required because we're going to let CM automatically map the suspension state to its `State` property. To this end, we wrap the `SuspensionState` object into a new dictionary with a unique key, `State`:

```cs
public async Task SaveStateAsync()
{
    var suspensionState = new SuspensionState()
    {
        SuspensionDate = DateTime.Now
    };

    Type target = OnBackgroundEntering?.Target.GetType();
    OnBackgroundEnteringEventArgs onBackgroundEnteringArgs =
        new OnBackgroundEnteringEventArgs(suspensionState, target);

    OnBackgroundEntering?.Invoke(this, onBackgroundEnteringArgs);

    await ApplicationData.Current.LocalFolder.SaveAsync(STATE_FILENAME, onBackgroundEnteringArgs);
}

private async Task RestoreStateAsync()
{
    OnBackgroundEnteringEventArgs state = await ApplicationData.Current.LocalFolder
        .ReadAsync<OnBackgroundEnteringEventArgs>(STATE_FILENAME);

    var navigationService = IoC.Get<INavigationService>();
    navigationService.NavigateToViewModel(typeof(PivotViewModel),
        new Dictionary<string, object> { ["State"] = state.SuspensionState });
}
```

3.add the `IHasState` interface, used to enforce the stateful nature of all the VMs which must save and restore their state:

```cs
public interface IHasState
{
    void GetState(SuspensionState state);
    void SetState(SuspensionState state);
}
```

4.`PivotViewModel.cs`: add the `State` property to be targeted by CM. In `OnInitialize`, we add the code for publishing the restore state message if a state was received and it should be used for restoring:

```cs
/// <summary>
/// Gets or sets the suspension state for the whole app.
/// </summary>
public SuspensionState State { get; set; }

protected override void OnInitialize()
{
    base.OnInitialize();

	// ... Items initialization code omitted for brevity...

    if (State != null && State.ShouldResume())
    {
        _events.PublishOnUIThread(new RestoreStateMessage(State));
        Resume();
    }
}

private void Resume()
{
	if (State == null || !State.ShouldResume()) return;

	int i = State.TryGetInt32(nameof(ActiveItem), 0);
	if (i > -1 && i < Items.Count) ActivateItem(Items[i]);
}
```

5.add `RestoreStateMessage.cs`. This is just a wrapper for the state:

```cs
public sealed class RestoreStateMessage
{
    public SuspensionState State { get; }

    public RestoreStateMessage(SuspensionState state)
    {
        State = state ?? throw new ArgumentNullException(nameof(state));
    }
}
```

6.all the other VMs which require to save/restore must implement `IHasState` and `IHandle<RestoreStateMessage>`. The handler stores the received state, and a `Resume` method applying it to the VM is called in `OnInitialize`, or directly in the handler if the VM is already initialized. Note that to avoid names clashes in the state dictionary we are prefixing each property name with an arbitrary prefix (e.g. `Main.` for `MainViewModel`, etc.). This avoids issues when two VMs have the same property name like e.g. `PageNumber`.


```cs
public void Handle(RestoreStateMessage message)
{
    _state = message.State;
    if (IsInitialized) Resume();
}
```

At the end of the `OnInitialize` method call `Resume`, which before applying the state checks if there is any, and it should be applied (in my case I do not want to apply it if a predefined number of days has passed):

```cs
private void Resume()
{
    if (_state == null || !_state.ShouldResume()) return;

    // TODO apply state from _state
}
```

7.`PivotViewModel.cs`: add code for saving the app state. The `PivotViewModel` (or other conductor type) does it, as it holds all the children VMs. Here we subscribe to the `OnBackgroundEntering` event, and in the handler we save the index of the active item for the pivot, plus the state of all the stateful children VMs. This way the full state of the app will be saved in the unique dictionary.

```cs
public PivotViewModel()
{
    Singleton<SuspendAndResumeService>.Instance.OnBackgroundEntering
        += OnBackgroundEntering;
}

private void OnBackgroundEntering(object sender, OnBackgroundEnteringEventArgs e)
{
    _state = e.SuspensionState;
    _state.Data.Clear();

    // pivot state
    if (ActiveItem != null)
        e.SuspensionState.Data[nameof(ActiveItem)] = Items.IndexOf(ActiveItem);

    // children states
    foreach (Screen item in Items)
    {
        if (item is IHasState stateful)
            stateful.GetState(_state);
    }
}
```

**Comment by sibille** [comment]
The initial issue seems to be resolved, is that correct @Myrmex? Can we close this and open another one if new issues appear?
