### ISSUE TITLE
Update wizard to framework 4.7.1

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2256]
We need to update the wizard to 4.7.1 to be able to notify static text changes to narrator.

**Comment by mrlacey** [comment]
why?

**Comment by sibille** [comment]
We need the LiveRegionsSupport coming with 4.7.1
https://blogs.msdn.microsoft.com/dotnet/2017/09/21/net-framework-4-7-1-accessibility-and-wpf-improvements/

**Comment by crutkas** [comment]
we need it for accessibility

**Comment by dgomezc** [comment]
We have tried to migrate the projects to .NET Framework 4.7.1 but many references show a warning.

![captura](https://user-images.githubusercontent.com/12777039/40479837-fcf882f6-5f4c-11e8-8348-b54caad61671.PNG)

Investigating why this problem occurs, we have seen that it is a nuget bug, when the library has standard net dependencies ([show bug info](https://github.com/dotnet/standard/issues/481)).

The solution is migrate to PackageReferences. We tried to migrate from packages.json to PackageReferences, but some libraries have installation files .ps1, which are incompatible with PackageReferences ([Package compatibility issues](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference#package-compatibility-issues)). 

More info [here](https://github.com/NuGet/Home/issues/4942).

![image](https://user-images.githubusercontent.com/12777039/40480459-de3c64ac-5f4e-11e8-81a5-8cf488fc341f.png)

We believe that it is better to wait for the nuget team to resolve these incidents before migrating to .NET Framework 4.7.1.

**Comment by sibille** [comment]
Moving to backlog until unblocked

**Comment by sibille** [comment]
Closing as we updated to 4.7.2 as part of https://github.com/microsoft/WindowsTemplateStudio/issues/3701
