### ISSUE TITLE
When trying to delete and item that is a dependency, tell all dependant items

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2257]
1) Create a project with MasterDetail, Grid and Chart page
2) Try to delete SampleData Feature

-> Notification shows only the first dependency but should show all.

**Comment by crutkas** [comment]
unless that person added that item

**Comment by mrlacey** [comment]
> unless that person added that item

Why should that make a difference?

**Comment by crutkas** [comment]
I explicitly added it versus the system. Shouldn’t matter if I removed something

**Comment by mrlacey** [comment]
The issue is that if trying to remove something with multiple dependencies, all dependencies should be listed in the "you can't remove this because dependencies" message. Just listing one is potentially misleading. How would only listing some based on rules about how they were added be better?
