### ISSUE TITLE
Can templates support a wider range of SDK versions?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2285]
Currently WTS only supports generating projects that target the latest and previous 1 SDK versions (AKA "n & n-1")

This raises a couple pf potential issues:
1. Some people would like to be able to target older SDKs too. (e.g. n-2 or older)
2. Some people would like us to provide functionality that is only available in the latest SDK.

The first issue may be something more people may ask for and we're better able to support once WinUI controls are released and also support targegtting older SDK versions.

The second issue could be addressed by having page or feature templates that force an increase in the minimum SDK version of the geenrated project.
Doing this would require that the min version of the generated project is clear prior to creation and that any item that causes a change to the min version is indicated.
Further investigation and research is required to explore this.

X-Ref #335

> MEETING NOTES
> Supporting N / downlevel
> *	Badge features with min level?
>     *	Do mocks for this
> *	Add overview that warns with min version adjustments
> *	Be aware of dependencies that could force min version, not just the primary feature

**Comment by touseefbsb** [comment]
yes once win ui library is released, it would definitely go back to anniversay update and you might be able to support wts templates back to anniversary update.

**Comment by crutkas** [comment]
@touseefbsb there are features that do have hard API dependencies on OS version.  An example will be User Activity API which needs FCU or higher.  Multi-Instance needs April 2018 update or higher ....

**Comment by touseefbsb** [comment]
@crutkas  yes I know that, in that case a warning can be given within the wizard to only choose those features if the developer can deal with dynamically using them with adaptive code, and also the generated code for these services can use adaptive api check and comment on the services as well tht "these services require this specific api version and must be used with precaution and adaptive checks wherever they are used in the app"

**Comment by mrlacey** [comment]
Please note that WinUI does not give an automatic backwards compatibility level of functionality to all controls.
Some controls rely on functionality that is part of the OS and would not be made fully backwards compatible to earlier versions via WinUI.

Also, just because it may be technically be possibel to target older versions does not mean that this is something we will automatically do. When such effort requires additional effort, the cost of that effort must be balanced against the value of reaching a wider user base. Continuing to monitor stats on the number of people using each version will be important.

Also, the work covered by this issue does not rule out using runtime API detection to include newer functionality. It is only functionality that must move the minimum SDK that should do this.

**Comment by mrlacey** [comment]
Noting that WinUI3 should hopefully make this less of an issue.

**Comment by mrlacey** [comment]
Closing as I don't see any value of keeping this open as WinUI and Project Reunion improve version compatibility.
