### ISSUE TITLE
Reference projects we like on main readme

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2288]
Update main readme to add links to associated/partner projects at the bottom of the file.

> MEETING NOTES
> Projects we like
> *	Have a section for projects we like
>     *	Community Toolkit
>     *	Rapid XAML Toolkit
>     *	Do we link dependencies projects?
>         *	json.NET
>         *	Telerik
>         *	MVVM Light
>         *	Caliburn.Micro
>         *	Prism

**Comment by sibille** [comment]
Just did a PR for the first part of this. 
I think we should also add the projects we use as dependencies in generated projects. It'll be useful to have a list of all dependencies we have.
