### ISSUE TITLE
WTS is extracting templates after VS Update 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2291]
X-Ref: #2261

**Comment by sibille** [comment]
This is happening because the template cache is linked to the VS Version number, when you update VS, cache is renewed. Still it might not be necessary to extract the templates again if because they are already in the working folder.  

I'll include code to look for templates in workingfolder and renew the cache based on what's there.

**Comment by mvegaca** [comment]
Checked in Dev-Nightly after update VS to 15.7.3
Templates version: 0.18.18152.1
Wizard version: 0.18.18152.1
