### ISSUE TITLE
CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by maSafdari** [Microsoft/WindowsTemplateStudio#2304]
<p></p>
## For Bugs:
<p>I have got below Error in my WTS project.
**CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)**
</p>
<p></p>
### Repro steps
<p></p>
What did you do? How can someone else reproduce this?
<p></p>

### Actual Behavior
I am using VS 2017 community. Installed WTS vsix. 

<p>Created a simple project, selected Master/View page, Settings, MVVM Light, and that's it.
After opening a class, and other also observed in other forms/template, the error exists. Compile time Error for all the System.XXXX. e.g. int, String, object, etc all shows error.
</p>
What really happened
<p></p>
![image](https://user-images.githubusercontent.com/39573245/40456450-b8954f86-5f06-11e8-82d9-7b3a7c4eeaf4.png)
<p></p>
I also tested .NetStandard Liabrary project. It works when I make it in separate solution. But it gives error as I inserted this in the same solution as WTS project.
<p></p>
![image](https://user-images.githubusercontent.com/39573245/40456564-48a17d5c-5f07-11e8-9dc8-9ce6eb51bb5d.png)

<p></p>
## System

* **VS Version: Visual Studio 2017 Community**<p></p>
* **WTS Wizard Version:**
* **WTS Template Version:**
* **Windows Build:**

**Comment by crutkas** [comment]
did you compile the project?

**Comment by maSafdari** [comment]
Yes, I have compiled the project and the projects I tested before. They give error as below.


<p>Error	CS2001	Source file 'C:\Users\XXXXX\source\repos\App5\App5\obj\x86\Debug\App.g.i.cs' could not be found.	App5

**Comment by crutkas** [comment]
can you share the project / exact repro steps?  what exact build of windows are you on?

**Comment by maSafdari** [comment]
Hi. I am using Surface Pro 4 with below OS info.

<p>
![image](https://user-images.githubusercontent.com/39573245/40533343-ae101d36-6017-11e8-8188-f4940015420d.png)
</p>

**Comment by harvinders** [comment]
@maSafdari  I have seen a similar issue (spent/wasted whole of today), but that seems to me like a visual studio issue. If there is no obj folder/project.assets.json then you could see this issue. 

Also in VS make sure you have both the packge restore option checked. 

![image](https://user-images.githubusercontent.com/8557046/40546050-685be4dc-6071-11e8-8f65-b101363216ff.png)

I had to recreate the whole project from scratch today and later I found that the project.assets.json were slightly different.

Hope this helps.

**Comment by maSafdari** [comment]
@harvinders many thanks for your kind support.

Your method worked and the problem solved.

After creating the project, we need too install or update the following nugets:

1. microsoft.netcore.universalwindowsplatform
2. Newtonsoft.Json
3. Net.NetiveCompilers

and more.


Thanks again. Issue is resolved now.
