### ISSUE TITLE
Update localization docs (in wiki)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2307]
The information in https://github.com/Microsoft/WindowsTemplateStudio/wiki/Localization-Tool and in [the help output from the app](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/code/tools/Localization/Program.cs#L100) is wrong.

the `ext` verb actually takes three parameters `-o`, `-a` & `-s` (`-t` & `-c` are not valid args)

**Comment by sibille** [comment]
Tracked on #2199
