### ISSUE TITLE
Created project is always rebuild in Visual Studio, making testing slow

### ISSUE THREAD

**Issue by vbaderks** [Microsoft/WindowsTemplateStudio#2310]
### Repro steps

1. Create a simple new project with latest Window Template Studio
2. Build solution
3. Build solution again

### Expected Behavior
========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

### Actual Behavior

Solution is rebuild, VS output:
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Visual Studio can cache build output results. This prevents VS to trigger to complete msbuild process. For some reason VS thinks always that the project is out of date and performs a build. 
When creating a basic C# UPW app, VS works as expected and no rebuild is done.

Note: I have been unable to find the root cause of the problem (often a reference to a file that doesn't exist)

## System

* **VS Version:** 15.7.2
* **WTS Wizard Version:** 2.1.18124.1
* **WTS Template Version:** ? 
* **Windows Build:** 1803

**Comment by vbaderks** [comment]
The generated .csproj has for some .xaml files also a copy step, removing these copy step solves the rebuild problem:

For example:
    <Page Include="Styles\_Colors.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>

Remove CopyToOutputDirectory for _Colors.xaml, _FontSizes.xaml, _Thickness.xaml and TextBlock,xaml solves my rebuild problem.

Is it save to remove this copy step? (project still compiles fine and runs ok)

**Comment by mvegaca** [comment]
Hi @vbaderks  nice catch! Thank you for helping. Issue is now fixed on #2320

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.18.18152.1
Wizard version: 0.18.18152.1
