### ISSUE TITLE
Review Async methods

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2316]
There are also some PRISM templates that return Task.CompletedTask; rather than awaiting it. This means that method signatures don't match what might be expected. There are also some calls to methods with names ending 'Async' which aren't awaited. This breaks expectations on naming and calling conventions.

X-ref: #2068

**Comment by milazzom** [comment]
@sibille Is there a branch I can reference for this item?  Thanks!

**Comment by sibille** [comment]
@milazzom, yes, it's implemented in the branch https://github.com/sibille/WindowsTemplateStudio/tree/issue2316_reviewasyncmethodsinprism and I did PR https://github.com/Microsoft/WindowsTemplateStudio/pull/2429

**Comment by milazzom** [comment]
@sibille The changes look good to me.

**Comment by sibille** [comment]
thanks @milazzom

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.18.18212.1
Wizard version: 0.18.18212.1
