### ISSUE TITLE
User Feedback: user didn't realize need to confirm adjustable named item

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#233]
User went through the wizard with multiple items selected.  They didn't click the "check" after clicking the +.  They completed the wizard but left multiple pages and background tasks in a limbo state without realizing it.

One idea to solve this would be to throw a warning.

**Comment by crutkas** [comment]
yeah but how do i know that i didn't fully submit the prior one?  I need to poke at the June branch.

**Comment by mvegaca** [comment]
I've just fixed this issue on dev branch. Now one single item can be editing at the same time. Issue labeled as "Can Close Out Soon"

**Comment by ralarcon** [comment]
Verified in nightly build 0.14.17146.65001.
