### ISSUE TITLE
Help/About details are incorrect

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2332]
The extension details are incorrectly specified in the code and cause it to be displayed incorrectly.

![image](https://user-images.githubusercontent.com/189547/40865709-a035cc94-65f1-11e8-87ba-ff0ec0adcc0a.png)

Honestly, this is the WTS entry.

This is because of the settings here:

![image](https://user-images.githubusercontent.com/189547/40865745-d4399fca-65f1-11e8-8bf9-9ec4fb53539f.png)

The text comes from a resource file that has the wrong values but these wrong values have been translated.
e.g.
![image](https://user-images.githubusercontent.com/189547/40865797-31d21504-65f2-11e8-8529-086eb473a9d3.png)

We not only need to correct the RESX files, but the attribute needs updating with the correct version number.
Need to determine if there's a way to automatically pick up the version number without duplicating it in the attribute or look at ways of automating updating it as part of a release.

**Comment by sibille** [comment]
Will have a look at this!! Version number has to be set on build as that's where the number comes from.

**Comment by sibille** [comment]
I grabbed the correct name and description from localized vstemplate files, so no translation is necessary.
![image](https://user-images.githubusercontent.com/24698018/40911698-d516ada2-67ef-11e8-869c-52c0d3dbeff7.png)

**Comment by mvegaca** [comment]
Check fixed
Templates version: 0.18.18157.1
Wizard version: 0.18.18157.1
