### ISSUE TITLE
Include Platform Specific Analyzer as an option

### ISSUE THREAD

**Issue by hermitdave** [Microsoft/WindowsTemplateStudio#2334]
## For new Features:

* **Overview:** What you'd think should be added with scenarios
Windows Toolkit v3.0 shipped with many additions including Platform Specific Analyzer. This supports not just platform specific but also version specific type checks to warn the developer and offer basic fix for the issues. This would result in less run time errors.

* **Links:**
https://docs.microsoft.com/en-us/windows/uwpcommunitytoolkit/platform-specific/platformspecificanalyzer
https://docs.microsoft.com/en-gb/windows/uwp/debug-test-perf/version-adaptive-code

### Repro steps

What did you do? How can someone else reproduce this?

### Expected Behavior

What was expected to happen
(include screenshots if a visual issue)

### Actual Behavior

What really happened

## System

* **VS Version:**
* **WTS Wizard Version:**
* **WTS Template Version:**
* **Windows Build:**

**Comment by mrlacey** [comment]
We could add "Developer Tools" to the features list and include this there, but there are a couple of issues with the analyzer I'd want to see addressed before we considered this.

- https://github.com/Microsoft/WindowsCommunityToolkit/issues/2206 
- https://github.com/Microsoft/WindowsCommunityToolkit/issues/2207

Addressing the first issue would be essential before we could add this as it incorrectly flags the code we generate as needing extra version checks when it doesn't. If we added the analyzer as it is now, we'd be generating code which includes warnings, but this is something we don't want to do.

I understand that the second is more complicated to address but with beginner developers using WTS, I want to avoid support issues from people saying "we used the tools provided by WTS and followed the suggestions and now the code won't compile."


Also, this wouldn't be a page or feature in the way that everything else we allow adding to the generated app is, but making this a "feature" seems the easiest way to add it.
Putting a "Developer Tools" section at the end of the Features page feels more desirable than have it mixed with other features but this would require changing the order of feature groups to not be sorted alphabetically.

**Comment by mrlacey** [comment]
Community toolkit issues that were preventing this have been closed as inactive. Reading as not going to fix, so closing this. 
Can reopen if the external issues are ever addressed.

**Comment by crutkas** [comment]
@nmetulev any chance those issues would be worked on?

**Comment by nmetulev** [comment]
ping @michael-hawker for triage

**Comment by michael-hawker** [comment]
Sorry @mrlacey, our bot is a bit aggressive, I may look into increasing our timeout a bit.  I've added some comments and re-opened those issues to see if we can get new traction on them, it'd be good to see this helper have an easier install path via WTS.  I've also created a new label for toolkit issues for `Windows Template Studio`.
