### ISSUE TITLE
Link Moved

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2336]
The following link in the generated code was moved and it should be fixed in templates.
[https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/08/quickstart-sending-a-local-toast-notification-and-handling-activations-from-it-windows-10/](https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/08/quickstart-sending-a-local-toast-notification-and-handling-activations-from-it-windows-10/)

We could have more links with the same problem.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18157.1
Wizard version: 0.18.18157.1
