### ISSUE TITLE
DataGrid page templates does not display SymbolIcon

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2351]
DataGrid page templates does not display SymbolIcon
![image](https://user-images.githubusercontent.com/5556784/41092659-ae1137b6-6a49-11e8-81bb-02c15cf73c2b.png)

To solve it I propose to add column definitions in control instead of auto-discover properties from source class.
```xml
<tg:RadDataGrid
   x:Name="grid"
   ColumnDataOperationsMode="Flyout"
   AutoGenerateColumns="False"
   ItemsSource="{x:Bind Source}">
   <tg:RadDataGrid.Columns>
      <!--TODO WTS:
      Remove this column definitions and define columns for your data.
      Consider adding header properties to Resources.resw-->
      <tg:DataGridTextColumn PropertyName="OrderId" />
      <tg:DataGridDateColumn PropertyName="OrderDate" />
      <tg:DataGridTextColumn PropertyName="Company" />
      <tg:DataGridTextColumn PropertyName="ShipTo" />
      <tg:DataGridNumericalColumn PropertyName="OrderTotal" />
      <tg:DataGridTextColumn PropertyName="Status" />
      <tg:DataGridTemplateColumn Header="Symbol">
         <tg:DataGridTemplateColumn.CellContentTemplate>
            <DataTemplate x:DataType="models:SampleOrder">
               <FontIcon
                  HorizontalAlignment="Left"
                  Margin="8,0,0,0"
                  FontFamily="{ThemeResource SymbolThemeFontFamily}"
                  Glyph="{x:Bind Symbol}" />
            </DataTemplate>
         </tg:DataGridTemplateColumn.CellContentTemplate>
      </tg:DataGridTemplateColumn>
   </tg:RadDataGrid.Columns>
</tg:RadDataGrid>
```

IMO is a good idea to add it in generated code that shows user how to customize the columns that they want to show in the Grid and personalize the column layout to different property data types.

Any comments or suggestions here?

**Comment by sibille** [comment]
An alternative would be to remove the symbol column from the data that SampleDataService returns to grid pages. 
I prefer what Martin proposes as this shows how to show a symbol column.
This is a production issue, I think we should include the fix in 2.2 version.

**Comment by mrlacey** [comment]
Hasn't the symbol always been displayed like this? (at least since the encoding issue was fixed.)
Adding this to the current release just before shipping would imply a bug. But it's just a change, isn't it?

Adding the column definitions just creates more code to be deleted. Our goal has always been to minimize what we know must be removed. What makes this an exception? Or is that goal no longer valid?

Is showing how to show a symbol column something lots of people will need to do?
If it's appropriate to show how to display a symbol column, what other things might it be appropriate to show as well? Why haven't these been proposed as part of this change also?

Do all these issues apply to both Grid pages, or just the one using the control from Telerik?

**Comment by sibille** [comment]
Happens on both grid pages and I don't know how long this is showing like that, but I think it worked in the past. I think we should either not show the column or apply the datatemplate to show it correctly.

**Comment by sibille** [comment]
Moving to 2.3 to discuss about how to solve.

**Comment by sibille** [comment]
It is code that will get deleted, but I think it's better than showing the rectangle instead of an icon. Master Detail page is wiring up all fields from sample data too.

**Comment by sibille** [comment]
Low pri, moving to 2.4

**Comment by crutkas** [comment]
this is an issue with our template, it should be fixed in this release cycle.  this looks to be pushed back multiple releases as well.  Generated code (templates) should be P0 fixes

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.18.18194.1
Wizard version: 0.18.18194.1
