### ISSUE TITLE
Sample code or not

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2352]
X-ref: #2283
Lets resume positive aspects of each approach and take a decision based on that. (I'm not adding negative aspects as negative points are basically the negation of positive points of the alternative)

Sample code:
Pro: 
	- Testable code
	- Easy to understand/see use of a feature
	- Adapted to concrete framework/projecttype

Documentation: 
Pro: 
	- You only go to documentation if you don't understand how to use the code, once you understood it
	- No code to delete (if you add a lot of features that can be a lot of code to delete)

Would be great to get feedback from the community about what they prefer.

**Comment by crutkas** [comment]
what exactly is being proposed:

- we have sample code in our repository for reference
- we have sample app in the app we generate
- generate app with sample functionally wired up

**Comment by sibille** [comment]
Not sure what's the difference between your option 2 and 3.
Let me give more details on what I was referring to by sample code and documentation options.

Sample code refers to adding sample code to a feature (in the template)  that shows how a feature is used. An example would be what the URI scheme feature does  currently. It's adding a sample page that show when app is invoked with the URI from the sample.
Documentation refers to the feature only adding feature code and have a doc that explains the usage. An example for this would be the Multiview feature.

**Comment by crutkas** [comment]
2. the sample app would ship with the generated app when i generate 
3. the sample code would be fully wired up inside the app that was generated.  No extra sample

**Comment by sibille** [comment]
So 2 would generate two apps when you generate? The problem here is the m*n problem, we would have to have 15+9 sample apps (and growing)

**Comment by sibille** [comment]
The goal is that all features should be easy to use for a developer without generating too much sample code, but just enough to see things working. 

I went through all features, to see which do not (or not fully) work out of the box and found the following:

- DevCenter Analytics
- Web to app link
- SettingsStorage
- Suspend and resume
- Multiple Views
- Background Task
- ShareSource
- ToastNotification (Activation from toast notification)
- Azure Notification (Activation from toast notification)
- Dev Center Notification (Activation from toast notification)
- Live Tile (Activation from live tile)
- Drag and Drop
	
	
Some of them have instructions in the code, some use github docs to explain how to use, and some sample apps in github.
I'll open an issue for each to discuss individually what actions to take on each.

**Comment by crutkas** [comment]
lets create new issues for each.  Lets determine what the proper approach is for each is

**Comment by mrlacey** [comment]
The discussion we had earlier this week was that:

1. Everything that's generated should work (as far as possible) without the need for further effort.
2. Generate working code, not samples.
3. Provide documentation that explains more advanced or alternative scenarios.

In addition to investigating the templates mentioned above, we also need to

- Review the existing [samples](https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/samples) and plan for their removal/replacement.
- Review similar features together. Where there are multiple features that do similar things (such as activation) we should, if possible, have a single way of handling them all.

**Comment by crutkas** [comment]
> 

> The discussion we had earlier this week was that:
> 
> 1. Everything that's generated should work (as far as possible) without the need for further effort.
> 2. Generate working code, not samples.
> 3. Provide documentation that explains more advanced or alternative scenarios.
> 
> In addition to investigating the templates mentioned above, we also need to
> 
> * Review the existing [samples](https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/samples) and plan for their removal/replacement.
> * Review similar features together. Where there are multiple features that do similar things (such as activation) we should, if possible, have a single way of handling them all.

what @mrlacey wrote :)  we have bugs created, we can close this out.
