### ISSUE TITLE
Expose test execution details

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2357]
Expose details of which tests are run as part of the automated tests that happen on the server. The current details are insufficient.

At the moment the front page of the repo says everything is passing.

![image](https://user-images.githubusercontent.com/189547/41180704-f95b36e0-6b66-11e8-9c1f-dc09a7dcc106.png)

However, when running the tests locally I get errors for tests that should be included in what is done automatically. [This](https://github.com/Microsoft/WindowsTemplateStudio/commit/0d36a36932f2c22dce4e798fe210d3ab19f56044) and [this](https://github.com/Microsoft/WindowsTemplateStudio/commit/ce5a1e288538919ac2bc9f24a447a2e2f9d2d3ac) were necessary to fix failing tests that won't have passed for several months.

**Actions**

1.  Expose details of exactly what tests are executed as part of the automated processes. Not a vague description of what is supposed to be run but it should be possible to see a list of all tests that were executed.
2.  Review which tests are actually executed on a regular basis. Ensure that all tests that should be run are.
3. Review how ended up in a situation where not all tests were executed when they should have been and make plans to prevent this from happening again.

**Comment by sibille** [comment]
GenTests are no longer executed during the build, I'll update the information on the docs. 
They only generated the project in contrast to the buildtest that generate and build the projects and were done to get quicker feedback from generations.

As buildtests are now run in parallel they were no longer necessary, as the buildtest build finished before the other. 

You can access build information from the link in the build badge, there is a .md page for every build, that allows you to download the build logs, where you can find the tests executed.

**Comment by sibille** [comment]
@mrlacey, information is updated, can we close this?

**Comment by mrlacey** [comment]
ok
