### ISSUE TITLE
WACK tests fail on 17134

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2358]
Follow on from #2357 

When running the WACK tests on a machine running 10.0.17134.0 (April 2018 update) the tests fail 

> Background tasks cancelation handler
> Error Found: The background tasks cancelation handler validation detected the following errors:
> The app failed to handle background task cancelation. 45140mrlacey.com.mrlaceytest_1.1.2.0_x64__sn79dhp891p9m.
> Impact if not fixed: An app that fails to handle cancelation request to background tasks, which will result in being force terminated. 
> How to fix: Background tasks need to implement cancelation event handler.

This is using **Kit version 10.0.17134.12**

This same error is not reported on a machine running 10.0.16299.0 (Fall Creators Update), even when using the same kit version.

I suspect this is a change to the validation rules when running on the latest OS version.

The template code should be changed so the generated code passes WACK tests. 

It's also important to investigate why the server version of this test is reporting successful execution but this fails locally on me for multiple machines.
Adding more details of the test execution and environment for the server run tests may also help with this and any future issues.

**Repro**
- New app (any project type, any framework)
- Add a backgrund task
- Associate app with store
- Build store package
- Run WACK test

or

- Run test `WindowsAppCertKitTests.RunWackOnProjectWithAllPagesAndFeaturesAsync`

**Comment by sibille** [comment]
Tests fail on some machines but work on others. They used to fail on the build machine and now the succeed. 
I reviewed the background task code, and the cancel event is wired up correctly. I saw that the OnCanceled eventhandler does not have code, we should set _cancelRequested = true; here. But despite setting this, tests still fail. (will do a PR for this)
@crutkas, is there someone from the wack team that could give us more insight on why those tests fail on some machines and others not?

**Comment by crutkas** [comment]
any eta?

**Comment by sibille** [comment]
whats eta?

**Comment by sibille** [comment]
After a system update, wack tests are failing now on server too. Will have a look at this.

**Comment by sibille** [comment]
Had a look at this and the background task is wired up correctly, out of 20 tries I got 2 passed results. Need more insight on what this is testing exactly to investigate this.

**Comment by sibille** [comment]
We'll exclude the background task from WACK tests and reinclude them once WACK is fixed.

**Comment by sibille** [comment]
Wack tests are running fine now
