### ISSUE TITLE
TreeView Navigation

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2363]
**Feature Request**

new treeview control based navigation as an alternate to NavigationView and Pivot navigation. ofcourse it will be a bit different because it will support nested pages navigation, but I just had this idea so I thought I should share it as it can be useful for many kinds of apps.

**Comment by crutkas** [comment]
We have discussed this for master detail and possible as a navview view as well.  Right now our next major pattern will be menu bar. 

Do you have an idea for how you were thinking this would work / look?

**Comment by touseefbsb** [comment]
yeah I just found out this brilliant blog of the implementation I hope this is helpful :) https://xamlbrewer.wordpress.com/2018/06/08/using-a-treeview-control-for-navigation-in-uwp/

**Comment by mrlacey** [comment]
Would a master/detail style page be a suitable intermediary step?
It could be the same as the current master/detail page but with the treeview instead of the master list.

I'm not sure how we'd provide anything generally applicable for a treeview based top-level navigation solution. Does anyone use a treeview for general, top-level navigation? What scenarios is it appropriate for?

**Comment by touseefbsb** [comment]
@mrlacey  if you look at traditional Desktop file explorer and notice its left pane it is a tree view. This is first example I could think of. Basically will be used if the app required scenarios like file explorer or nested sub pages.

**Comment by crutkas** [comment]
On reflection, this requires actual use cases and i would ask for a spec for how the interaction model would work. If we were to move forward, there would be a large work item on the wizard as well to support moving and nesting.

The only instances i can think of a tree view navigation is when the navigated page remains same content, not with different pages.  This would put it in line with a master-detail, not a new navigation paradigm.  We have an open item for a tree view based master detail (#1246) too

**Comment by mdtauk** [comment]
Wouldn't you put a Treeview control, into a SplitView - Master/Detail view, and then fire up the selection changed event?

**Comment by crutkas** [comment]
@mdtauk We need to currently focus on the scenario / use case based here, not implementation.  It is unclear scenarios where this would be used and exactly how.  Doing implementation before knowing the scenarios we're solving causes bad implementations

**Comment by mdtauk** [comment]
Well from the use case put forward, a **File Explorer** scenario, clicking on a folder would navigate the Icon View to that folder, displaying the contents.  Clicking on a folder containing folders, would navigate and expand the tree-view.

Master Detail views navigate one pane when an item selection is made.  So my question was basically does that File Explorer implementation require a new control, or could using an existing panel/layout control with a TreeView achieve the same thing.

What about doing it like that wouldn't work, is there a use case where you need something to work in a way that can't be done with a control in a control?

**Comment by crutkas** [comment]
@mdtauk that is a master detail page, not a holistic new navigation paradigm with different pages inside the master list.  The detail page doesn't change.  Which would put it inside #1246 and to do file explorer, it would be a blank app w/ #1246 as the only page.

Also, it still is unclear what is the application scenario use cases here are.  This item implies a master tree view with multiple different pages that could be nested somehow that causes the detail page to change to it.

**Comment by mdtauk** [comment]
@crutkas  That was my view on the suggestion.  Something that would be covered by putting a TreeView into an existing control.

**Comment by mrlacey** [comment]
Allowing people to build a new version of a file explorer isn't a good use of WTS. THere's already one in the box ;)
Or do lots of apps use a file explorer as part of wider app functionality? It's not something I've seen.

**Comment by crutkas** [comment]
Then this is #1246.
