### ISSUE TITLE
IoT-Core UWP Supported by Windows Template Studio?

### ISSUE THREAD

**Issue by PtwHub** [Microsoft/WindowsTemplateStudio#2367]
I could not find an answer to this anywhere, perhaps because IoT-Core does support UWP so is certainly supported by the Windows Template Studio. Can you confirm and perhaps point to a sample. Thanks!

**Comment by crutkas** [comment]
It should, we don't do anything such as directly reference the IoT extension but it should be fine for a foreground application.  Just like working on an xbox, it should just work.

Are you seeing an issue?  If so, please reopen.

https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/buildingappsforiotcore
