### ISSUE TITLE
Wizard doesn't respect Visual Studio theme

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#238]
It looks fine with 'Blue' and 'Light' themes but looks wrong in 'Dark' theme.

Should support the Visual Studio selected theme.

**Comment by mrlacey** [comment]
Moving to 1.3 as this falls under accessibility. (If someone can only use VS in one theme because of visual issues then that makes this an accessibility issue.)

**Comment by crutkas** [comment]
Should we be VS theme or Windows theme?

**Comment by mrlacey** [comment]
> Should we be VS theme or Windows theme?

The wizard should match the VS theme. It's running as a part (extension) of VS.

**Comment by crutkas** [comment]
high contrast setting trumps everything.  With that said, VS forces high contrast and cannot be turned off if Windows is in high contrast.

**Comment by crutkas** [comment]
is this a realistic 1.3 workitem?

**Comment by mrlacey** [comment]
> is this a realistic 1.3 workitem?

Not if it doesn't have to be.

**Comment by mrlacey** [comment]
Is it worth delaying this until the big UI redesign?

**Comment by crutkas** [comment]
No matter what we need to know how.  But yes IMO this can wait

Redesign is more of a polish :)

**Comment by ralarcon** [comment]
Moving to backlog as it looks that this make sense to be acomplished at the same time as UI redesign.

**Comment by mvegaca** [comment]
New Wizard redesign is taking Colors, font sizes and font family from Visual Studio in VS Extension and from a Light Theme static collection in VS Emulator. The status of the new Wizard can be checked on #875.

Closing this issue in favor of #875.
