### ISSUE TITLE
RadCartesianChart.Grid not visible with Dark Theme

### ISSUE THREAD

**Issue by codingdna2** [Microsoft/WindowsTemplateStudio#2385]
### Repro steps

When I configure a Telerik Chart Control to show the axis grid, the grid is visible only with the Light theme and not with the Dark one. This is probably a continuation of issue  https://github.com/Microsoft/WindowsTemplateStudio/issues/808. Following is the XAML I've used to test it. Can someone please advise on how to fix it?
Thanks in advance

    <Grid Background="{ThemeResource SystemControlPageBackgroundChromeLowBrush}">
        <tc:RadCartesianChart x:Name="ChartScatterLine" PaletteName="DefaultLight">
            <tc:RadCartesianChart.HorizontalAxis>
                <tc:LinearAxis MajorStep="1.0" TickThickness="0" Foreground="{ThemeResource SystemControlForegroundBaseHighBrush}">
                    <tc:LinearAxis.LineStyle>
                        <Style TargetType="Line">
                            <Setter Property="Stroke" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                        </Style>
                    </tc:LinearAxis.LineStyle>
                    <tc:LinearAxis.MajorTickStyle>
                        <Style TargetType="Rectangle">
                            <Setter Property="Fill" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                        </Style>
                    </tc:LinearAxis.MajorTickStyle>
                </tc:LinearAxis>
            </tc:RadCartesianChart.HorizontalAxis>
            <tc:RadCartesianChart.VerticalAxis>
                <tc:LinearAxis TickThickness="0" Foreground="{ThemeResource SystemControlForegroundBaseHighBrush}" >
                    <tc:LinearAxis.LineStyle>
                        <Style TargetType="Line">
                            <Setter Property="Stroke" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                        </Style>
                    </tc:LinearAxis.LineStyle>
                    <tc:LinearAxis.MajorTickStyle>
                        <Style TargetType="Rectangle">
                            <Setter Property="Fill" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                        </Style>
                    </tc:LinearAxis.MajorTickStyle>
                </tc:LinearAxis>
            </tc:RadCartesianChart.VerticalAxis>
            <tc:RadCartesianChart.Grid>
                <tc:CartesianChartGrid MajorLinesVisibility="XY" />
            </tc:RadCartesianChart.Grid>
            <tc:RadCartesianChart.SeriesProvider>
                <tc:ChartSeriesProvider Source="{x:Bind ViewModel.Source}">
                    <tc:ChartSeriesProvider.SeriesDescriptors>
                        <tc:ScatterSeriesDescriptor ItemsSourcePath="Points" XValuePath="XValue" YValuePath="YValue">
                            <tc:ScatterSeriesDescriptor.Style>
                                <Style TargetType="tc:ScatterLineSeries">
                                </Style>
                            </tc:ScatterSeriesDescriptor.Style>
                        </tc:ScatterSeriesDescriptor>
                    </tc:ChartSeriesProvider.SeriesDescriptors>
                </tc:ChartSeriesProvider>
            </tc:RadCartesianChart.SeriesProvider>
        </tc:RadCartesianChart>

## System

* **VS Version:** 15.7.4
* **WTS Wizard Version:** 2.2
* **WTS Template Version:** 2.2
* **Windows Build:** 1803 (build 17134.112)

**Comment by mrlacey** [comment]
@codingdna2 can you share your VM too so I can reproduce exactly what you're doing?

**Comment by codingdna2** [comment]
My VM is rather complex to post it here. I've reproduced modifying the default ChartPage.xaml (generated by WTS). Just add the following snippet and switch theme to Dark:

            <tc:RadCartesianChart.Grid>
                <tc:CartesianChartGrid MajorLinesVisibility="XY" />
            </tc:RadCartesianChart.Grid>

This is the result with the Light Theme:
![image](https://user-images.githubusercontent.com/6033635/41770450-8a29c924-7612-11e8-8324-035c5df4215d.png)

And this is the result with the Dark Theme:
![image](https://user-images.githubusercontent.com/6033635/41770468-9746f7e4-7612-11e8-8034-f4db5f76855b.png)

The grid is barely visible but it's there. Let me know if you need additional informations.

**Comment by mrlacey** [comment]
So, this (just like #808) is due to the way the Telerik controls use resources. 
The underlying way theme resources are treated changed with the Creators Update and this stopped them working the same way in apps. As Telerik's control supports older versions of Windows10 it still uses the old technique and they are waiting on Microsoft to change something to resolve the issue. (I don't know what this would be, when it might happen, or if it would help anyone running a shipped version of WIndows10 after the Anniversary Update.)

I've followed up with Telerik on their [open issue](https://github.com/telerik/UI-For-UWP/issues/147#issuecomment-399415943) about this.

For now, you can work around this by styling the lines yourself. The code below should be what you want.

```xml
    <tc:RadCartesianChart.Grid>
        <tc:CartesianChartGrid MajorLinesVisibility="XY">
            <tc:CartesianChartGrid.MajorXLineStyle>
                <Style TargetType="Line">
                    <Setter Property="Stroke" Value="{ThemeResource SystemControlBackgroundBaseLowBrush}"/>
                    <Setter Property="StrokeDashArray" Value="4, 2"/>
                </Style>
            </tc:CartesianChartGrid.MajorXLineStyle>
            <tc:CartesianChartGrid.MajorYLineStyle>
                <Style TargetType="Line">
                    <Setter Property="Stroke" Value="{ThemeResource SystemControlBackgroundBaseLowBrush}"/>
                    <Setter Property="StrokeDashArray" Value="4, 2"/>
                </Style>
            </tc:CartesianChartGrid.MajorYLineStyle>
        </tc:CartesianChartGrid>
    </tc:RadCartesianChart.Grid>
```

Which produces this:

![image](https://user-images.githubusercontent.com/189547/41775216-f9e60f4a-761a-11e8-8ef6-da2899a44e06.png)

and

![image](https://user-images.githubusercontent.com/189547/41775224-01e1ea34-761b-11e8-81f8-9e07c3ccb5fc.png)

**Comment by codingdna2** [comment]
Perfect thanks, issue closed for me.
