### ISSUE TITLE
Review unit tests and code coverage

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2398]
Running minimum and rightclickWithLegacy tests code coverage for templates.core.dll is at 78%. Review what is not covered and do more tests.

**Comment by sibille** [comment]
Moved to 3.0 as this is work is ongoing

**Comment by crutkas** [comment]
Lets document which sections need to be done and create individual bugs here.  We're working on this but it dependent where we are currently working on the code.  individual issues will allow us to be more targeted.

once we have the issues created, xref and close this out
