### ISSUE TITLE
Issues with MultiView docs

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2402]
Regarding https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/features/multiple-views.md

The example that walks through how to use the service mentions launching a photo detail page in the intro but there's no other reference to "photo detail" in the rest of the document.

[Section 3](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/features/multiple-views.md#3-open-the-secondary-page-on-a-new-window) includes a code snippet that is supposed to work with code-behind projects but it doesn't because it references `RelayCommand` which does not exist.

While detailing adding a new Command there's nothing in the document that shows where/how this should be used. This means that following the example instructions produces something that doesn't allow the opening of other windows.

[Section 4](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/features/multiple-views.md#4-handle-the-secondarypage-released-event) includes a code snippet that, if using Code-Behind should be added to `SecondaryViewModel.cs` but that file does not exist in a Code-Behind project.

If using a NavigationPane project structure the "SecondaryPage" created in the example will also be included in the NavigationView menu. Launching the SecondaryPage from that menu will result in the app crashing. I would expect this to be addressed in the document.

**Comment by sibille** [comment]
@mrlacey, I think this was fixed as part of https://github.com/microsoft/WindowsTemplateStudio/issues/2829, please reopen if there is any outstanding work here.
