### ISSUE TITLE
Build a separate feature for Theme Selection

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2403]
Currently the ThemeSelectionService comes with the SettingsPage. 
We were thinking about separating this into a separate feature, to allow Multi-View feature, First-Run-Prompt and Whats-New-Prompt to consume the theme from the ThemeSelection Service. (#2387)

This would also allow to add a ThemeSelectionService without a SettingsPage and change the theme in your app based on environment light for example. 

Features that should have a dependency on theme selection feature: 
- Settings Page
- Multi-View feature

**Comment by mrlacey** [comment]
Why do the prompts need this dependency? They currently work fine without it.

**Comment by sibille** [comment]
They work fine, but take the theme from the current window content 

`RequestedTheme = (Window.Current.Content as FrameworkElement).RequestedTheme;`

I think they should get this from the ThemeSelectorService

**Comment by mrlacey** [comment]
The prompts get the theme from the current window content as they are displayed within that context. The prompts never exist separately from the window content and just need to use the same theme. They don't need any of the other functionality that comes with the ThemeService.
I see no benefit to changing this behavior other than adding complexity and an unnecessary dependency.

**Comment by sibille** [comment]
I liked the idea of having a unique point of managing themes, but your right on context and dependencies. 
Will edit the issue and remove dialogs from the list.

**Comment by crutkas** [comment]
i agree with Matt here, the theme service should help keep the windows / app on the right theme.  The prompts should grab it from the window in case something is overridden.

**Comment by mvegaca** [comment]
Checked in Dev
Templates version: 0.18.18241.1
Wizard version: 0.18.18241.1
