### ISSUE TITLE
Add more validations to naming of pages in wizard

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2404]
If a page is named MainPage in the wizard, the generated page will be MainPagePage as templates append "Page" to the specified name. (X-Ref #2362) 

We should: 
- Show error on pages ending with Page
- Show warning if all (renamable) pages end with views

**Comment by sibille** [comment]
This is not high priority, but I'd like to agree on a text for the notification message so we can send it to localization and implement later.

Proposal:
- Page name cannot end with 'Page' as this is the suffix WTS uses on generation. For more info about WTS naming see [here](link)
- Page names should not end with View as WTS appends 'Page' on generation. For more info about WTS naming see [here](link)

**Comment by mrlacey** [comment]
I'd make a couple of tweaks to simplify those suggestions:

- The name cannot end with 'Page' as this will be automatically added. [More info about naming.](link)
- Note that 'Page' will be added to the end of the specified name. [More info about naming.](link)

**Comment by sibille** [comment]
Great, I'll go with those two!

**Comment by sibille** [comment]
Low pri, moving to 2.4

**Comment by sibille** [comment]
A few small things:
- Link on the warning for "View" suffix does not work,
- Order the list of reserved names in the docs alphabetically
- Fix warning SA1633: The file header is missing or not located at the top of the file in PageSuffixValidator.cs

**Comment by mvegaca** [comment]
Link fixed and header added on PR #2522

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18241.1
Wizard version: 0.18.18241.1
