### ISSUE TITLE
Review/Improve guidance for "Settings Storage" feature usage

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2413]
X-Ref #2352
Current status: 
- Does not work out of the box when added individually, but is wired up in SettingsPage, LiveTile, ImageGallery and SuspendAndResume
- Docs in our github: https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/features/setting-storage.md

**Comment by mrlacey** [comment]
This is just a helper class. There's nothing for it to do if installed on its own.

**Comment by crutkas** [comment]
I am leaning to agree with Matt here. I think usage is self documenting since it is hooked into everything when included.

**Comment by sibille** [comment]
Agree, I'm closing this.
