### ISSUE TITLE
Review Prism sample project

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2425]
X-Ref #2294 and #2352 

Review Prism samples, is this still needed?
https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/samples/Prism

**Comment by LeeParrishMSFT** [comment]
These were only used as a starter to get the PRISM concepts into a baseline WTS template, so their usefulness is over. So we can remove them as I don't think there is anything to be learned from them at this point. If we want to integrate a new feature using PRISM we won't go back to these to prototype it, we'd generate a starter PRISM app and go from there.

**Comment by sibille** [comment]
done
