### ISSUE TITLE
Azure is compatible with WTS,

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#2438]
Azure is compatible with WTS, do the Backend with MSA no authenticate, WTS is compatible or there is some incompatibility

**Comment by mrlacey** [comment]
Integration/compatibility with Azure is a broad idea that could cover many different scenarios.
There's nothing fundamentally stopping the creation of an app through WTS that then connects to any external server (hosted on Azure or not.)
We have plans to provide functionality related to Azure connectivity and authentication in the future (e.g. #130 #292 #387 #462) but would be keen to hear more about your specific scenario.

**Comment by crutkas** [comment]
closing this out due to lack of follow up.  we have plans to do some to do some of these items.
