### ISSUE TITLE
Question: Is Unity chosen deliberately as IoC container for Prism projects?

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/WindowsTemplateStudio#2442]
When creating a new WTS project based on Prism, it gets setup with Unity as the IoC container.

Personally I find Unity unpleasant to work with (e.g. its registration methods are quite limited - the way you register a type as singleton in Unity is very unelegant* especially when that class type has dependencies).

Seeing that [Prism also is going to offer an Autofac package](https://www.nuget.org/packages/Prism.Autofac.Windows/7.0.0.336-pre), I'm wondering whether the choice for Unity was deliberate and might be reconsidered?

*example:
In unity, when wanting to register a singleton, you need to call

```csharp
Container.RegisterInstance<ISomeClass>(new SomeClass(Container.Resolve<ISomeDependency>(), Container.Resolve<IOtherDependency>()));
```

In Autofac this would be

```csharp
builder.RegisterType<SomeClass>().As<ISomeClass>().SingleInstance();
```

The discussion of whether wanting to register a singleton is a good practice is off-topic here since this issue is about the design decision for Unity. However my rationale is to create a service that makes a connection to a WebSocket endpoint. I want this service to be used everywhere in the application and I want this service to continue living even when the service consumers (UWP XAML pages) that have this service as a dependency are closed.

**Comment by mrlacey** [comment]
I can't explain the choice of Unity as the IOC container, but I do know we worked with members of the Prism team in developing the template, and they said this was the recommended way to go.

It would be possible to add support for other IOC containers, but before doing so, we would need to balance the demand for this and the amount of effort the change requires.
In turn, this leads to more questions:
- Which containers should be supported? (Do we also need to consider DryIOC, Ninject, others?)
- How much demand for this is there?
- How should this be implemented? (This has UI and internal generator code implications.)

I'll consider this issue a vote for adding AutoFac support but would be keen to hear from anyone else who has thoughts, preferences, or a need for this.

Please also provide any details to help justify making this change. e.g., Is AutoFac just a personal preference or do you have any technical reasons or requirements for using it? Is there anything in the currently generated code that makes it hard to convert it to use another IOC container?

**Comment by wind-rider** [comment]
Thanks for your reply :)

There is no real technical reason (Unity is not broken). The reason for me preferring another framework is the awkward syntax that Unity requires at least for registering single instances.

The reasons for mentioning Autofac are that I have better experiences with that than with Unity and that I noticed that the Prism team is working on a package for that.

My personal favorite for a DI framework (at least syntax-wise) is [Microsoft.Extensions.DependencyInjection](https://msdn.microsoft.com/en-us/magazine/mt707534.aspx) but I do not know whether that works with Prism and UWP. That is another reason for mentioning autofac.

**Comment by wind-rider** [comment]
Also, I see that the autofac package for prism is still in -pre status so maybe at the moment Unity is the way to go.

However for the future I would prefer something else.

**Comment by bartlannoeye** [comment]
Since we were working on a version 7.0 for Prism UWP (still ongoing), the team only implemented Unity as the default container for 6.3 in WTS. I'm not sure if it's already possible to select the IoC container as part of the wizard (@mrlacey), since this would give us the most flexibility (as everyone has its favorite IoC container).

Autofac is being discussed to be dropped (sadly, as I use it myself as primary container) because it is no longer mutable in the latest release. This is an issue for Prism modules. We'll see if we can keep it in, but with the knowledge to the users that it doesn't support modules.

Once we release v 7.0 for UWP, we plan to update the integration in WTS and that's the moment that we can look at multiple IoC containers.

**Comment by wind-rider** [comment]
Nice to hear about the idea of flexibility of IoC containers! I hope that will be maintainable enough. Where would that be on [the roadmap](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/roadmap.md)? I looked there and in the issues but could not find a tracking issue for it.

Pity about Autofac.. I like it, too. However then I'm hoping for [Microsoft.Extensions.DependencyInjection](https://msdn.microsoft.com/en-us/magazine/mt707534.aspx) :)

**Comment by crutkas** [comment]
@bartlannoeye you are more than welcome to take this but lets update the title / be sure we have a clear "what is being asked" and "what we will do" as this sounds more like an improvement request

**Comment by mrlacey** [comment]
side note: Adding the ability to select which IOC container to use with Unity would require UI changes in addition to extra internal logic to handle an extra selection.
The ability to make extra selections related to an item would also apply to other items on the backlog and so would, ideally, need to be done in a way that means anything can have a sub-selection option.

**Comment by bartlannoeye** [comment]
Exactly @mrlacey. I can do the changes required in the templates related to Prism, but for UI - flow related tasks on WTS, I will have to rely on the team. Right now we're in the process of integrating the code of Template 10 and Prism, next step will be write a battery of tests as these are missing in Template 10 and we want to be comfortable to move forward with future changes. I suggest we (Prism team) continue our focus on that first and _I try to come back in a few weeks with a detailed list of changes to be done to WTS to integrate it._

Which doesn't keep us from the replying the first questions and already list changes required in WTS itself to allow sub-selection.

**Question:**
- Can we support multiple IoC frameworks to use with Prism

This is a reasonable question, as Prism supports multiple frameworks out of the box (versus e.g. MVVM Light which brings its own IoC container).

Currently we scaled back to following containers for UWP, we'll have to see if we ramp up to other frameworks already supported on other platforms. If people want more platforms, don't hesitate to help out on the Prism repo (but only for the supported ones, we currently don't accept new ones):

- [ ] Unity
- [ ] DryIoc

Might be an overkill to change WTS for just 2 containers, but I hope this is a start, where we can go back to +- 4 different containers at some point. And if the sub-selection is already required for other backlog items?

@mrlacey will you link the issue with work for sub-selection? I suppose this should be separate from this item.

**Comment by crutkas** [comment]
there are a few items on the horizion that will force us to look at wizard flow.  i can see easy ways to do the UX for this use case.

@bartlannoeye do you have usage for which IoC is used typically?  If one is used 95% of the time and it takes 2 minutes for someone to flip to another, is the wizard work really needed.

**Comment by bartlannoeye** [comment]
@crutkas in short: no.

We only have NuGet metrics, but since a separate package for UWP containers has only been made for Prism 7 (which is not released yet for UWP, so stats are useless). In the past Prism.Autofac (on Windows) pulled in Prism.Windows and everything worked. And then came XF :).

> Prism.Windows has 102k downloads
> Prism.Unity.Windows: 681 (so for Prism 7 only)
> Prism.Autofac.Windows: 403 (so for Prism 7 only, no longer supported even)
> Prism.DryIoc.Windows is only prerelease on MyGet

You could compare the Prism.Unity vs Prism.Autofac, but since this is for all platforms, those stats aren't reliable either.

We are lowering the friction to switch between containers indeed. Maybe we should freeze (or even close) this issue since demand seems rather low (I don't see 50 thumbs up) until we've actually released Prism 7 for UWP (which with our current agendas isn't for next week). It's something we can always pick up at a later time, once the wizard flow has been revisited for other items and we have a better view of the impact.

**Comment by crutkas** [comment]
i'm fine with closing and reopening if demand is there.  I just want to be a bit more data driven

**Comment by hansmbakker** [comment]
@bartlannoeye is [Microsoft.Extensions.DependencyInjection
](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection) being considered as an option?

**Comment by bartlannoeye** [comment]
That's an addition we might consider with the release of .NET Core 3, so we can support it on all platforms including WPF. Right now it's not our focus.

**Comment by crutkas** [comment]
if and when these come online for Prism, lets please reopen this.

**Comment by davidhenley** [comment]
@bartlannoeye an update on considerations for other IOC options?
