### ISSUE TITLE
Review first time project creation

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2454]
When you create a new project on a new machine, nuget restore takes sometimes very long on slow connections. 
Check what we do vs what VS does when you create a new blank project.

**Comment by crutkas** [comment]
big work item, this has multi-project impact so lets spin it for v3

**Comment by sibille** [comment]
Did some tests, and saw that the Microsoft.NETCore.UniversalWindowsPlatform is available locally with VS installation, while we install from nuget. 
Adding the Microsoft.NETCore.UniversalWindowsPlatform nuget to the csproj to see if it is restored from local this way.

**Comment by sibille** [comment]
Although I add the nuget to the csproj file directly it is still downloading from nuget.org. Not sure if we can improve this.

**Comment by sibille** [comment]
Think this is fixed, but we need a Microsoft.NETCore.UniversalWindowsPlatform version available online and offline to verify.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.20.19175.1
Wizard version: 0.20.19175.1
