### ISSUE TITLE
Add test to check that navigating to a page doesn't cause a crash

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2462]
Add automated UI test to verify that can safely navigate to each page without the app crashing.

Tab&Pivot navigation is the priority here as has historically been overlooked in manual testing but would also be good to have NavigationView tests too.

X-Ref #2461 (navigating to a page in a tab/pivot caused app to crash)

**Comment by touseefbsb** [comment]
consider using the preview NavigationView ( winui ) because it has built in pivot view as well, will make implementation a lot simpler.

**Comment by mrlacey** [comment]
Tests merged to dev
