### ISSUE TITLE
Confusing composition filter logic

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2465]
I have seen examples of `compostionFilter` rules which are contradictory or confusing where one part of the rule says something says an item should not be included and another says it should
(such as [here](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/Uwp/_composition/_shared/Page.MediaPlayer.AddNavigation_Blank_SplitView/.template.config/template.json#L13))

`"wts.compositionFilter": "$framework != CodeBehind & $projectType == Blank|SplitView & identity == wts.Page.MediaPlayer|wts.Page.MediaPlayer.CodeBehind"`

This is saying no CodeBehind items but then a specific CodeBehind item should be included.

Having automated checks for such contradictions may be too much effort for little reward but a manual review of all filters may be worthwhile.

**Comment by sibille** [comment]
we'll have a look at this!

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18288.2
Wizard version: 0.18.18288.1
