### ISSUE TITLE
Inconsistencies and issues in new Ink pages

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2470]
The three new Ink pages (Draw, DrawPicture, & SmartCanvas) have some inconsistencies between themselves and other functionality in the generated code.

1. Inconsistent commanding. Draw & SmartCanvas define "commands" as `RelayCommand`. DrawPicture and all other pages and features use `ICommand.`  
For consistency, all should use `ICommand.` If there's a reason why this isn't appropriate or possible this should be documented. 

2. DrawPicture doesn't support Undo/Redo. Draw & SmartCanvas do support this functionality. For consistency, all should support this functionality. If the current inconsistency is due to a limitation of the undo/redo implementation this should be documented. As undo/redo functionality is something that I've heard lots of developers claim is overly complicated and difficult to implement, I expect that many would find it useful if this were made a stand-alone feature (that these pages included as a dependency.) Any limitation of the current implementation would need addressing first.

3. Clear all should not remove the undo stack. Not technically an inconsistency, but this command does not behave as I'd expect. My expectation was for this to act as a combination of "Select All" and "Delete" I did not expect it to remove the contents of the undo stack and can't picture a scenario where doing so is helpful.

4. Commands that are not enabled are not indicated. There's no way to tell, from looking at the UI if the commands can be used, and for those that are not enabled, nothing tells the person using the generated app that nothing has happened as a result of trying to trigger a command. An indication is neither visual or provided in another way. Such a failure is an accessibility issue.

5. Why doesn't InkDrawPicture have the lasso command? (the other pages have this.)

6. Why no, 'Cut', 'Copy', or 'Paste' commands for InkSmartCanvas? (the other pages have these commands.)

7. Why does InkDrawPicture use a non-standard save icon? (and one that's different from the save icon used in the other ink pages?)

8. Why no, 'Zoom in', or 'Zoom out' commands for InkSmartCanvas? (the other pages have these.)

## System

* **WTS Wizard Version: 0.18.18201.1**
* **WTS Template Version: 0.18.18201.1**

**Comment by sibille** [comment]
1. Will change this to use ICommand everywhere

2, 5, 6, 8. Feature inconsistencies: each page contains whats initially most interesting for the pages purpose. We did intentionally not implement everything everywhere to not overload the pages with functionality. As functionality is implemented in services developers can easily add functionality they need from one page to another.  We'll add a table to the docs to show which functionality is implemented where for reference.

3. Clear all was planned as starting a new document, so it's cleaning up everything. We can study to change this and include a undo action for the clear all, but thats a bigger change, lets open a separate issue, get more feedback and plan for 2.4 or 2.5

4. We'll have a look at this one for 2.3

7. We'll change the save icon to the standard save icon.

**Comment by sibille** [comment]
@mrlacey, we've started implementation for enabling/disabling buttons. In PR #2474 you can see the approach we're taking, implementation for Ink Draw Picture is finished.

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.18.18212.2
Wizard version: 0.18.18212.1
