### ISSUE TITLE
BackgroundTask sample

### ISSUE THREAD

**Issue by joshkore** [Microsoft/WindowsTemplateStudio#2475]
Can someone point to me an example of using the BackgroundTask generated by Windows Template Studio please?
I think I need to use the BackgroundTaskService to start a task but I need to see a sample of this. I also notice the Activator class creates one and not sure if I should use the same service instance or not?

When a user clicks a button I wish to start a task.  IS this possible with the generated code?  Or can I sent in data to the running background task?

I need a sample of someone pressing a button and starting the task or feeding information into the task from a button click event.  I think you code assumes the task will start when the app starts but that's not my use case

**Comment by joshkore** [comment]
I think I need to use the BackgroundTaskService to start a task but I need to see a sample of this.  I also notice the Activator class creates one and not sure if I should use the same service instance or not?

**Comment by joshkore** [comment]
I find it insane you wont show us how to use this background service

**Comment by crutkas** [comment]
I wouldn’t use a background service for this, I would use an async method to do that. 

A service is something you want to run typically regularly and when the app isn’t running. 

Did the todo’s not help?  They should have linked you to documentation. 

 are you familiar with c# / uwp programming models?

**Comment by joshkore** [comment]
Yes I know c#, the issue is the app will be creating 100 MB high density images.  We wish to put them into a background task on a button click event because the internet connection will be slow.  this way people can continue to use the app.  They will be making a new image very several images but the image could take 30 minutes to upload.

**Comment by joshkore** [comment]
and your samples folder does not have a backgroundtaskservice sample in it

**Comment by crutkas** [comment]
so you're uploading an image?  you'll actually want to use https://docs.microsoft.com/en-us/windows/uwp/networking/background-transfers, namely https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.BackgroundTransfer.UploadOperation

**Comment by joshkore** [comment]
And can I use this for uploading to Azure Blob Storage.  Also after the image sI have to upload to Azure able storage some meta data for each image.

**Comment by sibille** [comment]
@joshkore, did the docs link help? Based on your question, we're thinking about doing templates for background transfer (download and upload), You can see and comment what we're initially think this feature should do on #2594. Would love to hear your opinion!

**Comment by sibille** [comment]
Moving to 3.0, as we moved #2594 there

**Comment by crutkas** [comment]
we'll do upload / download transfer tasks in 3.1

**Comment by crutkas** [comment]
Closing this one in favor of #2594 which is how someone would download/ upload large files.
