### ISSUE TITLE
Standardize code on Var or class name

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#249]
there is a ton of spots mixing and matching var versus the actual class name.

**Comment by mvegaca** [comment]
I've push 2 commits including var code normalization on madrid-dev branch.
[var code normalization](https://github.com/Microsoft/WindowsTemplateStudio/commit/7e6612b32279c0ecb56a3cab3c0cba22e411d157)
[var code review in src projects](https://github.com/Microsoft/WindowsTemplateStudio/commit/483b093975f41332e62a275bee03b9101ab905e9)

The criteria I have applied is using **var** on self-described names and I also improve name definitions.

**Comment by mrlacey** [comment]
So it's **var** everywhere then.
Any movement on adding something to enforce this?

**Comment by skendrot** [comment]
I love var as long as I know what the type is. As @mrlacey points out, `var input = GetInput();` isn't helpful to know what the type actually is. 

Yes we have Visual Studio and can hover over var, but I view many open source projects online through github or other sites. Seeing `var num = 0;` is fine, but not `var input = GetInput();`

**Comment by ralarcon** [comment]
In my opinion, we can include StyleCop as @mrlacey suggest but we need to rationalize the style applied. We can start by defining the style rules to be applied and then pass over the code to check how far we are...  cc/ @crutkas

**Comment by mrlacey** [comment]
To be clear (and as I think I've said somewhere on here before)
- I am in favor of consistent code structure and formatting, both for the code in the project and the generated code.
- If (when?) we have rules, these should be checked/enforced by tooling. If a manual step they get forgotten.
- I do not think we should include StyleCop (or similar) in the generated project.

**Comment by crutkas** [comment]
Yes, Yes, Yes.  In unit tests, can we run stylecop over a generated project w/ everything checked to see if we throw anything?

**Comment by ralarcon** [comment]
@crutkas @mrlacey for the code in the project we can easily enforce the validation within the build process. Build will not pass if there are violations or something similar.

For the generated project, we can explore the ability to run the tool after the generation and check if there are some violations.

It would be easy to enable the usage of VS Code Analysis with set of rules we like. The execution and reporting would be simple. Anyway I understand StyleCop contains a broad number of coding style rules. Does it make sense to just enforce thru VS Code Analysis?

Passing to action:
@mrlacey it would be helpful if you can aid running the StyleCop tool against the project code and generated code to see how far we are. The sooner we include the enforcement, the better, but we need to check the impact.

@crutkas which rules we would like to apply? and, if we use StyleCop we need to update the Contribution Guidelines.

**Comment by mrlacey** [comment]
I've created a branch with StyleCop analyzer added in all non-test projects
https://github.com/Microsoft/WindowsTemplateStudio/tree/Issue249-StyleCop
Initial commit was just suppressing all the issues (3000+)
Have then added a few commits to address some of the simpler issues in turn. Nothing controversial just adding some code consistency.

Did it this way to allow merging the simpler issues and then can address which policies we want to apply/fix.

**Comment by crutkas** [comment]
enabled via Install-Package StyleCop.Analyzers and put on code analysis w/ recommended rules

I see ~350 with emulator, core, installer, and UI enabled.

Quickly scanning: rulesi don't agree with:

- SA1000
- SA1101
- SA1200
- SA1309

**Comment by mrlacey** [comment]
I'll push back on [SA1000](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md) for these reasons:
- We should be consistent and most of our code does have the recommended spacing.
- Code on docs.microsoft.com follows these spacing guidelines.
- Almost all code I've ever seen follows these spacing guidelines.
- If you do File > New > Blank UWP app, the generated coded follows these spacing guidelines.

Happy to keep suppressions for the other settings you call out though.

Does anyone else want to weigh in before I raise a PR on [the branch](https://github.com/Microsoft/WindowsTemplateStudio/tree/Issue249-StyleCop)?

**Comment by crutkas** [comment]
I'm fine with SA1000, it just raised it for a single item, and in the error listing stated just "foreach" i thought it was a very targetted to just that.

**Comment by mrlacey** [comment]
@crutkas I noted 15 places where it was flagged https://github.com/Microsoft/WindowsTemplateStudio/commit/a330aa77d0032b4d634386195bb055ef01fc9dfe

**Comment by crutkas** [comment]
SA1005 is easy to fix looking in the suppressed list

weird, clearly i'm not doing something you're doing to run this with stylecop as i had to manually turn on stuff and seeing different results.

**Comment by mrlacey** [comment]
Yes, I've already provisionally fixed the SA1005 issues [here](https://github.com/Microsoft/WindowsTemplateStudio/commit/fc08b87d5f26edbc705c1c9f98d44698a65b7bfa)
and as part of the PR

**Comment by ralarcon** [comment]
To enforce the CodeAnalysis rules (StyleCop included) I have added a build configuration to be able to execute CodeAnalysis on build and forced warnings as errors. 

Once the PR is merged to dev and adjusted the build definition, the build will not be success if there are CodeAnalysis warnings, so we will need to be sure that the following commits do not leave any compilation warnings as this will the dev ci build fail.

I'm currently finishing removing the CodeAnalysis warnings.

**Comment by ralarcon** [comment]
No the changes are integrated in dev and the build has been changed to enforce the general & stylecope rules. 

Next step is to investigate how we can leverage the Sytle Cop rules in the generated test projects during the build to apply the same set of rules to the generated code.

**Comment by ralarcon** [comment]
Closing now. Regarding the Sytle Cop rules on generated code follow up in #461
