### ISSUE TITLE
Question - Windows UI Library support

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#2497]
Just want to know if there are any plans to include Windows UI library into future versions of template studio ?

https://docs.microsoft.com/en-us/uwp/toolkits/winui/nuget-packages

thanks in advance.

**Comment by crutkas** [comment]
Yes. We will be moving the navigation view control to that and it will also allow us to use newer controls sooner

**Comment by Pinox** [comment]
thanks @crutkas .
