### ISSUE TITLE
Templates composition does not filter using groupIdentity

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2503]
While working on #2465 I was trying to re-design the filter for template `Feature.ShareTarget.VB`

Old filter
`"wts.compositionFilter": "$framework == MVVMBasic|MVVMLight|CodeBehind & identity == wts.Feat.ShareTarget.VB|wts.Feat.ShareTarget.CodeBehind.VB"`

This template is applyed always that you add a ShareTarget in VisualBasic, this will be the same to use the following filter:
`"wts.compositionFilter": "groupIdentity == wts.Feat.ShareTarget.VB"`

There are only 2 templates with this groupIdentity:

**wts.Feat.ShareTarget.VB**
```xml
"groupIdentity": "wts.Feat.ShareTarget.VB",
"identity": "wts.Feat.ShareTarget.VB",
```
**wts.Feat.ShareTarget.CodeBehind.VB**
```xml
"groupIdentity": "wts.Feat.ShareTarget.VB",
"identity": "wts.Feat.ShareTarget.CodeBehind.VB",
```

When I updated the filter te composition template is added only for MVVMBasic and MVVMLight  frameworks but not for CodeBehind.

I also tryed using framework and group identity filter but it still failing for CodeBehind
`"wts.compositionFilter": "$framework == MVVMBasic|MVVMLight|CodeBehind & groupIdentity == wts.Feat.ShareTarget.VB"`

**Comment by sibille** [comment]
Composition filter identifiers were designed to be all lower case. Tried with "wts.compositionFilter": "groupidentity == wts.Feat.ShareTarget.VB" and worked fine.
