### ISSUE TITLE
Uwp Community Toolkit reference appears two times in Licenses list

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2518]
### Repro steps
Create an app adding all pages and features.

### Expected Behavior
UWP Community Toolkit is added one time

### Actual Behavior
UWP Community Toolkit is added two times

We also have to change from UWP Community Toolkit to Windows Community Toolkit
It looks that also there is a problem with Windows Store SDK license.

![image](https://user-images.githubusercontent.com/5556784/44711695-3e898a00-aaaf-11e8-8d70-46fde5b97aa7.png)

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.18.18242.2
Wizard version: 0.18.18242.1
