### ISSUE TITLE
ASP.Net Core ItemTemplates

### ISSUE THREAD

**Issue by MichelLaplane** [Microsoft/WindowsTemplateStudio#2530]
When creating itemtemplates for ASP.NET Core project, the templates will not appear unless you add 
`<TemplateGroupID>AspNetCore</TemplateGroupID>`
in the .vstemplate file.

Unfortunately, this is not documented.
Could be interesting to add this in ProjectType instead in adding other categories for ProjectType:
`<ProjectType>AspNetCore</ProjectType>`

**Comment by sibille** [comment]
WTS is a VisualStudio extension that allows you to quickly build UWP project. I think the correct place for your suggestion are Microsoft Docs, for example [this topic](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-custom-project-and-item-templates?view=vs-2017) or somewhere beneath.

**Comment by sibille** [comment]
Closing this issue, please reopen if needed

**Comment by crutkas** [comment]
Hi @MichelLaplane https://github.com/aspnet/Templating  I think is actually where you to ask this question i think
