### ISSUE TITLE
Review calls on app initialization 

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2550]
We should add .ConfigureAwait(false) to all calls that do not require running on UI Thread to optimize initialization and explicitly wrap those that require UI Thread in a Dispatcher as apps generated with Prism do.
Also add a comment to MultiView and ThemeSelectorService initialization to make sure they are called first.

X-Ref: #2533

**Comment by crutkas** [comment]
This I think is a lower priority item.

**Comment by mrlacey** [comment]
>This I think is a lower priority item.

I'd consider making the existing generated code follow conventions and recommended practices a priority over adding new features.
Recommend for including in next release.

**Comment by mrlacey** [comment]
Assigning to next release to avoid this being forgotten about

**Comment by sibille** [comment]
Verified in dev-nightly;
Templates version: 0.20.19263.2
Wizard version: 0.20.19262.1

**Comment by sibille** [comment]
UserActivityService.SaveAsync needs to be executed on UI thread.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.20.19281.1
Wizard version: 0.20.19281.1
