### ISSUE TITLE
What should we generate for multiproject?

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2551]
Opening this to gather feedback from community.

**What should we generate for multiproject?**
We're planning to separate logic into two projects for version 3.0, a UWP project with the UI logic and a .net standard project with the application logic. 
The output would be the following:

![image](https://user-images.githubusercontent.com/24698018/45214725-8a9cb180-b29b-11e8-98ed-6e52a41086a3.png)

For generation we are evaluating two approaches: 
	A) Create the core project always, although it might only have an empty Models folder
	B) Create the core project only when necessary, for example if you choose a MasterDetail page it would be created with a SampleModel in the Models folder, if you choose only Blank pages it would not be generated. 

We would like to here your opinion on which approach you'd prefer. What would you expect WTS to generate?

X-Ref:  #2252 (Tracking issue for multiproject support)

**Comment by LanceMcCarthy** [comment]
I would find a Core project useful.

**Comment by crutkas** [comment]
@LanceMcCarthy the empty is what i'm worried about but honestly i think at some level, even with a blank file-new there would be some stuff that could be ok to put in there.  Another option would be is to create a readme.txt if empty.

**Comment by milazzom** [comment]
I'm voting for option A.  Reason is that if my app is going to do anything worthwhile, I'll need to have some code that would be appropriate to store in the Core project.  Think data models, services, and anything that doesn't have any coupling to UWP, Xamarin, or whatever UI platform or MVVM framework might be used in my projects.  It's easy enough to delete if you deliberately don't want to use it, but I think it's good to encourage a "good, maintainable" (good/maintainable being relative of course) solution structure from the start.  

@jermws @LeeParrishMSFT Any thoughts?

**Comment by LanceMcCarthy** [comment]
@crutkas a readme.txt in the Core project seems like a good option. 

You'd be able to put a note in there on how to remove the project from the solution for folks who aren't as experienced with Visual Studio... but at the same time, explain it's a .NET Standard 2.0 project and is a great place to put their model/helper classes so they can be reused.

**Comment by sibille** [comment]
Thanks for you feedback. We'll go for option A and include the core project always, adding a readme.txt file to explain it's purpose.

**Comment by mrlacey** [comment]
A `readme.txt` sounds like it would be useful even if the project contains content as its purpose may not be apparent to everyone looking at the generated code.

My broader concern is with the implementation of always including multiple projects. If templates are changed to assume that there will be the "main" project and the core one there are two potential issues:

Firstly, it risks preventing anyone with a project built with an older version of WTS from using the right-click>add (RCA) functionality. While it may be preferable from a development standpoint to limit the RCA functionality to projects created with specific WTS versions, this isn't reflective of the realities of software development. It is common for projects to be extended many months and years after they were first created. If WTS only makes the RCA functionality available to projects created with "recent" versions of WTS this risks limiting RCA functionality to the first few months after a project's creation. A short timeframe of use means that RCA is still useful early in a project's development but not when adding support for new platform features as they are released or when the needs of the people using the app change.
If it's acceptable that RCA will only be expected to work with recently created projects this should be documented clearly. (If it is I'm not aware of it.) My perception of the real value of the RCA functionality is that it provides long-term value from WTS and helps add to and extend projects over their lifetime. WTS loses value to developers if solutions must have a specific structure as fewer people will be able to use it. This potentially lost value also leads to my second concern.

Secondly, expecting that the core project will always be there will make enabling RCA support for projects created without WTS (#663) much harder. Care should be taken to avoid doing anything now that will make eventually implementing #663 harder.

**Comment by sibille** [comment]
I agree that we should support right click on older projects that were created without ".core" project, we're exploring different approaches to achieve this. 
Ideas we had so far:

1) Breaking change message and manual update instructions.
2) Breaking change message and .core feature project, that can be added by right click (in this case we would need some manual cleanup instructions, to avoid duplicated clases)
3) Create new projects with .core project, and additionally add core project feature as dependency to where it is needed so it gets added on right click generation.

Projects that have been created with 2.x can be in various situations, they could:
- Have no ".core" project
- Have a ".core" project that is a .netstandard project
- Have a ".core" project that is not a .netstandard project
- … 

We should explore advantages/disadvantages of each approach in the different scenarios.

**Comment by mrlacey** [comment]
Without having investigated all the options, my inclination is towards having the ".core" project as a dependency. New projects could depend on it and any page/feature that needs it should have the dependency too. This would cover initial creation and RCA.

Existing ".core" projects that are not of the expected type should cause an RCA failure just like any current existing file name collision but it'll be important to test this thoroughly.

--- 

Also when switching to a multi-project output, the main project should be named "Xxxx.UWP". This will make it clear which is the UWP project and will aid compatibility when also adding support for generating Xamarin.Forms based solutions (#2274) in the future. Will also need a review of namespace changes to reflect the project name, especially with regard RCA.

**Comment by LanceMcCarthy** [comment]
I second the `.UWP` naming convention. This is not only standard for Xamarin.Forms but for multi-project solutions.

**Comment by sibille** [comment]
Adding .UWP to the name makes sence. I've created a separate issue to discuss how to best support RCA.

**Comment by touseefbsb** [comment]
I would definitely prefer a core project even if it is empty with just an empty class with a read me or comments encouraging developer to put logic in the core project, also I was wondering whether offloading even the view model and some helpers into the core project would make sense ? @sibille

**Comment by crutkas** [comment]
always add core project
