### ISSUE TITLE
Review Sample Images location and SampleDataService

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2561]
The SampleDataService was moved to the .core project for version 3.0. 
Sample Images for the ImageGallery are still in the UWP project. The SampleDataService.GetGallerySampleData() returns image paths that are only valid for the UWP Project.

**Comment by crutkas** [comment]
could we maybe adjust the page(s) that use that to call a function?  that way core stays agnostic and the actual page itself knows how to deal with an app URI structure?

**Comment by mrlacey** [comment]
Solve this issue as you would for a Xamarin project. Inject the relative paths or a concrete UWP implementation of the way to get the paths.
a) This is a known solution to this problem.
b) This will need to be addressed in a way appropriate to XF projects when support for XF is added.

**Comment by sibille** [comment]
Missing changes for vb templates

**Comment by sibille** [comment]
vb templates where adapted in #2824

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19018.3
Wizard version: 0.20.19018.3
