### ISSUE TITLE
ImageGallery doesn't maintain back button behaviour

### ISSUE THREAD

**Issue by mjmeans** [Microsoft/WindowsTemplateStudio#2563]
Create a new project with an image gallery. Run it. Click the gallery hamburger menu item . Click on image 1. Click the gallery hamburger menu item (not the back button). Click on image 2. Click the gallery hamburger menu item again. Click on image 3. Now click the back button twice (to go to gallery then an image). It displays image 1. What is expected is that it show image 2 (i.e. maintain the back context as you go back through the pages). Or at least show image 3, the last shown image on each back to a detail page.

**Comment by dgomezc** [comment]
Thanks for reporting! To maintain the back navigation through various images we added a ImageNavHelper, that maintains the image navigation history in a stack.

You can find a example implementation here: [ImageGalleryExample.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2393338/ImageGalleryExample.zip)

**Comment by sibille** [comment]
@mjmeans, does this solution work for your scenario? We'll include the helper class in generation, so ImageGallery works correct in this scenario on back navigation out of the box.

**Comment by mjmeans** [comment]
I discovered the problem when investigating the various options in WTS. My scenario doesn't currently require this functionality. It may in the future, though not with pictures of course. Nevertheless, a helper class to manage back navigation to multiple different instances of the same page and ViewModel (but with different content) is something I'm sure many developers will want.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.19.18299.1
Wizard version: 0.19.18299.1
