### ISSUE TITLE
WACK testing failed due to space issues on dev and master

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#2573]
https://github.com/Microsoft/WindowsTemplateStudio/blob/vsts-builds/docs/vsts-builds/142.md
https://github.com/Microsoft/WindowsTemplateStudio/blob/vsts-builds/docs/vsts-builds/144.md

**Comment by sibille** [comment]
Cleaned up the build machines
Projects from failing tests are not deleted to be able to diagnose, but I think we should add cleanup logic to the tests that deletes everything that's older than a week, for example.

**Comment by sibille** [comment]
Wack tests are running fine now
