### ISSUE TITLE
Re-include background task to WACK

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2574]
We'll exclude background tasks from WACK tests due to issue #2358. Opened this issue to re-include once it's fixed.

**Comment by mrlacey** [comment]
#2358 has been closed but I still get the incorrect WACK failure on a machine with 1803 (the original issue).
Reenabling this will be dependent upon what is running on the build machine

**Comment by sibille** [comment]
Tested WACKs with BackgroundTask and it's running fine, but BackgroundTask and MultiView cannot be tested at once. Moving this to 3.6 to see if we can speed up or separate Wack tests somehow (while looking at https://github.com/microsoft/WindowsTemplateStudio/issues/3345) and test both scenarios.

**Comment by sibille** [comment]
Verified in dev
