### ISSUE TITLE
"Add nuget package reference" to project postaction

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2606]
This is currently done by Merge-Postactions that modifies the .csproj/.vbproj directly. 
After modifying the project file, we remove and re-add the project to the solution to un-dirty it for VS.
This way to un-dirty is no longer valid in VS 2019 as it introduces changes to package loading (https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/) 

Working on adding references between projects (#2386), we've also seen that adding nuget references editing the .csproj/.vbproj file causes the removal of references between projects (due to removing and re-adding the project to the solution). 

This should be done using nuget API.

**Comment by crutkas** [comment]
On offline scenario and if any of the nuget caches are not there, we will do the following:

1. generate the projects as normal
2. catch nuget exception
3. create ERROR_NugetPackages_Missing.txt in project
4. Add in text that says something to the regards of
5. open said text file so on generation so a developer clearly knows what to do and why it may have failed

> NuGet packages could not be added.  This could have been caused if you were offline.  Please manually add the following:
> Add PACKAGE1
> Add PACKAGE2

**Comment by sibille** [comment]
Migrating the nuget additions to the new system I found a few SDKReferences, that cause the same problem as they edit the _csproj file directly. Will add them via VS automation through a postaction too.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.18354.1
Wizard version: 0.20.18354.1
