### ISSUE TITLE
RSS Feed like Windows App Studio

### ISSUE THREAD

**Issue by SimoneRaspagni** [Microsoft/WindowsTemplateStudio#2612]
## For new Features:
I think would be nice if in the next versions it was possible to add RSS feeds (like Windows App Studio with rss link) using MasterDetails template!

**Comment by crutkas** [comment]
Would you like to take a stab?

**Comment by mrlacey** [comment]
This looks like a duplicate of #2095

**Comment by crutkas** [comment]
@mrlacey  agreed, marking as dup.  really wish github on a mobile device would be easier to do stuff like this :)
