### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by GeertvanHorrik** [Microsoft/WindowsTemplateStudio#2616]
https://github.com/Microsoft/WindowsTemplateStudio/blob/5c02b97d436f40b5c1b911079f7243826e672999/code/src/UI/Services/SystemService.cs#L44

**Comment by mrlacey** [comment]
Note. This is in the wizard source, not the generated code.

This typo is in 15 files but should be easy to fix (low risk) everywhere.

**Comment by sibille** [comment]
Fixed in dev
