### ISSUE TITLE
Explore how to support new page/new feature on 2.x projects

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2619]
Opening this issue to see what's the best way to support adding new pages/features on projects created with version 2.x (X-Ref #2551)

Ideas so far: 

1. Breaking change message and manual update instructions.
2. Breaking change message and .core feature project, that can be added by right click (in this case we would need some manual cleanup instructions, to avoid duplicated clases) - can we do this with TODOs on the affected files?
3. Create new projects with .core project, and additionally add core project feature as dependency to where it is needed so it gets added on right click generation.
	
Projects that have been created with 2.x can be in various situations, they could:
- Have no ".core" project
- Have a ".core" project that is a .netstandard project
- Have a ".core" project that is not a .netstandard project

**Comment by crutkas** [comment]
Add in core project.  dev can migrate code to new core from their existing

**Comment by sibille** [comment]
While working on always generating the core project, I had a look at this too. 
Option 3 (adding the core project as a dependency to pages that need it) will lead to conflicts when the core project evolves, for example, if I add a new reference to the core project, I'll get conflicts when adding a page that depends on the core project. 

![image](https://user-images.githubusercontent.com/24698018/49644417-afc6ca80-fa18-11e8-8c1d-e515c4fbec1b.png)

**Comment by sibille** [comment]
If it's only adding the core project we could add a right click action that's only shows on projects from version 2.x that have no core project and allows to add one in. 
If we also add a .Uwp project as suggested in  https://github.com/Microsoft/WindowsTemplateStudio/issues/2551 I think we should show a breaking change message with manual migration steps.

**Comment by sibille** [comment]
@crutkas, we should decide on this before sending localization, to include the texts for the chosen option. 

Options to support adding new pages/features on projects created with 2.x are: 
- Show a breaking change message when adding a page or feature on 2.x projects (that do not have a core project) that links to a document with manual update steps. 
- Add a right click command that is only available on 2.x projects (that do not have a core project) and allows to add the core project automatically. (if we go for this option we cannot add the ".Uwp" suffix to the uwp project). After adding the core project the dev will need to manually move code. 

I'd choose the first option as this is how we are alerting on breaking changes so far, there will always be manual actions, and right click addition vs new project creation is still 10% vs 90 %.

**Comment by sibille** [comment]
Ok, I'll see if I can set up a query to compare the RCA values.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19022.2
Wizard version: 0.20.19022.1
