### ISSUE TITLE
[Prism] Background activation should not recreate container

### ISSUE THREAD

**Issue by bartlannoeye** [Microsoft/WindowsTemplateStudio#2632]
### Repro steps

Repro steps on clean project:
- Add at least 2 pages
- Add background task
- Trigger background task through VS
- Navigate

### Expected Behavior

Navigation is succesful.

### Actual Behavior

While testing #2621 (on a private repo) I received following exception on first navigation after the event got fired.

> Microsoft.Practices.Unity.ResolutionFailedException: 'Resolution of the dependency failed, type = "XXX.ViewModels.YYYViewModel", name = "(none)".
> Exception occurred while: while resolving.
> Exception is: InvalidOperationException - The current type, Prism.Windows.Navigation.INavigationService, is an interface and cannot be constructed. Are you missing a type mapping?

## System

* **VS Version:** 15.8.5
* **WTS Wizard Version:** 2.4.18260.1
* **WTS Template Version:** 2.4.18260.1
* **Windows Build:**

**Comment by bartlannoeye** [comment]
Since the background task is in-process, we have a running/suspended application with the IoC container already configured. A background activation in the app should not recreate the IoC container. If I overlook anything, please let me know.

**Comment by mjmeans** [comment]
I spoke too soon. After leaving development for several hours, I started development again and upon first run, App.OnBackgroundActivated() is being called before App.ConfigureContainer(). So simple removal of the call to CreateAndConfigureContainer() corrects the navigation issue but introduces a new activation error. I think this is because the already registered background task has missed it scheduled run time, so it starts first.

**Comment by bartlannoeye** [comment]
@crutkas can someone responsible for application lifecycle and background tasks contact me? Something in my reasoning seems to be off.

**Comment by mjmeans** [comment]
Adding what check? Are you referring to a "try/catch" block? If so, then have you confirmed that the internals of CreateAndConfigureContainer don't change any underlying static or singleton classes references in the container system prior to throwing the exception? i.e. Are you sure that just ignoring the error won't contribute to later failures in the container implementation?

**Comment by bartlannoeye** [comment]
@mjmeans please scroll up to my [1st comment](https://github.com/Microsoft/WindowsTemplateStudio/issues/2632#issuecomment-427918944) in the thread. I've added a `== null` check, only when null, we should call the `CreateAndConfigureContainer `method.

**Comment by mjmeans** [comment]
Thanks. I missed the Edit.
