### ISSUE TITLE
Remove duplicate XElement.extensions file

### ISSUE THREAD

**Issue by GeertvanHorrik** [Microsoft/WindowsTemplateStudio#2640]
https://github.com/Microsoft/WindowsTemplateStudio/blob/8736d3c1c070a9e8274e6a034ac3f340c3749be6/code/src/Core/XElement.extensions.cs#L14

Code seems to have moved to /extensions/XElementExtensions.cs

**Comment by GeertvanHorrik** [comment]
Nice, @crnd already created a PR for this one.

**Comment by sibille** [comment]
Thanks @GeertvanHorrik  and @crnd!!

**Comment by sibille** [comment]
Fixed in dev
