### ISSUE TITLE
ARM64 is not supported

### ISSUE THREAD

**Issue by rido-min** [microsoft/WindowsTemplateStudio#2649]
VS 15.9 will include support for ARM64 when TPMinV>=RS5.
WTS generated projects should support ARM64 configurations.

Depends on https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/727

**Comment by crutkas** [comment]
This requires RS5 so this would come next spring with 19H1

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19273.1
Wizard version: 0.20.19273.1
