### ISSUE TITLE
Alt+Left tooltip shows up everywhere on NavigationView

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2650]
## For Bugs:

When creating a project with NavigationView, the **Alt + Left** shortcut key to go back shows up no matter where I hover over the **NavigationView** ( which is basically all UI in the app ), while it actually should just show up on the actual back button only with something like **Go Back (Alt + Left)** also in a localized manner. I have attached a screenshot showing the tooltip appearing on hover on a random place on an empty page of NavigationView.

![image](https://user-images.githubusercontent.com/11542189/46849140-68043800-ce07-11e8-8198-7005ee2e976d.png)

## System

* **VS Version:**  VS 2017 15.8.7
* **WTS Wizard Version:** 0.18.18284.65002
* **WTS Template Version:** 0.18.18284.65002
* **Windows Build:** 1809

**Comment by crutkas** [comment]
does #1229 cover this or #2488

**Comment by touseefbsb** [comment]
I do not think it does.

**Comment by crutkas** [comment]
For this issue, is it something we're doing or WinUI.  

In nightly, just start program and hover over a nav item and the alt-left pops up.

**Comment by touseefbsb** [comment]
I noticed following behviour : 

> When winui has 2 keyboard accelrators ( GoBack and Alt + Enter ) it shows Alt + Enter as tooltip on whole **ShellPage**

> I commented out the Alt + Enter accelrator and now **GoBack** tooltip was popping up all over.

> I commented out both accelrators, and now there was no tooltip, but ofcourse I lost feature of those 2 Accelerators.

**Comment by mvegaca** [comment]
Fixed #2679

**Comment by crutkas** [comment]
So this was us, not the navview control, thanks!

Wonder why the updated navview control would act differently

**Comment by mrlacey** [comment]
> We've moved the Keyboard accelerators addition from Page contructor to PageLoad event.

Sounds like a possible bug in their control. Has this been escalated/reported? I can imagine other people having the same issue.

**Comment by touseefbsb** [comment]
I have applied the fix in my mvvm basic app and it seems it has fixed the tooltip everywhere issue, but the thing is, now it is not showing the tooltip anywhere. I think it should show a tooltip on the backbutton. now the trick is which tooltip to show, Alt+left or go back ? or like **GoBack ( Alt+Left )** ?

**Comment by sibille** [comment]
Not fixed in Caliburn.Micro

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.19.18311.1
Wizard version: 0.19.18310.2

**Comment by StephenLPeters** [comment]
@sibille We've received reports on the Winui repo issue that this has regressed for winui3 preview 4. https://github.com/microsoft/microsoft-ui-xaml/issues/8  Do you have any thoughts on this?
