### ISSUE TITLE
Typo in NewItemGenController::TrackWizardCompletedTelemery

### ISSUE THREAD

**Issue by GeertvanHorrik** [Microsoft/WindowsTemplateStudio#2652]
https://github.com/Microsoft/WindowsTemplateStudio/blob/c5118634673b75a1a7c7c5db45540f5e863209a9/code/src/UI/Generation/NewItemGenController.cs#L342

**Comment by crutkas** [comment]
note "TrackTelemery" should be TrackTelemetry 

Also @GeertvanHorrik, great job finding these, 100% you can do pull requests ;)

**Comment by GeertvanHorrik** [comment]
Sure, since I am in a good mood today, I will do a few PR. They are all applicable to the wizard, so they shouldn't have much impact.

We forked WTS so we can build our own templates and wizard logic into VS for our own needs. WTS is a great starting point :)

**Comment by GeertvanHorrik** [comment]
Included in PR.
