### ISSUE TITLE
Adding a new platform?

### ISSUE THREAD

**Issue by weitzhandler** [Microsoft/WindowsTemplateStudio#2657]
What would it take to add a new platform (specifically [Uno](https://github.com/nventive/Uno))?

Basically it's just like UWP, except that 4 projects have to be generated, one of them a shared project, and the items have to be added to the shared project.

Can I have some basic direction on where to get started to adding support for Uno Platform?

@jeromelaban

**Comment by crutkas** [comment]
Something like Uno requires a few things. Like multi project support, which we are working on. :)

There are larger questions on a few things like UX and how everything is broken apart. We have an item for WPF and xamarin as well. 

I am not sure if we are quiet in a state for people to start experimenting with a branch of multi project BUT what would be interesting is to create a list of pages and features that work / don’t work on Uno

**Comment by weitzhandler** [comment]
Thanks for your reply.
@jeromelaban FYI

**Comment by crutkas** [comment]
If you want uno, open up a new issue. But help us with that up front work.  What does and doesn’t work.  Remember also we are bringing on the WinUI menu bar as a top level nav system too

**Comment by crutkas** [comment]
Please do. That initial what works and does not from a UWP to UNO project is a lot of investigation work. 

This is they type of help that really goes a long way for new stuff.

**Comment by weitzhandler** [comment]
Thanks for your kindness! #2658
