### ISSUE TITLE
Review calls to external APIs

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2695]
All calls to notification API should be wrapped in try/catch, as they can fail (in rare conditions). One reason would be for example failure to add a notification, due to running out of disk space.

**Comment by mrlacey** [comment]
Any external call could potentially cause an exception. Even if it's fire and forget.
Need to review all generated code for this, not just notifications.

**Comment by sibille** [comment]
good point, updated the title

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.19.18316.2
Wizard version: 0.19.18316.1
