### ISSUE TITLE
Datagrid headers

### ISSUE THREAD

**Issue by Pinox** [microsoft/WindowsTemplateStudio#2707]
Hi,

Just something I noticed, datagrid headers are not visible when using the light theme on ts (when in focus) and there is always a tooltip that says ALT Left.

![ts](https://user-images.githubusercontent.com/5297255/47298658-a32d1500-d618-11e8-9608-7c8ea95fa06a.PNG)

**Comment by sibille** [comment]
Thanks @pinox, we're working on the Alt+Left (#2650). Will have a look on the datagrid headers too.  Which version are you using?

**Comment by Pinox** [comment]
![version](https://user-images.githubusercontent.com/5297255/47300992-2a30bc00-d61e-11e8-9dfb-20fe49503ecf.PNG)

**Comment by sibille** [comment]
Hi @Pinox, 
to avoid showing Alt + Left we added a workaround in dev consisting in moving the KeyBoardAccelerator addition to the ShellPage's Page_Loaded event handler.

For the DataGrid issue, I think this is related to https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2373. WCT team is working on it.

**Comment by sibille** [comment]
Moving to 3.0 to revisit when fixed on community toolkit

**Comment by crutkas** [comment]
Pushing to 3.1 / Hotfix for 3.0, should be fixed with Toolkit 5.1 which is release released Feb 13th.

**Comment by sibille** [comment]
After updating to Windows Community Toolkit Version 6.0.0 this looks correct now!
![image](https://user-images.githubusercontent.com/24698018/73077482-8ab54580-3ec0-11ea-8498-cf360413d7bf.png)

**Comment by mrlacey** [comment]
Do people with existing (pre-generated) apps need to do anything other than update to the latest package version?
If they do, some notes on what to do would be useful.

**Comment by sibille** [comment]
No, we didn't do any changes to the datagrid other than updating to the latest package version.
