### ISSUE TITLE
NavigationViewHeaderBehaviour does not work correctly when setting HeaderContext to Page

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2711]
Raising a separate issue for this (X-Ref:#1229)

We're facing an issue in the NavViewHeaderBehaviour with CodeBehind.
X:Bind is not working in the DataTemplate when HeaderContext is set to a Page.

Possible workarounds would be:
- Bind to a HelperClass
- Not setting HeaderContext and use binding instead of x:bind.

I've attached a solution where you can see the problem and the workaround:
[App1.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2506011/App1.zip)

- App1_XBind_Page: This project shows the problem, binding seems to work fine, but value is not shown.
- App1_XBind_Helper: Solution 1: Bind to a HelperClass
- App1_Binding: Solution 2: Use Binding instead of xBind
- App1_ContentPresenter: This project shows what we suspect is the underlying problem, a `ContentPresenter` with `Content` bound to a page does not resolve bindings in `ContentTemplate `correctly, a ContentPresenter with content bound to another class does.

**Comment by sibille** [comment]
Moving to 3.0 to revisit once problem is solved on the control

**Comment by crutkas** [comment]
pushing to 3.1 / hot fix depending on WinUI

**Comment by sibille** [comment]
Looking into this with the WinUI team we think the best solution is using binding for the CodeBehind design pattern.
