### ISSUE TITLE
Master-Detail does not work properly on Pivot Project

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#272]
If you create a Pivot Type project, and add a Master-Detail page, when you come back from detail to Master, Pivot load first item. Pivot Shell must set NavigationCache.

**Comment by crutkas** [comment]
is this a must fix issue or can wait for a larger update?

sounds like must fix.

**Comment by mvegaca** [comment]
Fix on following commit

[Fix Master-Detail does not work properly on Pivot Project](https://github.com/Microsoft/WindowsTemplateStudio/commit/2584835a145fb9c4e6fadf0bf1a46d13a929864c)

**Comment by mvegaca** [comment]
Added useful comment and links on generated code on this [commit](https://github.com/Microsoft/WindowsTemplateStudio/commit/61ebb9050339dea9c5282d6952786718ed58127e).

**Comment by ralarcon** [comment]
Fixed in PR #421.
