### ISSUE TITLE
VB projects are not generated correctly on WACK Build machine

### ISSUE THREAD

**Issue by wasteam** [Microsoft/WindowsTemplateStudio#2724]
## Build dev.templates.tests.wack_20181031.2
- **Build result:** `failed`
- **Build queued:** 10/31/2018 1:00:25 PM
- **Build duration:** 530.05 minutes
### Details
Build [dev.templates.tests.wack_20181031.2](https://winappstudio.visualstudio.com/web/build.aspx?pcguid=a4ef43be-68ce-4195-a619-079b4d9834c2&builduri=vstfs%3a%2f%2f%2fBuild%2fBuild%2f26502) failed

+ Process completed with exit code 1.

Find detailed information in the [build log files](https://uwpctdiags.blob.core.windows.net/buildlogs/dev.templates.tests.wack_20181031.2_logs.zip)

**Comment by sibille** [comment]
The build machine executing the wack tests is broken, I'm setting up a new one. 
Will execute the tests locally meanwhile.

**Comment by sibille** [comment]
New machine has same error, it's throwing error 
'Error while processing file /Projects/DefaultVB/wts.DefaultProject.vbproj
Non-negative number required.
Parameter name: srcOffset'

Doing some investigation I found this issue: https://github.com/dotnet/templating/issues/1641

**Comment by sibille** [comment]
Fixed wack test machine, dev run successfully, pre is currently running
