### ISSUE TITLE
Dev-nightly: Error when navigating to MasterDetail in Prism App

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2739]
1. Create a new app with ProjectType SplitView and Framework Prism
2. Add a MasterDetail page
3. Start the app
4. Navigate to the MasterDetail page

-> Error is thrown: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.SetBackButtonVisibility(Nullable`1 previousState)
   at Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.UpdateViewState()
   at Microsoft.Toolkit.Uwp.UI.Controls.MasterDetailsView.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at Windows.UI.Xaml.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Microsoft

Repro app attached: 
[PrismMasterDetailRepro.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2553995/PrismMasterDetailRepro.zip)

**Comment by skendrot** [comment]
This is probably a duplicate of #2738

**Comment by sibille** [comment]
It comes down to the same issue, but the cause and resolution is slightly different. 
Workaround here is not setting the selected item to the first item when entering the page. Manual selection is working fine here.

**Comment by crutkas** [comment]
Can we move default selection to later in page life cycle?

**Comment by crutkas** [comment]
Do whatever works best. If the toolkit will fix this after the fact via a nuget update, it isn’t the end of the world.

**Comment by sibille** [comment]
Moved default selection to the page_loaded event.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.19.18316.1
Wizard version: 0.19.18316.1
