### ISSUE TITLE
Multi-View template should throw meaningful exception or not crash if not hooking into released event

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/WindowsTemplateStudio#2743]
### Repro steps
1. Create a new WTS project with Multiple-Views
2. Call `WindowManagerService.Current.TryShowAsStandaloneAsync` with the type of the same page (from somewhere, e.g. Button)
3. Run app
4. Open 2nd window
5. Close 2nd window (crash)

### Expected Behavior

Don't crash, though if I follow the [documentation](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/features/multiple-views.md) it works fine.  This documentation though isn't provided to in a link within the source code/api, instead only get this:

```
// Displays a view as a standalone
// You can use the resulting ViewLifeTileControl to interact with the new window.
```

Would be nice to have a note here about having to clean-up the registration for release and have a link to the doc about it here or above on the class.

### Actual Behavior

Get a
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  StackTrace:
   at Services.ViewLifetimeControl.FinalizeRelease() in Services\ViewLifetimeControl.cs:line 157

as InternalReleased event is null (though should probably use InternalReleased?.Invoke(…) pattern here instead).

## System

* **VS Version:** 15.8.8
* **WTS Wizard Version:** 2.4.18260.0
* **WTS Template Version:** ??? not sure where to find this after generation
* **Windows Build:** 17763.55

**Comment by sibille** [comment]
There should be a link to the docs on the top of the WindowManagerService class:

`// For instructions on testing this service see https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/features/multiple-views.md`

Would you expect it to be in another place? 

You can see the template version used for generation in the Package.appxmanifest:

```
<genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
    <genTemplate:Item Name="wizardVersion" Version="v2.4.18260.1" />
    <genTemplate:Item Name="templatesVersion" Version="v2.4.18260.1" />
    <genTemplate:Item Name="projectType" Value="SplitView" />
    <genTemplate:Item Name="framework" Value="CodeBehind" />
    <genTemplate:Item Name="platform" Value="Uwp" />
  </genTemplate:Metadata>
```

**Comment by michael-hawker** [comment]
Thanks @sibille, not sure what happened, but it didn't show up in VS the other day, comment is there today... :|

It'd be nice if it didn't crash if you didn't add the other part though too, or threw an exception to mention about releasing the view.

Also, `testing` should probably be `using` in the comment though.

**Comment by sibille** [comment]
Had a look at this and I agree we should throw an exception that tells you that you should subscribe to the Released event. Also agree that text should say "using" instead of "testing"

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19021.2
Wizard version: 0.20.19018.3
