### ISSUE TITLE
Spinning out a UI dev environment tool

### ISSUE THREAD

**Issue by M-Zuber** [Microsoft/WindowsTemplateStudio#2749]
Recently I was at a meetup where the Windows Template Studio was demoed.
Seeing made me think of a potential use case,
based off of my experience developing web based UIs.

There is a tool called [Storybook](https://storybook.js.org/) which allows a developer to "host" a component outside
of the context of a running app.
This is accomplished by the tool acting as a "host" for a given component termed a "story".
Within each story, the developer can add the different possible states by passing the
data in the relevant shape to the component being focused on.

This allows the designers to work on the UI and UX without needing to run the app,
or even go through any steps to work on a particular state.

Such a tool could be very useful for XAML development as well I believe.
Is such a project within the scope of the team,
whether as leads or supporting a community run project?

**Comment by crutkas** [comment]
Can you provide the scenario you are trying to solve here?

**Comment by M-Zuber** [comment]
Apologies for the delay.

As a scenario, something I am working on right now, is an edit screen for events.
The screen looks slightly different for each high level event category.

I can do all the UI and in-client behavior work without needing to actually run the app or make any network calls.
Additionally I don't even need a data source that contains every possible type of data, I can just set the test data in each story.
Essentially only hosting the components that comprise what I am working on.

Another scenario where it could be useful, is that it enables the developer working on the UI to start working even before any backend code is ready. A Desktop-Fronted developer so to speak 😃 

Side note: The main draw is for code bases that are component based

**Comment by mrlacey** [comment]
@M-Zuber That sounds like something totally different to Template Studio and more like a custom design tool.
Is your aim to make a version of Storybook that works with XAML or something more specific? 
Are you looking to address something that can't be done with current tooling? Do you want to enable another way of working? Are there specific limitations in what's currently available with other tools?

**Comment by M-Zuber** [comment]
>Is your aim to make a version of Storybook that works with XAML
Pretty much exactly this ☺

When I was shown the demo app, the way is was described was "view your components rendered in isolation" which is essentially storybook (apologies if this issue should have been on that repo). 

I looked around and only found different "live" coding tools which seem to only take care of development time. Storybook has the advantage (in the web version) of being a parallel site that be viewed independently, for UI/UX reviews for example. 
Or for a tutorial for new users.

Also, thank you for taking the time to talk through this.

**Comment by mrlacey** [comment]
What you're talking about is something very different to Template Studio which is a developer tool to help get started and create the structure of an app.
There may be an audience for and suitable community developers wanting to contribute to creating what you're talking about but it would be separate from what we're doing here.

**Comment by M-Zuber** [comment]
😳😳

this was the wrong repo...
I mean to post it in https://github.com/windows-toolkit/WindowsCommunityToolkit/

What is the simplest way to transfer the issue? Close this one and open one in the correct repo, copying over the comments?

**Comment by crutkas** [comment]
Open a new one over there and adjust the start of it. I would allow a new conversation to start vs copying comments
