### ISSUE TITLE
Naviagation View

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#2763]
how can I do that panel navigation using PaneDisplayMode ?

**Comment by sibille** [comment]
@javier118, are you looking for a horizonal NavView with PaneDisplaymode=Top or sth else?

**Comment by sibille** [comment]
It should just be adding PaneDisplayMode="LeftCompact" to the winui:NavigationView. Did you have any issues doing that?

**Comment by sibille** [comment]
@Javier118 , I'll close this issue, please feel free to reopen if you need anything else
