### ISSUE TITLE
RatingControl MvvmLight

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#2768]
When using TS and adding a ratingcontrol to page I get the following error:   "No such interface supported"

Not sure if this is TS or WinUI issue.  

plse see attached repo

![vs](https://user-images.githubusercontent.com/5297255/48888352-181f8480-ee3b-11e8-89f6-e1d13c6b898e.PNG)

![ts](https://user-images.githubusercontent.com/5297255/48888354-1a81de80-ee3b-11e8-9215-145dc43e4151.PNG)

[Blade_RatingsControl.zip](https://github.com/Microsoft/WindowsTemplateStudio/files/2606986/Blade_RatingsControl.zip)

**Comment by sibille** [comment]
Thanks for reporting, we'll have a look into it

**Comment by sibille** [comment]
HI @pinox, could you try adding winui namespace to the rating control, that made it work for me.

**Comment by Pinox** [comment]
@sibille  Apologies, did not realize I have to specifically add namespace to ratings control. All good again. 
Just for my understanding, Is there a reason why I should add namespace to only specific controls versus Grid or stackpanel that works out of the box.
many thanks.

**Comment by mrlacey** [comment]
> Just for my understanding, Is there a reason why I should add namespace to only specific controls versus Grid or stackpanel that works out of the box.
many thanks

WinUi adds support for newer controls to older versions of Win10. `Grid` and `StackPanel` have been around forever and so don't need this.

**Comment by Pinox** [comment]
@mrlacey  got it , thank you.
