### ISSUE TITLE
Templates are not downloaded in background

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#277]
After the UI redesign the ability to download the templates in background has been lost, that is, the user cannot continue working if a compatible template content is locally available while new content is being donwloaded.

It looks it is something related to the UI and when it consider you can continue working.

**Comment by mrlacey** [comment]
What's the rationale behind this bug? If someone is online and there are newer templates available don't we want them to use the newer ones. They should only fall back to cached older ones if can't check for new templates or there are problems during the download.

**Comment by ralarcon** [comment]
You are right, the thing is that everything was thought to make the downloads in background so if you have available content you can continue working without waiting to get the latest version of templates. 

It is not really important if you have good internet connection but we are showing some exceptions being tracked in the telemetry regarding timeouts in the download or not connectivity issues.

This now has been fixed and, by the way, we have added support to work in off-line mode even the first time you launch the wizard.

**Comment by mrlacey** [comment]
So, if 
1. Person installs the VSIX
2. Person uses it to create an app
3. New version of template is released with bug fix
4. Person goes to create another app they still have to use old, buggy templates
5. Person then goes to create a third app then they get the templates with the fix

This concerns me. 
For the sake of a check for new content when the tool loads we stop people having access to the latest and greatest templates.

Typical developers don't create new apps very often. They could end up using templates that are weeks out of date.

Yes, fallback to cached version if offline or there's a problem getting the new template.
Allow a person to skip the check if they really want too.
Don't check more often than every N hours.
But, do try and get people using the latest version of templates by default.


If connectivity is an issue in terms of the time to retrieve and download the templates, then those people are going to be in for a real shock when nuget package restore kicks in when they try and build the app.

**Comment by ralarcon** [comment]
We can allow users to search explicitly for new templates and / or we can allow users to force the refresh of recent downloaded templates... if so, we can open a different issue to track this.
