### ISSUE TITLE
docs/mvvmbasic.md Not sure what this means

### ISSUE THREAD

**Issue by ajventi** [Microsoft/WindowsTemplateStudio#2770]
"You can see examples of this being used in many of the pages that can be included as part of project generation"

I am not sure what this project generation refers to, this needs to be more clear.

**Comment by sibille** [comment]
@ajventi, not sure what you'd expect here. 
Could you give more details?

**Comment by sibille** [comment]
Windows Template Studio is a Visual Studio extension that allows you to generate UWP projects. You choose a ProjectType and DesignPattern/Framework, add pages and features and WTS generates the boilerplate sourcecode for you. The document you mention is a description of one of the frameworks, it's linked from https://github.com/Microsoft/WindowsTemplateStudio/blob/5fad02b0c228d45495c9dc16ca7958665a169d54/docs/getting-started-endusers.md where you can get more info about the generated project. 

For more info about WTS in general see: https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/README.md

**Comment by ajventi** [comment]
I took that quote off a confusing paragraph from one of the doc pages, no idea how to get back there.

**Comment by crutkas** [comment]
inside: https://github.com/Microsoft/WindowsTemplateStudio/blob/18f180215045b6a41b234e0e963a2887f4df7cb3/docs/mvvmbasic.md

**Comment by mrlacey** [comment]
@ajventi Would it be clearer if the paragraph read?

"`RelayCommand` contains an implementation of the `ICommand` interface and allows the **View** to call commands on the **ViewModel**, rather than handle UI events directly. You can see examples of `RelayCommand` in use in the **Camera**, **ImageGallery**, **Settings**, and **WebView** pages included in a generated project."

**Comment by ajventi** [comment]
@mrlacey, everything up to the 'generated project' is good. 

 I understand these docs are part of a project, however there is so much linking between various parts of the MS dev docs that many people are bound to find themselves (as I did) on one of these pages without having any idea what "a generated project" would refer to. Link to the head of the entire project.

**Comment by crutkas** [comment]
Ah, a generated project is what template studio made. We literally procedurally generate your file->new.   This is unique to template studio

**Comment by mrlacey** [comment]
@ajventi If we also change the opening paragraph of the document to the following, would this make everything clearer?

MVVM Basic is not a framework but provides the minimum functionality necessary to create an app using the [Model-View-ViewModel (MVVM) pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel). It is unique to projects generated with Windows Template Studio and was created for people who can't or don't want to use a 3rd party MVVM Framework.

**Comment by ajventi** [comment]
Yes, very much

**Comment by crutkas** [comment]
@mrlacey I would direct state at the end “such as MVVM Light or Prism”

**Comment by ajventi** [comment]
Thanks
