### ISSUE TITLE
Support for breaking changes in frameworks

### ISSUE THREAD

**Issue by nigel-sampson** [Microsoft/WindowsTemplateStudio#2771]
I'd like to kick off a discussion on how WTS can support breaking changes between major versions of frameworks such as Caliburn.Micro, MVVMLight and Prism.

From my side Caliburn.Micro is going through some major changes to support async first lifecycles in Conductors and so on. These changes will breaking ones and will mean a change in the major package version.

This could cause a problem in WTS where the templates can't been updated to use the new framework version without causing problems for users who have already generated their project on an earlier version.

Don't have any quick answers here, but wanted to start the discussion and see what other people think.

**Comment by sibille** [comment]
We had a similar case some time ago with a change in Mvvmlight and set up this document: 
https://github.com/Microsoft/WindowsTemplateStudio/wiki/3rd-party-libraries---updates-and-breaking-changes

Additionally we can detect a project created with an older version when adding items using right click addition and show a breaking change notification, linking to a doc with guidance on how to update. 
We've done this for the update from HamburgerMenu to NavigationView and Navigationview to WinUI Navigation View for example. (see first image in https://github.com/Microsoft/WindowsTemplateStudio/issues/2125#issuecomment-382371654)

**Comment by sibille** [comment]
Great, I'm closing this one. Let's open a separate issue for updating Caliburn.Micro (+the doing breaking change message) once Caliburn.Micro update is available
