### ISSUE TITLE
WinUI:NavigationView does not navigate in Release Mode

### ISSUE THREAD

**Issue by Pinox** [Microsoft/WindowsTemplateStudio#2774]
Hi , something I noticed , the Hamburger menu items does not change the page views when app is build to UWP Release Mode.

 
![releasemode1](https://user-images.githubusercontent.com/5297255/49093489-dcd2ea80-f26c-11e8-8269-8bc1ac7168f0.PNG)

Using latest stable VS 15.9.2
![ts](https://user-images.githubusercontent.com/5297255/49093590-16a3f100-f26d-11e8-8dc7-8c7f6c4158c0.PNG)

**Comment by crutkas** [comment]
@Pinox can you share the 'recipe' you used to aid us in debugging?

**Comment by Pinox** [comment]
@crutkas    Sure,   Navigation Menu , Mvvmlight and then I had a couple of random pages as in screenshot above.

**Comment by sibille** [comment]
@pinox, we're having a look at this. 
The issue seems to be related to using the EventTriggerBehavior on the ItemInvoked event. 

While we are working on a fix you can workaround by using the event instead. 
In ShellPage.xaml, remove the following code: 
```
<ic:EventTriggerBehavior EventName="ItemInvoked">
         <ic:InvokeCommandAction Command="{x:Bind ViewModel.ItemInvokedCommand}" />
 </ic:EventTriggerBehavior>
```
and add 

`ItemInvoked="NavigationView_ItemInvoked"`


In the ShellPage.xaml.cs add:

```
private void NavigationView_ItemInvoked(Microsoft.UI.Xaml.Controls.NavigationView sender, Microsoft.UI.Xaml.Controls.NavigationViewItemInvokedEventArgs args)
{
     ViewModel.ItemInvokedCommand.Execute(args);
}
```

**Comment by Pinox** [comment]
@sibille Thanks.

**Comment by crutkas** [comment]
Will this need a hot fix?

**Comment by sibille** [comment]
Created an issue to investigate this at https://github.com/Microsoft/XamlBehaviors/issues/142. I think we should prepare a hotfix with the workaround while investigating the root cause.

**Comment by mvegaca** [comment]
Hotfix added on a pull request
[https://github.com/Microsoft/WindowsTemplateStudio/pull/2776](https://github.com/Microsoft/WindowsTemplateStudio/pull/2776)

**Comment by sibille** [comment]
Hotfix published

**Comment by PedroLamas** [comment]
I see that you've moved away from the XAML Behaviors with this hotfix, but in case you still want to use it, I have a [solution](https://github.com/Microsoft/XamlBehaviors/issues/142#issuecomment-444824645) for you!

On the "Default.rd.xml" template files, add the following directives:

```xml
<Type Name="Windows.Foundation.TypedEventHandler{Microsoft.UI.Xaml.Controls.NavigationView,Microsoft.UI.Xaml.Controls.NavigationViewItemInvokedEventArgs}" MarshalObject="Public" />

<Type Name="Microsoft.UI.Xaml.Controls.NavigationView">
  <Event Name="ItemInvoked" Dynamic="Required"/>
</Type>
```

This will be enough to ensure that `NavigationView.ItemInvoked` event can be used dynamically with reflection (in this case, with the `EventTriggerBehavior`)

**Comment by crutkas** [comment]
Oooo. Thanks Pedro. Sibille, thoughts?

**Comment by sibille** [comment]
I think we should re-include the behaviour and the directives in the Default.rd.xml file, adding a comment that explains what they are needed for.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19009.3
Wizard version: 0.20.19009.1

**Comment by pavll** [comment]
Does somebody know where to mention this issue that it gets fixed by default (also for people who don't use WTS)? Maybe at the Microsoft.Xaml.Interactivity team or the microsoft-ui-xaml repo or the UWP Team?

**Comment by mrlacey** [comment]
> Does somebody know where to mention this issue that it gets fixed by default (also for people who don't use WTS)? Maybe at the Microsoft.Xaml.Interactivity team or the microsoft-ui-xaml repo or the UWP Team?

@pavll Yes, a fix for this at a UWP level should be reported at the WinUI repository. (Maybe reopen your issue there as a workaround isn't as good as a fix.)
Or, for WinUI related issues, report them on [the WindowsAppsSDK repo](https://github.com/microsoft/WindowsAppSDK) as that's where the templates for WinUI 3 projects live.
