### ISSUE TITLE
Failed Merge Postaction when adding first Settings, then Azure Notifications

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2789]
### Repro steps

- Create al App (CodeBehid, SplitView, Blank and Settings pages).
- Add an Azure Notifications feature using right click.

### Expected Behavior

Azure notifications feature adds AzureNotificationsService file and updates the ActivationService file.

### Actual Behavior

Azure notifications feature adds AzureNotificationsService file and fails updating the ActivationService file because the postaction can't find `await Task.CompletedTask;` line in `StartupAsync` method.

**What really happened**
We are adding different pieces of code in `StartupAsync` from different pages and features, and we need to respect a specific order in these additions to avoid unlikely behaviors, such a delay on theme initialization.

We remove the line `await Task.CompletedTask;` to deliver a clear code but we need this line in some postaction to add the code at the beginning of the method. We already have an instruction to add code at the end of the method **//^^** but we need to update the postaction engine to add code at the beginning.

![image](https://user-images.githubusercontent.com/5556784/49509885-f08eda00-f886-11e8-8a5b-e9a4458c15c9.png)

**Comment by mrlacey** [comment]
Has this ever worked?
- If so, what test should we have that would have detected this?

I can understand the need to add lines at the top of a method for some scenarios but this will need to be used very carefully.
We can only ever have one template that uses the new "insert at top of code block" functionality for a specific block or the issue of code needing to be executed in a specific order will come up again. Will we need new validation rules to detect multiple templates trying to modify the same block?

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.20.19018.3
Wizard version: 0.20.19018.3
