### ISSUE TITLE
Chart page enhancements

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#279]
Chart page has enough space to include richer information about the nature of data represented, for example,  a ListView with the source data, the title of represented data or the legend with data percents.
I think that this will improve the user experience for this page. What do you think @mrlacey ?

**Comment by mrlacey** [comment]
We had discussed this before. The page is intentionally very basic. The real aim of the page is to get the Telerik controls in and show that they can be used.
We are not trying to create an example of all that can be done. The expectation of anyone adding this page is that they will remove all that's in there by default and add their own code and configuration. If we add more then it's just more for people to remove.

Also need better sample data in the generated code. Can we use something more meaningful while still generic? @crutkas any suggestions?

**Comment by crutkas** [comment]
I want to review both Grid (#128) and chart pages (#129).  I also want to sync with our friends at Telerik to be sure we can provide a solid base implementation that fits a good 80% use case.  @mbcrump can actually help out here as he is ex-Telerik :)

**Comment by crutkas** [comment]
can we close this out?  Any expectations here?

**Comment by mrlacey** [comment]
I think this is all good and can be closed.   
Additional comments added to the generated pages since this was raised should avoid any further confusion about what is intended for/with these pages.
