### ISSUE TITLE
Add Visual Studio "Report Issue" in Windows Template Studio Menu.

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/WindowsTemplateStudio#2795]
* **Overview:** 

It'd be great if in the Windows Template Studio solution context menu, there was a 'Report Issue' option (or maybe somewhere else?).

It should automatically go to the GitHub New Issue template but have all the VS and WTS version/template info filled out.  I believe VS Code does something like this.

**Comment by crutkas** [comment]
That is a bit hidden, no?  I think there but would also think it needs to be visible from the wizard

**Comment by mrlacey** [comment]
Can't find the issue now but this is also something that we talked about adding to the [new] startup page

**Comment by mvegaca** [comment]
I'm working on it,  this is my proposal.

 - Replace `https://aka.ms/wts` to `aka.ms/wts`
 - Add Report issue link
 - Code in [this branch](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue2795-report).

**Current wizard**

![image](https://user-images.githubusercontent.com/5556784/53567670-3c88ac80-3b60-11e9-8ffa-b4832494b5bb.png)

**Changes in About section**

![image](https://user-images.githubusercontent.com/5556784/53567706-588c4e00-3b60-11e9-9449-33418c2d0d54.png)

Ok with this change? @crutkas

**Comment by crutkas** [comment]
Like report issue. Why not hyperlink our name?

**Comment by mvegaca** [comment]
**Code**

[Issue2795-report](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue2795-report).

**Final layout**

![image](https://user-images.githubusercontent.com/5556784/53579580-15d76f80-3b7a-11e9-926c-73533ef4dd81.png)

**Issue Markdown template**

I've also updated the issue markdown template, reducing styles from H2 y H3 and H3 to H4.
Left new right current.

![image](https://user-images.githubusercontent.com/5556784/53579706-5b943800-3b7a-11e9-9524-b9021c1016cd.png)

**Missing to PR**

Add VS Code version from extension and fake version from VS Emulator.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19070.1
Wizard version: 0.20.19070.1
