### ISSUE TITLE
What's New and First Run Prompts are setting the title two times

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2805]
### Repro steps

Create an app adding First Run and What's new prompts.

### Actual Behavior
Title property of content dialogs is set in XAML and RESW files.
The value in xaml must be removed.
```xml
<TextBlock x:Uid="FirstRun_Title" Text="Welcome" Margin="{StaticResource SmallLeftMargin}" VerticalAlignment="Center"/>
```

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.20.18354.1
Wizard version: 0.20.18354.1
