### ISSUE TITLE
ImageGallery & ContentGrid don't load in Blank Prism apps

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2809]
**Repro**

- Project Type = Blank
- Framework = Prism
- Add page "ContentGrid" (Or Image Gallery)
- Remove default Main page
- Create
- Run App
- Just get a blank window with no content displayed

The issue relates to how the connected animation service is wired up.

Found while implementing tests for #2780

**Comment by crutkas** [comment]
Feels hotfix worthy.

**Comment by mrlacey** [comment]
@crutkas It only applies if these pages are added to a Prism app that uses Blank navigation. I noted on the PR that I thought this was a bit niche to necessitate a hotfix but am happy for a hotfix if telemetry suggests this is worth it.

**Comment by mvegaca** [comment]
This issue is not happening in production enviroment, it was introduced when working on connected animation using toolkit. The PR #2810 fix this Issue and it's already merged to dev.

**Comment by mrlacey** [comment]
Closing as found and fixed in dev branch and has tests to identify any regression
