### ISSUE TITLE
CameraControl could throw exceptions

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#2813]
### Repro steps

Create an app:
 - NavView
 - Any Framework
 - Blank and camera pages.

Fast switch between blank and camera (stress test).

### Actual Behavior

CameraControl `InitializeCameraAsync` method could throw `TaskCanceledException `or `NullReferenceException` with this stress test and it must be handled.

**Comment by dgomezc** [comment]
When navigating to the camera page, InitializeCameraAsync method is called, and when you leave the page, the CleanupCameraAsync method is called. These two calls are made asynchronously, and when we perform a very fast navigation the application cancels the asynchronous tasks and throws an exception of type TaskCanceledException.

The solution is add a catch block in the InitializeCameraAsync method that captures the TaskCanceledException, the navigation is done correctly.

The InitializeCameraAsync method initializes the _mediaCapture object, and the CleanupCameraAsync method destroys it. As the two are asynchronous calls and performed very fast, it may happen that the CleanupCameraAsync method destroys the object while the InitializeCameraAsync method is using it, so a NullReferenceException is thrown.

To fix it we can use SemaphoreSlim (https://docs.microsoft.com/es-es/dotnet/api/system.threading.semaphoreslim), which will block the CleanupCameraAsync method and will not have access to _mediaCapture until the initialization finishes.

The problem with this approach is that when you put the semaphore, in all the navigations the object is created and destroyed (none is cancelled), so if we perform many navigations in a very fast way, the initialization of the camera is slowing down.

Another option is to use a catch block in the InitializeCameraAsync method that captures the initialization errors, and show a message in the page.

This type of problem is not going to happen in many cases and navigation will destroy the page anyway, so we believe that the catch is a better option and provides a cleaner code .

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19021.3
Wizard version: 0.20.19021.3
