### ISSUE TITLE
Add new tabbed page 

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#2820]
Add new tabbed page that uses the tabbed control from the windows community toolkit https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview. 
(X-Ref: https://github.com/Microsoft/WindowsTemplateStudio/issues/2428)

Action Plan: 
- [x] Create Mockup
- [x] Product team approval
- [x] Add templates
- [x] Add docs

**Comment by mrlacey** [comment]
Tabs via a Horizontal NavigationView make sense for some applications.
A single page using the TabbedView from the community toolkit as a single page app (or (WTS Blank project type) make sense for others.
I see no reason to exclude one over the other.

**Comment by mdtauk** [comment]
Not so much about exclusion, but having two Tabbed app templates could be confusing if the use cases for each are not defined and included in descriptions when choosing.

Of course a TabView Page in the Add File list wouldn't be inherently confusing.  It's just a concern about encouraging the use of NavigationView for tabbed navigation - and the TabView control for tabbed content.  Is this the right usage for each of these Tab patterns?  The Alarms & Clocks app is the main inbox example of using Top NavigationView as a tabbed interface, and there are no first party uses of the  TabView control as of yet.

**Comment by sibille** [comment]
@mdtauk, not sure what you're asking for.
We will use Horizontal Navview for tabbed style project types in v3.0.
![image](https://user-images.githubusercontent.com/24698018/50280920-21a60780-044e-11e9-898e-09fa5ee8d227.png)

This issue is for creating a tabbed page (using the control from windows community toolkit), that can be added to any project type, as the one we already have. 

![image](https://user-images.githubusercontent.com/24698018/50280977-5a45e100-044e-11e9-843f-60127decc311.png)


I agree with Matt, that there is no need to restrict it's usage to a concrete project type.

**Comment by mdtauk** [comment]
That was the point I was trying to make in my last comment.  As a Add New Page option it makes sense, but perhaps not as a New Project option.

And my comments in general about how NavigationView should be encouraged for navigation use, but the TabView control for content rather than navigation.

**Comment by mrlacey** [comment]
Rename the current option as "Pivot" (as that's what it is) and add a new page as "Tabbed" that uses the Tabs control from the community toolkit.
(May need to adjust internal naming to avoid confusion over analytics.)

**Comment by mrlacey** [comment]
> (May need to adjust internal naming to avoid confusion over analytics.)

ID of current page is "TabbedPivot" so if new page is identified as "TabView" (to match the control name) we shouldn't have to rename anything for analytics (always a bad idea.)

**Comment by mrlacey** [comment]
I'm thinking that this page should include binding to a collection of `TabViewItem`s and implement the `TabActionHeader` as a '+' that adds an item to the collection when clicked.
Leave everything else as default.

**Comment by mvegaca** [comment]
Here is the GitHub repository withe the Mockup for the new TabbedPage.
https://github.com/mvegaca/TabbedPageMockup

It's created using NavigationPage and MVVMBasic. The App also contains the current TabbedPage renamed as PivotPage.

We should not use the name TabViewPage for the new Page because this name is not a valid name (View Sufix).

![image](https://user-images.githubusercontent.com/5556784/64258064-d291fb00-cf26-11e9-8341-3f2025a85817.png)

**Comment by mrlacey** [comment]
Three observations:

- You've set both `CanDragItems` and `CanReorderItems` to `True` but not added the code to handle these scenarios. 
- Need to handle deleting all tabs and then clicking the add button - current code causes a crash.
- Feels like `TabbedItem.Content` should be an `object` so it can contain more than just a string. If not doing this, will need documentation showing how to have content within a tab that is more complex than just simple text.

**Comment by mvegaca** [comment]
Thanks for you feedback Matt, I've added [some updates](https://github.com/mvegaca/TabbedPageMockup/commit/7998a31cb9e7c08104cf36c8a0968d461f883470):
 - Remove DragAndDrop behaviors
 - Fix add tab method
 - Set TabbedItemModel as a sample class that should be replaced with comment

**Comment by sibille** [comment]
Just saw that WinUI 2.2 includes the TabView control. We're working on updating the mocks to use this control instead of the Community Toolkits one.

**Comment by mrlacey** [comment]
Working on VB version now

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.20.19281.1
Wizard version: 0.20.19281.1
