### ISSUE TITLE
content dialog PrimaryButtonText should be localized

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2822]
**PrimaryButtonText="Ok"** can be found in **FirstRunDialog.xaml** and **WhatsNewDialog.xaml** this limits it to English language only, I noticed it when I was testing my app for a different language, so this ok text should be localized by default.

### Proposed Solution : 

remove the **PrimaryButtonText="Ok"**  property from xaml page, and add it in c# instead.

```
public sealed partial class FirstRunDialog : ContentDialog
    {
        public FirstRunDialog()
        {
            RequestedTheme = (Window.Current.Content as FrameworkElement).RequestedTheme;
            InitializeComponent();
            PrimaryButtonText = "OK".GetLocalized();
        }
    }
```

similarly do it in WhatNewDialog and any others dialogs ( if any ) and ofcourse add "OK" value in the default Strings Resources file.

**Comment by sibille** [comment]
Thanks for reporting @touseefbsb, I think this was fixed as part of #2807
