### ISSUE TITLE
Build fails in AppCenter if the "Feedback Hub Link" feature has been selected in wizard

### ISSUE THREAD

**Issue by edetoc** [Microsoft/WindowsTemplateStudio#2827]
### Repro steps

in VS 2017, create a brand new UWP app using the Windows Template Studio wizard.
Check the "**Feedback Hub Link**" feature (which uses the Microsoft.Services.Store.SDK).
Add this app to Visual Studio AppCenter, and build it from AppCenter.

### Expected Behavior

Build succeeds

### Actual Behavior

Build failed with error:

`(ResolveSDKReferences target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2377,5): error MSB3774: Could not find SDK "Microsoft.Services.Store.Engagement, Version=10.0". [D:\a\1\s\App36\App36.csproj]`

note: building the app locally on the PC succeeds.

## System

* **VS Version: VS 2017 15.9.4**
* **WTS Wizard Version: 2.5.18319.1**
* **WTS Template Version: 2.5.18334.1**
* **Windows Build: Win 10 1809**

**Comment by edetoc** [comment]
additional info:
if the target version of the App is changed from 1809 to 1803 then the build in AppCenter succeeds

**Comment by crutkas** [comment]
@edetoc did you get this to work?

**Comment by edetoc** [comment]
No. AppCenter build still only succeeds when the app targets 1803. 
According to AppCenter team (I also reached out to them in parallel) the hosted VS 2017 image currently has version 17134 (1803) installed. they're currently working on rolling out the latest image with version 17763 (1809), in the meantime until this is rolled out they advise to build with 1803.

**Comment by mrlacey** [comment]
@edetoc I'm curious what, if anything, you think WTS should do about this?

It appears that the issue is that AppCenter hasn't updated their build machines to the latest OS/SDK.
We can't hold back WTS to not use the new UWP functionality until all possible build servers have been updated to support it. 
The best I think we can do here is to try and encourage AppCenter to update their build machines quickly now and set up processes so they're updated promptly when future VS/OS/SDK updates are released.

**Comment by edetoc** [comment]
@mrlacey I opened this issue because at the beginning I was unsure this was related to missing SDK (17763) on the build machines. It appears the engagement SDK itself has references to the missing SDK when targeting 17763, thus it will show this not found unless the app targets an SDK that actually exists on the build machines (like 17134). So think this issue can be safely closed now. thanks everyone for looking into this.
