### ISSUE TITLE
Multiple views feature exception when trying to open a Map Page

### ISSUE THREAD

**Issue by dawsongh** [Microsoft/WindowsTemplateStudio#2829]
When trying to use multiple view feature opening a Map page that has been created in WTS get the following exception:

_System.Exception
  HResult=0x8001010E
  Message=The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))_

### Repro steps

Create a new project using template (Nav Pane, Code behind), add Map page and add "Multiple Views" from Features.

From the main page, add a button then add the following code to try and open the page:
`await WindowManagerService.Current.TryShowAsStandaloneAsync("Secondary_Title.Text", typeof(MapPage))`;

Just wondering if this call should be away from the UI thread?

TIA

## System

* **VS Version:** 15.9.4
* **WTS Wizard Version:** 2.5.18319.1
* **WTS Template Version:** 2.5.18334.1
* **Windows Build:** 1809 17763.195

**Comment by crutkas** [comment]
@dawsongh can you attach a zip with a repro here, i want to be sure we're 100% capturing the issue with the given framework and nav pattern.

**Comment by mvegaca** [comment]
There are two different problems here:

 - MapPage should not include NavigationViewHeaderBehavior HeaderMode property when it is not shown in a NavigationView.
 - LocationService_PositionChanged should wrap the code in the new window Dispatcher RunAsyncCode.

We are going to add some dev guidance in NavigationView and MultiView docs.

**Comment by crutkas** [comment]
@mvegaca would this affect every page or just map page.  i am a bit worried about having custom page logic where one page has crazy different logic

what is your suggested changes here for the actual templates due to this bug?

**Comment by mvegaca** [comment]
We can't include the changes in the page templates as this only has to be done when the page is shown in a new window.

When a developer wants to show pages in separated views they must take care of some things like:

 - Use the new window dispatcher to run code on the UI thread.
 - Remove attached properties used to configure the Main Window NavigationView header.
 - Use MainWindow Dispatcher to run code on the main window from new windows.

These kind of considerations are not necessary when pages are shown as part of the app in the main window.

**Comment by crutkas** [comment]
Thoughts on having a docs page and link in actually page that would have the instructions for shifting page to multiple view?  It is used by 4% based on the telem data

**Comment by dgomezc** [comment]
We update the [multiview documentation](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/features/multiple-views.md) and added things to take into account when showing a page in the new window.
