### ISSUE TITLE
Review moving to VSSDK Meta package

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2834]
Core, Installer.2017, & UI projects may benefit from switching to using the VSSDK Meta package to simplify project references.

See https://blogs.msdn.microsoft.com/visualstudio/2018/10/10/simplify-extension-development-with-packagereference-and-the-vssdk-meta-package/

Also, x-ref https://github.com/Microsoft/Rapid-XAML-Toolkit/issues/126

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.22.20154.1
Wizard version: 0.22.20154.1
