### ISSUE TITLE
Review steps in the wizard

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2841]
The wizard currently has four steps, but some contain many options which may be easier to view and navigate if divided into more steps.

Here's what we have currently

- Step 1 (project type) - 3 options
- Step 2 (design pattern) - 6 options (3 for VB)
- Step 3 (pages) - 16 options
- Step 4 (features) - 19 options (in six groups)

It's only the pages and features steps that are impacted by the number of options they contain.

There is a separate issue/discussion (#2338) on breaking pages into groups. I don't see any potential benefit in splitting pages over multiple steps.

The number of features is growing faster than pages and has more potential for further growth.

There are currently plans to add five new features in a "Testing" group and six new features in a "Data Access" group. It is this increase that prompted the question of whether it might be better to display these new options in separate steps.

Questions:
- Do you think splitting features over more steps would be beneficial?
- Would "Testing" and "DataAccess" features be better as separate steps, or as groups within the features step?
- Are there any currently existing groups in the features section that you feel should be a separate step?
- If adding more steps, should we add a way to make clear which (if any) are optional?

_Development note that adding more steps would have an impact on right-click functionality too._

----

Related to this is whether the steps available should be configurable.

Configurability would increase flexibility for future changes in the number of steps and also make it easier to reuse the UI for generating more than just UWP apps. 

The implications for right-click support with the ability to configure steps are also potentially significant.

**Comment by crutkas** [comment]
Design patterns will gain menu bar as well but that still is pretty scoped

With identity being brought on line as well and other cloud features, I think we can break out features a bit more.  Pages may be a bit harder to break up but i think those are stable versus features too.

Services, Authentication, Testing, Data, ...  maybe a good way to think about this is list the upcoming things we're thinking about along with the current stuff and try to categorize them logically.

**Comment by mvegaca** [comment]
Working on it on this branch
[Issue2841-steps](https://github.com/mvegaca/WindowsTemplateStudio/tree/Issue2841-steps)

**Comment by mrlacey** [comment]
> Working on it on this branch

Working on what?
There are still unanswered questions about what, if anything, should be changed.

**Comment by mvegaca** [comment]
What I'm doing is add to the wizard the capability to handle 2 new steps (only visible if are templates available).

**Comment by mrlacey** [comment]
What's the spec for these changes?
How will they be configured?
How will they be labelled?
Which other planned changes for the wizard does this align with?

**Comment by sibille** [comment]
The idea is to be able to break out features into other steps, apart from Pages and Features (like Services, Authentication, Testing, Data).
Steps should be shown dynamically (if there are no templates in a step it should not be shown).

We're still looking into different options for definition of which template goes into which step and will update the issue once we've got a proposal.

**Comment by crutkas** [comment]
@mvegaca what is driving this?  bit confused.

**Comment by sibille** [comment]
Synced offline and decided to come up with open questions for this issue: 
1. Should we break out some of the Features (like SQL Server, Testing, Identity) into separate steps?
2. Are there other options to organize the long feature list?

If we decide to break out features in various steps:
3. Should steps be configurable / inferred from templates?
4. Do we need a new tag to define the step on the tamplate or should we reuse wts.type?
5. How is step order defined?
6. How should telemetry report those features (as feature or as the step they are in (e.g. Testing, … )?
7. Should we have separate right click options for each step or one common "New feature" right click option?

@mrlacey, @crutkas, what else would you add?

**Comment by mrlacey** [comment]
**Have we had feedback from anyone that the current feature list is too long and/or hard to navigate or find things on?**

Going back to the OP, no-one ever came back and said the number of items in a step was something that was a problem. Nor has anyone expressed opinion on whether certain groups of features would benefit from being in a separate step.

_This started as an **Open Community Question** but no-one from the community thought this was important enough to respond._


Working on the basis that the future will bring requirements for supporting more/different steps, having the ability to divide the current features step might seem like a reasonable first step and as a way of exploring options and proving a solution.

---

If separating out some of the features, how should the ones to be separated be decided?
Need to have good documented reasons for this so that we can adjust in future as more features are added.  If it's based on number of items in a group, what's the threshold for splitting into a separate step? If it's based on the type of feature, it would be good to have solid reasoning for why that type warrants a separate step so every group or additional feature doesn't necessitate a debate on whether it should be a separate group.

**If add a new step with a specific name**
- What happens if there are combinations of selectable items that don't have that new step? (e.g. If we added support for a new framework but it didn't have any features that go in the new group. Would all possible steps be shown from the start but some may end up empty?)
- How can this change be done so that it makes adding additional steps in the future simple?


**If add the ability to add steps with template defined names**
- Will these only go after the existing steps?
- Will this include the ability to specify steps between existing steps? (i.e. if wanted to split up pages over more than one "step".)


**What might we want in the future that's related to this**
- The ability to specify arbitrary steps in templates.
- The ability to not specify something in an existing step. (e.g. for an app type with no navigation pattern.)
- The ability to exclude currently defined steps.
- The ability to fully evaluate and process templates that are downloaded from other locations. (For when this is supported.)
- The ability to specify the order of steps?

**Open questions (broadly applicable)**
- How can template defined step names be localized?
- Will custom steps also support grouping?
- Should grouping support be added to the existing steps?
- What if there's an intermediary step with no selectable options? (Consider a console app template which would have no framework or pages.) Can this be supported?
- What validation (if any) should be applied to names defined in templates? And what if this validation fails?
- What do we need to do to fully test (preferably in an automated way) any changes that are made for this?
- Can group order be made configurable? (currently it's alphabetical.)
- If adding the ability to define steps (and groups) in templates, should all existing templates be updated to get this information from templates? (This would avoid having to manage step (and group) definitions coming from different places.)
- What does this all mean for right-click>add functionality, which currently assumes that there are only "Pages" and "Features" that can be added? It also assumes that there are manifest entries related to navigation and framework--what happens for them in scenarios where there is no such step defined?
- What if multiple different, templates define steps (or groups) with the same order but different names? or different orders but the same name?

**Comment by sibille** [comment]
Discussed with the Madrid team, and came up with the following suggestions: 

**Should we break out some of the Features (like SQL Server, Testing, Identity) into separate steps?**

The feature list is very long, we and experienced users already know what is there, but we think that it can be tough for people that start with WinTS to find a concrete feature. 
Breaking out some features into other steps would make the list shorter and also gives us the opportunity to give them more entity. For example Testing isn't really a feature, but a bigger activity related to the development process. We think that having it as a step suggests people to add it more than having it in the long list of features. 

**Alternatives**: 
* Filtering/Searching: Problem we see here is how can we make people aware of what they can search for. We could also combine both ideas, but search should work globally on all steps then.
* Collapsable Groups: This would not reduce the long list in features, but would help to make it more manageable

**What steps do we want to add?**
We believe that we should identify other bigger entities (like pages and features) and define new steps for them. Also  
Step order is important.  Also the step list should be no longer than 6 steps ideally. 

Proposal for new steps
* Services 
   * will contain templates that add code that is not related to UWP platform. 
   * Initially, this will contains two groups 
     * Identity (Optional login, Forced login,…) 
     * Data Access (SQL Server, Web Api,…) 
* Testing 
    * will contain templates related to testing. 
    * We could think on create groups for App, UI and Core tests
	
**How would steps be defined in wizard and templates?**
* First two steps are not related to the project definition and would be handled apart, all others are about adding item templates. 
* Our proposal for steps infrastructure is: 
   * Step configuration in the template.json file (wts.type or new tag). 
   * Step string resources and steps order defined in wizard. 

**Should steps be always visible even if there are no templates?**
* We think only steps with templates should be visible 
* Steps should be updated when project type or framework are changed, to have the possibility, for example, to not have a step for MenuBar/Prism combination. 
	
**Right click**
* For consistency with the steps we'd add a right click option for each step:
* Windows Template Studio 
  * New page… 
  * New feature… 
  * New service… 
  * New testing project… 

**Telemetry**
	We currently report how many pages/features where added on project generation, on template generation there is info if the template is a page or feature. We should include the new steps here
		
**Visual changes**
* Add two new steps (Services and Testing). 
* Place the check at the right side to be able to always show the step number. 
	
**Code refactor**
Create a Navigation controller to handle all wizard steps navigation logic, at this moment, this logic is on MainViewModel and its base class. This update reduces the complexity of the MainViewModel. 

**Future considerations:**

Steps login
Support sub steps for templates configurations, for example allow to add a sub step to configure identity in AAD.

**Comment by mrlacey** [comment]
>... gives us the opportunity to give them more entity.

I'm not clear what you mean by "entity" here.

**Tools** is another potential group to move to services. While it currently only contains a single item, it's "not related to UWP platform" and so should be moved based on that principle.

If making these new steps optional, can "Pages" and "Features" be made optional? (Would help with some ideas I have for the future...)

Can "Framework" be made optional too? Or does there always need to be one? If there is only one, does this step need to be shown?

Will the different right-click options only be made available if the appropriate steps are available? Or will they always be available? (How will it know? How will it be able to check for new templates which may add a step which wasn't available previously?)


To confirm:
- No support for template defined steps will be added (at this time.)
- No support for template defined groups will be added (at this time.)

**Comment by sibille** [comment]
What I wanted to say is give the testing more emphasis.

Ok with adding Tools as another group under services. 
Pages and Features can also be optional, as all steps (with exception of Project Type and framework) would be handled the same. 
Making framework (or project type) optional is more complicated as those steps work different and have more dependencies. Also, even if there's only one, I think it's good to see it somewhere. What would be a use case for no or only 1 framework?
The right click options should only be visible if there are templates available (for consistency with "new project"). We could add an "update templates" entry if we detect that new templates are available.

We don't think we should let templates only define steps and groups. Step order should be defined in the wizard, and we also need the translated resources.

**Comment by mrlacey** [comment]
> Making framework (or project type) optional is more complicated as those steps work different and have more dependencies. 

Thought that might be the case, but can live with it.

> What would be a use case for no or only 1 framework?

- Console apps. Don't have frameworks (or pages.)
- New project type where only one framework is (currently) available.
- When we add support for additional template sources, imagine an organization who always uses one framework and so would only have templates for that.

> Step order should be defined in the wizard, and we also need the translated resources.

Fine for now, but not once we have 3rd party template sources. Can defer until then, but will be needed eventually.

**Comment by mvegaca** [comment]
- The step a template is going to be shown in can be configured using the `wts.type` tag in template.json.
 - I've added two new TemplateTypes in  CoreTS: Service and Testing.
 - I've also moved Services and Testing templates to new corresponding folders.

**Comment by sibille** [comment]
Adjust localization tool and wts telemetry tool and queries

**Comment by mvegaca** [comment]
Things that must be fixed:
 - Back button on template details view.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19183.1
Wizard version: 0.20.19183.1
