### ISSUE TITLE
Address code suggestions in the generated code

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2842]
The generated code includes some places which Visual Studio suggests should be changed or improved.

![image](https://user-images.githubusercontent.com/189547/50967099-13885b80-14cf-11e9-91de-e56516c7509e.png)

These are not errors just different/simpler/more modern/"better(?)" ways of doing things.

These have not been addressed previously as the goal with the generated code has always been to have a focus on readability.
However, after seeing these comments many times I've started to get the impression that Visual Studio is implying the generated code could be better and so should be changed.
Whether a brand new language feature shortcut is easier to understand or not is subjective but these suggestions are being applied to all code, and so it feels right not to be producing something that works one way when the people creating the language (and the analyzers that are highlighting the issue) say should be done in another.

Applies to C# & VB templates.

When making this change, also need to look at modifying testing to detect any issues in future changes or additions.

**Comment by crutkas** [comment]
I’m all for it. I think the code shouldn’t throw warnings and error. I think this is a great idea

**Comment by mrlacey** [comment]
Choosing not to address `IDE0017 Object initialization can be simplified` as this si a style preference. May review once init properties are released (and commonplace)
Choosing not to address `IDE0044 Make field readonly` as assuming the properties that aren't read-only were done this way deliberately. (And I'm not inclined to review each one at this time.)
Choosing not to address unused members as they exist for future enhancement of the generated app.
Choosing not to address `IDE0059 Unnecessary assignment of a value to ...` as the assigned values help with the readability of the code.
Choosing not to remove unassigned parameters as many of these are false positives or likely needed when the generated code is enhanced.
