### ISSUE TITLE
VS 2019: Error adding nuget package to core project

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2862]
Adding SettingsStorage Feature does not add nuget Newtonsoft.Json to core project in VS 2019.

Error message: Method not found: 'Microsoft.VisualStudio.ProjectSystem.IProjectServices Microsoft.VisualStudio.ProjectSystem.IProjectService.get_Services()'.

**Comment by crutkas** [comment]
I'm assuming in both scenarios we are using https://www.nuget.org/packages/Microsoft.VisualStudio.ProjectSystem/

they have a preview version, does that fix it?

**Comment by crutkas** [comment]
looks like there is a breaking change per our call, https://github.com/Microsoft/VSProjectSystem/blob/b513b6eb3f73cb4233d6da0dff1f9fa527a73f68/doc/overview/breaking_changes_visual_studio_2019.md

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19065.1
Wizard version: 0.20.19065.1
