### ISSUE TITLE
enable uri deep linking and FileAssosiation after creating project

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#2864]
## For new Features:

* **Overview:**

Uri deep linking protocol feature is currently only available when creating a new project and we cannot add it after creating the project, so it would be great if we can have that option a well.
Also we do not have a FileAssosiation ( FileActivatedEventrgs ) feature and it would be a bonus to have that feature in wts as well. I am aware of the docs provided for it and we can easily include it manually, but if it is possible automating it as well would be helpful.
Thanks.

**Comment by mrlacey** [comment]
There is a separate issue tracking the lack of right-click support for the deep-linking feature at #1097 

There is also a separate issue for tracking the lack of file handling within a generate app at #920

There are lots of features that _could_ be added. 
Is there a reason for adding implementations of the [file activation sample](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/activation.md#sample-add-activation-from-file-association) now?
Why add an implementation for this now and not another type of activation handler that doesn't even had documentation showing how to add it?

It would be nice if features were available for all supported activation types but it would be a lot of work to implement, and there has been little/no demand for it.

If this is your way of asking for a built-in feature implementation for file activation, please upvote and/or explain your reason on the [existing issue](https://github.com/Microsoft/WindowsTemplateStudio/issues/920).
