### ISSUE TITLE
FeedbackHub is not working on 1809

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2869]
Feedback Hub feature is not working correctly on Windows 1809, we should disable the feature until this is fixed.

**Comment by mrlacey** [comment]
How "not working correctly"?
Is this something that could have been tested for?
Is a review of how tests are run on all supported platforms required?

**Comment by crutkas** [comment]
@mrlacey, it crashes the app when launched.  it is the SDK, not us.

**Comment by sibille** [comment]
Excluded from pre and pro template packages, in dev this will still be available so we can test.
