### ISSUE TITLE
Code smells in generated code

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2871]
Not bugs, as such, but ways for the generated code to be improved.
Assigning to 3.1 as assuming late for 3.0 and these may require some discussion/review.

In **WindowManagerService**
- `TryShowAsStandaloneAsync` and `TryShowAsViewModeAsync` both assign a variable `viewShown` but this variable is never used. Should the assignment be removed and the return of the method call ignored, or should the code be checking the returned value and using it accordingly?

In **ViewLifetimeControl**
- There are various places where the code locks on `this` (or `Me` in VB) but this is widely considered a bad practice as it risks creating deadlocks. A separate object should be used for locking instead.
- In `StopViewInUse` a value is assigned to the variable `task` but this variable is never used. Should the assignment be removed and the return of the method call ignored, or should the code be checking the returned value and using it accordingly?

In **InkFileService**
- In `ExportCanvasAndImageAsync` a value is assigned to the variable `status` but this variable is never used. Should the assignment be removed and the return of the method call ignored, or should the code be checking the returned value and using it accordingly?

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.20.19078.1
Wizard version: 0.20.19078.1
