### ISSUE TITLE
Set build and deploy actions for 'Any CPU' config

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#2880]
![image](https://user-images.githubusercontent.com/189547/51930154-cf171e00-23f1-11e9-804a-eebbf7418d50.png)

For an app generated with VSEmulator, Visual Studio defaults to using the "Any CPU" architecture.
(Apps generated with File>New inside VS default to x86.)

This can be an issue as Build and Deply actions are not set for the main app.

![image](https://user-images.githubusercontent.com/189547/51930269-156c7d00-23f2-11e9-8fa5-25debde3b0a6.png)

When using VSEmulator, it means remembering that when first opening the app in VS, the selected platform or change what is built/deployed via the configuration manager.

This isn't as much as an issue for apps generated within VS as the default platform selection doesn't cause errors to be shown or F5 to cause an error.

It would be nice to address this though as adding other projects to the solution (e.g. for testing, or Web API) these can also use "Any CPU" and it would be better if selecting any of the architecture options didn't lead to errors preventing the code from compiling.

**Comment by sibille** [comment]
@mrlacey, I was looking into the possibility to change the selected configuration to x86 as we do in the VS extension, but could not find a way. 

I'll add Build and Deploy to the "Any CPU" configuration + a comment stating that the solution was generated by the emulator and is different from what VS generates.

**Comment by sibille** [comment]
Verified in dev
