### ISSUE TITLE
// TODO: THIS SHOULD BE THE ITEM IN CONTEXT

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2881]
GenComposer.cs contains the comment
```cs
// TODO: THIS SHOULD BE THE ITEM IN CONTEXT
```

It's not clear what the action to be done here is.
EIther the coment should be removed or the appropriate change made.

**Comment by sibille** [comment]
Did some investigation and think this comment goes back a very long time, when RootNamespace and ItemNamespace where different. 

We should unify the usage in the templates too.

**Comment by mrlacey** [comment]
covered by #2907
