### ISSUE TITLE
DataGrid: MasterDetailDetailControl usage

### ISSUE THREAD

**Issue by Scnck** [Microsoft/WindowsTemplateStudio#2895]
Hello,

I'm new to UWP and trying to get a DataGrid to show the info based on menu selection but unable to figure out the proper syntax for the data binding of the MasterMenuItem. Any help would be grateful

**Comment by crutkas** [comment]
can you tell us more about what you generated?  screenshots are helpful too with arrows and "i want to do this!"

**Comment by crutkas** [comment]
We generate functional code that binds against a sample data service.  

For screenshots, I was thinking more in terms of your generated application so we have more of a proper representation of what you are trying to do. 

What I think you are asking is I have a menu bar and I want my data grid data to be different based on the selection.  Correct?

**Comment by crutkas** [comment]
you want a data grid in the detail page.  Correct?  That data would change based off what was selected, right?

**Comment by Scnck** [comment]
Yes that is correct.

**Comment by crutkas** [comment]
What you'll want to do in your **MasterDetailDetailControl.xaml** file is add in your DataGrid.  The datasource itself that gets passed in by is **SampleOrder MasterMenuItem**.  As you can see, that is of type SampleOrder, which does not have a collection to bind to so this would be something you'd want in your data object you'd bind against.  We can hack something in just by borrowing code from the **DataGridPage.xaml** and **DataGridPage.xaml.cs** page for the observable collection and DataGrid.  you'd then need to alter the binding slightly to point at your MasterMenuItem's collection versus the hardcoded sample data we just injected.

Does that make sense?

**Comment by Scnck** [comment]
I need up creating a data converter prior to your reply; what approach would be consider best practice?
    public sealed class MenuSelectedConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string culture)
        {
            SampleOrder sampleOrder = (SampleOrder)value;
            var data = new ObservableCollection<SampleOrder> { sampleOrder };
            //data.Add(sampleOrder);

            return data;
        }

        public object ConvertBack(object value, Type targetType,
            object parameter, string culture)
        {
            throw new NotImplementedException();
        }
    }

**Comment by crutkas** [comment]
It all depends on what you want to do.  I'm only seeing a partial lens here so guidance is hard to give. The wonderful thing about programming is there are multiple approaches you could take.

The easiest way is to give us a repro we can see in the issue.  This would let us do a quick poke around and give maybe a suggestion.

@sibille this could be a good idea for documentation to talk about how to maybe do bind to maybe a datagrid here.  I could see in this exact scenario having it show all the orders from that company in a datagrid.

**Comment by Scnck** [comment]
here is my sample app https://github.com/Scnck/App.git
