### ISSUE TITLE
DataGrid + UWP

### ISSUE THREAD

**Issue by Scnck** [Microsoft/WindowsTemplateStudio#2901]
I'm new to UWP, is it possible to have a menu control on a cell within a DataGrid; if so a simple example of the syntax would be grateful. Thank you.

**Comment by crutkas** [comment]
this is possible, you are referring to a ComboBox is the generic control.  I'm going to loop in @michael-hawker as he would be a better resource for exact XAML syntax.  However looking at docs, 
https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid_guidance/datagrid_basics they have a control type just for this scenario

`<controls:DataGridComboBoxColumn Header="Department"
                                                 Binding="{Binding DepartmentId}"                                                  
                                                 ItemsSource="{x:Bind Departments, Mode=OneWay}"
                                                 DisplayMemberPath="DepartmentName"/>`

**Comment by crutkas** [comment]
@sibille would this be maybe a good idea to add into our default grid?

**Comment by Scnck** [comment]
I don't believe we are talking about the save thing. I want an actual menu when right_click() on certain cell withing the DataGrid

![image](https://user-images.githubusercontent.com/17710395/52309941-a94cc480-296f-11e9-885c-ea0a41535d96.png)

**Comment by crutkas** [comment]
Oh!  That is called a context menu typically, Here you'd do ala below.  With that said, www.stackoverflow.com is a much better spot to ask these questions as this is more of a using UWP versus windows template studio.  

if you don't get a good response, hit me up on twitter and i'll be sure we track it down.  https://twitter.com/clintrutkas or email at clint.rutkas@microsoft.com

`<controls:DataGrid.ContextFlyout>
    <MenuFlyout>
        <MenuFlyoutItem Text="Change color" Click="MenuFlyoutItem_Click" />
    </MenuFlyout>
</controls:DataGrid.ContextFlyout>`

**Comment by Scnck** [comment]
here is my sample app  https://github.com/Scnck/App.git

**Comment by Scnck** [comment]
> `<controls:DataGrid.ContextFlyout> <MenuFlyout> <MenuFlyoutItem Text="Change color" Click="MenuFlyoutItem_Click" /> </MenuFlyout> </controls:DataGrid.ContextFlyout>`

But is it possible to do in a cell rather than entire DataGrid; if so haven't seen/found any examples?

**Comment by michael-hawker** [comment]
You should also be able to grab the item from the events args of the flyoutitem's click event.
