### ISSUE TITLE
Remove use of ItemNamespace

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#2907]
Following on from #2892 and PR #2902 

#2902 changed some uses of Param_ItemNamespace to Param_RootNamespace but not others.

At the moment, Param_ItemNamespace and Param_RootNamespace have the same values. I think it would be much simpler to just have the one placeholder for this value.

This would be a big change but would make sense to do at the same time as all the other changes that are being made in this area. 

This would also address #2881 

@sibille @mvegaca - thoughts?

**Comment by sibille** [comment]
Agree
