### ISSUE TITLE
new Version TemplateStudio this Problem CommandBar

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#2910]
The CommandBar falls below the title .

 ````
      <Grid.RowDefinitions>
            <RowDefinition x:Name="TitleRow" Height="48"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <TextBlock
            x:Name="TitlePage"
            x:Uid="Main_Tilte"
            Margin="0,0,12,7"
            Style="{StaticResource PageTitleStyle}"/>


        <CommandBar Grid.Row="0" Background="Transparent" x:Name="AppBar" HorizontalAlignment="Right" DefaultLabelPosition="Right">
            <CommandBar.PrimaryCommands>
                <AppBarButton x:Name="App_plus" Icon="Add"  FontSize="{StaticResource  MediumFontSize}"  />
            </CommandBar.PrimaryCommands>
        </CommandBar>
```

**Comment by crutkas** [comment]
can you provide a repro / what you generated against?  want to be sure we see the initial bug and see if there is a larger issue.

**Comment by Javier118** [comment]
When I add the rows for the title The Comandbar I add grid. Row = 0, for the Content grid. Row = 1, then the Commandbar falls below the title is supposed to be the same height as the title.

**Comment by crutkas** [comment]
@javier118, having a actual project we can test against is super useful.  Knowing exactly what file, the type of framework, and tons of other permutations could impact what you're trying to do.  Remember we generate ~50 different styles of applications when you factor in navigation pattern, language, and framework + pages and features.

This would help us see exactly what is happening and then see if other permutations are suffering the same issue.

**Comment by mrlacey** [comment]
updated formatting in original post so all code is visible

**Comment by mrlacey** [comment]
@Javier118  I'm assumming this is in the ShareTarget page - can you confirm?

**Comment by mrlacey** [comment]
@Javier118 can you also show a screenshot of what you're seeing?
I've added the CommandBar to the ShareTargetPage as per your sample code but I see the title and comand bar in the same row as expected.

![image](https://user-images.githubusercontent.com/189547/52406520-dad7a400-2ac5-11e9-9b22-747eef6327c9.png)

**Comment by Javier118** [comment]
<img width="960" alt="2019-02-07" src="https://user-images.githubusercontent.com/17751683/52427965-51de5e00-2b01-11e9-8450-b32816803002.png">

version Windows Template studio versión de las plantillas: 3.0.19038.1
Versión del asistente: 3.0.19031.2

**Comment by sibille** [comment]
The header is part of the NavigationViewControl, if you want to show a common header on all pages you can add this to the DefaultHeaderTemplate of the NavigationViewHeaderBehavior in the ShellPage. 
If you want to have a personalized header per page, you can use the NavigationViewHeaderBehavior as explained in https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.md#navigationviewheaderbehavior

You can find a sample implementation in the InkPages.

**Comment by crutkas** [comment]
Hmm, this raises an interesting issue, if it isn't obvious, how do we make someone aware where to put this in.

would a single WTS todo for navigation pane customization be helpful?  Trying to not make it be overkill but this isn't the first instance

`// WTS TODO: If you want to do additional customization such as Commandbars and having a title different than the navigation item, head over to https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.md`

**Comment by mrlacey** [comment]
> would a single WTS todo for navigation pane customization be helpful?  Trying to not make it be overkill but this isn't the first instance

Not a TODO. They are just for things that must be done with the generated code. Optional things can still be commented though.

**Comment by crutkas** [comment]
Issue is without a todo, how is that bubbled up to the single spot it would be located?

**Comment by Javier118** [comment]
Then change the way you put title and CommandBar

**Comment by sibille** [comment]
Not sure what you're asking for. We changed the way we set the title due to how the NavView works. 
Spanish seems to be your native language feel free to ask in spanish, we can translate. 

Hemos cambiado la forma de poner el titulo por como funciona el NavigationView, quien es el que controla el Header. Por el pantallazo que mandaste parece que español es tu idioma nativo, puedes preguntar en español y traducimos, si tienes algún problema en conseguir colocar el command bar.

**Comment by mrlacey** [comment]
> Issue is without a todo, how is that bubbled up to the single spot it would be located?

There can still be a comment in the code, maybe it coudl even point to further docs elsewhere. My point is that we shouldn't be putting optional or informational things in the list of tasks for peopel to do.

**Comment by Javier118** [comment]
La pregunta es si para poner la CommandBar se puede hacer como antes poniendo este codigo  o como dice la documentación para la nueva version WTS:
<Grid.RowDefinitions>
            <RowDefinition x:Name="TitleRow"  Height="48"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <TextBlock
            x:Name="TitlePage"
            x:Uid="Chart_Title"
            Style="{StaticResource PageTitleStyle}" />


        <CommandBar  Grid.Row="0" Background="Transparent" HorizontalAlignment="Right" x:Name="AppBar">
            
        </CommandBar>

**Comment by sibille** [comment]
No puedes hacerlo como antes porque la version del navview que usamos no lo permite. 
Hay que seguir la documentación en https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/projectTypes/navigationpane.md#navigationviewheaderbehavior

Si quieres tener una commandbar commun para todas las paginas puedes definirla en el DefaultHeaderTemplate del NavigationViewHeaderBehavior en la pagina Shell. 
Si quieres personalizarla desde la pagina tienes que fijar el HeaderContext y el HeaderTemplate desde la pagina, te puedes fijar en las paginas de Ink para ver como se hace.

**Comment by Javier118** [comment]
Viendo la documentación he visto que es para ViewModel  y sin ViewModel para Codebehind.

**Comment by sibille** [comment]
Si usas codebehind, tienes que asignar el codebehind de la pagina al HeaderContext y usar Binding para acceder a las propiedades de la pagina a traves del content del shellframe, porque el DataTemplate se ejecuta en el contexto del NavigationView.

-------------------
When using CodeBehind, the HeaderContext is associated to the page's code behind file and use Binding and access the CodeBehind properties through the shellFrame's Content as the Datatemplate is executed in the Context of the NavigationView.

**Comment by sibille** [comment]
@Javier118 has podido conseguir lo que estabas intentando? Voy a cerrar esta issue, reabrela si necesitas mas informacion. 
---------------------------
Could you achieve what you were trying to do? I'll close this issue, please reopen if you need anything else.

**Comment by Javier118** [comment]
si puedes cerrar , ya esta soluccioando.
