### ISSUE TITLE
DataGrid: TextWrapping fixing issue when resizing columns.

### ISSUE THREAD

**Issue by Scnck** [Microsoft/WindowsTemplateStudio#2917]
What is the proper method of applying text wrapping so that when resizing a column it fixs the auto adjust the row height?
```
<controls:DataGridTextColumn Width="300" IsReadOnly="True" Header="Description" Binding="{Binding Description}">
	<controls:DataGridTextColumn.ElementStyle>
		<Style TargetType="TextBlock">
			<Setter Property="TextWrapping" Value="Wrap" />
		</Style>
	</controls:DataGridTextColumn.ElementStyle>
</controls:DataGridTextColumn>
```

**Comment by crutkas** [comment]
I don't know, i would ask the question over at the Community Toolkit, https://github.com/windows-toolkit/WindowsCommunityToolkit or on www.StackOverflow.com.  

@nmetulev and @harinikmsft would know more.

This is outside the scope of WTS and as this isn't a WTS bug, i will close it.
