### ISSUE TITLE
New Feature: Authentication with Azure Identity

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#292]
Make it quick and easy to add authentication with common authentication providers
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-auth
X-Ref #130 

Action Plan: 
- [x] Build mockups for Forced Login and Optional Login
- [x] Get product team feedback
- [x] Give possibility to do exclusive selection on a template group (either choose Forced or Optional Login)
- [x] Do forced login templates
- [x] Do optional login templates
- [x] Update docs
- [x] Update tests

**Comment by grahamehorner** [comment]
was thinking Client Application Services; have a few client using WinForms/WPF application coupled with  Client Application Services

**Comment by mrlacey** [comment]
I'm not familiar with [Client App Services](https://msdn.microsoft.com/en-us/library/bb384339(v=vs.110).aspx) but seems like a reasonable request. 😄

**Comment by myokeeh** [comment]
Yes. It would be nice to have a cohesive example of login, authorization, authentication that promotes good UX.

I just found out that Azure Mobile App SSO got a little worse for UX. https://github.com/Azure/azure-mobile-apps-net-client/pull/326

Version 4.0.0. now opens a separate browser to log-in. Yuck.

**Comment by Javier118** [comment]
I have problem  System.Threading.Tasks.Task<bool> AuthenticateAsync() 
Says the string cannot be converted Newtonsoft. Json. Linq. JObject.

**Comment by mrlacey** [comment]
@Javier118 I'm not sure what you're asking or how it relates to this issue. This issue is a request to add a feature for Azure Mobile Authentication into Windows Template Studio. This hasn't been done yet so your code can't be related to this. 
If you have a general coding inquiry, I suggest asking it on [StackOverflow](https://stackoverflow.com/help/how-to-ask) or the [MSDN forum](https://social.msdn.microsoft.com/forums/en-us/home?forum=wpdevelop).

**Comment by Javier118** [comment]
When authenticated to Azure with Microsoft Account through the MainPage navigate another page where I enter data to the backend gives me a failure the requested could not the completed (unauthorized) as I can fix this Bug. I'm using the version Azure 4.0.0. Mobile. Client

**Comment by mrlacey** [comment]
@Javier118 again, this GitHub issue is for tracking the adding of support for integration with Azure for projects generated by WTS. This functionality is not yet in the product. If you have a problem with or question about code you have written, I suggest you ask at either of the sites listed previously.

**Comment by Javier118** [comment]
I am use  Window Template studio

**Comment by Javier118** [comment]
Meaning the requested could not the completed (unauthorized)

**Comment by sibille** [comment]
We were working on the templates descriptions to be able to localize them. 
Proposals are: 
- Forced Login Template:
  - Short description: Access to the app is restricted with user login.
  - Long description: 
Forced Login adds user authentication using Azure AD and [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client), aka MSAL. 
The access to the app is restricted to logged in and authorized users. If interactive login is required, the user is redirected to a LoginPage before showing the interactive dialog. The same page is shown after logging out.
The application includes a call to the Microsoft Graph to show user info and photo on the NavigationPane and the SettingsPage.
By default this features works with accounts in any organizational directory and personal Microsoft accounts (e.g. Skype, Xbox, Outlook.com) and gives the option to exclude personal Microsoft accounts, limit access to a specific directory or use windows integrated auth.
[Learn more about Microsoft Identity platform.](https://docs.microsoft.com/azure/active-directory/develop/v2-overview)

- Optional Login Template: 
  - Short description: Allows to add restricted content for logged in users.
  - Long description: 
Optional login adds user authentication using Azure AD and [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client), aka MSAL.
The application allows to combine unrestricted and restricted content. Restricted content is only shown to logged in and authorized users.
The application includes a call to the Microsoft Graph to show user info and photo on the NavigationPane and the SettingsPage.
By default this features works with Accounts in any organizational directory and personal Microsoft accounts (e.g. Skype, Xbox, Outlook.com) and gives the option to exclude personal Microsoft accounts, limit access to a specific directory or use integrated auth.
[Learn more about Microsoft Identity platform.](https://docs.microsoft.com/azure/active-directory/develop/v2-overview)

**Comment by sibille** [comment]
Working on the templates, you can checkout the mockup for identity on https://github.com/mvegaca/identity

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19119.1
Wizard version: 0.20.19116.1
