### ISSUE TITLE
Update getting started instructions

### ISSUE THREAD

**Issue by wldevries** [Microsoft/WindowsTemplateStudio#2920]
### Repro steps

* I installed Windows Template Studio 3.0.19038.1 via the VS Installer. 
* I created a blank UWP app
* Right click on the project

### Expected Behavior

I would expect Windows Template Studio to be present in the context menu.

### Actual Behavior

The first time I open the context menu on the UWP application the entry is present, but when I open it I get a weird visual glitch. The second time I open the context menu the Windows Template Studio is no longer available in the context menu.

![image](https://user-images.githubusercontent.com/1745610/52520674-3fccfe80-2c6c-11e9-970a-89a1d840565d.png)

## System

* **VS Version:** 15.9.6
* **WTS Wizard Version:** ??
* **WTS Template Version:** ??
* **Windows Build:** 1809

**Comment by crutkas** [comment]
Was the blank created via wts or the stock VS template.

**Comment by crutkas** [comment]
If it is an app that wasn’t generated via WTS, it would be #663 then. Currently we cannot alter projects we did not create due to the complexity of application development. We would need to make large assumptions and even then, we worry about how well we could merge

This is something that is on our minds on how to best execute this however.

**Comment by wldevries** [comment]
It was a stock VS template blank, so I guess it's a duplicate of the item you mentioned. The weird visual glitch is still a problem I think.

By the way, I had no idea you had to create a WTS specific project. I read the documentation and somehow skipped over it. I think item 2 on page https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md could use a screenshot for emphasis as it is the main entry point of using WTS.

**Comment by sibille** [comment]
Updated the getting started document, thanks for reporting @wldevries
