### ISSUE TITLE
Ink Page secondary commands style too large in Wide view

### ISSUE THREAD

**Issue by TheJoeFin** [Microsoft/WindowsTemplateStudio#2921]
### Repro steps

- Create an app with Ink Pages (InkDraw, InkSmartCanvas, InkDrawPicture)
- Launch app
- Open Ink Page
- Make Window wide enough so the "..." is in the top menu bar
- Click on the "..." button
- Observe text style 

- Shrink Window so the "..." button is in the bottom menu bar
- Click on the "..." button
- Observe text style

### Expected Behavior
Normal style text
https://i.imgur.com/UkKtlt9

### Actual Behavior
Large style text
https://i.imgur.com/8b6fQqA

## System

* **VS Version:4.7.03190**
* **WTS Extension Version: 3.0.19038.1**
* **Windows Build: 17763.253**

**Comment by dgomezc** [comment]
@TheJoeFin thanks to report this error. We think this error is a Win UI NavigationView issue with Windows 10 October 2018 Update. Testing the same application shows fine in Windows 10 April 2018 Update.

We created an issue on their repository.

Meanwhile you can specify the font size on the CommandBar to workaround.

` <CommandBar x:Name="topCommandBar" ...  FontSize="{StaticResource MediumFontSize}">`

**Comment by crutkas** [comment]
Can you xref the issue @dgomezc please.

**Comment by dgomezc** [comment]
@crutkas  Done.

**Comment by dgomezc** [comment]
As mention in Microsoft/microsoft-ui-xaml#307, this is expected behavior. We have to set the commandBar fontsize to default control font size in InkCommandBarStyle:

```xml
<Style x:Key="InkCommandBarStyle" TargetType="CommandBar">
    <Setter Property="FontSize" Value="{ThemeResource ControlContentThemeFontSize}" />
</Style>
```

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19065.1
Wizard version: 0.20.19065.1
