### ISSUE TITLE
VS2019: Rename project names to reflect VS2019 support

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#2941]
Following project names should be changed:

- Installer.2017 -> Installer
- CSharp.UWP.2017.Solution -> CSharp.UWP.Solution
- VBNet.UWP.VS2017.Solution -> VBNet.UWP.Solution

**Comment by crutkas** [comment]
Why not drop the moniker. We will support 2017 and 2019 for a bit

**Comment by sibille** [comment]
Drop the 2017 part? That's what I wanted to say, updated the initial issue to make it clearer,

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19080.1
Wizard version: 0.20.19080.1
