### ISSUE TITLE
Change size of Share target window

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#2996]
## Feature:
I am not sure if this is really possible through WTS or or limited by the UWP framework. The default share window that pops up is too big for some use cases and it should be possible to set a smaller size for the window.

### Repro steps
Add share target feature to the project and try sharing a url link from edge. A window pops up which is too big.

### Expected 
TODO statements to change the share target window size. Or better still if window size can be determined automatically by the content defined in the `SharetargetPage.xaml`

## System

* **VS Version:** 2019 RC1
* **Templates version:** 3.0.19038.1
* **Wizard version:** 3.0.19038.1
* **Windows Build:** 1803

**Comment by mvegaca** [comment]
Thanks, @harvinders thank you for opening this issue. I'll have a look on it!

**Comment by mvegaca** [comment]
Hi @harvinders

We've had a look on share target implementation, it looks like it's not possible to reduce the minimum of the share window size.

The minimum seems to be limited by the platform to 650x683 px.
One of the things that you could do in your app is showing the html content of the link as the mail app does when sharing a link.

![image](https://user-images.githubusercontent.com/5556784/59675663-05e5a900-91c6-11e9-98db-2988fb9253f9.png)
