### ISSUE TITLE
Add a UI test project to solution

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#300]
Add a UI test project to the solution.

This should include a test to launch the app and take a screenshot.

**Comment by jamesmcroft** [comment]
Completely agree that this should be available. 

With this, would we try to generate some basic UI tests for the pages that we add? Say for example, if we had a login page, would we write some UI tests for logging in etc.

**Comment by jamesmcroft** [comment]
Thinking into this further though, would this be optional as it currently is when creating a new blank project?

**Comment by crutkas** [comment]
Yes, I'm going to sync with Yosef Durr on the best way to integrate this support for WinAppDriver.

**Comment by mrlacey** [comment]
As a feature this becomes optional. In line with our current guidance, I was only thinking of a minimal test implementation with comments pointing to docs for more information.
@jamesmcroft  in terms of more complex tests, perhaps they could be an "enhanced page feature"

**Comment by ralarcon** [comment]
I agree with @mrlacey, we can explore the way to allow users to add a "UI test project" like other features... to implement testing logic would be really tough.

**Comment by mrlacey** [comment]
Moving to the next milestone as this won't be ready by the localization deadline.

**Comment by mrlacey** [comment]
Moving to 3.0 as will be dependent upon solution level changes (for Any CPU)

**Comment by crutkas** [comment]
@mrlacey will this be possible for 3.0 or should it be moved to backlog

**Comment by mrlacey** [comment]
Also need to add support for multiple licenses in a single template

**Comment by mrlacey** [comment]
- [x] Also need to add support for multiple licenses in a single template - Done

**Comment by mrlacey** [comment]
waiting for #2527 - will then update and resubmit PR

**Comment by mrlacey** [comment]
Will update and create PR once #2924 is merged

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.20.19066.1
Wizard version: 0.20.19066.1
