### ISSUE TITLE
Refactor Core to return complete TemplateInfo when retrieving templates and light TemplateInfo on generation

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#3001]
Refactor Core to return complete TemplateInfo when retrieving templates and light TemplateInfo on generation

- [x] We should use a lighter TemplateInfo in UserSelection when generating. We only need the name + templateid to generate
- [x] TemplateRepo should have methods that return the complete TemplateInfo +  dependencies when retrieving templates.
- [x] to get supported projectTypes or frameworks two methods have to be called
(e.g. GetSupportedProjecttypes from GenComposer and GetProjectTypes from Repository). This should be done in one method on the TemplateRepo, that returns MetaDataInfo for the supported projecttypes and frameworks

**Comment by mrlacey** [comment]
Is there a technical requirement driving this change?

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19085.1
Wizard version: 0.20.19085.1
