### ISSUE TITLE
Question: How do I resolve errors after Prism.Unity NuGet update to 7.1.0.431?

### ISSUE THREAD

**Issue by myokeeh** [Microsoft/WindowsTemplateStudio#3022]
Is there any guidance available about addressing errors after updating Prism.Unity NuGet to 7.1.0.431? I have searched around to understand some of the history and how to resolve this, but can't figure this out.

**Comment by crutkas** [comment]
I would file an issue with the Prism team.  https://github.com/PrismLibrary/Prism
