### ISSUE TITLE
MapViewModel with doubled "using System"

### ISSUE THREAD

**Issue by azchohfi** [Microsoft/WindowsTemplateStudio#305]
I created a simple project:
Project Type: Navigation Pane
Framework: MVVM Basic
Added one Map page, and the PageViewModel has two instances of **using System;**

**Comment by mrlacey** [comment]
Obviously this shouldn't happen. 
It's an issue with a template and easily fixed. 
In addition to addressing the template issue I wonder if it's going to be necessary to add a check for duplicate using statements when we sort them. 
As templates get more complex and multiple features necessitate adding to the same file, multiple combinations of items may mean it's not possible to avoid things like this happening. 
Thoughts anyone?

**Comment by skendrot** [comment]
Can the "remove and sort using" command be ran?

**Comment by mrlacey** [comment]
@skendrot there's a "SortUsings" action run as part of the generation process already. I'll extend this to remove duplicates. Unfortunately, it can't be run separately.

**Comment by crutkas** [comment]
@azchohfi good catch.  Non-critical but is crappy code generated.  Also looks like @mrlacey has entered beast mode and already provided a fix.

**Comment by crutkas** [comment]
merged into dev branch now.

**Comment by mrlacey** [comment]
closing as has been in dev branch for a while and verified with the latest nightly (0.14.17144.95001).
