### ISSUE TITLE
Custom Title Bar, if not a page option, it should be.

### ISSUE THREAD

**Issue by mdtauk** [Microsoft/WindowsTemplateStudio#306]
With Acrylic being pushed in the UI, more apps will start extending into the TitleBar area, so will there be a per-page option for this in the app, and if so, placing the Window Title textblock with the localised string, and appropriate styling.

**Comment by mrlacey** [comment]
Expect a complete updating of the default UI when support for the Fall Creators Update is added.

**Comment by skendrot** [comment]
What would WTS do o support this? Making your app extend into the title bar is only a couple lines of code.

**Comment by mdtauk** [comment]
@Skendrot It could be a checkbox option when adding pages.  That page would then have the TextBox to display the Window Title, add the code to extend the CoreWindow bounds, and set a grid object to be the custom Title Bar object, to allow dragging the window with it.  It could also handle the back button.

**Comment by mrlacey** [comment]
Already working on extending into the title bar for #196 so extending that for this will be easy.
For this, we'll take guidance from the design team on what should be added and where. We'll review all the generated UI when fully supporting Fall Creators Update.
Right now I can see doing this for Pivot and Tabbed pages but others will be better decided upon later.

**Comment by crutkas** [comment]
@mdtauk it is unclear what this actually is asking for.  I think this can be made much more clear and i'm afraid the original ask here isn't being addressed.

**Comment by mdtauk** [comment]
@crutkas  Basically, when adding a page within the wizard.  An option which when checked, automatically adds the code required to extend the app UI where the titlebar is.  

I believe the code involves picking a XAML object to act as the Titlebar.  Text to display the Window Title. Styling for the Window Buttons, and the Back Button implemented.

**Comment by mrlacey** [comment]
Because of Sets, the recommendation is now to not put anything in the TitleBar.
Based on this recommendation, it would not be wise for us to add a feature that encourages extending the app into the title bar.
