### ISSUE TITLE
Why does the MapPage include a `TickBar`?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#3060]
The generated XAML on the `MapPage` includes a `TickBar`. Why is this?

Example [here](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/templates/Uwp/Pages/Map/Views/MapPagePage.xaml#L15)

According to the [docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.tickbar), this is a primitive control used within a `Slider` and is not intended for general use.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.20.19116.1
Wizard version: 0.20.19116.1
