### ISSUE TITLE
Allow features to only be displayed if appropriate workload is installed

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3067]
For #133 (Add WebAPI project) and possibly other things in the future 😉, it will be necessary to only include some feature options if the appropriate Visual Studio workload is also installed.

To do this, I propose the following:

- Add a new tag `wts.requiredWorkload`
- If specified, (e.g. `"wts.requiredWorkload": "Microsoft.VisualStudio.Workload.NetWeb"`) the feature would only be displayed if the specified workload is installed in Visual Studio.
- If the workload is not installed the feature will not be installed.
- Multiple workloads can be specified by using a pipe delimiter. (As we do with other tags.)
- This needs to consider inclusion based on dependencies also. (i.e. if **A** depends on **B** and be has a dependency on something that is not installed, neither **A** nor **B** should be made available.)

Questions:
- Should this be enabled for pages as well as features?
- Is there an alternative/better way of achieving the same result?

**Comment by harvinders** [comment]
@mrlacey I think instead of "not displaying" it should be grayed out and somehow a reason should also be provided, i.e which component should be installed to get the feature/page back.

**Comment by mrlacey** [comment]
The behavior I described was based on what other new project dialogs (i.e. Xamarin.Forms) do.

If you haven't installed the ability to create web based solutions, would you really care that the tool could add something that relies on it? (I don't think everyone would answer the same way.)
Additionally, this could lead to a situation in the future where lots of things that can't be used, and therefore selected, are listed. I don't think that would be helpful.

_I also know that any change to the UI of the wizard is a lot of work and likely to delay the implementation of such a feature. Changes without a UI change can be done faster. ;)_

If not displaying something because of a missing dependency we could put details of why in the output pane. This would mean we're not hiding things with no details/explanation.

**Comment by mrlacey** [comment]
Doing for pages & features (although we won't have any pages that use this initially.)

VSEmulator will not have this capability and will always show items even if the relevant workload is not installed.

**Comment by crutkas** [comment]
I'm thinking about this, i feel like we should prompt or warn.  I can see scenarios a project would want to be generated but maybe not buildable on someone's current machine.

**Comment by mrlacey** [comment]
> I can see scenarios a project would want to be generated but maybe not buildable on someone's current machine.

This argument goes against the concept of workloads in VS. If people wanting to create apps they can't then build was a common scenario, wouldn't all templates always be available to everyone in VS?
I can also see this being a cause of potential confusion and support issues in the future > "Something's broken because the generated app won't compile!"

**Comment by mrlacey** [comment]
Currently waiting on the merging of #3128

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.20.19159.1
Wizard version: 0.20.19159.1
