### ISSUE TITLE
Make project generation faster

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#307]
It'd be great to make the time between clicking 'create' in the wizard and being able to work with what's generated as short as possible.

**Comment by crutkas** [comment]
Here is the odd thing i noticed here, in the emulator, we're pretty damn fast.  inside VS, it feels much slower.

**Comment by mrlacey** [comment]
By "emulator" do you mean "experimental instance"? 
I suspect that's due to other extensions not loaded by the experimental instance.

**Comment by ralarcon** [comment]
I think references the VsEmulator project under the tests. The generation itself is pretty fast, the inclusion of elements in the solution / project thru IDE automation objects make the VS experience much slower.

**Comment by mrlacey** [comment]
Bumping to v1.3 as no time for this now as large potential for regressions  in the core engine

**Comment by crutkas** [comment]
I agree with @ralarcon here, in the emulator, we're wicked fast generating.  we should see where time is truly being allocated inside VS that is causing this.  If it is an issue on us, we fix, if it is on them, lets see if we can't get this corrected.

**Comment by crutkas** [comment]
@mrlacey, is this a real thing?  I feel we make it fast but actual VS is slow for properly building.

If this can't be done, we should close this.

**Comment by mrlacey** [comment]
Yes, VS is slow but have we yet looked at if there's anything we could do to help VS be faster when generating a project? I haven't.

Moving to the backlog as not a priority but not something we should just dismiss as not our problem.

**Comment by ralarcon** [comment]
Apart from restoring the package which is time consuming, we use the VS automation to include the generated items (xaml, cs, certificate, etc.) to properly compose the project file (csproj, vbproj). Adding this pages thru VS Automation is quite time consuming too. In the emulator we compose the project file "manually"... maybe we can port this idea to the real project generations and add the project to the solution once is created, instead add items on the fly.
 
One option we can consider is to allow the users avoid the "package restoring" to speed up the project availability (but this lets the project open with lots of intellisen errors)

**Comment by crutkas** [comment]
this is pretty old.  do we feel we can improve stuff or should we close this out

**Comment by mrlacey** [comment]
Maybe review this in the future if it's felt to be an issue then. With lots of things changing at the moment (VS2019 & multi-project output) it seems like a bad time to be reviewing optimizations or other ways of changing the way generation works.
