### ISSUE TITLE
3D Launcher not available on right click

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3095]
#### Overview

3D launcher should be available from right click, I was reviewing the code of this feature and I think we should include it on the right click mode of WTS.

* **WTS Wizard Version:**
3.1.19092.1
* **WTS Template Version:**
3.1.19092.1

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19273.1
Wizard version: 0.20.19273.1
