### ISSUE TITLE
Depending on what level all of this is being pitched, I would think that a happy medium is the place to go whereby you could have a gui front end that allowed you to select if you wanted all of the classes set up. I am not one for plagiarism but I envisage it something like Radzen have done (see tick boxes at top of screen to create CRUD etc)

### ISSUE THREAD

**Issue by flaviofaraujo** [microsoft/WindowsTemplateStudio#3100]
Depending on what level all of this is being pitched, I would think that a happy medium is the place to go whereby you could have a gui front end that allowed you to select if you wanted all of the classes set up. I am not one for plagiarism but I envisage it something like Radzen have done (see tick boxes at top of screen to create CRUD etc)
![ms-sql-auto](https://user-images.githubusercontent.com/31215901/29556706-8c312516-871e-11e7-8987-edb003418ad8.gif)

_Originally posted by @OtisRanger in https://github.com/Microsoft/WindowsTemplateStudio/issues/900#issuecomment-323960508_

**Comment by crutkas** [comment]
?  Can you explain a bit more on why this issue was opened.

**Comment by mrlacey** [comment]
This is out of scope as we're not going to create this type of DB based form generation tool as part of this project.
