### ISSUE TITLE
Update Nuget Packages in templates

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3104]
We should update two nuget packages in templates
 - **Microsoft.UI.Xaml**
 - Newtonsoft.Json to 12.0.2
 - Microsoft.Xaml.Behaviors.Uwp.Managed to 2.0.1

**Comment by sibille** [comment]
Issue https://github.com/Microsoft/microsoft-ui-xaml/issues/599 causes build failures when using Microsoft.UI.Xaml version 2.1.190405004 and adding "Test App with MSTest" or "Test App with xUnit" features

**Comment by sibille** [comment]
Issue is fixed on WinUI side, waiting for next version to be released.

**Comment by sibille** [comment]
Updated to version 2.1.190405004.2 where this is fixed

**Comment by mvegaca** [comment]
Updated
 - WinUI
 - Telerik
 - MSAL
 - nUnit
 - MSTest
 - AdaptativeCards
 - AppCeter Analytics

**Comment by mrlacey** [comment]
The change also includes alterations to auth related templates?
Is this a consequence of updating the referenced version of MSAL? or something else?

**Comment by sibille** [comment]
yes, update to Microsoft.Identity.Client 4.0.0 required some changes in the code

**Comment by sibille** [comment]
New version of Microsoft.AppCenter.Analytics and Crashes was released: 
Update Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes to 2.1.0

**Comment by sibille** [comment]
More new packages:
- Update Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes to 2.1.1
- Update Microsoft.NET.Test.Sdk to 16.2.0

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19183.1
Wizard version: 0.20.19179.1
