### ISSUE TITLE
Better support / Need more specific error for offline use

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#311]
"Error updating templates. See output for more details." is not helpful enough. Can we add a more specific error if unable to download templates as offline.
Would also be good to add a retry option without having to close the wizard.

Repro:
- Install VSIX
- Go offline
- File > New > WTS

nothing downloads and have to close our dialog and the Choose Project type dialog before can see the output window. :(

**Comment by crutkas** [comment]
Agreed, we need better offline support.  If you have a cached version, it should continue to run.

**Comment by mrlacey** [comment]
Changing the milestone on this as a real report of this problem was marked for addressing as a critical bug fix.

**Comment by ralarcon** [comment]
I'm assiging this to myself as I will be working on it.
