### ISSUE TITLE
Question: Should framework be chosen before navigation mode?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3124]
The current wizard (images below) asks the user to choose the navigation style for the application before selecting the MVVM framework (or none/code-behind) to use.

- Does this order seem right to you?
- Does it feel more natural to select the framework to use before the navigation style?
- If you feel the order should change, how important of an issue is this?

Please comment with your thoughts below.

---

**How things are currently**

The wizard first asks you to select the "Project type" (or navigation pattern)

![Project Type selection step in Wizard](https://user-images.githubusercontent.com/189547/57715538-e8756a80-766e-11e9-9e37-514b96af53a7.png)

Secondly, the wizard prompts for the "Design pattern" (or MVVM framework) to use.

![Design Pattern selection step in wizard](https://user-images.githubusercontent.com/189547/57715592-08a52980-766f-11e9-8b4b-46b99472e34d.png)

**Comment by harvinders** [comment]
Though we know it does not matter, but I see the point.

**Comment by mrlacey** [comment]
There was [some discussion on Twitter here](https://twitter.com/mrlacey/status/1128669958890774531).

There are good arguments for either option.

If we were starting again now, I might debate the options a bit further but right now it doesn't seem as though this is something worth changing.
