### ISSUE TITLE
cant display Chinese normaly on the controls

### ISSUE THREAD

**Issue by Jason190** [Microsoft/WindowsTemplateStudio#313]
the Chinese char display "?"
how can I display Chinese with template studio?

**Comment by skendrot** [comment]
Can you give more details?

**Comment by mrlacey** [comment]
@Jason190 What character(s) are you entering and where?
I can enter Chinese and Cyrillic characters in every place text can be entered and these display fine for me in both the tool (summary section) and in the generated app.

**Comment by Jason190** [comment]
![image](https://cloud.githubusercontent.com/assets/10508510/25985917/bc6f29de-371f-11e7-9bc4-f19313bd0844.png)
it look fina in designer and code. But when run it up. it trun out:
![Uploading QQ截图20170512143505.png…]()
oops, the picture upload always failed. And I don't know how to descrip it .
just ..... a blank "?" in dark diamond for a char
what's more, I use the win10 insider preview version. Is that matter?

**Comment by mrlacey** [comment]
This isn't an issue with WTS. You'll see the same if you created a blank project and added that text.
That you're on an insider preview version is a red flag. Which version are you on? I suspect this is the issue.
Can you also include the text you're entering, not just a picture. This would also help those of us who can't type Chinese characters :(

**Comment by Jason190** [comment]
@mrlacey Hi, Thanks for your reply. I have try to create a blank project without WTS. The display is ok.>_<
my os win10 insider preview build 16193. vs 2017 15.2(26430.4)
I think the problem maybe in the Unicode Transformation Format. But I don't  know how to change it. at least, Chinese display is ok with vs stand alone.
and those are some Chinese char below:

你好，我的vs无法输入汉字，你知道是怎么回事吗？
and you can use google translate to get what you want to say.

**Comment by mrlacey** [comment]
@Jason190 I can't repro this can you zip up one of your generated projects and share so we can look at the file encodings from your machine.

**Comment by crutkas** [comment]
@Jason190 I agree with Matt, if you can provide a repro, that would be helpful.  me looking at your code, that looks like it should work and at that point, we've fully generated the code and it is in VS's hands

**Comment by Jason190** [comment]
@mrlacey @crutkas 
Hi, guys
thx for your reply.
I have upload a repro https://github.com/Jason190/WTStest
I create a new project with WTS tool and add a <textblock>only. I didnt change others
BUT I NOTICE THAT when I open the MainPage.xaml the code has changed into Garbled instead Chinese char. I DONT KNOW WHAT HAPPEN. and I just upload the code with nothing to do.
Do you have any idea?

**Comment by Jason190** [comment]
OK, guys
I have solved the problem.
As what I am thinking the coding method is wrong. The default coding method is not utf-8. Just change the method to utf-8 problem solved.
What's more the settings is hide in default VS settings. So the problem confused me for days. If there are anybody have same problem you can follow below:(should I write in Chinese?)
view->tool bar->custom->command tab->add command button->file->advanced saving options
then use the item change the coding method to utf-8.
then build. everything goes well.

And thank you for all the guys who follow the problem.
this issue will be closed.
Jason

**Comment by crutkas** [comment]
Glad you fixed it!
