### ISSUE TITLE
Fix outstanding TODO actions in code

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3144]
There are many `TODO` comments in the code base which make reference to waiting for events that have been passed.
e.g.

```csharp
// TODO: Remove this when 3.0 is released, only necesary for legacy tests

// TODO: This is needed to make legacy tests work, remove once 3.1 is released

// TODO: Enable legacy test when version 3.1 is published+

// TODO: Re-enable for all platforms
```

Based on these comments there are some which can (should?) be addressed now.

There are also some comments where it's not clear when/if/how they will be addressed. If there are things in the code that need to be addressed, issues should be created so we can keep track of the work that needs to be done and the comment should be updated to include the issue number.

**Comment by sibille** [comment]
thanks for reminding, will fix those

**Comment by mrlacey** [comment]
> thanks for reminding, will fix those

If you want the IDE to nag you about them in future, [consider using this so they show up as warnings too](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WarnAboutTODOs).
It's easy to ignore items on the Task List, harder when you see them as warnings ;)

**Comment by sibille** [comment]
Verified in dev
