### ISSUE TITLE
Update documentation for Navigation

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3150]
It seems that the documentation for [advanced navigation](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/navigation-advanced.md) is no longer current.

#### Expected Behavior
It should be possible to follow the documentation examples and incorporate the changes in the current version of WTS

#### Actual Behavior
Compilation errors

### System
Templates version: 3.2.19120.1
Wizard version: 3.2.19120.1

**Comment by sibille** [comment]
Thanks for reporting, will adjust the document to reflect the latest changes

**Comment by mvegaca** [comment]
Doc Updated #3158

**Comment by mvegaca** [comment]
Some updates for this doc on next 3.3 version #3172 3172

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.20.19183.1
Wizard version: 0.20.19182.1
