### ISSUE TITLE
TogglePaneButton always get focus while loading app

### ISSUE THREAD

**Issue by hupo376787** [microsoft/WindowsTemplateStudio#3152]
### For Bugs:
I'm using `Microsoft.UI.Xaml.Controls.NavigationView`, and set `IsPaneToggleButtonVisible="True"`.

And I use the below code to show who is getting focus
```
//Display who is getting focus
this.GotFocus += (object sender, RoutedEventArgs e) =>
{
       FrameworkElement focus = FocusManager.GetFocusedElement() as FrameworkElement;
       Debug.WriteLine("Shell Page Got focus: " + focus.Name + " (" + focus.GetType().ToString() + ")");
};
```

When app launched, I received
`Shell Page Got focus: TogglePaneButton (Windows.UI.Xaml.Controls.Button)`
#### Repro steps
Use WTS to create a NavigationView project, add the code above.

Now I want to control the `FocusState `using code, how to do?

**Comment by mrlacey** [comment]
This is not a WindowsTemplateStudio issue. This is down to the way the `NavigationView` control works in response to needing to set focus on something.

The focus has to be on something. When the NavigationView is the main focusable control on the page it takes the responsibility of assigning this and it set focus on the toggle button presumably as it's the first focusable child item.


If you want to set the focus on something pragmatically, just call  `myControl.Focus(FocusState.Programmatic);`


If you want to question why the `NavigationView` behaves this way, or suggest that it be changed, raise an issue on the [WinUI](https://github.com/microsoft/microsoft-ui-xaml/) repo. Note that the focus has to be on something (and preferably something useful) for many reasons, including accessibility .
