### ISSUE TITLE
Dev-nightly: Testing features are not showing in the testing group

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3159]
Seems we have lost the "testing" group under features, templates are showing outside of groups:

![image](https://user-images.githubusercontent.com/24698018/58422300-80714c00-8092-11e9-8a0c-8842c861e43c.png)

**Comment by mrlacey** [comment]
I noticed this had gone away last week.
I've put this back in other work that I will shortly raise a PR on.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19160.1
Wizard version: 0.20.19160.1
