### ISSUE TITLE
Support generating WPF apps

### ISSUE THREAD

**Issue by grahamehorner** [microsoft/WindowsTemplateStudio#316]
Please consider supporting WPF templates and/or that generate both WPF/UWP UIs for projects

**Comment by mrlacey** [comment]
What specific pages, features, frameworks, etc would you like to see with WPF support?
The more specific details you can provide the more it helps with planning and prioritization.

**Comment by crutkas** [comment]
@grahamehorner what is your scenario here.  Supporting WPF would be a large engineering effort to keep parity.  why WPF over UWP?

**Comment by grahamehorner** [comment]
IMO to make this tool really useful for my use case; I would need to create both WPF/UWP user interfaces with shared logic in a satellite assembly; as a large number of businesses have systems which run older operating systems that don't support UWP or have older applications that prevent the move to new operating systems.  

You just need to look at the cyber attack and it's impact/number of systems effected to understand there is still a large user base running systems that can't run local UWP apps Windows 8/8.1

**Comment by mrlacey** [comment]
That there are lots of older systems in use isn't of itself proof that people are continuing to build for them.

If WPF is needed what is required in terms of basic structure and pages? Are, for example, the WPF apps you're building using nav panels and pivots?

**Comment by crutkas** [comment]
@grahamehorner UWP is Windows 10 only.  Based on what you're discussion, wouldn't the desktop bridge be a better option for you?  We take a lot of dependencies on Win10 only features.  What we made should work with WPF but for us to make a WPF template branch would require a lot of effort.

If you want to share a more detailed information on your customer base, please email me crutkas@microsoft.com.  Would love to understand your data about your user population and their constraints. That will help us make more informed feature decisions.

If you're interested in contributing back and doing a PR with WPF, happy to see how this best fits in.

**Comment by mrlacey** [comment]
Moving to Open Community Questions to see if there's (still?) demand for this

**Comment by mrlacey** [comment]
What project/navigation types would apply here?
- classic/main menu?
- ribbon menu?
- blank / roll your own (like with current UWP support)

any others?

**Comment by mrlacey** [comment]
Notes from recent discussion about this:
- We need lots of planning here
- Need clearly defined goals for doing this
- Need to sync with plans from VS, XAML, & Mike H's team
- Projects would default to targetting Win10 & include WinMD reference and have VS packaging project enabled.

**Comment by crutkas** [comment]
this should be executed w/ .NET Core 3

**Comment by rido-min** [comment]
@crutkas  @sibille any ETA to support WPF on .NET Core 3 ?

**Comment by mrlacey** [comment]
@rido-min I wouldn't expect anything until .Net Core 3 is officially released. (Remeber it has only just gone into preview.)

**Comment by Postlagerkarte** [comment]
Since WPF is getting some love recently and Build 2019 has a session called "Windows Template Studio - WPF Edition" - do you have any news on the plans/eta for us?

**Comment by crutkas** [comment]
I am one of the speakers for this 😁

**Comment by mrlacey** [comment]
Another common WPF pattern I've seen is where every "page" opens in a new window. Is this something that should be supported?

**Comment by calloncampbell** [comment]
> Since WPF is getting some love recently and Build 2019 has a session called "Windows Template Studio - WPF Edition" - do you have any news on the plans/eta for us?

Will this session be available online (YouTube or Channel 9) post Build 2019 conference?

**Comment by crutkas** [comment]
> Will this session be available online (YouTube or Channel 9) post Build 2019 conference?

It was a sneak peek were we were valid a couple open questions.  Navigation patterns, look&feel, critical functionality, and the frameworks needed

**Comment by sibille** [comment]
We created issue https://github.com/dotnet/wpf/issues/1378 and would love to hear your feedback their on what to start with for new project templates for WPF with .NET Core 3.0 in WTS.

**Comment by sibille** [comment]
We finished work on our first WPF mockup and would love to get your feedback on issue 
https://github.com/microsoft/WindowsTemplateStudio/issues/3318

**Comment by sibille** [comment]
WPF templates are now available in our pre-release version: 0.24.20185.1
