### ISSUE TITLE
SQL Server feature enhancements

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3175]
Had a look at this feature and suggest to: 
- Add a doc page that explains setup and usage, link to sql server docs (sql express, management studio, northwind db)
- Add a config file 
- Add developer TODO's for not having sql statement in code and exception handling
- Add link to SQL best practices
- Should this have a complete CRUD instead of only read example?

**Comment by mrlacey** [comment]
> Add a doc page that explains setup and usage, link to sql server docs (sql express, management studio, northwind db)

links to 
- https://docs.microsoft.com/sql/sql-server/sql-server-technical-documentation
- Northwind: https://www.microsoft.com/en-us/download/details.aspx?id=23654


> Add a config file

Ok. But will require modifications to Identity templates which already include a config file.

> Add developer TODO's for not having sql statement in code and exception handling

What's wrong with "having sql statement in code"? Or is this just to include a general warning about the potential for issues if not done correctly? 

I can add a comment to the exception handler of the `AllOrders` method but that's a method that's intended to be removed anyway. What could be added that would be useful? 

> Add link to SQL best practices

Any suggestions for this?

> Should this have a complete CRUD instead of only read example?

We don't have CRUD examples for anything else. This would require adding a number of data access operations and the UI to accompany them with the expectation that they would just be removed. It doesn't feel an appropriate addition. It would be like adding a complete, mini sample to the generated app and that's not something we do anywhere else.

**Comment by sibille** [comment]
- Config file:
Yes, this would need a change in Identity templates. I think we should always add the config to the project, and have postactions for the Identity and SQL Data feature.
- SQL Statement in code:
It's fine for an example, but I'd like to call out, that for production code you should use stored procedures for maintainability and security reasons.
- Exception Handling: 
Sorry, my fault, wasn't aware that the whole method is really sample code and will be deleted. Maybe we can still add a comment saying handle exceptions appropriately to your scenario. 
- Link to best practices:
@crutkas, are you aware of any SQL best practices docs we can link to? Was thinking of things like avoiding SQL Injection, …
- CRUD: 
I think a full usage example would be too much, but having sample Add/Update/Delete methods would help beginners. I think it would also be helpful to have generic methods for opening connections and getting the datareader, to separate the sample code from reusable pieces.

**Comment by mrlacey** [comment]
> I think we should always add the config to the project, and have postactions for the Identity and SQL Data feature.

I was thinking of adding it as a hidden dependency feature. I don't see a need to always include it in every app that is generated.

> I think it would also be helpful to have generic methods for opening connections and getting the datareader, to separate the sample code from reusable pieces.

I was deliberately trying to avoid anything that tries to teach people how to use the technology. The aim is to make something possible not say how to do it. If you don't know how to use T-SQL this isn't the best place to learn.
Similarly, providing generic methods risks implying that these are the only way to use the generated code. There are already countless ways (helpers, libraries, tools, etc.) to make SQL data access easy. I don't think we should be providing another.
As you're so against having SQL in the code, how would this even work with the generic methods you propose?

**Comment by sibille** [comment]
Hidden dependency feature works!

I don't see another option than having SQL in code to put together a SampleOrder (which I think is a great idea). I'm just concerned about a beginner seeing this and taking it as "best practice". I think we should make very clear that this is an example and link to a good place to learn about how to get started with using SQL and SQL Server.

**Comment by JamesHHoustonII** [comment]
I think the biggest issue is not the Sql connection is extracting. But how to use the access token or oid token provided using MS Graph, B2B or B2C for CRUD operations.

**Comment by mrlacey** [comment]
Verified in 
Templates version: 0.20.19184.1
Wizard version: 0.20.19184.1
