### ISSUE TITLE
Use Onedrive toolKit service with WTS Login

### ISSUE THREAD

**Issue by Javier118** [microsoft/WindowsTemplateStudio#3179]
I have an app where the menu added the option WTS Login for MSA services as I can join the service Onedrive Windows ToolKit to Login.

**Comment by sibille** [comment]
I'm not sure I fully understand what you're asking for: 
Are you trying to use the OneDrive Service from the Communtity Toolkit (https://docs.microsoft.com/en-us/windows/communitytoolkit/services/OneDrive) after login in with one of the WTS Identity features?
What problems are you facing?
Or is this a request for a new feature?

**Comment by Javier118** [comment]
If log in can open Onedrive service, at WtS this will work with Skype, Outlook.com with OneDrive would run
![Captura de pantalla (2)](https://user-images.githubusercontent.com/17751683/59355380-270e4b80-8d27-11e9-9ea2-ed9af886c0d1.png)

**Comment by mrlacey** [comment]
@Javier118 At the moment, WinTS does not provide a selectable item to handle authentication with the Microsoft Graph (which is what you need to access OneDrive services.)
This is something that we hope to have in the future as it is also needed for #3122 but the libraries they provide to help with authentication don't yet work in the same way (via MSLA) as the Identity templates WTS currently has.

**Comment by Javier118** [comment]
version WTS :  3.2.19120.1

**Comment by Javier118** [comment]
So how can I dock OneDrive service Toolkit in WTS Log in

**Comment by Javier118** [comment]
With the backend in Azure is compatible.

**Comment by Javier118** [comment]
Well in the code part you can implement the OneDrive connection of Toolkit service.

**Comment by mvegaca** [comment]
You can not use the Toolkit OneDriveService and combine it with WTS Identity, What I recommend you is to use WTS LogIn and add methods to the MicrosoftGraphService (Core project) to retrieve OneDrive files.

See all OneDrive api calls
https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0

Try to get api calls on Graph Explorer
https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by mvegaca** [comment]
Another possibility is to add a reference to the Graph SDK in your project
https://github.com/microsoftgraph/msgraph-sdk-dotnet

You can use the WTS Identity that uses MSAL and use the Graph toolkit to consume OneDrive services.

**Comment by sibille** [comment]
Closing this, @Javier118 please open a new issue if you have any problems with the graph calls and WTS Identity
