### ISSUE TITLE
Mobile App Service Enhancements

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3181]
We had a look at the Mobile App Service and have the following questions/proposals: 
- this should have more comments on how to use, developer TODOs + links to web api  docs
- we should change [Route("api/item")] to [Route("api/[controller]")] as Visual Studio does when creating a web api 
- Can we change the name to "Web API" instead of "Mobile App Service"?
- Should we have a doc on how things play together in different scenarios?

  - UWP -> HttpDataService -> API Controller ->  SampleDataService
  - UWP -> HttpDataService -> API Controller -> SqlDataService
  - UWP -> SQLDataService

**Comment by sibille** [comment]
Deleted first point as this is the same as #3180

**Comment by sibille** [comment]
Reviewing the nuget package updates we came up with a few questions more: 
- Should this be aspnet core 2.2?
- Should use **Metapackage Microsoft.AspNetCore.App** instead of  Microsoft.AspNetCore.App Version="2.1.1" and Microsoft.EntityFrameworkCore Version="2.1.11"

**Comment by mrlacey** [comment]
> * Should this be aspnet core 2.2?

Targetting 2.1 (rather than 2.2) as 2.1 is the Long Term Servicing (LTS) version. Want to push people to the version that is supported for longer by default. They can upgrade if they wish.

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.20.19186.2
Wizard version: 0.20.19186.2
