### ISSUE TITLE
Http Data Service enhancements

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3182]
We had a look at the Http Data Service and have the following questions/proposals: 
- This needs some developer TODO's and links to docs
- There are some minor differences in the code that we have doubts on: 
  -  Why is DeserializeObject is done inside a Task.Run, Serialize object isn't?
  -  Why is the post method sending a string, and the put method an array?

**Comment by mrlacey** [comment]
@sibille For both these questions, the answer is "I don't know, this code came from the Xamarin template."

To guess though:

> Why is DeserializeObject is done inside a Task.Run, Serialize object isn't?

My guess is to aid performance as deserialization has the potential to take longer than serialization and so this should help with UI responsiveness. Especially with deserializing large responses.

**Are you happy to keep the difference?**

> Why is the post method sending a string, and the put method an array?

My guess is to show both options. **Do you think we should standardize on one serialization method? or are you happy to stick with both variants?**

**Comment by sibille** [comment]
@mrlacey

> My guess is to aid performance as deserialization has the potential to take longer than serialization and so this should help with UI responsiveness. Especially with deserializing large responses.

Ok, that makes sense, thanks for the explanation. Lets keep it as it is.

> My guess is to show both options. Do you think we should standardize on one serialization method? or are you happy to stick with both variants?

Can we do PostAsJsonAsync and PostAsync +  PutAsJsonAsync and PutAsync so devs have all options and can delete those they wont use?

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.20.19186.2
Wizard version: 0.20.19186.2
