### ISSUE TITLE
TODO comment casing consistency

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#322]
The comments added to the generated project starting "TODO UWPTemplate" are inconsistently cases. 
A couple are all uppercase but shouldn't be.

**Comment by crutkas** [comment]
YES!  I noticed this!  I actually think it is in a few more spots, looking now

**Comment by crutkas** [comment]
actually, looks like you nailed it

**Comment by mrlacey** [comment]
@crutkas disappointed you doubt my ability to GREP

**Comment by crutkas** [comment]
I have an older brother, i live by #trustButVerify :)
