### ISSUE TITLE
WTS: How to access user information 

### ISSUE THREAD

**Issue by jhhouston** [microsoft/WindowsTemplateStudio#3231]
I have been unable to access the user information. Below is a snippet where I use an access modifier that should allow me to print out the user name or userPrincipalName  so that I can do what I want with it. How is this accomplished?

 public UserDataService UserDataService => Singleton<UserDataService>.Instance; //Its all here
                     
        private UserData _user; //this is null

        public UserData User
        {
            get { return _user; }
            set { Set(ref _user, value); }
        }

        public TrailPage()
        {
            InitializeComponent();
            Print();
        }

        public void  Print()
        {
            UserData ud = new UserData();
            
            var messageDialog = new MessageDialog(" Username is '" + ud.Name + "'");

        }

Thanks
#### Overview

What you'd think should be added with scenarios

#### Repro steps

What did you do? How can someone else reproduce this?

#### Expected Behavior

What was expected to happen
(include screenshots if a visual issue)

#### Actual Behavior

What really happened

### System

* **VS Version:**
* **WTS Wizard Version:**
* **WTS Template Version:**
* **Windows Build:**

**Comment by sibille** [comment]
Hi @jhhouston, could you give us more information to better understand your scenario? Which WTS version are you using? What framework and project type did you chose when you generated your app? Are you using Forced or Optional Login?

You can find a sample of how to display the username on the Settings Page and the Shell Page if you are using a Navigationview project type.

**Comment by mrlacey** [comment]
This issue has been waiting on more information without a response so closing.
This looks to be a general UWP related question and not specific to WinTS but feel free to one with more information (see above) if necessary.
