### ISSUE TITLE
Project Template name doesn't include " (Windows Universal)"

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#324]
![image](https://cloud.githubusercontent.com/assets/189547/26013284/82a06ff0-370c-11e7-95c7-dfc382abd67d.png)

Add the label for consistency with other entries and to make it clearer that this is UWP only.

**Comment by crutkas** [comment]
I want @mbcrump opinion on this.  My thought is if we support Xamarin, we fit into multiple categories then and this becomes a void issue

**Comment by degant** [comment]
If you support Xamarin templates too, then wouldn't it make sense to have the 'Windows Template Studio' template appear in the Xamarin/Cross-Platform tab as well? 

In that case it might sense to have _'Windows Template Studio (Universal Windows)'_ as the title here and similarly have a different one in the Cross-Platform tab _'Windows Template Studio (Xamarin.Forms or Native)'_. Both can launch WTS in different modes (UWP or Xamarin wizard) which can be changed later in the wizard.

**Comment by crutkas** [comment]
I now remember why this do this.  if you go to the root level (Visual C#), you have multiple flavors of "projects".  Example you have "Class Library" for .NET, .NET Standard and UWP.

Lets figure out the Xam thing then we can append.

**Comment by mrlacey** [comment]
If we include Xamarin support then the whole name needs reconsidering.

**Comment by crutkas** [comment]
Lets add in now, we'll have to revisit shortly.

**Comment by mrlacey** [comment]
@crutkas do you still want to add this in now? and for v1.1? If we add Cross-Platform/Xamarin support I expect it'll be in the Cross-Platform folder and so might be good to have a different suffix to distinguish the different options.

**Comment by ralarcon** [comment]
The change is easy. Doing it know.

**Comment by ralarcon** [comment]
Included in PR #478

**Comment by ralarcon** [comment]
Verified
