### ISSUE TITLE
Dev-nightly: Wizard fails when adding and removing WebAPI

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3244]
1) Create new project
2) Add WebAPI
3) Delete WebAPI

**Comment by mrlacey** [comment]
@mvegaca was this caused by something specific in the WebAPI template or because of other recent changes made to the wizard?

**Comment by mrlacey** [comment]
Was this discovered in manual or automated testing?

If only in manual we need to create a follow-up task to add automated testing for this scenario.

**Comment by sibille** [comment]
Manual, will add a unit test, good point!

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19189.1
Wizard version: 0.20.19189.1
