### ISSUE TITLE
Feature: Add secured Web API

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3254]
This feature will add a project with an WebAPI that validates the authentication token sent by the Application.

This template will add a Web API that validates the JWToken passed by the UWP application. 
The protection ensures that the API can only be called by:
	- Applications on behalf of users who have the right scopes.
	- Users that have the right application roles.

We'll use JwtBearer middleware from ASP.Net Core to verify tokens.

You can find the mockup application at https://github.com/dgomezc/JWTValidationDemo

Action Plan:
- [x] Create mockups
- [ ] Product team validation
- [x] Create templates
- [x] Add docs

**Comment by sibille** [comment]
Updated the issue with detailed specs and added link to mockup

**Comment by sibille** [comment]
This needs https://github.com/microsoft/CoreTemplateStudio/issues/182 to be able to specify either Forced or Optional Login as a dependency.

**Comment by mrlacey** [comment]
"Securized" isn't a word. (At least in English.) Do you mean "Secured"? or "Authenticated"?

**Comment by sibille** [comment]
Secured, thanks for the hint!

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.20.19302.1
Wizard version: 0.20.19301.3
