### ISSUE TITLE
Clicking OK on Toast Notification makes it appear again

### ISSUE THREAD

**Issue by degant** [Microsoft/WindowsTemplateStudio#326]
Created a basic app with Toast Notifications
- **Project Type:** Navigation Page
- **Framework:** MVVM Light
- **Pages:** Main [Blank]
- **Features:** Toast Notifications
- **Wizard Version:** 1.0.17131.1
- **Templates Version:** 1.0.17131.2

After building & running the app, a toast notification pops up which asks user to verify if buttons have 'Ok' and 'Cancel' options. On clicking Cancel it gets dismissed but on clicking 'Ok' it pops up again (along with the ding notification sound) recursively until Cancel is pressed. 

Is this behavior expected? Because it isn't called out in the code comments. Also the action text _'Make sure the left button on the toast has the text "Ok" on it, and the right button has the text "Cancel" on it.'_ suggests that clicking either of the buttons would dismiss it.

**Comment by mrlacey** [comment]
This is by design but I've labeled it as a bug to indicate that it needs changing.
The purpose of the Toast sample is to show how to create a toast notification with interactive buttons.
We need to to a better job of documenting this and providing a more intuitive experience with the sample.

**Comment by degant** [comment]
As it stands, it isn't clear that the user is supposed to click 'Cancel' to proceed. However even if the documentation is changed, it still wouldn't make sense to have a scenario where the notification keeps popping back every time 'Cancel' is clicked. So wouldn't it make sense to get rid of the toast, irrespective whether the user clicked 'OK' or 'Cancel'?

**Comment by mrlacey** [comment]
Yes, sorry I wasn't clear.
1. The text of the message should be changed.
2. The buttons should both actually do something and not just show the same notification again.
3. The documentation should also be updated.

**Comment by crutkas** [comment]
This adjustment can be pushed out of band.  good catch @degant 

Marking 1.01

**Comment by degant** [comment]
The OK button has the `ActivationType` set to `ToastActivationType.Foreground` which essentially launches the app and calls the `OnActivated()` method. This subsequently triggers a new Toast Notification and so on infinitely until 'Cancel' is clicked. Two simple approaches that I could think of to avoid this:

- Change the `ActivationType` to `ToastActivationType.Background` so that the app doesn't launch in the foreground. However if a user doesn't respond to the toast and it goes into the notification center. Then clicking on OK will not launch the app again.
- `ActivationService.StartupAsync()` can have a condition to check if the activation was due to a Toast Notification or due to an actual Launch. If it is from a Toast Notification then the `StartupAsync` can be skipped so that a new toast doesn't popup.

Thoughts?

Regarding the title and message for the toast, how about just having something plain and simple like a _'This is a sample adaptive toast notification with two buttons'_.

If the approach and text is finalized, would love to give this a shot or contribute in any way possible!
