### ISSUE TITLE
Is making people install the prior Windows SDK a needed requirement?

### ISSUE THREAD

**Issue by jcotton42** [Microsoft/WindowsTemplateStudio#327]
Even when I have already installed the Creators Update SDK, Visual Studio will install the Anniversary Update SDK upon installing the extension. This seems like a bug to me, unless there's some dependency on the AU SDK that I'm not aware of.

Following that, will the extension continue to work if I manually remove the AU SDK after installing it?

**Comment by mrlacey** [comment]
The Creators update does not include the AU update as well. The generated templates come set to reach both and so VS will install the missing SDK if it's not there.
Downloading and installing the extra SDK is obviously not desirable (& potentially slow) if you explicitly don't want to target it.

The way to address this will be to control the minimum and target versions of Windows 10 that the app should support as part of the generation process. 
Marking this as a question to gather some wider input on this:
- Should the selection of min&target version be specifiable? (It adds an extra level of complexity to testing and the possible number of configurable options and how they interact and behave.)
- What versions should we allow to be selected? (Just from the last 2 or going further back?)
- What UI would be good to do this selection? (2 drop downs like the default template or something else? If we limit to just versions N and N-1 this could just be a checkbox.)

**Comment by crutkas** [comment]
Our current min versions is 14393 and will always try to do N and N-1. [Falls Creators Update is N+1].  SDKs only contain their version so we have to do this.

I'll keep this issue open, and rename it for a discussion.

**Comment by ralarcon** [comment]
This will be addressed in the next update.

**Comment by mrlacey** [comment]
@ralarcon  What do you mean by targeting 15.1? The current release version of VS2017 is 15.2
By "Templates will target 10.0.15063.0 " do you mean for Target AND minimum versions?
What happened to targeting the current and previous versions? (N & N-1) 

It feels as though the solution proposed here is to limit the supported platforms and make the problem go away. It ignores the fact that there are often good reasons to set the minimum version below the target version. #334 goes the opposite way to what you're proposing and suggests that we should be opening up to support a, potentially, wider range of versions. Ideally, we'd have figures on the install size of the different target platform versions to inform this conversation, but as the default blank template targets the current and sets minimum back two versions I think that's a good indication that it may not be the best idea to just target the latest public release. I assume their decision wasn't arbitrary and was based on some [non-public] data.

@crutkas care to weigh in on plans for which versions should be supported?

**Comment by ralarcon** [comment]
Finally, to better support Visual Studio versions ranging from 15.0 to 15.3 , the the VSIX will not require any SDK as pre-requisite. If the user generate a solution and the SDK is not present, the Visual Studio ask to install it (default VS behaviour). 

![image](https://cloud.githubusercontent.com/assets/2638875/26239637/1e29a1c8-3c7e-11e7-84c4-b17658f81589.png)

By default, the templates TargetPlatformVersion will point to the 10.0.15063 and the TargetPlatformMinVersion will point to SDK 10.0.10586.
