### ISSUE TITLE
[Request] Move back arrow in the title bar

### ISSUE THREAD

**Issue by LoriBru** [microsoft/WindowsTemplateStudio#3280]
I think that the back navigation arrow should be placed by default in the title bar as in the Settings app.
This is a more compact and nicer layout.
I would also make the upper portion with the title the same color as the hamburger menu.

![Annotation 2019-07-23 094259](https://user-images.githubusercontent.com/22811725/61692875-c9f6b400-ad2e-11e9-9973-7da2ed924000.png)

**Comment by mrlacey** [comment]
@LoriBru WinTS follows the official guidance on UI layout and styling. Unfortunately these guidelines are not always followed by all apps and so inconsistencies can occur. 

It is my understanding that the position, use, and position of the Back button within the NavigationView is [under discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/810) and so I expect the WinTS templates to be updated accordingly when any change is made. For now, we'll continue to follow the [guidance](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation) and default behavior of official controls.

I'll also try and find out if there is any updated guidance on the position/styling of the app name too.

**Comment by LoriBru** [comment]
@mrlacey Thank you for the detailed answer.
It's good to know that decisions regarding these kind of details are taken so professionally.

**Comment by mrlacey** [comment]
@LoriBru I've checked with the design team and their guidance remains unchanged with what's [documented regarding the placement of the back button](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#back-button).

When official guidance changes WinTS templates will be updated accordingly. Until then, you're free to change what is generated as per what's suitable/appropriate for your app. 
If you want to change the color of the text in the title bar, you can do this by adding the control as part of your page and then extending into the title bar. [[see customization doc for more details](https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar)]
