### ISSUE TITLE
docs / readme.md is out of date

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3284]
The readme.md document in the docs was not updated for the 3.3 release.

Changes needed:

- What is a template is missing Services and Testing.
- What is the Generation Wizard is missing references to Services and Testing.

**Comment by sibille** [comment]
Thanks for bringing this up! Will update documentation to include the new steps

**Comment by mrlacey** [comment]
this document has now been updated

https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/readme.md
