### ISSUE TITLE
docs/getting-started-extension.md is out of date

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3285]
Windows 10 Creators Update SDK (version 10.0.15063.0 or later)
Is this correct?  Seems like it should read:
Windows 10, version 1803 (version 10.0.17134.0) or later

Item (3) To add pages and features to an existing Windows Template Studio project screen shot is old and missing services and testing project items.

**Comment by sibille** [comment]
Thats correct, version 10.0.17134.0 is currently our supported min version.

**Comment by mrlacey** [comment]
This document has no been updated

https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md
