### ISSUE TITLE
docs/getting-started-endusers.md is out of date

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3286]
- TreeView is missing from the Pages section.  Should be listed after Master/Detail.
- Content Grid should be moved up and listed after TreeView to keep the same order as in the UI.
- DataGrid is missing from the Pages section.  Should be listed between Content Grid and Telerik Data Grid.
- Ink Draw is missing from the Pages section.
- Ink Smart Canvas is missing from the Pages section.
- Ink Draw Picture is missing from the Pages section.
- Feedback Hub Link is missing from User Interactions section.
- Services section is missing.
- Testing section is missing.

**Comment by sibille** [comment]
Good catch! We'll include services and testing sections and missing pages!

**Comment by mrlacey** [comment]
This document has now been updated :)

https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-endusers.md
