### ISSUE TITLE
Have separate issue templates for 'bugs' and 'new features'

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3289]
To try and encourage the provision of all required information, have separate templates for issues about bugs and new features.

See the community toolkit, WinUI, and Xamarin.Forms repositories for reference/ideas.

**Comment by mrlacey** [comment]
removing my assignment as I don't have permissions to change this

**Comment by sibille** [comment]
I've created the new templates for bugs and features. I think we could add a third Question, with sth similar to what Community Toolkit has. 

I went with the default templates that github suggests + Version info on the bugs templates, they are very similar to what we had before.

**Comment by mvegaca** [comment]
Checked in dev
Templates version: 0.20.19288.1
Wizard version: 0.20.19288.1
