### ISSUE TITLE
“ToastNotificationsService ” can't handle activation from toast notification.

### ISSUE THREAD

**Issue by KevinZjYang** [microsoft/WindowsTemplateStudio#3291]
I first added "ToastNotificationsService" in the app.Then I successfully handle activation from toast notification. Like this.
```
       protected override async Task HandleInternalAsync(ToastNotificationActivatedEventArgs args)
        {
            var queryStr = args.Argument.ToString();
            var type = QueryString.Parse(queryStr)["Type"];
            var url = QueryString.Parse(queryStr)["url"];
            if (type == "SetWallpaper")
            {
                await Core.Helpers.Singleton<QuickSetWallpaperService>.Instance.UpdateWallpaperByUrlAsync(url);
            }
            if (type == "OpenPath")
            {
                await Launcher.LaunchFolderPathAsync(url);
            }
            await Task.CompletedTask;
        }
```
But when I added "AzureNotificationsService", I can't handle activation from toast notification. Then I found out that "AzureNotificationsService" has exactly the same method that can handle activation from toast notification.
```
      protected override async Task HandleInternalAsync(ToastNotificationActivatedEventArgs args)
        {
            await Task.CompletedTask;
        }
```
Then I deleted the "AzureNotificationsService". But I still can't handle activation in "ToastNotificationsService".When I re-add "AzureNotificationsService", it re-worked.

Now,I just want use "ToastNotificationsService",How can I do to handle the activation?
Help me,thanks.

**Comment by sibille** [comment]
@KevinZjYang, could you check what services you have in the method GetActivationHandlers on the ActivationService? You should find there all the ActivationHandlers you want to use, those you don't want to use should not be there, so in your case you should only have the ToastNotificationService here. 

The ActivationService determines which ActivationHandler will handle the activation evaluating the result from the CanHandle method of each ActivationHandler. This method looks by default at the type of the ActivationEventArgs, you can override the method CanHandleInternal of each ActivationHandler to do further checks.
More details on how Activation and ActivationHandlers work can be found at: https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/activation.md

**Comment by KevinZjYang** [comment]
Thanks，I will try this.

**Comment by KevinZjYang** [comment]
I changed the position of the “ToastNotificationsService” in "GetActivationHandlers()" to the top and it started working fine.
```
       private IEnumerable<ActivationHandler> GetActivationHandlers()
        {
            yield return Singleton<ToastNotificationsService>.Instance;
            yield return Singleton<DevCenterNotificationsService>.Instance;
            yield return Singleton<BackgroundTaskService>.Instance;
            yield return Singleton<LiveTileService>.Instance;
        }
```
I don't understand "LiveTileService" at the bottom, it works fine. And because I added "AzureNotificationsService" before, I have to move "ToastNotificationsService" to the top now to make it work.
I found that after adding "AzureNotificationsService", it will be added to the top by default.
Who is at the top of the two, who can handle the activation.

**Comment by mrlacey** [comment]
> Who is at the top of the two, who can handle the activation.

Yes, the way the activation handlers work is that the first one that is returned that can handle the type of arguments used during activation will process it. As both the ToastNotificationService and the DevCenterNotificationService (and AzureNotificationsService) can handle `ToastNotificationActivatedEventArgs` the first to be returned by `GetActivationHandlers()` will handle it.

**Unless**...the service overrides `CanHandleInternal(ToastNotificationActivatedEventArgs args)` and is able to determine from the args if it can handle it or not and returning false if it can't. At which point the next handler returned by `GetActivationHandlers()` will be tried.


Glad you were able to figure out a way forward.
