### ISSUE TITLE
Update description shown in Extension Gallery

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3292]
When viewing the extension though the Visual Studio extension gallery (either for installation or to update) the description shown is the same as the title. (see below)
This should be updated to include a more useful description.

![image](https://user-images.githubusercontent.com/189547/61876951-ea1ca380-aee5-11e9-8ecf-dfc2eecb747f.png)

**Comment by sibille** [comment]
Good catch! Will update!

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19273.1
Wizard version: 0.20.19273.1
