### ISSUE TITLE
Microsoft Graph Service not getting User Photo

### ISSUE THREAD

**Issue by PaulaScholz** [microsoft/WindowsTemplateStudio#3293]
#### Repro steps
1.  Make a UWP project with a Settings page and Login options.
2.  Build it and start the project.
3.  Login with an MSA account.
4.  Observe that your photo does not appear in the Settings page or ShellPage.

What did you do? How can someone else reproduce this?

The simple fix is to replace the _graphAPIEndpoint URI with:
 private const string _graphAPIEndpoint = "https://graph.microsoft.com/beta/";

in MicrosoftGraphService.cs at line 18 in the Core project, Services folder.

instead of 1.0, and then you will get the photo.

### System

* **VS Version:**  16.1.6
* **WTS Wizard Version:**  3.3.19200.1
* **WTS Template Version:**
* **Windows Build:**  Version	10.0.18362 Build 18362

**Comment by sibille** [comment]
@PaulaScholz, I think you are hitting issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/3990. The photo should be available on the v1 graph within the next few weeks for MSA accounts. 
Using beta graph is not recommended in production apps as they are subject to change (https://docs.microsoft.com/en-us/graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-beta)

**Comment by PaulaScholz** [comment]
Ok, good advice.  Love how WTS is shaping up.
