### ISSUE TITLE
[Test Failure] “No content available” show when adding MVVM Light app into Windows Template Studio project

### ISSUE THREAD

**Issue by v-longmin** [microsoft/WindowsTemplateStudio#3295]
## Details about Problem
VS Version: Master 29124.47
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps
1. Install the Windows Template Studio .vsix in the Visual Studio Marketplace.
2. Create a new Windows Template Studio project.
3. Add MVVM Light App into the Windows Template Studio project.
## Expected
The “MVVM Light App” can be added into the Windows Template Studio project successfully.
## Actual
“No content available” show when adding MVVM Light app into Windows Template Studio project as attached screenshot.
![image](https://user-images.githubusercontent.com/40230425/62599608-412b6b00-b91f-11e9-96bf-9c6ce97da029.png)

**Comment by sibille** [comment]
@v-longmin, thanks for reporting. Could you give more details on step 3: Add MVVM Light App into Windows Template Studio project?
Could you successfully create the first project and then had trouble to add another or did the wizard directly show up without content?

**Comment by v-longmin** [comment]
@sibille Yes. The Windows Template Studio Wizard directly show up without content.

**Comment by sibille** [comment]
@v-longmin, looks like the templates could not be synchronized. Could you send us the logs from Windows Template Studio. 

there anything in the VS Output  for Window Template Studio or in the log files %userprofile%\AppData\Local\WinTS\Logs to further look into this?

**Comment by v-longmin** [comment]
@sibille The logs as below attachment:
[WTS_Pro_20190812.log](https://github.com/microsoft/WindowsTemplateStudio/files/3491661/WTS_Pro_20190812.log)

**Comment by sibille** [comment]
Thanks @v-longmin! I was able to reproduce this with VS 2019 Preview Version 16.3.0 Preview 2. What version are you using?

**Comment by v-longmin** [comment]
@sibille We are using the same VS 2019 Preview Version, thanks!

**Comment by Hatsor** [comment]
I have the exact same problem. Has it been fixed?

**Comment by v-longmin** [comment]
@Hatsor No, the issue still repro on Master\29221.49.

**Comment by sibille** [comment]
We're still investigating what causes this, will update you as soon as we know anything new!

**Comment by sharpninja** [comment]
My 2 cents worth of logs having the same problem.
[WTS_Pro_20190824.log](https://github.com/microsoft/WindowsTemplateStudio/files/3537803/WTS_Pro_20190824.log)

[sysinfo.txt](https://github.com/microsoft/WindowsTemplateStudio/files/3537804/sysinfo.txt)

![image](https://user-images.githubusercontent.com/16146732/63645090-acfe2980-c6bc-11e9-9a85-92271d8ba71e.png)

**Comment by sharpninja** [comment]
Microsoft Visual Studio Community 2019 Preview
Version 16.3.0 Preview 2.0
VisualStudio.16.Preview/16.3.0-pre.2.0+29209.152
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA361
Microsoft Visual C++ 2019

.ignore   1.2.77
A language service that makes it painless to handle all types of .ignore files such as .gitignore, .tfignore, etc.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASP.NET and Web Tools 2019   16.3.205.56800
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.205.56800
For additional information, visit https://www.asp.net/

AttachToAllTheThings   1.0
AttachToAllTheThings Visual Studio Package Detailed Info

Azure App Service Tools v3.0.0   16.3.205.56800
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.3.205.56800
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bridge.NET   1.0
Bridge.NET

C# Tools   3.3.0-beta3-19407-03+d961190a1b4b2a81ac178b567840dfeff048b037
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.0.183
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Color Picker   1.0
Integrated Color Picker for Visual Studio IDE and Editor

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.3.19219.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.9.1.7781
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20726.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10731.1 Commit Hash:92029a8ccd61fbc31c21b823ec3025ce7e598894
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.29130.00
Microsoft Office Developer Tools for Visual Studio

Open in Visual Studio Code   1.4.46
Adds a menu command that lets you open any solution, project, folder and file in Visual Studio Code.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.3.19219.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.3.19219.1
Conda support for Python projects.

Python - Django support   16.3.19219.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.3.19219.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.3.19219.1
Profiling support for Python projects.

SQL Server Data Tools   16.0.61907.31040
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10802.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.0-beta3-19407-03+d961190a1b4b2a81ac178b567840dfeff048b037
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.29209.152
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.29209
Visual C++ for Linux Development

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19381.3+8e8a754ab056dc16f6dda49110fe8729d1bbabc9
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Color Theme Editor   1.0
Allows users to create and edit Visual Studio themes. Themes can customize colors used for menus, toolbars, tabs, titlebars, the text editor, and other environment colors.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.3.1.0
Visual Studio Tools for Unity

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Template Studio   3.3.19200.1
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.3.0.179 (d16-3@8669bd4)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.122 (remotes/origin/d16-3@a187bbc98)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.536 (069a02b)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.4 (d16-3/a1f7825)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@17ac7dcfc74
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   12.16.1.9 (a12e76f)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by sibille** [comment]
The underlying reason is that our templates do not define the shortName property. VS 2019 Preview includes a new version of the template engine that requires this property to be set. We're working on an updated template package for version 3.3 to fix this.

**Comment by sibille** [comment]
The problem is solved in dev-nightly version 
Templates version: 0.20.19248.1
Wizard version: 0.20.19248.1

but there is another problem in VS 2019 Preview causing the generation to fail. (X-ref #3309)

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.20.19252.1
Wizard version: 0.20.19252.1

**Comment by sharpninja** [comment]
When will the extension be updated on the store so I can update in VS 2019?

**Comment by sibille** [comment]
We'll ship an updated template package in the next days. I'll keep this issue open until the template package has been published. WinTS will download the updated template package on startup automatically, so no need to update the extension itself.

**Comment by sibille** [comment]
We'll have to publish a new version to the marketplace as the pin of the certificate we use to sign the template package has changed and the current version will not be able to load the new package.

**Comment by sibille** [comment]
Just released version 3.4.19254.01 on the marketplace which fixes this issue.
