### ISSUE TITLE
Page: Data Form (property grid)

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#330]
Add a page with the [Telerik DataForm](http://www.telerik.com/universal-windows-platform-ui/dataform) control.
Page should show some simple usage based on an option from their [samples](https://github.com/telerik/UI-For-UWP/tree/master/SDKExamples.UWP/Examples/DataForm).

**Comment by crutkas** [comment]
would this be a user control or a new page?  I could see in the example of editing from a grid and creating someone would want these to be together, maybe in a modal or flyout.

Thoughts?

**Comment by mrlacey** [comment]
I think a page.
This suggestion came from Telerik when I showed them the Grid and Chart. They said that those, plus DataForm were their most popular scenarios and what they thought we should include.  I haven't yet looked at or thought about, how this would work.

**Comment by ralarcon** [comment]
I think that a page showing a simple usage scenario would help developers. It would be great if we can involve someone from Telerik to validate / contribute.

**Comment by mrlacey** [comment]
This came at the suggestion of John from Telerik when I showed him WTS and the Chart & Grid pages at build. Apparently this, [Charts](https://github.com/Microsoft/WindowsTemplateStudio/issues/129) & [Grids](https://github.com/Microsoft/WindowsTemplateStudio/issues/128) are the most popular items.
Would be good to include this in v1.1 along with the other referenced pages.
Should run all three past Telerik for feedback once get them into nightly builds.

**Comment by ralarcon** [comment]
Sounds good!

**Comment by mrlacey** [comment]
Upon further discussion, it's felt that the DataForm control depends too much on annotations of the ViewModel to create a helpful, agnostic, sample/placeholder. 
Instead, we're going to add references, with links, to the documentation for the Grid page (#128) suggesting the use of the DataForm as a possible extension the developer may wish to add.
