### ISSUE TITLE
Add reference to MVVMBasic Snippets

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3301]
Earlier this year, while building apps with WinTS and the **MVVMBasic** framework, I found it frustrating that I had to write as much code by hand, in the ViewModels as I did. 
To address this, I created some MVVMBasic specific code snippets to help with creating new properties, etc. and submitted them to the [marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.MvvmBasicSnippets).

The following snippets are defined and available for C# and VB.Net
- **mbvm** Creates an empty View Model with the `Observable` base class.
- **mbprop** Creates a property with a backing field.
- **mbcmd** Creates an ICommand property returning RelayCommand.
- **mbcmdt** Creates an ICommand property returning RelayCommand&lt;T&gt;.
- **mbcmdCanExecute** Creates an ICommand property returning RelayCommand with a - CanExecute method.
- **mbcmdtCanExecute** Creates an ICommand property returning RelayCommand&lt;T&gt; with a CanExecute method.

I put them in the marketplace to make it easier for me to use them on different machines as much as anything.
I've only told two people about them but it's had over 500 downloads. This makes me suspect other people are finding and using them. Therefore, I think it will be beneficial to more people to make these snippets easier for anyone using WinTS and MVVMBasic to find, install, and use.

I see 4 possible options (listed in my order of preference)

1. Link the snippets package to the main WinTS vsix. This will make it an easily discoverable option for anyone using WinTS while still making it optional for anyone who doesn't want these snippets installed. (Not wanting these will be preferable if the developer only uses other MVVM frameworks.)
2. Include the snippets directly in WinTS. This would automatically make them available to anyone who installs WinTS but it would force them upon every developer even if they never use MVVMBasic.
3. Add a link to them in the documentation for MVVM Basic. ([here](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/mvvmbasic.md) and [here?](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/templates/_catalog/frontendframeworks/MVVMBasic.md))
4. Do nothing. (Always an option but it would make me sad. 😢)

Thoughts?

**Comment by sibille** [comment]
@mrlacey, I think this is very useful for people working with MVVMBasic.

Could you give more details on option 1? Are you saying add a link on the WTS marketplace or inside the wizard or something else?

**Comment by mrlacey** [comment]
> Could you give more details on option 1? Are you saying add a link on the WTS marketplace or inside the wizard or something else?

Add a .vsext file to the WinTS installer so that the snippet option is presented at install (or update) time.

**Comment by mrlacey** [comment]
For reference, the **Image Sprites** extension also installs the **Image Optimizer**

![image](https://user-images.githubusercontent.com/189547/64541476-d607f680-d319-11e9-8309-e78af6aeba53.png)

If the VSIX is downloaded from the gallery, there is a checkbox in the installer to choose whether to install the other extension.

![image](https://user-images.githubusercontent.com/189547/64543230-bfaf6a00-d31c-11e9-89b1-ad5759366dd1.png)


If the primary extension is installed from within VS, the option to chose what to install is within the dialog.

![image](https://user-images.githubusercontent.com/189547/64543026-6cd5b280-d31c-11e9-9375-b7352f89f8e9.png)

Even if both are installed, they can be disabled (or uninstalled) separately.

![image](https://user-images.githubusercontent.com/189547/64541585-0780c200-d31a-11e9-860d-faa0f27a7d32.png)

**Comment by mrlacey** [comment]
Add links to docs for snippets for all frameworks as a first step.

**Comment by mrlacey** [comment]
Nothing more than the docs reference is going to be done so closing this
