### ISSUE TITLE
Login Wts

### ISSUE THREAD

**Issue by Javier118** [microsoft/WindowsTemplateStudio#3302]
It can be used
About the WTS Login can be used with Azure for Bakend mobile App for Authentication.

**Comment by mrlacey** [comment]
@Javier118 Can you clarify what you're asking here?

**Comment by Javier118** [comment]
The question is : 

If WTS login can be used with Mobile Apps for Backend in Azure

**Comment by Javier118** [comment]
![Captura de pantalla (6)_LI](https://user-images.githubusercontent.com/17751683/64041345-824e1e00-cb5f-11e9-8d41-c7b8c0c3c20b.jpg)

**Comment by mrlacey** [comment]
The identity options currently only work with AAD.
This will be extended in a future update. Sorry, we don't have a time-line on this yet as there are some external dependencies that are blocking the planned work.

**Comment by Javier118** [comment]
hello:
I'm implementing MSA account code for mobile apps for Back End, part of the code conflicts with Newtosonft.Json.LinqJobject.

How can I fix the bug? , or the two options (login) that come WTS is for Mobile Apps (Backeend)

authentication for windows from Azure (Mobile Apps)

**Comment by sibille** [comment]
@Javier118, what's your exact scenario? Are you using the Optional Login feature to connect with a backend service? Is this backend service a ASP.NET or ASP.NET Core Web API or something else? 

We are working on a feature that shown how to validate the token from the Identity Features on a ASP.NET Core API, if that's your scenario, you can have a look at issue #3254. 

If not, please share more details about your scenario and the exact conflict to see if we can help you.

**Comment by Javier118** [comment]
he scenario is Windows Template Studio UWP C# for authentication mobile App for Backend . App for Microsoft Store.

error says you can't convert string to Newtonsoft.Json.Linq.JObject

I followed the Azure prompts for Windows authentication.
` string message;
            bool success = false;

            try
            {
                //Sign in using MicrosoftAccount

                user = await App.MobileService
                    .LoginAsync(MobileServiceAuthenticationProvider.MicrosoftAccount**, "{}"**);
                message =
                    string.Format("You are now signed in - {0}", user.UserId);
               

                success = true;
            }
            catch(InvalidOperationException)
            {
                message = "You must log in. Login Required";

            }

            var dlg = new MessageDialog(message);
            dlg.Commands.Add(new UICommand("ok"));
            await dlg.ShowAsync();
            return success;`

**Comment by Javier118** [comment]
Hello:

When the login option will be for the Azure Backend (webApp) connection for Uwp.

**Comment by Javier118** [comment]
hello:

login there wtS serves me for Onedrive for an App in UWp for Microsft Store

**Comment by Javier118** [comment]
WTS will include A Login for mobile App where you can use account providers such as Facebook, Twitter, Msa etc. For the backend

**Comment by Javier118** [comment]
I have put login optional but when I go I have entered the outlook account does not come out to put the password directly I get a dialog box with button close. The APp is ua uwp
