### ISSUE TITLE
Change theme bug when set shell page's background to SystemControlBaseMediumLowAcrylicWindowMediumBrush

### ISSUE THREAD

**Issue by hupo376787** [microsoft/WindowsTemplateStudio#3306]
### For Bugs:
When set Grid's background to `{StaticResource SystemControlBaseMediumLowAcrylicWindowMediumBrush}`, and change theme from light to dark, the app's background doesn't change with the theme.
#### Repro steps
Download my sample **[repo](https://github.com/hupo376787/UWPThemeTest.git)**, change theme in settings.

![CHangeThemeBug.gif](https://github.com/hupo376787/UWPThemeTest/blob/master/CHangeThemeBug.gif)

#### Expected Behavior
When change theme to dark, the app's acrylic background also changes.

I rember long time ago, maybe last year, I created a repo, the same steps, it works normally. 
### System

* **VS Version:**16.2.3
* **WTS Wizard Version:**3.3.19200.1
* **WTS Template Version:**3.3.19200.1
* **Windows Build:**18360.295

**Comment by mdtauk** [comment]
Instead of setting it to a StaticResource, have you tried setting it to a **ThemeResource**?  These brushes automatically update as the theme changes in the App or the OS

**Comment by hupo376787** [comment]
Wow, it works. But now I'm confused when setting brushes, **ThemeResource** and **StaticResource** , which one to use? Thx.

**Comment by hupo376787** [comment]
When dynamicly change brushes, use **ThemeResource**?

**Comment by mdtauk** [comment]
> Wow, it works. But now I'm confused when setting brushes, **ThemeResource** and **StaticResource** , which one to use? Thx.

Any brush that should adapt to the theme, should use a ThemeResource.  Static Resources are "static" as in they will not change unless you make it change.

[ThemeResource Docs](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/themeresource-markup-extension)

**Comment by hupo376787** [comment]
Thanks, bro.
