### ISSUE TITLE
Localize the wizard

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#332]
Visual Studio is used by the world and our wizard should reflect that.  If someone has VS set to a different language, our wizard should respect that.

this is a different issue that #46.  #46 is about making the code product localized content that is generated.

**Comment by crutkas** [comment]
FYI, we do have code debt for warnings.

**Comment by ralarcon** [comment]
Latest resources ready to be localized. Waiting to get them back integrated.

**Comment by ralarcon** [comment]
Moving to 1.5 as we do not have the localized files jet.

**Comment by sibille** [comment]
Verified on dev-nightly:

Assistent: 0.14.17307.65003
Vorlagen: 0.14.17307.4
