### ISSUE TITLE
Update nuget packages in templates

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3328]
Update the following packages to version: 

Package | Version
:-- |:--|
AdaptiveCards | 1.2.2
Microsoft.UI.Xaml | 2.2.190917002
MSTest.TestAdapter | 2.0.0
MSTest.TestFramework | 2.0.0
Microsoft.NET.Test.SDK | 16.3.0
Appium.WebDriver | 4.0.0
Microsoft.EntityFrameworkCore | 2.2.6
Microsoft.EntityFrameworkCore.SQLServer | 2.2.6
Microsoft.Identity.Client | 4.4.0
NUnit3TestAdapter | 3.15.1
Moq | 4.13.0

**Comment by mvegaca** [comment]
Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer can be updated because there is a conflict on WebAPI project

**Comment by mrlacey** [comment]
> Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.SqlServer can be updated because there is a conflict on WebAPI project

**CAN** or **CAN NOT**?

**Comment by mvegaca** [comment]
Can not, sorry :)

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.20.19280.1
Wizard version: 0.20.19278.1
