### ISSUE TITLE
Feedback requested for WPF mockup (MVVMLight + NavigationView)

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3336]
We'd love to hear your feedback on the WPF mockup for MVVMLight. You can find the solution at https://github.com/mvegaca/WTS.WPF.MVVMLight.GeneratedApps

Project setup is the following:

ProjectType:

- NavigationView (using Hamburger Menu)

Framework:

- MVVMLight

Pages:

- Blank
- Settings

Features:

- MSIX Packaging
- Theme Support (Dark/Light)
- Setting Storage / Persisting app data

**Comment by mrlacey** [comment]
From looking at the MVMVLight version (in no particular order)

- Packaging project is missing a certificate and so can't build
- Referencing a .NET Framework version of Microsoft.Xaml.Behaviors.Wpf
- The back button doesn't change it's UI when enabled or not.
- Clicking the privacy URI link on the settings page causes a crash
- Why use the INavigationAware interface (and implementation) in an MVVMLight based project? INavigationAware is a Prism convention.
- There's a lot more here than I'd expect. The guideline we applied when creating the UWP templates was that what was generated would meet the expectation of someone who is familiar with that framework. This seems a long way away from the old MVVMLight project templates.
- Why are the interfaces under a 'Contracts' directory? What convention is this that is being adopted/enforced?
- I would expect EnumToBooleanConverter.cs to be in a directory called `Converters` as that's a convention I've seen much more frequently. "Helpers" is a name more commonly used for miscellaneous files in projects that don't have a "Utils" grouping, or it's used for classes that use the suffix "Helper" in their name.
- What's `AppConfig.DataFolder` intended for? I can't see where it's being used.
- Whos should //TODO: Set high contrast theme name` be handled? Is this something still to be added to the sample or something for the end developer to do?
- There are lots of suggested code improvements from the compiler (IDExxxx error codes) that could be made.
- `SettingsViewModel.GetVersionDescription` uses hard-coded version numbers (& potentially confusing formatting) but shouldn't.
- Consider installing FxCopAnalyzers in solution
- Regarding the comment `<!-- MahApps.Metro resource dictionaries. Make sure that all file names are Case Sensitive! -->` what does it mean to "make sure that all file names are Case Sensitive"? and why case words in that question that way? Is this something that someone using the generated project needs to be aware of?
- Why no localizaton?
- I understand the use of MahApps to try and create a more up to date UI but having a Windows product use Material design seems wrong on a number of levels. Unless this is something Microsoft wants to encourage going forward.
- Why include an 'Internet (Client)' capability declaration when the app doesn't need it?


In comparing the different versions, inconsistent naming (fields, variables, etc.) and formatting (including ordering, unnecessary usings, & inconsistent whitespace) between the projects for each framework makes it hard to compare them. So I gave up. There seems a lot of work still to be done here so I assume the same is true for the other versions too.

**Comment by sibille** [comment]
@mrlacey, great feedback, thanks!

Reordering a bit in things we'll fix and things to discuss: 

- We're working on fixing the following issues:
> * Packaging project is missing a certificate and so can't build
> * Clicking the privacy URI link on the settings page causes a crash
> * I would expect EnumToBooleanConverter.cs to be in a directory called Converters as that's a convention I've seen much more frequently. "Helpers" is a name more commonly used for miscellaneous files in projects that don't have a "Utils" grouping, or it's used for classes that use the suffix "Helper" in their name.
> * What's AppConfig.DataFolder intended for? I can't see where it's being used.
> * SettingsViewModel.GetVersionDescription uses hard-coded version numbers (& potentially confusing formatting) but shouldn't.
> * Consider installing FxCopAnalyzers in solution
> * There are lots of suggested code improvements from the compiler (IDExxxx error codes) that could be made.
> * In comparing the different versions, inconsistent naming (fields, variables, etc.) and formatting (including ordering, unnecessary usings, & inconsistent whitespace) between the projects for each framework makes it hard to compare them. So I gave up. There seems a lot of work still to be done here so I assume the same is true for the other versions too.


- The following issues are related to MahApps, we'll sync with them to see if we missed sth or they can tackle them: 

> * Referencing a .NET Framework version of Microsoft.Xaml.Behaviors.Wpf
> * The back button doesn't change it's UI when enabled or not.
> * Whos should //TODO: Set high contrast theme name` be handled? Is this something still to be added to the sample or something for the end developer to do?
 
- Things to discuss: 

> * Why use the INavigationAware interface (and implementation) in an MVVMLight based project? INavigationAware is a Prism convention.
> There's a lot more here than I'd expect. The guideline we applied when creating the UWP templates was that what was generated would meet the expectation of someone who is familiar with that framework.
> This seems a long way away from the old MVVMLight project templates.

As WPF does not have an OnNavigatedTo on the page we liked Prisms approach to do sth similar on the ViewModel. The alterative would be using the an Onloaded event/command.

Are there more things that feel too much apart from the INavigationAware?
 

> * Why are the interfaces under a 'Contracts' directory? What convention is this that is being adopted/enforced?

Having both the interfaces and implementations in the same folder results in mixing them up, that's why we moved them to a separate folder. What organization would you prefer? 
 
- Others: 
> * Why no localizaton?

When we started the mockup tooling for resx was not available, will follow up on this one. 

> * I understand the use of MahApps to try and create a more up to date UI but having a Windows product use Material design seems wrong on a number of levels.
> Unless this is something Microsoft wants to encourage going forward.

We've removed the material icons. 
 
> * Why include an 'Internet (Client)' capability declaration when the app doesn't need it?

Is on default blank project template, that's why it's there.

> * Regarding the comment  what does it mean to "make sure that all file names are Case Sensitive"? and why case words in that question that way? Is this something that someone using the generated project needs to be aware of?

We grabbed the comment from Mahapps sample application. Is this sentence grammatically wrong? What would you suggest?

**Comment by sibille** [comment]
@mrlacey, we've updated the mockups with your suggestions from the first block and added localization.

**Comment by sibille** [comment]
Updated mocks with latest from dev can be found at  https://github.com/mvegaca/WTS.WPF.MVVMLight.GeneratedApps

**Comment by matthewacme** [comment]
When I add the default Map page in the template it generates the xaml at the bottom

Lines 9 and 10 cause an error after building the project

`   xmlns:behaviors="using:NotificationsReviewer.Behaviors"
    behaviors:NavigationViewHeaderBehavior.HeaderMode="Never"`

The error is 

> Severity	Error	
> Code	XDG0062
> Description	System.NullReferenceException: Object reference not set to an instance of an object
> Project	<project name>
> File	MapPage.xaml	
> Line	11	




```<Page
    x:Class="NotificationsReviewer.Views.MapPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:maps="using:Windows.UI.Xaml.Controls.Maps"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Style="{StaticResource PageStyle}"
    xmlns:behaviors="using:NotificationsReviewer.Behaviors"
    behaviors:NavigationViewHeaderBehavior.HeaderMode="Never"
    mc:Ignorable="d">

    <Grid>
        <maps:MapControl
            x:Name="mapControl"
            Center="{x:Bind ViewModel.Center, Mode=OneWay}"
            ZoomLevel="{x:Bind ViewModel.ZoomLevel, Mode=OneWay}" />
    </Grid>
</Page>
```
