### ISSUE TITLE
Feedback requested for WPF mockup (Prism+ NavigationView)

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3337]
We'd love to hear your feedback on our WPF mockup for Prism. You can find the solution at https://github.com/mvegaca/MyDotNetCoreWpfApp/blob/dev/Prism.sln

Project setup is the following:

ProjectType:
- NavigationView (using Hamburger Menu)

Framework:
- Prism

Pages:
- Blank
- Settings

Features:
- MSIX Packaging
- Theme Support (Dark/Light)
- Setting Storage / Persisting app data

**Comment by sibille** [comment]
Doing the templates we saw we can reuse a lot of templates for Prism by adding the Suffix "Page" to the pages as we do in Uwp.

**Comment by OzBob** [comment]
[Prism project has a design time error with merged resources.](https://github.com/mvegaca/MyDotNetCoreWpfApp/issues/1)

MVVMLight project does not.

**Comment by OzBob** [comment]
I've cloned the https://github.com/mvegaca/MyDotNetCoreWpfApp repo and added Deeplinking parameters. Hopefully it can be used for the WTS.

Is there a list of WPF WTS features on the Backlog in an issue?

My list of features that I found useful from the UWP templates are:

 1 Master Detail views with navigation history (and the back button) working for each Detail View
 2 Master Detail has 3 'VisualStates' for different app widths with an AdaptiveTrigger
 3 When in 'small' visualstate the Master click into Detail view adds the Detail into the navigation history

**Comment by sibille** [comment]
Hi @ozbob, 
Great suggestions! Thank you!
We're looking into adding Identity templates for WPF in version 3.7 (https://github.com/microsoft/WindowsTemplateStudio/issues/3502) and are evaluating what else to add. 

Could you open a separate issue for each of your proposals? We can then get feedback from other people, discuss implementation options and when finally create the templates. 

If you'd like to contribute, have a look at https://github.com/microsoft/WindowsTemplateStudio/blob/dev/CONTRIBUTING.md. If you have any questions or doubts just open an issue.
