### ISSUE TITLE
Ask what version of the UWP SDK to target

### ISSUE THREAD

**Issue by mahoekst** [Microsoft/WindowsTemplateStudio#334]
When creating a new project the developer need to be asked what version (min and max) of the SDK the app should target. Ideally we can have version dependent pages and features as well which light up when you select a newer SDK. 

The system can detect what SDK's are installed and download the templates targetting those SDKs as well.

this could benefit when for example we expand with preview Windows 10 fall creators update features in the SDK's as well and we could create a few templates benefiting from those new features.

Ideally the UI asking for the version shows a nice piechart with the % of TH1/TH2/RS1/RS2 active users. Might be able to connect to a powerbi something we would like to have on dev center anyway :)

**Comment by mrlacey** [comment]
@crutkas what's driving your current plan that we should always only target the current and last versions?

**Comment by mrlacey** [comment]
There's​ overlap here with #327
Should we also limit options to SDKs installed on the machine?

**Comment by mrlacey** [comment]
@mahoekst re this:
> Ideally the UI asking for the version shows a nice piechart with the % of TH1/TH2/RS1/RS2 active users. Might be able to connect to a powerbi something we would like to have on dev center anyway :)

Do you have access to that %age breakdown for now, to help justify supporting different/older SDK versions before the dev center add this?

**Comment by mrlacey** [comment]
I'm assuming that this isn't something we're ever going to do as it just adds to the compatibility overhead where we have even more combinations of generated items and configurations to code for and test.
If definitely off the cards, can we close this?

**Comment by ralarcon** [comment]
I think so. The estatement to target the current windows version N, and N-1 as MinTargetVersion.

**Comment by crutkas** [comment]
yup :)  I totally get why @mahoekst wants it, but then we won't be able to move forward with bleeding edge stuff.
