### ISSUE TITLE
BackgroundTask and MultiInstance features are not compatible

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3342]
Features BackgroundTask and MultiInstance are not compatible.
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp

If you add both to a project, the project crashes at startup. 

To solve this problem I think we can add a tag to templates to mutually exclude them: 
	• BackgroundTask excludes MultiInstance
	• MultiInstance excludes BackgroundTask
	
If you try to add a template with exclusions the Wizard checks if any of the excluded templates is already there, and shows a notification like: You cannot add a Template A as the following templates do are not compatible: Template B.

**Comment by mrlacey** [comment]
:( it's documented as a known issue https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp#background-tasks-and-multi-instancing 😢 

A new tag and a warning seems like a good solution.

WACK tests should have caught this but are currently broken on the latest tooling as tools now produce msixbundle but the test is looking for .appxbundle - I'm fixing WACK tests as part of #3228

**Comment by sibille** [comment]
As background task and multiview are mutually exclusive they cannot be included together in the tests that generate projects with all pages and features. 

I've done separate tests for ProjectName validation, StyleCop and RightClick addition tests by creating groups of templates that are excluded from the test.

I've excluded them from the other tests that generate all pages and features for now, but I think we could unify those tests on the Stylecop tests.

**Comment by mvegaca** [comment]
Verified in dev
Templates version: 0.20.19288.1
Wizard version: 0.20.19288.1
