### ISSUE TITLE
Improve WACK testing

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3345]
Follow on from #3228 

These tests are currently a bit tempermental and fragile. Improve this.

**Comment by sibille** [comment]
@mrlacey, can we speed up the wack tests somehow?
Ideas: 
- Exclude the test projects 
- Only generate the x86 msixbundle

If not, can we split them in two ExecutionSets to do separate wack tests with BackgroundTask and MultiInstance?

**Comment by mrlacey** [comment]
All merged in and seem to be working ok
