### ISSUE TITLE
Combine template tests 

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3347]
With the growing permutation of things to test we should combine some tests and test as much as we can on each generated project. 
The following tests can be combined:
- `BuildEmptyProjectAndInferConfigAsync` and `BuildEmptyProjectAsync`
- `BuildAllPagesAndFeaturesAsync` and `BuildAllPagesAndFeaturesThenRunTestsAsync` with the `GenerateAllPagesAndFeaturesAndCheckWithStyleCopAsync` and `GenerateAllPagesAndFeaturesForcedLoginAndCheckWithVBStyleAsync` tests
- `BuildAllPagesAndFeaturesProjectNameValidationAsync` and `BuildAllPagesAndFeaturesRandomNamesAsync`

**Comment by mrlacey** [comment]
this might also be a good opportunity to also tidy up / address the warnings in the test output as this might help make reading test output easier.

**Comment by mrlacey** [comment]
Combining `BuildAllPagesAndFeaturesProjectNameValidationAsync` and `BuildAllPagesAndFeaturesRandomNamesAsync` means that `BuildAllPagesAndFeaturesRandomNamesAsync` will no longer be part of the CI tests.
Including the combined test as part of the CI set would increase CI test execution time and part of the reason for making these changes is to reduce execution time.

**Comment by sibille** [comment]
I think that's ok, stylecop tests should find most of the issues on pr builds. 
Full tests are triggered by each integration to dev/master, so if sth breaks we'll catch and fix.

**Comment by mrlacey** [comment]
closing as merged and have been executed in the nightly CI/DevOps process without issue
