### ISSUE TITLE
Question: Usage on INavigationAware on WPF MVVMBasic and MVVMLight

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3352]
We'd like to get some broader feedback on the following question: 

As WPF does not have an OnNavigatedTo EventHandler on the Page we wanted to provide something similar on the ViewModel. 

We followed  Prisms approach and introduced an interface INavigationAware for ViewModels, with two methods: OnNavigatedTo and OnNavigatingFrom. For ViewModels that implement the interface the NavigationService calls them as part of the navigation process. 

Do you like this approach on the frameworks MVVMBasic and MVVMLight or are we doing too much here? Would you prefer to work with the OnLoaded and OnUnLoaded events of the page? 

For implementation details you can look at the mockups at 
https://github.com/mvegaca/MyDotNetCoreWpfApp/blob/dev/MVVMBasic.sln
https://github.com/mvegaca/MyDotNetCoreWpfApp/blob/dev/MVVMLight.sln

X-Ref: #3336, #3318

**Comment by SariDev** [comment]
I personally would go for an INavigationAware style  interface + implementation instead of using the events.

This makes it easier to control these situations from ViewModel code and avoids references to UI libraries.
