### ISSUE TITLE
VS Preview - System.ArgumentNullException - Getting "Something went wrong" whenever I hit the Create button

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsTemplateStudio#336]
I get the following error whenever I hit the _Create_ button, regardless what template I chose.

> Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App6', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()

Please note that I am on Windows 10 build _16193_ and I am using Visual Studio 2017 Enterprise (version _15.2_ (_26430.6_)).

**Comment by crutkas** [comment]
Can you give the logs from c:\programdata\windeostemplatestudio?  If you don't want to upload, email crutkas@microsoft.com

Is the VS instance a preview build?

**Comment by JustinXinLiu** [comment]
Here's the full log.

> >>>>>>>>>>>>>> Log started 20170514 09:17:01.366
> >>>>>>>>>>>>>> Assembly File Version: 1.0.17131.1
> [20170514 09:17:01.516]	Justin	1956(1)		Information	Configuration file loaded: C:\USERS\JUSTIN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_96CE7F9E\EXTENSIONS\OZTRD14J.2QO\WindowsTemplateStudio.config.json
> 
> >>>>>>>>>>>>>> Log started 20170514 09:21:18.115
> >>>>>>>>>>>>>> Assembly File Version: 1.0.17131.1
> [20170514 09:21:18.270]	Justin	13556(1)		Information	Configuration file loaded: C:\USERS\JUSTIN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_FCDBD421\EXTENSIONS\NI1DNRGC.LQ5\WindowsTemplateStudio.config.json
> [20170514 09:22:09.816]	Justin	13556(1)		Information	Creating Windows Template Studio project...
> [20170514 09:22:09.867]	Justin	13556(1)		Information	Generating the template SplitView to c:\users\justin\documents\visual studio 2017\Projects\WindowsTempateStudioRepo\WindowsTempateStudioRepo.
> [20170514 09:22:10.397]	Justin	13556(1)		Error	Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'WindowsTempateStudioRepo', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> [20170514 09:22:10.417]	Justin	13556(1)		Critical	Exception Tracked. ProjectType: 'SplitView'
> Framework: 'MVVMBasic'
> Pages: 'Main - Blank'
> Features: 'SettingsStorage - Settings Storage, SuspendAndResume - Suspend and Resume'
> 
> ===================== Exception Info =====================
> Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'WindowsTempateStudioRepo', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> ----------------------------------------------------------
> [20170514 09:23:27.391]	Justin	13556(1)		Information	Creating Windows Template Studio project...
> [20170514 09:23:27.430]	Justin	13556(1)		Information	Generating the template SplitView to c:\users\justin\documents\visual studio 2017\Projects\App2\App2.
> [20170514 09:23:27.572]	Justin	13556(1)		Error	Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App2', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> [20170514 09:23:27.587]	Justin	13556(1)		Critical	Exception Tracked. ProjectType: 'SplitView'
> Framework: 'CodeBehind'
> Pages: 'Main - Blank'
> Features: 'SettingsStorage - Settings Storage, SuspendAndResume - Suspend and Resume'
> 
> ===================== Exception Info =====================
> Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App2', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> ----------------------------------------------------------
> [20170514 09:23:53.291]	Justin	13556(1)		Information	Creating Windows Template Studio project...
> [20170514 09:23:53.322]	Justin	13556(1)		Information	Generating the template SplitView to c:\users\justin\documents\visual studio 2017\Projects\App3\App3.
> [20170514 09:23:53.387]	Justin	13556(1)		Error	Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App3', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> [20170514 09:23:53.393]	Justin	13556(1)		Critical	Exception Tracked. ProjectType: 'SplitView'
> Framework: 'CodeBehind'
> Pages: 'Main - Blank'
> 
> ===================== Exception Info =====================
> Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App3', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> ----------------------------------------------------------
> [20170514 09:24:29.157]	Justin	13556(1)		Information	Creating Windows Template Studio project...
> [20170514 09:24:29.211]	Justin	13556(1)		Information	Generating the template TabbedPivot to c:\users\justin\documents\visual studio 2017\Projects\App4\App4.
> [20170514 09:24:29.305]	Justin	13556(1)		Error	Microsoft.Templates.UI.GenException: Template 'TabbedPivot', name: 'App4', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> [20170514 09:24:29.312]	Justin	13556(1)		Critical	Exception Tracked. ProjectType: 'TabbedPivot'
> Framework: 'CodeBehind'
> Pages: 'Main - Blank, Tabbed - Tabbed'
> Features: 'SettingsStorage - Settings Storage, SuspendAndResume - Suspend and Resume'
> 
> ===================== Exception Info =====================
> Microsoft.Templates.UI.GenException: Template 'TabbedPivot', name: 'App4', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> ----------------------------------------------------------
> [20170514 09:25:44.438]	Justin	13556(1)		Information	Creating Windows Template Studio project...
> [20170514 09:25:44.472]	Justin	13556(1)		Information	Generating the template Blank to c:\users\justin\documents\visual studio 2017\Projects\App5\App5.
> [20170514 09:25:44.584]	Justin	13556(1)		Error	Microsoft.Templates.UI.GenException: Template 'Blank', name: 'App5', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> [20170514 09:25:44.600]	Justin	13556(1)		Critical	Exception Tracked. ProjectType: 'Blank'
> Framework: 'CodeBehind'
> Pages: 'Main - Blank'
> Features: 'SettingsStorage - Settings Storage, SuspendAndResume - Suspend and Resume'
> 
> ===================== Exception Info =====================
> Microsoft.Templates.UI.GenException: Template 'Blank', name: 'App5', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> ----------------------------------------------------------
> [20170514 09:33:35.926]	Justin	13556(1)		Information	Creating Windows Template Studio project...
> [20170514 09:33:35.949]	Justin	13556(1)		Information	Generating the template SplitView to c:\users\justin\documents\visual studio 2017\Projects\App6\App6.
> [20170514 09:33:36.093]	Justin	13556(1)		Error	Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App6', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> [20170514 09:33:36.108]	Justin	13556(1)		Critical	Exception Tracked. ProjectType: 'SplitView'
> Framework: 'CodeBehind'
> Pages: 'Main - Blank'
> 
> ===================== Exception Info =====================
> Microsoft.Templates.UI.GenException: Template 'SplitView', name: 'App6', reason: 'Value cannot be null.
> Parameter name: type'
>    at Microsoft.Templates.UI.GenController.<UnsafeGenerateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Templates.UI.GenController.<GenerateAsync>d__1.MoveNext()
> ----------------------------------------------------------
> 

No, it's not. I tried with the Preview build first but got nothing showing up in the template section. Then I tried the normal build (version listed above), all templates showed up correctly but it failed to create.

**Comment by crutkas** [comment]
Yeah, This is the non-RTM build version we noticed right during Build.

**Comment by crutkas** [comment]
This could be related to #328.  Different errors

**Comment by JustinXinLiu** [comment]
I can now generate new projects without errors. Thanks guys!

**Comment by crutkas** [comment]
Awesome!
