### ISSUE TITLE
Icon for WTS is very faint in the Small Icons view in VS New project window

### ISSUE THREAD

**Issue by degant** [Microsoft/WindowsTemplateStudio#340]
When opening the new project window in VS2017 and using 'Small Icons' option instead of 'Medium Icons', the icon for WTS is very faint and not in line with the rest of the icons. Please take a look at the screenshot:

![image](https://cloud.githubusercontent.com/assets/6065982/26044807/2224826a-3964-11e7-97ab-e9349d6f0ac9.png)

**Comment by crutkas** [comment]
good catch, we need to do a white wrapper.
