### ISSUE TITLE
[Wizard] Link not set in the description for Tabbed Page

### ISSUE THREAD

**Issue by degant** [Microsoft/WindowsTemplateStudio#341]
The Link in the description for Tabbed Page in the Wizard is plain text and not a hyperlink unlike other pages. The link 'https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tabs-pivot' should be clickable.

![image](https://cloud.githubusercontent.com/assets/6065982/26073665/1d0534aa-39cd-11e7-8f51-d3ea3129379a.png)

**Comment by crutkas** [comment]
good catch!  PR approved
