### ISSUE TITLE
The menu button jumps from the original location after the menu is launched.

### ISSUE THREAD

**Issue by shaheedmalik** [microsoft/WindowsTemplateStudio#3418]
**Describe the bug**
The menu button jumps from the original location after the menu is launched.
Navigation Pane C# Universal Windows Navigation Pane

**To Reproduce**
Create a new Navigation Pane template with Code Behind and at least 6 pages.'.'
2. Shink the window size to minimal  '....'
3. Click on the Split View menu'....'

![App92019-11-0110-51-54](https://user-images.githubusercontent.com/51347950/68033635-79c8af80-fc96-11e9-9665-aae0c1b8137f.gif)
**Expected behavior**
The Back button should be shown while the menu is open to keep the Menu button from jumping.
https://github.com/microsoft/microsoft-ui-xaml/issues/563 should have fixed the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/51347950/68034673-7cc49f80-fc98-11e9-8e83-7e55a82f6313.png)
![image](https://user-images.githubusercontent.com/13142665/58736956-8a59be80-83b4-11e9-95e7-2b888ce0ee42.png)

**Additional context**
It seems like Microsoft.UI.Xaml v2.2.190830001 (https://github.com/microsoft/microsoft-ui-xaml/pull/1195) fixed this issue however, in the current Windows Template Studio, the problem persists in the Templates.

**System**

- VS Version: C++ 2019 00435-60000-00000-AA805
- WinTS Wizard Version: 1.0
- WinTS Template Version: 3.4.19254.1
- Windows Build: 1862.10024

**Comment by mvegaca** [comment]
This becomes fixed updating the WinUI nuget version, this Issue will be fixed on next 3.5 Release of Windows Template Studio
