### ISSUE TITLE
Docs for WPF

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3428]
We should add docs for new WPF templates and update existing docs to reflect that we now support UWP and WPF platforms.

General docs common to UWP/WPF to adapt:
 - Readme
 - getting-started-extension
 - Concepts
 - getting-started-developers
 - Templates
 - Telemetry
 - accessibility
 - CONTRIBUTING
 - newitem

Docs that should be created for WPF:
 - getting-started-endusers
 - Docs related to Frameworks and Project Types.
 - Docs related to Pages and Features
 - Docs related to App Lifecycle / Navigation.

We propose the following folder structure:
 - Docs (for common docs)
 - Docs/UWP (for UWP specific docs)
 - Docs/WPF (for WPF specific docs)

we will maintain current docs that are referenced in templates providing a redirect link to new docs in order to not break existing links in already generated projects as we do [here](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/mvvmbasic.md).

**Comment by sibille** [comment]
Verified in dev
