### ISSUE TITLE
Review telemetry for WPF + Adapt tools

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3429]
- [x] Review everything is reported correctly
- [x] Adapt dashboard
- [x] Adapt WtsTelemetry function

**Comment by Adeelessa** [comment]
Guys who were helping me to make my Motorola One Power Cell phone to be upgraded to Android 9 Pie. It's totally makes me sick without u guys I even can't imagine I can go that much far & u guys will be with me on my back for Assistance.

Regards,
Adeel Essa
adeelessa@gmail.com

**Comment by sibille** [comment]
Verified in dev-nightly;
Templates version: 0.21.20042.1
Wizard version: 0.21.20042.1
