### ISSUE TITLE
Templates not shown in Blend

### ISSUE THREAD

**Issue by ridomin** [Microsoft/WindowsTemplateStudio#343]
Can you enable the WTS wizard from Blend File->New Project ?

**Comment by mrlacey** [comment]
It shows up when searching

![image](https://cloud.githubusercontent.com/assets/189547/26123758/e7266034-3a30-11e7-8014-5dcde77988a8.png)

Install reports success but then it doesn't show up in the New Project list

**Comment by crutkas** [comment]
Happily will accept a PR for someone to add it in.

**Comment by mrlacey** [comment]
According to a comment, by someone on the VS IDE team, on a related issue [here](https://github.com/github/VisualStudio/issues/951) extensions in Blend require whitelisting.
If we really want this, @crutkas can you find out more about whitelisting?

**Comment by mgoertz-msft** [comment]
@crutkas I have a local fix for this. How do I create a PR? I cannot push my local branch and I cannot fork the repo either. Do you need to add me to this project first?

**Comment by mgoertz-msft** [comment]
PR #361 has the fix for this issue.

**Comment by crutkas** [comment]
in dev branch now
