### ISSUE TITLE
Accessibility for WPF

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3459]
We should fix these accessibility issues to be aligned with best practices and accessibility for WPF apps.

## UI

- [x] Ensure Automation properties (Id, Name and Help Text) are set correctly.
- [x] Ensure all UI correctly scales by any DPI setting.
- [x] Ensure that UI elements fit in a screen of 1024 x 768 with 120 (dpi).
- [x] High contrast (x-Ref https://github.com/MahApps/MahApps.Metro/issues/3831 and https://github.com/MahApps/MahApps.Metro/issues/3880).
- [x] Set automation properties for hamburger menu (x-ref https://github.com/MahApps/MahApps.Metro/issues/3839).

## Navigation

- [x] Add shortcuts for all commands.
- [x] Add accelerator keys en menus, submenus and add TODO comments to indicate to the developers that they should add accelerator keys to the pages.

**Comment by mrlacey** [comment]
Did the guidelines mentioned above come from a public source/page? if so, can it be linked for reference?
Similarly, any reference documents for how to test this would be useful for future verification of templates.

**Comment by mvegaca** [comment]
[This is the doc](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/accessibility-best-practices) for WPF Apps Accessibility best practices

**Comment by punker76** [comment]
@mvegaca @sibille Setting automation properties for hamburger menu (items, button) are coming in v2.1 [PR](https://github.com/MahApps/MahApps.Metro/pull/3856)

**Comment by sibille** [comment]
Awesome, thanks! When is v2.1 shipping?

**Comment by sibille** [comment]
Moving to 3.8 for the remaining work

**Comment by punker76** [comment]
@sibille @mvegaca This issue is now fixed and available with MahApps v2.1.1 and ControlzEx v4.3.1

>  High contrast (x-Ref MahApps/MahApps.Metro#3831).

**Comment by sibille** [comment]
@punker76 awesome, thanks! We'll try it out. 
One doubt: Do we still have to add our custom high contrast theme or are there plans to add a high contrast theme to MahApps?

**Comment by sibille** [comment]
As MahApps/MahApps.Metro#3880 is fixed now, we're looking into adding High Contrast support to WPF templates.

Plan is to provide very basic HC themes, that the user has to complete with the colors and brushes used in the app. We'll add a developer TODO with links to the docs and theme templates provided by MahApps.

A mockup can be found at https://github.com/sibille/WTS.WPF.HighContrastSupport
We'll also add a "Windows default" option on the settings page which will set the theme the default theme configured in Windows.

**Comment by sibille** [comment]
Verified in dev-nighty version:
Templates version: 0.22.20336.2
Wizard version: 0.22.20336.1
