### ISSUE TITLE
Won't install on VS 2017 Pro for some reason

### ISSUE THREAD

**Issue by waleed66** [Microsoft/WindowsTemplateStudio#347]
Won't install on VS 2017 Pro for some reason

**Comment by crutkas** [comment]
What version of VS are you running?  15.1?  Can you take a screenshot of your about screen?

Current release is 15.2 (26430.6)

**Comment by crutkas** [comment]
@waleed66 can you give us more information here?

**Comment by crutkas** [comment]
@waleed66 without additional information, we can't help out here.  We have a bunch of pending fixes that iron out a few edge cases for the installer that will be released on Monday and we hit the two primary blockers a few days ago.

By Monday if you haven't responded, we'll close this out due to not enough information.

**Comment by EricAtMSFT** [comment]
I have the same issue. VS 2017 15.0.0 26228.9

Windows Version: 15063.296

**Comment by ralarcon** [comment]
Looks like you are running a preview version. The dependency detection would be blocking the installation while using preview releases of VS. We plan to release an update for the extension by the beginning of next week which probably will unlock this. Stay tuned!

**Comment by EricAtMSFT** [comment]
Cool. Updating to 2017 15.2 seems to have fixed the issue. It's installing now. Good idea on making the error more verbose.

**Comment by mrlacey** [comment]
@EricAtMSFT yes, 'VS 2017 15.0.0 26228.9' is the original RTM version of VS2017. Unfortunately, you need to be on Update 1 or later to use this extension. I'll update the docs to reflect this.

**Comment by crutkas** [comment]
Fixed in dev
