### ISSUE TITLE
"No Content available" Under VS Enterprise 2017. and get error  "The folder d:\Temp\4ws1mcke.vul\Templates can't be moved to C:\ProgramData\WindowsTemplateStudio\Templates\Pro\1.0.17131.2."

### ISSUE THREAD

**Issue by waleed66** [Microsoft/WindowsTemplateStudio#348]
"No Content available" Under VS Enterprise 2017.
and get error 
"The folder d:\Temp\4ws1mcke.vul\Templates can't be moved to C:\ProgramData\WindowsTemplateStudio\Templates\Pro\1.0.17131.2."

**Comment by crutkas** [comment]
Dup of #333.  We have a fix for this and will update the VSIX shortly.
