### ISSUE TITLE
After installing WTS, It appeared in the list of template but the Windows Template Studio dialog displayed - No Content.

### ISSUE THREAD

**Issue by waleed66** [Microsoft/WindowsTemplateStudio#349]
After installing WTS, It appeared in the list of template but the Windows Template Studio dialog displayed - No Content.

**Comment by crutkas** [comment]
Can you provide a bit more to help us out?  What version of VS are you on?  Is your temp directory on a different drive? 

Can you give us the logs C:\ProgramData\WindowsTemplateStudio\Logs here so we can see what exception may have been thrown?

**Comment by bon-github** [comment]
Alright, Attached is the Log file. 
[WTS_Pro_20170513.txt](https://github.com/Microsoft/WindowsTemplateStudio/files/1007442/WTS_Pro_20170513.txt)

**Comment by mrlacey** [comment]
@bon-github the log file indicates that you weren't online when trying to use the tool. The templates are not included with the wizard but must be downloaded on first use. They are cached for subsequent use but the wizard will try and download the latest ones so you get bug fixes, etc. ASAP.
We already have an issue to track and improve this experience at #311

**Comment by crutkas** [comment]
This should be initially done by #311 for initial offline support.
