### ISSUE TITLE
Update nugets in WPF Templates to latest version

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3490]
Review and update nugets in WPF Templates to latest version.

**Comment by mvegaca** [comment]
**New Nuget versions:**

AdaptiveCards
**1.2.4**

Appium.WebDriver
**4.1.1**

Microsoft.AppCenter.Analytics
**2.6.4**

Microsoft.AppCenter.Crashes
**2.6.4**

Microsoft.Identity.Client
**4.7.1**

Microsoft.NET.Test.Sdk
**16.4.0**

Microsoft.Toolkit.Uwp
**6.0.0**

Microsoft.Toolkit.Uwp.UI.Controls
**6.0.0**

Microsoft.Toolkit.Uwp.UI.Animations
**6.0.0**

Microsoft.Toolkit.Uwp.UI.Controls.DataGrid
**6.0.0**

Microsoft.Toolkit.Uwp.Notifications
**6.0.0**

Microsoft.UI.Xaml
**2.3.191211002**

Moq
**4.13.1**

Newtonsoft.Json
**12.0.3**

NUnit3TestAdapter
**3.16.0**

SonarAnalyzer.VisualBasic
**8.2.0.14119**

System.Configuration.ConfigurationManager
**4.7.0**

Swashbuckle.AspNetCore
**5.0.0**

Telerik.UI.for.UniversalWindowsPlatform
**1.0.1.8**

Win2D.uwp
**1.24.0**

**Comment by sibille** [comment]
New packages available for: 
- Microsoft.Identity.Client

**Comment by sibille** [comment]
New packages available for:

- Microsoft.Identity.Client
- Microsoft.Toolkit.Wpf.UI.Controls.WebView
- Microsoft.Extensions.Hosting
- Microsoft.Extensions.Http
- Microsoft.Extensions.Configuration
- Microsoft.Extensions.Configuration.Binder
- OSVersionHelper
- Microsoft.Identity.Client

**Comment by sibille** [comment]
Verified in dev-nighlty:
Templates version: 0.22.20181.1
Wizard version: 0.22.20179.1
