### ISSUE TITLE
Generated Content Grid Page Does Not Scroll

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3493]
**Describe the bug**
When the content on a generated detail page from the Content Grid template is too long to view, the page does not scroll.

**To Reproduce**
1. Generate a New Page
2. Select Content Grid.
3. Run the application.
4. Select your new page from the Navigation Menu.
5. Select any of the sample companies.
6. Make the window small enough so all the data cannot be seen.
7. Try to scroll to see the rest of the data.

**Expected behavior**
The window scrolls vertically to see the rest of the data.

**Screenshots**
![image](https://user-images.githubusercontent.com/4465616/71295505-b8e3ba80-2341-11ea-99ca-0abbb00efaff.png)

**System**

- **VS Version:** 16.4.2
- **WinTS Wizard Version:** 3.5.19310.1
- **WinTS Template Version:** 3.5.19310.1
- **Windows Build:** 1909 - 18363.535

**Comment by scottkuhl** [comment]
The simple fix would seem to be to put a scroll viewer control around the outer most stack panel.  But a more complex solution might be desired that only scrolls the note area if there is enough room.

**Comment by sibille** [comment]
Thanks for reporting @scottkuhl!

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.21.20030.1
Wizard version: 0.21.20030.1

**Comment by sibille** [comment]
Reopening to fix connected animation which was broken by adding the scrollviewer.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.21.20048.1
Wizard version: 0.21.20048.1
