### ISSUE TITLE
Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.18362.0"

### ISSUE THREAD

**Issue by karwanessmat** [microsoft/WindowsTemplateStudio#3497]
Hi dear
I am using vs 2019
and I have used the last windows version 1903
I have tried to run the application but I have always got this message
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find SDK "Microsoft.UniversalCRT.Debug, Version=10.0.18362.0".	

best regard

**Comment by sibille** [comment]
Hi @karwanessmat, thanks for reporting! Could you provide some more details? 
Do you get this error when generating the project or once you try to compile the generated project? Do you have the Windows 10 SDK (10.0.18362.0) installed (https://developer.microsoft.com/windows/downloads/windows-10-sdk)?

**Comment by sibille** [comment]
Hi @karwanessmat, could you provide some more detail to reproduce this issue? When exactly do you get this error? What's your OS?

**Comment by sibille** [comment]
Closing this, please reopen with more details to reproduce if this is still happening
