### ISSUE TITLE
Immediate bju on Lauch

### ISSUE THREAD

**Issue by srcoxlive** [Microsoft/WindowsTemplateStudio#351]
![snip_20170517014340](https://cloud.githubusercontent.com/assets/17368341/26133860/5d106df0-3aa2-11e7-9490-1f83b136d8da.png)

**Comment by crutkas** [comment]
dup of #328  fix is in place.  I bet you're on a VS 2017 preview, right?

**Comment by crutkas** [comment]
Closing this out as a dup.  If it isn't, please comment

**Comment by srcoxlive** [comment]
if a fix is in place for this dup, where can I find it?

**Comment by crutkas** [comment]
Should be live now. v1.0.17137.1.  Fix is in dev and master branch as well.

**Comment by srcoxlive** [comment]
Big thanks,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
