### ISSUE TITLE
Overview tab does not open automatically on project creation

### ISSUE THREAD

**Issue by prasethu** [Microsoft/WindowsTemplateStudio#353]
I'm blocked on trying this out because this extension is so broken on Preview bits, but I'm certain that either the tab isn't authored correctly OR on project creation when the shell queries for project capabilities, the project does not return the right capabilities and hence the shell doesn't show the Overview tab.

1. Install VS 2017 with UWP workload selected

2. Add the Windows Template Studio extension by following the instructions here:

https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/getting-started-extension.md

3. File -> New project with the Windows Template Studio template

4. Select anything in the wizard, shouldn't matter

Expected Results:

Overview page appears after creation completes

Actual Results:

No overview page appears. You can right click on the project to view the overview page manually.

**Comment by mrlacey** [comment]
@prasethu what do you mean by "overview tab"?
- a particular page within the project?
- a new page that details what can/should be done with the generated project?
- the project properties page?
- something else?

**Comment by crutkas** [comment]
@prasethu are you saying once VS fully loads the project you want to see some type of page load in VS?  This doesn't happen with a file->new->blank app template.

**Comment by diverdan92** [comment]
@crutkas this should happen with file -> new blank app. If that also doesn't happen, @prasethu should take a look first.

**Comment by crutkas** [comment]
OK, i see what you guys are talking about.
![capture2](https://cloud.githubusercontent.com/assets/1462282/26168590/7bdae74a-3aef-11e7-9c91-523fa20cd20e.PNG)

To get there without intervention
![capture](https://cloud.githubusercontent.com/assets/1462282/26168589/7bd9dcb0-3aef-11e7-9074-011e2a587509.PNG)

**Comment by ralarcon** [comment]
I know we had reviewed this to consider a way to show the "TODOs" but it was not extensible... I'm not sure if we finally do not open the Overview because it wasn't accessible thru the automation objects, we can have a look on it.

By the way, do we need to reconsider the experience after generation? An approach would be to show the "next steps" for developers in a "startup" page.

**Comment by sibille** [comment]
We're showing the overview page now, next step is finding out if we can personalize it or show another startup page (#2282)

**Comment by mvegaca** [comment]
Checked in Dev-Nightly
Templates version: 0.18.18152.1
Wizard version: 0.18.18152.1
