### ISSUE TITLE
Question: Getting Xunit tests working

### ISSUE THREAD

**Issue by hooligan495** [microsoft/WindowsTemplateStudio#3546]
Hi, 
I've an app generated with teh WindowsTemplateStudio from last year.  I've noticed that the latest version of the template has the ability to generate an app with an XUnit project linked directly to the app.  So I generated an empty project and I'm trying to layer in a test project into my app.  However I'm getting a weird compile error:

`4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1879,5): error APPX1101: Payload contains two or more files with the same destination path 'Properties\Default.rd.xml'. Source files: 
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1879,5): error APPX1101: C:\UnitTests\Properties\Default.rd.xml
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1879,5): error APPX1101: C:\MyApp\Properties\Default.rd.xml
4>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1879,5): error APPX1101: Payload contains two or more files with the same destination path 'Assets\SplashScreen.scale-200.png'. Source files: 
`
This seems to happen for all the 'default' assets in my application and xunit app.   I've been trying to use the sample app I generated with the latest WTS and layer in a new test app.  I've all the packages between my app and the Xunit app aligned (I think).   I've been through all the XUnit documentation on how to add xunit tests to a UWP app but the directions I can find (so far) seem different than what's happening in the WTS.  
Does anyone have any "debugging" tips, wild ideas, anything I they can throw my way that might help me figure out this issue?  

If it helps any:
Our original WTS based app (gen'd with the 3.1 template) has:
folders like:
\App
\App.Core
\AppTests <--- this is what I'm trying to add

I was able to get the Test project to compile if I ONLY add the App.Core dll as a reference.  But I don't want to move all my code to the Core project.  From looking at the "sample" i generated with the latest WTS it looks like I should just be able to add my main app as a reference.

Any ideas are greatly appreciated.

**Comment by sibille** [comment]
Hi hooligan495, 
could you give us more info to reproduce the problem your facing? 
- What framework/project type did you use when you first generated the project?
- Which VS Version are you using?
- Are you getting the compilation error when trying to add the Test Project to the original project?
- You tried to generate a new app with the latest WTS version, did this app compile correctly or are you getting the same error?
- Did you add the Test feature using the "Add new testing project" option from the projects context menu? 
- Can you share a repo?

Looking at what gets generated on the latest WTS version for "Test App with XUnit" I've seen that in the UnitTest project the .rd.xml file is called "UnitTestApp.rd.xml", this might solve the first error.

**Comment by hooligan495** [comment]
Sorry for the long delay... It's been a bit crazy recently... 

I didn't generate the original project but here are the manifest settings that answer your first question:
    <genTemplate:Item Name="generator" Value="Windows Template Studio" />
    <genTemplate:Item Name="wizardVersion" Version="v3.0.19038.1" />
    <genTemplate:Item Name="templatesVersion" Version="v3.0.19038.1" />
    <genTemplate:Item Name="projectType" Value="TabbedNav" />
    <genTemplate:Item Name="framework" Value="MVVMLight" />
    <genTemplate:Item Name="platform" Value="Uwp" />

VS= 2017 and 2019

When I add a reference to the original project to my test project that's when compilation starts failing.  

If I generate a new app with an XUnit test it generates and compiles

you asked: 
"Did you add the Test feature using the "Add new testing project" option from the projects context menu?" 
I'm not sure I follow what you are asking here. 

I can't share my repo at the moment.  I'll try to see if I can create a different dummy repo with teh same problem. 

I did rename the rd.xml file and it solved that one... but it still complains about duplicate assets files.

**Comment by mrlacey** [comment]
This looks like the same as #3795 

closing as duplicate and stale
