### ISSUE TITLE
Content dialog does not take the dark theme if set through the application settings

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3565]
**Describe the bug**
Create a derived ContentDialog and display it after setting the theme to dark in settings page

```cs
    public sealed partial class ImportFeedDialog : ContentDialog     
    {
    }
```

**Expected behavior**
Content dialog should take the dark theme

**Additional context**

**System**

- **VS Version:** 16.4
- Templates version: 3.5.19310.1
- Wizard version: 3.5.19310.1
- **Windows Build:** 1803

**Comment by sibille** [comment]
Hi @havinders, 
you'll have to set the RequestedTheme when opening the dialog like we do in the "Whats new prompt" feature. 

`RequestedTheme = (Window.Current.Content as FrameworkElement).RequestedTheme;`

More info about this in https://github.com/microsoft/WindowsTemplateStudio/issues/1998

**Comment by harvinders** [comment]
Thanks @sibille. It almost worked for me.

I am however still seeing some differences. I might have to create a repo app to confirm though, maybe there is some issues in my app.

The left hand side shot is with   OS Theme = Light and App Theme = Dark.
The right hand side shot is with OS Theme = Dark and App Theme = Dark.

![image](https://user-images.githubusercontent.com/8557046/74833224-2a091380-536d-11ea-88e0-540f6c7026ab.png)

**Comment by mvegaca** [comment]
The color that apps uses to show this overlay is a theme color with name `SystemControlPageBackgroundMediumAltMediumBrush` that depends on windows theme.

**generic.xaml**

```xml
<SolidColorBrush x:Key="SystemControlPageBackgroundMediumAltMediumBrush" Color="{StaticResource SystemColorWindowColor}" Opacity="0.6" />
```

A possible workaround could be set a color that gets a nice result in Ligkt and Dark mode and overrides this color in theme resource dictionaries.

**App.xaml**

```xml
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Styles/_Colors.xaml" />
                <ResourceDictionary Source="/Styles/_FontSizes.xaml" />
                <ResourceDictionary Source="/Styles/_Thickness.xaml" />

                <ResourceDictionary Source="/Styles/TextBlock.xaml" />
                <ResourceDictionary Source="/Styles/Page.xaml"/>
            </ResourceDictionary.MergedDictionaries>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Dark">
                    <SolidColorBrush x:Key="SystemControlPageBackgroundMediumAltMediumBrush" Color="#FF999999" />                    
                </ResourceDictionary>
                <ResourceDictionary x:Key="Light">
                    <SolidColorBrush x:Key="SystemControlPageBackgroundMediumAltMediumBrush" Color="#FF999999" />                    
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

![image](https://user-images.githubusercontent.com/5556784/79234934-44420800-7e6b-11ea-8226-f2625f1ab263.png)

![image](https://user-images.githubusercontent.com/5556784/79234951-499f5280-7e6b-11ea-850c-2f6c009770f5.png)

This is a repro app created for this workarround.
[Issue3565App.zip](https://github.com/microsoft/WindowsTemplateStudio/files/4475801/Issue3565App.zip)
