### ISSUE TITLE
VSIX / WTS needs to better handle incorrect versions of VS and Windows

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#357]
There have been issues where an earlier version of windows #339 causes a crypto error and VS 15.1 preventing the installer with an error that isn't straight forward.  We should account for these and provide better guidance.  

This may actually need to be broken into two issues.  1 for invalid version of Windows, one for invalid version of VS

**Comment by ralarcon** [comment]
I'm assiging this to my self as I will be working on it.
