### ISSUE TITLE
VS Emulator: Recreate app

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3571]
Add a button in the generation details that recreates the same app (user selection and folder destination).

This will be very usefull because when we are creating templates there are times when you fix something in the template and you want to generate the same app to check if the issue is fixed or not and you always have to open the wizard and set the same user selection.

**Comment by sibille** [comment]
UserSelection from wpf and uwp should be stored separately.

**Comment by sibille** [comment]
Verified in dev
