### ISSUE TITLE
Removed ClientID for Identity templates

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3577]
We've removed the ClientID from our Identity templates. Please create your own ClientID follwoing the steps in https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app

**Comment by Javier118** [comment]
I've been selling the example I downloaded into Azure by looking at the example I've seen that in the call for authentication comes the scopes code.  the doubt is that part of the OnLOggedIn code I have to introduce scopes , also example I have seen this code that goes intinialize();

>  PublicClientApp = PublicClientApplicationBuilder.Create(ClientId)
                .WithAuthority("https://login.microsoftonline.com/common")
                .WithLogging((level, message, containsPii) =>
                {
                    Debug.WriteLine($"MSAL: {level} {message} ");
                }, LogLevel.Warning, enablePiiLogging: false, enableDefaultPlatformLogging: true)
                .WithUseCorporateNetwork(true)
                .WithRedirectUri(Constant.PublicClientRedirectUri)
                .Build();
