### ISSUE TITLE
Log in Fails Immediately After Generation

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3584]
**Describe the bug**
After generating a new application and selecting the Optional Login service, you can not login.

**To Reproduce**
1. Generate a new application.
2. Select the Optional Login service.
3. Run the application.
4. Select Login from the navigation menu.
5. Login with a Microsoft account.
6. An error is produced: unauthorized_client.

**Expected behavior**
User should be logged into the application with the Microsoft account they used.

**Screenshots**

![image](https://user-images.githubusercontent.com/4465616/75513689-328bca80-59bb-11ea-8a4d-7fca46929b8e.png)

**Additional context**
I am testing this with a personal account with two-factor authentication enabled.  I have not registered the application within the Azure Portal because it seems like according to the documentation it should work with the test client id.

> The app includes a ClientID that is for testing purposes only.

**System**

- **VS Version:** 16.4.5
- **WinTS Wizard Version:** 3.5.19310.1
- **WinTS Template Version:** 3.5.19310.1
- **Windows Build:** 18363.657

**Comment by scottkuhl** [comment]
I also tried enabling the Private Networks (Client & Server) capability as suggested for the OneDrive Service for the Windows Community Toolkit and that did not help.

The error I am getting in the Output window is:

Exception thrown: 'Microsoft.Identity.Client.MsalServiceException' in System.Private.CoreLib.dll

**Comment by sibille** [comment]
Hi @scottkuhl, Thanks for reporting. 

We recently disabled the test clientID. Please create your own ClientID follwoing the steps in https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app. 

We're updating the templates accordingly. 

X-Ref: https://github.com/microsoft/WindowsTemplateStudio/issues/3577

**Comment by sibille** [comment]
Closing as dup of #3577
