### ISSUE TITLE
Optional Login Configuration Question

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3585]
I am trying to register an application for Optional Login primarily for use with personal accounts and need some guidance.  I used the Application (client id) as the IdentityClientId in the app config and here is the configuration is Azure:

![image](https://user-images.githubusercontent.com/4465616/75515209-15f19180-59bf-11ea-9cca-7638f384631d.png)

I receive the following exception after login:

ErrorCode: "invalid_client"

Message: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal.

Description: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application.

I think what I am missing is the redirect URI of the application.  I'm not sure what to put in for that.

Any guidance is appreciated.

System

VS Version: 16.4.5
WinTS Wizard Version: 3.5.19310.1
WinTS Template Version: 3.5.19310.1
Windows Build: 18363.657

**Comment by sibille** [comment]
Please add "urn:ietf:wg:oauth:2.0:oob" to the Redirect URIs, as stated in https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/Client-Applications#redirect-uri

**Comment by scottkuhl** [comment]
That was it.  Thank you.
