### ISSUE TITLE
New TwoPaneView UWP Page Template

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3596]
Create a new UWP page template that uses the new WinUI TwoPaneView control to optimize the content in dual screen devices. This will show a master-detail patern to display content.

**Comment by sibille** [comment]
Adding a twopaneview to prism results in the following error:
Some NuGet packages could not be added to your project App165/App165.csproj. This could have been caused if you were offline. 
Please verify the following list of packages needed by your project's code and manually add the missing packages: 

Install-Package -Id Microsoft.UI.Xaml -Version 2.3.200213001
Install-Package -Id Microsoft.Toolkit.Uwp.UI.Controls -Version 6.0.0

**Comment by sibille** [comment]
Verified in dev-nightly;
Templates version: 0.21.20118.1
Wizard version: 0.21.20118.1
