### ISSUE TITLE
Nuget package issues when first creating template

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/WindowsTemplateStudio#3598]
When creating a new app there are always problems with the nuget packages

VS Version: 16.5.0
WinTS Wizard Version: 0.21.20081.1
WinTS Template Version:  0.21.20081.1

Create an app using the simplest features.

**Expected behavior**
To be able to build an app.

**Screenshots**

We get a file like this:

_Some NuGet packages could not be added to your project Hexcel.WTS.Test\Hexcel.WTS.Test.csproj. This could have been caused if you were offline. 
Please verify the following list of packages needed by your project's code and manually add the missing packages: 

Install-Package -Id Microsoft.Extensions.Hosting -Version 3.1.1
Install-Package -Id MahApps.Metro -Version 2.0.0-alpha0660_

Trying to use the PMC to install the packages give

PM> Install-Package -Id Microsoft.Extensions.Hosting -Version 3.1.1
Install-Package : Object reference not set to an instance of an object.
At line:1 char:1
+ Install-Package -Id Microsoft.Extensions.Hosting -Version 3.1.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], NullReferenceException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

The solution is to close and reopen the solution.  Then add the first package with the nuget package UI not the console.  After that the additional packages can be added with the console.

**Comment by sibille** [comment]
Hi @PhilPJL, 
this is one of the known issue of having two versions of WTS installed side by side in the same Visual Studio Instance. 

You can workaround this by installing WTS on different VS instances (for example VS 2019 and VS 2019 preview) or temporarily disabling one of the extensions in the extension managers:

![image](https://user-images.githubusercontent.com/24698018/77301233-9c17a400-6cef-11ea-9365-a528b5eee66a.png)

**Comment by PhilPJL** [comment]
Ok thanks that fixed it.
