### ISSUE TITLE
Design time theme

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/WindowsTemplateStudio#3601]
Theming is broken at design time

VS 2019 16.5.0
```
<xml
    xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio">
    <genTemplate:Metadata>
        <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
        <genTemplate:Item Name="wizardVersion" Version="v0.21.20083.1" />
        <genTemplate:Item Name="templatesVersion" Version="v0.21.20084.1" />
        <genTemplate:Item Name="projectType" Value="SplitView" />
        <genTemplate:Item Name="framework" Value="Prism" />
        <genTemplate:Item Name="platform" Value="Wpf" />
    </genTemplate:Metadata>
</xml>
```

Create a new app.  Generated views in the designer are mostly dark/black.

e.g.
![image](https://user-images.githubusercontent.com/271656/77437705-df9c0c00-6ddc-11ea-94b9-7d5e726cac25.png)

Can we configure an explicit theme dark/light at design time?

**Comment by sibille** [comment]
Thanks for reporting!

**Comment by sibille** [comment]
There was a style missing in the Prism templates.
We also switched the dark and light theme in the Apps RessourceDictionary so you see the Light Theme by default. If you prefer to see the dark theme at design time you can just switch them back.

Verified in dev-nightly: 
Templates version: 0.21.20111.1
Wizard version: 0.21.20110.1
