### ISSUE TITLE
WPF Page: DataGrid

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3606]
Add a **DataGrid** page template for **WPF**.

Action Plan:
- [x] Create mockups
- [x] Product team validation
- [x] Create templates
- [x] Add docs

You can find the mockups at https://github.com/mvegaca/WpfDataGrid
This page contains a basic datagrid showing data from the SampleData Service.

![image](https://user-images.githubusercontent.com/24698018/88778365-bb847900-d188-11ea-90ae-eda92aa69a6c.png)

**Comment by sibille** [comment]
Additions to SampleDataService should be done using Global Postactions, to avoid conflicts when adding pages using right click.
Same applies to MasterDetail Page and Content Grid Page.
![image](https://user-images.githubusercontent.com/24698018/92362084-bef81200-f0ef-11ea-9262-2baef7d8d6f2.png)

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20252.1
Wizard version: 0.22.20251.1
