### ISSUE TITLE
WPF Page: ContentGrid

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3607]
Add a **ContentGrid** page template for **WPF**.

Action Plan:

 - [x] Create mockups
 - [x] Product team validation
 - [x] Create templates
 - [x] Add docs

You can find the mockups at https://github.com/mvegaca/ContentGridMockup.
This page contains a basic content grid based on a list view. Selecting an item shows a detail page.
Items rearrange when resizing the window but there's no adaptative behaviour or connected animations like in the UWP Content Grid Page.

![image](https://user-images.githubusercontent.com/24698018/85841574-98883300-b79e-11ea-84e4-337786a8b319.png)
![image](https://user-images.githubusercontent.com/24698018/85841616-a6d64f00-b79e-11ea-9728-3274ea87e8ca.png)

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.20252.1
Wizard version: 0.22.20251.1
