### ISSUE TITLE
WPF Navigation

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3621]
**Is your feature request related to a problem? Please describe.**
After creating the WPF app with basic MVVM I found out I cant figure out how to correctly navigate between pages. I searched all available documentation and tryied to reverse engineer it but I still have no idea how it works.

**Describe the solution you'd like**
I have no idea what I am doing wrong, so either a few words in documentation on how to navigate between pages, or a simpler way to do it.

**Additional context**
I am a newbie when it comes to XAML but I did a lot of android development and I would appreciate something like androidx navigator approach.

**Comment by Luk164** [comment]
Ok I figured out you are not supposed to use NavigationService from page but use dependency injection to get navigationService and then pass fullName of viewModel, not page.

**Comment by sibille** [comment]
@Luk164, thanks for reporting! We'll include this in our MVVMBasic docs.
