### ISSUE TITLE
WPF Page with XAML Island

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3624]
Add a WPF Page with a Xaml island. 
The Xaml Island should contain a user control with a two-way binding to a property in the page's viewmodel. Colors should be synced from WPF App to Xaml Island. 

Action Plan:

- [x] Create mockups
- [x] Product team validation
- [x] Create templates
- [x] Template Metadata (Texts and Icon)
- [x] Add codebind templates for XAML Island
- [x] Verify if .NET Core runtime 3.1.7 is installed
- [x] Add docs

**Comment by mvegaca** [comment]
This is the Xaml Island [mockup repository](https://github.com/mvegaca/xamlislandsample) with a first approach to create a new Xaml Island page template.

**Comment by sibille** [comment]
Confirmed: Xaml Island needs .NET Core 3.1.7 installed to work correctly. 
Working on adding this check and a notification if it's not installed to the XAML Island page.
Idea is to convert the tag wts.requiredSdks that we use to check for Windows SDKs into something more generic like wts.requiredVersions and use it to check for required SDKs and .NET Core runtime. This will also be helpfull for checking Node/Python version in WebTS (https://github.com/microsoft/WebTemplateStudio/issues/1487)

**Comment by sibille** [comment]
Issues found: 
- Add WTS TODO on XAMLIslandControlUniversal
- Localized files should not contain empty strings (either english or translated files)

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.22.20267.2
Wizard version: 0.22.20267.2
