### ISSUE TITLE
WPF ApplicationInfoService fails during debug (GetVersion exception)

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3630]
**Describe the bug**
GetVersion tries to get the app version from manifest, which is not available during debugging and thus fails to run.

**To Reproduce**
1. Make a new project using WPF
2. Add settings
3. Build and launch
4. Navigate to settings

**Expected behavior**
Some sort of backup version or debug mode message shows

**Additional context**
I am not using the latest template but from what I have seen this has not been addressed yet.
I am currently using this ugly workaround:
```
public Version GetVersion()
        {
            try
            {
                //// MSIX distribuition
                //// Setup the App Version in Archivator_desktop_WPF_WTS.Packaging > Package.appxmanifest > Packaging > PackageVersion
                var version = Package.Current.Id.Version;
                return new Version(version.Major, version.Minor, version.Build, version.Revision);
            }
            catch (Exception)
            {
                //Console.WriteLine("Debug mode detected!");
                return new Version(6, 6, 6);
            }
        }
```

Also, is there a way to make an auto-incrementing version?

**System**

- **VS Version: 16.5.2** 
- **WinTS Wizard Version:0.21.20097.1 (nightly)** 
- **WinTS Template Version: unknown, whatever is the default for this nightly version** 
- **Windows Build:18363**

**Comment by sibille** [comment]
Hi @Luk164, did you add a MSIX project? In this case you should set the MSIX project as Startup Project when debugging, Will create an issue to set MSIX as Startup project on project creation if it is available.

**Comment by Luk164** [comment]
Thank, you, but is there any way to make this work even if the MSIX is not set as startup? If nothing else the build would be faster. Maybe something like I did, but prettier?

**Comment by sibille** [comment]
There actually is: Found the [OSVersionHelper](https://github.com/novotnyllc/OSVersionHelper) which allows you to check if the app is packaged or not.
 ```
public Version GetVersion()
{
    if (OSVersionHelper.WindowsVersionHelper.HasPackageIdentity)
    {
        var version = Package.Current.Id.Version;
        return new Version(version.Major, version.Minor, version.Build, version.Revision);
    }
    else
    {
        var v = Assembly.GetExecutingAssembly().GetName().Version;
        return new Version(v.Major, v.Minor, v.Build, v.Revision);
    }
}
```

**Comment by Luk164** [comment]
A truly elegant solution! Can this be added to template?

**Comment by sibille** [comment]
Yep! Agree we should add this

**Comment by mvegaca** [comment]
Added to templates #3634

**Comment by sibille** [comment]
Verified on dev-nightly;
Templates version: 0.21.20121.1
Wizard version: 0.21.20121.1
