### ISSUE TITLE
WPF strings/Resources.resx is not set as default resource file

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3632]
**Describe the bug**
Visual Studio does not pick up strings/Resources.resx as a default resource file, requesting a new one to be created instead

**To Reproduce**
1. Create new WPF project
2. Go to properties of main project
3. Select Resources on the left hand panel

**Expected behavior**
Resources.resx is picked up as a default resource file immidiately after project generation.

**Additional context**
This is only a minor inconvenience, but it is still annoying because I do not know how to set it manually.

**System**

- **VS Version:4.8.03752** 
- **WinTS Wizard Version:0.21.20112.1** 
- **WinTS Template Version:Unknown** 
- **Windows Build:18363**

**Comment by sibille** [comment]
Great catch, wasn't aware of that setting!

**Comment by Luk164** [comment]
@sibille No worries, I really like the idea of this project, so I am trying to help any way I can.

**Comment by sibille** [comment]
Verified on dev-nightly;
Templates version: 0.21.20121.1
Wizard version: 0.21.20121.1
