### ISSUE TITLE
WPF install [Nightly]

### ISSUE THREAD

**Issue by paeded** [microsoft/WindowsTemplateStudio#3635]
Error: **the specified key was
not specified in the dictionary**

The error came when I create a new project and want to start the Wizard

**Comment by sibille** [comment]
@paeded, thanks for reporting!
Could you add more detailed reproduction steps and information on what VS version you are using?
Do you have the release version installed on the same Visual Studio Instance? 
We've seen issues in this scenario (https://github.com/microsoft/WindowsTemplateStudio#known-issues). You can workaround by installing the different versions of WTS on different VS instances (f.ex VS 2019 and VS 2019 Preview) or temporarily disabling the extension you are not working with.

**Comment by paeded** [comment]
Hey my Vs Version 16.5.4

**Comment by paeded** [comment]
It's the normal release Version

**Comment by sibille** [comment]
Updated my VS Version, but cannot reproduce the problem. This is happening when you try to create a New WPF Project with Windows Template Studio (dev-nightly version), correct? Is this happening before the Wizard is shown or once you hit Create?
Or is this an issue with the generated project?

**Comment by paeded** [comment]
Correct, it's shown before the wizard opens

**Comment by sibille** [comment]
Which version of WTS are you using and do you have other versions of WTS installed?

**Comment by paeded** [comment]
![image](https://user-images.githubusercontent.com/53492623/80367605-b2cf8e80-888b-11ea-9e65-867f45f21708.png)

**Comment by paeded** [comment]
I found the error.
My Language was German I changed it to English then it works

**Comment by sibille** [comment]
Awesome! Changed my language to german and can reproduce this now!
Working on a fix!

**Comment by sibille** [comment]
Verified in dev-nightly:
Vorlagenversion: 0.21.20121.1
Assistenten-Version: 0.21.20121.1
