### ISSUE TITLE
UWP WPF Add Entity Framework Core

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3639]
**Is your feature request related to a problem? Please describe.**
I found it complicated to add Entity Framework Core to WPF and I was unable to add it to UWP.

**Describe the solution you'd like**
Add EFC to features that can be added to the template. If possible with support for multiple providers and including a no-setup internal database, with ConnectionString and provider choice integrated into settings screen.

**Additional context**
I know this is a big feature but I think it would be seriously helpful. It is the same thing I am currently working on in my project and its incredibly hard to do it right. Many apps need to work with a Db so why not give it to them all already set up?

**Comment by Luk164** [comment]
Update: There currently seems to be quite a lot of problems with EF Core and UWP cooperation. Does anyone have a working example I could use? Thank you

**Comment by sibille** [comment]
Closing as dup of #3176
