### ISSUE TITLE
Hamburger menu generated by template does not match typical UWP style.

### ISSUE THREAD

**Issue by geometrikal** [Microsoft/WindowsTemplateStudio#364]
- Row height is not 48 x 48
- Animation is wrong

For the row height etc, the following works ok, but not sure how to change the animation.

    <Button
                Margin="0"
                Padding="0,0"
                HorizontalAlignment="Stretch"
                HorizontalContentAlignment="Stretch"
                AutomationProperties.AccessibilityView="Control"
                AutomationProperties.LandmarkType="Navigation"
                AutomationProperties.Name="{x:Bind Label}"
                Background="Transparent"
                BorderThickness="0"
                Click="NavigationButton_Click">
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="48"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="48" />
                        <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>
                    <Rectangle
                        Width="6"
                        Height="36"
                        HorizontalAlignment="Left"
                        VerticalAlignment="Center"
                        Fill="{ThemeResource SystemControlForegroundAccentBrush}"
                        Visibility="{x:Bind SelectedVis, Mode=OneWay}" />
                    <FontIcon
                        HorizontalAlignment="Center"
                        VerticalAlignment="Center"
                        FontSize="16"
                        Foreground="{x:Bind SelectedForeground, Mode=OneWay}"
                        Glyph="{x:Bind SymbolAsChar}" />
                    <TextBlock
                        Grid.Column="1"
                        Margin="0,0,24,0"
                        VerticalAlignment="Center"
                        Foreground="{x:Bind SelectedForeground, Mode=OneWay}"
                        Text="{x:Bind Label}"
                        TextTrimming="CharacterEllipsis" />
                </Grid>
            </Button>

**Comment by mrlacey** [comment]
For note, differences are:
- Removed button padding
- Set Grid row height = 48
- Set Rectangle height = 36
- Set Rectangle alignment = Center

**Comment by mrlacey** [comment]
Please note that the ShellPage will use the HamburgerMenu from the community toolkit in a forthcoming update and addresses most of these already.
The only thing it doesn't do is the rectangle size change. @geometrikal what's your source for the rectangle height change

**Comment by mrlacey** [comment]
@geometrikal what's wrong with the animation?

**Comment by geometrikal** [comment]
@mrlacey The rectangle height was a guess based on the rectangles in the Windows Settings app. The animation is the [pointer down animation](https://docs.microsoft.com/en-us/windows/uwp/style/motion-pointer) (shrink and tilt) which I don't see in a typical hamburger menu. Cool that it will integrate with Community Toolkit, looking forward to the update!

**Comment by mrlacey** [comment]
Reopening as even with the community toolkit HamburgerMenu we still need to set the rectangle size correctly.
The rectangle should be 4 wide and 24 high (centered vertically) to match built-in system apps.

I can make the change but holding off until the June branch is brought into dev or otherwise refactored.

The animation in the current version is because the items are using a button to work around a previous issue with keyboard activation that is not present in the toolkit control.

**Comment by geometrikal** [comment]
@mrlacey I just did a quick tour of current MS apps... Some have a full high rectangle, some smaller height, some none. Some have a button animation, some the icon and text have the button animation, some no animation. Maybe just make it look as much like the new NavigationView as possible?

**Comment by mrlacey** [comment]
@geometrikal which apps did you test? which versions of those apps? and on which version of Windows? That there are differences isn't as useful as knowing where those differences are.

**Comment by mrlacey** [comment]
According to the "official" guide from earlier this year, the rectangle should be 4 wide and 24 high (centered vertically)
Will update to this.
Will also revisit when we update to the NavigationView control in the FCU. (#308)

**Comment by mrlacey** [comment]
I've now got the latest FCU official guide for sizes and spacing and so will update to that shortly.

**Comment by mrlacey** [comment]
I now have all the spacing, sizing, and behavior in [the branch Issue364-NavMenuStyling](https://github.com/Microsoft/WindowsTemplateStudio/tree/Issue364-NavMenuStyling).

Much of the styling is to reverse the behavior change from [this commit in the toolkit](https://github.com/Microsoft/UWPCommunityToolkit/commit/e261664fed5d441618b84d05e200e3ce2f0190e3#diff-ec353bd0ed9375d55f33140404f9969f) to what is defined for FCU. That is, items at the bottom (options/secondary) do not scroll and are fixed to the bottom of the screen.

The only thing it doesn't yet have, and which is needed, is the correct focus visuals. They're proving a bit tricky, so if anyone wants to help.....

**Comment by mrlacey** [comment]
Correct/desired focused visuals are defined in https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/navigationview#how-to-use-navigationview under the "Visual Style" section and copied below

![navview_item-states 1](https://user-images.githubusercontent.com/189547/27014238-adb225ba-4eec-11e7-81d8-ee896c3de17a.png)

**Comment by mrlacey** [comment]
merged 7 days ago but still not in the dev-nightly build 😕 
Tested with 0.14.17171.65003

**Comment by crutkas** [comment]
i just ran the nightly and it was in CB.  i see it in 
W - 17171.65003 
T - 17171.5

**Comment by mrlacey** [comment]
Rerunning again this morning and now I do see the changes. 
Expect that I had a cached older version of the templates somewhere. Not sure how that should be the case after updating the installer though. :(

**Comment by ralarcon** [comment]
@mrlacey this happen because the templates are downloaded in background and are not refreshed until next time you open the wizard. 

For the v1.2 we have a better mechanism in place, where you will see when you have updates (currently implemented in the Issue267-RightClick branch).

I have opened the issue #487 to track and improve the experience when you download a new version.

**Comment by ralarcon** [comment]
Closing this issue now as it is solve and verified.

**Comment by mrlacey** [comment]
So the delay when starting the wizard while it claims to be updating templates doesn't actually let you use the ones you have to wait for it to download.? Sound like the worst way of doing things.
