### ISSUE TITLE
Update WebApi Template to .NET Core 3.1

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3642]
Update WebAPI templates to .NET Core 3.1 which is the recomended LTS version.

**Comment by sibille** [comment]
Mockup for WebApi using .NET Core 3.1 [SampleWebApiApp.zip](https://github.com/microsoft/WindowsTemplateStudio/files/4593666/SampleWebApiApp.zip)

**Comment by mrlacey** [comment]
Notes.

The sample is based on a UWP app with Left Navigation Menu (SplitView) and **Code Behind** for the MVVM Framework.

It includes the single additional **Service** of **WebAPI** (and the dependencies that are automatically included.)

There are no other pages, features, or tests added.

---

Changes identified in the sample:

- Project targeting 3.1 (as per the issue title)
- ASPNetCore no longer needed as a NuGet package
- An updated version of Swagger referenced.
- Changes in `Program` (mostly trivial but a method renamed)
- Changes in `Startup` reflecting changes in the underlying platform version.
- Changes in `appsettings.json` reflecting what's needed by the 

I like that it sets multiple start-up projects ;)

---

Suggestion~s~:

- Add the comment `// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.` above `Startup.Configure()` just like in projects created with File > New Project > ASPNet app > Web API

---

Question~s~:

- Is documentation that explains how to update previously generated apps (services/API projects) planned?

**Comment by sibille** [comment]
Good point, will include your suggestion and apply the changes in a separate repo instead of the zip. There are detailed update guides at:
- https://docs.microsoft.com/es-es/aspnet/core/migration/21-to-22  
- https://docs.microsoft.com/es-es/aspnet/core/migration/22-to-30 
- https://docs.microsoft.com/es-es/aspnet/core/migration/30-to-31

so I don't think we need a separate one.

**Comment by sibille** [comment]
Included the proposed change by @mrlacey in mockup at https://github.com/sibille/SampleWebApiApp

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.20156.1
Wizard version: 0.22.20155.1
