### ISSUE TITLE
Have Navigation Pane on Left But Collapsed.

### ISSUE THREAD

**Issue by keithnicholson** [microsoft/WindowsTemplateStudio#3644]
**Describe the bug**
Unable to Have NavigationView Collapsed By Default for DisplayMode Left

**To Reproduce**
1. Create NavigationView (Left) 
Pane project in any platform (I'm using MVVMLight) with any number of pages
2. Go to ShellPage.xaml
3. Find the NavigationView  control at winui:NavigationView and include IsPaneOpen="False" as attribute.
4.  Run the app.
5.  It stays expanded.

**Expected behavior**
With the default being DisplayMode = Left and using IsPaneOpen="False" it should be collapsed.

**Additional context**
I have downloaded the Repo and I have tried to see where this occurs.  The Navigational Sample gave me an idea, but it is a different implementation and brought the code in but something external, according to the stack, sets it back to IsPaneOpen="True".

Let me know if this is not enough info.

**System**

- VS 2019 16.5+
- WTS Version 3.5.19310.1
- Windows 10 Build 1909

**Comment by sibille** [comment]
Thanks for reporting @keithnicholson! This seems to be an issue in the NavView Control from WinUI. There is nothing in our Templates that sets the PaneDisplayMode back to true, and I could reproduce in a Blank UWP App without using Windows Template Studio. 

Opened an issue on the WinUI repo so this can be fixed there.

**Comment by keithnicholson** [comment]
Glad to help and thank you for reporting to the WinUI team.  Here is a link if anyone follows this.  https://github.com/microsoft/microsoft-ui-xaml/issues/2391.

**Comment by keithnicholson** [comment]
I was able to work around it by adding to the the WTS' ShellViewModel's OnLoaded method.   

```
private async void OnLoaded()
        {
            _navigationView.IsPaneOpen = false;

```

**Comment by mrlacey** [comment]
Just tidying up and believe this can be closed. Please reopen if needed.
