### ISSUE TITLE
It seems that it is not possible to add BackgroundTask after the project is created

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3645]
**Describe the bug**
I am unable to add background task to my existing WTS project.

**To Reproduce**
1. Create a simple WTS project, with NavigationView, MVVM Basic and a Blank Page
2. Right click project->WTS->new feature
3. Option to include background task is not shown

**Expected behavior**
Option to include background task should be shown

**System**
- **VS Version:** 16.5.4
- **WinTS Wizard Version:** 3.5.19310.1
- **WinTS Template Version:** 3.5.19310.1
- **Windows Build:**1803

**Comment by sibille** [comment]
BackgroundTask is not available for right click addition as it is not compatible with the MultiInstance. 
To workaround you can create a new project and copy the background task code

**Comment by harvinders** [comment]
Thanks @sibille
