### ISSUE TITLE
Make WPF Application Host public access +  changes in app initialization

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3651]
To avoid breaking change when we will work on Background Task and Xaml Island features we should make the App.xaml.cs application host as a public property.

```csharp
private IHost _host;
public IHost ApplicationHost { get; private set; }
```

**Comment by sibille** [comment]
Exposing Services and StartAsync should be sufficient.

**Comment by mvegaca** [comment]
We are working on ToastNotification #3614 Mockups and we think we should add some updates in WPF templates to improve app code infrastructure and avoid future breaking change with templates that handles different ways to handle the app activation.


## MVVM Basic

### App.xaml.cs
  - Add GetService
  - ConfigureAppConfiguration method with { } instead of inline method to allow composition

### ApplicationHostService.cs
  - Add HandleActivationAsync method

## MVVM Light
### ApplicationHostService.cs
  - HandleActivationAsync method

## All Frameworks
  - Rename AppConfig from _config to _appConfig
  - MSIX add empty <Extensions></Extensions> entry in manifest file.

**Comment by sibille** [comment]
Verified in dev-nightly; 
Templates version: 0.22.20161.1
Wizard version: 0.22.20161.1
