### ISSUE TITLE
WPF mahApps update breaks templates

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3659]
**Describe the bug**
A new pre-release of mahApps library that is used in WPF templates no longer allows static access to some functions like `ThemeManager.DetectTheme(Application.Current)`, which breaks the templates. https://github.com/MahApps/MahApps.Metro

**To Reproduce**
1. Generate new project
2. Update to latest mahApps library version (v2.0.0-alpha0775)
3. Check ThemeSelectorService

**Additional context**
I know this is a pre-release, but I think it is safe to assume these functions are not coming back later.

**Comment by Luk164** [comment]
Nevermind, looks like I jumpled to conclusion. https://github.com/MahApps/MahApps.Metro/issues/3779

**Comment by Luk164** [comment]
Version 2.0.0 stable has just been released and it still breaks the template, it looks like in order to upgrade to stable version some changes will have to be made.

**Comment by sibille** [comment]
Hi @Luk164, we updated the ThemeSelectorService in PR https://github.com/microsoft/WindowsTemplateStudio/pull/3650/files. 
Have you tried with the latest dev-nightly version?

**Comment by Luk164** [comment]
> Hi @Luk164, we updated the ThemeSelectorService in PR https://github.com/microsoft/WindowsTemplateStudio/pull/3650/files.
> Have you tried with the latest dev-nightly version?

Yeah, fixed already, I downloaded the latest template and manually updated the code. BTW is there any way to update the template in an already started project?

**Comment by sibille** [comment]
You can add new pages/features to your project using the projects context menu. But updating the rest of the code, as for example an existing ThemeSelectorService would be very difficult as we don't know what you might have changed. WTS is about getting you bootstrapped, after that the project is yours :)

For breaking changes we do docs on how to adjust your project.

**Comment by Luk164** [comment]
@sibille Thought that would be the case, just wanted to make sure. It is still a tremendous help. The only thing I had a problem with was I had to use WPF because I could not get UWP to work with EF Core no matter what I tried.

**Comment by sibille** [comment]
Closing this as the initial issue is solved and a separate issue for EF support has been raised.

**Comment by Luk164** [comment]
@sibille Can I get a link to the issue, please? Thanks

**Comment by sibille** [comment]
Sure, was refering to this one: https://github.com/microsoft/WindowsTemplateStudio/issues/3639
