### ISSUE TITLE
Why aren't updates, releases and milestones in sync?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#366]
On May 17th version "1.0.17137.1" of the extension was released to the public gallery.
Much of what was in this version was in the milestone '[1.01 - Critical Bug Fixes](https://github.com/Microsoft/WindowsTemplateStudio/milestone/6)' but that milestone still contains open items and more items have been added to this milestone since "1.0.17137.1" was made public.

Why isn't "1.0.17137.1" included in the list of [Releases](https://github.com/Microsoft/WindowsTemplateStudio/releases)?

Is "1.0.17137.1" considered v1.01? If not, what is it? and what will be in the *"official"* v1.01? If it is v1.01 then can the milestone be updated/split/renamed as appropriate?

This seeming lack of discipline, consistency, and structure around the planning and release process makes it hard to know what was included in specific releases that have happened and what is intended to be included in upcoming releases.

**Comment by crutkas** [comment]
Yes Matt, you are correct, right now i'm focused on getting critical bugs fixed.  100% we should rev to 1.01 and i should have updated the master branch with the release
