### ISSUE TITLE
WPF Automatic culture setting

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3667]
**Is your feature request related to a problem? Please describe.**
I found that there is an easy way to automatically set culture for an entire solution based on the system settings.

**Describe the solution you'd like**
The only thing that needs to be added is this piece of code to OnStartup function:

```
//Sets culture in the entire app depending on system settings automatically
            Thread.CurrentThread.CurrentCulture = CultureInfo.CurrentCulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.CurrentCulture;
            FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(
                XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.Name)));
```

**Additional context**
I already created a pull request that does this. This is my first time ever creating one so please excuse any errors I may have made.

**Comment by mrlacey** [comment]
The app should get the system culture by default have you got issues and scenarios where that isn't the case?

Here you're overriding the default UI culture? Why?
What about people who deliberately have the UI as a different culture?

**Comment by Luk164** [comment]
> The app should get the system culture by default have you got issues and scenarios where that isn't the case?
> 
> Here you're overriding the default UI culture? Why?
> What about people who deliberately have the UI as a different culture?

Maybe it could be made into an opt-in feature, but in my case I have a slovak set in OS and I got american system by default. This simply makes it so your OS culture is the default instead of the US one.

**Comment by mrlacey** [comment]
@Luk164 Please can you explain (or provide) a quick way to recreate something that displays the initial problem and show how your change addresses it.

**Comment by Luk164** [comment]
> @Luk164 Please can you explain (or provide) a quick way to recreate something that displays the initial problem and show how your change addresses it.

Simple enough. Create a new WPF template, add a textblock to a page and bind content to a DateTime object. Now even if your culture is set to something different it will be formatted in the US style, m/d/yyyy and 12h time. Using this piece of code on start should apply your culture settings to everything, so for me it will look like d/m/yyyy and 24h time. Date and time is only one of many small cultural differences, others relate to using "," or "." for decimal numbers etc. etc.

**Comment by mrlacey** [comment]
There are two things going on here.

**1.**

For reasons I'm not 100% certain of, there are two regional settings in Windows.

**Settings > Time & Language > Language > Windows display language**
![i3367-language](https://user-images.githubusercontent.com/189547/82258580-fd579e80-9951-11ea-88f4-5bcfaa2f6a95.png)

**Settings > Time & Language > Region > Region format**
![i3667-region](https://user-images.githubusercontent.com/189547/82258585-ffb9f880-9951-11ea-8ebd-b1562a313d5b.png)

The language setting controls the default culture for `CultueInfo.CurrentUICulture`.
The region setting controls the default culture for `CultureInfo.CurrentCulture`.

@Luk164 check these settings on your machine and see if that reflects what you're seeing.


**2.**

The second issue is that Framework elements default to using a default region of "en-US" and as this is used as the culture for binding and formatting (& the default for converters) in XAML, this will mean you may end up with formatting that is not what you expect based on machine settings.

There's an open [issue that relates to this on the WPF GitHub repo that I have added to](https://github.com/dotnet/wpf/issues/1946#issuecomment-630428646).

I'm going to continue to investigate and escalate this through some other channels to see if I can find out more.

- - - - - 

In your proposed fix, you're changing three things

1. Making the (main) thread culture be the "CurrentCulture" - which it should be by default making this unnecessary.
2. Making the (main) thread UI culture be the "CurrentCulture" - this may lead to confusion in some circumstances as it might not be what some people expect as the "region" setting is used where the "language" setting should be.
3. Changing the default framework element culture to be the "CurrentCulture" - this works around issue 2 above but I believe it is more correct to use "CurrentUICulture" for this though.

Making these changes may solve the specific issues you are seeing with specific settings on some machines but they are not a universal solution that should be applied to all projects. 
Even making them an optional selection in the wizard will be hard to do in a way that is easy to explain and justify.

Let me continue to investigate and we'll come to a recommended solution that can be applied everywhere.

**Comment by Luk164** [comment]
@mrlacey Sure, I admit I am new to this and your input is much appreciated. I simply found an issue with a pretty simple fix and thought it might be useful to others too. Please do update me if you find a better solution.

**Comment by miloush** [comment]
@Luk164 @mrlacey There is actually more settings than these two but the above are the most relevant. The display language corresponds to `CurrentUICulture` and is intended for localization, most notably loading resources in different languages. The regional format corresponds to `CurrentCulture` and is intended for internationalization, most notably formatting numbers and dates.

You might be interested in [Why we have both CurrentCulture and CurrentUICulture](http://archives.miloush.net/michkap/archive/2007/01/11/1449754.html) for why there are two things going on.

As @mrlacey pointed out, you should definitely not set one to the other if your aim is honoring user preference, set `Thread.CurrentThread.CurrentUICulture` to `CultureInfo.CurrentUICulture` instead.

Also note that `XmlLanguage.GetLanguage` throws when you are using custom cultures.

The referenced issue in WPF shows that the proposed solution is not enough to have formatting the way user has set it, but that is a WPF issue.

**Comment by mrlacey** [comment]
The .NET Framework version of WPF also displays the same behavior.
Despite there being the open issue about this on the WPF repo (for .NET Core) I don't expect them to make a change there as it's potentially a breaking change to the behavior of existing apps.


The issue appears to simply be that there is a bad default for the language of WPF `FrameworkElement`s.

I think it is worth including a line in the app initialization to set the default FrameworkElement LanguageProperty to be the system configured region (CurrentCulture). (This would mean that any formatting done in XAML would default to the system configured region, rather than en-US. This is the "correct" behavior for an internationalized app.)
An explanatory comment should also explain why the line of code is there. Something like:

```
// Ensure that formatting and other internationalization done in XAML defaults to the
 system configured region settings.
```

---

Note also that this doesn't affect UWP as that uses the CurrentCulture (rather than "en-us") by default.

**Comment by miloush** [comment]
As I suggested above, that is not always possible, as some of the cultures are not supported by the `LanguageProperty`. My first proposed solution in the referenced issue would fix both that and this issue though, i.e. allowing to override a `CultureInfo` instance rather than a language tag.

**Comment by mrlacey** [comment]
Yes, as per [this comment](https://github.com/dotnet/wpf/issues/1946#issuecomment-534564980) a more complex solution may be needed.
I don't know how to verify this is correct for all scenarios though.

**Comment by sibille** [comment]
There is no recommended way to work around this issue, but we still think we should call it out to the devs, so they can do what works best for their app.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20182.2
Wizard version: 0.22.20179.1
