### ISSUE TITLE
In Known Issues year is mentioned wrongly  

### ISSUE THREAD

**Issue by harisjayadev** [Microsoft/WindowsTemplateStudio#367]
Only compatible with Windows 10. You cannot use this if running **VS 2107** on an older Operating System. #357

**Comment by crutkas** [comment]
Issue #357 calls that out.  you need both VS 2017 15.2+ and Win10 14393 or better w/ 15086 SDK installed

**Comment by crutkas** [comment]
Thanks for filing the bug, any feedback / suggestions is fully welcome
