### ISSUE TITLE
Help Needed: How to create a WPF App 

### ISSUE THREAD

**Issue by msavazzi** [microsoft/WindowsTemplateStudio#3674]
I feel very dummy but I do see the WTS only for UWP not for WPF.
I even updated it to 3.6.x version but it does only generate UWP.
Also the menu WTS Wizard in Solution Explorer is not visible for me on WPF

Can you help me?

**Comment by mrlacey** [comment]
From the main [readme](https://github.com/Microsoft/WindowsTemplateStudio/#windows-template-studio)

❗ WPF Templates are still in development and will be available from version 3.7 onwards. You can get a preview using our dev-nightly version. Find more instructions on installing the dev-nightly at https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio ❗

**Comment by msavazzi** [comment]
Heem... when I read it 2 hours ago was: from version 3.6 onward

no problem :) happy that the solution is soo simple and I've not messed up
