### ISSUE TITLE
Unable to create project after upgrade to 3.6

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsTemplateStudio#3681]
**Describe the bug**
I am stuck at 
![image](https://user-images.githubusercontent.com/8557046/82554588-9502fa00-9ba9-11ea-8091-56d0c94ad5d1.png)

The main project and the core projects are created, but not the sln

I had to also upgrade the visual studio 2019 to 16.6 and added the Windows 10 (2004 ) SDK. I am on 1803 though.

Is 1803 a factor? Is there a way to go back to 3.5?

**Comment by sibille** [comment]
We support current and previous windows version, which are 2004 and 1909.
Not sure if there is a way to download an earlier version of the vsix, will find out and come back to you.
To unblock you meanwhile: Have you tried to add the projects to an empty solution?

**Comment by sibille** [comment]
Hi @havinders, I didn't find a way to get older versions from the marketplace but uploaded the 3.5 version to the release assets (https://github.com/microsoft/WindowsTemplateStudio/releases/download/3.5.19310.01/Microsoft.Templates.vsix).
As you already had installed version 3.6 you'll need to delete the templates + cache from 
- %userprofile%\.templateengine\Pro.Uwp.CS
- %userprofile%\.templateengine\Pro.Uwp.VB
- %userprofile%\AppData\Local\WinTS\Templates\Pro

Also make sure to uncheck the "Automatically update this extension" in Visual Studio.
