### ISSUE TITLE
Include the VSIX in the release

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3682]
Following on from #3681 

Future releases should include a copy of the vsix so that it is possible to test and, if necessary, reinstall old versions.

**Comment by mrlacey** [comment]
Actually, just thought. Even if had the old VSIX, wouldn't it still auto-update to the newer templates?
If older installers were available, there would be no way to force them to still use older templates.

**Comment by sibille** [comment]
No, templates are not shared among version 3.5 and 3.6. On package creation there is a possibility to define which wizard the package is valid for. We don't share templates among mayor/minor version updates.

**Comment by sibille** [comment]
I've attached the last few vsix's to the releases.
