### ISSUE TITLE
WPF Default page setting (minor)

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3683]
**Describe the bug**
In ApplicationHostService in function StartAsync there is a setting for default page of application. I would appreciate some sort of a comment to make it easier to find.

**Expected behavior**
At least a todo flag for setting the default page.

**Comment by sibille** [comment]
Good point, it's not a todo really, as the startup page is set to the first page you selected in the wizard, but adding a comment is a good idea!

**Comment by Luk164** [comment]
> Good point, it's not a todo really, as the startup page is set to the first page you selected in the wizard, but adding a comment is a good idea!

I only suggested using a todo because they get marked, so it would be easier to find.

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20175.1
Wizard version: 0.22.20174.3
