### ISSUE TITLE
Dev-nightly: WPF projects should not show Add Services option

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3691]
1. Create a new WPF project
2. Choose "Windows Template Studio (dev-nightly)" option from the context menu
3. "Add services" option should not be shown as there are no services available.

WPF projects should not show Add Services option as there are no templates that are available for right click in services currently.

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20160.1
Wizard version: 0.22.20160.1
