### ISSUE TITLE
ToastNotification fails on right click using Prism

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3697]
**Describe the bug**
ToastNotification fails on right click using Prism. Failed merge postaction.

**To Reproduce**
1. Create an app with Prism and forced login.
2. Add ToastNotification using right click

**Screenshots**

![image](https://user-images.githubusercontent.com/5556784/83537518-ef2e8400-a4f4-11ea-9b16-5d4f418d0a9b.png)

**System**
Templates version: 0.22.20154.1
Wizard version: 0.22.20154.1

**Comment by sibille** [comment]
Problem is that the line            
` await Task.CompletedTask;`
was removed when adding the ThemeSelectorService. 

Same happens for Azure and Dev-Center Notifications + UserActivity.

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20160.1
Wizard version: 0.22.20160.1
