### ISSUE TITLE
Update all projects to target framework 4.7.2

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3701]
Microsoft.VisualStudio.SDK metapackage required updating UI and Installer to targetframework 4.7.2.
The following projects are still using targetframework 4.7:
- Localization
- TemplateValidator
- WtsPackagingTool
- Microsoft.Templates.Fakes
- Utilities.Test
- Utilities 

We should update all projects to use targetframework 4.7.2

**Comment by mvegaca** [comment]
Verified in Dev
