### ISSUE TITLE
MahApps packages updated to 2.0.1

### ISSUE THREAD

**Issue by OzBob** [microsoft/WindowsTemplateStudio#3708]
Update templates to use latest non-alpha MahApps package
https://github.com/MahApps/MahApps.Metro/releases
latest is v2.0.1
nuget also published v2.0.1
https://www.nuget.org/packages/MahApps.Metro/

**Comment by sibille** [comment]
Updating to the latest version right now!

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20160.1
Wizard version: 0.22.20160.1

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20171.1
Wizard version: 0.22.20168.1
