### ISSUE TITLE
Add a global exception handler for UWP applications

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3709]
We should add a global exception handler for UWP applications to avoid an app crash on unhandled exceptions.

```

private void App_UnhandledException(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e)
{
  // TODO WTS: Please log and handle the exception as appropriate to your scenario
  // For more info see https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.unhandledexception
       
}
```

**Comment by mrlacey** [comment]
I'm shocked we don't have this already.

---

I'm not in favor of including `e.Handled = true;` as a comment in this method.
I've seen many developers set this as a shortcut to avoid the app crashing but without handling the actual conditions that caused the error.
I consider it an anti-pattern that should not be encouraged.
The negative consequence of this is that the app is left in an unknown state that is more likely to have other issues/errors which then become harder to identify and resolve. The overall quality of the app is lowered for the sake of misleading developers into thinking they've prevented the app from crashing.


The comment would also be better as:

> // TODO WTS: Please **log and** handle the exception as appropriate to your scenario

This is to encourage developers to consider how they should be recording details of the exception, not just "handling" it.

**Comment by jamesmcroft** [comment]
Going off the points @mrlacey made, would it just make sense to include a simple file logging option? 

A while back I put together just this for one of my app component libraries - 

https://github.com/MADE-Apps/MADE-App-Components/blob/master/MADE.App.Diagnostics/AppDiagnostics.cs

**Comment by sibille** [comment]
I thought we had this, but couldn't find it going through the code, 
Agree on not setting the e.Handled = true and changing the comment. I've updated the initial issue.

@jamesmcroft, we talked a while ago about adding a default logging or exception handling system, the problem we saw back then is that there are a bunch of them.

**Comment by mrlacey** [comment]
> @jamesmcroft, we talked a while ago about adding a default logging or exception handling system, the problem we saw back then is that there are a bunch of them.

The conclusion I remember coming to was that we added the AppCenter Analytics feature which gave an official, supported, Microsoft-provided way of doing this and didn't rely on adding more code to the generated project that would need to be supported.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20167.1
Wizard version: 0.22.20164.1
