### ISSUE TITLE
VB Support

### ISSUE THREAD

**Issue by Nukepayload2** [Microsoft/WindowsTemplateStudio#371]
Please add VB support! 
We really need a tool that can help us create VB and UWP projects easier.

**Comment by mrlacey** [comment]
@Nukepayload2 thanks for the suggestion. Unfortunately, because this would mean doubling the effort around building and testing templates this is unlikely to happen unless *A LOT* of people ask for it or someone volunteers to do it.
Will leave this open to group/track other people wanting this too.

**Comment by crutkas** [comment]
@Nukepayload2 would this be something you may want to help lead?

**Comment by Nukepayload2** [comment]
@crutkas I'll try to port C# templates to VB when I'm free.

**Comment by Afanyiyu** [comment]
Come and support this,,,

**Comment by c00012** [comment]
please support c++!

**Comment by crutkas** [comment]
@Afanyiyu is this something you would like to help contribute back?

**Comment by crutkas** [comment]
One idea, can this and C++ be transcoded to have the support added in from our c# templates?

**Comment by mrlacey** [comment]
@crutkas, in theory, we could compile the app to IL and then decompile to VB.Net or C++ but that wouldn't help with the structure we have for templates and placeholders or post action files. Might be a good starting point though.

**Comment by graymatter00** [comment]
Yes!  VB support would be great.

**Comment by hannespreishuber** [comment]
this more a VB tool than C#

**Comment by mrlacey** [comment]
@hannespreishuber can you expand on that?

**Comment by mrlacey** [comment]
There is now an ***experimental*** branch with VB support at https://github.com/Microsoft/WindowsTemplateStudio/tree/VisualBasic
Please note this is ***not*** a guarantee that VB support is coming soon, more an exploration of what is involved in making it happen.
As such, this branch only supports a blank project, template, code behind, and a blank page. (The absolute minimum to generate a project.)

Important points of note from this experiment.
- The impact on testing is big! Running 298 tests (all of them) takes over an hour on my machine. If we had all C# templates for VB as well, it'll go over two hours!
- Tests can no longer run in parallel. Most of the tests we have are more of integration than strict unit tests and interact with the file system to analyze and iterate over the templates available. It's not possible to extract the templates for both language versions of tests into the same folder at the same time.
- Much work can (and should) be done to improve the isolation of tests and the dependencies between static objects in the code. This will improve maintainability and make it easier to isolate code for easier testing.

Before this can go live:
- There is still more integration and engine development work to be done before it's usable.
- It puts both the C# and VB templates in the same installer. Do we want that? (I think we do but best to check.)
- We'd need more support from people writing VB to develop and create new templates. Any volunteers?
- How to share code (mostly XAML files) that are used by both languages? We might need to think how files are shared so we don't have duplicate, identical XAML files for the CS and VB folders. Is it Ok if the VB config files link to CS ones? Should they be in a central location shared by both languages? Or something else?
- We need to establish clear naming principles for folder structures. Take the image below
-- Should we add language identifiers to all existing folders?
-- Where should the identifier go?
-- I propose adding the language identifier to every folder and having the identifier at the very end. (Not what's shown in the image.) So we'd end up with `ProjectCS` and `ProjectVB`, `Project.SplitViewCS` and `Project.SplitViewVB`, etc. Any objections?

![composition template naming](https://user-images.githubusercontent.com/189547/27196458-6c8b2e60-5202-11e7-9ff2-42760182c152.png)

**Comment by mrlacey** [comment]
On folder naming structure, moving forward with VB related folders ending with "VB" and no suffix for CS folders to ease backward compatibility.

**Comment by crutkas** [comment]
i'm fine with that but how much code reuse is possible on the xaml?

**Comment by mrlacey** [comment]
reuse **ALL** the XAML  
well that's what I'm aiming for and see no reason why it shouldn't be possible

**Comment by crutkas** [comment]
We are reusing or referencing?  Based on that file path feels copying code vs linking.  No matter what we need to adjust the structure for xaml / shared files, no?

**Comment by crutkas** [comment]
I am thinking also icons, do we need to rethink docs, readme, the descriptions?

**Comment by mrlacey** [comment]
Because of the way template files (& folders) are copied and filtered it's not possible to have the VB folders point to files in the CS folders so I wrote a script that will update the ones in VB folders from the CS ones.  It's XAML only while I test its effectiveness but know I need to add other file types there too. (*.png, *.md, *.resw)

**Comment by mrlacey** [comment]
Sync script now updated: https://github.com/Microsoft/WindowsTemplateStudio/blob/VisualBasic/SynchronizeFilesUsedByVisualBasicTemplates.ps1

I chose to go this route (copying files rather than redesigning the whole way templates are structured) because:
- It doesn't affect what already exists (so no confusion for people already using the codebase & templates, plus no merge issues.)
- It leaves both language versions with all the files they need together. (Template composition is already quite complicated, to suddenly move half the files to new folders--making twice as many templates are needed or extra file copy steps--would, I expect, be unnecessarily complicated)
- I always expect C# to be the primary development language and get new functionality first.
- There should be no need to create something that is for VB only.

_As a general rule, when I'm trying to make the code do something that wasn't considered in the original code design (e.g. multiple languages, or tests that use extra templates to add testing functionality) I'm trying to modify what exists as little as possible, rather than rebuild everything in the way that is best/simplest for what we want now. If we reach a period of stability then such redesign work can be done but to do it now will slow development down considerably and might still leave issues when we need more functionality in the future. (i.e. multiple big restructurings might be needed, with all the risks they contain.)_

**Comment by mrlacey** [comment]
Notes on VB development now in the wiki: https://github.com/Microsoft/WindowsTemplateStudio/wiki/Visual-Basic

**Comment by mrlacey** [comment]
**Progress update on VB support.**
The core work to enable generating projects in VB has now been done as part of PR #864

The work to add all the necessary templates is being tracked via issue #863 and there is additional information on the [VB page of the wiki](https://github.com/Microsoft/WindowsTemplateStudio/wiki/Visual-Basic).

The intention is that this will be included in the v1.4 release.

**Comment by mrlacey** [comment]
adjusted milestone to help set expectations

**Comment by Nukepayload2** [comment]
I'm translating existing features and pages at https://github.com/Nukepayload2/WindowsTemplateStudio .
Copy codes or merge changes if they are appropriate.

**Comment by mrlacey** [comment]
@Nukepayload2 Thanks. There's some useful stuff there for the code conversions but there are issues with template config and lots of failing tests.
Feel free to raise PRs against https://github.com/Microsoft/WindowsTemplateStudio/tree/Issue863-VBTemplates

**Comment by ralarcon** [comment]
Can we close this issue in favor of #863?

**Comment by crutkas** [comment]
No.  They are different items. This is the master item.

**Comment by mrlacey** [comment]
This is the master item for tracking the work necessary to add VB support.
To see all related items that need to be done see [here](https://github.com/Microsoft/WindowsTemplateStudio/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3AVB%20milestone%3A1.5).

**Comment by mrlacey** [comment]
VB.Net support is now available in the nightly builds.
If you use VB.Net your assistance in verifying what they produce will be greatly appreciated.
Instructions on installing the nightly build version of the templates can be found [here](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio).
Please [raise issues](https://github.com/Microsoft/WindowsTemplateStudio/issues/new) for anything you find that is wrong, broken, or could be improved and tag them [VB](https://github.com/Microsoft/WindowsTemplateStudio/issues?q=is%3Aissue+is%3Aopen+label%3AVB).

**Comment by mrlacey** [comment]
I think we're almost there. There is still more automated testing to add and I'll continue to port new C# pages/features and improvements but VB support is ready for your feedback.
You can see the tool in action if you have the dev-nightly build installed ([https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio)) or run from source on the dev branch.
Alternatively, you can look at examples of generated projects at https://github.com/mrlacey/wts-vb-demos
There are nine projects, one for each combination of supported framework (code-behind, MVVM Basic, & MVVMLight) and project structure (blank, pivot & tabs, & Navigation Menu). Each project also includes an instance of all pages and feature options that are available.

@Nukepayload2 @Afanyiyu @graymatter00 @hannespreishuber & anyone else, I'd love if you could take a look and let us know what you think. Any and all feedback appreciated, no matter how big or small.

**Comment by crutkas** [comment]
AWESOME!!!!

**Comment by aarondglover** [comment]
THANKYOU! Can't wait to test with VB!

**Comment by crutkas** [comment]
@aarondglover you can test right now!  Follow @mrlacey instructions to install the dev nightly!

**Comment by mrlacey** [comment]
Changing tags as I think it's now all there.
continuing with final verification testing prior to release at the end of the month.

**Comment by mrlacey** [comment]
I'm continuing to test this functionality (both manually and with new automated tests) but I think it's good to go.
