### ISSUE TITLE
support with fluent design

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#372]
the new fluent design system introduced in insider preview windows SDK as showed in BUILD 2017 should be included in the template, with navigation control as  "navigation view" control as it is present in latest preview SDK.

**Comment by mrlacey** [comment]
@touseefbsb it will be. At the moment we're not building templates that target the preview SDK but will in time. 
Your request is quite generic. Do you have any specific requests?
We already have an issue tracking changing to the new NavigationView at #308 
There's also #306 too.

**Comment by touseefbsb** [comment]
yeah I mainly wanted the navigation view to follow fluent design. but all other features of fluent design in general would be great. but yeah if you will support that after official release of the SDK that is perfect, looking forward to it :) @mrlacey

**Comment by crutkas** [comment]
@touseefbsb we just got out of a meeting with the Fluent, XAML, and Composition teams.  We're going to see how we can enable this direct while providing the support for the current release.  Once we're on 15086 as our min target, we can do some more clever things.

**Comment by touseefbsb** [comment]
yeah that right you guyx need to support all targets from 15086 upto 16190 ( preview sdk ) the code must be somehow adaptive already in the template to switch to page with splitview ( if user has window 10 older builds ) otherwise switch to fluent design system if user has creators fall update

**Comment by crutkas** [comment]
I'm going to break this apart into the work back items we've identified.  (https://github.com/Microsoft/WindowsTemplateStudio/wiki/Fluent

**Comment by crutkas** [comment]
we have a branch for this.

**Comment by ralarcon** [comment]
I think we can close this in favor of small issues we currently have:
* Master-Detail fluent improvements are being replaced by the ImageGallery. We are reviewing the redlines and implementation for master-detail to be aligned with design requirements.
* WebView improvements are ready.
* Hamburguer menu needs (acrylic and so on) are pending. I would suggest to open a different issue for it.

**Comment by ralarcon** [comment]
Closing as it is now we are ready for FCU and there are other issues tracking the details.
