### ISSUE TITLE
Back camera is rotated - and it should not be 

### ISSUE THREAD

**Issue by tesar-tech** [microsoft/WindowsTemplateStudio#3733]
**Describe the bug**
Camera rotation is wrong when using Back camera. It's caused by these two lines of code:
https://github.com/microsoft/WindowsTemplateStudio/blob/a7bbe6d3a6534749d8be3e68c45a23ec65f24a61/templates/Uwp/_comp/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs#L118

When deleting these lines, everything work as expected.

**To Reproduce**
1. Create fresh project with Camera page
2. Run on tablet and press button to switch camera
3. Preview and recorded video is rotated.

**Expected behavior**
Video should not be rotated when using back camera

**System**

- **VS Version:2019** 
- **WinTS Wizard Version:** 
- **WinTS Template Version:** 
- **Windows Build:**

**Comment by sibille** [comment]
Thanks for reporting!

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.20175.1
Wizard version: 0.22.20175.1
