### ISSUE TITLE
Add postaction to unset "Deploy" in Configuration Manager

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3740]
This is needed for XamlIsland page (#3624) as we should never deploy the UWP App that gets added.

**Comment by sibille** [comment]
This needs https://github.com/microsoft/CoreTemplateStudio/issues/247

**Comment by sibille** [comment]
The following postaction configuration can be used to configure a project to not be deployed from it's template:

```
{
  "description": "Unset deploy of XamlIslandAppProj",
  "manualInstructions": [ ],
  "actionId": "F74F9FBA-D4F5-494E-970E-D99DF5E3F4F3",
  "args": {
    "projectName": "Param_ProjectName.XamlIslandApp\\Param_ProjectName.XamlIslandApp.csproj",
    "deploy": "false"
   },
   "continueOnError": true
}

```

**Comment by mrlacey** [comment]
Are all the available/custom postactions documented anywhere?

**Comment by sibille** [comment]
Yes, you can find an overview here: https://github.com/microsoft/CoreTemplateStudio/blob/dev/docs/templates.md#post-actions.


A sample for usage of template defined postactions can be found as a comment in the code (f.ex. https://github.com/microsoft/CoreTemplateStudio/blob/release/code/src/CoreTemplateStudio/CoreTemplateStudio.Core/PostActions/Catalog/AddProjectConfigurationToContextPostaction.cs)

**Comment by mvegaca** [comment]
Postaction added to Xaml Island Template and [PR created](https://github.com/microsoft/WindowsTemplateStudio/pull/3790)

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20266.1
Wizard version: 0.22.20266.1
