### ISSUE TITLE
Add two instances of each template that is multiInstance to stylecop tests

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3742]
Follow up work from #3704. Stylecop tests should add two instances of templates that allow multi-instance, to ensure generated code is still valid and correctly formatted.

**Comment by mrlacey** [comment]
Is it necessary to test adding both a single instance of a template and multiple (two) copies?
I don't think there's a scenario where having one instance might pass, but two will fail (or vice versa) but wanted someone else to have thought about this too.

**Comment by sibille** [comment]
we have the one by one tests that are run on a weekly basis that cover the case of a single page being added on each projecttype/framework. This occasionally fails if usings/nuget packages are not added correctly from the package.

**Comment by sibille** [comment]
As this has some impact on test duration (aprox 2 min per framework) and we have two sets of stylecop tests (Group1 and Group2), I've added two instances only on G2 (which includes BackgroundTask which is multiinstance) tests

**Comment by sibille** [comment]
Verified in dev
