### ISSUE TITLE
Set dpiAware to true/PM 

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3751]
Setting dpiAware to true/PM as this is required for XamlIsland + also will bring per monitor dpi awareness for windows 8.1

https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiaware
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-2

**Comment by mrlacey** [comment]
> also will bring per monitor dpi awareness for windows 8.1

Is Windows 8.1 a supported target? If so, for how long will this be?
How is testing on Windows 8.1 being performed?

**Comment by sibille** [comment]
It's not an officially supported target as we don't test on Windows8.1, the dpiaware = true/PM is needed for adding xamlislands.

**Comment by mrlacey** [comment]
> It's not an officially supported target as we don't test on Windows8.1, the dpiaware = true/PM is needed for adding xamlislands.

Thanks for clarifying. The original post listed Windows 8.1 support as a benefit for doing this and so I wasn't clear.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.20181.1
Wizard version: 0.22.20179.1
