### ISSUE TITLE
WPF templates are not visible after the installation of .net 5 prevew 5

### ISSUE THREAD

**Issue by lishu** [microsoft/WindowsTemplateStudio#3752]
**Describe the bug**
Everything's fine after the first installation， but WPF templates are not visible after the installation of .net 5 prevew 5, I've tried uninstall .net 5, but there's still only a template for the UWP version(Has try Reinstall extension and restart OS)

**To Reproduce**
1. Install .net 5 preview 5 SDK after installing this template

**Expected behavior**
New Project Dialog will not found 'WPF' Window Template Studio, only 'UWP' Window Template Studio.

**Screenshots**
![TemplateStudioLossWPFTemplate](https://user-images.githubusercontent.com/1331008/85399315-31ddfc00-b589-11ea-97bc-f6db0dcb7222.png)

**System**

- **VS Version:** 16.6.2
- **WinTS Wizard Version:** 3.6.20139.1
- **WinTS Template Version:** -
- **Windows Build:** 19041.329

**Comment by lishu** [comment]
The following actions have been tried but have not resolved the problem:
- Reset All VS Setthings
- `devenv /installvstemplates`

**Comment by sibille** [comment]
@lishu, WPF project creation will be added in version 3.7. You can get a preview using our dev-nightly version. Find more instructions on installing the dev-nightly at https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio

**Comment by lishu** [comment]
Thanks, Seems rather strange why I first did not install from the market
