### ISSUE TITLE
Microsoft.Toolkit.Mvvm to replace MVVMBasic& MVVMLight templates 

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3753]
With the Windows Community Toolkit looking to take over from MVVM Light (which has ceased active development) and release a replacement, adopting support for this should be considered.

It would depend on the toolkit version getting to a full release version (AFAIK this will be in v7.0, but there's no timeline for this yet) but it might be worth starting to think about this now.

This is a tracking issue as much as anything and opened to keep track of any discussion on the subject.

Some questions that will (eventually) need answering

- Does this mean MVVMBasic (MB) can be "retired"? It was originally created, at least in part, due to a lack of a Microsoft supported framework being available. When there's one in the toolkit this argument goes away.
- Should Microsoft.Toolkit.Mvvm (MTM) be added as a new framework option? Or as a replacement for MVVMLight (ML)? If not a replacement, how long should MVVMLight be maintained?
- If a replacement, can support for "right-click>add" be maintained for existing apps using MB or ML?
- If a replacement, would a document on migrating be enough? Or is tooling going to be required?

Note. Replacing MB & ML with MTM would greatly ease the development and testing effort required in template development.

I would expect this to necessitate a major version change. As such, it may be worth doing this at the same time as other big changes. (.NET 5/WinUI3--perhaps?)

X-Ref: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3230

**Comment by mrlacey** [comment]
Looks like we may also need to consider CaliburnMicro in relation to this also.... https://github.com/Caliburn-Micro/Caliburn.Micro/issues/708

**Comment by michael-hawker** [comment]
Thanks @mrlacey for filing this issue. We've definitely been talking to @sibille about this path forward as well. We didn't want to ship a new MVVM framework in the Toolkit and not have the WTS on board as well.

Especially now that [Caliburn.Micro has announced development stopping as well](https://caliburnmicro.com/announcements/), this new MVVM package would probably replace all three of those in WTS, so the options would be 'None', 'WCT MVVM', and 'Prism'?

Happy to sync more as we finalize the PR, move to create documentation/samples, and get a more official/stable preview out in the coming weeks. I have a couple of final loose ends to tie-up next week before we official green-light and move forward, but the positive responses from the community have been very encouraging towards this path.

**Comment by michael-hawker** [comment]
Also, it's good to note that the new WCT MVVM package is .NET Standard based, so using it and supporting it with other directions for WTS in the future like WPF, Xamarin, and WinUI 3 should be relatively straight-forward and simplified. 🙂

**Comment by Sergio0694** [comment]
Hey @mrlacey - thank you for following up on this and creating this issue! 😄

I'm super excited for the response so far and the feedback from the early testers, so really looking forward to seeing how this moves forwards! I've already prepared a draft of the docs, and I'll be happy to get a docs PR started in the near future as well so that it might also be useful to clear things up for people interested in the PR and coming from other frameworks (eg. `MvvmLight` as you mentioned). Glad to hear the Windows Template Studio team is looking at the new project! 🚀

**Comment by sibille** [comment]
Great questions and discussion @mrlacey, @michael-hawker and @Sergio0694

Yes, our idea is to replace MVVMBasic and MVVMLight with the new WCT MVVM framework. 

Regarding the best way to update existing apps, I think we should evaluate how big the change is (considering also the changes WinUI3 will bring) and decide based on that, what's the best way to move support an update.
Bundling the big changes together in a mayor release seems a good way to reduce update effort. 

Would also love to hear from devs currently using MVVMLight + MVVMBasic what their plans and needs are.  

If CaliburnMicro is no longer maintained we should also remove it as an option, I believe an update path is more complicated in this case, as the frameworks are quite different.

**Comment by scottkuhl** [comment]
I like the direction this going. MVVM Light and Caliburn have seemed to be on life support lately. I agree that's its best to remove them. I try to use Template Studio and students that wander down those paths often get frustrated. I always steer them to Code Behind or MVVM Basic.

Now that Studio has added WPF support, anything that can reduce the maintenance effort is a good step.

**Comment by scottkuhl** [comment]
> so the options would be 'None', 'WCT MVVM', and 'Prism'?
> 

I thought Prism had effectively dropped support of UWP in the past. Is it even a viable option moving forward?

**Comment by mrlacey** [comment]
> > so the options would be 'None', 'WCT MVVM', and 'Prism'?
> 
> I thought Prism had effectively dropped support of UWP in the past. Is it even a viable option moving forward?

Uno are aiming to support Prism on WinUI so it might not be dead https://platform.uno/blog/uwp-winui-and-uno-platform-get-prism-support-thanks-to-uno-team-oss-contribution/

**Comment by michael-hawker** [comment]
@scottkuhl thanks for the input, that's really encouraging to hear and part of our reasoning on having a new light-weight MVVM package in the Windows Community Toolkit.

The great part too is since it'll be .NET Standard base with Windows Template Studio also supporting WPF now; they can just as easily have the same option there as well! 🙂

We'll hopefully be releasing a preview package on NuGet in a few weeks and have better samples and docs ready at that time. Hoping to get the PR merged in within the next week and then it'll be available on our MyGet for easier pre-preview consumption. 😋

**Comment by mrlacey** [comment]
I'm working on adding these as an extra framework option for review/testing.
My expectation is that we'll have (at least on the nightly builds) the new option along with existing ones for some time.

How existing frameworks will be retired is yet to be determined.

**Comment by mrlacey** [comment]
When any existing frameworks are eventually removed it will be worth creating a follow-up task to tidy-up and simplify the templates and remove some of the current complexity.

**Comment by mrlacey** [comment]
To document current thinking:

- We'll add the Microsoft.Toolkit.MVVM (MTM) version once it is out of preview. This is due to be in the Community Toolkit v7.0 and has no scheduled release date yet.
- The MTM version will become the default option in the wizard (UWP & WPF)
- When the MTM templates are released the MVVMBasic (MB), MVVM Light (ML), and Caliburn.Micro (CM) templates will be marked as deprecated.
- Deprecated templates will still be available in the wizard for (probably, at least) six months
- During the deprecation period, documentation will be provided (and linked from the wizard) that explains: why the deprecation notice, how to migrate to MTM, and what will happen after the deprecation period.
- After the deprecation period the MB, ML & CM templates will be removed from the wizard (and repository)
- A "best-effort" will be made to allow existing apps to use the right-click>Add functionality after the deprecation period but ongoing support is not guaranteed. (The amount of work needed to support this is still to be reviewed)
- Whether the WinUI3 versions of templates include support for deprecated frameworks will depend on when the MTM and WinUI3 templates are available.
- Currently, the expectation is that Prism templates will be included in the future. This is based on the current understanding that Uno will be supporting the UWP version. This will continue to be monitored and appropriate action will be taken if that's not the case.
- Code-Behind templates are not affected by this change (other than no longer being the UWP default.)

**Comment by yoshiask** [comment]
I have to say, I just recently started using WTS, and this is one of the things that would make it perfect for me. (The other big thing being Uno support, but I know how much effort that would take.) Is this template going to be released as soon as WCT 7.0 does? Will it take some time after the release for it to be useable in WTS?

**Comment by mrlacey** [comment]
> I have to say, I just recently started using WTS, and this is one of the things that would make it perfect for me. (The other big thing being Uno support, but I know how much effort that would take.) Is this template going to be released as soon as WCT 7.0 does? Will it take some time after the release for it to be useable in WTS?

The exact timeline for releasing this is still to be determined.
It won't get an official release until WCT7.0 is out of preview.
However, it may go into the nightly build of WinTS before then.

**Comment by mrlacey** [comment]
Docs for migrating existing apps built with MVVM Basic to use MVVM Toolkit can be found at https://github.com/windows-toolkit/MVVM-Samples/blob/master/docs/mvvm/MigratingFromMvvmBasic.md.
These will eventually be published on docs.microsoft once the toolkit is out of preview.

**Comment by mrlacey** [comment]
This will go into nightly builds shortly.
Expect the release in whatever comes after 3.9 (don't yet know if this will be 3.10 or 4.0)

**Comment by mvegaca** [comment]
WinUI3 Templates updated to MVVM Toolkit to Preview 4 in PR #3960

**Comment by michael-hawker** [comment]
Wanted to give folks a heads up, we had some people reach out to us after our .NET Conf talk. Seems like some community members are trying to work to keeping Caliburn.Micro alive as called out on the previously linked thread: https://github.com/Caliburn-Micro/Caliburn.Micro/issues/708.

Not sure how that effects plans or if you want to spin that part out as a separate issue. I think the original discussion around the MVVM Toolkit replacing both MVVM Basic and MVVM Light at least is still solid.

**Comment by michael-hawker** [comment]
See issues have been filed for tracking 7.0.0-preview5 #4104 and #4067 which we shipped last week.

We'll be hoping to ship our final bits next week, so we don't expect any changes to the MVVM bits outside of if we identify any other bug or XML doc fixes before release.

**Comment by mrlacey** [comment]
I believe the only thing preventing this from being ready for release is updating the documentation accordingly. 
I'll raise a separate issue for this.
