### ISSUE TITLE
Set WPF MinWidth and MinHeight to ShellWindow

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3757]
We should add MinWidth and MinHeight to ShellWindow in WPF Apps, I suggest to set **MinWidth="500" MinHeight="350"** to get the same UWP minimum aspect ratio.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.20181.1
Wizard version: 0.22.20179.1
