### ISSUE TITLE
Change design-time theme for UWP

### ISSUE THREAD

**Issue by Luk164** [microsoft/WindowsTemplateStudio#3765]
**Describe the bug**
I have started a new project using UWP. I am having trouble finding a way to switch design-time theme to dark, the only thing that works is RequestTheme="Dark", but that just locks the page into that theme.

**To Reproduce**
1. Create a new UWP project
2. Open xaml designer

**Expected behavior**
A well documented way of changing the design-time theme in the WTS documentation and possible a todo mark in relevant part of code.

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/85954655-5e26bd80-b979-11ea-85e7-3ce810c1a737.png)

**Additional context**
This problem does not seem to affect WPF, at least my project switched to darkmode without me having to do anything about it, though I do not know how.

**System**

- **VS Version:16.6.2** 
- **WinTS Wizard Version:0.22.20179.1** 
- **WinTS Template Version:???** 
- **Windows Build:
![image](https://user-images.githubusercontent.com/30559213/85954752-f1f88980-b979-11ea-8d9d-25ef2dae55fb.png)
**

**Comment by mrlacey** [comment]
Visual Studio only gained the ability to set design-time specific settings for UWP apps in [version 16.7 Preview 3](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.7.0-pre-3.0) but that was only released 5 days ago.
Until this feature is out of preview and in a release version of Visual Studio that is the minimal supported version by WinTS, it is not possible for this to be used in the generated templates or it will produce output that does not compile for older versions of VS.

Regarding:
> Expected behavior
A well documented way of changing the design-time theme in the WTS documentation and possible a todo mark in relevant part of code.

This is such new functionality (it only just came to the preview channel) that there is no official documentation for this yet, but I'm sure it will come in time.
I am not convinced pointing to this is appropriate for a "TODO" comment in the generated templates. This isn't something that a developer has to do. I understand that WinTS is useful for developers getting started but this isn't a reason to point to documentation of general topics/concepts.

**Comment by Luk164** [comment]
@mrlacey I was not aware of that. I thought it was simmilar to setting design time width and such, so thats why I asked for a todo to be placed where this had to be set. For now I will just have to use RequireTheme I guess, and delete it b4 release.

**Comment by Luk164** [comment]
I have somehow managed to switch my design-time theme to dark without requiretheme, but I have no idea how. Can someone check it out and help me? Thx

[My repo](https://github.com/Luk164/Archivator_desktop_WPF)

**Comment by mrlacey** [comment]
> I have somehow managed to switch my design-time theme to dark without requiretheme, but I have no idea how. Can someone check it out and help me? Thx
> 
> [My repo](https://github.com/Luk164/Archivator_desktop_WPF)

I took a quick look and can't see anything.
Could it be the default settings on your machine that are being picked up?

**Comment by Luk164** [comment]
@mrlacey I do not think so. A fresh project does not do that. I would not that it first happened when I started using blend.

**Comment by Luk164** [comment]
@mrlacey Found out how to change design time theme. Works on MVVMLight WPF, no idea about the others. In app.xaml, themes are defined. The last added theme is used in design-time, so just switching the two lines changes the theme!

Dark theme in design time:

```
<ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Styles/_FontSizes.xaml" />
                <ResourceDictionary Source="/Styles/_Thickness.xaml" />
                <ResourceDictionary Source="/Styles/MetroWindow.xaml" />
                <ResourceDictionary Source="/Styles/TextBlock.xaml" />
                 <!--
                MahApps.Metro resource dictionaries.
                Learn more about using MahApps.Metro at https://mahapps.com/
                -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <!-- Accent and AppTheme setting -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Dark.Blue.xaml" />
                <ResourceDictionary Source="/Styles/Button.xaml"/>
            </ResourceDictionary.MergedDictionaries> 
```

Light theme in design time:
```
<ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Styles/_FontSizes.xaml" />
                <ResourceDictionary Source="/Styles/_Thickness.xaml" />
                <ResourceDictionary Source="/Styles/MetroWindow.xaml" />
                <ResourceDictionary Source="/Styles/TextBlock.xaml" />
                 <!--
                MahApps.Metro resource dictionaries.
                Learn more about using MahApps.Metro at https://mahapps.com/
                -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <!-- Accent and AppTheme setting -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Dark.Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />
                <ResourceDictionary Source="/Styles/Button.xaml"/>
            </ResourceDictionary.MergedDictionaries>
```

**Comment by mrlacey** [comment]
closing this as it's about how the Visual Studio XAML designer chooses which dictionary to use.

@Luk164 if you have proposals for how this could/should be changed then I recommend logging them at https://developercommunity.visualstudio.com/
