### ISSUE TITLE
Include links in block comments in ExternalLinkTests

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3769]
In the generated code most comments are done with // or '.
There are a few bigger comment block that we put between /* and */ to improve readability.
Those comments are currently not checked by the external link tests, we should include them.

**Comment by mrlacey** [comment]
There appears to be only to places where these comments are used (`Identity.cs` & `MicrosoftGraphService.cs`)
Won't it be easier just to change these instances and have a policy of not using multi-line comments? (I half remember removing all multi-line comments when this test was first added anyway.)

Also, analyzing files for such comments is further complicated as they're used extensively in composition templates. Both at headers, and inline (e.g. `        public ShellViewModel(/*{[{*/IIdentityService identityService/*}]}*/)`)

Changing the test looks like a lot more potential work than just changing two instances of usage.

**Comment by sibille** [comment]
We started using multi-line comments for better readability on long comments without getting into conflict with stylecop rules. 

If we check for lines starting with /* we should not have issues with the inline merge postactions (`e.g. public ShellViewModel(/*{[{*/IIdentityService identityService/*}]}*/`)

**Comment by sibille** [comment]
Verified in dev
