### ISSUE TITLE
Review and update wiki

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3775]
Part of our wiki documents are outdated. The goal of this issue is to review the current wiki status, agree on a global strategy for what should be in the wiki vs docs and setup an action plan to clean up the wiki.

#### Proposal for what should be in the wiki vs docs:
Most of our docs are in the [docs](https://github.com/microsoft/WindowsTemplateStudio/tree/dev/docs) folder as this allows us to have a separate set of docs for dev and release. There are a few pages in the wiki that would fit in the docs too, I think we should move them to have a single point of truth.

The wiki, to me is a good place for:
 - documentation of helper tools (localization + packaging tool) that only the core team uses
 - checklists to support work (before release/template verification)

For specs we have some specs in the wiki, others in a [specs](https://github.com/microsoft/WindowsTemplateStudio/tree/dev/specs) folder. Both approaches are valid, but we should agree on one. 
	
#### Current status of wiki and actions proposed:

|Section                                        |Status                  |Action proposed|
|:-----------------------------------|:------------------|:------------------|        
|Home                                          |Outdated            |Update after reorganizing wiki|
|3rd party libraries                       |Ok                       |Move to docs                          |
|Accessibility                                |Outdated            |Open issue for things to review + delete from wiki |
|Checklist: Before release             |Ok	                |                                                | 
|Checklist: Template verification  |Ok	
|Fluent                                         |Work done          |Delete
|How to…	                                    |Ok                       |Move to docs
|Localization                                |Outdated            |Delete
|Tidy up list                                  |Work done         |Delete
|Tools: Localization                      |Ok	
|Tools: WTS Packaging Tool         |Outdated           |Delete (this has moved to [CoreTS](https://github.com/microsoft/CoreTemplateStudio/wiki/Tools:-WTS-Packaging-Tool))
|Use of Labels                              |Outdated           |Set description on labels and delete this page
|Visual Basic                                 |Ok	
|Xamarin                                      |Outdated           |Delete
|Xamarin approach                      |Outdated           |Delete
|Xamarin Workback                     |Outdated           |Delete

**Comment by sibille** [comment]
Instead of deleting outdated info on the wiki, we'll move it to an archive section (in case we want to consult the info in the future)

**Comment by vmadurga** [comment]
Verified in current Wiki https://github.com/microsoft/WindowsTemplateStudio/wiki
