### ISSUE TITLE
Clicking on NavigationView's Settings item throws NullReferenceException

### ISSUE THREAD

**Issue by YuliKl** [microsoft/WindowsTemplateStudio#3784]
**Describe the bug**
When starting a new app, it's easy to get into a state where the app throws a NullReferenceException. The way an app developer fixes this error is not obvious to someone not familiar with NavigationView.

**To Reproduce**
1. Create a new app using WTS with Navigation Pane project type.
2. Modify the NavigationView on ShellPage.xaml to show Settings: `IsSettingsVisible="True"`
3. Run the app and click on the Settings item
4. App throws error: 
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Windows
  StackTrace:
   at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride)
   at WTSApp1.Services.NavigationService.Navigate(Type pageType, Object parameter, NavigationTransitionInfo infoOverride) in C:\Users\yulikl\source\projects\WTSApp1\WTSApp1\Services\NavigationService.cs:line 62
   at WTSApp1.Views.ShellPage.OnItemInvoked(NavigationView sender, NavigationViewItemInvokedEventArgs args) in C:\Users\yulikl\source\projects\WTSApp1\WTSApp1\Views\ShellPage.xaml.cs:line 111`

**Expected behavior**
Ideally, app navigates to a blank settings page. As an alternative, app does nothing.

**Additional context**
This seems in the broad category of issues covered by #1122

**System**

- **VS Version:** 16.4.11
- **WinTS Wizard Version:** 
- **WinTS Template Version:** 
- **Windows Build:** Insider

**Comment by sibille** [comment]
Thanks for reporting @YuliKl . Underlying issues is that the SettingPage is not available, so we cannot navigate there. 

We see two options: 
1. NavigationService checks for invalid PageType and does not navigate.
2. NavigationService checks for invalid PageType and throws a more meaningful exception.
```
if (pageType == null || !pageType.IsSubclassOf(typeof(Page)))
{
   throw new ArgumentException("Invalid pageType, please provide a valid pageType.", nameof(pageType));
}
```
From our team we prefer the second option, as this helps the Dev to detect potential issues in the app, but also see that option 1 makes the app more robust. Would love to hear your opinion.

**Comment by YuliKl** [comment]
Both options seem reasonable. I agree that option two is more informative and therefore preferable.

**Comment by sibille** [comment]
Ok, going for option 2 then.

**Comment by mrlacey** [comment]
The usefulness of the exception message would be improved if it included the [invalid] provided value of `pageType`.

The proposed suggestion is equivalent to "You've provided an invalid value."
The anticipated response to seeing such a message will be to have to go and work out what the invalid value was.
The need to have to investigate the invalid value can be avoided if the error message includes the invalid value. This saves time investigating and avoids unnecessary work.

There's a general principle for good error messages in that they should help point towards a solution, not just say that something was wrong.

**Comment by sibille** [comment]
Sounds good, we'll change the exception message to `$"Invalid pageType '{pageType}', please provide a valid pageType.`" to include this info

**Comment by mrlacey** [comment]
Do changes for this need to be made to WPF templates as well as UWP ones?

**Comment by mvegaca** [comment]
I've reviewed all Frameworks in UWP and WPF, these are the changes.

**Templates updated**
UWP
 - MVVM Basic: Added validation for invalid page type.
 - CodeBehind: Added validation for invalid page type.
 - MVVM Light: Updated validation for invalid ViewModel name.

**Templates not updated**
UWP
 - Prism uses a Private Prism Navigation System that is already handling the validation for invalid navigation parameters.
 - Caliburn uses a Private Caliburn Navigation System that does not check the invalid navigation parameters.

WPF
 - MVVM Basic is already validating invalid navigation parameters in PageService.
 - MVVM Light is already validating invalid navigation parameters in PageService.
 - Prism uses a Private Prism Navigation System that does not check the invalid navigation parameters but doesn't make app crash.

**Comment by mrlacey** [comment]
**FOLLOW UP NEEDED*

If someone gets in this position again, maybe the error message needs to point to _how to add a settings page_ to an existing app.

**Comment by mvegaca** [comment]
The problem when a Developer sets `IsSettingsVisible="True"` in **Xaml** without adding more code is that the developers needs to define what's should happen if the setting option is selected and this code is not also intuitive to write without reading de NavigationView docs.

When WTS user adds SettingsPage in the wizard we compose this code block on the `OnItemInvoked` method.
```csharp
if (args.IsSettingsInvoked)
{
    NavigationService.Navigate(typeof(SettingsPage), null, args.RecommendedNavigationTransitionInfo);
    return;
}
```

We could think on generate this IF statement if user doen't add settings page and include a comment.
```csharp
if (args.IsSettingsInvoked)
{
    // SettingsPage is invoked, handle this scenario as appropriated
    return;
}
```

I thought about this possibility before preparing the PR but add this code means add no necessary code to improve the usability of a WinUI control.

Does anyone think that we should add this code?

**Comment by mrlacey** [comment]
My preference would be to change the handler to look like this

```cs
    private void OnItemInvoked(WinUI.NavigationViewItemInvokedEventArgs args)
    {
        if (args.IsSettingsInvoked)
        {
            // Navigate to the settings page - implement as appropriate if needed
            NavigationService.Navigate(typeof(SettingsPage), null, args.RecommendedNavigationTransitionInfo);
        }
        else if (args.InvokedItemContainer is WinUI.NavigationViewItem selectedItem)
        {
            var pageType = selectedItem.GetValue(NavHelper.NavigateToProperty) as Type;
            NavigationService.Navigate(pageType, null, args.RecommendedNavigationTransitionInfo);
        }
    }
```

By default, it will include the comment `// Navigate to the settings page - implement as appropriate if needed`
When adding the Settings Page this comment will be replaced with the appropriate call to `Navigate`.


It should not include a `TODO` comment as this is not something that must be done and is optional based on the requirements for the application.


There's a potential issue from making this change as it will affect adding a settings page to a previously generated project.
To make a decision on this will depend on how common a scenario this is. [Published telemetry](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/telemetryData.md) does not include this but I assume it can be determined from what is captured.
If adding a settings page to a previously generated app is common enough to consider the consequences of introducing a breaking change, then it will be worth looking at how to make this backwards compatible.

**Comment by sibille** [comment]
From telemetry in the last month there were around 1500 settings pages created on new projects vs 30 added by right click. 

I think we should add what @mrlacey suggests as benefit for new projects is bigger than the impact on older projects. 

Also, when trying to add a settings page to an older project, the "Change summary" page will offer details on what failed and what should be added.. 

![image](https://user-images.githubusercontent.com/24698018/91969350-3efc3180-ed16-11ea-9336-2dfb0a12bf2a.png)

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.20252.1
Wizard version: 0.22.20251.1
