### ISSUE TITLE
Project templates unification to reduce code duplication

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#379]
We have unified the project templates used for SplitView, Pivot and Blank project types as the code base was exactly the same. This help to reduce the code duplication.

This change requires a modification in the templates to reflect that the same template apply to different project types as well as in the wizard code to align with the new multivalued property.

This chages will be in dev branch soon.

**Comment by ralarcon** [comment]
Marked as `version increment required` as it will require the version of templates and wizard to be incremented to works properly.

In fact this means that previous wizard versions will not be able to work with this version content. The wizard only loads content of templates which matches the Mayor.Minor version.

**Comment by ralarcon** [comment]
Now is in dev branch.

**Comment by crutkas** [comment]
we will rev to 1.1 anyways, so not a big deal.

**Comment by ralarcon** [comment]
This is working fine. Verified in nightly build 0.14.17146.65001.
