### ISSUE TITLE
Exception Messages should not be localized

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3792]
There are some Exception messages thar are localized as string resources, I think it should be placed in Code and uses localized string resources for User Interface texts.

Action Plan:
- [x] Review localized messages in UWP templates
- [x] Review localized messages in WPF templates
- [x] Add tests to ensure messages in exceptions are not localized

**Comment by mrlacey** [comment]
Examples?

WPF, UWP, or both?

**Comment by mrlacey** [comment]
I remember this coming up before (but can't find an issue -- may have been asked at a BUILD Sneak peek) and the developer consensus opinion was that exception messages shouldn't be localized.

How can rules/tests for enforcing this be added?

**Comment by sibille** [comment]
The issue was found in the NavigationService for MVVMLight in UWP, not sure if there are more places. As part of this issue we should: 
- Review localized messages in UWP and WPF templates
- Add tests to ensure all messages in exceptions are not localized

Updated first message with an ActionPlan.
