### ISSUE TITLE
issue and PR templates to include indication of related platform(s)

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3793]
Bugs are being reported and new features proposed that do not make it clear if they relate to UWP templates, WPF templates, or both.

This can easily lead to assumptions that an item/idea/issue only applies to one of the platforms when it may apply to both.
If a change is made without considering whether to look at both platforms, time can be wasted when needing to go back and look at the other platform at a later time.

Having an item in the issue/PR template that asks about the affected/used platform may also help people to think about this when making any changes.

**Comment by sibille** [comment]
Good idea! We have tags for UWP and WPF, but should also add  platform to Issue/PR templates

**Comment by mrlacey** [comment]
closing as implemented

**Comment by sibille** [comment]
Reopening as I just saw that adding the platform as checkable bullet points makes github think those are tasks and PR and issues seem to be incomplete if they only apply to one platform, as for example PR #3148 .
![image](https://user-images.githubusercontent.com/24698018/91798309-e7ca6400-ec24-11ea-90de-6af00f0e7e62.png)

We should change the template to use a table to indicate which platform is affected to avoid confusion.
