### ISSUE TITLE
Tidy up test code - magic strings

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3799]
The code in the test projects has always had less attention paid to it regarding structure and maintainability.
This is now at a point where it is hurting [my] productivity.
As a start, I'd like to remove the inconsistent use of "magic strings" to define platforms, frameworks, etc. 

objections?

**Comment by mrlacey** [comment]
The method `ShortProjectType` ([here](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/code/test/Templates.Test/BaseGenAndBuildTests.cs#L60)) is expecting there to be project types of "MenuBarWpf" and "SplitViewWpf" but the templates don't appear to use them. @mvegaca do you know if they're still needed?

**Comment by mvegaca** [comment]
Hi Matt, ShortProjectType method is used for getting a shortened url in the test generated project apps to avoid too much long path errors.
The project type "MenuBarWpf" is not currently used, we remove this terminology on platform templates split UWP/WPF.
Only Ribbon is a Project Type specific for WPF and I think it should be added as en Enum Value. I think you could remove the MenuBarWpf case sentence.
PR looks good, nice job!
