### ISSUE TITLE
Include count of pages in wizard summary

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3803]
**Is your feature request related to a problem? Please describe.**
When adding _lots_ of pages to an app it can be tricky to check that I've added the right number.

**Describe the solution you'd like**
I'd like a total count for the number of pages (and features, services, etc.) to be displayed in the wizard.

Like the red text shown in the blue circles below.

![image](https://user-images.githubusercontent.com/189547/89717641-6d554e00-d9b0-11ea-894e-659dd1a420cc.png)

For clarification: the size and color of the red text are just for visibility in this mockup. This is not the proposed style & color I'd expect in the final implementation.

**Describe alternatives you've considered**

Going through and manually double-checking is the only option at the moment.
Separate totals could be shown elsewhere but I don't know where they could go and still be equally as visible without being intrusive or separated from the items that are being totaled.

Applies to the following platforms:
- [x] UWP
- [x] WPF

**Comment by mvegaca** [comment]
I think this is easy to add in the wizard but I'm not sure if is it common in this kind of wizards, maybe we can ask to someone in the product design team.

**Comment by Luk164** [comment]
Literally a few extra lines, but while convenient, I do not really see the point. When does any app need so many pages you would not be able to just count them yourself? I would put this to backlog for now.

**Comment by mrlacey** [comment]
> Literally a few extra lines, but while convenient, I do not really see the point. When does any app need so many pages you would not be able to just count them yourself? I would put this to backlog for now.

The point is _this would help me_.
I regularly create apps with lots/all pages and it would help me double-check I haven't missed anything or accidentally included something twice.

**Comment by mvegaca** [comment]
Alright, assigned to 3.8 milestone

**Comment by sibille** [comment]
Verified in dev-nightly; 
Templates version: 0.22.20250.1
Wizard version: 0.22.20250.1
