### ISSUE TITLE
Can the 1.01 milestone be closed?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#381]
It seems everything in the [1.01 Milestone](https://github.com/Microsoft/WindowsTemplateStudio/milestone/6) has now been done.
Can it now be closed?
The dev branch was being held while work on this was done but as *a lot* has been merged into the dev branch (presumably) ready for v1.1 I'm guessing that there are no plans anything else being added to this milestone.

**Comment by ralarcon** [comment]
Yes, now is closed. Work in dev branch is now towards 1.1. If any hotfix is required, we will make a branch form master.
