### ISSUE TITLE
Proposal: C# Templates for WinUI 3

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/WindowsTemplateStudio#3810]
# Proposal: C# Templates for WinUI 3 

## Summary
The proposal is based off [this](https://github.com/microsoft/WindowsTemplateStudio/issues/3807) issue. Thanks @mvegaca  for providing the skeleton for this proposal.

In an effort to provide parity with the works in WinUI and attract more developers to both WinTS and WinUI, WinTS should provide users with WinUI 3 templates for desktop apps on release. These templates should include the most common pages and most common design patterns to get developers up and running as quickly as possible. This information can be found from the published [telemetry](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/telemetryData.md).

## Rationale

* WinUI 3 will cover the whole native Windows UI platform. Ranging from Win32 to UWP, it will enable developers to create apps with a modern UX framework.
* WinTS currently has no templating support for WinUI.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Provide an easy way for users to create a WinUI app through template studio | Must |
| Provide users with at least one design pattern as a templating option (MVVM or Code Behind) | Must |
| Have documentation for using these templates | Must |
| Identify issues with WinUI 3 during the dev process and document them on the WinUI repo | Should |
| Provide users with at least the three most common pages as templating options (Blank, Master/Detail, Settings) | Should |

## Roadmap
* Create the mockups and deploy to dev nightly
* Get feedback from community and team and add enhancements
* Create templates
* Document templates
* CI/CD integration

## Important Issues
[Master/Detail Issue with WinUI](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3433)

**Comment by Felix-Dev** [comment]
> This particular feature is to add support for desktop. I will edit the post to include that.

I'm a bit confused right now why only WinUI Desktop (Win32) is covered here and not WinUI with UWP. Why are UWP developers being left behind here?

**Comment by Luk164** [comment]
> > This particular feature is to add support for desktop. I will edit the post to include that.
> 
> @JeanRoca I'm a bit confused right now why only WinUI Desktop (Win32) is covered here and not WinUI with UWP. Why are UWP developers left behind here?

Probably because setting up win32 is harder than UWP, so it is not as pressing.

**Comment by mrlacey** [comment]
> I'm a bit confused right now why only WinUI Desktop (Win32) is covered here and not WinUI with UWP. Why are UWP developers left behind here?

WinUI for Desktop is being added first.
The migration experience for existing UWP apps makes things more complicated and so will follow in time. (I'm watching this carefully. 😉)

**Comment by Felix-Dev** [comment]
@Luk164 @mrlacey As long as there will be WTS support for WinUI 3 UWP once WInUI 3 releases **next year** (so ample time for the team here, I'd say), then I'm fine. Otherwise, I'd find it quite ironic that the "combination" of WTS (first shipped with UWP support only) and WinUI 3 (based on UWP XAML) will only be available for Win32 apps on day 1 and not UWP apps.

**Comment by Luk164** [comment]
@Felix-Dev Yeah, a bit, but it will take you 5m to add WinUI to UWP so not really an issue.

**Comment by stevenbrix** [comment]
This is fantastic, the WTS experience is much better than what is currently offered.

Will there still be the WinUI3 Project Templates VSIX? Or is that going to be removed once WTS supports WinUI3?

**Comment by JeanRoca** [comment]
> @Luk164 @mrlacey As long as there will be WTS support for WinUI 3 UWP once WinUI 3 releases **next year** (so ample time for the team here, I'd say), then I'm fine. Otherwise, I'd find it quite ironic that the "combination" of WTS (first shipped with UWP support only) and WinUI 3 (based on UWP XAML) will only be available for Win32 apps on day 1 and not UWP apps.
> 
> (And I'm not speaking about migrating existing UWP apps here but creating _new_ UWP apps with WTS using WinUI 3.)

@Felix-Dev @mrlacey Matt is correct. We are hoping to launch both approaches, migrating existing UWP and creating new UWP apps, when WinUI 3 releases. 



> This is fantastic, the WTS experience is much better than what is currently offered.
> 
> Will there still be the WinUI3 Project Templates VSIX? Or is that going to be removed once WTS supports WinUI3?

Don't know the answer to this yet, but I am glad you brought it up. It would be cool if users only had to install one VSIX!

**Comment by mrlacey** [comment]
>  It would be cool if users only had to install one VSIX!

I'm not so sure.

I'm know there are people who don't want to use Template Studio and prefer to use blank templates that are already available.

Also, if Template Studio came in the same "package" as WinUI, that wouldn't be good for Template Studio supporting platforms other than WinUI (such as WPF) as the users of that functionality might not want to install WinUI just to get Template Studio.

**Comment by Luk164** [comment]
> >  It would be cool if users only had to install one VSIX!
> 
> I'm not so sure.
> 
> I'm know there are people who don't want to use Template Studio and prefer to use blank templates that are already available.
> 
> Also, if Template Studio came in the same "package" as WinUI, that wouldn't be good for Template Studio supporting platforms other than WinUI (such as WPF) as the users of that functionality might not want to install WinUI just to get Template Studio.
> 
> There are other solutions for making installation simpler. ;)

Is it possible to bundle two separate plugins into a single package?

**Comment by mrlacey** [comment]
> Is it possible to bundle two separate plugins into a single package?

Yes.

[UWP Essentials](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.UwpEssentials) includes a number of extensions useful and relevant to anyone doing UWP development and includes Windows Template Studio.
[WinUI Essentials](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WinUI-Essentials) includes the WinUI templates and a couple of other related extensions. It will include WinTS once it has WinUI templates.

They both exist to make the process of setting up a machine for development quicker and simpler.

**Comment by Luk164** [comment]
@mrlacey Well we have our solution then - just prepare multiple packages with different combination of plugins in each. Users can then just choose which package fits them the most.

**Comment by vmadurga** [comment]
We are currently waiting for the issue https://github.com/microsoft/microsoft-ui-xaml/issues/2602 to support localized resources.

**Comment by vmadurga** [comment]
MVVMToolkit preview-3 was published last week. We should update the WinUI 3 templates.

**Comment by mrlacey** [comment]
> MVVMToolkit preview-3 was published last week. We should update the WinUI 3 templates.

FYI: https://github.com/windows-toolkit/MVVM-Samples/issues/27#issuecomment-711412769

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.22.21137.1
Wizard version: 0.22.21137.1
