### ISSUE TITLE
How to preserve refspec to patches and branches after renaming 'master' branch

### ISSUE THREAD

**Issue by Nirmal4G** [microsoft/WindowsTemplateStudio#3824]
For all those who can't pull `master`, it has renamed to `release`. #3718

To preserve refspec to patches and branches, just changing the `heads/master` to `heads/release` should work.

```diff
[remote "origin"]
	url = https://github.com/microsoft/WindowsTemplateStudio
-	fetch = +refs/heads/master:refs/remotes/origin/master
+	fetch = +refs/heads/release:refs/remotes/origin/master
	tagopt = --no-tags
[branch "master"]
	remote = origin
-	merge = refs/heads/master
+	merge = refs/heads/release
```

> Putting this out there, if anyone else facing similar issue with git.

**Comment by sibille** [comment]
Thanks for sharing @Nirmal4G. Our main branch is dev, so hope the impact is not too big.

**Comment by Nirmal4G** [comment]
I don't know why GitHub is not redirecting the renamed ref. I'm mean the support is already there in Git.

Still not much a problem, since git is a powerful tool.

**Comment by Luk164** [comment]
> I don't know why GitHub is not redirecting the renamed ref. I'm mean the support is already there in Git.
> 
> Still not much a problem, since git is a powerful tool.

It's an empty gesture in the first place, but yeah, the impact should be minimal (in every respect unfortunately).

**Comment by mrlacey** [comment]
> I don't know why GitHub is not redirecting the renamed ref. I'm mean the support is already there in Git.

FYI: There is redirect functionality on GitHub but it only applies to default branches.
