### ISSUE TITLE
WebView page changes for v1.1

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#383]
As the functionality of the WebView was changed with #216 
1. Should the version number have been increased? (How are page version numbers used?)
2. Should the author be edited to include "community contribution"?
3. Or should this be rolled back and turned into an enhancement? (#325)

**Comment by ralarcon** [comment]
We currently are not enforcing / using the version number for pages and features. It could be increased but not mandatory. This is thought for future usage if needed.

Regarding the enhancement, fist we will need to design and think the infrastructure to support the enhancements but in my opinion this is a simple "conditional" generation (feasible) that used under control can be very useful, anyway we need to gather the inputs from the user shome how and the "questions" must be defined in the template config. So this is a whole feature IMHO.

Would suggest to hold with the current infrastructure and go forward to check how many "enhancements" appear.

**Comment by mrlacey** [comment]
Gonna bump the version number but leave the author the same.
Maybe revisit this once Enhancements are more fully planned out. (X-link means we should hopefully find this when we get to that point.)
