### ISSUE TITLE
Section 508 502.3.1: (WTS/edit 'Edit page') The Name must not include the same text as the LocalizedControlType.

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3830]
The following accessibility issue needs investigation.

**App:** WTS

**Page:** New project + Right click

**Element path:** edit 'Edit page'

**Issue Details:** The Name must not include the same text as the LocalizedControlType. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property for the element that:
 · Concisely identifies the element, AND
 · Does not include the same text as the element's LocalizedControlType property.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by vmadurga** [comment]
Same as #3831

The error is produced because the item contains reserved values. In this scenario users can introduce different page names

**Comment by sibille** [comment]
Verifed in dev-nightly version:

Templates version: 0.22.20310.1
Wizard version: 0.22.20310.1
