### ISSUE TITLE
Section 508 502.3.1: (WTS/list view 'Project types list') The Name property must not include the element's control type.

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3831]
The following accessibility issue needs investigation.

**App:** WTS

**Element path:** list view 'Project types list'

**Issue Details:** The Name property must not include the element's control type. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property for the element that:
 · Concisely identifies the element, AND
 · Does not include the control type.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by vmadurga** [comment]
The error is produced when a License contains reserved values, in this case _Microsoft.Extensions.Hosting_. In this case we can ignore the error because it's a techical name.

![imagen](https://user-images.githubusercontent.com/25466105/97436939-1150f480-1923-11eb-958c-af17e9ed0c70.png)

**Comment by sibille** [comment]
Verifed in dev-nightly version:

Templates version: 0.22.20310.1
Wizard version: 0.22.20310.1
