### ISSUE TITLE
Section 508 502.3.1: (WTS/list view 'Design pattern list') The Name property must not include the element's control type.

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3833]
The following accessibility issue needs investigation.

**App:** WTS

**Element path:** list view 'Design pattern list'

**Issue Details:** The Name property must not include the element's control type. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Provide a UI Automation Name property for the element that:
 · Concisely identifies the element, AND
 · Does not include the control type.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by vmadurga** [comment]
Same as #3831

The error is produced because the item contains reserved values.

**Comment by sibille** [comment]
Verifed in dev-nightly version:

Templates version: 0.22.20310.1
Wizard version: 0.22.20310.1
