### ISSUE TITLE
Section 508 502.3.1: (WTS/edit 'Editor content') The BoundingRectangle property must represent an area of at least 25 pixels.

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3836]
The following accessibility issue needs investigation.

**App:** WTS

**Page:** Right click

**Element path:** edit 'Editor content'

**Issue Details:** The BoundingRectangle property must represent an area of at least 25 pixels. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)

**How To Fix:** Modify the BoundingRectangle property so that its width and height define an area of at least 25 pixels.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

**Comment by vmadurga** [comment]
The error occurs in the html viewer.

![imagen](https://user-images.githubusercontent.com/25466105/97435077-427bf580-1920-11eb-8527-e246e4968ceb.png)

We are currently using the external tool Monaco Editor, it looks like an external issue.
https://microsoft.github.io/monaco-editor/
https://github.com/microsoft/monaco-editor/issues?q=is%3Aissue+accessibility+label%3Aaccessibility
