### ISSUE TITLE
Section 508 502.3.1: (WTS/group '<?xml version="1.0" encoding="utf-8"?>    <root>      <!--         Microsoft ResX Schema                 Version 2.0                The primary goals of this format is to allow a simple XML format         that is mostly human readable. The generation and parsing of the         various data types are done through the TypeConverter classes         associated with the data types.                Example:                ... ado.net/XML headers 

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3837]
The following accessibility issue needs investigation.

**App:** WTS

**Page:** Right click - Changes summary

**Element path:** group '<?xml version="1.0" encoding="utf-8"?>    <root>      <!--         Microsoft ResX Schema                 Version 2.0                The primary goals of this format is to allow a simple XML format         that is mostly human readable. The generation and parsing of the         various data types are done through the TypeConverter classes         associated with the data types.                Example:                ... ado.net/XML headers

**Comment by vmadurga** [comment]
The error occurs in the html viewer, it depends on the document displayed.

We are currently using the external tool (Monaco Editor)
https://microsoft.github.io/monaco-editor/
https://github.com/microsoft/monaco-editor/issues?q=is%3Aissue+accessibility+label%3Aaccessibility
