### ISSUE TITLE
Binding failures

### ISSUE THREAD

**Issue by PhilPJL** [microsoft/WindowsTemplateStudio#3845]
**Describe the bug**
After creating a new empty project, the debugger reports a binding failure.

**To Reproduce**

create app with Project type=Navigation Pane, Pattern=Prism.  No other options selected.
debug the app
VS debugger reports multiple binding failures

![image](https://user-images.githubusercontent.com/271656/93270849-d72ff700-f7a9-11ea-9c84-35cd2ab396ee.png)

The first 3 binding failures do not appear if we include the settings page when creating the app.  Perhaps the 'OptionsItemCommand=' etc should only be emitted when the settings page is selected to be created.

The fourth failure is because this
![image](https://user-images.githubusercontent.com/271656/93271058-473e7d00-f7aa-11ea-87d2-8a409fcdd9b7.png)
is looking for elementName=hamburgerMenu.

This can be fixed by adding the appropriate element name

![image](https://user-images.githubusercontent.com/271656/93271127-6e954a00-f7aa-11ea-87e5-ddc8ae199bc4.png)

**Expected behavior**
No binding failures

Applies to the following platforms:
WPF

**System**

- **VS Version:16.8.0 preview 3
- **WinTS Wizard Version:3.7.20203.3

**Comment by mvegaca** [comment]
Thanks for reporting

**Comment by mvegaca** [comment]
We can not reproduce option items properties binding on templates current versión, I think this will be fixed on WTS 3.8

**Comment by PhilPJL** [comment]
ok I'll give it try when released.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.20265.1
Wizard version: 0.22.20265.1
