### ISSUE TITLE
Outdated links in platform-specific-recommendations.md docs

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3857]
DocsLinksAreCorrectAsync reported the following failing links:

    Some Docs links failed:
    Got a 404 when requesting 'https://docs.microsoft.com/uwp/extension-sdks/windows-desktop-extension-sdk' for '../../../../../docs\UWP\platform-specific-recommendations.md'
    Got a 404 when requesting 'https://docs.microsoft.com/uwp/extension-sdks/windows-mobile-extension-sdk' for '../../../../../docs\UWP\platform-specific-recommendations.md'
    Got a 404 when requesting 'https://docs.microsoft.com/uwp/extension-sdks/xbox-live-extensions' for '../../../../../docs\UWP\platform-specific-recommendations.md'
    Got a 404 when requesting 'https://docs.microsoft.com/uwp/extension-sdks/windows-iot-extension-sdk' for '../../../../../docs\UWP\platform-specific-recommendations.md'

I could not find direct links to the different extension sdks but this general one: 
https://docs.microsoft.com/en-us/uwp/extension-sdks/
https://docs.microsoft.com/en-us/uwp/extension-sdks/device-families-overview

**Comment by mrlacey** [comment]
on this.
The extension SDK docs were removed ~2 1/2 weeks ago as most of their functionality is now in the core SDK.

**Comment by mrlacey** [comment]
Closing as changes are now live in docs: https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/platform-specific-recommendations.md
