### ISSUE TITLE
Migrate to NetAnalyzers analyzers

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3865]
Post-build Code Analysis (FxCopCmd.exe) has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers.

**Comment by sibille** [comment]
This needs first https://github.com/microsoft/CoreTemplateStudio/issues/281.

**Comment by sibille** [comment]
Moving to 3.10 as this is still in progress. After updating to FXCop analyzers there are new rules that we need to fix.

**Comment by mrlacey** [comment]
> Moving to 3.10 as this is still in progress. After updating to FXCop analyzers there are new rules that we need to fix.

Do the new rules _all_ need to be "fixed"?

**Comment by sibille** [comment]
Our goal is to fix all warnings from recommended code analysis rules on the vsix code. 
For tests and tools we can exclude rules.

**Comment by suchja** [comment]
Does this mean all the warnings in a newly generated project from WTS will be gone? I just created a WinUI desktop app with some pages and do have 536 warnings.

**Comment by sibille** [comment]
No, this is about migrating FXCop to .NET analyzers on our vsix-code base, not on the generated code. 
But I can reproduce the huge amount of warnings on a WinUI project and we need to look at this to see how it can be fixed. 
Opening a separate issue. Thanks for reporting!

**Comment by sibille** [comment]
Verified on dev-nightly version:
Şablon sürümü: 0.22.21134.1
Sihirbaz sürümü: 0.22.21134.1
