### ISSUE TITLE
Azure Integration

### ISSUE THREAD

**Issue by brantzw** [Microsoft/WindowsTemplateStudio#387]
It would be great if the Template Studio supported bootstrapping a few Azure client integration options including Azure Functions, IoT Hub, Event Hub, and Service Bus.

**Comment by ralarcon** [comment]
Sure, definitively we will to include Azure client integration features. Are these which you consider most important / interesting? ¿Any other suggestions? 

We already have some references in the backlog: #133, #292, #297 and #387

**Comment by crutkas** [comment]
@brantzw this is pretty vague.  We have some ideas we're throwing against the wall currently but the ask needs to be much more scenario based.

Can you go into a bit more of what things you'd want out of a file->New project here as we need to do enough to be helpful but not too much were we overstep ourselves.

Also shame on me w/ #133 for vagueness :)

**Comment by crutkas** [comment]
this is too vague, closing
