### ISSUE TITLE
Template validation of RequiredSDK has the wrong error message

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3874]
From https://github.com/microsoft/WindowsTemplateStudio/blob/6c97fd5a2432658d3ac050b5545859721d00a513/code/tools/TemplateValidator/TemplateJsonVerifier.cs#L635

```cs
        private static void VerifyRequiredSdkTagValue(List<string> results)
        {
            results.Add($"The wts.order tag is no longer supported. Please use the wts.displayOrder or the wts.compositionOrder tag.");
        }
```

This message is wrong based on the method name.

Looks like a cut&paste or merge issue

**Comment by sibille** [comment]
Verified in dev
