### ISSUE TITLE
A11y_Windows Template Studio_ Services Your project Details_Keyboard: Keyboard focus is not in logical order after pressing tab key from “Design Pattern” combo box.

### ISSUE THREAD

**Issue by harshgangrade111** [microsoft/WindowsTemplateStudio#3893]
[“Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yTCS;#A11ySev2;#A11yMAS;#FocusOrder;#Benchmark;#FTP;#Keyboard;#WCAG2.4.3;#DesktopApp;#Windows Template Studio;#GH_WindowsTemplateStudio_Oct2020;#Win10;

### **Environment Details:**
Application Name: Windows Template Studio (WinTS)
Templates version: 3.8.20273.1
Wizard version: 3.8.20273.1Date: 2020-06-17T21:13:20.174Z
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 3.1
Windows Version: Windows10

### **Repro Steps:**

1.	Open Visual Studio 2019 
2.	Click on File from menu and then select new and then project
3.	Select the "Windows template studio(WPF.Net Core)".Click on next
4.	"Configure your new project" screen will appear. Click on create button.
5.	New WPF App screen will open. Navigate to "Services" in the left navigation menu and click on it.
6.	"Add Services "screen will appear. Navigate to "your Project Details" with the help of keyboard.
7.	Navigate to “Services Your Project Details” section with the help of keyboard tab .
8.	Check focus order after hit tab key from “Design Pattern” combo box.

### **Actual:**
Keyboard focus is not in logical order after hit enter from “Design Pattern” combo box. After hit tab key from “Design Pattern” combo box focus moved to Pages then again pressing tab key focus move to “Pages” combo box that is not correct focus order.
**Same issue is also observed in Scenario "Your Project Details"**.

### **Expected:**
After pressing Tab key from “Design Pattern” combo box keyboard focus should move to “Pages” combo box not on Pages section.

### **User Impact:**
Keyboard users will get confuse if keyboard focus is not in logical order.

**Comment by sibille** [comment]
Verified in dev-nightly version:
Wizard version: 0.22.20310.1

You can install the dev-nightly version from our nightly feed (https://www.myget.org/F/windows-template-studio-nightly/vsix/).
For instructions on how install WTS from the dev-nightly feed in Visual Studio see https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-instructions

**Comment by harshgangrade111** [comment]
Issue does not repro in the latest dev-nightly version. Hence closing This bug.
