### ISSUE TITLE
A11y_ Windows Template Studio_ Navigation pane details_Keyboard: Keyboard focus is not on logical order after performing action on BACK button.

### ISSUE THREAD

**Issue by Yash14j** [microsoft/WindowsTemplateStudio#3898]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) – Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yTCS;#Windows Template Studio;#GH_WindowsTemplateStudio_Oct2020;#A11y_Windows Template Studio; #DesktopApp;#Win10;#WCAG2.4.3;#NonBenchmark;#FTP;#STP;#Keyboard;#FocusOrder;#A11yMAS;#A11ySev2;

### **Environment Details:**
Application Name: Windows Template Studio (WinTS)
Templates version: 3.8.20273.1
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 3.1
Windows Version: Windows10

### **Repro Steps:**
1. Open Visual Studio 2019 
2. Navigate to File from menu with the help of tab key and press enter key to expand it. 
3. Select new, press enter to expand and then select project.
4. Select the "Windows template studio (WPF.Net Core)". Navigate to next button with the help of tab key and press enter key
5. "Configure your new project" screen will appear. 
6. Navigate to create button with the help of tab key and press enter key.
7. New WPF App screen will open.
8. Navigate to Navigation pane with the help of tab key
9. Using Tab key navigate to details and press enter
10. Navigate to back button with the help of Tab key and press enter to see the focus

### **Actual Result:**
Keyboard focus is not on logical order after performing action on BACK button with tab key. Focus goes to Navigation menu.

### **Note:**
This issue is observed throughout the application where back button is there.

### **Expected Result:**
After performing action on Back button with tab key, keyboard focus should go to details and not on Navigation Menu.

### **User Impact:**
Keyboard users will get confused in navigating the content if focus order is not in logical order after performing action on back button.

**Comment by sibille** [comment]
Verified in dev-nightly version:
Wizard version: 0.22.20310.1

You can install the dev-nightly version from our nightly feed (https://www.myget.org/F/windows-template-studio-nightly/vsix/).
For instructions on how install WTS from the dev-nightly feed in Visual Studio see https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-instructions

**Comment by Yash14j** [comment]
Issue does not repro in the Wizard version: 0.22.20310.1 hence closing this bug.
