### ISSUE TITLE
Unhelpful "readonly" warning

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3906]
**Describe the bug**
An unhelpful messages can be displayed in the wizard notification. This message does not explain why a scenario exists or if/how the user can do anything about it.

**To Reproduce**
1. Go to the `WinUI3.Templates` branch
2. Run VSEmulator
3. Create a WinUI app
4. Try and remove the `MSIX Packaging` feature
5. See message 'You cannot remove **MSIX Packaging** because it is readonly.'

**Expected behavior**
The error message is less than helpful. The error message should explain _why_ an item cannot be removed.  "[B]ecause it is readonly" is not a reason. It's like saying "you're not allowed to do that because we've not allowed you to do that." The immediate response to such a statement is "why isn't that allowed?"  A more appropriate message is "You cannot do X because it's not supported", "... because it's not yet enabled.", "... because it is required by Y", etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/189547/96149699-870b9800-0f01-11eb-8ec3-aa6d5ee63e44.png)

**Additional context**
If what I'm seeing is a message because this is still in development then consider this an issue to track that this is addressed before shipping.
If this is indicative of messages that can be seen based on other selected options, these should all be reviewed and _useful_ messages displayed instead.

Applies to the following platforms:
| UWP              | WPF              | WinUI |
| :--------------- | :--------------- |:---|
| possibly | possibly | Yes |

**System**

- **VS Version:** 
- **WinTS Wizard Version:** 
- **WinTS Template Version:** 
- **Windows Build:**

**Comment by mrlacey** [comment]
Updated OP to remove incorrect point I was confusing with WPF

**Comment by vmadurga** [comment]
We agree that the notification message can be improved.
 
For WinUI3 MSIX is currently required, as you said, once if is optional we'll remove the readonly flag.
The  message is shown for readonly templates in the project layout.json.

It is also shown for the MultiView Feature on a  MenuBar and Pivot project type .
As you suggested we should change the message to something more meaningful , how about :
_"You cannot remove MultiView because it is required for the selected project type."_ ?

**Comment by mrlacey** [comment]
> how about :
> _"You cannot remove MultiView because it is required for the selected project type."_ ?

Sounds good to me

**Comment by mvegaca** [comment]
Verified in Dev Nightly
Templates version: 0.22.20337.1
Wizard version: 0.22.20335.2
