### ISSUE TITLE
Review and decouple VM from Views in Winui 3

### ISSUE THREAD

**Issue by vmadurga** [microsoft/WindowsTemplateStudio#3908]
Review and decouple VM from Views in Winui 3.

Creating this issue to follow up on #2867 on WinUI 3.

Applies to the following platforms:
| UWP              | WPF              |WinUI 3|
| :--------------- | :--------------- |:--------------- |
| No | No |Yes |

**Comment by vmadurga** [comment]
Created Mockup project:
https://github.com/vmadurga/WinUIDecouple

Current status: in progress

**Comment by sibille** [comment]
We've updated the WinUI3 mockup on branch https://github.com/microsoft/WindowsTemplateStudio/tree/Mockup-WinUI3 with the following changes to decouple ViewModels and Views:
- Added Services for interaction with WebView and NavView
- Added method for ConnectedAnimation to NavigationService
- Refactored MasterDetailPage/ViewModel to listen to state changes and select first item if no other item is selected

Would love to get your feedback!

**Comment by sibille** [comment]
@JeanRoca, who can review those changes?

**Comment by sibille** [comment]
We had a review session with WinUI Team yesterday and this looks good. 
Will review usage of ElementTheme in the SettingsViewModel.

**Comment by mvegaca** [comment]
By this moment is not possible to add Test Project to WinUI3 Desktop App Packaged. We will keep using ElementTheme enum in the ViewModel.

Working adding decouple VM in templates.

**Comment by sibille** [comment]
Verified in dev-nightly version:
Templates version: 0.22.21022.1
Wizard version: 0.22.21022.1
