### ISSUE TITLE
Update icons in dev branch for editing summary item

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#391]
current icons are temps

**Comment by mrlacey** [comment]
For reference, I presume you mean these icons
![image](https://cloud.githubusercontent.com/assets/189547/26446672/ff854934-413c-11e7-9566-0b9ab39496fb.png) 

 ![image](https://cloud.githubusercontent.com/assets/189547/26446685/0c4858aa-413d-11e7-85ab-e2df62713059.png)

which exists [here](https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/code/src/UI/Assets)

**Comment by ralarcon** [comment]
We are considering this:

![image](https://user-images.githubusercontent.com/2638875/27122527-4823bbd6-50eb-11e7-9351-bb1d075849e6.png)

And this for re-ordering:
![image](https://user-images.githubusercontent.com/2638875/27122542-59c50b10-50eb-11e7-94db-fa5f4c499feb.png)

**Comment by crutkas** [comment]
those icons look awesome

**Comment by mvegaca** [comment]
Icons added in the following Pull Request
[Issue445 reordering](https://github.com/Microsoft/WindowsTemplateStudio/pull/464)

This is already on dev branch.

**Comment by ralarcon** [comment]
Verified in v0.14.17172.65001; templates v0.14.17172.1
