### ISSUE TITLE
When and how to use Fluent Design System through WindowsTemplateStudio

### ISSUE THREAD

**Issue by joeleesh** [Microsoft/WindowsTemplateStudio#392]
Looking around, there is no much information on how WindowsTemplateStudio will leverage the Fluent Design System. It would be appreciated if anyone can provide some clarity on this issue.

**Comment by mrlacey** [comment]
@joeleesh we will do more once the SDK is out and we have a consistent vision for how this will sit with the rest of what we have. There are also plans to liaise with the Windows Design team to get their feedback and input on what we do out of the box.
Basically, when we have a release that targets the Fall Creators Update, expect the app that's generated to follow the principles and guidelines the design team set out.
Sorry for the vagueness but it's still very early days,

**Comment by crutkas** [comment]
closing this out in favor of #372 .  Both are fluent
