### ISSUE TITLE
Features Missing on New Feature Dialog

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/WindowsTemplateStudio#3922]
The **Background Task** and **Feedback Hub Link** features are currently only available to add during initial project creation.

I would like to see these options also available when you add a new Feature after the project is created.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | No | Yes |

Multi-Instance and Multi-Instance Advanced are also missing but I assume these would be much harder to implement post project creation.

**Comment by sibille** [comment]
Background Task and Multi-Instance are not available on right-click as they are mutually exclusive (https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp#background-tasks-and-multi-instancing) and we don't have a way of knowing if your app uses mutli-instance or background tasks.
For FeedbackHub, there's already on this https://github.com/microsoft/WindowsTemplateStudio/issues/3294, I've added it to milestone 3.9, to reevaluate and see if we can make this available on right click.
