### ISSUE TITLE
Need official designs for deprecation flags

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3928]
#3809 adds the ability to add "flags" to the frameworks that are being deprecated with the introduction of templates using the MVVM Toolkit.

The implemented designs are purely a placeholder.

![image](https://user-images.githubusercontent.com/189547/97327345-c8d6ff80-186c-11eb-9169-db3db3b6f247.png)

This new UI should be reviewed and appropriately adjusted accordingly.

_This is a follow-on from #3753_

**Comment by mrlacey** [comment]
The above image is placeholder only.
The text is deliberately at the top to make it hard to miss.
The text overlays the image to avoid people making a selection based on recognizing the image and not looking at anything else. Obscuring the image was deliberate.
The inverted text (background and foreground colors) is to make the deprecation prominent.
Even if someone never uses the deprecated options, the deprecation notice is to make all users aware that a change is coming. This should minimize the surprise when these options are removed.

**Comment by sibille** [comment]
I looked around a bit on other apps in the ecosystem to see how they mark things deprecated (or in preview). Leaving a few screenshots for reference here.

Windows Community Toolkit:
![image](https://user-images.githubusercontent.com/24698018/114197438-a33d3e80-9952-11eb-824c-817564443f72.png)

XAML Control Gallery:
![image](https://user-images.githubusercontent.com/24698018/114197778-f7482300-9952-11eb-9409-d10354302d1d.png)


Visual Studio: 
![image](https://user-images.githubusercontent.com/24698018/114197535-be0fb300-9952-11eb-9acf-382f6db01b22.png)

**Comment by sibille** [comment]
Design Team recommended us to:
- Not cover the framework images as some of them are brand images
- Use the warning icon for deprecated frameworks as the Nuget Package Manager does
- Show the warning icon and deprecated text below the framework name 
- Make sure "deprecated" text is pronounced by screen-readers

Card content would be similar to: 

**MVVM Light**
⚠️ Deprecated
MVVM Light is a ....

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.22.21110.1
Wizard version: 0.22.21110.1
