### ISSUE TITLE
Business entity form generation with CRUD operation using Fluent Design System

### ISSUE THREAD

**Issue by joeleesh** [Microsoft/WindowsTemplateStudio#393]
Entities, Forms and CRUD operations are bread and butter of all application. Provide sample template that uses  Fluent Design System would be huge boost for most developers.

**Comment by mrlacey** [comment]
@joeleesh are you specifically asking for pages that do this with the Fluent Design System or saying we need some form of those pages. Then add Fluent Design styling support for those pages in FCU?

Support for the Fluent Design System will come in time. X-Ref #392 

Can you be specific about what you woudl wnat in terms fo "Entities, Forms and CRUD operations"

In terms of "entities" do you mean support for Entity Framework?
In terms of "forms and CRUD operations" we'll be adding support for the Telerik DataForm in #330, is this enough, do you want more from this?

**Comment by crutkas** [comment]
we have #129 and #128 (grids and charts) that will be enabled in the near future for base pages.  I feel like this is a duplicate.

Right now this is very vague.

**Comment by joeleesh** [comment]
@mrlacey and @crutkas  These days, developers uses view models to wire up with their UI components. What developers would expect if the studio can generate one or a set of pages with right controls for each view model property The generated page will also comes with right layout, individual control sizing, user interaction animation, font, style on all device from mobile to desktop. It would be idea if the template is not bound to any third party tools such as Telerik DataForm.

**Comment by mrlacey** [comment]
WTS is not bound to any third party tools. We enable the ability to optionally include some functionality from relevant, popular open source projects to supplement what is available natively. We wouldn't want to try and recreate what's available elsewhere and as I said in a comment on #394 we're not planning on making a tool that will generate an app based on a data model.

**Comment by crutkas** [comment]
@joeleesh while a neat idea, it reminds me of [Microsoft PowerApps](https://powerapps.microsoft.com/en-us/) / Windows App Studio / [Visual Studio Lightswitch](https://msdn.microsoft.com/en-us/library/ff851953.aspx)

This is outside our scope of the project right now.

**Comment by dtsob75** [comment]
I would agree that we need samples of the business pages with CRUD examples.  This would tie up their use in a much more usable manner, especially since the methodology is so different from what we (or at least I) are normally used to using.
