### ISSUE TITLE
SampleDataService use static methods in WPF and WinUI3 Templates

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3931]
**Describe the bug**
SampleDataService use static methods in WPF and WinUI3 Templates
private static IEnumerable<SampleOrder> AllOrders()
private static IEnumerable<SampleCompany> AllCompanies()

**Expected behavior**
These methods should be non-static methods.

| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | Yes | Yes |

**System**

- **VS Version:** 
- **WinTS Wizard Version:**  DEV
- **WinTS Template Version:**  DEV
- **Windows Build:**

**Comment by mrlacey** [comment]
> These methods should be non-static methods.

why?

Why not just make everything in the class static?

**Comment by mvegaca** [comment]
We use all non-static services because we use IoC (singleton or transient) but we were reading about that and make sense that these methods can be static
