### ISSUE TITLE
OnNavigatedFrom event is not invoked when navigating backwards in WPF templates

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3944]
**Describe the bug**
OnNavigatedFrom event is not invoked when navigating backwards in WPF templates

**To Reproduce**
 1. Create a new WPF application using WinTS Dev-nightly version
 2. Add at least 2 pages that implement INavigationAware (for example two ContentGridPages)
 3. Start the app
 4. Add breakpoints on the OnNavigatedFrom methods
 5. Navigate between the two pages 
 6. Navigate backwards using the back button

=> OnNavigatedFrom is not invoked when navigating backwards.

**Expected behavior**
 OnNavigatedFrom should also be invoked when navigating backwards.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | Yes |No |

**System**

Templates version: 0.22.20311.1
Wizard version: 0.22.20311.1

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.22.20335.2
Wizard version: 0.22.20335.2

Leaving open as this is still happening on MVVMToolkit and should be fixed there

**Comment by mvegaca** [comment]
PR updated adding MVVM Toolkit WPF updates

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.22.20336.2
Wizard version: 0.22.20336.1
