### ISSUE TITLE
What should be the future for Caliburn.Micro support in WinTS

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#3955]
In June, it was [announced that the maintainer of Caliburn.Micro was stepping away](https://caliburnmicro.com/announcements/stepping-away) without anyone to take their place.

For a long time before that, support for Caliburn.Micro (CM) within Windows Template Studio (WinTS) had been limited and where new functionality was added to WinTS for UWP (CM is not supported in WPF templates in WinTS) support for CM was not included in the new templates.

Given the previous announcement, it was decided that CM would be[ deprecated from WinTS along with MVVMBasic and MVVMLight when support for the MVVM Toolkit is added](https://github.com/microsoft/WindowsTemplateStudio/issues/3753).
This is scheduled to happen in the version after 3.9.

However, [potential new maintainers for Caliburn.Micro have now stepped forward](https://github.com/Caliburn-Micro/Caliburn.Micro/issues/708#issuecomment-697057120). 
This raises some important questions.

The main question being:

# **Should CM remain as an option in WinTS?**

## **If No,** 
then I propose to deprecate it within WinTS as is currently planned.
This is not a criticism of the framework but a realization that the team currently does not have the experience and time to support the development and maintenance of the templates for this framework based on it's [relatively low usage](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/telemetryData.md#framework-uwp). Officially removing CM from the list of options provides the opportunity to focus more resources in other areas, such as supporting WinUI.

## **If Yes,** 

how/will/should the current functionality gap be closed? 

Based on the skills and priorities of the core team, adding support for the missing functionality would need to come from external contributors.
If such volunteers offer to come forward, I propose not deprecating the framework but allowing time for the feature gaps to be closed. 
If the feature gaps are closed then CM, and there is a commitment to maintain parity with other new features when added, it should remain in WinTS.
If the feature gaps are not closed in a reasonable amount of time (to be decided) then it should be deprecated and later removed.

**PLEASE SHARE YOUR THOUGHTS ON THIS IF IT MATTERS TO YOU.**

_Disclosure: I do not have decision making powers in this situation. This is simply the opinion of a long term contributor to the project who recognizes the importance of discussing this topic and a decision being made soon. I'm providing suggestions for the purpose of advancing the discussion._ 

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | No |No |

**Comment by scottkuhl** [comment]
I vote no.  Focus on Code Behind, MVVM Toolkit and Prism which have more life in them.  But there should be a transition plan for existing projects.

**Comment by mrlacey** [comment]
For awareness: @michael-hawker @nigel-sampson  @vb2ae  @KitKat31337

**Comment by nigel-sampson** [comment]
I agree that it should be removed, better to be honest about the lack of support.

**Comment by vb2ae** [comment]
I am curious to know what 8% means in users.  If it is only a few users then sure drop support.  If it means thousands of users then I would think it would be worth keep support going.

**Comment by mrlacey** [comment]
> I am curious to know what 8% means in users. If it is only a few users then sure drop support. If it means thousands of users then I would think it would be worth keep support going.

This would be good to know but Microsoft have so far been reluctant to publish actual numbers.

**Comment by michael-hawker** [comment]
@mrlacey who manages the telemetry? They could at least weigh-in to this discussion without disclosing specific numbers.

We also have an issue open about trying to have a migration guide for anyone who wants to switch from Caliburn.Micro to the MVVM Toolkit, but we haven't started work on that yet: https://github.com/windows-toolkit/MVVM-Samples/issues/11

**Comment by mrlacey** [comment]
> @mrlacey who manages the telemetry? They could at least weigh-in to this discussion without disclosing specific numbers.

The PM for the project will be reaching out to @vb2ae privately. :/

**Comment by vb2ae** [comment]
@mrlacey thank you

**Comment by JeanRoca** [comment]
I am in favor of deprecating as well. The usage is low and the support seems to be unclear. The team is prioritizing WinUI currently and this will allow us to focus more on that. 

@vb2ae please send me an email at jproca@microsoft.com so we can follow up.

**Comment by JeanRoca** [comment]
@vb2ae has been in communication with the team and we have agreed to not deprecate Caliburn.Micro as long as we receive the support that has been generously offered. For now that will be focused on parity with the current UWP templates.

**Comment by JeanRoca** [comment]
Team decision will be to deprecate these templates in 3.10 release and remove these in a later release.

**Comment by mrlacey** [comment]
I'll add the deprecation notices.

**Comment by mrlacey** [comment]
X-Ref #4162

**Comment by mrlacey** [comment]
Verified in 
Templates version: 0.22.21099.1
Wizard version: 0.22.21099.1
