### ISSUE TITLE
How should WTS work with data sources?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#396]
Opening this to try and gather/collate feedback.

**How should Windows Template Studio work with data sources?**

With the pages we have at the moment that use data we just hard code some sample data to show content on the page. Is this good enough?

What data sources would you like to see?
How should these data sources integrate with the code we generate?

If you already have a separate project that contains models, or database access should we be doing more to integrate with these? What would you like to see?

Is it enough to put references and folder structures in place so that you can wire up the code as needed?

Should we generate page contents based on a provided data source? Or leave you to do that? There's a lot of different ways people like things and so I'd be wary of trying to do something that many people would have to remove.

As ever, specifics and justification help :)

**Comment by crutkas** [comment]
haha, i just opened #403.  related but different.

My thought was we have a rich data sample that is local but in that file, we point to the github docs for examples maybe on remote data sources.

**Comment by mrlacey** [comment]
Refined idea

- Add data source specific implementations with usage comparable to the `SampleDataService`. (SQLServerDataService, SQLiteDataService, WebDataService, etc.)
- The generated code can then be changed once modified, so the code uses different providers. This will just be a case of commenting out/deleting the use of `SampleDataService` and replacing with a different data service. TODOs will be included to explain where and how to do this.
- The services should use an underlying implementation for actual data access that can be reused for data beyond just the sample data. [Specifics will vary based on service.]
- Where possible, the actual data services will be able to return data that looks like the sample data. e.g. For the SqlServerDataService it will be able to query the Northwind DB for data like that in the sample.

Automated testing or each data provider will vary based on each implementation and what is appropriate/practical.

**Comment by mrlacey** [comment]
I think the above is all sound (having working POCs for SQLServer & WebAPI/HTTPData based on this) and so will move forward in this way if no-one has objections or better alternatives.

**Comment by mrlacey** [comment]
No dissenting voices so that's what's going to happen :)
