### ISSUE TITLE
Update FormPage to use ObservableValidator from MVVMToolkit

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3961]
We should update our FormPage for WinUI3 to use the ObservableValidator from the MVVMToolkit once the following features are added:
- ValidateAll
- ResetAll

X-Ref https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3569

**Comment by vmadurga** [comment]
The current version of MVVMToolkit (7.0.1) includes ValidateAllProperties(), reset properties to the default values are not suported yet.

**Comment by sibille** [comment]
Think we're fine here resetting the values in the ViewModel and calling ClearErrors after resetting.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21123.1
Wizard version: 0.22.21123.1
