### ISSUE TITLE
Application crashes when click items in ImageGallery page twice

### ISSUE THREAD

**Issue by AkiyaX** [microsoft/WindowsTemplateStudio#3965]
**Describe the bug**
Application crashes when  click items in **ImageGallery** page twice

**To Reproduce**
1. Go to ImageGallery page
2. Click on image 1
3. Click Back
4. Click on image 1
5. App crashed

**Expected behavior**

Go to Image Detail page after step 4

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | ? |? |

**System**

- **VS Version:**  Microsoft Visual Studio Community 2019 version 16.8.2

- **WinTS Wizard Version:** 
- **WinTS Template Version:**  3.8.20273.1
- **Windows Build:**Windows 10 Professional Edition 20H2 version 19042.630

**Comment by sibille** [comment]
Thanks for reporting!
Which projecttype and framework did you use when you created the app?

**Comment by AkiyaX** [comment]
> Thanks for reporting!
> Which projecttype and framework did you use when you created the app?

Windows Template Studio (Universal Windows)
- Navigation Pane
- Mvvm Light

**Comment by sibille** [comment]
Verified on dev-nightly version:
Templates version: 0.22.20336.2
Wizard version: 0.22.20336.1
