### ISSUE TITLE
Rename Packaging project to Proj_Name (Package) in WinUI3

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3972]
**Is your feature request related to a problem? Please describe.**
Rename the Packaging project to Proj_Name (Package) in WinUI3 until WinUI3 becomes release candidate because this will be easy to compare WTS projects with WinUI3 VSIX projects.

**Comment by sibille** [comment]
Verified in dev-nightly version:
Templates version: 0.22.21022.1
Wizard version: 0.22.21022.1
