### ISSUE TITLE
WinUI3 preview3 DataGrid page throws exception

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3974]
**Describe the bug**
WinUI3 preview3 DataGrid page throws exception

**To Reproduce**
1. Create a new WinUI3 (Preview3) project  and add a DataGrid page
2. Start the app and navigate to the Datagrid page

=> The app crashes with the following error 
![image](https://user-images.githubusercontent.com/24698018/100466121-b13fa080-30d0-11eb-82c1-dfe8acdee584.png)

**Expected behavior**
The DataGrid page should show

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by mrlacey** [comment]
link to related issue on WinUI repo?

**Comment by sibille** [comment]
It's reported on the WCT repo in https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3585.

**Comment by anawishnoff** [comment]
@michael-hawker / @stevenbrix - any idea why this is happening? Looks like it's a new issue with WinUI 3 Preview 3 and has been reported a couple of times that adding in a DataGrid makes the app crash.

**Comment by stevenbrix** [comment]
I'm not aware of anything, are we able to get a stack trace?

**Comment by michael-hawker** [comment]
Continuing conversation here. There was a known issue effecting DataGrid in [our release notes](https://aka.ms/wct-winui3):

> There is a known issue with DropDownButton/SplitButton which will crash when opened on newer versions of Windows, this should be resolved in [insider build 20262](https://blogs.windows.com/windows-insider/2020/11/18/announcing-windows-10-insider-preview-build-20262/). This effects the Toolkit's new ColorPickerButton control as well and it can also effect the DataGrid control as well.

From my own testing I think it occurred if you had enough elements in the grid to make scrolling appear. I believe the WinUI 3 fix has already been patched, but it didn't make it in Preview 3? @azchohfi should have more details.

I think the troubling thing is that it was first thought to be a newer windows build problem, but the person who reported https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3585 is on an older build...

**Comment by azchohfi** [comment]
AFAIK, there are 2 fixes. The fix on the WinUI went in preview3, but there is a fix on Windows that requires an update to 20262.

**Comment by sibille** [comment]
This was fixed in WinUI3 Preview4 and is working fine now. 

Verified in dev-nightly:
Templates version: 0.22.21049.2
Wizard version: 0.22.21049.2
