### ISSUE TITLE
Remove Winui3 + MVVMToolkit for 3.9 release

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3978]
Remove WinUI3 entry point and MVVMToolkit from UWP and WPF catalog for 3.9 release.
This will be done once we've merged to release branch.

**Comment by AkiyaX** [comment]
Wondering is that means MVVMToolkit would not coming with 3.9 release. If yes, what's the reason

**Comment by mrlacey** [comment]
> Wondering is that means MVVMToolkit would not coming with 3.9 release. If yes, what's the reason

MVVM Toolkit is still in preview and subject to change.
As a guideline, WinTS does not ship templates that include references to projects/tools that are still in preview. This is to avoid complications from changes to the project/tool that are not compatible with the preview release. For example, we wouldn't want you to build a project with something in the preview version that gets removed or changed in an incompatible way that doesn't work with the release version.

The MVVM Toolkit functionality will remain [available in the nightly builds](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio).

**Comment by sibille** [comment]
Verified in pre-release version:
Templates version: 0.26.20350.1
Wizard version: 0.26.20350.1
