### ISSUE TITLE
WinUI 3 Apps crash after reading Theme from SettingsStorage

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#3984]
**Describe the bug**
After updating the templates to WinUI3 Preview3 apps throws an exception when reading the app theme from SettingsStorage.

There is an Issue on WinUI3 repro to solve this.
[App Crash after reading Theme from SettingsStorage #3730](https://github.com/microsoft/microsoft-ui-xaml/issues/3730)

**Comment by mvegaca** [comment]
Fixed on WinUI 3 Preview 4, I've uncomment the code and removing the reference in code to this worarround in PR #4065

**Comment by sibille** [comment]
Verified on dev-nightly: 
Templates version: 0.22.21049.2
Wizard version: 0.22.21049.2
