### ISSUE TITLE
Improve Naming Infer to apply validation steps independently

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#399]
Naming.Infer does the following: 
- Replace invalid chars
- Check against reserved names
- Check against existing names

Separate this into various steps that can be applied independently. Check also DefaultInstancenames from singleInstance templates are not used in templates that allow name edition. (f.ex a Page cannot be named LiveTile) to avoid collision.

**Comment by ralarcon** [comment]
Verified in nightly build 0.14.17146.65001
