### ISSUE TITLE
Rename CurrentWindow to MainWindow in generated WinUI Code

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3993]
We should rename `CurrentWindow `to `MainWindow` in generated WinUI Code.
MainWindow explains better what's the purpose of this window and avoids confusion with Window.Current from UWP

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by mvegaca** [comment]
Property renamed in templates #3998 and also in mockup in [this commit](https://github.com/microsoft/WindowsTemplateStudio/commit/5092b9aa8e9daf989c9eae9738476e7c2069db86).

**Comment by sibille** [comment]
Verified in dev-nightly version:
Templates version: 0.22.21022.1
Wizard version: 0.22.21022.1
