### ISSUE TITLE
Use localized resources in generated WinUI projects

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#3994]
After updating our templates to WinUI Preview3 we should reevaluate if we can use localized resources from a resw file now. 

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by mvegaca** [comment]
I've added a string localized resource to include the Shell window title in a project Resw file, it works and it's already included in the dev branch.

Accessing to Resw properties works if we do that from code behind (case of WindowTitle in ShellWindow.xaml.cs) but it does not work if we do that from XAML definition.

```xml
<!-- This doesn't work -->
<NavigationViewItem x:Uid="Shell_Main" Icon="Document" helpers:NavHelper.NavigateTo="MyApp.ViewModels.MainViewModel" />
<!-- This works -->
<NavigationViewItem Content="Main" Icon="Document" helpers:NavHelper.NavigateTo="MyApp.ViewModels.MainViewModel" />
```

We can not include the **NavigationViewItem Content** for pages until `x:Uid` localized resources assignment works from xaml.

**Comment by sibille** [comment]
The resw file has to be added as a PRIResource to the csproj. With this cange x:Uid should work fine.

**Comment by sibille** [comment]
We should also use localized Content for the Privacy Statement link in the Settings Page and adapt the developer TODO on the SettingPage.xaml.cs to  `// TODO WTS: Change the URL for your privacy policy in the Resource File, currently set to https://YourPrivacyUrlGoesHere`

**Comment by sibille** [comment]
Verified in dev-nightly:

Templates version: 0.22.21064.1
Wizard version: 0.22.21064.1
