### ISSUE TITLE
WinUI 3 C++ Templates (UWP and Desktop)

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/WindowsTemplateStudio#4011]
# WinUI 3 C++ Templates (UWP and Desktop)

## Summary
In an effort to provide parity with the works in WinUI and attract more developers to both WinTS and WinUI, WinTS should provide users with WinUI 3 templates for C++ users as well. The WinUI 3 team currently offers 2 templates for C++. These are a blank UWP app and blank Desktop app. The team will establish parity with these before expanding into new templates and frameworks. This issue will be updated to reflect those changes as they come.

## Rationale

* WinUI 3 will cover the whole native Windows UI platform. Ranging from Win32 to UWP, it will enable developers to create apps with a modern UX framework.
* WinTS currently has no templating support for WinUI 3 C++.
* WinTS will be able to provide a better File -> New Project experience than the one currently offered.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Provide an easy way for users to create a WinUI 3 C++ app through template studio | Must |
| Provide users with a blank template as a starting point | Must |
| Have documentation for using these templates | Must |
| Identify issues with WinUI 3 during the dev process and document them on the WinUI repo | Should |
| Expand in the future to include more common templates in our wizard like the ones offered already for WinUI 3 C# | Should |

## Roadmap
* Create the mockups and deploy to dev nightly
* Create templates
* Document templates
* CI/CD integration

**Comment by sibille** [comment]
We've published the mockup for a Blank WinUI C++ Desktop App at https://github.com/microsoft/WindowsTemplateStudio/tree/Mockup-WinUI3CppDesktop. There are a few questions related to the mockup that we'd like to discuss: 
1. We observed differences in the MainPage elements in the vcxproj file when comparing the mockup to a project created with the WinUI Vsix. The following elements include the listed subtype elements:
  - MainPage.xaml - `<SubType>Designer</SubType>`
  - MainPage.xaml.cpp - `<SubType>Code</SubType>`
  - MainPage.idl - `<SubType>Code</SubType>`
  
2. Our blank C# templates add a NavigationService and navigate to the first page the user added. We tried to do the same on the C++ Mockup but could not obtain the PageType for navigation. Is there a sample/docs on how to do this in C++?

**Comment by mrlacey** [comment]
> We've published the mockup for a Blank WinUI C++ Desktop App at https://github.com/microsoft/WindowsTemplateStudio/tree/Mockup-WinUI3CppDesktop. There are a few questions related to the mockup that we'd like to discuss:

Discuss with whom? Are you asking for feedback here?

> 
> 1. We observed differences in the MainPage elements in the vcxproj file when comparing the mockup to a project created with the WinUI Vsix. The following elements include the listed subtype elements:
> 
> * MainPage.xaml - `<SubType>Designer</SubType>`
> * MainPage.xaml.cpp - `<SubType>Code</SubType>`
> * MainPage.idl - `<SubType>Code</SubType>`

Is there a question here?
It sounds like you've noticed differences in what you've created compared to what the default project template creates. And...?
If this is just stating changes you've made and you're asking for feedback, can you start by explaining why you've done something different?n

> 1. Our blank C# templates add a NavigationService and navigate to the first page the user added. We tried to do the same on the C++ Mockup but could not obtain the PageType for navigation. Is there a sample/docs on how to do this in C++?

Who is this question for?

The UWP and WPF templates have a description that includes "It provides no scaffolding and leaves everything up to you."
Assuming that the WinUI templates will eventually include the same, it seems superfluous to include a NavigationService at all. Afterall, what is a NavigationService if not part of an applications scaffolding?
I question why a NavigationService is included in a "Blank" project (for any framework.)
It doesn't feel like "a blank canvas upon which to build your app" if you're implying navigation should be handled in a particular way by providing a service to do it.

**Comment by sibille** [comment]
You're right, I missed the actual question: Do we need those subtype elements? How can they be set using VS extensibility? (edited the original post)

To provide more background: We do not do anything special, just generate the files and add them using the EnvDTE's method [ProjectItems.AddFromFile](https://docs.microsoft.com/en-us/dotnet/api/envdte.projectitems.addfromfile?view=visualstudiosdk-2019)


Regarding your thoughts on the blank project type in UWP and WPF: 

I think the initial idea here was to provide a starting point for devs that do not want any of the provided Navigation patterns, but implement their own. All the pages you select are created, first page is shown on the shell window, but navigation to the rest of the pages is not wired up. The NavigationService is used to navigate to the MainPage and also needed in pages like the ImageGallery or ContentGrid, that include navigation. 

I think we should change the description of the blank project type as it is misleading, but let's discuss this in a separate issue. 

Both questions are for C++ devs, @jeanroca, is there anybody concrete we can tag?

**Comment by sibille** [comment]
Synced internally on the subtype question: It seems to be only used on .csproj and .vbproj, so we don't need it here.

**Comment by sibille** [comment]
Depending on the decision in https://github.com/microsoft/WindowsTemplateStudio/issues/4172#issuecomment-808227136 we should adapt the C++ WinUI in Desktop templates.

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.21132.1
Wizard version: 0.22.21132.1
