### ISSUE TITLE
Run standalone option

### ISSUE THREAD

**Issue by jcbritobr** [microsoft/WindowsTemplateStudio#4026]
Make this software run standalone out of visual studio. This will be very usefull for people who dont wants to use ms ide but vscode.

**Comment by mrlacey** [comment]
In that Windows Template Studio lets you build WPF and UWP apps but VSCode does not fully support building such apps, what do you hope to gain by using WinTS with VSCode without using Visual Studio? Are you just installing the SDKs and building from the command line?

However, the code has lots of dependencies on Visual Studio but there is an (undocumented) app called VSEmulator that used in for testing that can operate without Visual Studio. You'll find it in the source.

**Comment by jcbritobr** [comment]
Thats what I was observing in source code. I could install all templates in net5 cli, but thats brokened it. Turned all commands slow. Needed to uninstall. I think I will stay with wpf. Is not so much acoplated to ide.
