### ISSUE TITLE
Support Non-navigating NavigationViewItems

### ISSUE THREAD

**Issue by myokeeh** [microsoft/WindowsTemplateStudio#4029]
@mvegaca, I think I'm recalling why I did this. It was to account for cases where I didn't want navigation to occur for certain  `NavigationViewItem`s. One case is when you have nested `NavigationViewItem`s where for the top/parent, `helpers:NavHelper.NavigateTo` is NOT set because it's more of a container for children `NavigationViewItem`s

It appears even onthe latest version (wizardVersion: v3.9.20351.2, templatesVersion: v3.9.20351.2), clicking on such an `NavigationViewItem` will throw exception below.

>throw new ArgumentException(string.Format("Invalid pageKey '{0}', please provide a valid pageKey. Maybe you forgot to call NavigationService.Configure?", pageKey), nameof(pageKey));

How is WTS going to account for such a case?

_Originally posted by @myokeeh in https://github.com/microsoft/WindowsTemplateStudio/issues/3806#issuecomment-754970442_

**Comment by mrlacey** [comment]
It sounds like you should be using a `NavigationViewItemHeader` instead of a `NavigationViewItem`.

![image](https://user-images.githubusercontent.com/189547/104362364-a79cbb80-550b-11eb-9d7d-990dbf8f993f.png)

![image](https://user-images.githubusercontent.com/189547/104362327-9b186300-550b-11eb-8d81-29d0da1b8c9b.png)

If for some reason you can't do this, you could have the check for a page parameter not throw an exception and instead do nothing.

![image](https://user-images.githubusercontent.com/189547/104362656-fe09fa00-550b-11eb-9239-ff059ce50cce.png)

**Comment by myokeeh** [comment]
`NavigationViewItemHeader` doesn't look like it's collapsible the way you'd be able to if you nest `NavigationViewItem`s. I've removed the Exception throw as you've pointed out.

**Comment by mrlacey** [comment]
> `NavigationViewItemHeader` doesn't look like it's collapsible the way you'd be able to if you nest `NavigationViewItem`s.

It sounds like you want [Hierarchical Navigation](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#hierarchical-navigation) rather than repurposing individual items.

**Comment by sibille** [comment]
@myokeeh, does Hierarchical Navigation with NavigationView.MenuItems solve your issue?

**Comment by myokeeh** [comment]
@sibille, from what I see in the sample code on that page, that's what I mean by nested. I think that's what I'm already doing. `NavigationViewItem`s with children `NavigationViewItem` items. I think there's just a bit of a disconnect between WinUI and WTS when WinUI introduced the ability to have a hierarchy of `NavigationViewItem`s and that NOT all of them will be intended to be "navigating" and purely for "containing" down-level items.

**Comment by sibille** [comment]
Oh, I see the problem now. I think we can add the check you proposed in the inital PR to support this scenario.

**Comment by vmadurga** [comment]
Verified on dev-nightly:
Templates version: 0.22.21106.1
Wizard version: 0.22.21106.1
