### ISSUE TITLE
Default common dataset for sample data

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#403]
With the pending chart and data grid, a richer (maybe generated) default data model may be needed.  This would prevent each page from generating its own.

**Comment by crutkas** [comment]
One thought is to use some nasa asteroid data like they did for the custom control talk at Build 2017

**Comment by mrlacey** [comment]
Maybe we have a SampleDataService to provide this. *Possibly* using it as a guide for whatever we do with other data sources...

**Comment by crutkas** [comment]
not a bad idea.  I just don't want to over complicate stuff but still have enough base data to be useful and not have different sample data for different things.

**Comment by mrlacey** [comment]
A single SampleDataService might be a good single place to collect all the different data used to prepopulate pages. It would remove the duplication when adding multiple copies of the same page and would be an isolated thing that could easily (and should be) removed.
Need to think about the best way to add a file to a project only if it is used by one or other items and those items can each merge with it.
Might require a dependency that doesn't show in the wizard and that isn't something we yet support. But should be easy to add.

**Comment by ralarcon** [comment]
Yes, SampleDataService will work being the base sample data for everything needed. Some time ago we had in mind to allow the user decide if they want sample data or not as an option, but this might increase the templates complexity. In the other hand, to generate always with sample data will make the developers to have to "delete" things they don't want. 

My opinion is that an "opt in / opt out" sample data would be great.

**Comment by mrlacey** [comment]
Any issues with reusing some NorthWind data for this?

**Comment by mrlacey** [comment]
@ralarcon yes, populate the SampleDatService with data from NorthWind. This should provide a varied number of options and avoid any issues with made up names, etc.

**Comment by ralarcon** [comment]
Just one more question... are you thinking in just copy some of the datat into a "static" class or implement the data acces to the database? In our initial approach we where thinkin to have some static data within the SampleDataService, I don't know if adding database would make things "harder"...

**Comment by mrlacey** [comment]
static data. It needs to be self-contained and easily removable.

**Comment by ralarcon** [comment]
That was exacly our thougth.

**Comment by mvegaca** [comment]
Pull request of SampleDataService merged to dev branch.

**Comment by mrlacey** [comment]
Closing as now in dev nightly and seems to be working fine.
