### ISSUE TITLE
MasterDetail page does not adapt the header with VisualStateManager in WinUI3

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4035]
**Describe the bug**
MasterDetail page does not adapt the header with VisualStateManager in WinUI3.
VisualStateManager does not work fine when we start creating the templates on Preview 1 but works as expected on preview 3.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by sibille** [comment]
ListDetail page is now adapting the header, except when navigating between pages in narrow mode https://github.com/microsoft/WindowsTemplateStudio/issues/4072

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21127.1
Wizard version: 0.22.21127.1
