### ISSUE TITLE
ShellWindow -> ShellViewModel method OnUnloaded() never called

### ISSUE THREAD

**Issue by msavazzi** [microsoft/WindowsTemplateStudio#4037]
**Describe the bug**
The method OnUnloaded() is never called on windows closing.
The binding is correct as the UnloadedCommand is invoked and _unloadedCommand is initialized.

Project created on .NET Core

**To Reproduce**
1. Just create a new project
2. Add breakpoint on OnUnloaded method in ShellViewModel.cs
3. Start application
4. Close application with the X
5. app is not blocked on breakpoint and code is not exected

**Expected behavior**
Code to be executed

**Screenshots**

**Additional context**
I've tried to add 
        <i:EventTrigger EventName="Closing">
            <i:InvokeCommandAction Command="{Binding UnloadedCommand}" />
        </i:EventTrigger>

and at that point the OnUnloaded is executed

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  do not know - expect yes | yes  | do not know |

**System**

- **VS Version: 2019
Templates version: 3.9.20351.2
Wizard version: 3.9.20351.2

- **Windows Build: OS Build 19042.746

**Comment by mvegaca** [comment]
We added the unloaded command and method for scenarios where a new window is opened and the ShellWindow is closed. In this case, all events that have been subscribed to in `OnLoaded`, should be unsubscribed from in `UnLoaded` to allow GB to remove this object from memory. You can see an example of this generating an app with forced login service, I've also created [this repro app](https://github.com/microsoft/WindowsTemplateStudio/files/5874335/Issue4037App.zip).

If you want to run code on Window Close, you can use the `Window Closing` or `Window Closed` events, or use `App OnExit` method.

**Comment by msavazzi** [comment]
mvegaca I've downloaded your code, added a breakpoint on OnUnloaded() in ShellVieqwModel.cs , executed in debug mode and is hit only when I create a new window and close the original one.
Is that ok? what that the desired behaviour?
If so everything fine, I'll use a different event :)

**Comment by mvegaca** [comment]
Yes, the idea is to unsubscribe events from the shell window when the user log out, the login window is opened before the shell window close. It looks that when there is only the main window and it's closed the unloaded event is not fired. You can also try to modify the app shutdown mode to MainWindowClose value to change this behavior.

**Comment by sibille** [comment]
@msavazzi, I'm going to close this issue, please reopen if you have further questions related to this.
