### ISSUE TITLE
Reduce instructions on removal of SampleData

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4038]
Opening this issue as follow up from https://github.com/microsoft/WindowsTemplateStudio/issues/3996#issuecomment-758602856.

We should reduce the  instructions on removal of SampleData in the same way we did for WinUI to not overload the tasklist.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes |No |

**Comment by dgomezc** [comment]
We need to remove TODO comments in ImageGallery and Chart templates.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.22.21109.1
Wizard version: 0.22.21109.1
