### ISSUE TITLE
Add AppModel (Desktop, UWP) to WinUI templates and entry points

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4040]
In order to use WinUI as a shared platform for WinUI Desktop and WinUI Uwp apps we need a separate parameter in the template.json and composition queries to define which templates are shared and which are specific to the Desktop or Uwp AppModel. 

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by sibille** [comment]
Idea here is to add another parameter to the UserSelection that allows filtering the templates on the TemplatesRepository and can be used on composition queries. Initially this parameter will be informed on the vstemplate entry point for WinUI.

The UserSelection has a group of context parameters (like language, platform, projecttype + frameworks) that are used to filter templates on the TemplateRepository. We should group them together so they can be passed together to make method signatures easier to understand and less error prone (when parameters are switched).

This needs changes in CoreTS, I'll create a separate tacking issue there.

**Comment by mrlacey** [comment]
> We should group them together so they can be passed together to make method signatures easier to understand and less error prone (when parameters are switched).

Can you expand on this? 
What will it look like?

**Comment by mrlacey** [comment]
Can you show before and after examples of what this will look like?

**Comment by sibille** [comment]
Sure, for CoreTS most important changes are: 

User selection: 
![image](https://user-images.githubusercontent.com/24698018/107403352-4c0f1f00-6b05-11eb-9055-b025db38e523.png)
 
TemplateRepository : 
![image](https://user-images.githubusercontent.com/24698018/107403600-9b554f80-6b05-11eb-82aa-93cbed0bc251.png)

For a full comparison of changes so far see: https://github.com/microsoft/CoreTemplateStudio/compare/dev...sibille:issue4040_addappmodel?diff=split

On the templates this will allow us to specify the appModel on templates like this:
![image](https://user-images.githubusercontent.com/24698018/107404485-9fce3800-6b06-11eb-8a0a-30edb3a71302.png)

and on composition queries like this: 
![image](https://user-images.githubusercontent.com/24698018/107404981-1bc88000-6b07-11eb-8f0c-ff64ec271ec8.png)



The AppModel options will be defined in the WinTS UI project and specified on the VS entry point (at the moment there will be no UI changes)

**Comment by mrlacey** [comment]
Glad I asked now because this isn't the change I was expecting based on the initial description.

What change is being made in this repo to "Add support for AppModel ..."?
The only change appears to be in CoreTS.
Why did this issue (specifically in this repo) need creating? At best it seems a duplication of the one in the CoreTS repo.
If this was created for tracking purposes, why not simply refer to the CoreTS issue from the issue(s) for the functionality that need the new capability?

As per my comments in https://github.com/microsoft/CoreTemplateStudio/issues/287 this seems to only further couple CoreTS and WinTS.

**Comment by sibille** [comment]
There will be changes in this repo too. We'll set the AppModel on the SolutionWizard for WinUI and add the wts.appmodel filters to the WinUI Desktop templates.

Also, as the UserSelection from CoreTS is used in the Wizard, the changes there will need adapting the wizard code too.

I've tweaked the title of both issues to make the difference clearer.

**Comment by vmadurga** [comment]
Projects creation - Verified in dev-nightly:
Templates version: 0.22.21132.1
Wizard version: 0.22.21132.1

Tests - Verified in Dev and Current Pipelines
