### ISSUE TITLE
Check pre-requisits for WinUI3 project creation

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4041]
We are already checking for the required VS workloads, but should also check for the required VS Version.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by sibille** [comment]
WinUI3 need VS 16.8 (https://github.com/microsoft/microsoft-ui-xaml/issues/4411#event-4404960292)

**Comment by dgomezc** [comment]
Verified in dev nightly
Templates version: 0.22.21132.1
Wizard version: 0.22.21132.1
