### ISSUE TITLE
Review right click support for WinUI

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4042]
We need to infer the project metadata for right click on WinUI3. 

We also need to verify that right click on C++ templates only allows page addition as there are no features/services there yet.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by sibille** [comment]
We need to review the InferProject for WinUI Blank and Codebehin in the ProjectConfigInfoService after adding C# UWP Templates

**Comment by sibille** [comment]
After adding the possibility to add itemTemplates using Add->"New Item" to the generated project, we think that we should disable the "WTS right click" for Blank project types in WinUI.

Both options create the same output, but "WTS right click" is less flexible (as it can only be executed from the project node) and also adds an extra step that is not needed in this case.

**Comment by vmadurga** [comment]
Verified in dev-nightly:
Templates version: 0.22.21132.1
Wizard version: 0.22.21132.1
