### ISSUE TITLE
TreeViewPage Exception on Drop TreeViewItem

### ISSUE THREAD

**Issue by aaron-salisbury** [microsoft/WindowsTemplateStudio#4056]
In a UWP generated app with a TreeView page, you can drag and drop TreeViewItems to reorder or move into another entity, but there is no prevention of dropping an item at an incorrect level. When the user does this there is an unhandled exception.

1. Generate UWP application that includes a TreeView page.
2. Launch application.
3. Go to TreeView page.
4. Drag a Company.
5. Drop Company over an Order.
6. Exception.

**Expected behavior**
I'd expect the incorrect drop action to be automatically dismissed/ignored, but at a minimum a gracefully handled exception.

**Comment by mrlacey** [comment]
Nice catch. I didn't even know the TreeView had built-in support for dragging to reorder.

Investigating how to avoid the exception. For the sample data that is included in the generated code, failing silently seems like the most appropriate action.

Aside: according to the documentation, the ability to drag and reorder items is disabled by default but this doesn't appear to be the case. I will also investigate this further.

**Comment by mrlacey** [comment]
Default values are documented incorrectly. Docs issues raised: https://github.com/MicrosoftDocs/winrt-api/issues/1936 & https://github.com/MicrosoftDocs/winrt-api/issues/1937

**Comment by mrlacey** [comment]
It seems there's no easy workaround for this.
The [underlying code](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/TreeView/TreeViewItem.cpp#L108) simply adds the dragged item to the new parent collection without any form of validation or opportunity for capturing the exception that this scenario creates.

I propose the following:
1. Change the generated code to disable dragging and reordering of items in the TreeView page. (This will match the behavior that existed prior to RS5/1809.)
2. Raise a request on the WinUI repository to add an option for handling this scenario. I'm thinking a `DragItemsCompleting` event that allows for client code to validate the item being dropped and the location/container/collection it will be added to. This event would also allow for the drop/reordering to be cancelled by the client code


Note. This is possibly also connected with https://github.com/microsoft/microsoft-ui-xaml/issues/2328

**Comment by mvegaca** [comment]
Added a PR to disable the possibility to reorder items in the generated code.

**Comment by mrlacey** [comment]
> Added a PR to disable the possibility to reorder items in the generated code.

Why just this property and not disabling item dragging as well?
Have you verified the issue separately?
Will you raise the WinUI issue (with minimal repro) too?

**Comment by mvegaca** [comment]
I've check that set CanDragItems to false does not fix the Issue, however I'll open an Issue in WinUI repo to better understand what is it design for.

I've created a minimum repro app that throws this exception on items dragging.
[TreeViewDragAndDropIssue.zip](https://github.com/microsoft/WindowsTemplateStudio/files/5951067/TreeViewDragAndDropIssue.zip)

I've opened an issue with your suggestion in WinUI repo.
https://github.com/microsoft/microsoft-ui-xaml/issues/4135

**Comment by sibille** [comment]
I've opened a new issue for the outstanding questions here: https://github.com/microsoft/WindowsTemplateStudio/issues/4204
For now, we disabled item dragging on the TreeViewPage.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21102.1
Wizard version: 0.22.21102.1

**Comment by aaron-salisbury** [comment]
The rally around this has been very impressive. Thank all of you.
