### ISSUE TITLE
Review usings in WinUI 3 Templates

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4058]
**Describe the bug**
There are some unnecessary using statements in WinUI 3 Templates, we should review the generated code and remove unused usings excepts `using System;`
Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21085.3
Wizard version: 0.22.21085.3
