### ISSUE TITLE
MainPage name change causes bug in App.xaml.cs

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#406]
its a very minor bug but I think is worth the notice.
During template creation I changed the name of home page which is by default "MainPage" so I changed it to "HomePage" but after creation of project I tried to run and App.xaml.cs was still trying to navigate to "Views.MainPage" Which ofcourse doesnt exist because I renamed it to "HomePage" so i just changed it to "Views.HomePage" in App.xaml.cs and now the app works fine.

**Comment by crutkas** [comment]
is this inside of dev branch?

**Comment by mrlacey** [comment]
@touseefbsb yes, if you chance the name of something you have to change the references to that thing too. Visual Studio has a rename refactoring that can do this for you.
We have an issue (#100) that will allow you to rename or change the startup page as part of the wizard but this is still under development and will be part of the v1.1 release. If you want to see it now it's only available if you run from source as it's so new it hasn't made it to the nightly dev build yet.
Of course, if you are running from the source already please check you've got the latest code. I ran it a few hours ago and it worked fine for me.

**Comment by touseefbsb** [comment]
@crutkas  yes I am using the nightly build of the template studio.

**Comment by ralarcon** [comment]
@touseefbsb It should not happen in the latest nightly build. Can you confirm you are running the latest bits? If this is happening in the dev branch (nightly build) I'll mark it as a bug and have a deep look on it. Can you provide the exactly steps you take?

**Comment by ralarcon** [comment]
@touseefbsb you don't need to confirm anything, I just confirmed it... it looks we have had a regresion at some point in time. Marking this as a bug to quick fix it.

**Comment by touseefbsb** [comment]
@ralarcon  ok thankyou

**Comment by ralarcon** [comment]
Fixed in PR #411. Holding to close when verified in following nightly build.

**Comment by ralarcon** [comment]
Verified.
