### ISSUE TITLE
Details pages does not scroll using arrows

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4062]
**Describe the bug**
Some detail pages like MasterDetail or ContentGrid has a long sample data on detail pages. This data is contained in a ScrollViewer that is scrollable using the mouse wheel but no using the arrow keyboards.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes | Yes |

**Comment by dgomezc** [comment]
Verified in dev-nightly:

Templates version: 0.22.21104.1
Wizard version: 0.22.21104.1
