### ISSUE TITLE
What controls and features from the UWP Community Toolkit should we add as pages or features?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#407]
What features and functionality from the UWP Community Toolkit should be able to add preconfigured in WTS?
Full list: http://docs.uwpcommunitytoolkit.com/

Asking because we have had quite a few be suggested already and it might be useful to group them.

For reference, we already have:
- MasterDetailsView #157
- HamburgerMenu #212 
- AdaptiveGridView #405

and a few that may end up using it: #130, #241 & #362

Possible additions:
- BladeView (as a page)
- Carousel (as a page)
- Developer tools (as a feature)
- Any Helpers? (if so which?)
- Any Services? (if so which?)

Please share your suggestions and reasons.

**Comment by mrlacey** [comment]
I wonder if there's a way to determine the most used features of the toolkit.
Probably not on actual use, but page views on their docs might give an indication.

**Comment by skendrot** [comment]
Maybe PullToRefreshListView for list pages?

**Comment by mrlacey** [comment]
@skendrot as a page on its own with just a list? or as part of something else?

**Comment by skendrot** [comment]
Page for sure, or a template that shows a list of items when first opened. However that is probably covered with the MasterDetails template. The UWP Toolkit has had a request to put the PullToRefreshListView in the MasterDetailsView so would be a good addition to the WTS MasterDetails template as well. Or use the UWP Toolkit version.

**Comment by crutkas** [comment]
For PullToRefresh, i would rather have a pointer on the xaml / cs for that.  That is a superset control.  I think that is us going too far.

**Comment by touseefbsb** [comment]
how about a helper service for sqlite database? as an optional service which user can add if they need a database backend with the app locally stored like sqlite db

**Comment by touseefbsb** [comment]
also within uwp community toolkit I guess social services like facebook and twitter are most used so that would be perfect

**Comment by skendrot** [comment]
I don't think the services make sense for WTS. Maybe you would add a page to few twitter/facebook feeds but that's a small use case. Larger usecase for the services are sharing. These are best done with a single button or multiple buttons on a page of your choosing.

**Comment by mrlacey** [comment]
in terms of adding support for services can and should we do more than just add the reference to the package? Is there value in this beyond making it a button click in WTS vs searching/installing in NuGet package manager?

**Comment by crutkas** [comment]
@touseefbsb 

- for SQLite, #134 is SQLite as a feature
- for services, it depends.  for what you listed out, really need to understand the scenarios on how/what we'd generate.  I agree with @skendrot and @mrlacey on his discussion points.  With that said, 100% lets chat on scenarios and use cases.  Those help drive requirements.

**Comment by touseefbsb** [comment]
the main scenario use case for facebook and twitter would be sharing stuff. community toolkit already provides code to do that, we can have that code wrapped around in one class as a service and provide basic methods for the developer to consume and incorporate basing sharing data from app to facebook or twitter. developer can provide their own API key and then start using the API.

**Comment by crutkas** [comment]
@touseefbsb my initial viewpoint is I dislike the idea of doing a wrapper of a wrapper.  Reason being is how is that any different than them just directly referencing it.  It causes a burden on us to stay on top of another framework that has to stay on top of a different service.

I would love to see something mocked out (create a new issue if you want to do this :)) to help adjust my thinking.

**Comment by crutkas** [comment]
for adaptive grid view, i would rather have a grid view and have something that could reference options they could change to as there are a ton of different grids.  What should be the behavior for when they click on something in the grid?

what about virtualization on that as well?

**Comment by skendrot** [comment]
@crutkas The [AdaptiveGridView is a GridView](https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs#L31). It does not layout the items. Instead it sets up [width and height binding](https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI.Controls/AdaptiveGridView/AdaptiveGridView.cs#L87-L88) for the GridViewItem

**Comment by crutkas** [comment]
I personally would rather use the generic in-box item and have in comments alternatives unless there is an extremely compelling reason to not to.

Also lets move this to a new item :)

**Comment by mrlacey** [comment]
closing this as I don't see any value in keeping it open.
Happy to open new issues for adding anything specific
