### ISSUE TITLE
Exception on WebView2 with WinUI 3 Preview 4

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4073]
**Describe the bug**
I think there is an Issue with WebView2 control in WinUI 3 Preview 4.
WebView2 control throws an exception while debugging. The app does not crash and if you press F5 on the exception details view, the app continues running and the webview content is shown.

I've opened an issue in WinUI repo
https://github.com/microsoft/microsoft-ui-xaml/issues/4206

**Comment by JeanRoca** [comment]
@sibille It looks like the fix for this was released yesterday with reunion 0.5. Just found this since I ran into the same issue :)

**Comment by sibille** [comment]
Yes, this issue is solved after updating to Project Reunion 0.5 Preview

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21077.1
Wizard version: 0.22.21075.1
