### ISSUE TITLE
NavigationService.GoBack should return bool

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4076]
Working on #4075 I've noticed that GoBack method in NavigationService should return true if the operation is done and false if not.

This is how it's working on UWP and it is useful in some scenarios like handling a keyboard accelerator invoke event.

```csharp
private static void OnKeyboardAcceleratorInvoked(KeyboardAccelerator sender, KeyboardAcceleratorInvokedEventArgs args)
{
    var navigationService = Ioc.Default.GetService<INavigationService>();
    var result = navigationService.GoBack();
    args.Handled = result;
}
```

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21085.3
Wizard version: 0.22.21085.3
