### ISSUE TITLE
Add Package.appinstaller in MSIX project for WinUI 3 

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4078]
WinUI 3 add Package.appinstaller in MSIX project

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by sibille** [comment]
Verified in dev-nighlty:
Templates version: 0.22.21064.1
Wizard version: 0.22.21064.1
