### ISSUE TITLE
App does not respond to theme changes in Windows when selecting Windows Default theme until restarted

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4086]
App does not respond to theme changes in Windows when selecting Windows Default theme until restarted.

See more detailed info in the WinUI 3 issue
https://github.com/microsoft/microsoft-ui-xaml/issues/3385

**Comment by sibille** [comment]
This issue is solved after updating to Project Reunion 0.5 Preview

**Comment by sibille** [comment]
Verified in de-nightly:
Templates version: 0.22.21077.1
Wizard version: 0.22.21075.1
