### ISSUE TITLE
Theme is not applied to NavView items on App Startup when assigning Dark or Light Theme

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4087]
Theme is not applied to NavView items on App Startup when assigning Dark or Light Theme.

See more detailed info in the WinUI 3 issue
https://github.com/microsoft/microsoft-ui-xaml/issues/3384

**Comment by sibille** [comment]
This issue is still happening after updating to Project Reunion 0.5 Preview

**Comment by sibille** [comment]
This was fixed by adding changing the ShellWindow to ShellPage in PR https://github.com/microsoft/WindowsTemplateStudio/pull/4262
