### ISSUE TITLE
MasterDetail page crash

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4088]
MasterDetail page crash on WinUI 3 Preview 4

There is an opened issue in WindowsCommunityToolkit repo
https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3433

**Comment by JeanRoca** [comment]
@sibille any updates on this issue?

**Comment by sibille** [comment]
This issue is solved after updating to Project Reunion 0.5 Preview

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21077.1
Wizard version: 0.22.21075.1
