### ISSUE TITLE
Question: how to update the app once that a new template is out

### ISSUE THREAD

**Issue by msavazzi** [microsoft/WindowsTemplateStudio#4089]
Team sorry to ask maybe a silly question but I've developed an app with WTS on WPF and I'm super happy of it.
My challenge is that I, obviously, have added a lot of code around to create my app...
... if there is a new version of WTS how can I port the changes in the app ?
Is there anyway?

**Comment by msavazzi** [comment]
Because in my app I have
`
<xml
    xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio">
    <genTemplate:Metadata>
        <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
        <genTemplate:Item Name="wizardVersion" Version="v0.21.20143.1" />
        <genTemplate:Item Name="templatesVersion" Version="v0.21.20146.1" />
        <genTemplate:Item Name="projectType" Value="SplitView" />
        <genTemplate:Item Name="framework" Value="MVVMLight" />
        <genTemplate:Item Name="platform" Value="Wpf" />
    </genTemplate:Metadata>
</xml>
`

and the latest app sample I just created is
`
<xml
    xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio">
    <genTemplate:Metadata>
        <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
        <genTemplate:Item Name="wizardVersion" Version="v3.9.20351.2" />
        <genTemplate:Item Name="templatesVersion" Version="v3.9.20351.2" />
        <genTemplate:Item Name="projectType" Value="SplitView" />
        <genTemplate:Item Name="framework" Value="MVVMLight" />
        <genTemplate:Item Name="platform" Value="Wpf" />
    </genTemplate:Metadata>
</xml>
`

I'm a "little" worried by the difference!!!

**Comment by mrlacey** [comment]
It all depends what you're trying to achieve.

- If you want to add additional pages/features/etc. to you shouldn't need to do anything. Simply, right-click on the project in Solution Explorer, and select `Windows Template Studio` and the option you desire. 

![partial screenshot showing context menu entries for adding to an existing project](https://user-images.githubusercontent.com/189547/108545695-078f3a80-72e0-11eb-9c75-5d88914c771e.png)

- If you're concerned that changes in the code that the newer version of WinTS generates may mean that you're not getting an important bug fix, there are three options
    - Check the [release notes](https://github.com/microsoft/WindowsTemplateStudio/releases)
    - Generate a new app (with the updated version of WinTS) and compare the classes it generates with what's in your app to look for changes.
    - Generate a new app (with WinTS) and copy your changes in to the newly generated version.

Sadly, none of these options are perfect and all require effort on your part. That the generated code can be modified in infinitely many ways means that it's never going to be possible for the tool to be safely modify your app to make all possible changes.  :(

**Comment by mrlacey** [comment]
> I'm a "little" worried by the difference!!!

Aaah, based on those version numbers it looks like they app was originally generated with an early preview of the WPF tooling.

The difference between v0.21.xxx (a nightly/preview build version) and 3.9.xxx (a supported release version) is actually very small. 
It still might be worth comparing a newly generated app with your current code but I don't see any need for concern.

**Comment by msavazzi** [comment]
@mrlacey thank you very much. Clear and exhaustive :) 👍 
I'll follow your guidance and probably will tag somehow the code I've added in the WinTS auto generated files so is easier for me to compare and spot. All the rest is is separate classes...
As I've added a first run wizard and similar I've got to change a little the core classes

**Comment by sibille** [comment]
As you're app was created with a preview version I'd recommend you to compare with version 3.9 to make sure that you got all the changes. 

If there are any future updates that cause breaking changes we'll add a breaking change alert with info on how to update in the "Add New Item" Dialog.

This example shows a breaking change alert on an outdated UWP project for reference: ![breaking_change](https://user-images.githubusercontent.com/24698018/38931740-7b90149e-4314-11e8-8b8c-4adaf6a50ef0.PNG).

**Comment by JeanRoca** [comment]
Closing for now please reopen if you require more information @msavazzi
