### ISSUE TITLE
Question: Confused from libraries used

### ISSUE THREAD

**Issue by msavazzi** [microsoft/WindowsTemplateStudio#4090]
I was studying around and discovered WinTS uses https://github.com/windows-toolkit/WindowsCommunityToolkit and that in the toolkit what is recommended is to use the WCT MVVM implementation and they even provide info on how to migrate from MVVMLight
https://github.com/windows-toolkit/MVVM-Samples/blob/16b5e52f405f92a79f9956d9260233880bd1c89a/docs/mvvm/MigratingFromMvvmLight.md

Also in other topics I've read that WCT is alternative to MahApps.Metro.
But in the MD I read both are used so I'm a little confused.

Can anyone help what is the correct approach and libraries?

Thanks
M

**Comment by mrlacey** [comment]
The MVVM Toolkit is part of the Windows Community Toolkit (WCT) but is currently in preview.
When it comes out of preview, support will be added to Windows Template Studio (WinTS). (It's already there in the [nightly previews](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-extension.md#nightly--pre-release-feeds-for-windows-template-studio) if you want to try it out.)


WCT provides a number of controls and helpers for use in UWP and Win32 apps.

MahApps.Metro is used to provide some controls and the general styling in WPF apps generated by WinTS. This is to give apps generated by WinTS a modern looks and feel.


It's perfectly possible to use both MahApps .Metro and WCT in a single WPF app.


---

> in the toolkit what is recommended is to use the WCT MVVM implementation

Can you link to where this is recommended?

**Comment by msavazzi** [comment]
@mrlacey thank you, very clear.
With regard to the version I'm not able to find the page but here are some of them
https://xamlbrewer.wordpress.com/2020/11/16/a-lap-around-the-microsoft-mvvm-toolkit/

**Comment by sibille** [comment]
@msavazzi, I'm closing this isssue, please reopen if you have any follow up questions.
