### ISSUE TITLE
Update WinUI 3 templates to final WinUI version

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4095]
Once WinUI 3.0 get's released with Project Reunion 0.5 we need to update our templates to the final version.

Packages that are currently in preview and need to get updated:

- [x] Project Reunion 
- [x] MVVM Toolkit 
- [x] Windows Community Toolkit (Controls)
- [x] Microsoft.Xaml.Behaviors.WinUI.Managed

Also need to make sure we update the README file + Mockups + WinUI docs accordingly. 

X-Ref: Tracking issues:
- WinUI 3 C# Desktop: https://github.com/microsoft/WindowsTemplateStudio/issues/3810 
- WinUI 3 C# Uwp: https://github.com/microsoft/WindowsTemplateStudio/issues/4012
- WinUI 3 C++ Desktop + UWP: https://github.com/microsoft/WindowsTemplateStudio/issues/4011

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by sibille** [comment]
@azchohfi is there an ETA for a release version for the Microsoft.Xaml.Behaviors.WinUI.Managed nuget package?

**Comment by azchohfi** [comment]
I'll ask the Xaml Behaviors team, but I don't believe there is anything blocking this prerelease version from being promoted to stable.

**Comment by DVaughan** [comment]
Hi all, 
The release version of the XAML Behaviors for WinUI has just been published over at https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.WinUI.Managed/2.0.3

Thanks @azchohfi for the heads up!

**Comment by sibille** [comment]
Closing this in favor of https://github.com/microsoft/WindowsTemplateStudio/issues/4217
