### ISSUE TITLE
Change TargetPlatformMinVersion for WinUI3 Preview 4 to 10.0.17134.0

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4097]
WinUI 3 Preview 4 minimum supported version is Windows 10 April 2018 Update (version 1803 - build 17134) according to https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#platform-and-os-support

We should change the TargetPlatformMinVersion in our templates to this version.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by mrlacey** [comment]
Who benefits from temporarily changing the TargetPlatformMinimumVersion [when you know this will need to be changed back](https://github.com/microsoft/WindowsTemplateStudio/issues/4098)?

Are enough people using the nightly build feed and needing to test against this OS version (that won't be supported at launch) that it justifies making the changes and testing everything works with this target version?
(I know the change is small but testing isn't quick and will require a test environment--for that OS version-- that isn't already being used to test other WinTS templates.)

Even if this is set up and it finds an issue when using 1803, if that same issue isn't also present in 1809 and above, there would be no benefit in addressing or working around that bug as it would only be relevant to a target that will be unsupported after the current preview.

**Comment by sibille** [comment]
Those are all good points. My thinking was to align WinTS with what WinUI 3 does for Preview4. There aren't too many generations on the dev-nightly, but it might help detect an issue (even if it might not be fixed immediately).
Testing should not be very time consuming as we don't have a lot of framework/project type combinations.

@JeanRoca, what do you think? Should we change our TargetPlatformMinVersion to 1803 for WinUI3 Preview4, even if we know it will go back to 1809 or stay on 1809?

**Comment by sibille** [comment]
Closing this as Project Reunion 0.5 Preview targets 1809
