### ISSUE TITLE
Update WinUI MVVM Toolkit templates to Preview 5

### ISSUE THREAD

**Issue by mvegaca** [microsoft/WindowsTemplateStudio#4104]
Update templates to the latest preview of the MVVM Toolkit (preview 5) and retest all functioanlity.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21064.1
Wizard version: 0.22.21064.1
