### ISSUE TITLE
Review SettingsViewModel use and lifespan

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4122]
In light of the investigation done for #4118 (Current Theme Not Correctly Selected on Settings Page : WPF & MVVMLight)

Review SettingsViewModel use and lifespan everywhere.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  Yes | Yes | Yes|

**Comment by mrlacey** [comment]
## Review Notes

### UWP
- **MVVMLight** : no issue
- **MVVMBasic** : no issue
- **Caliburn.Micro** :  no issue
- **Prism** : no issue
- **CodeBehind** : no issue
- **MVVMToolkit** : no issue

### WPF
- **MVVMLight** : issue as per #4118 |  App name hard-coded
- **MVVMBasic** :  App name hard-coded
- **Prism** : App name hard-coded
- **CodeBehind** : App name hard-coded
- **MVVMToolkit** : App name hard-coded

### WinUI3
- **MVVMToolkit** : App name is not localized correctly | SwitchThemeCommand should look to see if there's a change before doing anything.

I'll create follow up issues for the problems identified above.

**Comment by sibille** [comment]
Great catches @mrlacey, thanks!

**Comment by mrlacey** [comment]
Closing this as separate issues created for follow-up issues.
