### ISSUE TITLE
XAML Island now throws error from generated code

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4140]
**Describe the bug**

When run, a WPF project including the XAML Island page crashes when trying to view this page.

**To Reproduce**
1. Create a new WPF project: Navigation Pane, MVMV Toolkit, + "XAML Island" page
2. Run the generated app
3. Navigate to the "XAMLIsland" page in the app
4. See error:

```ascii
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='No matching constructor found on type 'App254.Controls.XAMLIslandControl'. You can use the Arguments or FactoryMethod directives to construct this type.' Line number '27' and line position '14'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

  This exception was originally thrown at this call stack:
    System.Xaml.Schema.XamlTypeInvoker.DefaultCtorXamlActivator.EnsureConstructorDelegate(System.Xaml.Schema.XamlTypeInvoker)
    System.Xaml.Schema.XamlTypeInvoker.CreateInstance(object[])
    MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(System.Xaml.XamlType, object[])
    MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(System.Xaml.XamlType, object[])

Inner Exception 1:
MissingMethodException: No default constructor found for type 'App254.Controls.XAMLIslandControl'. You can use the Arguments or FactoryMethod directives to construct this type.

```

**Expected behavior**

The XAML island page displays without error.

**Screenshots**

**Additional context**

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | Yes |No |

**System**

- **VS Version:** 16.10
- **WinTS Wizard Version:** 0.22.21070.1
- **WinTS Template Version:** 0.22.21070.1
- **Windows Build:** 2004/21296.1010

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21099.1
Wizard version: 0.22.21091.1
