### ISSUE TITLE
Inconsistent page margins

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4141]
**Describe the bug**

The margins of individual pages that can be added to a generated app are inconsistent and it's not clear why this is the case.

If the variations are deliberate, it's not clear why this is the case.

A careless or casual approach to layout consistency is in contrast to the project goal of providing a strong foundation that the developer can build on.
Navigating through the app as generated can also be distracting as comparable items on different pages appear to move about while navigating between pages.

If the variations are accidental this highlights a need to correct the incorrect situation and add a design review process that ensures new page additions are in keeping with the styles and layout of exising pages.

**To Reproduce**
1. Create a new UWP or WPF app including all available pages
2. Run the generated app
3. Notice different margins as you navigate between the pages

These are the margin values currently in use:

**UWP**
Blank - 24,0
Camera - 0,0
Chart - 24,0
ContentGrid (list) - 24,0
ContentGrid (details) - 36,0
DataGrid - 12,0
ImageGallery (list) - 24,0
ImageGallery (detail) - 0,0
InkDraw - 0,0
InkDrawPicture - 0,0
InkSmartCanvas - 0,0
Map - 0,0
MasterDetail (list) - 0,0
MasterDetail (detail) - 52,40,52,0
Media Player -  0,0
Settings - 24,0
TabbedPivot - 24,0
TabView - 0,0
TelerikDataGrid - 24,0
TwoPaneView (list) - 0,0
TwoPaneView (detail) - 52,40,52,0
WebView - 0,0

**WPF**
Blank - sides:24, top/bottom:0
ContentGrid (list) - sides:12, top/bottom:0
ContentGrid (details) - sides:24
DataGrid - sides:12, top/bottom:0
MasterDetail - sides: 0, top/bottom:0
Settings - sides:24, top/bottom:12
WebView - sides:0, top/bottom:0

**Expected behavior**

The same margin values should be used consistently. Variations should be clear and documented.

**Screenshots**

**Additional context**

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes |No |

**System**

- **VS Version:** 16.9
- **WinTS Wizard Version:** 0.22.21070.1
- **WinTS Template Version:** 0.22.21070.1
- **Windows Build:** 2004/21296.1010

**Comment by sibille** [comment]
We got a design review from the fluent design team for the UWP pages 2 years ago, that's where the margins come from. 
https://github.com/microsoft/WindowsTemplateStudio/issues/1229#issuecomment-428996724

**Comment by mrlacey** [comment]
Wow. If I'd seen that at the time I'd have pushed back with some questions. But if this is the official guidance then so be it.
