### ISSUE TITLE
Review ongoing support for Caliburn.Micro (UWP)

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4143]
Deprecation of Caliburn.Micro (CM) support in the UWP templates was originally planned as part of the changes in #3753. But, when new maintainers for the project stepped forward and committed to also supporting CM templates within WinTS, deprecation was delayed subject to a demonstration of commitment to support the templates.

This issue has been created as a reminder that this situation should be reviewed in the future based on involvement and a demonstration of that commitment.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  Yes | No | No |

**Comment by JeanRoca** [comment]
Thanks for this. We have yet to hear back from the maintainers and I feel it is adequate to deprecate at this point.

**Comment by mrlacey** [comment]
X-Ref #3955 
The decision was previously made to deprecate support and this was implemented as per the release of v3.10 of WinTS
