### ISSUE TITLE
WinUI 3 Runtime Components

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/WindowsTemplateStudio#4146]
# WinUI 3 Runtime Components

## Summary
To provide parity to the templates currently offered by WinUI 3 in the Project Reunion 0.5 VSIX, we must offer developers with the entry points in our wizard to create runtime components. Due to us not supporting customizations of runtime components currently, we will NOT open the WinTS wizard upon project creation and instead just generate the runtime component output. These templates will include the same output as these which are in the current Project Reunion VSIX:
![image](https://user-images.githubusercontent.com/33772802/110923559-a6f38c00-82e6-11eb-9259-797fe7dddca0.png)

## Scope
| Capability | Priority |
| :---------- | :------- |
| Provide exact same output as the Project Reunion 0.5 VSIX | Must |
| Provide one entry point for each (Desktop and UWP) | Must |
| Will not open up the WinTS wizard | Must |

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
|  No  |  No  |Yes |

**Comment by sibille** [comment]
While working on the templates for Runtime Components we had the following doubts:

- Naming: We're currently using the same name as the reunion vsix: Windows Runtime Component (WinUI in UWP) and the WTS icon. Should we add Windows Template Studio or WTS to the name?
- TargetFramework dialog: We're showing the TargetFramework/MinTargetFramework dialog  as the reunion vsix does. We don't show this dialog for Uwp App creation and always target 2004/1809 instead. Wondering if we should do the same for Runtime component creation to be consistent.
- Certificate: Reunion VSIX creates a Test Certificate for Runtime components. The certificate does not seem to be used in the project. Can we remove test certificate creation here?

**Comment by sibille** [comment]
C++ runtime component uses nugets from the Project.Reunion repository, we should add and consume those packages from our own vsix

**Comment by sibille** [comment]
> TargetFramework dialog: We're showing the TargetFramework/MinTargetFramework dialog as the reunion vsix does. We don't show this dialog for Uwp App creation and always target 2004/1809 instead. Wondering if we should do the same for Runtime component creation to be consistent.

We decided to not show the TargetFramework/MinTargetFramework dialog in WTS always target 2004/1809 instead which is what project reunion supports. If the dev wants to adjust, this can be done in the project settings after creation.

> Test Certificate creation: Reunion VSIX creates a Test Certificate for Runtime components. The certificate does not seem to be used in the project. Can we remove test certificate creation here?

We'll remove the Test Certificate here as it is not used.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21131.1
Wizard version: 0.22.21131.1
