### ISSUE TITLE
Update documentation to reflect the deprecation of MVVM Basic & MVVMLight

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4147]
As part of adding support for MVVM Toolkit and deprecating MVVMLight & MVVMBasic (#3753), there are multiple pieces of documentation that need to be updated. 

Key pieces of documentation that must be updated before the release.

- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-started-endusers.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/frameworks/mvvmbasic.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/frameworks/mvvmlight.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/frameworks/readme.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/getting-started-endusers.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/frameworks/mvvmbasic.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/frameworks/mvvmlight.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/frameworks/readme.md

Less important documentation that should not block release.
_These items use examples from now deprecated frameworks that must be updated to use MVVM Toolkit._

- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/activation.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/activation.vb.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/navigation-advanced.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/navigation.md
- https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/navigation.vb.md

**Comment by mrlacey** [comment]
Have updated all, including the "less important" ones.

**Comment by mrlacey** [comment]
Closing as merged and now the default docs on the repo

**Comment by michael-hawker** [comment]
@mrlacey should the Readme also be updated?

**Comment by mrlacey** [comment]
> @mrlacey should the Readme also be updated now? Have the bits shipped?

It's still not decided when this will ship. :(
