### ISSUE TITLE
Conflict on DLLs

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#415]
File->WTS -> Blank w/ MVVM Light
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	App95			
Log:
1>  There was a conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes".
1>      "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" was chosen because it was primary and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" was not.
1>      References which depend on "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Users\crutkas\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll].
1>          C:\Users\crutkas\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll
1>            Project file item includes which caused reference "C:\Users\crutkas\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll".
1>              C:\Users\crutkas\.nuget\packages\Microsoft.NETCore.Portable.Compatibility\1.0.2\ref\netcore50\mscorlib.dll
1>      References which depend on "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" [].
1>          C:\Users\crutkas\.nuget\packages\CommonServiceLocator\1.3.0\lib\portable-net4+sl5+netcore45+wpa81+wp8\Microsoft.Practices.ServiceLocation.dll
1>            Project file item includes which caused reference "C:\Users\crutkas\.nuget\packages\CommonServiceLocator\1.3.0\lib\portable-net4+sl5+netcore45+wpa81+wp8\Microsoft.Practices.ServiceLocation.dll".
1>              C:\Users\crutkas\.nuget\packages\CommonServiceLocator\1.3.0\lib\portable-net4+sl5+netcore45+wpa81+wp8\Microsoft.Practices.ServiceLocation.dll
1>              C:\Users\crutkas\.nuget\packages\MvvmLightLibs\5.3.0\lib\windows81\GalaSoft.MvvmLight.Extras.dll

**Comment by mrlacey** [comment]
@crutkas was this when generating while offline? I cannot repro

**Comment by crutkas** [comment]
Yes.  Had to manually add in the budget reference to compile.

**Comment by mrlacey** [comment]
Is this still valid? suspect it's the same as #418 (can't generate when offline) which has now been fixed.

**Comment by crutkas** [comment]
Just tested, no conflict thrown this time.
