### ISSUE TITLE
Update MasterDetail to ListDetail

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WindowsTemplateStudio#4152]
**Is your feature request related to a problem? Please describe.**
Now that WCT 7.0 has shipped the MasterDetail template should be updated to use ListDetailsView control and naming instead.

The link in the docs should also be updated after, see the root issue here: https://github.com/MicrosoftDocs/windows-uwp/issues/2949

**Describe the solution you'd like**
Update Template for new control.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes |  | Yes |

**Comment by sibille** [comment]
Thanks for opening this issue @michael-hawker! 
For WinUI3 we are already using the new control, but need to update our template name + docs.
For UWP we need to update to WCT 7.0.0 and update control + template name and docs

I think we should rename MasterDetail page for WPF to ListDetail too, for consistency, although we are not using controls from the WCT there.

**Comment by sibille** [comment]
Verified on dev-nightly:
Templates version: 0.22.21102.1
Wizard version: 0.22.21102.1
