### ISSUE TITLE
WinUI 3 NavigationView does not apply correct styles

### ISSUE THREAD

**Issue by vmadurga** [microsoft/WindowsTemplateStudio#4159]
**Describe the bug**
After updating WinUI 3 Nuget package to Project Reunion "0.5.0-prerelease" NavigationView does not apply correct styles when use small window size.

**Expected behavior**
Apply correct styles

Expected:
![imagen](https://user-images.githubusercontent.com/25466105/111995439-36841080-8b19-11eb-8d2a-19dc409f82f1.png)

**Project example**
[NavView.zip](https://github.com/microsoft/WindowsTemplateStudio/files/6182256/NavView.zip)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/25466105/111994182-c2953880-8b17-11eb-8527-d43747df2f29.png)

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

- **VS Version:** 16.9.0
- **Windows Build:** 19042.868
- **Dotnet SDK:** 5.0.200

**Comment by mrlacey** [comment]
Corresponding WinUI3 bug? or is this a problem with the code generated by WinTS?

**Comment by sibille** [comment]
We think it's a WinUI3 issue, working on opening the corresponding issue.

**Comment by sibille** [comment]
X-Ref: https://github.com/microsoft/microsoft-ui-xaml/issues/4608

**Comment by sibille** [comment]
This was fixed as part of the update to reunion 0.5.5
