### ISSUE TITLE
WinUI 3 ListDetailsView does not work as expected

### ISSUE THREAD

**Issue by vmadurga** [microsoft/WindowsTemplateStudio#4160]
**Describe the bug**
After updating WinUI 3 Nuget package to Project Reunion "0.5.0-prerelease" and Microsoft.Toolkit.Uwp.UI.Controls to 8.0.0-preview5, ListDetailsView does not work as expected. Apparently ListDetailsView does not apply the styles correctly

**Expected behavior**
Apply correct styles and work correctly

Expected:
![imagen](https://user-images.githubusercontent.com/25466105/112005922-7ea83080-8b23-11eb-8b8c-b67403ab9362.png)

**Project example**
[ListDetails.zip](https://github.com/microsoft/WindowsTemplateStudio/files/6182957/ListDetails.zip)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/25466105/112006106-b3b48300-8b23-11eb-908b-d9680a2ce980.png)

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**System**

- **VS Version:** 16.9.0
- **Windows Build:** 19042.868
- **Dotnet SDK:** 5.0.200

**Comment by vmadurga** [comment]
X-Ref: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3874

**Comment by sibille** [comment]
This was fixed as part of the update to reunion 0.5.5
