### ISSUE TITLE
Add ItemTemplates for WinUI

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4164]
To provide parity to the templates currently offered by WinUI 3 in the Project Reunion 0.5 VSIX, we should offer the same ItemTemplates as the Project Reunion VSIX.

Items available in Project Reunion VSIX for Desktop Apps:
![image](https://user-images.githubusercontent.com/24698018/112290830-e2e80300-8c8f-11eb-983f-0f43c6d48187.png)

Items available in  Project Reunion VSIX for UWP Apps:
![image](https://user-images.githubusercontent.com/24698018/112291094-1aef4600-8c90-11eb-9675-63263f79d540.png)

Item Templates should be provided for C# and C++.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by mrlacey** [comment]
As the [Project Reunion VSIX](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion) contains nothing more than the templates, is this just a case of copying [the relevant files from the Project Reunion repo](https://github.com/microsoft/ProjectReunion/tree/main/dev/VSIX)?

Or, will any changes or reviews of that code be made?
(Noting that there are [open questions](https://github.com/microsoft/ProjectReunion/discussions/574) on the other repo about the contents of the templates.)

**Comment by sibille** [comment]
At the moment it is a copy.! 
Thanks for linking the questions, agree that we should discuss them once we have parity. @JP for awareness.

**Comment by sibille** [comment]
Our WinUI template icons are showing pixeled in the new item dialog, we'll need to review we provide all the required sizes.

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.21132.1
Wizard version: 0.22.21132.1
