### ISSUE TITLE
AssemblyInfo shows year of 1976 instead of current year.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#417]
File->new blank app
[assembly: AssemblyCopyright("Copyright ©  2017")]

File->WTS->blank + MVVM Light
[assembly: AssemblyCopyright("Copyright ©  1976")]

**Comment by mrlacey** [comment]
1976 is a placeholder that should be replaced by the current year.
Config for this is in WTS\templates\Projects\Default\.template.config\template.json

**Comment by sibille** [comment]
Fixed with PR #419

**Comment by ralarcon** [comment]
Verified in latest nightly.
