### ISSUE TITLE
Add Blank Project Type and None Design Pattern to WinUI 3 Desktop Templates

### ISSUE THREAD

**Issue by JeanRoca** [microsoft/WindowsTemplateStudio#4172]
WinUI 3 templates in the Wizard only have Navigation Pane as a project type and MVVM Toolkit as design pattern. It would be good if we offered a "blanker" alternative to developers that just wanted to create a blank app that does not utilize navigation. This is also how the current WinUI 3 templates are provided in the Reunion VSIX so it would allow us to align with that as well.

If a developer picks a blank project type, then they would not get access to add more pages or features to their app as they would have no way to navigate to them. 

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by sibille** [comment]
On the C++ WinUI Desktop we currently add 1 blank page and allow addition of additional blank pages, 
![image](https://user-images.githubusercontent.com/24698018/112639636-c7702a00-8e40-11eb-87c3-d68684526f5c.png)


but working on this issue we've found a way to remove this blank page too and make the Blank project a bit blanker. 
![image](https://user-images.githubusercontent.com/24698018/112639498-a1e32080-8e40-11eb-9735-158da314d371.png)


Giving the following options which do you prefer for the blank project type: 
1. Do not offer the possibility to add blank pages to blank projects 
2. Always add a blank page and allow to add more blank pages 
3. Do not add a blank page by default, but allow to add more blank pages directly on the wizard

**Comment by sibille** [comment]
"Blank" should be the default option for project type to allow the creation of a blank app with as few extra steps as possible.

**Comment by sibille** [comment]
We'll go for option 1 to keep the blank templates as blank as possible.

**Comment by sibille** [comment]
We'll rename the design pattern to "None" for the Blank templates in WinUI, as this better reflects what's generated.

**Comment by mvegaca** [comment]
Verified in dev-nightly
Templates version: 0.22.21131.1
Wizard version: 0.22.21131.1
