### ISSUE TITLE
Working offline -> can't generate a blank MVVM project.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#418]
2 error are thrown.
Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot resolve Assembly or Windows Metadata file 'System.Runtime.dll'	App89	c:\users\crutkas\documents\visual studio 2017\Projects\App89\App89\App89.csproj
	
Error		Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	App89

Adding back in to the csproj alloweed it to compile again in project reference area
<ItemGroup>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>5.2.3</Version>
    </PackageReference>
  </ItemGroup>

**Comment by mrlacey** [comment]
I have this as well but for any combination when offline.  'Microsoft.NETCore.UniversalWindowsPlatform' doesn't get added to the project and must be added manually.
Assumed it's a NuGet thing where some packages won't be loaded from a local cache, possibly a Time-To-Live indicator on the cache item expiry.

**Comment by ralarcon** [comment]
Selfasigned to review if we can easily avoid this behaviour.

**Comment by crutkas** [comment]
Ugh.  The part that was in the csproj file was left out when inposted

**Comment by ralarcon** [comment]
Verified in nighly 0.14.17165.65001
