### ISSUE TITLE
how share target works if I include it in a Uwp project

### ISSUE THREAD

**Issue by Javier118** [microsoft/WindowsTemplateStudio#4181]
how share target works if I include it in a Uwp project. I have a button on the MainPage as I could link this button to the share Target for Image control found on the Main page.

**Comment by sibille** [comment]
@Javier118, I'm not sure what you're trying to achieve. 
Could you provide more detailed steps or share a repro project?

**Comment by mrlacey** [comment]
> how share target works if I include it in a Uwp project. I have a button on the MainPage as I could link this button to the share Target for Image control found on the Main page.

Being a share **Target** allows other apps to share data with your app. 
If you want to do something when you click a button on the page, you probably want to be a Share **Source** so you can share something (an image?) with another app.

**Comment by Javier118** [comment]
In the App I added the share target to the project but as I can from the MainPage you go through a button in lazar with the Share Target to share an image and enter it in the image control

**Comment by Javier118** [comment]
> > ‎cómo funciona el destino compartido si lo incluyo en un proyecto para Uwp. Tengo un botón en el MainPage, ya que podría vincular este botón al control Compartir destino para imagen que se encuentra en la página principal.‎
> 
> ‎Ser un ‎**‎destino‎**‎ compartido permite que otras‎
> ‎ aplicaciones compartan datos con tu aplicación. Si quieres hacer algo al hacer clic en un botón de la página, probablemente quieras ser un ‎**‎origen compartido‎**‎ para que puedas compartir algo (¿una imagen?) con otra aplicación.‎

**Comment by Javier118** [comment]
the idea from The App on one of the pages I have the Image control and the button that will open the share to choose the image and put it in the image control

**Comment by mrlacey** [comment]
> the idea from The App on one of the pages I have the Image control and the button that will open the share to choose the image and put it in the image control

From this description, it sounds that you want the [FileOpenPicker ](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker?view=winrt-19041&WT.mc_id=WDIT-MVP-5001397) so you can choose a file from disk and then display it in the app.

Sharing (via Share Targets and Share Sources) is about for passing data (including files & images) between apps.

**Comment by Javier118** [comment]
More than fileopen picker I think it's better to use share target

**Comment by mrlacey** [comment]
> More than fileopen picker I think it's better to use share target

If you want your app to go out and get the file from somewhere else you need the FilePicker.
If you want the user to be in another app (including file explorer) select share, have them pick your app, and then your app (be launched/activated and) receive the file (or the path) then you need your app to be a Share Target.

[Documentation for receiving data (being a share target)](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/receive-data)
This is not something that can start with a button being clicked in the app you want to receive (and show) the image.

**Comment by Javier118** [comment]
I want to do is access the image library

**Comment by mrlacey** [comment]
Based on the information provided, it sounds like this is a general programming inquiry about how to load and display an image from a user-selected location.

The simplest way to do this is to add this to the XAML page.

```xml
    <StackPanel>
        <Button Click="LoadImageClicked">Load Image</Button>
        <Image x:Name="DisplayedImage" />
    </StackPanel>
```

Add add this to the code-behind file.

```cs
using Windows.Storage;
using Windows.Storage.Pickers;
using Windows.UI.Xaml.Media.Imaging;

...
    private async void LoadImageClicked(object sender, Windows.UI.Xaml.RoutedEventArgs e)
    {
        var picker = new FileOpenPicker();
        picker.ViewMode = PickerViewMode.Thumbnail;
        picker.SuggestedStartLocation = PickerLocationId.PicturesLibrary;
        picker.FileTypeFilter.Add(".jpg");
        picker.FileTypeFilter.Add(".jpeg");
        picker.FileTypeFilter.Add(".png");

        var file = await picker.PickSingleFileAsync();
        if (file != null)
        {
            using (var fileStream = await file.OpenAsync(FileAccessMode.Read))
            {
                var bitmapImage = new BitmapImage();
                await bitmapImage.SetSourceAsync(fileStream);
                DisplayedImage.Source = bitmapImage;
            }
        }
    }
```



In the future, asking general questions on [StackOverflow](https://stackoverflow.com/questions/ask) or the [Microsoft Q&A site](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) is likely to get you a quicker answer. We ask that issues opened on this repository are directly related to Windows Template Studio or the code included in the generated app. We don't have the capacity to answer general programming questions here.
