### ISSUE TITLE
XamlIsland controls are always on top

### ISSUE THREAD

**Issue by Phil-jci** [microsoft/WindowsTemplateStudio#4183]
**Describe the bug**
When using XamlIsland based control, if you use the RightPaneService based settings page the XamlIsland controls sit on top of the settings right pane, instead of going underneath it.

**To Reproduce**
1. Create a new Templated WPF project with Menu based navigation, a settings page and a XamlIslands page.
2. Run the App.
3. Go to the XamlIsland view, then open the Settings.
4. The settings pane slides out over the top of the WPF controls, but if you shrink the window so that the settings pane would go over the UWP controls, the UWP controls cover the settings pane.

**Expected behavior**
The UWP controls should be underneath the right hand pane when it slides out.

**Screenshots**
![Islands Bug](https://user-images.githubusercontent.com/81750242/113281859-0a694c00-92de-11eb-9945-dee549bf96b1.png)

**Additional context**

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes | No |

**System**

- **VS Version: 2019 Enterprise** 
- **WinTS Wizard Version: v3.9.20351.2** 
- **WinTS Template Version: v3.9.20351.2** 
- **Windows Build: 19042.867**

**Comment by vmadurga** [comment]
Thanks for reporting @Phil-jci, We'll have a look at this.

**Comment by mrlacey** [comment]
I believe this is a side-effect of how XAML Islands are implemented and not somethings specific to WinTS, and not something it's possible to work around.
I believe the best solution is to not have a design that might try and overlap with the XAML Island. The simplest solution is probably to put the settings in a "regular" page inside the app and not in a flyout. 
Note. I'm not suggesting a change to the templates here, rather something developers can change inside their generated app.

**Comment by Phil-jci** [comment]
Matt,

Thanks for looking into this for me, in the application I'm building (where I actually ran into this issue) I did have my settings as a page rather than a flyout, but thought the flyout might look fancier. I guess I'll go back to the separate settings page.

I am finding that Xaml Islands is generally more trouble than it's worth. I originally thought it would be a way to move over to UWP a bit at a time, but I just keep encountering "side-effects of how XAML Islands works". I'm thinking it may be better just to create a complete UWP application, the extra time spent learning UWP is hardly wasted.

Thanks for your time.
Phil.

**Comment by Phil-jci** [comment]
P.S. found an alternative for my particular application.
Setting the SplitView DisplayMode property to Inline (instead of overlay) does work, since it simply shrinks the XAML Islands space instead of trying to sit on top of it. However you do need to then implement a mechanism to close the Pane manually since it doesn't close by simply clicking elsewhere as with the Overlay mode.
