### ISSUE TITLE
Wizard stuck in full screen when magnetizing with top of screen

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4185]
Originally reported by @calvega at  https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3911

---

**Describe the bug:**
Magnetizing wizard template up top of screen causes wizard to permanently go full screen and no longer be resizable. No option to minimize window or option for resizable corners.

**Steps to reproduce the behavior:**

1. Create WTS project.
2. Once WTS wizard opens, drag wizard the top of the screen so that it magnetizes and becomes full screen.
3. Attempt to minimize or resize wizard.
4. Press cancel to exit and regain control of screen.

**Expected behavior:**
Ability to resize window back down so that it doesn't take over the screen permanently.

--- 

I've confirmed this happens in Wizard version: 3.9.20351.2

**Comment by sibille** [comment]
Thanks for reporting @calvega and @mrlacey. 
The New Project Dialog in Visual Studio has a maximize/restore down button next to the close button to avoid this issue
![image](https://user-images.githubusercontent.com/24698018/113675836-0d888180-96bc-11eb-9e67-161ebb468e09.png)
![image](https://user-images.githubusercontent.com/24698018/113676153-67894700-96bc-11eb-866c-5d83884bf9d3.png)

I think we can use the same behaviour for WTS.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21123.1
Wizard version: 0.22.21123.1
