### ISSUE TITLE
Review + Re-enable WinUI Template Tests

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4197]
We've temporarily disabled WinUI Template Tests on our build pipelines due to an issue https://github.com/microsoft/ProjectReunion/issues/700.

In the meantime, we are validating changes compiling the generated apps in Visual Studio (they build correctly there).

Once this is fixed we should review and re-enable tests.

We can probably remove the RuntimeIdentifier as this should be resolved automatically.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by vmadurga** [comment]
Verified in Pipelines
