### ISSUE TITLE
Where to put Azure ClientId at login?

### ISSUE THREAD

**Issue by Javier118** [microsoft/WindowsTemplateStudio#4199]
Where I can put the Client ID code of the App in the optional login in App UWp . also in azure configured the personal account puts me the option sdk live in the App I would have to install live and Azure client

**Comment by sibille** [comment]
The ClientID should be configured in the App.config file, please replace the "set_your_client-id" placeholder in the AppSettings section with the ClientId from Azure.

```
  <appSettings>
    <add key="IdentityClientId" value="set_your_client_id" />
  </appSettings>
```

For a basic scenario where you want to allow the user to login to your app, you don't need the "Live SDK support" option. 
This is required only required for integration with Microsoft account SDKs such as Xbox or Bing Ads​

**Comment by Javier118** [comment]
this is problem when I put the username and give next I get an empty box with a button closed.
