### ISSUE TITLE
Optional Login pair a Uwp crash

### ISSUE THREAD

**Issue by Javier118** [microsoft/WindowsTemplateStudio#4211]
I have put login optional but when I go I have entered the outlook account does not come out to put the password directly I get a dialog box with button close. The APp is ua uwp.   

version WTS : Versión de las plantillas: 3.9.20351.2
Versión del asistente: 3.9.20351.2

**Comment by sibille** [comment]
Sorry, I cannot reproduce this. 
Could you provide more info?

What's the message on the dialog box?
Which framework and project type did you use when creating the project?
Did you configure the ClientID as mentioned on the developer TODO in the IdentityService?

```
        // TODO WTS: Please create a ClientID following these steps and update the app.config IdentityClientId.
        // https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app
        // Make sure you configure urn:ietf:wg:oauth:2.0:oob as a redirect uri as described in
        // https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.applicationoptions.redirecturi?view=azure-dotnet
```
What was the supported account type you chose when configuring the ClientID?

**Comment by Javier118** [comment]
![Captura de pantalla (8)](https://user-images.githubusercontent.com/17751683/114856654-a66b7b00-9de7-11eb-9cb9-e52b5446cc09.png)
the messagebox comes out to me after I enter the outlook account.
https://login.microsoftonline.com/common/oauth2/nativeclient

I have to activate some option in package.appxmanifest

**Comment by sibille** [comment]
> I have to activate some option in package.appxmanifest

This should not be necessary initially. What options did you enable?

To narrow down what's happening and further investigate this issue I need either a Sample App or answers to the following questions: 

- Which framework and project type did you use when creating the project?
- Did you configure the ClientID as mentioned on the developer TODO in the IdentityService?
- What was the supported account type you chose when configuring the ClientID?

**Comment by Javier118** [comment]
Wintows Tempalete stutio UWP C#

Versión de las plantillas: 3.9.20351.2  WTS
Versión del asistente: 3.9.20351.2 WTS

uri reditection: https://login.microsoftonline.com/common/oauth2/nativeclient
version account: only personal account Microsoft
the ClientId is correct in the app.config the  App Uwp

**Comment by sibille** [comment]
Thanks @javier118, "only personal account" is a new option that we haven't tested for when we implemented this. 
We'll investigate what updates we need here.

**Comment by Javier118** [comment]
the option I have is only personal Microsoft account since the App for The Windows 10 MSFT Store

**Comment by vmadurga** [comment]
Hi @Javier118 ,

Try to set the _RedirectUri_ and _Authority_ using the below code in _IdentityService_ class:

```
public void InitializeWithAadAndPersonalMsAccounts()
{
    _integratedAuthAvailable = false;
    _client = PublicClientApplicationBuilder.Create(_clientId)
        .WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")
        .WithAuthority(AadAuthorityAudience.PersonalMicrosoftAccount)
        .Build();
}
```
We will modify our current templates to apply this change in future versions.

**Comment by Javier118** [comment]
Thank You . this work properly

**Comment by sibille** [comment]
Verified in dev-nightly: 
Templates version: 0.22.21111.1
Wizard version: 0.22.21111.1

**Comment by sibille** [comment]
Reopening as we need to apply the updates for Prism templates (Uwp) too.

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21113.1
Wizard version: 0.22.21112.1
