### ISSUE TITLE
Duplicated test execution on build pipeline

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4223]
While looking at #3925 I saw that tests are executed twice on the build pipeline.

For example there should be a total of 20 WACK tests for WPF in the [WACK build pipeline](
https://winappstudio.visualstudio.com/WTS/_build/results?buildId=36786&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=00933dce-c782-5c03-4a85-76379ccfa50a) instead of 40.

The method that returns member data for the xunit test theories is returning duplicates. While the visual studio runner filters them out, the xunit.runner.console does not.

**Comment by sibille** [comment]
Overview of current test number in the different execution sets:

### UWP
**Execution Set Minimum{FrameworkName}**
Testname | CodeBehind     (C# and VB) | MVVMToolkit   (C# and VB) | Prism
-- | -- | -- | --
BuildAndTest_All_CheckWithStyleCop_G2_UwpAsync | 4 | 4 | 4

**ExecutionSet Build{FrameworkName}**
Testname | CodeBehind     (C# and VB) | MVVMToolkit   (C# and VB) | Prism
-- | -- | -- | --
Build_EmptyProject_InferConfig_UwpAsync | 8 | 8 | 4
Build_All_ProjectNameValidation_G1_UwpAsync | 8 | 8 | 4
Build_All_ProjectNameValidation_G2_UwpAsync | 8 | 8 | 4
BuildAndTest_All_CheckWithStyleCop_G1_UwpAsync | 4 | 4 | 4
Build_Empty_AddRightClick_UwpAsync | 8 | 8 | 4
Total | 36 | 36 | 20

**ExecutionSet BuildVBStyle** 
TestName|  All frameworks
-- | --
GenerateAllWithOptionalLoginRunTestsAndCheckWithVBStyleAsync | 16
GenerateAllWithForcedLoginRunTestsAndCheckWithVBStyleAsync | 16
Total | 32

### WPF Tests

Testname | CodeBehind | MVVMToolkit | Prism
-- | -- | -- | --
Build_All_CheckWithStyleCop_G2_WpfAsync | 4 | 4 | 4


Testname | CodeBehind | MVVMToolkit | Prism
-- | -- | -- | --
Build_EmptyProject_WpfAsync | 4 | 4 | 4
Build_All_ProjectNameValidation_G1_WpfAsync | 4 | 4 | 4
Build_All_ProjectNameValidation_G2_WpfAsync | 4 | 4 | 4
Build_All_CheckWithStyleCop_G1_WpfAsync | 4 | 4 | 4
Build_AllWithMsix_G1_WpfAsync | 4 | 4 | 4
Build_AllWithMsix_G2_WpfAsync | 4 | 4 | 4
Build_Empty_AddRightClick_WpfAsync | 4 | 4 | 4
Total | 28 | 28 | 28


Testname | CodeBehind | MVVMToolkit | Prism
-- | -- | -- | --
Build_[FrameworkName]_OneByOneItems_WpfAsync | 80 | 80 | 76

**Comment by vmadurga** [comment]
Verified in Pipeline 
https://winappstudio.visualstudio.com/WTS/_build/results?buildId=36861
