### ISSUE TITLE
Remove FrameworkReference once .NET SDK 5.0.204 or 5.0.300 is available

### ISSUE THREAD

**Issue by vmadurga** [microsoft/WindowsTemplateStudio#4229]
Updating WinUI templates to ProjectReunion 0.5.5 we have to add the following lines in .csproj files:

```
<ItemGroup>            
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />
</ItemGroup>
```

Once .NET 5.0.6 is available, these lines can be removed.

Docs: https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by vmadurga** [comment]
.NET 5.0.6 is now available and Included in Visual Studio 16.9.5
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by sibille** [comment]
As mentioned in https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#known-issues we'll need to maintain the FrameworkReferences for .NET SDK 5.0.203. A fix will be available on  .NET SDK 5.0.204 or 5.0.300.
To make devs aware of this workaround we will add a developer TODO to the csproj file and the App.xaml.cs so it shows on the task list

```xml
<!-- WTS TODO: This is a temporary workaround as Project Reunion 0.5.7 requires WinRT.Runtime.dll version 1.2 or greater. 
Please remove the fixed FrameworkReferences once you updated to .NET SDK 5.0.204 or 5.0.300 (when available) which fixes this. -->
<ItemGroup>            
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.16" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.19041.16" />
</ItemGroup>
```

**Comment by sibille** [comment]
Moving to milestone 4.1 to remove FrameworkReferences once .NET 5.0.7 is available

**Comment by sibille** [comment]
Visual Studio v16.10 was released yesterday and includes .NET SDK 5.0.300, so FrameworkReferences are no longer necessary in VS16.10.

I think we can remove them from our csproj files.

**Comment by vmadurga** [comment]
Verified in pre-release version:
Templates version: 0.28.21147.1
Wizard version: 0.28.21147.1
