### ISSUE TITLE
Add Blank (Advanced) ProjectType for WinUI 

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4244]
We should add an advanced Blank project type for WinUI in Desktop project creation, that provides folder scaffolding, basic services and styles. This advanced blank project type should allow adding pages and features, but not add top level navigation controls as the NavView, to allow the user to build its own navigation pattern.

We currently offer a basic Blank project type for WinUI in Desktop that adds the minimum needed code to get the app started. 
As this project type does not add any folder scaffolding, styles or services users cannot add pages/features that depend on folder structure, services or styles. 

In our UWP and WPF templates the project type Blank adds folder scaffolding and basic styles and services as shown in this UWP sample app: 
![image](https://user-images.githubusercontent.com/24698018/116234380-ce9a9880-a75c-11eb-83b5-fca60d1a1d66.png)
This allows the user to scaffold an advanced app and build its own navigation. 

Tasks: 
- [x] Add templates
- [x] Add docs

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by mvegaca** [comment]
We're working on Blank Advanced project type.

Here is a proposal for **name**, **icon** and **description** for this new WinUI 3 Blank Advanced project type.

![image](https://user-images.githubusercontent.com/5556784/119674510-898d8300-be3c-11eb-9772-d445236c01d8.png)

Regarding the name, we are thinking different options:
- Blank Advanced
- Blank (Advanced)
- Blank Extended
- Blank (Extended)

Happy to hear other suggestions :)

**Comment by sibille** [comment]
We need to add compositions for the Readme.md file that is generated as part of the project, file structure and projecttype need to be adapted to the blank advanced project type.

**Comment by vmadurga** [comment]
Verified in dev-nighlty:
Templates version: 0.22.21173.1
Wizard version: 0.22.21173.1
