### ISSUE TITLE
Add language variations for WinUI vstemplates

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4261]
We have localized vstemplates for App creation in WinUI but not for ClassLibrary, RuntimeComponents and ItemTemplates. 
We should add those

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.21132.1
Wizard version: 0.22.21132.1
