### ISSUE TITLE
Review generated code for BlankWindow on Blank/None project

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4275]
Currently for the BlankWindow we are generating the following code: 

```
  <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
      <Button x:Name="myButton" Click="MyButton_Click">Click Me</Button>
  </StackPanel>
```

On  https://github.com/microsoft/ProjectReunion/discussions/574 @mrlacey suggested replacing this the following code which produces the same output

```
  <Grid>
      <Button x:Name="myButton" HorizontalAlignment="Center" Click="myButton_Click">Click Me</Button>
  </Grid>
```

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No |Yes |

**Comment by sibille** [comment]
We've updated the sample code on the MainWindow and MainPage to be a Grid with a Button as suggested above. 

On our WinUI in UWP templates (which will not be part of WTS release 4.0) we are adding the button only on the first page, all other pages you add from the wizard will only have an empty grid.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Templates version: 0.22.21137.1
Wizard version: 0.22.21137.1
