### ISSUE TITLE
Width of NavigationView and ListDetailsView in WinUI

### ISSUE THREAD

**Issue by suchja** [microsoft/WindowsTemplateStudio#4291]
I'm wondering how it is possible to change the width of the `NavigationView` and the list in the `ListDetailsView` of the generated WinUI desktop application. I cannot find any fixed width or ratio and really would like to have the `NavigationView` a little smaller and the list of `ListDetailsView` larger.

According to [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/2680) it is not (directly) possible to change the window size. Is the width of the `NavigationView` fixed, too?

This question is probably a bit off topic, but information for WinUI is really rare.

**Comment by mdtauk** [comment]
There is a width property you can set.

NavigationView.**CompactPaneLength**
NavigationView.**OpenPaneLength**

ListDetailsView.**ListPaneWidth**

**Comment by suchja** [comment]
Thank you so much! This should have been obvious. Sorry!

**Comment by mdtauk** [comment]
> Thank you so much! This should have been obvious. Sorry!

I think using Length is a poor name choice for discoverability, where you would be searching for **Width**.
