### ISSUE TITLE
Review Binding Failures on Wizard

### ISSUE THREAD

**Issue by vmadurga** [microsoft/WindowsTemplateStudio#4299]
Remove and fix unnecessary Bindings that generate Binding Failures on Wizard.

![imagen](https://user-images.githubusercontent.com/25466105/119009375-57d77080-b993-11eb-9c05-955ce88dcb9a.png)

**Comment by sibille** [comment]
Reviewed in dev-nightly:
Templates version: 0.22.21161.1
Wizard version: 0.22.21161.1
