### ISSUE TITLE
Review Code suggestions on Wizard

### ISSUE THREAD

**Issue by vmadurga** [microsoft/WindowsTemplateStudio#4301]
Review code suggestions on Wizard, such as:

- Make fields readonly
- Use pattern matching
- Simplify object initializations
- Redundant and unnecesary assignments
- Simplify interpolations
- Do not use Count when Any can be used
- Use nameof to express symbol names
- Deconstruct variable declarations
- Use Count/Length property instead of Count()
- Simplify conditional expressions
- Remove unnecessary suppressions
- Remove unnecessary assignments
- Remove unused methods
- Remove unused function parameters
- Remove not access fields
- Offer async method options
- Remove unused directives

**Comment by sibille** [comment]
Verified in dev-nightly:
Templates version: 0.22.21167.1
Wizard version: 0.22.21167.1
