### ISSUE TITLE
Unify SolutionWizard files

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4304]
We currently have 7 classes that extend SolutionWizard to initialize the platform, language and appmodel for the SolutionWizard depending on the entry point.
We can set those parameters on the vstemplates as CustomParameters.

**Comment by dgomezc** [comment]
Reviewed in dev-nightly:
Templates version: 0.22.21174.1
Wizard version: 0.22.21174.1
