### ISSUE TITLE
What does "Layout" mean in the wizard details page?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4305]
**Describe the bug**

The wizard details pages includes an entry for "Layout" but it is not clear what this is.
The term "Layout" isn't used elsewhere in the wizard.
The items linked to for a "Layout" can be of different types. (See screenshots below)

It's not clear what a "Layout" is meant to be or what this is supposed to communicate to the user.

**Expected behavior**

- Terms should be used consistently through the UI.
- Terms should be understandable to the user.

**Screenshots**

WinUI Desktop project type example - showing a "layout" that is a "Feature"
![image](https://user-images.githubusercontent.com/189547/119326563-ed1b8300-bc79-11eb-9034-0ba11a6042de.png)

UWP project type example - showing a "layout" that is a "Page"
![image](https://user-images.githubusercontent.com/189547/119326688-14725000-bc7a-11eb-91ed-3598a43ec1c9.png)

**Additional context**

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes | Yes |

**System**

- **VS Version:** 
- **WinTS Wizard Version:** 
- **WinTS Template Version:** 
- **Windows Build:**

**Comment by sibille** [comment]
Thanks for reporting, I think you are right, we should be clearer here. Layout refers to templates that are added by default to the Wizard. 

Would "Default layout" or "Default templates" be a better term?

For more (technical info) on Template Layout see https://github.com/microsoft/CoreTemplateStudio/blob/dev/docs/templates.md#template-layouts
> Template Layouts
> Project templates can define a default layout of pages/features to be added to the wizard. To do so, you need to add a Layout.json file within the .template.config folder.
> 
> By using template layouts, you can determine which templates are automatically added to a certain project type and if those templates are mandatory or can be removed. In other words, layout definition provides a way to pre-configure templates associated to a certain project type.

**Comment by mrlacey** [comment]
So, "Layout" is an internal piece of terminology that has no direct meaning to the user. Therefore, the term should not be used in the UI.

I think "Includes" is a better label here as it is saying "by selecting this option the wizard will also **include** these other items."

**Comment by vmadurga** [comment]
Verified in dev-nightly:
Templates version: 0.22.21174.1
Wizard version: 0.22.21173.1
