### ISSUE TITLE
Update WindowsCommunityToolkit packages to the latest versions

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4306]
**Is your feature request related to a problem? Please describe.**

The latest version of the Comunity Tooolkit packages aren't being used in the generated apps.

Where possible:
-  should update to the latest versions (v7.0.2) is out.
- should use the versions with the new CommunityToolkit prefix. 

Will need to investigate the implications of changing the names of versions used in previously generated apps but I don't think there should be any.
Getting this change in before the WinUI version is officially released will help avoid any possible future confusion due to future changes.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| Yes | Yes  | Yes |

**Comment by sibille** [comment]
I think this is just updating to version 7.0.2. There are still separate packages for WinUI and UWP as mentioned in https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3295.

**Comment by mrlacey** [comment]
So if you don't want to start adopting the use of the new package route now, when will/should the change be made?
Why wait?

**Comment by sibille** [comment]
Not sure if I misunderstood something here: What's your suggestion? Updating the Microsoft.Toolkit.Uwp.* packages used in UWP templates to CommunityToolkit.WinUI.* packages or something else?

> ⚠ Important Note ⚠
> When Project Reunion 0.5 releases, we will ship packages to NuGet for the Toolkit, compatible with it like these previews. However, they will be under a different namespace/package identity of CommunityToolkit.WinUI.*. There'll be corresponding packages for each Microsoft.Toolkit.Uwp.* package. The version of the WinUI packages will align to the same version of the current UWP packages that contain the same features. Therefore when we ship 7.1 of the UWP packages, there'll be an equivalent set of 7.1 packages for WinUI 3 as well. This will continue until a time in the future we feel the community can move to WinUI 3 in full, at which point we will deprecate our UWP packages and move to WinUI 3 only.

What I read from the above comment was that we should use the Microsoft.Toolkit.Uwp.* packages for UWP templates and CommunityToolkit.WinUI.* packages for WinUI templates.

Actually, for example the CommunityToolkit.WinUI.UI.Controls has a dependency on net5.0-windows10.0.18362, so we can't use this for UWP. 

For the MVVM package I agree, we should switch to the CommunityToolkit.Mvvm package on WinUI for consistency.

**Comment by mrlacey** [comment]
@michael-hawker can you confirm that you recommend using the versions with the "CommunityToolkit." prefix where possible?

**Comment by michael-hawker** [comment]
For UWP projects, stick with `Microsoft.Toolkit.*` as our packages still reference the .NET versions of those, so trying to mix and match the .NET packages with the `CommunityToolkit.*` ones will be tricky. Ideally, when WinUI 3 is ready, you just swap everything out still in one go.

For WinUI, @sibille is correct that all those move to the `CommunityToolkit.WinUI.*` ones and similarly should use the new `CommunityToolkit.*` .NET packages to align.

If you were to start a pure .NET project without UWP, we'd recommend using the `CommunityToolkit.*` ones, as then you won't have to migrate when we stop shipping them in the future once we move from UWP to WinUI 3 longterm (next year?).

Bits wise, the .NET packages are effectively the same. It's really just about if packages in the UWP/WinUI 3 space take dependencies on the lower ones, but generally you get those transitively anyway.

**Comment by sibille** [comment]
Thanks for the quick answer @michael-hawker. 
PR #4310 switches to the CommunityToolkit.* MVVM package for WinUI and updates all CommunityToolkit.* packages to the latest version

**Comment by mvegaca** [comment]
Verified in dev nightly
Templates version: 0.22.21147.1
Wizard version: 0.22.21147.1
