### ISSUE TITLE
Poor grammar in TODO comments

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4307]
**Describe the bug**

The following is included in a generated WinUI3 app

```cs
    // TODO WTS: Please remove the fixed FrameworkReferences from the {appname}.csproj file
    // once you updated to .NET SDK 5.0.204 or 5.0.300.
    // For more info see https://docs.microsoft.com/windows/apps/winui/winui3/#known-issues
```

the second line of the above would read better if it was 

`    // once you have updated to .NET SDK 5.0.204 or 5.0.300.`

or 
`    // after updating to .NET SDK 5.0.204 or 5.0.300.`

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**System**

- **VS Version:** 
- **WinTS Wizard Version:** 
- **WinTS Template Version:** 
- **Windows Build:**

**Comment by sibille** [comment]
Closing this as the comment was removed in #4229
