### ISSUE TITLE
WinUI3 templates for the WebView page have some issues

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#4308]
**Describe the bug**

There appear to be a few issues with the WebView Page option for WinUI3 apps. 

**Expected behavior**

The convention for displayed template names is to use the name of the control when that is all that is included in the generated page. Following this convention, the displayed name of the template should be "WebView2" and not "WebView".

There is nothing in the details (see image below) that indicates this uses the WebView2 control and should be treated as such.

The generated code includes a comment that "Microsoft.UI.Xaml.Controls.WebView2 is for evaluation purposes only and is subject to change or removal in future updates." but no version of this notice is displayed in the wizard. That this is an evaluation only control is potentially very important information for a person creating an app and should be made obvious in the wizard.

The link text "Is the Web view control right for you?" goes to a page that doesn't answer the question. I appreciate that the text from this link was copied from the UWP version of the template but when changing the link, a consideration for changing the link text should also have been made.

Using WebView2 in an app has potential implications on the distribution of that app as it has external dependencies on the WebView2 Runtime. These are not mentioned in the wizard or generated code. The recommendation for using the WebView2 control in production is to include the dependency on the runtime but the generated code does not do this. This seems to be in conflict with the aim of WinTS in creating a complete working, deployable app.

**Screenshots**

![image](https://user-images.githubusercontent.com/189547/119332242-3bcc1b80-bc80-11eb-8107-3d616375af34.png)

**Additional context**

The above is based on only looking at the C# templates. I haven't looked at the C++ ones.

Applies to the following platforms:
| UWP              | WPF              | WinUI           |
| :--------------- | :--------------- | :---------------|
| No | No | Yes |

**System**

- **VS Version:** 
- **WinTS Wizard Version:** 
- **WinTS Template Version:** 
- **Windows Build:**

**Comment by sibille** [comment]
Thanks for reporting!

We'll stay with WebView as template name, but update the description to say WebView2 to be more explicit here.

WebView2 is no longer in preview, so we should remove the developer TODO comment.

We'll also add a comment pointing to the docs on distributing apps with WebView2 (https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)

**Comment by sibille** [comment]
Verified in pre-release version:
Templates version: 0.28.21147.1
Wizard version: 0.28.21147.1
