### ISSUE TITLE
Create a SuspendAndResume feature sample

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#432]
After fixing #422 we realize that a sample to explain how to use SuspendAndResume feature on different frameworks would be really valuable.

**Comment by crutkas** [comment]
Github page + link in docs.

**Comment by mvegaca** [comment]
Documentation and samples created on #987

**Comment by mrlacey** [comment]
For reference, the new doc can be seen at https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/features/suspend-and-resume.md

**Comment by mrlacey** [comment]
@mvegaca This new documentation is using a new (and different) folder structure for image resources.

You've created this new folder
https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/docs/features/resources
but all the other docs put their related image resources under
https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/docs/resources

Please move the new image files to follow the existing standard.

**Comment by mvegaca** [comment]
Thanks Matt, updated on #997

**Comment by mvegaca** [comment]
Samples and documentation in dev, close issue
