### ISSUE TITLE
Review and update nuget packages in WTS

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsTemplateStudio#4326]
We should review and update the nuget packages used in the extension, emulator, wizard and tests.

**Comment by mrlacey** [comment]
updating the NuGet packages in the extension is something that should happen with every release. 
Is there a checklist for all the things that happen before a release?

**Comment by sibille** [comment]
https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Before-Release

**Comment by sibille** [comment]
Verified in dev
