### ISSUE TITLE
Document link is broken

### ISSUE THREAD

**Issue by saf-itpro** [microsoft/WindowsTemplateStudio#4335]
On the third bullet `WinUI 3: Blank, Navigation Pane` of the `Project Type` section the following link for `Navigation Pane` is broken:

https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WinUI/projectTypes/navigationpane.md

**Comment by sibille** [comment]
Thanks for reporting!

**Comment by sibille** [comment]
Verified in dev
