### ISSUE TITLE
Proposal: Add a way for ViewModels to react to navigation

### ISSUE THREAD

**Issue by tomzorz** [Microsoft/WindowsTemplateStudio#435]
Hi everyone!

One crucial thing that seems to be missing for me in WTS is a built-in way/pattern to react within 
ViewModels to navigation. (OnNavigatedTo, and OnNavigatingFrom)

The reasons why this is important:

- many ViewModels need to load data after they were created to populate the content in the View: right now there's no clear way to do async work aside from doing an `async void` method from the constructor which we all know is a bad idea
- it'd be great if ViewModels (especially those that deal with data-entry) could cancel accidental navigation requests

There are many ways to implement this:

- Add optional interfaces on ViewModels (the PRISM way), eg `INavigationAware`. We would check if the page had a ViewModel that implements this interface, and call in from the events mentioned earlier
- Create a custom `ViewModelBase` that has abstract methods that get called from the events mentioned earlier

I suggest that we preferably go with the first one (plus this pattern could be extended in many ways, eg. window title setter interface etc...). This code should live somewhere near the App/Frame/NavigationService instead of the page codebehinds.

**Comment by mrlacey** [comment]
@tomzorz It's not clear what you're actually asking for.  
WTS currently supports two MVVM frameworks and a code-behind implementation too.
Obviously, we can't add something like this to the code-behind version, we're not going to change MVVM Light, and the point of MVVM Basic is to be as simple an implementation as possible so adding this would go against that.

How view models interact with views works in many different ways and there are reasons for different uses at different times. There are also many developers with differing strong opinions about how this should work.  
There are also other frameworks that already have ways for implementing what you're asking or variations thereof. PRISM, as you mentioned, but also Caliburn and MVVMCross have similar built-in capabilities.

I think you might just get what you want if you wait for the [upcoming PRISM support](https://github.com/Microsoft/WindowsTemplateStudio/issues/304).

In terms of ViewModels canceling navigation requests, that only makes sense in terms of VM to VM led navigation. Support for this is determined, predominantly, by the MVVM Framework in use. Again, I suggest you wait for, or contribute to adding, PRISM support.

**Comment by tomzorz** [comment]
@mrlacey All right, your points make sense - I'll probably wait for PRISM :)

**Comment by crutkas** [comment]
@tomzorz you want to help out that team and get Prism or Template10 in?  :)

**Comment by tomzorz** [comment]
@crutkas I'd love to, but I'm afraid I won't have time until July 😞
