### ISSUE TITLE
title bar extension, back button overlaps the menu button

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#437]
when I try to extend the app into title bar it works but the back button in title bar overlaps the hamburger menu button. I tried setting padding to the HambugermenuTemplate property but it pushes the fontIcon out of view. What can be solution of extending into titlebar without disturbing hamburger button?

**Comment by mrlacey** [comment]
@touseefbsb as with any UWP app, not just WTS created ones, once you extend into the title bar you become responsible for back button.

**Comment by touseefbsb** [comment]
oh, can you please give me a tip regarding that? I mean how to deal with this scenario?

**Comment by mrlacey** [comment]
@touseefbsb as with any request for help with code, showing what you've already tried is always useful.  
There's a good blog post I've used for reference before at http://www.joeljoseph.net/customizing-title-bar-and-status-bar-in-universal-windows-platform-uwp/
Non-WTS specific issues are also better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/uwp) or the [MSDN forums](https://social.msdn.microsoft.com/forums/windowsapps/en-us/home?forum=wpdevelop).

**Comment by touseefbsb** [comment]
thnkyou :)
