### ISSUE TITLE
Make support Installing on Visual Studio 2022

### ISSUE THREAD

**Issue by SamParkLCF** [microsoft/WindowsTemplateStudio#4381]
Currently, it can not be installed in visual studio 2022 as it was not designed to be installed  x64 based visual studio

**Comment by mrlacey** [comment]
It's not that it's not designed to be installed on VS2022, it's that some of the libraries it depends on don't yet support working with VS2022.
support will come in time.

**Comment by p2pbsh** [comment]
@mrlacey @sibille  Any updates on this? I really like this extension, my go to when firing up a new app, a real shame its not working with VS2022 with the final release now upon us.

**Comment by sibille** [comment]
@marb2000 do you have any updates on this?

**Comment by michael-hawker** [comment]
🦙 Duplicate of #4353

**Comment by cwilliams145** [comment]
Duplicate of #4353
