### ISSUE TITLE
Store Notification throwing Async await warning

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#442]
HandleInternalAsync is throwing an async await warning.

Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.	App99	C:\Users\crutkas\Documents\Visual Studio 2017\Projects\App99\App99\Services\StoreNotificationsService.cs	20	Active

**Comment by mrlacey** [comment]
I also get this error when adding the Store Notifications feature

> The SDK "Microsoft.Services.Store.Engagement, Version=10.0" depends on the following SDK(s) "Microsoft.VCLibs, Version=14.0", which have not been added to the project or were not found. Please ensure that you add these dependencies to your project or you may experience runtime issues. You can add dependencies to your project through the Reference Manager.

**Comment by mvegaca** [comment]
Fixed on the following PR

[Fix async warning](https://github.com/Microsoft/WindowsTemplateStudio/pull/475)

**Comment by ralarcon** [comment]
Verified in v0.14.17172.65001; templates v0.14.17172.1
