### ISSUE TITLE
Master Detail should hook into shared data

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#444]
Looking at the project, looks like master detail does not use the the shared data list.  This is from a 6/9 snapshot on dev branch

**Comment by mrlacey** [comment]
@crutkas got a repo? I just built a CodeBehind NavPanel app with dev nightly build versions 0.14.17158.65001 & 0.14.17160.65001 and it worked fine.

**Comment by crutkas** [comment]
lemme grab my laptop.  Maybe i lied and had an earlier snapshot in time.  thought it was an up-to-date pull

**Comment by crutkas** [comment]
i pulled directly from the dev branch with both CB and MVVMLight and both had charts / grid using sample data but master detail was just the basic 2 items with lorem ipsum.   I verified with getting latest with same behavior.

Let me blow away my branch and will try the nightly as well.

**Comment by crutkas** [comment]
nightly has same behavior, Master detail has 2 lorem impsum, not pulling data from the sample data

**Comment by crutkas** [comment]
Ok, i see what is going on here now that i'm seeing the source code :)  I don't think how stuff is implemented what I envisioned for the sample data.

**Comment by mrlacey** [comment]
@crutkas is this more what you were after: https://github.com/Microsoft/WindowsTemplateStudio/tree/Issue444-SingleSampleDataSource

**Comment by crutkas** [comment]
Yes but with an image of some sort for master detail.  Is the data northwind or just random stuff you generated?

Does anyone feel that this is not a good idea?

**Comment by gcaughey** [comment]
I'm a big fan of Northwind. ;)

**Comment by mrlacey** [comment]
@crutkas data came from Northwind. I opened Access 2016, selected the Northwind 2007 Sample and copied some stuff.
Suggestions for images to use would be welcomed.

**Comment by mrlacey** [comment]
@crutkas got any suggestions for extending this further or an appropriate image to add? Or can this be closed?

**Comment by mrlacey** [comment]
@crutkas can this be closed? or do you have an idea for an image?

**Comment by crutkas** [comment]
i would like image due to the connected header personally.  IMO could be the same image.

Lets close this out and open a new one.

**Comment by mrlacey** [comment]
Could use Text for the connected header. But that can be discussed as part of fluent work.
Closing for now
