### ISSUE TITLE
Why do we need MasterDetailDetailControl?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#447]
Why can't the content in `MasterDetailDetailControl` go directly in `MasterDetailDetailPage`?

Having the separate embedded control appears to just add unnecessary extra complexity.

**Comment by mvegaca** [comment]
This is a solution to have the detail layout on the same Xaml code and share this between MasterDetailPage and DetailPage.

**Comment by mrlacey** [comment]
Oh, I see what you're doing now. In the past, I've just used a single page and intercepted back navigation and suppress unwanted navigation to create the same appearance on desktop & mobile/narrow.
