### ISSUE TITLE
Will this template provide INavigatedAware style NavigatedTo and NavigatedFrom in viewmodel?

### ISSUE THREAD

**Issue by nidilong** [Microsoft/WindowsTemplateStudio#449]
and if possible,  you can provide if view/viewmodel is present view/viewmodel.

**Comment by mrlacey** [comment]
@nidilong it is not the intention that the "MVVM Basic" implementation will support this but we're in the process of adding support for PRISM (#304) and Caliburn.Micro (#438) which do both have built-in navigation related handling in view models.

**Comment by nidilong** [comment]
@mrlacey thank you for your reply!
