### ISSUE TITLE
Store push notifications 

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#45]
Store push notifications are planned to be added but we need to resolve a positive experience for the end user.  Right now the install experience leaves a bit to be desired.

**Comment by crutkas** [comment]
https://docs.microsoft.com/en-us/windows/uwp/monetize/microsoft-store-services-sdk#install-via-nuget

**Comment by ralarcon** [comment]
With the PR #427 we are adding this feature back. We have used the configuration mentioned to install the Store Services SDK via nuget and tested it in different installations of VS with success. Anyway it would be something left so we invite everyone to check this works fine.

**Comment by ralarcon** [comment]
By the way, this will be delivered in the next Nightly Build.
