### ISSUE TITLE
XamlParseException when launching VsEmulator

### ISSUE THREAD

**Issue by CarteKiwi** [Microsoft/WindowsTemplateStudio#450]
Hello,

I have a XamlParseException when launching the VsEmulator for the first time:
![image](https://user-images.githubusercontent.com/12309245/27014393-14bd3d20-4ef8-11e7-806a-12bf8e3d8121.png)

I followed the doc: opened UI.sln, VsEmulator as "StartUp". A window is displayed at launch, with 2 links: "new project" and "configure version", click and voilà...

Clicking on "new project" cause exception in "ShowNewProjectDialog()" method.
Clicking on "configure version" cause same exception in "ConfigureVersions()" method.

Am I missing something ?

(Using VS 2017 13.2 (26430.12) on Insider Preview 16215)

Thanks.

**Comment by mrlacey** [comment]
I can't repro this (dev or master branches) when running on 15063.
I get different errors and VS is very unstable for me on the latest Insider Preview, so I'd attribute the issues to preview platform instability unless anyone else can repro.

**Comment by CarteKiwi** [comment]
Ok, wait'n see :)
Thanks

**Comment by crutkas** [comment]
asking VS team if this is a known issue.

**Comment by CarteKiwi** [comment]
This exception is due to the XAML Debugging tools.
Have to disable it. [Read this.
](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1732fe72-30ce-4cdb-b06f-a4becf0f2d72/when-debugging-i-cannot-open-any-forms-in-vs-2017-windows-10-build-16215?forum=wpf&prof=required)
