### ISSUE TITLE
Create issue template for WTS github

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#453]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/ 

I can take point on this but want an issue to keep me honest

**Comment by mrlacey** [comment]
@crutkas do it 😜

**Comment by crutkas** [comment]
this needs to be in master before i can take effect i believe

**Comment by mrlacey** [comment]
Any objections to adding a Pull Request Template too? (I have some thoughts on what should go in it. 😉)

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by crutkas** [comment]
100%

**Comment by crutkas** [comment]
100% please do, great idea

**Comment by crutkas** [comment]
we did this :)
