### ISSUE TITLE
REST Model Class generation

### ISSUE THREAD

**Issue by hannespreishuber** [Microsoft/WindowsTemplateStudio#454]
I am didnt get the story, how to create a viewmodel without the model classes. Did I miss some feature?

My proposed workflow.
Add some service URL
generate model classes
generate httpclient code für CRUD (option)

**Comment by mrlacey** [comment]
I don't understand how what you're describing relates to WTS. Can you expand on what you're trying to achieve, what you did, and how the result differed from what you're after?

**Comment by crutkas** [comment]
@hannespreishuber I think you're asking for a new feature, is it you want us to help generate code via a service URL?

if you feel you'd communicate better in your native language, I can get someone to help translate.  (looks like German based on your profile)

**Comment by hannespreishuber** [comment]
@crutkas I wondering that this kind scaffolding is not in the box, perhaps I have not seen how to do it. But from @mrlacey 's post, I learned there is nothing like that.

And to be clear, I do not understand: what is the purpose of a viewmodel generator without the model classes.

**Comment by crutkas** [comment]
@hannespreishuber we never stated support for what you are proposing.  Our goal is to help stub out the app quicker for you to get going versus the older templates where they were static.

We don't know what you're model exactly is but have to wire up some parts.  We do wire in some sample data depending on what you selected but try to keep that as contained as possible to make sure you as the dev have minimal amount of code removal and is as straight forward as possible.

this could get sticky as a feature as well since each framework could need the model generated differently as well.

if there is something we're doing and you feel it shouldn't be done, please be very crisp and provide the wizard / template version with the permutation you used to create the app and we'll see if it makes sense.  We did work directly with community to vet what was created so we feel pretty confident we hit a happy middle ground of not enough and not too much.

**Comment by crutkas** [comment]
@hannespreishuber do you feel this is something we *should* be doing?

**Comment by mrlacey** [comment]
Having done a bunch of work previously with code generated from random API endpoints, there's a lot to make me nervous about trying to add something like this.

The tool would need to handle:

- Endpoint authentication
- Custom headers
- Inconsistent Error responses
- Responses that vary in their format based on content
- Responses that can't automatically be deserialized to 
- Responses that aren't versioned consistently
- Versioned APIs that break API contracts over time
- Multiple endpoints that return variations on the same data but in slightly different formats that can't be automatically and reliably combined into a single POCO
- Responses that can't be deserialized without custom converters.
- APIs with version definitions that are automatically regenerated and hide changes in data structures.
- APIs which misuse HTTP responses codes and headers
- It wouldn't handle sending of data, just getting it and so would only do half the job.
- Handling of issues in the above would require potentially non-trivial amounts of code and we'd get into the realm of providing lots of code which assumes a specific way of working.
- Handling retries and partial data responses.
- Version changes to the endpoints and responses in the future.
- Automatic POCO generation typically relies on less specific types as can't be certain on formats, ranges, and possible response variations, which can result in classes far from being optimal.

Individually most of these are manageable but together things can get *very* complicated. (Yes, the above is a quick, from memory list of issues from multiple past projects.)

I know for simple cases there's an argument for a basic API support (App Studio has something) but it would only be basic scenarios we could cover without a lot of work that would be going way beyond the original aims of WTS. Most serious apps use more than a single endpoint and so managing multiple endpoints becomes a lot more complicated.  
To me, this really raises the question of how much should we be doing to get people started, versus building the app for them?   
There are third party tools that will do this for people who really want it.

**Comment by hannespreishuber** [comment]
wow, so many questions
1) there have been services like that, some Wizard, some uri, some code you extend
(WCF Data Services, also VB6, EF model wizard, Azure mobile Apps, ASp.NET Webforms DataControls)
2) doen't overengineer, CRUD is enough
3) keep the generated code easy, the model classes (like EF), a tiny Viewmodel based on X:bind syntax, 
3b) perhaps a base class for the interface inotify... but no best pattern bla abstraction classes
3c) Json.net

why you should doing that. It lowers the entry barrier for the newbie,

**Comment by mrlacey** [comment]
Yes, there are tools/services that already do this. It's not a good use of our time to recreate something that already exists.

The barrier to entry is already really low for generating classes (your original request). Visual Studio will do this for you if you just copy the API response into the clipboard and then "Paste as Classes".
![image](https://user-images.githubusercontent.com/189547/27280639-8ec56dfc-54e0-11e7-87d9-af05e2a42ebe.png)
If you want something more than just POCOs try [Swagger CodeGen](https://github.com/swagger-api/swagger-codegen).

**Comment by hannespreishuber** [comment]
@mrlacey  I know "paste special" and also swagger (a little bit). But I also know hot to copy paste some XAML to get a prototyped UI. 
Dont get me wrong, I like the concept and now also the idea "help stub out the app quicker". But app without data is in 99% nothing.
On feature idea regarding the "rest crud mvvm" generator is generating design data from rest and include it :-)

**Comment by mrlacey** [comment]
We're not trying to build a whole app though. From the project principles:

2. Generated templates are a starting point, not a completed application.

**Comment by crutkas** [comment]
@hannespreishuber My gut is this is outside Template Studio scope.  I know that this would be super powerful but that is something that would take a heavy tax on the team.  We have a philosophy of doing enough, but not too much.  This causes us to get into tons of sub screens and how to do data in each framework, auth for services, ... (look at @mrlacey list) . It adds tons of complexity to the wizard and user flow not to mention bubbling that data back to the templates so it is wired back in..

Are there other file->new systems that can do just this?  Wouldn't this be more powerful built into Visual Studio?

**Comment by mrlacey** [comment]
Closing this as we have no plans for this in the foreseeable future. Although, we may revisit this in relation to #396 in terms of remote data sources.
