### ISSUE TITLE
Localization added into wizard

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#46]
The system currently is localized.  However, the wizard needs an improved experience for adding new languages.  Due to the v0.1 experience, we're moving this out to focus on polishing the experience.

**Comment by mrlacey** [comment]
My interpretation was that this issue was about localizing the tool. So, if, for example, I have a language pack for Visual studio installed, the wizard can be in that language too.
This comes with two parts.
1. Localizing the UI of the Wizard.
2. Localizing the text displayed from template config files.

**Comment by crutkas** [comment]
This was about integrate somehow the toolkit for generated code.

@mrlacey you're raising a 100% valid issue that with how our data is currently being housed could cause issues to localize the wizard itself

**Comment by mrlacey** [comment]
So I'm clear, this is about having multiple languages selectable in the wizard and including them in the generated code.?

**Comment by ralarcon** [comment]
So the idea here is to allow the user to define the preferred locale for the generated app, isn't it?

If we allow users to select (somehow) the target language (consider es-es), then we need to have the current "en-us resources" translations for "es-es" or we just generate the "en-us resources" + "es-es" but without translation?

Initially we had a "Localization" feature which allowed to include the  resources for a certain language, but it wasn't so clear how to use the feature... we can revisit this and define the approach based on the requirements.

**Comment by mrlacey** [comment]
If including multiple languages must be able to choose, in the wizard which is the default language in the project.

The wizard will default to just having en-US selected by default.
 
I think we should supply RESX files for all languages we offer. Initially, we can generate these with MultiLingual Toolkit and then accept contributions to improve them as appropriate.

This prompts another question: Which languages do we make selectable? (All supported in UWP or just ones we have translations for?)

I think we should start with a few. The most popular would seem obvious. @crutkas can you find out the breakdown of the most popular languages from the store team?
I think the list in the tool should be limited to the languages we provide RESX files for and include a link to docs showing how to add more languages once the project is generated.

**Comment by crutkas** [comment]
One idea is we just have a developer to-do and just point to the toolkit and verify we work with it and call this done.  I think if we auto gen, we may be doing the "too much" bar

https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit

@mrlacey tracking down popular languages.

**Comment by crutkas** [comment]
the primary chunk of work is targetted for 1.1 but true localization won't hit until maybe august

**Comment by ralarcon** [comment]
Close in favor of #322
