### ISSUE TITLE
multiple view support

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#466]
CFU might bring multiple instances of the app as well ( not sure about this though ) but anyways multiple views still exist in UWP and it would be nice if their is a service/Helper created just for sole purpose of managing multiple views for the app in some basic scenarios. I just think lot of people might need this service.

**Comment by crutkas** [comment]
dup of #241

**Comment by touseefbsb** [comment]
thankyou for informing :) btw do you have any time frame in which next version might be released?

**Comment by crutkas** [comment]
maybe 6/22 pending us not finding any major bug.
