### ISSUE TITLE
code analysis: catching back to back if-statements

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#467]
C:\Users\crutkas\Source\Repos\windowstemplatestudio\code\src\UI\ViewModels\MainViewModel.cs

low pri, betting one of the global suppressions is not catching this.  i feel like it should have caught this with back to back if statements:

```
           if (!_templatesReady)
            {
                return false;
            }
            if (_hasValidationErrors)
            {
                return false;
            }
            if (string.IsNullOrEmpty(ProjectTemplates.HomeName))
            {
                Status = new StatusViewModel(StatusType.Error, StringRes.ErrorNoHomePage);
                return false;
            }
```

**Comment by mrlacey** [comment]
That's a bit beyond what StyleCop is designed for.
Even ReSharper doesn't suggest anything about this code to me.
I don't know of any tools that would pick this up? If it's a big issue for you, you write a Roslyn Analyzer for it but it looks non-trivial to reliably suggest a fix for this.

To me, this is an example of the type of thing that manual code reviews are good ar getting. By all means fix individual issues like this when you see them but please don't make any solution wide changes for things like this. They'd be likely to make merging of any branches very complicated as there would likely be masses of conflicts.  
I'm all for a tidying up of code generally but it has to be done when there aren't lots of branches we'll want to merge. And that's not likely to happen any time soon.

**Comment by crutkas** [comment]
agreed :(

**Comment by mrlacey** [comment]
close?
