### ISSUE TITLE
Why is TogglePane control broken out like no other control?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#468]
TogglePane has a xaml, cs and member.cs file.  I saw another instance of this as well.

Feels like a new coding style principle was added that differs from other controls.

**Comment by mrlacey** [comment]
@mvegaca can you explain the reason for the change.

I'd also like to call out the use of regions. I expect to remove the suppression of [SA1124](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1124.md) soon and so these will go anyway.

>A violation of this rule occurs whenever a region is placed anywhere within the code. In many editors, including Visual Studio, the region will appear collapsed by default, hiding the code within the region. It is generally a bad practice to hide code, as this can lead to bad decisions as the code is maintained over time.

**Comment by mvegaca** [comment]
This is a practice that I use to split the code when there are a lot of members, I'll change it to align with code styling.

**Comment by mvegaca** [comment]
Fixed on following PR

[https://github.com/Microsoft/WindowsTemplateStudio/pull/474](https://github.com/Microsoft/WindowsTemplateStudio/pull/474)

**Comment by crutkas** [comment]
@mvegaca this was me asking why.  I'm fine with it but we should be consistent.  If you guys feel this is more maintainable and readable, 100% lets do it this way but then lets create issues for updating the other controls.

**Comment by mvegaca** [comment]
This is an approach that I like when a  control grows a lot, and is easier to have a  lock up of different parts on the implementation.

At this moment, we have no controls with too much logic to implement this code styling, but we could think about that in the future.

In Windows App Studio we had a shell control with a lot of funcionallity and we used this style.
[ShellControl](https://github.com/wasteam/waslibs/tree/master/src/AppStudio.Uwp/Controls/ShellControl)

**Comment by mrlacey** [comment]
YAGNI
