### ISSUE TITLE
code analysis to catch missing header?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#469]
is this possible?  I've seen a few files that were missing a header.  would be awesome if we could flag files via code analysis missing this.

**Comment by mrlacey** [comment]
The SA1633 suppression was hiding this because we're not using headers in the format StyleCop recommends. Have made a PR to make sure all files do have the standard copyright header, even if it's not the "proper" XML one.

**Comment by crutkas** [comment]
That PR caught them but would like to be proactive on new files

This would only be needed for our engine however.

**Comment by mrlacey** [comment]
Bam. added to PR and now the inclusion and content of file copyright headers will be enforced by StyleCop.

Although, I have had in the back of my mind the idea of having a WTS feature which could add copyright headers to all generated files.....

**Comment by ralarcon** [comment]
We just need to decide what is the most appropiated but it is easily to be done by implementing a global Post-Action to be executed over .cs & .xaml files instead of editing all template files and adding the header there...

**Comment by mrlacey** [comment]
@ralarcon yes that's what I was thinking but you're now discussing something separate from the original issue. I've opened a new issue (#477) to discuss this further and gather feedback.

Closing this as now implemented
