### ISSUE TITLE
Generated pages do not match layout guidelines

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#472]
Page content does not match RS3 guidelines for the size and position of the content. It should.

**Comment by crutkas** [comment]
which page?

**Comment by mrlacey** [comment]
Based on the red lines I have:
- Tab/pivot page side margins
- Master-Detail page side margins
- Whitespace around title on all pages with title text
- Side margins on all pages with content
- Pages also don't adjust margins as they should for display on phones/small screens
- Settings page, the link should not be underlined
- Settings page, body text size is wrong

**Comment by mrlacey** [comment]
Need to reevaluate if this is still relevant based on styling updates done for FCU & #1183

**Comment by mrlacey** [comment]
Actually, it looks like #1229 supersedes this as it's doing the same thing.
Closing as duplicated.
