### ISSUE TITLE
Pages and features templates order

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#479]
Currently we are not using order in pages and features, the default is alphabetical order by template name.
I' suggest set the following templates order for pages and features:

**Pages**
- Blank
- Master / Detail
- Tabbed
- WebView
- Settings
- Map
- Chart
- Data grid
- Media player

**Features**

_Application lifecycle_
- Setting storage
- Suspend and resume

_Background Work_
- Background work

_User interaction_
- Live tile
- Toast notifications
- Azure notifications hub
- Store notifications

What do you think about this order?
We can include it for 1.2.

**Comment by mrlacey** [comment]
@crutkas do you have telemetry on the page and feature usage to inform the order?

**Comment by mvegaca** [comment]
I've tried to order using following criteria:

_Microsoft Templates_
- Relevant
- Basic

_Community_
- Relevant
- Basic


For example. It make sense that Toast Notification be placed before Azure Notifications

**Comment by ralarcon** [comment]
We have telemetry but, sometimes, just the placement drive user decisions. My understanding here is that maybe it is interesting for us to order the templates in a certain way... or not. :-)

**Comment by mrlacey** [comment]
The order seems fine.   
While in general, the order of items can influence what is selected I'd not jump to that conclusion here without properly testing it. Without statistical evidence to back it up you're claiming that people using the tool aren't choosing the most appropriate pages for their app but are being influenced by the available pages and the order they're in. If that's true it's concerning and should be explored further.  
This order could potentially be seen as arbitrary as there's nothing obvious to the person using the wizard to explain the order. Not such an issue now but could affect how easy it is to find what someone is looking for as the list grows.  Yes, I know #14 & #282 may change this though.
If we have data then at least consult it. If not, then why's it being captured?  
It'd be good to clearly define the difference between "Relevant" and "Basic" to help understand where future pages should be added.

**Comment by mvegaca** [comment]
I'm not sure features and pages should be ordered based on usage by default (maybe we can add a way to allow users to order the templates based on popularity). 

Regarding relevant / basic I was thinking:

**Relevant**
A template is more relevant when there are more application types targets to use this template, for example, Blank page make sense to add to 100% of project types and Chart page only on heavy data analytics projects.

**Basic**
Talking of similar templates, the basic template is the template with easy usage, for example, Toast Notifications is more basic than Azure Hub Notifications.

**Comment by mrlacey** [comment]
I never claimed we should sort based on usage I asked if we had data to **inform** what was done. 

My objection is to:
- Capturing telemetry data and not using it to inform decisions. and
- Assuming we know what people want and will use without testing that assumption.

The proposed list might be perfectly fine but, for example, *if* it turns out no-one is using the tabbed page then maybe it's shouldn't be third on the list. Or, *if* almost all new apps add the settings page then maybe it should be higher.

**Comment by crutkas** [comment]
i'm verifying our telem data right now (which goes into my #135) issue.  From this i do believe we need to validate as well do we feel we should override the data and how does new features come in to play like new pages.

**Comment by mrlacey** [comment]
I think settings would be better in the top row of page options so it doesn't get lost in the list.

I also wonder if "Blank" is skewed by it being included by default as the home page on everything generated in 1.0. Is this accounted for in the data?

**Comment by crutkas** [comment]
First, i think we shouldn't segment MSFT vs Community, instead highly used features should be bubbled up.

For ordering, 
**Pages** - thoughts why: maps is low, data rich are grouped together, still data driven.  minimal adjustments on layout.

- Blank
- Settings
- Web View 
- Media Player 
- Master Detail
- Grid
- Chart
- Tabbed
- Map

I'm ok for rest.

**Comment by crutkas** [comment]
Created a branch for this
