### ISSUE TITLE
Accessibility: 4.5 to 1 color verification

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#490]
All text needs to have a 4.5 to 1 color contrast.  This is background to text color.

This is both wizard and templates

**Comment by crutkas** [comment]
https://github.com/ThePacielloGroup/CCA-Win/releases/ to help with contrasts.

One idea is to be sure we do a color palette pulled from styles.

**Comment by crutkas** [comment]
I thought the titlebar was Windows Blue.  Use #0078D6

I don't like black.

**Comment by mvegaca** [comment]
Looks fine with #0078D6 and contrast is 4.5

![image](https://user-images.githubusercontent.com/5556784/29554160-67a24fc2-871e-11e7-9883-80b631e6430e.png)

**Comment by crutkas** [comment]
oops, letting @mvegaca close this out

**Comment by dgomezc** [comment]
Verified on pre-release

Wizard: 0.8.17248.4
Templates: 0.8.17248.4
