### ISSUE TITLE
Accessibility: Narrator support verified

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#494]
Narrator support properly works on both wizard and template.  Areas i feel it may not work the best are summary, the selection items in the wizard, and master detail page.

**Comment by dgomezc** [comment]
Status of this issue:

- In the wizard all elements are read correctly by the narrator, except static texts.
- In the generated apps, the narrator correctly reads the hamburger menu and pivots menu.
- The main button of hamburger menu should have a more descriptive name, we asked the development team ([#1329](https://github.com/Microsoft/UWPCommunityToolkit/issues/1329)).

 It is necessary to verify how the narrator behaves on our pages (master-detail, map, pages with telerik controls,...)

**Comment by dgomezc** [comment]
In the main button of the hamburger menu the narrator says "Main Button". This text is not customizable.
The narrator works correctly on our pages (master-detail, map, pages with telerik controls,etc).

**Comment by mrlacey** [comment]
@mvegaca You've marked this as can-close-out-soon, does that mean we're not going to address the "Main Button" issue raised by @dgomezc ?

For reference, the "Main Button" text comes from the toolkit control. I suspect that the fix will be to override the template for now and raise an issue with them to make it configurable.

**Comment by crutkas** [comment]
Is that being addressed by toolkit?  If so where is the linked bug.

**Comment by mrlacey** [comment]
I remembered seeing it as a hard coded value in the past. I took it out when we had our own version. On going back to the official one their hard coded text came back. 

It seems @dgomezc created and then closed an issue for them on this (https://github.com/Microsoft/UWPCommunityToolkit/issues/1329) but I don't deem it closed. Hard coded English text is not adequate for our needs.

**Comment by mvegaca** [comment]
Working on a PR for [toolkit issue](https://github.com/Microsoft/UWPCommunityToolkit/issues/1329).

**Comment by mvegaca** [comment]
[PR](https://github.com/Microsoft/UWPCommunityToolkit/pull/1418) updated on UWP Community Template

**Comment by sibille** [comment]
Info button is saying only Button

**Comment by sibille** [comment]
Verified in pre-release
Wizard: 0.8.17249.2
Templates: 0.8.17249.2
