### ISSUE TITLE
Improve speed and isolation of tests

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#497]
Would be good to improve the code isolation so that tests can be run in parallel and can, therefore, be executed faster.

**Comment by mrlacey** [comment]
Be good to wait until after the VB and StyleCop branches are integrated before attempting anything here or risk making merging them *very* tricky.

**Comment by crutkas** [comment]
what is not making the tests run not parallel?  looking at it, each test is 1 after another versus multiple at the same time

**Comment by mrlacey** [comment]
> what is not making the tests run not parallel? looking at it, each test is 1 after another versus multiple at the same time 

A consequence of the VB changes (plus they don't run in parallel on the build server)
There were also intermittent errors previously when running some tests in parallel - e.g. #709

The generation tests can't run in parallel as they are based on the templates appropriate to the test. Under the hood, there's a lot of copying of files to specific folders based on the selected items (project type, framework, pages, features, and now language.) Tests can't run in parallel with this or they start overwriting the files that different tests need. Imagine one test starts and copies over some C# files and then another test running at the same time overwrites these with some VB ones. The current code it too brittle to handle such testing.

I raised this issue directly in response to realizing how things currently work and how this lack of isolation prevent parallelization.

A short, quick fix would be to have each test put files in different folders but I haven't verified: this doesn't have other consequences; what this means for non-test generation; what the required code changes are; or if it just ignores another underlying problem in the way the generation code is structured. (The big static globals being a red flag on this too.)

**Comment by mrlacey** [comment]
Past changes to cache template unpacking by tests have made running tests much faster. This makes this redundant
