### ISSUE TITLE
Need a checklist of things to verify when adding new output to generated content

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#508]
Need a central list of things to check before a release and when adding new pages, features, and frameworks, or modifying existing items.

Should include:
- Automated tests pass
- Spelling & grammar check of any comments in the generated code
- Description text in the wizard. Summary & details.
- Icon shown in the wizard is not the default.
- also issues mentioned in  #490 #491 #494 #495 (which are all checks to verify that current code meets accessibility standards--this is about ensuring the same level of support in the future)

**Comment by touseefbsb** [comment]
I second that this should be done to keep it consistent and simpler to manage , it will prevent future issues

**Comment by crutkas** [comment]
also readability for code comments and text.

**Comment by crutkas** [comment]
how should we go about enforcing these?

**Comment by mrlacey** [comment]
Not sure about enforcing. Although at least some of it will need to be manual. That's partly what code reviews are for. But, also need to be able to point to something that says what should be doing.

**Comment by mrlacey** [comment]
some of this can be enforced with current automated tests. Some new tests may be needed. 
Plus, need some documentation for other items

**Comment by mrlacey** [comment]
This is increasingly important as we get external contributions. We shouldn't need weeks of back and forth to be clear of everything that needs to be done.

**Comment by ralarcon** [comment]
@crutkas @mrlacey do you think is enough with the [list ](https://github.com/Microsoft/WindowsTemplateStudio/wiki/Template-Verification-Checklist) @sibille provided?

**Comment by crutkas** [comment]
tweaked.  we can keep it as an evolution.  great job @sibille and everyone
