### ISSUE TITLE
Bug: Broken links in page descriptions

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#509]
There are broken markdown links for the three new pages added in 1.1.

Image below shows MediaPlayer but Chart & Grid are similarly affected.

![image](https://user-images.githubusercontent.com/189547/27497717-fa094a90-5853-11e7-98b6-34174f8f8cc0.png)

Grid description also mentions chart in a horrible display of a cut-and-paste schoolboy error.

It turns out that some markdown viewers are more tolerant of this than our code to display these files.

**Comment by crutkas** [comment]
@mrlacey feel like we can close this out.
