### ISSUE TITLE
remove / blank out shortName

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#511]
Can we delete "shortName" inside template.json?  It is redundant since we use "name".  I've brought this up a few times.  If the VS engine needs it, can we move it to the bottom of our json files or blank it out?

**Comment by ralarcon** [comment]
I'm sure I already check this but I do not remember exactly the outcome. We'll have a look.

**Comment by sibille** [comment]
Checked, we are not using this. Going to remove
