### ISSUE TITLE
New Page: Take photo

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#519]
Add a page that shows capturing a photo from the camera (or library if no camera available) and displaying it on the page.

**Comment by JimSEOW** [comment]
@mrlacey, could you extend that to include video?

**Comment by mrlacey** [comment]
The original intent of this was to just do images as feedback from Xamarin said this was one of their top requests. Support for video capture was not wanted nearly as much though.

The intent is also that this is implemented with the system provided capture UI (docs: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-photos-and-video-with-cameracaptureui)

Maybe video can be a P2 on this. Worth reviewing if can easily be made part of the same page or if it should be a separate page (and issue).

I've also opened a separate issue (#606) for adding the ability to control the capture of video and photos which could also be useful for AR scenarios.

**Comment by crutkas** [comment]
Video would be a different page/issue.  Video introduces a slew of edge cases that a camera page doesn't.

The two pages at the end of the day could be the same base but I think they are different from what someone would want.

**Comment by CarteKiwi** [comment]
Working on it ! If you don't mind... :)


![image](https://user-images.githubusercontent.com/12309245/28342603-5ab6fe54-6c19-11e7-9d01-91f240fd7334.png)

**Comment by crutkas** [comment]
@cartekiwi. Let's work together for how the page works and stuff.  This way we aren't doing duplicate work  :)

**Comment by JimSEOW** [comment]
@crutkas Sorry, I have been busy lobbying for[ a broad .NET Deep Learning feedback.](https://github.com/Microsoft/CNTK/issues/960#issuecomment-316228402) . I will get back to what I have proposed soon. Thanks for your patient.

**Comment by ralarcon** [comment]
Verified in pre-release 0.9.17289.03

**Comment by mrlacey** [comment]
As part of porting this template to VB (#1335) it would be really useful to know all the ways to test this page/functionality. I don't want to miss anything. 
Has anyone got, or is able to put together, a list of all aspects of this page that need testing?
