### ISSUE TITLE
Renaming a file and "focus" with mouse clicking

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#522]
When you click "rename" then try to click on the textbox to alter the name, it loses focus and stops the rename.  An example where this isn't ideal is someone would want click in the middle of the text blox to fix a minor spelling mistake or focus to the end of the dialog

**Comment by mvegaca** [comment]
Working on it

**Comment by mvegaca** [comment]
It's working fine on dev branch

**Comment by sibille** [comment]
happening again on 0.14.17187.05

**Comment by mvegaca** [comment]
Fixed on following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/652)

**Comment by mvegaca** [comment]
Fixed on #682

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
