### ISSUE TITLE
Accessibility: tabbing on screen 1 w/ keyboard

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#536]
There is no way to move to next screen via tabbing.  When i tab, i auto select the next item.  So no matter what i would end up with a mvvm basic w/ pivot tab

Next doesn't have an alt hot key.

**Comment by mvegaca** [comment]
You can move from framework items group to summary items and next button with tab key and move between framework items using arrows. Checked on dev branch.

**Comment by dgomezc** [comment]
Verified on pre-release
Wizard: 0.8.17248.4
Templates: 0.8.17248.4
