### ISSUE TITLE
Accessibility: Summary controls - reordering

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#537]
Unclear how this is selected via keyboard.  space bar doesn't select and cant use arrows

**Comment by mvegaca** [comment]
This is always for 1.3? #495

**Comment by mvegaca** [comment]
Implemented on #993 now you can select a saved page template as draggable item using the space bar, move in different items and drop the item pressing the space bar again.
This operation could be canceled by pressing Esc key. Draggin item is highlighted with a light yellow background.

**Comment by sibille** [comment]
Steps to repro: 
Add two pages Blank1 and Blank2
Select Blank1 and move it below Blank2
Press Whitespace twice on Blank2

**Comment by mvegaca** [comment]
Fixed on #1076

**Comment by mvegaca** [comment]
Any more on keyboad accessibility @Sibille ?

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65001
Templates: 0.14.17249.4
