### ISSUE TITLE
Summary control - tabbing on the pages / feature control and  focus

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#538]
Feels like there is a double tab focus going on here.

I tab on to the control, i see the following when i hit tab over and over again

- dashed line
- nothing (feels like deselected)
- move is highlighted 
- gear is highlighted

**Comment by mvegaca** [comment]
I think that it does not still happen. Can you check it @crutkas ??

**Comment by dgomezc** [comment]
Checked on version:
Wizard: 0.14.17244.65002
Templates: 0.14.17244.2
