### ISSUE TITLE
Text cut when high dpi

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#542]
![image](https://user-images.githubusercontent.com/2638875/27726131-6dac3a64-5d79-11e7-8a6f-115501c9efc5.png)

**Comment by crutkas** [comment]
I think the verbiage is too verbose actually

**Comment by ralarcon** [comment]
Yeah, we had reduced it.

**Comment by mvegaca** [comment]
Fixed on following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/577)
