### ISSUE TITLE
Wizard status displayed in the wrong place?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#543]
![image](https://user-images.githubusercontent.com/189547/27727218-690f1c8c-5d75-11e7-8e80-a1d4723974ac.png)

Has this intentionally been moved from the bottom left of the screen?

**Comment by ralarcon** [comment]
We have moved the notification area (for errors and warnings from the bottom to the upper left). The informational status will be redesinged a bit to give more consistency... know is a bit wierd and does not look good...

**Comment by mrlacey** [comment]
really looks bad if using the new 'Check for new templates' button when content ahs already loaded as overlaps existing content.

![image](https://user-images.githubusercontent.com/189547/27741591-83e4a10c-5dad-11e7-8d16-3f38696c8bfe.png)


With the Lorem Ipsum in there, I assumed this wasn't finished yet but as there's no issue detailing what the intended change is I can't really say.

**Comment by mvegaca** [comment]
Updated on following [Pull Request](https://github.com/Microsoft/WindowsTemplateStudio/pull/562)
