### ISSUE TITLE
Licenses of dependencies are not shown on right click wizard

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#547]
Adding suspend and Resume service should show the Newtonsoft.Json license, from it's dependency on SettingsStorage but does not do so.

**Comment by mvegaca** [comment]
Fixed on following [Pull Request](https://github.com/Microsoft/WindowsTemplateStudio/pull/557)

**Comment by mvegaca** [comment]
Fixed on following [Pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/582)
