### ISSUE TITLE
.NET 4.7

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#552]
Just set up a new machine for testing and saw that we are 4.6.2.  Any reason to not just got to 4.7?  Needed to download new targeting packages.

**Comment by crutkas** [comment]
VS solution is 4.5.2.  .net

**Comment by crutkas** [comment]
punting to 1.4 due to issue @ralarcon raised in PR.  lets reduce complexity in this release

**Comment by ralarcon** [comment]
I'm going to double check if adding the dependency to the installer solve the issue and what is the behaviour when users do not have installed W10 Creators Update (where the .NET 4.7 is being shipped).

**Comment by sibille** [comment]
Verified in dev
