### ISSUE TITLE
CSharp.Upw.Solution targets .NET 4.6.1

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#553]
Everything else targets 4.6.2 that I could tell.  this is related to #552 on my new machine setup

**Comment by ralarcon** [comment]
We can move to 4.7 but I suggest to do it after released the 1.2 (just to avoid any collateral effect)

**Comment by crutkas** [comment]
ok.  Closing this in favor to #552 and will make that for 1.3
