### ISSUE TITLE
commandBar for smartphone  template Studio

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#558]
put  the CommandBar on the  bottom for Smartphone when the desktop is  at the to  you can do  
VisualState

> <Grid
        x:Name="ContentArea"
        Margin="12,0,12,0">

        <Grid.RowDefinitions>
            <RowDefinition x:Name="TitleRow" Height="48"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <TextBlock
            x:Name="TitlePage"
            x:Uid="Main_Title"
             FontSize="{StaticResource FontSizeMedium}" Foreground="{StaticResource RedBrush}" FontWeight="SemiLight" TextTrimming="CharacterEllipsis" TextWrapping="NoWrap" VerticalAlignment="Center"
            Margin="0,0,12,7"/>

        <CommandBar HorizontalAlignment="Right" Background="White" >
            <CommandBar.PrimaryCommands>
                <AppBarButton  x:Name="AddButton" Icon="Accept" x:Uid="Aceptar"  Foreground="{StaticResource RedBrush}" Click="AddButton_Click"/>
            </CommandBar.PrimaryCommands>
        </CommandBar>

        <Grid 
            Grid.Row="1" 
            Background="White">

**Comment by mrlacey** [comment]
@Javier118 None of the templates include a CommandBar. What are you asking here?

**Comment by Javier118** [comment]
The question is: having the Commnadbar as put the XAML code as I can said CommandBar that has appear at the bottom in the Samrtphone, while on the desktop is at the top.

**Comment by mrlacey** [comment]
If this is just a general question of how to do something in a UWP app then, as a non-WTS specific question it would be better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/uwp) or the [MSDN forums](https://social.msdn.microsoft.com/forums/windowsapps/en-us/home?forum=wpdevelop).

If this relates to the code generated by the tool, please reopen and explain: how to recreate what you have; what you're trying to do; what you've tried; and how what you've tried differs from what you're aiming for.

**Comment by Javier118** [comment]
As I can commondbar in the templates as I can do the Commanbar has look at the bottom of the mobile, when it is DESKOTP has appear at the top according to the code you put before.

**Comment by mrlacey** [comment]
Yes, but none of the generated projects include a CommandBar.  

It seems you're asking a general development question about how to change the position of the command bar based on the device the app is running on. This is not the place to ask such general questions.  
There are many ways to do this and there is no single best way that is right for all apps. You probably want an adaptive trigger based on device family though.

**Comment by crutkas** [comment]
@Javier118 many things are possible with XAML, what you want can be accomplished a few different ways.  But we cannot provide support for every XAML question.  Please ask those questions over at StackOverflow.  Doing a quick search, i found a few answers.
