### ISSUE TITLE
shellpage onnavigated to method override never gets invoked

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#564]
Code below exists in ShellPage.xaml.cs
`
protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            RootFrame = Frame;
        }
        public static Frame RootFrame;`

above overridden method never gets invoked, Ive even tried break points. I want to access the root frame of the app ( the frame which has ShellPage in it, ) because I want to directly navigate to a page within the rootframe and not within shellFrame ( the frame which is within ShellPage and contains all other child pages for the app ) . after analyzing Window.Current.Content anywhere I have found that it contains ShellPage directly, and no frame, and returns null when I try to get "**Window.Current.Content as Frame**".

**Comment by crutkas** [comment]
Codebehind, MVVM Basic or MVVM Light?

**Comment by ralarcon** [comment]
@mvegaca could give us some light here...

**Comment by touseefbsb** [comment]
@crutkas.  Mvvm basic

**Comment by mrlacey** [comment]
@touseefbsb when was this project created? With what version of the templates? (open package.appxmanifest to see this in the metadata.)  
There is no longer any reference to `RootFrame` and no override of `OnNAvigatedTo` in the latest templates, so I wonder if something that wasn't needed has been removed.

**Comment by mvegaca** [comment]
The ShellPage is not thought to be navigated because ShellPage already defines its own frame.
ShellPage is assigned to Window.Current.Content in ActivationServices and no navigated from a frame.
This is the reason why ShellPage is never navigated and OnNavigatedTo is never called.

Try adding StartUp logic on ActivationService methods.
Before application load
```
private async Task StartupAsync()
{
}
```
After activation
```
private async Task InitializeAsync()
{
}
```

If you want to run code on ShellPage you can also use Loaded handler.

You can also customize ActivationService setting Window.Current.Content as a new Frame and then navigating to ShellPage.

```
var frame = new Frame();
Window.Current.Content = frame;
frame.Navigate(_shell);
```

**Comment by touseefbsb** [comment]
I m using the latest dev build and yes i can work around it in activation handler, thnks @mvegaca

**Comment by crutkas** [comment]
should we add a comment to the template?  Did https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/activation.md not handle your need?

**Comment by touseefbsb** [comment]
Yes I think adding a couple of comments specifically for this scenario would be better :)

**Comment by ralarcon** [comment]
We will include the in this post in the documentation.

**Comment by mvegaca** [comment]
Documentation is pretty clear on this point. The issue can be closed.

**Comment by mrlacey** [comment]
Where is the documentation that makes this clear?
This issue is a dead-end if someone comes to this with the same question?

**Comment by mvegaca** [comment]
The [documentation](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/activation.md) specify the methods InitializeAsync and StartupAsync to add the initial logic instead of using Shell navigation events because ShellPage is not navigated from a frame.
