### ISSUE TITLE
not digging the new UX for info

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#565]
It gets in the way. and not in a good way.  It covers up too much critical information all the time by being on top.

We need to do a few other mocks.

**Comment by ralarcon** [comment]
The main reason to have this info area is to be able to check for templates on-demand. We can make it "light" and hide if open once the user clicks out of its area. We can evaluate other proposals as well.

**Comment by mvegaca** [comment]
Updated on following [Pull Request](https://github.com/Microsoft/WindowsTemplateStudio/pull/577)

This is the simpler and smaller overlay box.

![image](https://user-images.githubusercontent.com/5556784/27823510-a87a738a-60a9-11e7-969b-8ee1a7cf31a9.png)
![image](https://user-images.githubusercontent.com/5556784/27823567-d9ca595a-60a9-11e7-8591-80874034d41b.png)

**Comment by crutkas** [comment]
I was talking more about errors and info dialogs.  The cover up everything and for reasons that don't deserve that much chatter.  There are tons of areas people are getting information in the wizard and causes conflict. 

The dialog you are talking in the screenshot above right now just is too verbose.

**Comment by ralarcon** [comment]
Well we can review and give consistency. Let me know what elements are too much verbose / can be removed and we'll do asap.

**Comment by crutkas** [comment]
closing this out in favor of #596
