### ISSUE TITLE
grey border on top and left?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#566]
what is with the grey border on the top / left

**Comment by ralarcon** [comment]
Basically, its makes a frame to contain the whole content as well as allow us to have the notification area in the top without hiding important content when messages appear.

**Comment by crutkas** [comment]
it doesn't fully frame out and forces a ton of wasted space.

**Comment by ralarcon** [comment]
This is what we have now: full frame with margin consistency and allowing to have the notifications shown without hiding important content. :
![image](https://user-images.githubusercontent.com/2638875/27819711-ce6bb7b0-609b-11e7-9b98-e59ab666fe69.png)

![image](https://user-images.githubusercontent.com/2638875/27819948-c48e30b4-609c-11e7-80e2-6b327c6da058.png)

This is a matter of likes, so we can adjust to whatever is preferred.

**Comment by crutkas** [comment]
I don't want the border.  The areas that you highlighted that are grey are due to scroll bars.

**Comment by ralarcon** [comment]
Yes, dont worry, we can remove it. Was marking it as using them create a frame. We we will remove this.

**Comment by mvegaca** [comment]
Take a look on this PR #687
- Gray margins removed from New project and New Item wizards.

![image](https://user-images.githubusercontent.com/5556784/28025900-e9e75d3e-6594-11e7-9724-f46a6f146a4f.png)

- Margins removed from Changes Summary code viewer #616 

![image](https://user-images.githubusercontent.com/5556784/28025936-f79da096-6594-11e7-9f28-48101fd3dc6a.png)

@ralarcon @crutkas

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
