### ISSUE TITLE
user control vs control

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#570]
why is it togglepane.xaml and togglepane.cs.  shouldn't this be togglepane.xaml.cs?  

This also affects overlaybox and codeviewer

**Comment by mvegaca** [comment]
User control combines one single Xaml file with the cs file, for example on Status control.
I used prefer to add Custom Control with separated Xaml and CSharp code files because I prefer the use TemplateBinding when I make UI controls.

**Comment by crutkas** [comment]
lets pick one and move forward.  

Unless there is a clear reason, we shouldn't have multiple competing ways of doing things.  Right now, other than developer preference, there was no reason to do something different.

**Comment by crutkas** [comment]
feels like we're migrating pure control instead of user control, correct?

At this point, i think we can punt this 1.4.  Low hanging fruit for just general app cleaniness

**Comment by mvegaca** [comment]
I agree with you

**Comment by mvegaca** [comment]
Updated from Control to UserControl in #1125. From now, we will use UserControl.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.1
