### ISSUE TITLE
Merge with documentation leaves additional blank lines in code

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#573]
See image, 

![image](https://user-images.githubusercontent.com/24698018/27819400-55f2d6fc-609a-11e7-8276-4469f8ce72dd.png)

Blank lines should not be added if not in block

**Comment by mrlacey** [comment]
Fixed in the StyleCop branch - PR at #559

**Comment by sibille** [comment]
I think this should be fixed in the merge method of the IEnumerableExtension. 
Now that we force to surround blocks to be inserted with {[{ and }]} I think blank lines that have to inserted should be part of the block instead of inserting any blank line found in the postaction file. It's more coherent and we'll have a bigger control over the blank lines in files. 
Deleting the blank line between postaction documentation and code has the same effect, but will be less readable when postaction fail (see picture).
![image](https://user-images.githubusercontent.com/24698018/27823968-352632b4-60ab-11e7-9138-0b50bdba5156.png)

**Comment by mrlacey** [comment]
two things

1. Templates shouldn't include unnecessary blank lines.

2. If there is a need to have some blank lines I'd look to update the global post action that sorts namespaces to make sure it doesn't output a blank line at the top of the file.

**Comment by sibille** [comment]
1. I added this for readability, but thats just my opinion, we can remove that line. 
2. Good point, going with that approach :)
