### ISSUE TITLE
Why Chinese will garbled?

### ISSUE THREAD

**Issue by CodingNinjaOctocat** [Microsoft/WindowsTemplateStudio#587]
If I use Chinese directly on the XAML page, it will appear garbled, if in Resources.resw use Chinese is normal, why?

**Comment by ralarcon** [comment]
@CodingNinjaOctocat, can you please give us the repro steps so we can investigate it further?

**Comment by CodingNinjaOctocat** [comment]
@ralarcon I found that the code file encoding for the WTS creation project was UTF-8, but VS created UTF-8 (with BOM), I manually converted the file encoding, found that normal, but I am puzzled that when I use Git to undo the use of Chinese again, no problem (file encoding UTF-8, but no problem), so I do not know how. anyway, garbled problem to converte file encoding😭

**Comment by CodingNinjaOctocat** [comment]
For the time being, if I ever find this problem again, I'll feed back!

**Comment by ralarcon** [comment]
Ok!
