### ISSUE TITLE
Rename on new project wizard is not renaming when clicking in the pages list after renaming

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#594]
1) click rename
2) rename and click another page

-> name is not changed

**Comment by mvegaca** [comment]
Fixed on [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/637)

**Comment by mvegaca** [comment]
Fixes on #661

**Comment by mvegaca** [comment]
Updated #682

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
