### ISSUE TITLE
Info box hides important information

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#596]
![image](https://user-images.githubusercontent.com/24698018/27860496-334dd712-617d-11e7-8509-18b70fd712ab.png)

**Comment by mvegaca** [comment]
On this [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/604) I've add a button to hide notification on the right site of the status area.

**Comment by crutkas** [comment]
I don't like that solution, it is a band aid on top of a major usability issue.  This is the same issue as #565

**Comment by mvegaca** [comment]
Update at [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/637)

- Notification with auto hide.
- Update close icon.

**Comment by ralarcon** [comment]
@crutkas we moved the notification area to the top based on consistency. With that we can have a common place for New Item and New Project where to display notifications. Do you think it would be fine to reserve space for the notification area (for one line of content) and, if required (more than one line), move the content? With this approach we will not be hidding any important information.

**Comment by crutkas** [comment]
I don't like the X, it is placed oddly and isn't clickable.  That wasn't what i was hoping for as a discussion for this.

The root of the issue is this is the first information someone is greeted with and it covers up critical information.  It throws up a ton of information that is causing information overload that isn't relevant nor an error.

**Comment by ralarcon** [comment]
I thought that giving the message would make more clear that there are no changes, but it is probably I didn't have a reflexion considering that having only the "Unchanged files" and the button "Close" will be enough information for the users.

Do you agree to remove the notification in that case?  It is pretty simple.

**Comment by mvegaca** [comment]
Warning message removed on #679

**Comment by crutkas** [comment]
This PR feels like it swings too far by removing a ton of things.  Did we vet each one we just removed?

**Comment by ralarcon** [comment]
@crutkas maybe I got it wrong but understood the there was too much redundant info. We just removed the extra warning message saying that there are no changes. 

The only thing is that the resource was removed from all the resx files (no required now, by the way). 

Let me know if you prefer this to be back or what approach to follow.

**Comment by ralarcon** [comment]
@crutkas in the meanwhile do you think we can add an "auto-hide" notification here to remark that there are no changes?
