### ISSUE TITLE
Hamburger button and page headers are not aligned

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#597]
![image](https://user-images.githubusercontent.com/24698018/27861791-951dd154-6182-11e7-9a65-f50e888a2d39.png)

![image](https://user-images.githubusercontent.com/24698018/27861760-790509b0-6182-11e7-99c3-8eba90d0ca59.png)

**Comment by crutkas** [comment]
the entire header is off on this.  look at the title

**Comment by mrlacey** [comment]
This and #612 highlight the need to do a full review of the generated pages. I thought I raised an issue on this when doing the Hamburger menu changes, as they don't all match the redlines, but can't find it now.

**Comment by mrlacey** [comment]
The images below are taken from the `NavigationView` control in the latest FCU SDK preview and do not have the spacing above and below the hamburger button that the original red-lines included.

![image](https://user-images.githubusercontent.com/189547/27930308-0bc50078-628e-11e7-9b9b-037242024b89.png)
![image](https://user-images.githubusercontent.com/189547/27930323-13e0f7f8-628e-11e7-941e-287a5aae35cb.png)

@crutkas can you confirm that we should use this as a guideline over the red-lines and remove that space and therefore address the alignment issue that way?

**Comment by crutkas** [comment]
kill the whitespace.

**Comment by mrlacey** [comment]
Closing as verified in DevNightly

wizardVersion - 0.14.17192.65001
templatesVersion - 0.14.17192.4
