### ISSUE TITLE
ActivationService has lots of compile time errors

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsTemplateStudio#603]
I am on latest dev nightly build ( version = 0.14.17167.65001 ) and I am making a very simple project with following features.
1. Three blank pages and One Media Player Page
2. Settings Page.
3. Top Pivot navigation with MVVM Basic.
4. Suspend and Resume Service.

**Problem 1: ** 
Project is not added to the solution but is created, when tried to add to the solution it gives error because the ".csproj" file has white spaces and "Newsoft.Json" refrenced at the very top of the file, before **xml** starts. 
**Solution : ** 
I was able to solve this by removing it from top and pasting it where it belongs under <--Nuget Package Refrence -->> comment in the file.

**Problem 2 : **
the project doesn't compile because ApplicationService has lot of errors. and errors are quite obvious and strange as well, there is some code at random places in the file and a line at top without semi colon as well. Following line was written at the very top of the file, even above using statements.

**private async Task InitializeAsync()**

Note that above line has no ending semi colon as well. but even if I put it here the errors don't go away.
>Then there is another line written just before **internal class ActivationService** so following line is written directly into the **Services** namespace.

**await ThemeSelectorService.InitializeAsync();**

Which again is very obvious that a method is never called in a namespace.

Rest of the file looks fine.

**Problem 3 : **

There is no **NavigationService** at all in the project, but that's probably because I chose the Pivot View instead of hamburger navigation for the project. but ActivationService is still trying to use the navigationService in it which doesn't exist

**Comment by ralarcon** [comment]
Please, can you double check the version, today's nightly is 0.14.17186.01 and during the day we have released some other fixing various issues (current release is 0.14.17186.07)

**Comment by touseefbsb** [comment]
I think I have an older version of nightly installed, but I cant see the updated version to update it.

**Comment by touseefbsb** [comment]
my bad, I cant see the update in blend, but it is available in visual studio. Thankyou :)

**Comment by ralarcon** [comment]
Welcome... in fact, you scared me a bit 😨 (this should be solved yet)

**Comment by touseefbsb** [comment]
yes it is fixed on the latest version. Thanks

**Comment by crutkas** [comment]
the wonders of using the nightly branch :)

**Comment by touseefbsb** [comment]
Yeah nightly branch is great
