### ISSUE TITLE
Back button does not return to the MasterListView

### ISSUE THREAD

**Issue by TheJoeFin** [Microsoft/WindowsTemplateStudio#611]
I created an app using a pivot control and had two master detail pages. The first page the app launches to is a blank page. When I navigate to the first master detail page and pick an item from the list the back button in the narrow state does not return to the list. Instead the back button navigates to the first blank page. This Issue can be reproduced on mobile and a narrow desktop window

**Comment by crutkas** [comment]
can you provide the recipe you used for this?  namely the framework you picked.  Template version also would be helpful.

**Comment by ralarcon** [comment]
This looks related to #272. Maybe we have had a regresion?

**Comment by TheJoeFin** [comment]
Yeah it sounds like it is the same issue.

**Comment by mrlacey** [comment]
When going to a narrow view and seeing just the details page I think it should still be within the outer tab page and you can still see and access the top level nav.

**Comment by TheJoeFin** [comment]
The fix on this page fixed this issue.

https://github.com/Microsoft/WindowsTemplateStudio/commit/61ebb9050339dea9c5282d6952786718ed58127e

**Comment by crutkas** [comment]
That link on PivotPage.xaml.cs just has a comment.  What fix?

**Comment by TheJoeFin** [comment]
Adding this line to the pivotpage.xaml.cs file:



`NavigationCacheMode = NavigationCacheMode.Required;`

**Comment by mrlacey** [comment]
> I am using the extension version 1.0.17142.1.

This was fixed in version 1.1 of the extension. (Verified no regression in 1.1, dev-nightly & dev)

To get the latest version:
In Visual Studio, go to Tools > Extensions and Updates. Under 'Updates' you should see 'Windows Template Studio' listed. Click the update button. Close VS and install the update.
Alternatively, go to aka.ms/wtsinstall and install the new version from there.
