### ISSUE TITLE
Detail view on a Master/Detail page has white space in Narrow View

### ISSUE THREAD

**Issue by TheJoeFin** [Microsoft/WindowsTemplateStudio#612]
The margins in the Detail view for a Master/Detail page show 12px white bars on the sides of the application when in the narrow state.

**Comment by crutkas** [comment]
can you tell us what version of the templates you are using and maybe drop in a screenshot?  Github will let you just drag the image on and will do the hosting for it.

**Comment by crutkas** [comment]
Is this the same issue as #597?

**Comment by TheJoeFin** [comment]
It doesn't look like the same as #597 Here is a screen shot.
![MasterDetailEdgeMargins](https://user-images.githubusercontent.com/7809853/27887443-6a01f274-61a6-11e7-938a-3fe9b3a39e98.png)

I am using version 1.0.17142.1 of the Windows Template Studio extension for Visual Studio 2017

**Comment by crutkas** [comment]
Thanks for the screen shot, that makes is much more useful.

**Comment by mrlacey** [comment]
Repro:
- tabbed project type
- add master/detail page
- add a settings page
- Run generated app
- with app window wide enough to show the master and detail
- go to settings tab and enable dark theme
- go m/d tab
- make the window small so only see the master list
- tap an item in the list
- window show white side borders :(

**Comment by mrlacey** [comment]
Verified in dev nightly

wizardVersion="0.14.17193.65001" 
templatesVersion="0.14.17193.7"
