### ISSUE TITLE
License font size larger than rest

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#615]
![image](https://user-images.githubusercontent.com/1462282/27885617-6b503280-618d-11e7-89fd-fed746afe612.png)

**Comment by mvegaca** [comment]
Fixed on the following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/634)

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
