### ISSUE TITLE
padding on right click add code diff viewer

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#616]
![image](https://user-images.githubusercontent.com/1462282/27886158-b47cfe50-618f-11e7-923b-12ff7818fc9b.png)

What is with the padding?

**Comment by mvegaca** [comment]
Fixed on the following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/632)

![image](https://user-images.githubusercontent.com/5556784/27903898-38c1f840-623b-11e7-9f7e-5c6b5bd391cf.png)

**Comment by crutkas** [comment]
I feel like this should be the other way corrected,  now we have a white border + the gray border.

**Comment by mvegaca** [comment]
We could try different possibilities:

- Removing white margins:

![image1](https://user-images.githubusercontent.com/5556784/28011513-e5f98d0a-6562-11e7-9bd4-5dc3c5a4b055.png)

- Removing white margins and removing resulting file header (to be aligned with new files):

![image2](https://user-images.githubusercontent.com/5556784/28011519-e91f96f0-6562-11e7-99bf-0b4c09a821e8.png)

What do you preffer @crutkas ?

**Comment by crutkas** [comment]
i like 2nd one but the right title area should not be a dark grey.  how about a light blue?

**Comment by mvegaca** [comment]
Not bad, light blue works fine.
Uploaded with some code analysis fixes on PR #704


![image](https://user-images.githubusercontent.com/5556784/28063646-16b208b2-6632-11e7-8381-8f6b3390dc50.png)

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
