### ISSUE TITLE
right click add, modified files has non-clickable area

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#617]
If you click on the actual name, you're fine but the area i outlined isn't clickable when it should be.

![image](https://user-images.githubusercontent.com/1462282/27886214-efbbac64-618f-11e7-9b77-330954e93fd4.png)

**Comment by mvegaca** [comment]
Fixed on the following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/631)

**Comment by crutkas** [comment]
I don't agree with the fix here.  #649 is open due to that.  Adds unneeded complexity to the visual tree.

**Comment by mvegaca** [comment]
Related to #649. Fixed on #654

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
