### ISSUE TITLE
redundant information w/ screen VS info modal.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#618]
![image](https://user-images.githubusercontent.com/1462282/27886274-33e6dd96-6190-11e7-9964-11b3708bcadb.png)

This is related to #596 where we display redundant information.

**Comment by mvegaca** [comment]
Updated on following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/630)

- Replace redundant loading text by Windows Template Studio Logo
- Add LogoControl with customizable fill color property

![image](https://user-images.githubusercontent.com/5556784/27900793-eea3645c-622f-11e7-813e-687d554d5350.png)

**Comment by ralarcon** [comment]
This will be soon fixed over the existing control instead of changing the control type.

**Comment by mvegaca** [comment]
Fixed on #677

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
