### ISSUE TITLE
padding inconstancy for license on right click 

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#619]
![image](https://user-images.githubusercontent.com/1462282/27886236-068a5724-6190-11e7-8855-53dafaaf8821.png)

This feels off and we kind of have this look / feel issue on the file->new wizard as well.

**Comment by mvegaca** [comment]
Fixed on following [pull request](https://github.com/Microsoft/WindowsTemplateStudio/pull/629)


![image](https://user-images.githubusercontent.com/5556784/27899617-40343a08-622b-11e7-985c-d6c549118ea5.png)

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
