### ISSUE TITLE
Add WTS icon for right click menu

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#620]
![image](https://user-images.githubusercontent.com/1462282/27886381-a4d60ae0-6190-11e7-87a8-a1501cefce52.png)

**Comment by ralarcon** [comment]
I tried but haven't found an easy way to do it.

The schema for Visual Studio Commands define icons for buttons but not for Menus, so I haven't found way to add the icon to the Menu level.

The schema is like this:
```
<Commands package="GuidMyPackage" >  
  <Menus>... </Menus>  
  <Groups>... </Groups>  
  <Buttons>... </Buttons>  
  <Combos>... </Combos>  
  <Bitmaps>... </Bitmaps>  
</Commands>  
```

"Windows Template Studio" is a `Menu` and that kind of item does not allow an "Icon" element. 
https://docs.microsoft.com/es-es/visualstudio/extensibility/menu-element

https://docs.microsoft.com/es-es/visualstudio/extensibility/adding-icons-to-menu-commands

**Comment by crutkas** [comment]
ok, lets close this out but lets keep this in the back of our head

**Comment by sibille** [comment]
@crutkas 
I just noticed that we're the only one's with submenu and icon. Maybe we shouldn't have the wts icon there.
![image](https://user-images.githubusercontent.com/24698018/28111763-de0fa4ae-66f6-11e7-81e8-1fdd285a63ef.png)

**Comment by crutkas** [comment]
i really would love if we could get a WTS icon in that menu.  Lets punt to 1.3 or a later update.

**Comment by crutkas** [comment]
we tried and broke some stuff, no other item does context menu + icon as well.  closing issue
