### ISSUE TITLE
Right click summary file is created with non valid links.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#621]
Example from one.  Note the URL encoding.  When using the recommended editor, links are not clickable.

```
### Changes in file 'Strings\en-us\Resources.resw':
See the final result: [Strings\en-us\Resources.resw](c:%5Cusers%5Ccrutkas%5Cdocuments%5Cvisual%20studio%202017%5CProjects%5CApp22%5CApp22%5CStrings%5Cen-us%5CResources.resw)

```

**Comment by sibille** [comment]
I think that's an issue of the editor. It's showing correctly all relative links but not the absolute ones. Maybe this was done on purpose, as the tool's purpose is to create html from markdown files (at least that's what I understood from the docs).   
If you open the file in Visual Studio Code you can navigate fine.

I see the following options to solve the problem: 

1. The generation summary file is currently created in the temp generation folder, if we create it in the project folder links could be relative and would work.
2. Just name the files and have no links. They are already part of the project so I think they won't be too hard to find. 
3. Find another extension that shows the files like Visual Studio Code.

**Comment by crutkas** [comment]
I think we should figure out how to make it work with the recommended editor and not force someone to use VS Code (it is a great product) but asking someone to install another product just isn't realistic.

**Comment by ralarcon** [comment]
Maybe we can look for other extension to show the md within VS. 

@crutkas What do you think about moving the file from the Temp folder to the project solution?

**Comment by sibille** [comment]
Talking to the people from markdowneditor we found a way to generate a working link: 

```
### Changes in file 'Strings\en-us\Resources.resw':
See the final result: [Strings\en-us\Resources.resw](about:/C:/Users/sibil/documents/visual%20studio%202017/Projects/App178/App178/Strings/en-us/Resources.resw)
```
It's not a perfect solution:

*  the link is marked with a readline as unresolvable on the left side 
* the link does not work in other editors (f.ex. VS Code)

**Comment by crutkas** [comment]
doing the shortened version which looks to be in the nightly works.

`[Strings\en-us\Resources.resw](Strings\en-us\Resources.resw)`

**Comment by crutkas** [comment]
Actually, looks like #740 just bit us.  Pages works, features did not.

**Comment by sibille** [comment]
The links in the CreateSyncSummaryPostAction were not clickable because they contained whitespaces. GenerationSummary.md is generated in the temp directory and the linked files are in your project folder which contains white spaces. 
Pointing to the files in the temp directory solves the problem, but I think it's not correct. If the files are already integrated we should point to the project files.

**Comment by sibille** [comment]
@crutkas What makes you think pages work but features not. I think it's the whitespaces, but want to be sure to not oversee another condition.
