### ISSUE TITLE
designer for chart page still broke

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#622]
it no longer breaks the compiler but CategoricalAxis throws a warning.  Tried MVVM Light and Code behind.

This is from the nightly

```
<tc:RadCartesianChart.HorizontalAxis>
   <tc:CategoricalAxis />
</tc:RadCartesianChart.HorizontalAxis>
```

Object reference not set to an instance of an object.	App24	c:\users\crutkas\documents\visual studio 2017\Projects\App24\App24\Views\ChartPage.xaml	27	

Code behind throws another error while MVVM throws a different.
**CODEBEHIND**
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ChartPage' does not contain a definition for 'Bindings' and no extension method 'Bindings' accepting a first argument of type 'ChartPage' could be found (are you missing a using directive or an assembly reference?)	App22	c:\users\crutkas\documents\visual studio 2017\Projects\App22\App22\obj\x86\Debug\Views\ChartPage.g.cs	169	Active

**MVVM**
errors on: `<vms:ViewModelLocator x:Key="Locator" />`

Severity	Code	Description	Project	File	Line	Suppression State
Error		There is already a factory registered for App24.Services.NavigationServiceEx.	App24	c:\users\crutkas\documents\visual studio 2017\Projects\App24\App24\App.xaml	10

**Comment by mrlacey** [comment]
I can't repro the ChartPage warning.
The ViewModelLcoator issue appears to not be a real error but a fault in VS reporting a false-positive on an error. I also only see this reported in the Preview version, not the release version of VS.

@crutkas, or anyone else, still able to repro?

**Comment by crutkas** [comment]
Think i figured it out.  Are you doing a x64 or x86 compile?

* **x86** - With cleaning the solution and compiling w/ x86, i see errors when viewing the chart page.
* **x64** - With cleaning the solution and compiling w/ x64, the designer loads

When i filed this bug, i was didn't have the laptop i'm currently on so I'm betting this has something to do with it and how Telerik compiled the DLL.

I don't even see the Locator error w/ an x64 build, only x86

**Comment by mrlacey** [comment]
I also see the issue only when in x86

**Comment by crutkas** [comment]
Created issue against telerik

**Comment by crutkas** [comment]
Looks like they just updated the NuGet package.
