### ISSUE TITLE
Random folder should be linked closer to file for right click add

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#624]
Was thinking Solution+DateTime.  Random folder name becomes too hard to track stuff.

**Comment by sibille** [comment]
I've changed the temp folder name to be ProjectName.
Using Naming.Infer if the folder exists another with Name ProjectName_2 (ProjectName_3, etc) is created. We can also add the date in, but I think it's not necessary.

**Comment by crutkas** [comment]
reason why i was thinking datetime was it tells me instantly when stuff was done.  Not just a number increment.

**Comment by crutkas** [comment]
Also date time ensures uniqueness while maintaining making it filterable.

**Comment by ralarcon** [comment]
Adding the DateTime in the following format: "<ProjectName>_<YYYYMMDD_HHMMSS>". We can easily change it if required.
