### ISSUE TITLE
Are we too verbose on descriptions?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#627]
I'm looking at Toast, Dev Center notification, azure hub, live tile, and few others.

**Comment by JimSEOW** [comment]
@crutkas  Why Toast4.NET?

**Comment by mrlacey** [comment]
I think the real issue here is that these descriptions describe the service that the feature connects to, rather than what gets added to the project when adding this feature.

![image](https://user-images.githubusercontent.com/189547/28068231-777e5e70-663c-11e7-94db-3f7f1a05cd8c.png)

**Comment by mrlacey** [comment]
verified changes now in dev-nightly (v 0.14.17192.65003)
