### ISSUE TITLE
Review updating to Community Toolkit v1.5

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#633]
https://github.com/Microsoft/UWPCommunityToolkit/releases/tag/1.5.0
Need to double check existing control use after upgrade and review simplifying our Hamburger Menu styling as they have updated based on our past changes.
There may also be more issues.

Note all issues and changes required before implementing any changes.

**Comment by crutkas** [comment]
Should try to get it into 1.2 IMO.

**Comment by ralarcon** [comment]
@mrlacey Are we going to face this or should be move to 1.3?

**Comment by mrlacey** [comment]
We use the toolkit for:
- Live Tiles feature
- Toast Notifications Feature
- HamburgerMenu on SplitView project

updating to 1.5 seems to be no problem for the notification related features

The hamburger related update comes down to whether we're happy taking a styling change this close to release.

It would be good if we could as it might help avoid similar issue to those who were using HamburgerMenu 1.4 with custom styling and then updated to 1.5
https://github.com/Microsoft/UWPCommunityToolkit/issues/1296
https://github.com/Microsoft/UWPCommunityToolkit/issues/1277

**Comment by crutkas** [comment]
@mrlacey i say do a quick branch and test.  if you're happy, lets roll with it.  We're not shipping this week.

**Comment by mrlacey** [comment]
in progress

**Comment by mrlacey** [comment]
The review looks good. No issues were seen. Preparing for changes...

**Comment by mrlacey** [comment]
verified in Dev Nightly

wizardVersion=0.14.17193.65002
templatesVersion=0.14.17193.13
