### ISSUE TITLE
Unit test for testing dependancy properties from being removed

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#644]
in #595 there was a bug where you could remove a DP that another item required.  Looking at the PR (#628), i don't see an associated unit test.

**Comment by mrlacey** [comment]
Also slightly concerned that the logic for this was previously in the UI. What other logic exists in the UI?

**Comment by ralarcon** [comment]
@mrlacey I think is the only logic at this level We will ensure to reinforce the behavior properly at engine level.

**Comment by crutkas** [comment]
Moving to 1.4, low pri

**Comment by sibille** [comment]
verified in dev
