### ISSUE TITLE
Markdown info window license link vertical alignment issue

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#647]
![image](https://user-images.githubusercontent.com/1462282/27931287-8da85044-624e-11e7-8378-592fc9b7e5c1.png)

looks to be too high

**Comment by mvegaca** [comment]
Fixed on #685

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
