### ISSUE TITLE
StatusControl.xaml has hardcoded font and margin sizes

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#650]
noticed it in https://github.com/Microsoft/WindowsTemplateStudio/pull/634/files while reviewing.

**Comment by mvegaca** [comment]
Referring to this bug and #610 bug I'm thinking of making few reactors to handle all visual styles in Xaml code and optimize the control.

**Comment by mvegaca** [comment]
Control added on #676

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
