### ISSUE TITLE
Review new item telemetry

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#662]
Ensure the telemetry for new item is properly generated and we can track the features usage.

**Comment by ralarcon** [comment]
Reviewed and looks fine.

Wizard Type:
![image](https://user-images.githubusercontent.com/2638875/28128506-33d6d090-6730-11e7-928a-25cec85201f9.png)

Wizard Actions:
![image](https://user-images.githubusercontent.com/2638875/28128487-27e1655c-6730-11e7-94c2-2d2c29776399.png)

Pages:
![image](https://user-images.githubusercontent.com/2638875/28128381-d9682226-672f-11e7-9ca9-73195fb66289.png)

Fetures:
![image](https://user-images.githubusercontent.com/2638875/28128111-f389a806-672e-11e7-96ae-e01b5dfd94ae.png)

@sibille We can think if we could modify the WizardAction for new projects which currently is undefined (we can use GenerateProj -to avoid mix the results with Generations vs GenerationAndMerge from right-click)

**Comment by ralarcon** [comment]
It is pending to replicate the chart updates once we have "production / pre-release" data.

**Comment by mrlacey** [comment]
> &lt;undefined>

Should not be. You can't rely on this always being one thing.  Define it.

**Comment by ralarcon** [comment]
Yes, is what I pointed. Anyway, we are not relaying on this value as that property was not in the original telemetry set.

**Comment by sibille** [comment]
Verified in nightly build: Wizard Version 0.14.17194.65002, Templates Version 0.14.17194.3
