### ISSUE TITLE
TODO notes in generated code are inconsistent

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#665]
In the generated code a number of comments are included that start "TODO UWPTemplates: " but only 

For example:

    // TODO UWPTemplates: For more information regarding the application lifecycle and how to handle suspend and resume, please see:
    // Documentation: https://docs.microsoft.com/windows/uwp/launch-resume/app-lifecycle

and

    // TODO UWPTemplates: This event is fired just before the app enters in background. Subscribe to this event if you want to save your current state.

Here there is nothing the developer must do. These actions are optional. Should we really be saying these are things that every developer should do in every app?

We should review all such TODO comments and remove the "TODO" part from the ones that are optional or just provide information. 
We should only include the "TODO" part for non-optional changes that the developer must make to the generated code.

**Comment by crutkas** [comment]
Yeah, also why we have it as "UWPTemplates" is legacy as well.

How about:
// TODO WTS: [action required]
// NOTE WTS: [optional but helpful]

**Comment by ralarcon** [comment]
Changed all "//TODO UWPTemplates:" by "// TODO WTS:"; Not added "// NOTE WTS:" where the comment is just an extension or clarification as it adds too much verbosity.

**Comment by crutkas** [comment]
Reviewed @ralarcon, good first step and i'll approve.  this will be something we need to look at each one for 1.3

**Comment by mrlacey** [comment]
can close out now? It's in dev branch
