### ISSUE TITLE
Code duplication: GetTempGenerationPath

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#666]
Code duplication: GetTempGenerationPath - #651.  Found in a code review

code/src/UI/VisualStudio/RightClickActions.cs
code/test/VsEmulator/Main/MainViewModel.cs

private static string GetTempGenerationPath(string projectName) is the same function

**Comment by dgomezc** [comment]
Remove duplicate code corretly.
