### ISSUE TITLE
Rename fake classes and namespaces

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#667]
this feels like unneeded IO.  We write it, then read it, update it, then rewrite it.

**Comment by mrlacey** [comment]
where are you seeing this?

**Comment by crutkas** [comment]
I set a break point on both file write and you will see both are hit. 

We write the sln twice.

**Comment by mrlacey** [comment]
@crutkas where are you setting breakpoints? file name and line numbers please.

**Comment by sibille** [comment]
It's this one [MSBuildSolution](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/code/test/Artifacts/MSBuild/MsBuildSolution.cs), correct?
This is part of the VSEmulator, not the extension, but yes, we can optimize this. 
@crutkas: I'll push it to 1.3, if you're fine with that.

**Comment by crutkas** [comment]
@sibille yes, that file.  yes, per the milestone, i wrote this for 1.3
@mrlacey line 81 and 86 in MSBuildSolution

This raises a few questions:
1. If this is emulator only, how does the extension physically create the SLN?
1. why do these two differ
1. Why is a file being labeled "Test" being used outside a unit test

**Comment by sibille** [comment]
1. In the case of the extension the solution is created by Visual Studio.
2. The emulator emulates the things Visual Studio does in the "real extension", it's a way to abstract things from the VSShell. 
3. The MSBuildSolution code is used by the unit tests and the emulator, which is part of the testing code, the emulator is a tool to test the wizard and templates outside the VSShell

**Comment by mrlacey** [comment]
I don't think this is really an issue. There's the potential to optimize what we have to save some disk I/O but doing that will make it harder to handle solutions containing multiple projects.
We'll need multi-project solutions in the future and the current code is ready to support this.

**Comment by crutkas** [comment]
Here is my brain dump after doing some reference tracing and reading @sibille's response.  @mrlacey i don't think my original issue is valid now that more light has shed on this.

1. Artifact namespace isn't clear what it is nor implies.  This feels more like a Mock or Fake subset.
2. The emulator lives in Microsoft.Templates.VsEmulator, not a .Test namespace
3. Test namespace to me states a UnitTest of some sort, not something we'd take a dependency on.  Once again, Fake or Mock.
4. Should have FakeGenShell, why don't wasn't that naming followed through?

My thought is we should rename a few of those files along with the namespace.  Make it very clear that these do stuff so we can test.

**Comment by sibille** [comment]
So, what do you think about these two actions: 

- Rename MSBuildProject and MSBuildSolution to FakeMSBuild and FakeSolution 
- Change the namespace of the Artifacts project to Microsoft.Templates.Fake.Artifacts

**Comment by mrlacey** [comment]
"Artifacts" are the things that are created. This code is doing the creating.
I'd change the namespace to "BuildFakes"

**Comment by sibille** [comment]
Renamed the title of the issue to reflect what we agreed to do. 
 @mrlacey: The former Microsoft.Templates.Test.Artifacts also contains the FakeGenShell, I think I'll go with 
Microsoft.Templates.Fakes as namespace if eveybody agrees.
