### ISSUE TITLE
Unify controls between right click add and file->new

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#669]
Looking at code reviews, we are repeating way too many items.

Things that could be made into controls off the top of my head:
- header
- Item control (both wizard project type, page, along with right click add)

This will start causing consistency issues for xaml, accessibility, and localization

**Comment by mvegaca** [comment]
I start working on header and Item control.
I'm going to compare new project and new item views looking for code that can be reused.

**Comment by mvegaca** [comment]
Header control added on #1127

I'm trying to unify DataTemplates property of our three current ListView types:
- 1. New project: Project type & Framework
- 2. New project: Add page / feature
- 3. New item: Page / feature

There are some important differences between templates 1/3 and 2/3. Looking at those differences, I think that trying to share code makes the code less flexible and harder to understand.

I'm thinking on parts of xaml code that we can share using controls between New Project and New Item.  
We could think about sharing the bottom bar implementation but we need to think about #607 and the changes that it cloud includes on that bar.
In my opinion is not necessary to add more control by this moment.

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.1
