### ISSUE TITLE
Define process for changes that should be merged straight to master

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#673]
At the moment *evevrything* goes into dev before being merged into master.
Some of the more meta files, like readme.md or docs/issue_template.md should have their changes applied to master faster than only when we make a release.
Do we need a process for these type of changes?
Would it also be better to update the docs pages more frequently too?

**Comment by ralarcon** [comment]
We can have another branch for docs / samples with higher merge frequency than dev. The only thing is to merge back the changes from master to dev everytime we update documentation.

**Comment by crutkas** [comment]
How about:

1. branch from master
2. do PR back into master
3. do PR back into dev

Doc changes only, two people must sign off before we merge

**Comment by mrlacey** [comment]
I see that #681 has also been created on a similar theme.

It'd be good to avoid things like the date issue fixed for #367 only being fixed in dev and so another issue&PR was raise 2 months later in #551 when master should have been updated immediately.

It'd also be good to avoid the current need to update doc references (from another branch to master) when we make a release.


How about:

- Fixes to existing docs (corrections and additional info that applies to what is live) should go straight to master.
- Double sign off for merge to master sounds good.
- As with any change to master, dev should be updated to reflect the change
- Create new links to docs that reference the master branch by default.  I think that if someone's using dev and they follow a link to the docs in master that is broken they should be smart enough to figure it out.

**Comment by ralarcon** [comment]
Sounds good for me. Regarding the last point, even we can figure out how to handle a replacement (which vary by environment) for the "root url" in the TODOs / NOTEs.

**Comment by mrlacey** [comment]
Now dev is the default branch this is redundant. 
Any new changes are made prominent on GitHub so making changes on dev & master should no longer be necessary
