### ISSUE TITLE
Make github urls in code and vsix configurable

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#681]
Links to github documentation in Vsix and Wizard (f.ex links to new item documentation) should be configurable by environment. 
LocalVsix should point to dev, published to master.

**Comment by crutkas** [comment]
Point this to the roadmap. This has the changelog. 

https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/roadmap.md

**Comment by crutkas** [comment]
Good idea.

**Comment by dgomezc** [comment]
Verified on pre-release
Wizard: 0.8.17248.4
Templates: 0.8.17248.4
