### ISSUE TITLE
Close Gap between drop down and gap.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#688]
![image](https://user-images.githubusercontent.com/1462282/28028402-47dc2206-6551-11e7-9b5a-2d162493f88a.png)

feels disconnected with that gap

**Comment by mvegaca** [comment]
Fixed position and color on #702

![image](https://user-images.githubusercontent.com/5556784/28062179-62f28224-662d-11e7-9d1a-04b7ec08cd97.png)

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
