### ISSUE TITLE
Emulator tooltips

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#689]
![image](https://user-images.githubusercontent.com/1462282/28028602-e88c1224-6551-11e7-973c-29187c644f3a.png)

Can we get tooltips added to the emulator for what the icons mean

**Comment by dgomezc** [comment]
Update on  #814.

**Comment by crutkas** [comment]
checked into 1.3

**Comment by sibille** [comment]
verified dev 20/07/2017
