### ISSUE TITLE
Right Click Add:  Change summary

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#690]
The current left side feels like the summary on the file->new.  Feels odd that this is on the left side versus right.

![image](https://user-images.githubusercontent.com/1462282/28028658-270e8900-6552-11e7-864a-f0bfe2d3a780.png)

**Comment by ralarcon** [comment]
Our conclusion here is that chnages summary is more like a file explorer, usually located at the left, and the file->new is more like a shopping cart, usually located at the right.

**Comment by crutkas** [comment]
I'm mixed on this.  In my opinion, it feels off but i have no good justification other than that.  Lets get user feedback on it.
