### ISSUE TITLE
Right Click add: Title differences

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#691]
- Font weight differ in summary vs title on left and right.  The right side's bold is no where else in the UX
- Note the alignment between titles difference

![image](https://user-images.githubusercontent.com/1462282/28028851-c024fae8-6552-11e7-9aef-ebbf76ab4a7d.png)

**Comment by mvegaca** [comment]
Fixed on #701 

![image](https://user-images.githubusercontent.com/5556784/28061286-66ce28b0-662a-11e7-9798-bd06431b9d09.png)

**Comment by crutkas** [comment]
I don't think the bottom one would have been an issue.

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
