### ISSUE TITLE
centralize datetime tostring writing

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#692]
#674 improvement

**Comment by crutkas** [comment]
Found 
- [ ] ShellHealthWriter
- [ ] FormatWriterMessage

**Comment by mrlacey** [comment]
Also in 
- FormattedWriterMessages
- ShellHealthWriter
- GenContext
- GenerationFixture
- NewItemGenerationTests
- StyleCopGenerationTestsFixture
- VsOutputPane

**Comment by mrlacey** [comment]
ReOpening as `FormatAsFullDateTime` would be improved with a hyphen separating the year, month, and day parts of the date so it's easier to read.

**Comment by mrlacey** [comment]
Before
![image](https://user-images.githubusercontent.com/189547/29669648-0a52df0c-88dc-11e7-81db-569bd2f8e638.png)

After
![image](https://user-images.githubusercontent.com/189547/29669809-8d440d8c-88dc-11e7-8e63-e255ab7a4d8f.png)
