### ISSUE TITLE
Misaligned circles on Add summary page

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#693]
The colored circles next to the file names in the summary section of the add page wizard should be aligned with the chevron/down-arrow 
![image](https://user-images.githubusercontent.com/189547/28037083-27d8708e-65b2-11e7-8f29-79cb35640f35.png)

It would stop making my eyes bleed if the circles were centered under the chevron, like this

![image](https://user-images.githubusercontent.com/189547/28037162-68263180-65b2-11e7-8fff-89859057464d.png)

**Comment by crutkas** [comment]
OOOo, surprised my OCD didn't catch that

**Comment by crutkas** [comment]
pushing to 1.3 for higher pri issues

**Comment by mvegaca** [comment]
Circles aligned #782

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
