### ISSUE TITLE
Left border on infobar is distracting - remove

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#694]
I'm not keen on this left border

![image](https://user-images.githubusercontent.com/189547/28037668-0abc5216-65b4-11e7-88d9-71c4f4caf5a4.png)

- It feels unnecessary
- The color is very similar to the background of the title but different enough to make me think is looks out of place.

**Comment by crutkas** [comment]
Agreed.  I really think we need to reevaluate the notification system

**Comment by mvegaca** [comment]
Left border removed on #699

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
