### ISSUE TITLE
Project generated incorrectly - ForInfo

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#695]
_Logging this as a record that it happened. Not sure if it was just a one-off as been unable to repro._

I generated a project (local, from dev [baf4dc07db7d94db375abd6780d9242a09e62564])

SplitView
CodeBehind
Settings
Grid
Suspend&Resume

Right click on generated project had the "New Page" and "New Feature" options but not "Open generation folder"

I tried to add another **Grid** page to the existing project but the conflict page had _weird_ namespace issues
![image](https://user-images.githubusercontent.com/189547/28038086-97c79002-65b5-11e7-9d40-8bd53528f06d.png)

Closed and reopened project.

Now WTS entry on the right click menu is missing.

Opened Package.appxmanifest and saw that was missing version numbers.

  <genTemplate:Metadata>
    <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
    <genTemplate:Item Name="wizardVersion" Version="0.0.0.0" />
    <genTemplate:Item Name="templatesVersion" Version="0.0.0.0" />
    <genTemplate:Item Name="projectType" Value="SplitView" />
    <genTemplate:Item Name="framework" Value="CodeBehind" />
  </genTemplate:Metadata>

Tried to generate another project and it worked fine and all behavior was as expected.

**Comment by ralarcon** [comment]
We will try to figure out what have happened...

**Comment by ralarcon** [comment]
Is it possible that you launched the "Add Page" using the keyboard shortcut? Is how I can repro it... 

The thing is that the shortcut launch the wizard no matter what project file / folder / item is selected in the solution explorer (except if you are at solution level), so we infer the namespace based on it. 

The correct behavior should be to use always the project root namespace, as we only allow to launch the "right click" commands by clicking in the project (and we do not allow to add pages / features in different location than the root)

**Comment by mrlacey** [comment]
That sounds like a bug.

If launching the "Add Page" or "Add Feature" wizard it should not use the directory with the focus as the root namespace.

It is not reasonable to require that the focus is on the root of the project to use the keyboard shortcut.
It is reasonable for people to have the cursor on the Views folder when they use the keyboard shortcut to add a new page.

Yes, there are some potential edge cases for modified folder names and namespaces that mean it might not be possible to infer the correct root namespace in 100% of cases but we can do a better job than this.

**Comment by ralarcon** [comment]
It is a bug. Never said a different thing :-)

I'm going to try to fix it for 1.2

**Comment by ralarcon** [comment]
Verified in nightly 0.14.17194.2
