### ISSUE TITLE
Allow NavigationService to support hiding app level navigation chrome

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#697]
Inspired by #482 

By "chrome" mean the Hamburger menu or top level tab navigation.

- Be purely additive, allow current code to continue to work as is.
- Add a new method to the `NavigationService` that allows `NavigateWithChromeHidden()` (open to suggestions for a better name)
- The new method should work from within the app and as a way of starting the app so the first page loaded doesn't have the navigation chrome but subsequent pages do. (There's potential overlap here with the planned ExtendedSplashScreen and SignIn pages.)

(Will need to break coupling between NavigationService and ActivationService - also has impact on other things that try and reference the `ContentFrame`)

**Comment by mvegaca** [comment]
Can it be closed in favor of #1122?

**Comment by mrlacey** [comment]
@mvegaca ok. I created this as I was originally going to cover it as part of #775 but you did it a different way.
