### ISSUE TITLE
Invalid RightClink menu in non-WTS UWP project

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#707]
Create a blank UWP app without using WTS.
The right-click menu on the project contained the WTS menu option with a single empty entry. (see picture below.)
The right-click project menu should not contain the WTS submenu if not a WTS generated project.

![image](https://user-images.githubusercontent.com/189547/28064411-76af2976-662c-11e7-9baa-a5c9fa03ef96.png)

**Comment by ralarcon** [comment]
This is caused because the work arround applied to allow to have Icon in the menu... Investigating right now.

**Comment by ralarcon** [comment]
This should not happen any more as we are removing the HiddenCommand to force the icon to be shown xref #774

**Comment by sibille** [comment]
Verified in nightly build: Wizard Version 0.14.17194.65002, Templates Version 0.14.17194.3
