### ISSUE TITLE
Telemetry on NewItem contains list of features

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#708]
This event should only contain number of features/pages

**Comment by mrlacey** [comment]
Don't we need to know which features are being used?

**Comment by sibille** [comment]
yes, we do, but features and pages generation have their own events, so there is no need to log them on the newItem event too. It's a minor issue, I just opened it to have consistency between NewProject (that logs the number of pages and features) and NewItem (that logs number of pages and features and their identities) event

**Comment by sibille** [comment]
Verified in dev-nightly 0.14.17192.65002
