### ISSUE TITLE
HealthTests not returning consistent results

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#709]
`UsageAsync()` and `VerifyTraceLevelChangeAsync()` fail inconsistently.

I cannot repro consistently but suspect this is due to the use of global static objects.

Cannot recreate when running test in isolation and only seen failures when running all tests. I suspect removing test parallelization (already included in StyleCop PR) will remove the issue but would still be good to isolate these tests better.

**Comment by mrlacey** [comment]
Would also be good to update these tests to report more useful information when they fail.

**Comment by ralarcon** [comment]
@mrlacey you are right the issue is the parallelization. In the build server never happend because the test do not use parallelizations.

**Comment by crutkas** [comment]
is this still an issue @mrlacey?

**Comment by mrlacey** [comment]
I'm not running these tests locally so don't know if it's still an issue.
I still regularly see tests failing in CI but I don't know if it's related to this.

**Comment by sibille** [comment]
Had a look at the failure reason for the builds in last two month: Found nothing related to this, from the transitient failures, most failed due to lost communication with the server or missing folders

**Comment by mrlacey** [comment]
> Had a look at the failure reason for the builds in last two month: Found nothing related to this, from the transitient failures, most failed due to lost communication with the server or missing folders

lets close this then
