### ISSUE TITLE
Renaming textbox is smaller on community templates

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#711]
![image](https://user-images.githubusercontent.com/5556784/28068574-755c4a94-6646-11e7-9bf2-6b9b81c8131f.png)

![image](https://user-images.githubusercontent.com/5556784/28068579-7b01d5e0-6646-11e7-9c2a-1cee7a76a13c.png)

**Comment by mvegaca** [comment]
Fixed #713

**Comment by crutkas** [comment]
Why are these separate controls?

**Comment by mvegaca** [comment]
I've add a TemplateSelector and different templates to Microsoft Templates and Community and other users templetes to add author textblock. It makes that author templates are taller than microsoft templates.

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
