### ISSUE TITLE
Increase code viewer FontSize

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#721]
Font size is too small on 200% display configuration settings

**Comment by mvegaca** [comment]
Set font size manually to 20 pts #722

**Comment by crutkas** [comment]
Screen shots would have been helpful for this to witness the issue.

**Comment by ralarcon** [comment]
Here are some (applying 20pts as text size looks more proportioned):

Code viewer default text size - 2560x1440 - **200%** Size of Text, Apps, others: 
![image](https://user-images.githubusercontent.com/2638875/28079629-70646076-6669-11e7-9b2f-45ee4a1838d1.png)

Code viewer 20pts text size - 2560x1440 - **200%** Size of Text, Apps, others:
![image](https://user-images.githubusercontent.com/2638875/28079729-c742b230-6669-11e7-97a1-3d2490bd51fa.png)

Code viewer default text size - 2560x1440 - **100%** Size of Text, Apps, others: 
![image](https://user-images.githubusercontent.com/2638875/28079797-fe3b15de-6669-11e7-9884-8427e556b58a.png)

Code viewer 20pts text size - 2560x1440 - **100%** Size of Text, Apps, others:
![image](https://user-images.githubusercontent.com/2638875/28079812-10d2020c-666a-11e7-8893-cf94abd4f896.png)

**Comment by crutkas** [comment]
The fix makes a normal screen render look giant.  This is not the appropriate fix and wasn't fully tested before doing a PR.  We need to roll back.

![image](https://user-images.githubusercontent.com/1462282/28083127-41fe1c26-6629-11e7-949a-d32f755d433d.png)

**Comment by crutkas** [comment]
I'm inclined to roll this back and punt to 1.3

**Comment by mvegaca** [comment]
Maybe we cloud add a default font size to 20 and add buttons to increase and decrement the font size.

**Comment by crutkas** [comment]
There is has to be a different fix here.  You're adjusting stuff for edge case that blows everything up to extremes to become unusable.

**Comment by ralarcon** [comment]
I guess @mvegaca idea was to leave the default font size (not 20pts) and add the zoom buttons for users to be able to adjust under their preference.

**Comment by crutkas** [comment]
i want to punt this to 1.3 also

**Comment by mrlacey** [comment]
We need a default value that works with DPI settings.
Adding the ability to zoom content would be a nice extra.
A super nice option would be if wee could pick up the configured text display size from within VS  and use that. But one for the backlog.

**Comment by crutkas** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410(v=vs.85).aspx could help making the UI dpi aware then.

**Comment by mvegaca** [comment]
#1031 Add buttons initializing font size to a double value between 9 and 25 based on DPI information.
Can you check it on different screen and let me know if it has a good user experience?

**Comment by crutkas** [comment]
why did we add buttons for zooming?  that feels like a setting we should have grabbed from VS.  I don't like that solution and feel like we should have had a discussion to figure out the pro's and con's of each.

**Comment by mrlacey** [comment]
I'd expect to see the size variation of what's basically a code window controlled like any other code window in VS. That means DropDown for picking specific sizes plus support for scroll-wheel zooming.
To my mind though, that sounds like an awful lot of work for such a small feature.
Can't we just support current font size from VS and add proper handling for DPI. It seems that's the real issue. That we're not displaying this page like others.

**Comment by mvegaca** [comment]
I've added a default font size estimated from Dpi information, the main idea is that code preview looks fine by default on all screens. Additionally, I've added a small button to increase and decrease the font size as an extra for this page. This code view is not a view for editing the code or programming, this is a preview of the code WTS is going to generate. In my opinion, the most important here is to can read clearly with different resolutions. Zoom buttons are a good extra.

**Comment by mvegaca** [comment]
Can this issue be closed?

**Comment by sibille** [comment]
We'll comment out the buttons for the moment, as you can modify size using ctrl + + and ctrl + -

**Comment by mvegaca** [comment]
Buttons where commented on #1077

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65002
Templates: 0.14.17249.10
