### ISSUE TITLE
Info dialog: right click to copy version/log to clipboard 

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#723]
would be nice if i could click and just have this information quickly to aid in people reporting bugs.

Logs / version information.

**Comment by mvegaca** [comment]
Make wizard and templates versions as a select target. #1023

**Comment by mvegaca** [comment]
Fixed, checked on version
Wizard: 0.14.17242.65001
Templates: 0.14.17242.2
