### ISSUE TITLE
Summary: expanders are misaligned

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#725]
This is a 1.3 item, we've lived with this for a while.

![image](https://user-images.githubusercontent.com/1462282/28081862-96ff2732-6625-11e7-896a-ce3d5df6b4d0.png)

**Comment by mvegaca** [comment]
Fixed on #1018 
![image](https://user-images.githubusercontent.com/5556784/29779715-abfb45b2-8c13-11e7-847f-34570c45b6e6.png)

**Comment by mvegaca** [comment]
Checked on WV: 0.14.17241.65001 - TV: 0.14.17327.2
