### ISSUE TITLE
Dev-Nightly build is listed under "Tools" not "Templates"

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#726]
Now shows here

![image](https://user-images.githubusercontent.com/189547/28081967-f7e265bc-6668-11e7-9ed2-7f834a65bb35.png)

Was here

![image](https://user-images.githubusercontent.com/189547/28081996-148d0e92-6669-11e7-89ac-21f6fcef37ae.png)

**Comment by ralarcon** [comment]
This could be because of the trick we used to be able to show the icon in the menu... I'll try to check it.

**Comment by crutkas** [comment]
noticed this too #728.

**Comment by sibille** [comment]
In the branch i removed the hidden command the extension is still showing under tools not template. 
I think it's because now we're not only providing a template but also relaycommands, but still searching for official reference to proof that

**Comment by crutkas** [comment]
Actually i bet this is what caused the upload issue to visual studio gallery!

**Comment by mrlacey** [comment]
Closing as an underlying issue due to how VS categories extensions.
WTS is more than just static templates (it has menus, etc. in VS) and so they classify it as a tool.
