### ISSUE TITLE
PNG and "highlighting" in wizard

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#727]
The MVVM Light logo is actually a PNG.  It would be great if we could get that to highlight to the correct color.  Could a WPF shader effect do this?

**Comment by crutkas** [comment]
here is some stuff that could be an item but man, rathole to get set up.

http://wpffx.codeplex.com/
http://wpf.codeplex.com/releases/view/14962
http://wpffx.codeplex.com/discussions/37107

**Comment by mrlacey** [comment]
Or we could just have two versions of the image and swap between then as necessary

**Comment by crutkas** [comment]
high contrast mode is where this could cause a curve ball or if we change this to accent color

**Comment by crutkas** [comment]
synced with @onovotny and he recommended looking at https://github.com/teichgraf/WriteableBitmapEx/

This could do it and i'm pretty sure it is a nuget package too.

**Comment by crutkas** [comment]
using writable bitmap, have a functional version.

```
private void Image_MouseEnter(object sender, MouseEventArgs e)
{
    var setColor = Colors.CornflowerBlue; // highlight color
    ChangeColorOfImage(sender, setColor);
}

private void Image_MouseLeave(object sender, MouseEventArgs e)
{
    var setColor = Colors.Black; // base brush color
    ChangeColorOfImage(sender, setColor);
}

private static void ChangeColorOfImage(object sender, Color setColor)
{
    var img = sender as Image;
    WriteableBitmap writeableBmp = new WriteableBitmap(img.Source as BitmapSource);
    img.Source = writeableBmp;

    using (writeableBmp.GetBitmapContext())
    {
        writeableBmp.ForEach((x, y, color) => Color.FromArgb(color.A, setColor.R, setColor.G, setColor.B));
    }
}
```
