### ISSUE TITLE
Redunant information in Right click merge window

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#729]
Why do we have the "Resulting file" included.  This feels redundant and a waste of space.

![image](https://user-images.githubusercontent.com/1462282/28083242-9626eae4-6629-11e7-8b4e-8c2cd92dbb68.png)

![image](https://user-images.githubusercontent.com/1462282/28083947-eafa6a62-662b-11e7-8982-d26290cd361a.png)

**Comment by mvegaca** [comment]
Updated on #771
