### ISSUE TITLE
Subtext in merging: Is it redundant?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#730]
![image](https://user-images.githubusercontent.com/1462282/28083523-75d6b9f8-662a-11e7-9180-cf75d370affb.png)

Looking at Github and VS, i think we're too verbose on this.  We don't do this anywhere else as well.

**Comment by mrlacey** [comment]
There's more room for improvement here:
![image](https://user-images.githubusercontent.com/189547/28088576-fd327cf4-667d-11e7-935b-4a956aa14ccc.png)

**Comment by ralarcon** [comment]
Agree with all except the line numbers as those are handles directly by "Monaco" (we can try to see if it is customizable, anyway)

**Comment by mrlacey** [comment]
The larger text size makes the numbers much more obvious and I think they take up a lot of space and are in a prominent position for no real benefit. If they are out of the box with a control then I wouldn't worry.

**Comment by mvegaca** [comment]
Updated at #771

- Remove Resulting file header.
- Removed a part of text: "Below you can check the modifications."

![image](https://user-images.githubusercontent.com/5556784/28114114-b5e8e5ae-66ff-11e7-87c0-b865f1656040.png)

**Comment by crutkas** [comment]
@mrlacey we can't remove the dual lines, see Martin's last screenshot.  it shows code line adjustments in 2nd column.

Personally, i think we should remove the subheader "the file ''XXX' blah blah".  When you merge the title on the right, the light blue bar and the fact where it is highlighted in the left, it is very clear what is happening IMO.

That can be a 1.3 adjustment IMO.

**Comment by crutkas** [comment]
* if we do the subheader removal, it should be a new issue and xref this bug.

**Comment by mvegaca** [comment]
Maybe we can add the text after the file name:

App.csproj (resulting file)

**Comment by crutkas** [comment]
I don't know, i feel like that is implied personally by the title.  It also isn't the resulting file from that view as it does show lines added / removed at times.  it is the diff view.

**Comment by crutkas** [comment]
I still think this page can be made tighter but closing out for now.
