### ISSUE TITLE
Right Click able to do multi-select in summary window

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#731]
![image](https://user-images.githubusercontent.com/1462282/28083859-ab00e472-662b-11e7-8cd0-e9c5a819b6da.png)

select one item then shift click

**Comment by mvegaca** [comment]
Fixed on #770

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
