### ISSUE TITLE
Right click: Temp generated not cleaned up when cancelled

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#733]
Wizard Version 0.14.17192.65003

Repro steps:
1. open WTSTempGeneration folder (mine is C:\Users\crutkas\AppData\Local\Temp\WTSTempGeneration)
1. Add new page
1. click next
1. click cancel (you should be on the merge page)
1. folder not deleted

**Comment by mvegaca** [comment]
Fixed on #766

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
