### ISSUE TITLE
Right Click: Merge window loads blank

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#734]
Inconsistent but how it appears to happen is if you 

1. add a feature / page
2. go back
3. select different item

![image](https://user-images.githubusercontent.com/1462282/28085216-de01e23c-662f-11e7-894b-794be6cca956.png)

**Comment by mvegaca** [comment]
I can not reproduce, could you please let me know more details about how to reproduce:
 - Installer or VSEmulator
 - Framework & Project type.
 - First right click and second right click selections.


I was trying on VSEmulator, Dev Branch and different pages and features. CodeViewer control always refreshes selected file code.

**Comment by mvegaca** [comment]
Finally fixed on #780

**Comment by ralarcon** [comment]
@mvegaca, you finally was able to reproduce it using the nightly, isn't it?

**Comment by mvegaca** [comment]
Yes, it's been reproduced also in Installer

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
