### ISSUE TITLE
Right click: open generate folder appears when it shouldn't

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#735]
No generation happened here yet it still is asking me to open the temp dir folder.  if no folders are in the temp dir, it doesn't appear.

![image](https://user-images.githubusercontent.com/1462282/28085454-a29f712c-6630-11e7-84f6-9a1217fbadb5.png)

**Comment by ralarcon** [comment]
What is the expected behaviora here? It open the temp folder because there are some previous generations.

**Comment by crutkas** [comment]
That solution didn't generate any however.  why would i want to go to that folder?

**Comment by ralarcon** [comment]
Well, is just because that is the temp folder, I thought you could be interested in see other generations, for example, if you have multiple wts projects in your solution... anyway, is just a matter of define what makes more sense. I'm fine if we define to open the temp generation folder if there are folders related to the active project.

**Comment by crutkas** [comment]
This is my opinion.  Feels odd.

**Comment by dgomezc** [comment]
We can add the ProjectGuid to the folder name. This way we can detect if a project has generations and if it does not have, disable "Open Generation Folder" button.

![image](https://user-images.githubusercontent.com/12777039/29715294-0045c7f6-89a7-11e7-987f-a94def31eb28.png)

**Comment by ralarcon** [comment]
Maybe at the end would be more readable, or use the proyect guid as a folder and then the "info" (project name and dates) within a subfolder. We can "open" directly at the "info" level.

**Comment by crutkas** [comment]
is the GUID pre or post?

**Comment by dgomezc** [comment]
The GUID is the first level folder. For each project there is a folder containing yours partial generations.

First level:
![image](https://user-images.githubusercontent.com/12777039/29911513-6dca839e-8e2e-11e7-9ff1-065800cf3146.png)

Second level:
![image](https://user-images.githubusercontent.com/12777039/29911517-73755b02-8e2e-11e7-9094-1f6b7d9993d9.png)

open the temp dir folder only appear if guid project folder exists and has content.

![image](https://user-images.githubusercontent.com/12777039/29911630-d3b2b5aa-8e2e-11e7-9668-139c18f1f9b4.png)
![image](https://user-images.githubusercontent.com/12777039/29911651-e83e25ae-8e2e-11e7-8b96-9496d06bc73f.png)

**Comment by crutkas** [comment]
feels weird we know the app name yet are doing it by GUID for the folder

**Comment by ralarcon** [comment]
Yes I now, but the thing is that the app name (the project name) could change, in that case we will miss previous generations... 

Considering we open the content at the "project level" that is, the user will see the content, not the list of guids, we though it was a good balance. Other option is to use the project name and if the user renames it, forgot about previous generations. Not a big deal.

**Comment by crutkas** [comment]
Yup, i get it and understand the "why".  Just voicing my opinion :)

**Comment by sibille** [comment]
Verified on pre-release
Wizard: 0.8.17248.4
Templates: 0.8.17248.4
