### ISSUE TITLE
Summary differences for scrolling

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#736]
Right click and file->new summary scrollbars are at different locations.

**Proposed solution:**
Have same parent container with the license and scroll bar.

![image](https://user-images.githubusercontent.com/1462282/28085685-52541ae6-6631-11e7-8eef-5ac70efaa8d4.png)
![image](https://user-images.githubusercontent.com/1462282/28085712-67cb8ef4-6631-11e7-8abf-001e90eb2070.png)

**Comment by sibille** [comment]
![image](https://user-images.githubusercontent.com/24698018/30061237-e7b3d9c8-9246-11e7-8a64-0faaa18517f1.png)
Verified in pre-release
Wizard: 0.8.17248.4
Templates: 0.8.17248.4

**Comment by mvegaca** [comment]
Checked on:
Wizard: 0.14.17248.65001
Templates: 0.14.17247.1
