### ISSUE TITLE
Duplication: CreateSyncStepsInstructionsPostAction and CreateSyncSummaryPostAction

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#740]
Why do we have duplication.  Feels like CreateSyncStepsInstructionsPostAction and CreateSyncSummaryPostAction are the same.  I tracked this down based on looking at text

```
  <data name="SyncInstructionsTempFolder" xml:space="preserve">
    <value>You can find all referenced files in the temporary generation folder: {0}</value>
    <comment>s</comment>
  </data>

  <data name="SyncSummaryTempFolder" xml:space="preserve">
    <value>You can find the files from the generation in the temporary generation folder: {0}</value>
    <comment>s</comment>
  </data>
```

**Comment by sibille** [comment]
The difference between the two is that CreateSyncStepsInstructionsPostAction is executed when you choose to integrate your files manually and CreateSyncSummaryPostAction is executed when the wizard merges changes from temp folder to project folder for you. 
The first text contains instructions for you to include the files in your project and all files, the second one is a summary of what has been done. 
I think it's important to have the two separated. Maybe I have to change the names a bit to reflect better what each does.

**Comment by crutkas** [comment]
I didn't really see a big difference looking at the code.  I strongly believe the logic can be shared and maybe it is sending two different templates to the class.  Lets work together on rearchitecting this

**Comment by sibille** [comment]
Yeah, logic is very similar, texts and files differ. Shared logic and different templates could work.

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65001
Templates: 0.14.17249.4
