### ISSUE TITLE
Merge MD summary should be a proper template in Resx

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#741]
Right now it is too hard to alter the holistic text from the completed MD file since it is 100% created in code behind.  I feel like this should have a larger resource template that has the needed parts auto generated in.

**Comment by ralarcon** [comment]
We evaluate that but as the MD is quite simple to generate we did it in code... one advantage of using a template is that maybe we can use a HTML template instead of MD.

**Comment by crutkas** [comment]
ref #720 as well.

**Comment by crutkas** [comment]
@ralarcon issue i hit was I had to reference a final version to be able to see the text.  too much overlap and without reading a generated item, it is near impossible to understand what would be outputted.  I am also afraid at how this would localize with the smaller chunks of text.

**Comment by ralarcon** [comment]
We can prioritize it as first after 1.2 issues discovered done if you agree. I think it is not so hard to convert it to a template with replacements

**Comment by crutkas** [comment]
I defer to you guys, i'm on a bug filing spree right now :)  Before we submit files to loc, i think this should be fixed.

**Comment by crutkas** [comment]
the gotcha here also is we are also mixing Markdown inside the resx along with the code behind.  We need to do #740 in the same motion.

**Comment by sibille** [comment]
I think it's a good idea to have template for this. Will be easier to maintain and translate.

**Comment by sibille** [comment]
I was looking at this yesterday and like the fact of using a resx template, but there is a drawback: resx templates do not support iterative or if logic. 
![image](https://user-images.githubusercontent.com/24698018/28307065-e43f5fae-6ba1-11e7-8d9d-5ba1a2187f2f.png)
For example: There is no way to not show the conflicting files section if there are no conflicting files. Also for the modified files section I had to create another template as I had to compose postaction code and strings 
![image](https://user-images.githubusercontent.com/24698018/28307155-35656ebe-6ba2-11e7-8c47-02a218fc5b07.png)
@crutkas: Could we use T4 templates for the summary generation, that would allow us to have one template per generated file?

**Comment by mrlacey** [comment]
Because of the way the output is composed I'm not sure using a template defined in a resource is going to be efficient. We'd need multiple versions for each different combination of output.

Instead, I think it might be better to refactor the code to make it clearer what's happening. The current 92 line function could be broken up to be a lot more readable.

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65001
Templates: 0.14.17249.4
