### ISSUE TITLE
Right-click add options shouldn't be available when debugging

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#742]
When debugging an app it shouldn't be possible to use the WTS menu to add a Page or Feature, just like it isn't possible to add anything to the project via VS at that time.
At the moment the menu options are enabled. They should be disabled when debugging.

**Comment by ralarcon** [comment]
You are right.

**Comment by crutkas** [comment]
marking 1.3, any objection?

**Comment by sibille** [comment]
Verified on pre-release
Wizard: 0.8.17248.4
Templates: 0.8.17248.4
