### ISSUE TITLE
Button highlight remains when tab to complete item rename

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#743]
**REPRO**

- Go to rename an item in the summary
- When entered the new value press the [tab] button

**Expected**
- Name changes and no UI remnants remain

**Actual**
- Highlighting of settings button remains

![image](https://user-images.githubusercontent.com/189547/28089142-e19ddf36-667f-11e7-834b-e8c7e22e8f09.png)

**Comment by mvegaca** [comment]
I think this no still happens in dev. Can you confirm that @mrlacey?

**Comment by mrlacey** [comment]
No longer able to recreate this with the current version in the dev branch
