### ISSUE TITLE
Make "info" button into a control

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#746]
We have this "info" control in multiple places, for consistency it should be the same.  ref #738 as the base for the issue.

I see MainView.xaml and ChangesSummaryView both have this control and i'm assuming it is in other spots as well.

**Comment by crutkas** [comment]
do search for xE946

**Comment by mvegaca** [comment]
Control created on #1003

**Comment by mvegaca** [comment]
Checked on WV: 0.14.17241.65001 - TV: 0.14.17327.2
