### ISSUE TITLE
Local builds: template cache being used by another process

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#747]
IOException: The process cannot access the file 'C:\Users\crutkas\.templateengine\BaseName_Local\0.0\en-US.templatecache.json' because it is being used by another process.

Doing file->new to test stuff and got that inner exception on UpdateTemplatesCache in Microsoft.Templates.Core.Locations.TemplatesSynchronization

first time i've seen it but means some type of threading + file IO issue

**Comment by ralarcon** [comment]
I been able to reproduce it by running a local build and by having one VS instance syncing and other VS instance generating... it is trut that this could happen, but the probability running local builds is much more higher as the local templates repository is always being re-built (updated from the repo templates directory). 

I tried to repro using the nighty but no success. The probability in nightly / production release is much more lower as you will need to make two different instance of VS syncing and generating at the time while the templates become updated, and this will ocurre only when there new content updates are delivered. 

In my opinion we can live with this as the probability to have this behaviors in nightly / production are much lower. By the way, we check automatically every two hours if there is new content. I will change the time window to 24 hours (it is more probably now to have a Wizard version update -with content- than a templates content update).

**Comment by crutkas** [comment]
ok, lets punt to backlog to look into this.

**Comment by ralarcon** [comment]
Solved in #1187.

**Comment by sibille** [comment]
Verified in dev-nightly: 
Wizard: 0.14.17283.65001
Templates: 0.14.17283.1
