### ISSUE TITLE
Accessiblity: Icon buttons need tooltips

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#748]
Icon style buttons such as an i or gearbox need tooltips to aid in discoverability.

**Comment by dgomezc** [comment]
Update on  #811.

**Comment by dgomezc** [comment]
I think we also add tooltips on generation applications in following situations:
- Split view project open/close button.
- Split view project page element.

I think we can add a new string resource, i.e. settings page:
- Shell_Settings: Settings (Shell, and narrator)
- Settings_Title.Text: Settings (Page title)
- Tooltip_Settings: Settings (mouse tooltip)

**Comment by dgomezc** [comment]
In the main button of the hamburger menu the narrator says "Main Button". This text is not customizable.
The narrator works correctly on our pages (master-detail, map, pages with telerik controls,etc).

**Comment by mrlacey** [comment]
For future reference, I'd have preferred to have seen the changes to the generated projects created as a separate, but linked issue. 
If this had been done here, the original issue could have been closed out a month ago and I wouldn't have wasted time working out why changes to the generated projects reference an issue about changes to the wizard.

**Comment by crutkas** [comment]
@mrlacey  agreed, this was actually for the wizard.  not generated apps.

**Comment by dgomezc** [comment]
@crutkas @mrlacey ok, I will keep it in mind next time.

**Comment by sibille** [comment]
* and - buttons in right click wizard are missing tooltip

**Comment by mvegaca** [comment]
Done on #1077

**Comment by dgomezc** [comment]
'+' and '-' buttons are hidden #721.

**Comment by dgomezc** [comment]
Verified on dev-nightly
Wizard: 0.14.17249.65002
Templates: 0.14.17249.10
