### ISSUE TITLE
Right click: license alignment

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#749]
![image](https://user-images.githubusercontent.com/1462282/28093245-55deb238-664b-11e7-905e-61729ebbc9a0.png)

**Comment by mvegaca** [comment]
Fixed on #764

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
