### ISSUE TITLE
Commenting Resx file

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#756]
We really need to comment the resx file, i'm hunting for context here where stuff is being displayed.

**Comment by mvegaca** [comment]
Comments added on #1057

Pull request is open waiting for any grammar correction if it would be necessary.

**Comment by mvegaca** [comment]
Its a sample of a Resx file on generated project.

![image](https://user-images.githubusercontent.com/5556784/29969725-b3c30c6a-8f21-11e7-9d97-cdb71010df3a.png)

**Comment by mrlacey** [comment]
I thought this issue was for commenting the RES**X**  in the wizard project.
The generated code uses RES**W** files and already has names that explain their usage fairly well.

@crutkas can you confirm?

**Comment by crutkas** [comment]
this was for wizard, I strongly believe any resource in the templates also must have a comment to help provide context

**Comment by mvegaca** [comment]
Fixed on #1061

**Comment by mvegaca** [comment]
Now resx files have comments for each string resource

![image](https://user-images.githubusercontent.com/5556784/30050724-c1021528-921f-11e7-979a-6fc580242fbf.png)

**Comment by dgomezc** [comment]
All resources in wizard are commented. All resw generated resources are commented except the key "UriSchemeExample_Title.Text".
