### ISSUE TITLE
Unify templates for community and MSFT in summary window

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#758]
Noticed this in #713.  No need for these to be different templates.  They function exactly the same.

NewProject/MainView.xaml
* templateSelectors:SummaryItemTemplateSelector.MicrosoftTemplate
* templateSelectors:SummaryItemTemplateSelector.CommunityTemplate

**Comment by mrlacey** [comment]
Also, I don't think we need to call out the different authors in the summary pane. 
IMHO, it doesn't add anything and takes up a lot of space.

**Comment by crutkas** [comment]
works for me.  I'm all about simplifying.

**Comment by mvegaca** [comment]
Updated on PR #1021

**Comment by mvegaca** [comment]
Fixed! Checked on
Wizard: 0.14.17242.65001
Templates: 0.14.17242.2
