### ISSUE TITLE
Summary for rightclick add: horizontal scroll bars showing

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#760]
![image](https://user-images.githubusercontent.com/1462282/28103074-a764dafa-6688-11e7-9ff7-dad520247dc1.png)

Adding in new feature to an existing project and it appeared.  It is on both page and feature right click add.

Happens in my nightly and dev branch.  I did **NOT** notice this today testing most of the day on my desktop.  This could mean DPI related.  This laptop is set to 150% DPI.

**Comment by mvegaca** [comment]
Fixed on #763
Too long file name could also read on item tooltip, perhaps, we could think on make list with resizable like Visual Studio.  :)

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
