### ISSUE TITLE
Summary "title" feels out of place being bold

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#761]
The bold feels out of place for a title.  We don't use it anywhere else for a H2 style header.  I feel like it should match the Summary header.

![image](https://user-images.githubusercontent.com/1462282/28086673-a8e2c396-6634-11e7-995b-0885c86196ce.png)
![image](https://user-images.githubusercontent.com/1462282/28103540-1f7d4a8e-668b-11e7-8f0a-639bf7134d98.png)

**Comment by mvegaca** [comment]
Checked on:
Wizard Version - 0.14.17194.65002 
Templates Version - 0.14.17194.2

Issue fixed and closed.
