### ISSUE TITLE
LiveTile Feature needs improved default activation handling code

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#772]
The default Live Tile code includes just comments in the `HandleInternalAsync` method in `ToastNotificationsService`. This is potentially confusing if you use the toast to launch the app and haven't modified this method. (It confused me.) Because it doesn't navigate anywhere once the app is launched it looks broken.

![image](https://user-images.githubusercontent.com/189547/28114749-0b81a3da-66fa-11e7-8377-ec323c7a08ce.png)

I think we should extend the sample code to include calling the NavigationService to go to the home page and include comments about querying the event args to determine where to navigate to and possibly passing params too.
_I'm aware that trying to go to the "home" page from right-click add of this feature might be an issue though._

**Comment by mvegaca** [comment]
I don't think that feature template must be modified, I think that we could do a sample that uses LiveTile and notifications and implements custom activations.

**Comment by crutkas** [comment]
@mvegaca lets discuss before instantly jumping to action.

**Comment by mvegaca** [comment]
One possibility could be to use [TasksApp Sample](https://github.com/Microsoft/WindowsTemplateStudio/tree/dev/samples/suspendandresume/TasksApp) adding LiveTile feature to show different tasks. When the livetile is clicked open the app making the task on the livetile as active.
On this case, TasksApp sample would be a sample of suspend and resume and live tile features

**Comment by mrlacey** [comment]
My issue here is that the code we generate by default seems, to me, to be incomplete. It doesn't create a working app.
Having been through lots of confusion with the way the ActivationService works while implementing #506 (protocol launch) I know there are a lot of potential issues with implementing this.

To say that this isn't a problem feels like you're saying that no-one else will have a problem with this. I may not be the smartest person in the world but I'd be amazed if everyone else who ever tries to use this feature has no problems, questions, or confusion that we can't help with by extending what's in the generated code.

To just have a sample that shows a complete version of this feels like we'd be saying "this code isn't complete but you can see a finished version at XXX." This feels very short of the mark for what we should be outputting.

**Comment by ralarcon** [comment]
I agree with @mrlacey but at the same time I think that any code added to the Live Tile service to showcase the navigation will be needed to be removed as it will be sample code (the way to navigate or show a pop-up using the args). 

Complementing the current Live Tile feature with some documentation referenced in the "TODOs" will help users for sure. 

Other approach would be to add a new feature to showcase the Live Tile in action... the "Live Tile with Activation Handling" feature would contain all the pages / data / implementatons required and will have a dependency to the Live Tile feature allowing users to "see how this works"...

**Comment by mvegaca** [comment]
A good idea here could be adding a little documentation for extending LiveTile feature as I've done with [notifications](https://github.com/mvegaca/WindowsTemplateStudio/blob/a726a1a5f8a0a73379df8b22e39e889e4fd97caf/docs/notifications.md) in PR #1238

**Comment by ralarcon** [comment]
Moving to 1.5 as we are waiting for PR review.

**Comment by sibille** [comment]
Removed Can Close Out Soon while figuring out how to accomplish this

**Comment by ralarcon** [comment]
@crutkas @mrlacey do you think would be enough by now reviewing and fixing the documentation we currently have or we should close the PR and create a new approach? If we are not going to approve the PR, this needs to be moved to the backlog and the close the PR.

**Comment by ralarcon** [comment]
Moving to backlog.

**Comment by sibille** [comment]
Fixed as part of #1097
