### ISSUE TITLE
Blurry VS style icons on right click add summary

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#784]
From current dev branch from 17.07.12.  This is in the nightly as well.  I verified this change happened between the two nightly builds

c#, csproj icons, here

![image](https://user-images.githubusercontent.com/1462282/28126539-95016ada-66de-11e7-9aed-44a8370db8fb.png)

![image](https://user-images.githubusercontent.com/1462282/28126512-82305ab0-66de-11e7-9bd7-9e556a516c54.png)

**Comment by crutkas** [comment]
this is the check-in that caused it.
https://github.com/Microsoft/WindowsTemplateStudio/pull/768

**Comment by mrlacey** [comment]
The highlighted area in the OP also shows that icons are of an inconsistent width and so puts the text out of alignment.
Icons should all be the same width or spaced to appear the same.

**Comment by crutkas** [comment]
yeah, noticed that, working on fixing this now

**Comment by crutkas** [comment]
ok, so old icons still actually rendered blurry but not as bad but they lacked a few things that caused this.

My gut says this is due to DPI on the actual images

![image](https://user-images.githubusercontent.com/1462282/28140104-c4233686-670b-11e7-9a83-ce873d79e09a.png)

**Comment by crutkas** [comment]
yup, confirmed.  both image sets are 72dpi.  not 96.

**Comment by crutkas** [comment]
the IMG adjustments put a border around it which does improve what you see there, however they are still 72 dpi

**Comment by crutkas** [comment]
may want to shift to high quality after looking at it on a high DPI screen but works
