### ISSUE TITLE
All unchanged files when adding in a new page?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#785]
I added in a new page with a charting page.  Nothing changed but feels like an error should have been presented somehow.

![image](https://user-images.githubusercontent.com/1462282/28131281-456e5770-66ee-11e7-9eb8-4570a40d7cbf.png)

**Comment by ralarcon** [comment]
We removed the warning feedback saying that everything was already in the project as per #596. Probably we misunderstood something. 

Clarification requested here!

**Comment by crutkas** [comment]
My issue is i think the info / warning prompt needs to be rethought as it covers up critical information.  My feedback on #596 was just that.  I did state that we were providing too many updates.

The issue here is a VS right click add wouldn't allow me to name a file the same thing.  

Maybe we should rethink this for 1.3

**Comment by ralarcon** [comment]
@crutkas Do you think we can add the warning message again and rethink how to improve this for 1.3?

**Comment by mvegaca** [comment]
Move this to 1.4?

**Comment by crutkas** [comment]
moved.  this is low hanging work items

**Comment by mvegaca** [comment]
My idea here is to hide close button if there are no changes to apply. On that situation, the user can only go back or cancel the new item wizard. I've planned to add a status informing this situation.

Working on it on a different branch. Any suggestions here?

**Comment by crutkas** [comment]
This also should have thrown an error before i got here as there was a conflict in the same page.  Adding a page that already exists feels like it should have failed

**Comment by ralarcon** [comment]
The truth is that sometimes you can add some new features and have files unchanged because already exists from other additions. 

I think that having only the options cancel / back and adding an informative / warning message should be enough.

**Comment by crutkas** [comment]
@ralarcon, there is no time i should have a 100% zero total change.  That is what this is stating.  I have zero new files, zero removed files, and zero files modified.

**Comment by ralarcon** [comment]
You are right, we opted to show the un-changed to allow you to understand that the request do not make any change in your project. 

We can try the following.
* Before navigating to the "Changes Summary" page, if there is 100% of unchanged files, we will block the navigation and show a warning status message indicating that the page / feature name selected already exists in the project... 

@crutkas, Is that ok?

**Comment by crutkas** [comment]
i defer to your best judgement :)

**Comment by dgomezc** [comment]
Verified in dev-nightly:
Wizard: 0.14.17284.65001
Templates: 0.14.17284.1
