### ISSUE TITLE
Right Click: Margins off in summary

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#786]
![image](https://user-images.githubusercontent.com/1462282/28131699-95af88ac-66ef-11e7-8923-803705e7c5c2.png)

left side and top differ.

**Comment by mvegaca** [comment]
Fixed on #994

![image](https://user-images.githubusercontent.com/5556784/29616921-52427fee-8813-11e7-882f-e2020256a82c.png)

**Comment by mvegaca** [comment]
Checked on WV: 0.14.17241.65001 - TV: 0.14.17327.2
