### ISSUE TITLE
License summary overlays "None" in when wizard first opened

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#788]
Repro:
- Open wizard

Expected:
- "None" label should not be visible

Actual:
It is!

![image](https://user-images.githubusercontent.com/189547/28137548-9875dd88-6745-11e7-9a3f-a5059276aa1d.png)

in Dev Nightly

wizardVersion=0.14.17193.65002
templatesVersion=0.14.17193.13

**Comment by mvegaca** [comment]
Works fine on:

Wizard: 0.14.17194.65001
Templates: 0.14.17193.15

I update this part of wizard yesterday on PR #778

**Comment by sibille** [comment]
Verified on Wizard: 0.14.17198.01, Templates: 0.14.17197.01
