### ISSUE TITLE
Whats new prompt template does not take blue color when its selected

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#796]
![image](https://user-images.githubusercontent.com/5556784/28162741-6fd1b9fa-67c8-11e7-8462-f6b785a79d07.png)

**Comment by mrlacey** [comment]
Code for setting highlighting assumed that the image was either made of Paths or Shapes. This was just the first icon to use a combination of the two.
Can now support either or both (which I expect will be needed again in the future.)

![image](https://user-images.githubusercontent.com/189547/29244077-53fd4b08-7fa7-11e7-9662-a35a538adaad.png)

**Comment by mrlacey** [comment]
merged in and now all good
