### ISSUE TITLE
Cancelled add wizard still opens the 'step to include...md' file when cancelled

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#797]
**Repro**
- Create any project with WTS
- Use the right-click menu to add a page
- Select any page and then tap 'Next'
- Cancel the wizard using the X in the top right-hand corner of the window.

**Expected**
- Nothing

**Actual**
- The 'Steps to include new item generation.md' file is opened in VS.

**Notes**
- Also happens when adding a feature.
- Happens if go to the summary page and then go back but not if you cancel before pressing 'Next'.
- Doesn't happen if press the "Cancel" button.

Low priority, edge case, so recommending for v1.3

**Comment by crutkas** [comment]
agreed w/ 1.3.  Good testing!  I've always hit the cancel or esc

**Comment by sibille** [comment]
Right click wizard does not merge changes and open md files

**Comment by sibille** [comment]
Verified on pre-release
Wizard: 0.8.17249.1
Templates: 0.8.17249.1
