### ISSUE TITLE
Ink template scenarios

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#799]
Figure out 3 to 4 scenarios we can build Ink templates.  One would be basic drawing but there is so much more we can do here.

**Comment by mrlacey** [comment]
scenario idea:
- Load an image and annotate

**Comment by crutkas** [comment]
That is the basic drawing scenario IMO :)

**Comment by jamesmcroft** [comment]
Would we be interested in building a scenario that includes a signature control potentially? It's a control that I use often in LoB apps

**Comment by crutkas** [comment]
Sure. I would say let's spec that out and see if that isn't a UWP comm toolkit control and we do a nice wrapper on it

**Comment by jamesmcroft** [comment]
If it doesn't exist, I'm more than happy to lift a signature control into the UWP Community Toolkit and as you've said, provide an experience for the template studio that takes advantage of it.

**Comment by gcaughey** [comment]
Great idea. LOB apps often need that. Would the result be a base 64 encoded string? That's the way I usually store them.

**Comment by crutkas** [comment]
@jamesmcroft I think the control should live in the Toolkit and we just are a nice easy way to consume with everything wired up.  That helps out much more of the community and provides hot fixes when needed.

That is typically the handshake myself and @nmetulev have.

**Comment by crutkas** [comment]
- Take picture, annotate, save picture w/ ink, save & load ink
- Load image, annotate, save picture w/ ink, save & load ink
- signature control

**Comment by crutkas** [comment]
Two more scenarios: 
Smart Object Ink canvas
- Ink canvas w/ automatic conversion to shape and hand writing
- Select / move ink w/ custom dry

Ink Canvas
- Select / move ink w/ custom dry

Verifying if these are Fall creators update only

**Comment by crutkas** [comment]
created issues
