### ISSUE TITLE
Do we have lost or removed the Open Generation Folder icon?

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#800]
![image](https://user-images.githubusercontent.com/2638875/28184769-fc007410-6814-11e7-96b1-e8f3f2fc36e0.png)

Nightly Version: 0.14.17194.65003

**Comment by sibille** [comment]
I think that was me! 
I removed the WTS icon from too many places. Has to be in the iconlist to correctly show the folder icon. 
See PR #802

**Comment by sibille** [comment]
Verified on Wizard: 0.14.17198.01, Templates: 0.14.17197.01
