### ISSUE TITLE
When the child page got a CommandBar, the NavigationMenu on Shell page will not respond to the fist click

### ISSUE THREAD

**Issue by EdiWang** [Microsoft/WindowsTemplateStudio#804]
**Steps to reproduce:**
1. Create an App with "**Navigation Pane"** template, and add serveral blank pages. (e.g. Main, Page1, Page 2, Page 3)
2. Add a **CommandBar** to any one of the child page (e.g. Page1), it can be page level or in the gird, e.g:
```
<CommandBar Grid.Row="2" DefaultLabelPosition="Right" IsOpen="True" VerticalAlignment="Bottom">
    <AppBarButton x:Name="BtnLoadPicture" Icon="Pictures" Label="Load Picture" Click="BtnLoadPicture_OnClick" />
    <AppBarButton x:Name="BtnSave" Icon="Save" Label="Save" Click="BtnSave_OnClick" />
</CommandBar>

```
3. Run the App
4. Click the navigation menu to switch around pages.

**Expected:**
Each page can be opened by a single click on the menu.

**Actual:**
When navigated to the page with CommandBar (Page1), and then click the other menu in the navigation bar, the menu will not respond to the first click (even not hover).

Note: It happens to both mouse click and touch, on either desktop or phone. By click any where on the child page can re-enable the navigation menu.

**Comment by EdiWang** [comment]
Found the cause: IsOpen="True"

I am stupid. Please close this issue....

**Comment by mrlacey** [comment]
@EdiWang glad you found a solution
