### ISSUE TITLE
Check in to masters kick off proper build sequence

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#805]
if we do a merge from dev to master, why don't we just auto kick off a build?  It won't auto deploy due to the code-signing step but would save us the step of waiting for builds to complete.

**Comment by sibille** [comment]
We did not do this to have major control about the version number in pre and pro environment.

**Comment by crutkas** [comment]
wouldn't that be part of the sequence and validation?  increasing #?  I think another part of this would be to do a full template AND extension in one shot versus manually having to do both.

**Comment by crutkas** [comment]
I think this should do a pre-release and master build.
