### ISSUE TITLE
Typo in ProjectConfigInfo

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#806]
ProjectConfigInfo contains a typo in the method `IsMVVMBasic`

`return ExistsFileInProjectPath("Services", "ActivationServiHace.cs")`

should be 

`return ExistsFileInProjectPath("Services", "ActivationService.cs")`

**Comment by crutkas** [comment]
This looks like a must fix then for 1.2

**Comment by sibille** [comment]
Yeah, I think we should include this for 1.2

**Comment by crutkas** [comment]
How did a unit test not catch this?
