### ISSUE TITLE
Telerik Chart Control axes & labels not visible in Dark Theme Setting

### ISSUE THREAD

**Issue by rg-burton** [Microsoft/WindowsTemplateStudio#808]
If you create an App with the Telerik Chart control and run it then go to settings and switch the Theme to Dark, the Grid for the Telerik Chart control (Axis and Labels) is no longer visible.

**Comment by mrlacey** [comment]
verifying extent of this now

**Comment by mrlacey** [comment]
Confirmed in v1.1
Confirmed in v1.2 (release preview & DevNightly)

**Repro**
- New Project: NavPanel & CodeBehind (doesn't really matter, works with all combinations)
- Add Chart Page
- Add Settings
- Create project
- run generated project
- go to settings page and change the theme to dark
- go to chart page

**Expected**
- Should be able to see axis and labels (white on dark gray)

**Actual**
- Axis & labels are black on dark gray


**Needs a hotfix for v1.2** might take me a few hours. Anyone else is welcome to jump in on this if able.

**Comment by mrlacey** [comment]
Changing title to make it clear this is the CHart page, not the Grid page.
Grid page does not have any theme issues AFAIK

**Comment by crutkas** [comment]
Great catch.  I will try to work in a fix before we ship. Worst case we hot fix. For Tuesday. Which would actually be a good out of band test too :)

**Comment by mrlacey** [comment]
**Workaround**
Set the axis definitions to match the below

    <tc:RadCartesianChart.HorizontalAxis>
        <tc:CategoricalAxis Foreground="{ThemeResource SystemControlForegroundBaseHighBrush}">
            <tc:CategoricalAxis.LineStyle>
                <Style TargetType="Line">
                    <Setter Property="Stroke" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                </Style>
            </tc:CategoricalAxis.LineStyle>
            <tc:CategoricalAxis.MajorTickStyle>
                <Style TargetType="Rectangle">
                    <Setter Property="Fill" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                </Style>
            </tc:CategoricalAxis.MajorTickStyle>
        </tc:CategoricalAxis>
    </tc:RadCartesianChart.HorizontalAxis>
    <tc:RadCartesianChart.VerticalAxis>
        <tc:LinearAxis Foreground="{ThemeResource SystemControlForegroundBaseHighBrush}" >
            <tc:LinearAxis.LineStyle>
                <Style TargetType="Line">
                    <Setter Property="Stroke" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                </Style>
            </tc:LinearAxis.LineStyle>
            <tc:LinearAxis.MajorTickStyle>
                <Style TargetType="Rectangle">
                    <Setter Property="Fill" Value="{ThemeResource SystemControlBackgroundBaseMediumBrush}"/>
                </Style>
            </tc:LinearAxis.MajorTickStyle>
        </tc:LinearAxis>
    </tc:RadCartesianChart.VerticalAxis>

**Comment by mrlacey** [comment]
Here's how the issue presents

![image](https://user-images.githubusercontent.com/189547/28251345-1c5617e6-6a73-11e7-9f94-da04779214ac.png)


Here's how it looks with the fix

![image](https://user-images.githubusercontent.com/189547/28251336-dca374fe-6a72-11e7-9f39-25739d850f0c.png)

And with fix in light mode

![image](https://user-images.githubusercontent.com/189547/28251351-2fce1292-6a73-11e7-9366-5f8f3caa3209.png)

**Comment by rg-burton** [comment]
Thanks for the VERY quick response and answers.  Great work!

**Comment by crutkas** [comment]
@mrlacey. I feel like we should report this to telerik as this should work out of the gate. The fix works but as is not our fault.

**Comment by crutkas** [comment]
Thoughts on including into 1.2 or do a hot fix on Tuesday?

I do like actually verifying getting new templates out of band

**Comment by mrlacey** [comment]
I'm not sure it's a Telerik bug rather a feature. None of the Telerik controls have theme awareness.
It's my bug. I put something with fixed colors on a background that changes.
As this exists in 1.1 I don't think this fix has to get into the 1.2 release.  If that helps test hotfix releases then that's a benefit.

**Comment by sibille** [comment]
We can do both, ship with 1.2 or make an out of band fix. I'd include it with 1.2 as we should include #806 and have to generate a new version for this.

**Comment by crutkas** [comment]
Shouldn't there controls out of gate be theme aware however?

**Comment by gcaughey** [comment]
Should be. I'd agree this seems like a bug on their side.

**Comment by mrlacey** [comment]
I have raised the issue on the Telerik repo. Let's see what they say...

**Comment by crutkas** [comment]
merged fix into 1.2 hotfix branch.

**Comment by mrlacey** [comment]
bug confirmed by Telerik

**Comment by mrlacey** [comment]
Still not in dev nightly
    <genTemplate:Item Name="wizardVersion" Version="0.14.17199.65001" />
    <genTemplate:Item Name="templatesVersion" Version="0.14.17199.1" />

**Comment by crutkas** [comment]
just did the merge request from 1.2 hotfix.

**Comment by crutkas** [comment]
@rg-burton the fix is now in production :)

**Comment by rg-burton** [comment]
Verified.. it does work correctly now!  Thanks for the work!

**Comment by crutkas** [comment]
When we know of an issue, we do our best to solve it ASAP :)
