### ISSUE TITLE
Hidden features should be deleted from summary if there is no pages or features that depends on it.

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#810]
1 - Added a Chart Page.
2 - Deleted this Chart Page.
3 - SampleData feature still on Summary with no chart pages added.

![image](https://user-images.githubusercontent.com/5556784/28259015-85eeede8-6ad4-11e7-8210-39e87e5cda97.png)

**Comment by crutkas** [comment]
I feel like this should have a unit test against it.

**Comment by mrlacey** [comment]
There should be a generic test for removing items with dependencies.
This probably warrants an extra test for hidden templates. (I expect there's a check against a list of templates which doesn't include hidden ones.)

**Comment by mvegaca** [comment]
Added the code to remove hidden templates if no one templates depend on it. #1022

**Comment by crutkas** [comment]
@mvegaca this was merged in

**Comment by mvegaca** [comment]
Checked on
Wizard: 0.14.17244.65002
Templates: 0.14.17244.2
