### ISSUE TITLE
Unit Test due to Typo in ProjectConfigInfo

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#816]
Typo in ProjectConfigInfo #806

I feel like a unit test should have caught this typo early.

**Comment by ralarcon** [comment]
Yes, that right. I'll add it asap.

**Comment by mrlacey** [comment]
What's the plan for adding this unit test? Seems it should really validate the contents of all config files.

**Comment by mrlacey** [comment]
We'll also need a more thorough tool for verifying templates when we start to allow other people to add their own. I have a bunch of ideas for this based on similar work I've done in the past.
This might make this issue redundant as we could just have a test that runs the tool against the official templates.
Also a good reason for punting this issue to a future milestone....

**Comment by sibille** [comment]
Test name is GenEmptyProjectCorrectInferProjectConfigInfoAsync, included in commit 77d09d84
