### ISSUE TITLE
Template Studio no suports  DefaultLabelPosition commandbar

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#817]
The template studio supports the DefaultLabelPosition tag of CommandBar gives me error is not available for SDK 10586 when we have installed 10.0.14393.0

**Comment by crutkas** [comment]
we don't use a command bar anywhere to the best of my knowledge.  Can you provide a repro?

what is the min/target of your project?

**Comment by crutkas** [comment]
@Javier118 for general questions, please post those questions on www.StackOverflow.com.  If you want, reach out to me on twitter @clintrutkas once you did that.

That way general questions, the it helps out the community as we can really only support questions and issues relating to only Windows Template Studio on our github.
