### ISSUE TITLE
Missing French translation

### ISSUE THREAD

**Issue by DadvDadv** [Microsoft/WindowsTemplateStudio#821]
## For new Features:

* **Overview:** The menu in "New Project" is in english and should be in french
* **Links:**

### Repro steps

- Open a french version of VS
- Go to the "Fichier"  (File) menu
- Select "Nouveau Projet" (new project)
- Open the tree "Installé/Modèle(s)/Visual C#" (Installed/Model(s)/Visual C#)
=> 
Now you see 2 menu : 
- "Windows universel" (the french version)
- "Windows Universal" (the english version)

### Expected Behavior

Only one menu should be present, the french version : "Windows universel"

### Actual Behavior

There are 2 menus :
- "Windows universel" (the french version)
- "Windows Universal" (the english version)

## System

* **VS Version:**
 2017 
* **WTS Wizard Version:** 
?
* **WTS Template Version:** 
15.2.45.1736
* **Windows Build:**
1703

**Comment by crutkas** [comment]
We are localizing in 1.3.  We did a lot of work under the hood in 1.2 to be sure we can fully localize

**Comment by sibille** [comment]
Although we did not yet add in the translations for all supported languages the Windows Template Studio should now appear in the correct category. 

![image](https://user-images.githubusercontent.com/24698018/30118799-3e3d16c8-9324-11e7-8b15-e4f45b52e50c.png)

I tested with version 1.2.17198.1. I'll close this issue, please doublecheck and reopen if this is still happening after updating to version 1.2.
