### ISSUE TITLE
Re-categorize features

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#827]
**Overview:** I feel we can better categorize these.  We have grown a lot in the last 3 releases and will continue to add in new features in this and future releases.

My thoughts initial would be breaking out 

- Notifications
- User Enhancement Controls
- Life cycle enhancements
- Background work
- App to App (Drag and Drop, Share contract) (not thrilled with name)

Anything i'm missing

**Comment by mrlacey** [comment]
Can we get a list of features (current and planned) and work out which categories they should all go in as a guide for this? #Lazy

**Comment by mrlacey** [comment]
Ok, not lazy

**Existing**
- First Run prompt
- What's new prompt
- Background Task
- Live Tile
- Suspend & Resume
- Settings Storage
- Dev Center notifications
- Toast notifications
- Hub notifications

**Planned**
- Drag & Drop target
- Share target
- Share Source
- Schema launch of app
- Handling of specific file extension
- Sign In with Windows Hello (possibly a page)
- OneDrive integration (somehow)
- Background audio player
- Add Unit test project
- Add UI test project
- Exception logging
- Launch feedback hub
- Project Rome integration
- Cortana skill/voice command
- SQLite
- Remote data source
- Authentication (probably a page)

**Comment by mrlacey** [comment]
Given the above list, I'd divide them up like this:

**App Lifecycle**
- Suspend & Resume
- Exception Logging

**Background Work**
- Background Tasks
- Background Audio Player

**User Interaction**
- First run prompt
- What's new prompt
- Live Tiles
- Toast Notifications
- Dev Center Notifications
- Hub notifications
- Launch feedback hub

**Data**
- Settings Storage
- OneDrive Integration
- SQLite
- Remote Data Source

**App to App**
- Drag & Drop target
- Share source
- Share target
- Schema launch
- File extension handling
- Project Rome
- Cortana skill/voice command

**Authentication**
- Windows Hello
- Authentication

**Testing**
- UI Testing
- Unit testing


_Of course, the order of the groups and within each group are separate issues_ 😉

**Comment by crutkas** [comment]
- I feel like notification could be broken out into its own w/ 3 items.
- App2App would like to figure out how to better name this but feel like the grouping is solid.

Missing:
- Drag and drop source [app2app]
- App2Website [App2app]
- Activity API [rename Project Rome, App2App]

**Comment by michael-hawker** [comment]
It'd be nice to see a Most Recently Used / Most Frequently Used (option) File Service that also wraps the Future Access List.  Maybe give it static wrappers around the file picker, so whatever the user picks just get auto-added to the tracking and then it exposes a collection of the MRUs.

ref: https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders

**Comment by crutkas** [comment]
@michael-hawker new request == new issue :)  Great idea but out of scope for this issue.

**Comment by crutkas** [comment]
This is related to #607 as well IMO

**Comment by ralarcon** [comment]
Do we should proceed with the reorganization for the current features? Consider that for 1.4 will only have a couple of new feature (Uri Schema and Feedback hub).

**Comment by mrlacey** [comment]
UriScheme was added in 1.3
If the feedback hub link is the only addition in this release then it can be pushed back but there are four other features still planned for 1.4. If they're going to be done then this should be done too.

**Comment by ralarcon** [comment]
We currently have some uncertainity regarding the ability to finish the other features within the next two weeks. We could hold this and check it next week.

**Comment by ralarcon** [comment]
Moving to 1.5

**Comment by sibille** [comment]
Did not change Settings Storage to Data yet, to not have two categories (App Lifecycle and Data) with only 1 Template

**Comment by sibille** [comment]
Will we stay with AppToApp or are there any other suggestions? (App Interaction maybe?) 
We'll also have to establish internal order for the AppToApp category.

**Comment by michael-hawker** [comment]
@sibille how about 'Inter-App Communication'?  App Service would be a good one for that list too.

**Comment by crutkas** [comment]
Let’s create an issue dedicated for the app 2 App naming.  I do agree it is too limiting but it does have a lot there.

**Comment by sibille** [comment]
Assigning to Milestone 2.0 as work for 1.5 is done.

**Comment by crutkas** [comment]
this is done
