### ISSUE TITLE
dev template branch test timing out

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#828]
### Repro steps

Look at build server, dev.templates failing due to taking more than 10 minutes.

**Comment by sibille** [comment]
Build is taking longer due to adding stylecop tests, raising timeout to 20 min.

**Comment by mrlacey** [comment]
I thought Raul split the tests from the build step when they were taking a long time previously. 
Time to run tests can only be expected to get bigger. VB support will approx double it!

**Comment by sibille** [comment]
There are the two types of tests, the ProjectGeneration tests, that are executed before templates are published and the OnebyoneItemGeneration tests, that are executed in another build
