### ISSUE TITLE
Master Detail should have an image in it

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#829]
## For new Features:

**Overview:** We used to have an image on the master detail page.  For FCU, this would be critical IMO to show off some of the header work along with connected animation.

I would suggest we include 2 to 5 small images and reference those.  Another idea is to have those images be hosted on GitHub.

This is in reference to #444

**Comment by mrlacey** [comment]
A possible alternative to not including arbitrary images would be to use a placeholder based on the name like the People app does for contacts who don't have photos.

**Comment by crutkas** [comment]
yeah, could use the app logo

**Comment by mrlacey** [comment]
although, I can think of some other possible uses for random images inside the sample data...

**Comment by crutkas** [comment]
should we ship images with or have it pull from a CDN?  I think no matter what the images should be repeatable (versus random) for debugging.

nice thing about pulling from a CDN is we can also have a few larger images and they don't bloat the template package size.

Downside is no offline but i believe a bit more realistic for usage.

**Comment by mrlacey** [comment]
@crutkas does Microsoft have a collection of royalty free stock images we could host somewhere (github?) and include reference to in the SampleDataService?

**Comment by crutkas** [comment]
my gut says yes as UWP Toolkit's sample uses a bunch.

**Comment by crutkas** [comment]
my work around in the past was to take pics myself and use those :)

**Comment by gcaughey** [comment]
Build speakers had access to a bunch to use in slides, etc. I'm not sure how to access those now though.

**Comment by mrlacey** [comment]
Would the use of [identicons](https://en.wikipedia.org/wiki/Identicon) be sufficient images?

**Comment by mrlacey** [comment]
> my gut says yes as UWP Toolkit's sample uses a bunch.

@skendrot you're listed as a contributor of [those images](https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/Microsoft.Toolkit.Uwp.SampleApp/Assets/Photos). Do you know their origin and copyright?

**Comment by crutkas** [comment]
#1164 is a superset of this now.
