### ISSUE TITLE
Why is Identity in template.json localized?

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#832]
In the localized versions of `template.json` there is an entry for `"identity"` but I can't see why this would ever be localized.
Can this be removed from the culture specific files?

**Comment by sibille** [comment]
Nop, it's the identifier for localization of dotnet templating to work. See [dotnet Templating ILocalizationModel.cs](https://github.com/dotnet/templating/blob/ca51a6209f335c07b64d8bef01560829295cbf73/src/Microsoft.TemplateEngine.Abstractions/ILocalizationModel.cs)

**Comment by mrlacey** [comment]
😢  this has implications for #371 - will need to make changes there relating to localized file syncing based on this. #ThisCommentForReference

**Comment by sibille** [comment]
Sorry :( Maybe we could ha a convention for identity, like wts.Page.Blank.CSharp and wts.Page.Blank.VB.
The example template from [template engine](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) has that identity format, too
Would that help?

**Comment by mrlacey** [comment]
I already have such a convention but the identity field means I can't just copy the translated file from the CS folder. It needs modifying too.
