### ISSUE TITLE
Configure token GitHubDocsUrl  in builds 

### ISSUE THREAD

**Issue by sibille** [Microsoft/WindowsTemplateStudio#836]
Configure token GitHubDocsUrl  in builds to be replaced according to environment. 
https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/docs/ for dev
https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/ for pre and pro

**Comment by sibille** [comment]
Do this once #837 is in dev, issue was #681

**Comment by dgomezc** [comment]
Do in #1051
