### ISSUE TITLE
Folders created on disk even if Wizard is cancelled or backed out

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#84]
**Repro**
- From the New Project window select the template based project.
- Default app name will be like "App5"
- Press OK
- Get taken to the Wizard.
- Press Cancel
- Back on the New Project window

**Actual**
- Default app name is now "App6" (one number higher)
- Empty folders have been created on disk based on the project (and solution) name

**Expected**
- default name still "App5" and nothing created on disk

Nothing should be created on disk until the wizard is complete.

**Comment by ralarcon** [comment]
Verified in nightly build 0.14.17146.65001
