### ISSUE TITLE
Async methods should be named with the Async suffix

### ISSUE THREAD

**Issue by jlnostr** [Microsoft/WindowsTemplateStudio#844]
I've created a new project with the Windows Template Studio. However, the async methods aren't named like that. Async methods should **always** use the `Async` suffix wherever possible.

**This is wrong:**

    public class FirstRunDisplayService
    {
        internal static async Task ShowIfAppropriate()
        {
            ...
        }
    }

**This is the recommended way to go:**

    public class FirstRunDisplayService
    {
        internal static async Task ShowIfAppropriateAsync()
        {
            ...
        }
    }

**Comment by crutkas** [comment]
100% agree.  We can do a hotfix on this.

**Comment by mrlacey** [comment]
There are exceptions where a method shouldn't **always** have this suffix but it is a common convention.
Surprisingly not covered by our [coding conventions](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md).

moving to v1.3 milestone as 1.2 has shipped and I don't think this is worth a hotfix

**Comment by mrlacey** [comment]
Ok, @crutkas just seen you want this for a hotfix. changing it back.

**Comment by crutkas** [comment]
Lets hot fix, we already have one going out the door.

**Comment by crutkas** [comment]
this fix is now in production.  Thanks @jlnostr for making us aware.
