### ISSUE TITLE
PostactionFormatter.cs filename issue

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#846]
PostactionFormatter.cs should be PostActionFormatter.cs.  Note the capital A.

low priority

**Comment by crutkas** [comment]
Actually this the only file I see with "PostAction" leading in the name as well.

**Comment by mrlacey** [comment]
Naming could be better but it's about formatting the description text to the right click merge output for post actions. 

Casing is not an issue in some branches ;)

**Comment by crutkas** [comment]
This looks fixed now in dev, i didn't fix this but looks corrected.
