### ISSUE TITLE
Audit "this" keyword usage

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#847]
### Repro steps

While doing #350, i saw usage of "this" keyword when it wasn't required.  We should audit usage of this.

**Comment by mrlacey** [comment]
For clarity, is this just in the generated code?

**Comment by mrlacey** [comment]
42 instances in 9 files (among templates) - none of which are necessary.

**Comment by mrlacey** [comment]
I guess we should have an automated test for this as well.
It's not something StyleCop can pick up (it has a rule to recommend them) so might need something else.

**Comment by mrlacey** [comment]
Without doing a blame I suspect these were mostly down to me (years of being forced to use `this.` means I don't even think about them) so I'll fix them.

**Comment by mrlacey** [comment]
![image](https://user-images.githubusercontent.com/189547/28443094-e89852b6-6dab-11e7-8146-6d1d6d0bf33a.png)

![image](https://user-images.githubusercontent.com/189547/28443179-6c47155c-6dac-11e7-8c79-3f64206667a8.png)

**Comment by crutkas** [comment]
Not blaming anyone here :)

Yes, this was for generated code

**Comment by mrlacey** [comment]
blaming myself
