### ISSUE TITLE
Why is Templatex called this?

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#849]
Why is this file called Templatex?  Should it be TemplateEx?  Or it looks to be doing Template Packing, unpacking and Signing, maybe call the file something in lines with that?

**Comment by mrlacey** [comment]
The class could also be made static as it only contains constants and static methods.

**Comment by crutkas** [comment]
i just did a bunch of clean up on this where we had dup code versus calling into one another. 

I feel like this should be in Core.IO.Packaging and called MstxFile

**Comment by crutkas** [comment]
@ralarcon and @sibille any ideas?

**Comment by ralarcon** [comment]
No special reason behind the scenes... I personally set the class name to Templatex as it was dealing with the packaging of templates (the suffix "x" is used in multiple places where packs things using _Open Packaging Conventions_ -docx, appx, etc.). You can rename it and move to the mentioned namespace...

**Comment by crutkas** [comment]
this is ready for someone to review, FYI
