### ISSUE TITLE
GeolocatorOnPositionChanged name in templates

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#857]
in the map template page, if we're doing this: `async void GeolocatorOnPositionChanged(Geolocator sender, PositionChangedEventArgs args)`

shouldn't the method be called Geolocator_PositionChanged?

**Comment by mrlacey** [comment]
We have inconsistency in this area and use both formats throughout the generated code.

MapPagePage contains `LocationServicePositionChanged`
MediaPlayerViewPage contains `PlaybackSession_PlaybackStateChanged`

Decide on which format you want and we'll use this issue to track making everything consistent throughout the generated code bases.

**Comment by crutkas** [comment]
good catch on the playback.

I think it should default to what VS autowires up.

**Comment by mvegaca** [comment]
Hi
There are two possibilities for naming event handler methods:
- Object_EventName
  - Used on code auto-complete tool.
  - It has less sense when the method is defined in XAML ( Loaded="Page_Loaded" )

- OnEventName
  - Used by framework on empty project defined methods

![image](https://user-images.githubusercontent.com/5556784/29603848-f14bcdc6-87e5-11e7-887a-be42ff98cc73.png)

Conclusions
- Event handlers normally use names that finish with -ing or -ed. [Sample list](https://msdn.microsoft.com/en-us/library/system.windows.controls.grid_events(v=vs.110).aspx)
- Code auto-complete tool use Object_EventName on C#
- Code auto-complete tool use OnEventName on XAML
- Default project template use OnEventName
- Default event handler methods defined as virtual in framework use OnEventName.

![image](https://user-images.githubusercontent.com/5556784/29604195-0b5c1260-87e7-11e7-9173-1d111486418c.png)

Said that my vote is for using OnEventName naming practice and apply to wizard and templates.

**Comment by crutkas** [comment]
I think we should verify what VS auto completes for that scenario the template is wiring up.  That way we mimic the exact code VS would wire up via a tab-tab.

**Comment by mvegaca** [comment]
Normalized to VS wired up values #1006

**Comment by mvegaca** [comment]
Templates updated on dev
