### ISSUE TITLE
What's new Prompt icon does not apply selection color

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#861]
Template icon does not apply selection color.

![image](https://user-images.githubusercontent.com/5556784/28459432-be9c1b0c-6e0d-11e7-8a95-6f6bbecf8119.png)

![image](https://user-images.githubusercontent.com/5556784/28459507-0cb2a3ba-6e0e-11e7-8bed-f52cb3c32bbc.png)

**Comment by crutkas** [comment]
dup of #796
