### ISSUE TITLE
CLA automation for .NET Foundation

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#866]
Jon said he can get this hooked up :)

Get CLA Automation enabled to ensure contributors can easily sign the Contribution License Agreement

**Comment by mrlacey** [comment]
bump?

**Comment by jongalloway** [comment]
Thanks, checking on it. CLA system doesn't see this repo, working with CLA team.

**Comment by mrlacey** [comment]
Can this be closed? 
CLA check is being done on PRs

**Comment by crutkas** [comment]
closing this, @jongalloway reopen if needed
