### ISSUE TITLE
Stylecop.json not in all projects

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#867]
### Repro steps

code\test\Templates.Test\FileEncodingTests.cs in dev branch has the wrong header.  I don't see a compile time warning.

Looks like inside references ->analyzers, a few projects aren't hooked up.

### Expected Behavior

wrong header should throw SA1636.

### Actual Behavior

In Templates.Test, nothing is thrown, others have same issue.

**Comment by crutkas** [comment]
oh wow, this is a lot deeper of a rabbit hole than i thought.  i thought we rolled stylecop on everything already.

**Comment by mrlacey** [comment]
Sorry, no. Only did the "important" projects.
The testing projects and localization tool will need integrating and probably need to use a different (larger) set of suppressions.

Have also raised #868 to review the current suppressions.

**Comment by crutkas** [comment]
any objection against me hooking some of this up, we can start doing custom suppression if needed for different projects or reenable if needed

**Comment by mrlacey** [comment]
>any objection against me hooking some of this up, we can start doing custom suppression if needed for different projects or reenable if needed

No. Go do it.
Note that the Localization tool is only in the tools solution.

**Comment by mrlacey** [comment]
To clarify. **Test projects are _very_ important.** It's just the strictness of StyleCop rules does not sit well with many test code conventions. This is why they were not originally included.
