### ISSUE TITLE
GenerationFixture.GetPageAndFeatureTemplates has statement that needs clarity

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#869]
inside: GetPageAndFeatureTemplates

var itemTemplates = GenerationFixture.Templates.Where(t => **t.GetFrameworkList().Contains(framework) && t.GetTemplateType() == TemplateType.Page || t.GetTemplateType() == TemplateType.Feature && !t.GetIsHidden());**

is this (framework and page) or (feature and hidden)

Assigned to @sibille as blame shows it is her function and want clarity before anything is done.

**Comment by mrlacey** [comment]
I think I've added some brackets to that query (and others like it) in the VB branch as I also had to add another clause and it got even harder to read. Also reformatted over multiple lines to improve readability.

From https://github.com/Microsoft/WindowsTemplateStudio/blob/VisualBasic/code/test/Templates.Test/GenerationFixture.cs

    var itemTemplates = Templates.Where(t => t.GetFrameworkList().Contains(framework)
                                          && (t.GetTemplateType() == TemplateType.Page || t.GetTemplateType() == TemplateType.Feature)
                                          && t.GetLanguage() == language
                                          && !t.GetIsHidden());

Yes, this kind of "tidying up" also made things harder for me in terms of merging but is hopefully beneficial in the long run.

**Comment by crutkas** [comment]
i'll create a dedicated branch for just this one adjustment for CR.

**Comment by crutkas** [comment]
turns out, this is part of dead end code.  referenced by GetPageAndFeatureTemplates and that has zero references

**Comment by mrlacey** [comment]
No! It is called by `GetPageAndFeatureTemplates` in `ProjectGenerationTest` which is called indirectly by the test framework. Notice the string name in the attribute here.

```
 [Theory, MemberData("GetPageAndFeatureTemplates"), Trait("Type", "OneByOneItemGeneration")]
public async void GenerateProjectWithIsolatedItems(.....
```

**Comment by crutkas** [comment]
Ah. Vs references didn't see that. Was looking at their reference count.
