### ISSUE TITLE
Order.cs class comment refers to Telerik DataGrid even when there is none

### ISSUE THREAD

**Issue by LanceMcCarthy** [Microsoft/WindowsTemplateStudio#870]
## Issue

WTS generates a sample class "Order.cs" with a comment at the top of the class: 

`// TODO WTS: This is used by the Sample Grid Data. Remove this once your grid page is displaying real data`

This makes sense when the project generated contains a RadDataGrid, however it could be confusing for projects that do not contain any DataGrid instances.

## Recommended fix

Reword the comment so that it's relevant for any scenario.

## System

VS 2017
WTS 1.2
Creators Update

**Comment by mrlacey** [comment]
Looks like this was overlooked when sample data was all refactored into a single service.

**Comment by crutkas** [comment]
Does removing the word "grid" solve the issue?
