### ISSUE TITLE
Cancelling a "Add new project" into exist project with WTS deletes directory

### ISSUE THREAD

**Issue by ray1997** [Microsoft/WindowsTemplateStudio#882]
Today, I'm just try to add new project but I did not notice it select Windows Template Studio
so I name it and click ok, But when wizard window show up I tried to cancel it, But I get use to how most app have cancel on bottom right corner. So I press it *twice* without looking that I'm press next and it creating new project. So I wait.. But it quite too long so I tried to check project folder for anything else. But then I saw my project folder has only "obj" and "bin" folder left.
And I tried creating new project again. And it still delete test project. :(

**Comment by crutkas** [comment]
For the WTS deleting everything, I can't reproduce this however.  Can you give step by step details on reproducing?  Remember a solution and a project are different items too.  You can't add a project to a project.

Trying to repro this, I did:

1. file->new and did a console app.
2. Right click on the solution
3. Add->New Project
4. select Windows Template Studio
5. click through wizard quickly
6. solution has console project and WTS project.

I used

- WTS Version: 1.2.17198.1
- Template Version: 1.2.17202.1

For our cancel button placement, that is 100% fair and valid feedback looking at how Visual Studio puts their OK versus cancel button.  I think that is a different issue and should be a logged as such.

**Comment by ray1997** [comment]
I'm afraid I can't reproduce it anymore.
I swear this is not a joke. I did lose my project files. On both real project and test project.

But maybe there is some other issue that not from WTS. All I can remember is I just install WTS along with Template 10 and Multilingual Toolkit and after I relaunch app. I just add new project (click on solution) And the just happen.

I'm sorry, Maybe it's something else. I'll close this issue now.

![sketch 1](https://user-images.githubusercontent.com/14814401/28588429-bdd879b4-71a4-11e7-8af2-2a6675be80b3.png)

**Comment by crutkas** [comment]
Ray, I'm not doubting you, i need more information so we can see.  Is the steps i did above what you did?  What was the other project(s) in your solution?

I can say this was a scenario I never tested as I always assumed file->new, not adding to an existing solution new project

**Comment by ray1997** [comment]
In my case both project is UWP project. And I added more UWP project by right click on my solution and add new project with WTS project
Some info about my project: There are two exist project in solution and both of them is also UWP project.
but that maybe not relate as test project has only 1 project but it still delete everything
More info: I was on Windows insider fast ring build 16241 and install visual studio community 2017 with version 15.2 (26430.16)
and WTS is version 1.2.17198 and template version is 1.2.17202.1

**Comment by ray1997** [comment]
Wait! I try again. And just open a project page for a few seconds. And press quit. And it show project is creating for a brief second. And this dialog show up

![sketch 1](https://user-images.githubusercontent.com/14814401/28591160-e481cfb6-71ae-11e7-9b5f-a3d8e3e66cc2.png)

And everything deleted

**Comment by crutkas** [comment]
ok, so you have an existing UWP app (was this generated via WTS?) and then you add another project using WTS, correct?

**Comment by ray1997** [comment]
Well. I record video and I reproduce this bug again.
https://1drv.ms/v/s!AsPczr3-hqPBiMBqBmDPaG21p3zs8Q

**Comment by crutkas** [comment]
ok, i know what is doing this now.  It is due to the cancelling.  I think the scenario you're outlining is a scenario we didn't think of and 100% we should have.

My gut says this is the cause:
https://github.com/Microsoft/WindowsTemplateStudio/issues/733
https://github.com/Microsoft/WindowsTemplateStudio/pull/766

We'll add in unit tests so it never happens again.

**Comment by crutkas** [comment]
@ray1997 seriously, great job helping track this bug down!

**Comment by ray1997** [comment]
@crutkas Glad to help. And hope everyone else not experience this bug. Because it suck. I just lost lots of change I made because of this bug. :(

**Comment by sibille** [comment]
Verified on pre-release
Wizard: 0.8.17248.4
Templates: 0.8.17248.4

**Comment by battenstudio** [comment]
The Bug is still there.
I Cancelled the creation of an uwp app with the wizard on the wizards second page.
Every Project was deleted only the bin and obj folders where remaining.
In Addition to it there was an empty App1 folder  in the solutions directory (in the windows explorer)

Wizard: 1.2.17198.1
Templates: 1.2.17202.1

**Comment by mrlacey** [comment]
@battenstudio It has been fixed in the code and will show up in the next released version. This will be version1.3 while you're still using 1.2. Hopefully, the new version (with this fix) will be released next week.
