### ISSUE TITLE
consolidate update and nuget references

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#887]
* **Overview:** solution uses multiple references.   this is related to #552 to get to .NET 4.7 cleanup.

**Comment by mrlacey** [comment]
recent references to this issue are an error

**Comment by crutkas** [comment]
Huh

**Comment by crutkas** [comment]
ah, i see what you mean now

**Comment by crutkas** [comment]
fixed

**Comment by crutkas** [comment]
per #981, Closing this pull request as it is replaced by #1011 and #1007
