### ISSUE TITLE
Cannot use the letter Ñ

### ISSUE THREAD

**Issue by Javier118** [Microsoft/WindowsTemplateStudio#888]
I cannot use the letter Ñ

**Comment by crutkas** [comment]
Where

**Comment by crutkas** [comment]
i just created using Ñ in a few spots, i need more info

**Comment by Javier118** [comment]
When putting TextBlock,: x:Name= "Fechaaño" tells me strange character, as if not accept the letter Ñ, then missing some symbol MDL2 for the menu Splitview.

**Comment by crutkas** [comment]
thanks for the additional info.  Was able to reproduce this now.  

A system made blank app allows this.  Our blank template (and others) throws an error.  Wonder if this could be related to #598 bug with BOM encoding.

**Comment by crutkas** [comment]
Yup, my gut says it is the BOM encoding issue.  

I just tried in our dev branch and it compiles.  If you run our ps1 script for Set-All-Text-File-Template-Encodings.ps1, that should correct your solution.

**Comment by crutkas** [comment]
I'm going to close this out as it doesn't happen in dev and we know we had a file encoding issue that is fixed in #598.  If you disagree, please reopen.
