### ISSUE TITLE
Suspend and resume doesn’t work in Template Studio 1.2

### ISSUE THREAD

**Issue by pekspro** [Microsoft/WindowsTemplateStudio#896]
### Repro steps

* Create a new project. I selected project type Blank, Framework Codebehind and the only feature I added was SuspendAndResume.
* Set a break point in App.OnLaunched. First time I launched the application LaunchActivatedEventArgs.PreviousExecutionState had the value NotRunning. 
* Selected Lifecycle Events and pick Suspend and shutdown. 
* Start the application again. When the application stopped at the break point LaunchActivatedEventArgs.PreviousExecutionState again has the value NotRunning, instead of expected Terminated.

## System

* **VS Version:** 15.2 (26430.16)
* **WTS Template Version:** 1.2.17198.1
* **Windows Build:** 15063.483

## Notes

I have also an older projected based on Template Studio 1.0 and in that version Resume works as expected. I haven’t any own code in any of these projects. Just let me know if anyone wants to look on these solutions.

I’m a bit confused and frustrated of this bug :-/. I'm not sure if the problem is in WTS or VS :-/. I have noticed similar problems with Template10, which can’t resume in Visual Studio 2017 but it works in Visual Studio 2015. See this issue: https://github.com/Windows-XAML/Template10/issues/1501. I have also reported this as a bug in Visual Studio (maybe that was incorrect): https://developercommunity.visualstudio.com/content/problem/50470/cant-resume-uwp-application-after-suspend-and-shut.html

**Comment by pekspro** [comment]
I tried to dig deeper into this, and after spending way too much time on this I have found something interesting. If you create a new Template Studio 1.2 project, and removes the files in the Style folder and the dependencies in App.xaml and MainPage.xaml resuming works again. It looks like if you have a ResourceDictionary in a project VS 2017 wants to build and deploy the project every time you launch, even if you have made no changes, which I guess removes the ability to resume an application. This is weird...

**Comment by crutkas** [comment]
@ralarcon this seems critical

**Comment by mvegaca** [comment]
New pull request created #987 with documentation and samples with how to implement suspend and resume feature.
Now it's easier to understand how to implement suspend and resume feature and how to test this feature debugging your project.

Video sample use suspend and resume to remember the playing second and restore video playing on that second.
Tasks App is near than a final implementation of an app that allows the user to create and complete tasks to do. The App use suspend and resume feature to remember the selected task and resume the app selecting this task.

I hope it helps.

**Comment by ralarcon** [comment]
@crutkas In summary, we have found that the issue is more related to understand how the suspend / resume works than having a bug in the templates. We had some work done to improve the documentation and @mvegaca have finished it. 

@pekspro can you check if this helps to understand the feature and how to test / evolve it?

**Comment by pekspro** [comment]
My conclusion is that when you have a Resource Dictionary in a project, VS2017 will rebuild and redeploy the project every time is launched. And as a side effect this will break suspend / resume debugging. See more details here (and vote :-):

https://developercommunity.visualstudio.com/content/problem/50470/cant-resume-uwp-application-after-suspend-and-shut.html

That said, using the setting “Do not launch, but debug my code when it starts” seems to be a clever work around. Well done figuring this out :-) I tested on some very basic projects and this seems to work well.

**Comment by mvegaca** [comment]
Documentation and sample are in dev, close Issue
