### ISSUE TITLE
Be consistent with paradigm usages (e.g. MVVM Basic ICommand)

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/WindowsTemplateStudio#897]
### Repro steps

1) Create an app with Navigation and a Settings page using MVVM Basic.
2) Look at the SettingsViewModel.cs file compared to the ShellViewModel.cs file.

In Settings:
```
        public ICommand SwitchThemeCommand { get; private set; }

        public SettingsViewModel()
        {
            SwitchThemeCommand = new RelayCommand(async () => { await ThemeSelectorService.SwitchThemeAsync(); });
        }
```

In Shell:
```
        private ICommand _stateChangedCommand;
        public ICommand StateChangedCommand
        {
            get
            {
                if (_stateChangedCommand == null)
                {
                    _stateChangedCommand = new RelayCommand<Windows.UI.Xaml.VisualStateChangedEventArgs>(args => GoToState(args.NewState.Name));
                }

                return _stateChangedCommand;
            }
        }
```

The Settings model is more succinct, but the Shell model is better encapsulated for initialization.  Whichever one is "preferred" it should at least be consistent in the generated code.

## System

* **VS Version:** VS 2017 Update 2
* **WTS Wizard Version:** 1.2
* **Windows Build:** RS2

**Comment by crutkas** [comment]
agreed.  auditing this is going to suck

**Comment by crutkas** [comment]
actually not as bad as i thought.

- MasterDetailDetailViewModel (StateChangedCommand)
- MasterDetailViewModel (StateChangedCommand and ItemClickCommand)
- SettingsPageViewModel (SwitchThemeCommand)

**Comment by crutkas** [comment]
getting this fixed, running unit tests
