### ISSUE TITLE
Let view models be aware of navigation

### ISSUE THREAD

**Issue by pekspro** [Microsoft/WindowsTemplateStudio#898]
I would like to see some support of navigation events in view models. I’m using Template10 in some of my projects that supports this. Every time a page is navigated to or from my view model (if it’s set as DataContext on the page) get a callback. And in these callbacks a dictionary is provided which I can use to save/restore the view models state to support suspend/resume.

**Comment by mrlacey** [comment]
This has been asked for before as an addition to MVVM Basic but not something we're going to add there.

You haven't mentioned a framework explicitly but from a WTS perspective:
Doesn't apply to Code-Behind
Not applicable to MVVM Light
Deliberately left out of MVVM Basic as that implementation is intentionally as small as possible.

We're currently working with a number of other frameworks which do support ViewModel Navigation and the ability to use one of them will be the best approach forward for this issue.

For reference, work/discussion is ongoing with these frameworks (links to issues):
[Prism](https://github.com/Microsoft/WindowsTemplateStudio/issues/304)
[Caliburn.Micro](https://github.com/Microsoft/WindowsTemplateStudio/issues/438)
[Template10](https://github.com/Microsoft/WindowsTemplateStudio/issues/446)

If you can help bring support for any of these to WTS your help will be greatly appreciated.
