### ISSUE TITLE
SQL Server Support

### ISSUE THREAD

**Issue by andreweberle** [microsoft/WindowsTemplateStudio#900]
## For new Features:
I think if there was an option to add a WCF Service, that would be awesome as it would save so much time. If it was to the point where we only had to add our connection string and query that would be amazing too.

**Comment by crutkas** [comment]
do you want a sql client item or wcf?  title and description differ.  This also is related to #134 on how we actually implement this.  

How should this be included in a template?  What would be "success" for you?

**Comment by andreweberle** [comment]
An SQL client if possible so we can connect to our own servers over the internet, i could be wrong but I thought this was only possible by including a web service?

**Comment by crutkas** [comment]
Come Fall Creators Update with .NET Standard 2.0, SqlClient is included :)

**Comment by mrlacey** [comment]
Also X-Ref #396 
It's not just a case of getting access to data, what, if anything, should WTS do with that data?

**Comment by crutkas** [comment]
I agree.  I think maybe what we should do there is for sample data is maybe create a doc page.  not sure how much we can do.  @mahoekst any opinions?

**Comment by mahoekst** [comment]
Not sure how a template would help here? Do we need a 'master detail' page for example which binds to some dummy objects you can later hookup to a REST/WCF service or SQL EF thing?

**Comment by mahoekst** [comment]
But you risk copying what EF does for you today

**Comment by crutkas** [comment]
we already bind to a sample data service but all data is static.

**Comment by gcaughey** [comment]
I really think providing the dummy that developers can change makes the most sense. Developers may want to write their won Load methods for the classes that will get bound.

**Comment by crutkas** [comment]
I like the idea behind creating a "Data" page and talk about the options such as SQL and Restful data services and provide quick samples on how to write something up in the docs.

**Comment by gcaughey** [comment]
Good idea.

**Comment by XamlBrewer** [comment]
Good idea. Options could be: SQL Client, SQLite, and REST.

**Comment by OtisRanger** [comment]
Depending on what level all of this is being pitched, I would think that a happy medium is the place to go whereby you could have a gui front end that allowed you to select if you wanted all of the classes set up. I am not one for plagiarism but I envisage it something like Radzen have done
![ms-sql-auto](https://user-images.githubusercontent.com/31215901/29556706-8c312516-871e-11e7-8987-edb003418ad8.gif)

**Comment by crutkas** [comment]
@OtisRanger we [WTS] wouldn't be doing that anytime soon.  If that were to be built out, my gut would think that would be directly part of VS or a different extension, not WTS itself.  WTS doing that is death by a million cuts and it would never be perfect.  Someone else that specialized in doing that would be able to do a better, supported manner.  Our generated code then would have to match each target framework as well, it comes a very large engineering task in it self as well.  

Also remember, WTS is a small team inside MSFT with lots of fantastic community support.  Right now, there are many other items that are higher priority for us to build out.

Our solution may actually be to recommend a 3rd party extension to enable just want you're asking for in our documentation.  If you have a solid recommendation for something, 100% please tell us!

If this is something you feel strongly about and feel it should be in, we are open source and accept community based contributions.  Lets work together to spec it out first before implementation.

**Comment by mrlacey** [comment]
If adding this option (data from SQLClient) we need a way to ensure that there will be a suitable database available to provide (sample?) data.

Could we include a script to generate the appropriate tables and data in an existing database?   
We'd also include TODO comments to set the connection string and possibly some more documentation.  

Would assuming an existing DB be sufficient, or should we do more? (if so, what?) Can we assume that people will read a description that says "load data from an **existing** SQL Server database"?

**Comment by odyright** [comment]
Hello,
Any progress ? regarding the way we can manage connectionString to SQL server?

**Comment by mrlacey** [comment]
@odyright no promises but I'm hoping this'll be done in the next 2-3 months ;)

**Comment by mrlacey** [comment]
Need this to work with local & Azure hosted instances

**Comment by mrlacey** [comment]
Moved to 2.3 as this should really be done after we move to multi-project solutions and that won't happen until 2.3 at the earliest.

**Comment by crutkas** [comment]
do we have a crisp game plan for this for execution?  would be a cool feature to add in but needs to be done smartly and correctly

**Comment by gcaughey** [comment]
This is a problem I had with my Build and Ignite SqlClient demos from last year. Even though we provided what we thought were complete directions how to set up a test Northwind database and included the Northwind database creation script, I don't think most people went to all that trouble to try the sample that needed it.

**Comment by gcaughey** [comment]
Here's a link to the Build SqlClient sample showing the instructions we provided: https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/SQLServer

**Comment by OtisRanger** [comment]
@gcaughey Your example is good in the sense that it shows that you can, ultimatly, link to a SQL db but it really isnt a practical\real world solution; well not for me anyhow. I did follow your example and run it but as soon as I did I knew that it wouldn't work for us. 

In the example that I showed above, the only downside to it was that it would only connect via SQL Authentication and not Windows. The Radzen guy(s) have now sorted this out and it has become the top contender for us to use. 

Please don't give up guys, I really would like to see this work.

**Comment by mrlacey** [comment]
should this be:

a) Straight SQL Server access (via a `SqlConnection`?
b) SQL Server access via EntityFramework?
c) Both?

**Comment by mrlacey** [comment]
Adding this with an example query that returns data from Northwind that matches the response from `SampleDataService.AllOrders()`. This will allow testing the generated app with data from a DB without having to change anything apart from the service being used and the connection string.

**Comment by mrlacey** [comment]
Starting with just "Straight SQL Server access (via a SqlConnection)".
Can add more in the future if/when required.

**Comment by mrlacey** [comment]
Many data related pages currently load their data in the constructor.
This is fine with the sample data as it's all in code/memory and so very fast. In reality, data may come from disk/DB or over a network and so be subject to performance impacting delays. 
For this reason, I think we should stop loading any data in constructors and instead load it async after having navigated to the page.
Additionally, impacted pages should also have an ability to indicate that data is loading with an appropriately displayed ProgressRing.

Thoughts, comments, suggestions?
_Can make this a separate issue if deemed appropriate._

**Comment by mrlacey** [comment]
![image](https://user-images.githubusercontent.com/189547/57011689-df11ea00-6bfa-11e9-9b57-eb959a7cd9a5.png)

**Comment by mrlacey** [comment]
verified in 
Templates version: 0.20.19140.3
Wizard version: 0.20.19138.1
