### ISSUE TITLE
Contribution link is not working

### ISSUE THREAD

**Issue by GeertvanHorrik** [Microsoft/WindowsTemplateStudio#910]
See this page:

https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/templates.md

**Comment by mrlacey** [comment]
Also on 
https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/getting-started-extension.md
https://github.com/Microsoft/WindowsTemplateStudio/blob/master/docs/getting-started-developers.md

**Comment by crutkas** [comment]
merged into master, need to backport to dev

**Comment by crutkas** [comment]
https://github.com/Microsoft/WindowsTemplateStudio/pull/915 now need someone to approve this PR
