### ISSUE TITLE
Update generated projects to include latest version of json.net

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#932]
Newly generated projects still target 10.0.2 but 10.0.3 has been out for a couple of months and includes bug fixes.
Nothing critical in the update but I don't like it when creating a new project and the NuGet manager tells me there are things to update.

**Comment by crutkas** [comment]
https://github.com/Microsoft/WindowsTemplateStudio/pull/889 has that included in it.

**Comment by crutkas** [comment]
Crud, no it doesn't, that is only the wizard solution.  I'm a dirt liar

**Comment by crutkas** [comment]
ok, you got dibs on this as you assigned it to yourself :)

**Comment by mrlacey** [comment]
verified in dev-nightly
wizardVersion="0.14.17228.65001"
templatesVersion="0.14.17228.1"
