### ISSUE TITLE
Master Template updates do not kick off a CI build.

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#936]
Validated going into VSO, no build was kicked off so PR's are stuck in a pending state.

Does this also affect Dev?

**Comment by crutkas** [comment]
this is related to #805

**Comment by ralarcon** [comment]
I have created a build to generate pre-release versions which is launched everytime there are changes in master branch. The new build publish the templates and publish the pre-release vsix.
