### ISSUE TITLE
Speeding unit tests on server up

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#946]
not sure if this is possible but could help speed stuff up. have the tests segmented by core, framework + language.  Have each framework and language then would paralleled on the farm and if all succeed, then publish.

**Comment by mrlacey** [comment]
X-Ref #831

**Comment by mrlacey** [comment]
Also, X-Ref #497

**Comment by crutkas** [comment]
i see this isn't the first time i've brought this up :)

**Comment by crutkas** [comment]
Removing these groupings:

- GenerateAllPagesAndFeatures
- GenerateProjectWithIsolatedItems
- GenerateEmptyProject

Brought us to 148 total tests, from 319

**Comment by crutkas** [comment]
while we lost a bit of coverage from removing isolation, I believe #497 and #957 will cover fixing stuff.
