### ISSUE TITLE
GenException on new machines -> localhost

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#950]
Microsoft.Templates.UI.GenException: 'Dependency template wts.Feat.SampleDataService not found for framework CodeBehind.'

I've seen this a few times after the VB merge (not calling that out directly) but on first time run, it appears to throw.  doing another full cycle, it works perfectly.

I'm not sure if this only afflicts local or everything

**Comment by mrlacey** [comment]
What constitutes a "first run"? and "local"?

**Comment by crutkas** [comment]
Local == my dev box
First == select new branch and F5

I hit this issue twice so far, rerunning the wizard causes it to not appear again.

**Comment by mrlacey** [comment]
I couldn't repro with dev branch, NavPanel project, and adding Grid page

**Comment by crutkas** [comment]
next time i'll try to grab the mstx when i see it.

The weird thing is the first screen works but then throws the exception going to the next screen.

**Comment by ralarcon** [comment]
Can we close this? looks it is not reproduced anymore.

**Comment by ralarcon** [comment]
Closing now.
