### ISSUE TITLE
Provide a commandline interface to the wizard functionality

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#953]
There are a number of testing scenarios where it would be really useful to have a commandline interface to the wizard.
I'm sure there are other potential uses too.

Haven't thought about this too much and it might not even be something public at first if it just helps with testing.
I'm not saying it'd be a simple interface but would be useful.

This may also work as an extension to VSEmulator...at least for testing purposes.

Very low priority, I'm just putting this out there to see what others think

**Comment by crutkas** [comment]
We actually had this at the start

**Comment by mrlacey** [comment]
As part of #1869, some command line functionality has been added to VsEmulator that could conflict with this.

Gonna shut this down in the hope that #1100 removes the need for this as it should be easier to use than a complex set of command line commands.
