### ISSUE TITLE
Have a generator test that runs store validation/WACK against the generated project

### ISSUE THREAD

**Issue by mrlacey** [Microsoft/WindowsTemplateStudio#965]
X-Ref #907 

We should be totally confident that the generated project will get to the store and that we don't do anything that could prevent this.
This should include catching anything related to 3rd party libraries we add references to.

Not even sure how to do this (or if possible--as haven't looked) as I expect this will require associating with a dev center app entry. Will require some investigation but I think this is definitely worth having.

**Comment by crutkas** [comment]
great idea

**Comment by mrlacey** [comment]
Doing now as I want to run this against the VB generated projects to verify their completeness.

**Comment by mrlacey** [comment]
Closing as merged into dev. It isn't part of wizard or templates and so doesn't need to wait for a build to verify it.
