### ISSUE TITLE
Click Cancel Button on the Wizard blows up VS2017 15.3

### ISSUE THREAD

**Issue by EdiWang** [Microsoft/WindowsTemplateStudio#967]
### Repro steps

1. Open An Exisiting Solution.
2. Right Click on the Solution file and Add a new Template Studio project.
3. When the first screen of the wizard loaded, click "Cancel" button.

### Expected Behavior

Nothing would happen to the current IDE screen.

### Actual Behavior

An error dialog show up, says:

"The process cannot access the file 'storage.ide' beacuse it is being used by another process."

## System

* **VS Version: 2017, 15.3**
* **WTS Wizard Version:1.2.17198.1**
* **WTS Template Version:1.2.17202.1**
* **Windows Build:10.0.15063.540**

**Comment by crutkas** [comment]
I can't reproduce this.  Not saying it isn't happening.

Does it happen every time you do this?

**Comment by EdiWang** [comment]
@crutkas , I am able to reproduce it every time on both of my machines. I recored a viedo for that, please check "https://www.youtube.com/watch?v=TDyb3foOq7g". 

And it is happening to VS2017 15.3.1 also, I got this VS update just this morning.

**Comment by crutkas** [comment]
@EdiWang that video was SUPER helpful.

@ralarcon any ideas?

**Comment by ralarcon** [comment]
Taking a closer look...

**Comment by mrlacey** [comment]
I suspect this is related to a VS extensibility reference issue as using the 1.2 wizard and VS 15.3

**Comment by crutkas** [comment]
Nightly looks to have this fixed.
