### ISSUE TITLE
Page: Signature page

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#974]
A page with Ink that can capture a person's signature and store it into an object.

xref #799

**Comment by milazzom** [comment]
For this item, would storing the object equate to persisting it on disk as an image, or is there a preference to store this in memory as a base64 representation or something similar?  

I've been working on a reference inking app with a page that handles general inking, a page for capturing a signature, and a page for annotating an image with ink.

**Comment by crutkas** [comment]
not going to do this.  this is a control that would be more in the terms Windows Community Toolkit
