### ISSUE TITLE
FCU: Adjust name spaces

### ISSUE THREAD

**Issue by crutkas** [Microsoft/WindowsTemplateStudio#983]
In fluent branch, there is conditional XAML that references rs2 and rs3, 
Lets change those to Win10CU, Win10FCU or something along those lines, not internal code names :)

xmlns:rs3="http://schemas.microsoft.com/winfx/2006/xaml/presentation?IsApiContractPresent(Windows.Foundation.UniversalApiContract,5)"

**Comment by crutkas** [comment]
@ralarcon this should be part of the Fluent CR for when we merge

**Comment by sibille** [comment]
Docs (https://github.com/Microsoft/WindowsTemplateStudio/blob/Fluent-Design/docs/Fluent_PerspectiveParallax.md) use FCU as namespace. @Clint, I'll use FCU and CU in code too, without Win10 in the namespace. Ok from your side?

**Comment by mrlacey** [comment]
Just curious about the purpose of that fluent/perspectiveparallax doc. It doesn't appear to have anything specific to WTS in it. Will it have? Or is it an attempt to provide better/alternative docs to the official ones?

**Comment by ralarcon** [comment]
As far as I have seen it is a generic info about new features. Probably it will need updates to reflect what we have added in WTS.

**Comment by mvegaca** [comment]
Checked
Wizard: 0.14.17286.65001
Templates: 0.14.17286.1
