### ISSUE TITLE
StyleCop rule CA2214 violations

### ISSUE THREAD

**Issue by ralarcon** [Microsoft/WindowsTemplateStudio#988]
The `StyleCopPlusLocalTemplatesSource` and `ProjectTemplateGeneratorBase`clases are violating the rule [CA2214](https://msdn.microsoft.com/library/ms182331.aspx)

@mrlacey I would like to dobule check with you so I'm ignoring the warings by now until further discusion to check if a code refactor is needed.

**Comment by ralarcon** [comment]
The class `BaseFileViewModel` also violates this rule.

**Comment by crutkas** [comment]
I'm fine pushing this back to 1.4 FYI

**Comment by mrlacey** [comment]
To save me having to look this up again next time I view this

[CA2214: Do not call overridable methods in constructors](https://msdn.microsoft.com/en-us/library/ms182331.aspx)

**Comment by mvegaca** [comment]
Fixed on #1230
