### ISSUE TITLE
Accessibility: Speech recognition

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/WindowsTemplateStudio#990]
Wizard must be usable using speech recognition

**Comment by crutkas** [comment]
isn't that narrator support?  Or it must use this?  Feels like a large task

**Comment by ralarcon** [comment]
Nop, this is speech recognition: https://support.microsoft.com/en-us/help/14213/windows-how-to-use-speech-recognition... the ability to handle the computer by using voice.

**Comment by mvegaca** [comment]
Verified that wizard works with speech recognition using show numbers functionality, including create a full configurated project with pages and features and reordering features in the project summary.

**Comment by mvegaca** [comment]
Testing on VS Extension from nightly I've seen that in VS does not work speech function "show numbers". When I said show numbers, speech recognition software does a "beep" sound and does nothing.
WTS extensions still being usable from speech recognition by tab order navigation from controls like a keyboard.
