### ISSUE TITLE
Improve realism of automated tests and item name reuse

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsTemplateStudio#995]
As discovered as part of #506, `StyleCopGenerationTestsFixture` uses a single collection of used names in projects across the entire fixture, rather than being per project which is the reality for real project generation.

The issue here is that if the fixture created three projects and each should include a page called "Blank", the generated projects would actually contain "Blank", "Blank1", & "Blank2".
There are two issues with this:
1. It doesn't truly represent what would be generated outside of a test.
2. It doesn't allow a feature to include a page with a fixed name. (Such as an example page for feature usage.)

The following should be per test instance, not per fixture.
`private List<string> _usedNames = new List<string>();`

Also, need to check if this impacts more than just StyleCopGenerationTestsFixture.

**Comment by ralarcon** [comment]
@mrlacey we don't see this a priority right now. Could we move it to the backlog?

**Comment by mrlacey** [comment]
I can't remember the details now but half-recall this causing me an issue when I raised it.
Ok in backlog but can move it if becomes a bigger/wider issue.

**Comment by mrlacey** [comment]
I don't believe there is any value in keeping this open, having survived for three years since the issue was first encountered.
The value of making this change seems so small that I can't imagine it ever being done
